### ISSUE TITLE
copy.deepcopy does not work on Circuit objects

### ISSUE THREAD

**Issue by max-radin** [quantumlib/Cirq#1003]
Calling `copy.deepcopy` on a `Circuit` object fails because the `__deepcopy__` method of a `Circuit` does not take a second argument. Also, it looks like this method is actually attempting to perform a shallow copy.

Would it make sense to get rid of the `__deepcopy__` method and just use the default deep copy operation?

**Comment by Strilanc** [comment]
Moments are sorta-kinda intended to be immutable; that's why the deep copy looks like a shallow copy. But perhaps if someone is calling deep copy they're violating that expectation (which isn't really _written_ anywhere...) so point taken.
