### ISSUE TITLE
Schedules.md has a bad circuit diagram but isn't failing the snippet tests

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1006]
Look for:

```
print(circuit)
# prints:
# (0, 0): ───Z───X───
#            │
# (1, 0): ───Z───────
```

Z-Z is not how CZs are printed anymore.

**Comment by vtomole** [comment]
How do I self-assign to issues?

**Comment by Strilanc** [comment]
I gave you "collaborator: read" access to the repo, but that may not include the ability to assign issues. If you can, you click on `Assignees` in the right hand column and set it to yourself.

If you just leave a comment saying "I am working on this issue, please assign me", that is sufficient for now. I'll think about some kind of workaround, e.g. CirqBot watching for particular comments or good 'ol complaining to github that read access should include the ability to self-assign unassigned issues.

**Comment by vtomole** [comment]
> may not include the ability to assign issues

Yup. That only works for personal repos, not organizations'. Manual or CirqBot is fine.
