### ISSUE TITLE
Add `_phase_by_` magic method to `ControlledGate`

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1013]
Comes after https://github.com/quantumlib/Cirq/issues/947

The logic is as follows: if the qubit index is 0 (the control), the operation is returned unchanged. If it is larger then we delegate to phasing the sub gate with `cirq.phase_by` and a default result of NotImplemented. If it's NotImplemented, we return NotImplemented. Otherwise we return a controlled gate with the phased sub gate.

**Comment by smitsanghavi** [comment]
I can take this
