### ISSUE TITLE
Add `dtype` parameter to SimulatesFinalWaveFunction and SimulatesIntermediateWaveFunction

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1042]

**Comment by dabacon** [comment]
dtype is currently on the simulator classes themselves.  The `mux` methods pass them in while being constructed.

**Comment by dabacon** [comment]
Ah closed this because I don't think

**Comment by dabacon** [comment]
oop accidentally closed

**Comment by dabacon** [comment]
There was a need for this in the xmon simulator, but that is gone.  I think the simulators all take a dtype now, and this is used in the mux methods.
