### ISSUE TITLE
Add a "standard test battery" for new gates, use it on old gates

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1053]
There is a lot of repetition in tests between gates. This leaves a lot of room for accidental omission. Some of this repetition could be reduced by having a standard set of tests that a gate must pass, such as "the decomposition is consistent with its unitary matrix".

Here's roughly what I was thinking:

```python
def assert_implements_consistent_protocols(
        val: Any,
        *,
        qubit_count: Optional[int] = None,
        exponents: Sequence[Any] = (1,
                                    -0.5,
                                    0.5,
                                    -1,
                                    0.25,
                                    -0.25,
                                    0.1,
                                    value.Symbol('s'))):
    """Checks that a value is internally consistent and has a good __repr__."""

    _assert_gate_meets_standards_helper(val, qubit_count)

    for exponent in exponents:
        p = protocols.pow(val, exponent, None)
        if p is not None:
            _assert_gate_meets_standards_helper(val**exponent, qubit_count)


def _assert_gate_meets_standards_helper(val: Any, qubit_count: Optional[int]):
    import cirq.testing  # HACK: actually should do file-level imports

    cirq.testing.assert_equivalent_repr(val)
    cirq.testing.assert_decompose_is_consistent_with_unitary(val)
    cirq.testing.assert_phase_by_is_consistent_with_unitary(val)
    cirq.testing.assert_apply_unitary_to_tensor_is_consistent_with_unitary(
        val, qubit_count=qubit_count)
```

This issue is to cover perhaps a few more cases, and to then incorporate this into the `cirq.testing` namespace

**Comment by kevinsung** [comment]
In your example why does `val` have type Any instead of cirq.Gate?

**Comment by Strilanc** [comment]
New test to include in the battery:  `_eigen_shifts` must be consistent with `_eigen_components`.

**Comment by Strilanc** [comment]
New test to include in the battery: `_qasm_` must be consistent with `_unitary_`

**Comment by Strilanc** [comment]
New test to include, specific to EigenGate: check if there is a global_shift parameter in the constructor and, if so, vary it to a few values.

**Comment by Strilanc** [comment]
A bit sooner than that, actually. This is release blocking.

**Comment by Strilanc** [comment]
Oops, wrong spot

**Comment by kevinsung** [comment]
What to do with gates for which QASM output just doesn't work (i.e. some ControlledGates)?

**Comment by Strilanc** [comment]
We should detect the not-implemented situation and default to 'vacuously correct'. This involves re-implementing some of the logic in QasmOutput, unfortunately.

**Comment by kevinsung** [comment]
Actually, `assert_qasm_is_consistent_with_unitary` should be using the line
```
    qasm = protocols.qasm(op, qubits=qubits[::-1])

```
instead of the current one,
```
    qasm = str(circuits.QasmOutput(op, qubits[::-1], precision=10))
```
This currently causes
```
TypeError: _qasm_() got an unexpected keyword argument 'qubits'
```
which we need to fix.

**Comment by kevinsung** [comment]
However, the `qubits[::-1]` thing is quite confusing. Should we be changing the order of qubits in the `_qasm_` methods?
