### ISSUE TITLE
Replace usages of `cirq.decompose_once` with `cirq.decompose`

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1061]
There is some leftover code throughout cirq that manually performs the recursion/iteration commonly associated with decomposition, instead of delegating this task to `cirq.decompose`. Such code should be updated.

This applies to almost every instance of `cirq.decompose_once` in the code base that's not in tests or the documentation.

For example, `cirq/circuits.expand_composite.py` uses `protocols.decompose_once` (the internal name for `cirq.decompose_once`) in a recursive way that should instead be written using `protocols.decompose`.

This issue is a bit advanced for a "good first issue", in that it requires carefully reasoning about recursion in the context of existing code. But it doesn't require much knowledge of how cirq works other than these specific methods and the code in the individual files so I've marked it such.

**Comment by Strilanc** [comment]
Based on the errors, you probably forget to set `allow_partial_czs=False` somewhere. If you create a PR I can spot where the mistake is.

**Comment by smitsanghavi** [comment]
I think this can be closed now. I don't see any non-test non-documentation uses of decompose_once anymore. 
Or is this issue supposed to cover decompose_once_with_qubits too?

**Comment by Strilanc** [comment]
You're right, I think this is done. Good work!
