### ISSUE TITLE
Remove numerous PendingDeprecationWarning instances in pytest2

### ISSUE THREAD

**Issue by Ashalynd** [quantumlib/Cirq#1070]
There are currently numerous warnings being printed when pytest2 runs, looking like this:

```
cirq/linalg/decompositions_test.py::test_map_eigenvalues_identity[matrix0]
  /tmp/test-cirq-py2-kjeiw02o/.test_virtualenv_py2/local/lib/python2.7/site-packages/numpy/matrixlib/defmatrix.py:68: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
    return matrix(data, dtype=dtype, copy=False)
```

The files for which that happens:

cirq/linalg/decompositions_test.py
cirq/ops/matrix_gates_test.py
cirq/sim/state_test.py
examples/examples_test.py

**Comment by Strilanc** [comment]
I've also noticed this happening, but couldn't find `np.matrix` being used anywhere in cirq. I assumed it was something internal to numpy, but yes someone should look at this a bit more closely.
