### ISSUE TITLE
Speed up KAK decomposition

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#1071]
The following code constructs a circuit with 1140 common gates and then calculates the time it takes to run the Xmon optimization and Xmon gate conversion (separate procedures).
```
import time
import cirq


qubits = cirq.LineQubit.range(20)
circuit = cirq.Circuit.from_ops(
    [cirq.H(q) for q in qubits],
    [cirq.ISWAP(qubits[i], qubits[i+1]) for i in range(0, 18, 2)],
    [cirq.CNOT(qubits[i], qubits[i+1]) for i in range(1, 19, 2)]
)
circuit *= 30

print(len(list(circuit.all_operations())))
print()

t0 = time.time()
_ = cirq.google.optimized_for_xmon(circuit)
t1 = time.time()
print(t1-t0)
print()

t0 = time.time()
cirq.google.convert_to_xmon_gates.ConvertToXmonGates()(circuit)
t1 = time.time()
print(t1-t0)
```
On my machine, optimization took 12.6 seconds and conversion took 2.7 seconds.

**Comment by vtomole** [comment]
@dstrain115 Hey, how's this going?

**Comment by dstrain115** [comment]
From the latest code commit, it seems we have gotten about a 50% improvement so far.  I was starting to find it more and more difficult to continue improving this, without cutting out all the matrix decompositions.  I am open to suggestions.

From #1233 :

The cumulative savings of this change, in combination with the previous
fixes has decreased conversion from 2.7 seconds to 1.25 seconds and
optimization from 12.6 seconds to 5.4 seconds.

**Comment by Strilanc** [comment]
I think the next step for this would be to move the kak decomposition into C or Cython (which requires incorporating them into the build process), because that seems to be the huge bottleneck.

**Comment by balopat** [comment]
Merging #2070 here: we could also add shortcuts to two-qubit gates with known decompositions.

**Comment by MichaelBroughton** [comment]
This seems to have gone stale with the new transformers API. Can we close this @kevinsung and re-open for transformers ?

**Comment by kevinsung** [comment]
Sure, I'm not familiar with the transformers API so I can't write a new issue for it, but feel free to close this one either way.
