### ISSUE TITLE
When docstrings contain something like "`cirq.X`", turn it into a hyperlink when generating docs

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1072]
This is a pattern I've been using more and more when writing docstrings, and it would be great if it was actually a link on the documentation website.

**Comment by balopat** [comment]
This sounds like a great improvement. As far as I'm aware this doesn't exist in devsite yet, but would be cool. We should make sure that this gets solved with a devsite compatible way. @lamberta have you seen anything like this working on the TF devsite?

**Comment by balopat** [comment]
In fact this is working from docstrings already on the new site. 🎉  I thought first that this would be something picked up from regular text as well. I guess that would be a pretty large effort. Closing.

**Comment by lamberta** [comment]
We support this when generating the prod site :) But doesn't work in previews, afaik.

If you wrap the complete symbol in backticks it will autolink to the reference page. The shortname for the module is defined in your `build_docs.py` script and should already be enabled: https://github.com/quantumlib/Cirq/blob/master/dev_tools/docs/build_api_docs.py#L46
