### ISSUE TITLE
3d diagrams for circuits

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1075]
When working with qubits laid out in a 2d grid, it can be very helpful to see the circuit structure in 3d space.

I'm not sure what exactly the output should be here. Should a window open up with a 3d viewer, ala matplotlib plots? Should we export a model file for some 3d format?

I don't want anything particularly complicated for the diagrams themselves. Basically a text diagram in 3d space, with the symbols as textures on cubes. There is a clear positioning implied for GridQubit. For other qubits, sort them and put them into a big long line (or just raise an error).

**Comment by balopat** [comment]
[An RFC](https://docs.google.com/document/d/16LybO9bNqL3LaIy1pZCJQXSPvKs5g3IqKkkE3efqM8U/edit) is proposed for Typescript development - adding it here for sake of completeness.

**Comment by dabacon** [comment]
I think this is now implemented in cirq-web?  Putting on triage/discuss to see if we want to close at Cirq sync

**Comment by vtomole** [comment]
This has been done. See: https://www.youtube.com/watch?v=pgyCEY8oMYA
