### ISSUE TITLE
Should we still force keyword arguments in _PowGate initialization?

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#1079]
There's only one unit possible now.

**Comment by Strilanc** [comment]
I haven't really decided which way I want to go on that. For the most part users shouldn't be calling those methods anyways, they should be using the more convenient `cirq.X**0.5` or `cirq.Rx(np.pi/2)`. So I'm not too worried about making it convenient to call them.

**Comment by vtomole** [comment]
> There's only one unit possible now.

Isn't it two? `exponent ` and `global_shift`

https://github.com/quantumlib/Cirq/blob/1e6436c136dbe94a62970fa64692d27ed8f919c8/cirq/ops/eigen_gate.py#L65

**Comment by vtomole** [comment]
Anyway, these are the comments on the commit that introduce it

```
Use just '*' to force keyword arguments (#537)
    
    Casey pointed this out to me. It's significantly better because:
    - it doesn't require a docstring for the argument
    - it doesn't need an assert line
    - it gives a better error message to the user
```
I agree.

**Comment by dabacon** [comment]
I think the argument that it doesn't require a docstring is not a positive one.

**Comment by kevinsung** [comment]
@vtomole What I mean is that one is no longer allowed to specify the rotation in units of rads or degrees. There is only one choice: specify the exponent.

**Comment by vtomole** [comment]
@kevinsung Thanks for the clarification. In that case i agree.

**Comment by Strilanc** [comment]
I like that we continue to force the keyword, because I'm still not happy with the API here. It insulates us from making subtle breaking changes, where the first argument becomes different.

**Comment by kevinsung** [comment]
I think that's fine.
