### ISSUE TITLE
Make a noisy sampling simulator using `_channel_`

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1086]
Using `cirq.channel` you can get the krauss operator / quantum operator ( https://en.wikipedia.org/wiki/Quantum_operation ) for each operation in a circuit. You can then use this to update a density matrix state (I think). Start with a specified state, apply all the operations, sample from the result. Find optimizations to make it faster in special cases, such as using `cirq.unitary` first.

**Comment by Ashalynd** [comment]
Question: does it make sense to have an assumption that the same specific noise operator (e.g. amplitude damping) would apply to each operation in the given circuit?

**Comment by kevinsung** [comment]
Then this issue isn't really about noise at all then, but rather implementing simulation of channels, right?

**Comment by Ashalynd** [comment]
So should this issue be based on assumption that every operation already implements [SupportsChannel](http://go/gh/quantumlib/Cirq/blob/master/cirq/protocols/channel.py) class? 

If yes, then adding this dependency seems like a prerequisite to this one. 

(E.g. assume that the chosen simulation device would somehow transform the abstract operations from the circuit "blueprint" into channels). Does it make sense?

**Comment by kevinsung** [comment]
Perhaps the way to go is to define a `SupportsApplyChannel` protocol analogous to `SupportsApplyUnitary`. Any implementation of SupportsApplyUnitary should naturally transfer over to SupportsApplyChannel.

**Comment by c-poole** [comment]
`DensityMatrixSimulator` exists. Does that satisfy the conditions for closing this issue @Strilanc ?

**Comment by dabacon** [comment]
Closing this because it roughly exists.
