### ISSUE TITLE
Refactor PhasedXPowGate to inherit from EigenGate

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1093]
Note that it is necessary to override EigenGate's equality method, and methods such as `_with_exponent`, because they don't account for the phase parameter. For the most part, `PhasedXGate` will look quite a lot like `XPowGate` but with the phase parameter added.

**Comment by dabacon** [comment]
I made an attempt at this and I really don't think it is worth doing.  One ends up having to override many of the EigenGate methods and the code becomes much less readable as one has to constantly flip up to EigenGate to understand it.
