### ISSUE TITLE
Add 'trace' utility methods to TrialResult and similar classes

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1094]
I think users of `TrialResult` will often have questions like "what's the bloch vector of qubit 5?" and "if I trace out qubit 4, what's the remaining density matrix?". We should have methods for these kinds of questions, and others.

**Comment by MichaelBroughton** [comment]
Are you thinking of answering these kinds of questions with tomography or did you have something else in mind ?

**Comment by Strilanc** [comment]
I was thinking that, for the trial results that have the actual wavefunction, it would directly compute the bloch vectors. If there's only sample data, then the bloch vector would be unavailable but the expectation of observable Z would be.

**Comment by MichaelBroughton** [comment]
Ok I think I'd be up for adding a few of these. I'm thinking most of the logic might live in `sim/wave_function.py` and then would get passed up to TrialResult similar to how `dirac_notation` is done. What do you think ?

**Comment by Strilanc** [comment]
That sounds good to me.
