### ISSUE TITLE
Should `cirq.Rz(np.pi/2)` show in diagrams as `X^0.5` or as `Rz(0.5π)`?

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1095]
@babbush @kevinsung @dabacon opinions?

On the one hand, Rz is more true to what the user said and what they expect. On the other hand, using Rz is a visual difference with no particular corresponding behavior difference and it takes more horizontal space.

**Comment by babbush** [comment]
I vote for Rz(0.5pi). I don't care if multiple visualizations map to the same unitary.
