### ISSUE TITLE
Fractional exponents in diagrams

### ISSUE THREAD

**Issue by viathor** [quantumlib/Cirq#1098]
What do people think about replacing decimal fractions with ordinary fractions in diagrams (in cases where it is possible), e.g. displaying `X^(7/8)` rather than `X^0.875`?

An important property of quantum gates is that most of them are elements in finite [cyclic groups](https://en.wikipedia.org/wiki/Cyclic_group) and this is better exhibited by `X^(1/8)` than `X^0.125`. For example, the order of the minimal group containing the gate is clear from notation as it is equal to the denominator.

**Comment by Strilanc** [comment]
I think this is a good idea. If we're within 10**-precision of a fraction with a denominator less than 20-ish, it would add a nice amount of clarity.

Note that we can use unicode fraction characters, as long as they play nice in fixed width fonts.

```
⅟ ½ ⅓ ¼ ⅕ ⅙ ⅐ ⅛ ⅑ ⅒
    ⅔   ⅖
      ¾ ⅗     ⅜
        ⅘
          ⅚   ⅝

              ⅞
```

**Comment by MichaelBroughton** [comment]
I'd be happy to do this , but I think it's worth noting we may not be able to use unicode fractions, since I don't think there are very many ?

http://unicode.org/cldr/utility/list-unicodeset.jsp?a=[:Decomposition_Type=Fraction:]

**Comment by dabacon** [comment]
And frankly they are not very readable.
