### ISSUE TITLE
General Unitary to Probabilistic Unitary

### ISSUE THREAD

**Issue by MichaelBroughton** [quantumlib/Cirq#1105]
figure out how to incorporate different kinds of noise channels into circuit constructions in a nice way. right now we have `common_channels.py` containing the depolarizing channel. The best idea so far (from @Strilanc ) is "We should add something like a `with_probability(p)` method to `cirq.Operation` and `cirq.Gate` to make these easy to make, so you could say `cirq.Z(q).with_probability(p)`". But in the future other channels might not always fit into this nice construction of `with_probability` if they have multiple parameters for example.

**Comment by dabacon** [comment]
Fixed in #3024
