### ISSUE TITLE
Remove `cirq.Optimizer` class, which is just a `Callable[[Circuit], None]`

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1127]
More generally, instead of having to say `cirq.google.EjectZ().optimize(circuit)`, we should just be able to say `cirq.push_z_gates_to_end_of_circuit(circuit)`.

**Comment by vtomole** [comment]
This is was renamed to `cirq.OptimizationPass` we can close it in place of: https://github.com/quantumlib/Cirq/issues/1241.

**Comment by vtomole** [comment]
@Strilanc  Ping.

**Comment by Strilanc** [comment]
Duplicate of https://github.com/quantumlib/Cirq/issues/1241 which was fixed by https://github.com/quantumlib/Cirq/issues/1248

Thanks Victory
