### ISSUE TITLE
Define _unitary_ for QasmUGate and QasmTwoQubitGate

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#1139]

**Comment by jaywha** [comment]
In [qasm_output.py](https://github.com/quantumlib/Cirq/blob/master/cirq/circuits/qasm_output.py), I see the 2 classes, but what should _\_unitary_\_ be?  
Is it a [unitary matrix](http://mathworld.wolfram.com/UnitaryMatrix.html)?

**Comment by Strilanc** [comment]
@jaywha Yes, the output of `_unitary_` is the unitary matrix of the operation. E.g. for the Pauli Z gate the matrix is diag(1, -1).
