### ISSUE TITLE
Broken Hadamard gate decomposition

### ISSUE THREAD

**Issue by viathor** [quantumlib/Cirq#1159]
Steps to reproduce:

```
In [1]: import cirq                                                                                                                                                            

In [2]: q = cirq.NamedQubit('q')                                                                                                                                               

In [3]: cirq.Circuit.from_ops(cirq.decompose([cirq.H(q)]))._unitary_()                                                                                                         
Out[3]: 
array([[ 0.5+0.5j,  0.5+0.5j],
       [ 0.5+0.5j, -0.5-0.5j]])

In [4]: cirq.Circuit.from_ops([cirq.H(q)])._unitary_()                                                                                                                         
Out[4]: 
array([[ 0.70710678+0.j,  0.70710678+0.j],
       [ 0.70710678+0.j, -0.70710678+0.j]])
```

Note that exponentiating the gate to a power different from 1.0 makes this work, suggesting a special casing of a decomposition is the culprit.

This affects other gates whose decomposition includes Hadamards (e.g. iSwaps). 

There is a unit test that compares the unitary given by the gate and by its decomposition, but the assert it uses makes the comparison merely up to global phase. I think this is incorrect. Consider two qubits q0 and q1 and a circuit that applies U0 to q0 and U1 to q1. Suppose that the decomposition of U0 yields a unitary that is consistent with U0 merely up to global phase. What happens we you replace U0 with its decomposition? Well, this alters the *relative* phase between q0 and q1 producing observable effect.

**Comment by Strilanc** [comment]
Decompositions aren't required to maintain global phase. I opened https://github.com/quantumlib/Cirq/issues/1161 to fix this.

For this particular issue I guess we could global shift the Z...

**Comment by maffoo** [comment]
@viathor, the situation you described is not a problem. A "global" phase on a single qubit operation is still a global phase of the full system when you take a tensor product with other qubits, so it really is unobservable. You only have a problem if you're doing one of the operations _conditionally_ on the state of the other qubit (there was discussion of this on #865). But I agree with @Strilanc that people may _expect_ decompositions to preserve global phase, so it will head off confusion if we can preserve it (see also #816).
