### ISSUE TITLE
QASM test method doesn't use QASM protocol

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#1166]
The test method `assert_qasm_is_consistent_with_unitary` doesn't use the `protocols.qasm` method. Instead, it uses the line
```
qasm = str(circuits.QasmOutput(op, qubits[::-1], precision=10))
```
My understanding is that the reason `protocols.qasm` isn't used is that it doesn't let us pass in qubits in the reverse order, which is necessary due to qiskit using the reverse qubit ordering convention to convert a QASM to a unitary.
Blocking #1165

**Comment by kevinsung** [comment]
@Strilanc I think the correct thing to do is to not have `qubits[::-1]` anywhere, and to instead reorder the unitary returned by qiskit in tests. What do you think?

**Comment by Strilanc** [comment]
I agree.

**Comment by kevinsung** [comment]
#1176 fixes the order thing; the remaining issue is that simply calling `protocols.qasm(op)` won't work due to the different qasm protocols that can be implemented; some require QasmArgs, some require qubits.

**Comment by Strilanc** [comment]
Check out how `assert_decompose_is_consistent_with_unitary` does it. It just special cases operations and gates, since that's basically the distinction between qubits and no qubits. An alternative strategy would be to do runtime inspection of the method, but I'm happy with something simple that works on cases we care about for now.

**Comment by kevinsung** [comment]
I looks like we can make `isinstance` work by explicitly declaring protocols to be [runtime checkable](https://www.python.org/dev/peps/pep-0544/#runtime-checkable-decorator-and-narrowing-types-by-isinstance). I'm not sure we want to do that though; I'll try the special cases strategy you suggested.
