### ISSUE TITLE
gate1 == gate2 should imply f(gate1) == f(gate2)

### ISSUE THREAD

**Issue by viathor** [quantumlib/Cirq#1179]
Example where it doesn't:

```python
In [2]: z1 = cirq.Z                                                                                                                                  

In [3]: z3 = cirq.Z**3                                                                                                                               

In [4]: z1 == z3                                                                                                                                     
Out[4]: True

In [5]: z1**(1/3) == z3**(1/3)                                                                                                                       
Out[5]: False
```

This is a consequence of our attempt to preserve the identity

```
(1)                   (G**a)**b == G**(a*b)
```

The identity is true for real numbers. It fails when we move on to complex numbers. From then on it continues to fail for unitary operators.

I understand the desire for intuitive behavior, but I fear that an attempt to preserve a false identity will just lead to a surprising behavior elsewhere: since the identity is false, something has to give. In this case, we are giving up a very fundamental and intuitive property of equality: if two gates are equal then transforming each in a given way yields another pair of equal gates.

If we must surprise some users, perhaps it is best to do so in a context that is at least consistent with the rest of the world, which recognizes the failure of identity (1).

Filed from review of #1155.

**Comment by viathor** [comment]
@Strilanc are you saying that `(Z**-1)**0.5` should return `S**-1` rather than `S`? (Below I assume yes, please disregard otherwise.)

Taking roots is a multi-valued function, i.e. for any a and n there is generally many x such that

```
x**n = b
```

This is true for integers, reals, complex numbers and operators. For example, both 2 and -2 satisfy x^2 = 4, both i and -i satisfy x^2 = -1 and both S and its inverse satisfy x^2 = Z.

The prevailing convention for resolving this ambiguity is to choose the [principal value](https://en.wikipedia.org/wiki/Principal_value). This convention is followed in maths, physics, electrical engineering, python (math, cmath, numpy) and most other programming languages and libraries.

It's easily seen that S and not its inverse is the PV of `(Z**-1)**0.5`. Under the PV convention we should return `S` as the value of that expression.

IIUC, the competing new convention proposed in cirq is to encode the branch choice in the sign of the exponent. This may work in the above case, but only because there are exactly two roots to choose from. The new convention is not extensible in an intuitive and consistent way to other situations. Consider `(Z**-1)**0.25`. There are four candidates for the value of this expression: T, T^3, T^-3 and T^-1. Endowing the sign of the exponent with additional meaning isn't going to help us here, given that we're choosing one of four branches and there are only two signs :-)

Following the established mathematical definitions and conventions minimizes the risk of surprising and inconsistent behavior.

**Comment by Strilanc** [comment]
Yes, `(Z**-1)**0.5` should return `S**-1`. `(Z**3)**0.5` should also return something equivalent to `S**-1`.

An example of existing functionality standard to all languages that violates `a == b implies f(a) == f(b)` is how signed zeros interact with floating point division. 0==-0 but inf = 1/0 != 1/-0 = -inf.

**Comment by viathor** [comment]
> Yes, (Z**-1)**0.5 should return S**-1.

Intriguing. For diagonalizable operator A with eigenvalues λ1..λn and analytic function f, f(A) is the operator with eigenvalues f(λ1)..f(λn) (and same eigenvectors). In this case we're taking square root of an operator with eigenvalues 1 and -1, so one would expect that the square root has eigenvalues 1 and i (since sqrt(-1) is generally accepted to be i and not -i by the PV convention above). Instead, you're saying it should be the one with eigenvalues 1 and -i.

Could you explain why?

Also, do you know the behavior of other QC libraries?

> Python will raise an error if you do this, numpy will print a warning,

More evidence that violating the identity in the issue title is widely considered abnormal and surprising.

**Comment by Strilanc** [comment]
> Could you explain why?

Because `(g**a)**b` should equal `g**(a*b)`.

The gates have an internal winding number, and raising to a power scales the winding number. Winding twice is equivalent to winding once in terms of its final effects, but it's possible for mathematical invariants to be phrased in terms of the winding number and then the multiplicity matters.

**Comment by viathor** [comment]
> Because `(g**a)**b` should equal `g**(a*b)` whenever possible.

So, the failure of expressions such as `(Z**-1)**0.5` to evaluate to their principal value (here `S`) is another consequence of the desire to force unitaries to obey `(g**a)**b == g**(a*b)`. Like the inequality weirdness above, this leads to surprising behavior.

Here's what the user will most likely expect:

<img width="341" alt="sqrtz_pv" src="https://user-images.githubusercontent.com/40255865/48955341-72901200-ef1b-11e8-858d-f93b47b224f2.png">

Here's what they'll get some of the time instead:

<img width="354" alt="sqrtz_nonpv" src="https://user-images.githubusercontent.com/40255865/48955347-76bc2f80-ef1b-11e8-9e29-150d18f192fb.png">

I think this is very likely to surprise and confuse users as it would surprise and confuse if `numpy.sqrt(-1)` returned `-1j` instead of `1j`.

To make matters worse, in any given context it may be unclear which of the two square roots is chosen by cirq since the choice is dependent on the details of how the `Z` was constructed (which as Craig indicated above, may be obfuscated).

> it's possible for mathematical invariants to be phrased in terms of the winding number

This is a cool argument! :-) What are some examples of the mathematical invariants involving the winding number?

**Comment by Strilanc** [comment]
Off the top of my head, I remember that sphere eversion is possible because of conservation of a 3d analogue to the 2d winding number https://www.youtube.com/watch?v=sKqt6e7EcCs

**Comment by dabacon** [comment]
>  The same unitary can be generated by two different Hamiltonians applied for the same amount of time.
Just a side note that there are way more than two different Hamiltonians applied for the same amount of time that can generate a unitary.  Every eigenvalue of a unitary is ambiguous up to a phase of 2 \pi.

This discussion is the reason that most people in quantum computing do not talk about raising a gate to a fractional power.  A cursory look shows that no one else does this.

My inclination would be to follow what is done in complex analysis and use the principal value.  Two reasons
1) This is consistent with how other math libraries handle things and is the familiar mathematical convention.
2) Not doing this can make optimization routines get stuck in really bad states where they cannot optimize because they have gates that are on different branches but that are the same gate.

What are the main drawbacks of using the principal value?

**Comment by viathor** [comment]
Had a quick look at what implementation of this might look like. AFAICT, we should be able to store only canonicalized exponent. For EigenGate, this should give us nice code simplification by removing the need for having two different exponents for different purposes (equality tests vs other computations) and by removing the need for caching canonicalization result.

@Strilanc Unless you object, I'll go ahead and implement this in near future. Let me know what you think.

**Comment by Strilanc** [comment]
Yeah, go ahead and implement it.

I think the main obstacle you will run into is that the canonicalization differs when ignoring global phase and when not ignoring global phase, and this distinction has to be resolved. I think the solution is to bias much more heavily towards not ignoring global phase, e.g. show it in diagrams.

**Comment by dabacon** [comment]
I think the plan of record is documented in #1731.  I'm going to close this, though we need to get #1731 back on track as it is a better solution.  There is a comment on #1731 about this issue so should that not work out we should revisit this.

**Comment by daxfohl** [comment]
@viathor @MichaelBroughton @tanujkhattar  Given we've chosen not to address #1731 should this be reopened?

Another salient example, it seems controlled gates are considered equal even if the control qubit order is swapped. However this seems very not equal, as they create different operations when applied to qubits. If the dimensions are different, this even throws an exception when trying to apply.

```python
def test_me():
    g0 = cirq.ControlledGate(cirq.Z, control_values=[[1], [1, 2]], control_qid_shape=[2, 3])
    g1 = cirq.ControlledGate(cirq.Z, control_values=[[1, 2], [1]], control_qid_shape=[3, 2])
    assert g0 == g1  # passes
    qubits = cirq.LineQid.for_qid_shape((2, 3, 2))
    op0 = g0.on(*qubits)
    op1 = g1.on(*qubits)  # raises "Wrong shape of qids"
    assert op0 == op1
```

**Comment by daxfohl** [comment]
A better example of a common place this doesn't hold. Dictionaries in Python are ordered (now), so:

```python
>>> x = {'a':1, 'b':2}
>>> y = {'b':2, 'a':1}
>>> x == y
True
>>> list(x)
['a', 'b']
>>> list(y)
['b', 'a']
>>> list(x) == list(y)
False
```

**Comment by daxfohl** [comment]
Another way to look at this is, which is more important, `gate==gate implies f(gate)==f(gate)`, or `f_inv(f(gate)) == gate`. We can only have one. Or as @dabacon suggested, maybe we could stick to integer exponents, and if users needed to go lower-level than that, they can supply their own eigen phases. But that way, users can set things up however they want, and both of those relations will always hold.

**Comment by daxfohl** [comment]
And fwiw I think of the two, `f_inv(f(gate)) == gate` is the more important. (Which is great, because that's what we do). If we're doing transformations of gates into other gates via fractional exponent multiplication and such, preserving that winding number could be important. Canonicalizing / doing modular arithmetic at each step could make such things impossible.
