### ISSUE TITLE
half_turn name in ExpZGate is confusing

### ISSUE THREAD

**Issue by dkafri** [quantumlib/Cirq#118]
In sim.google.xmon_simulator_test, I added the following test:
```
@pytest.mark.parametrize('phase', (0.0, 0.2))
def test_param_resolver_exp_z_half_turns(phase):
    exp_z = ExpZGate(half_turns=phase)
    circuit = Circuit()
    circuit.append(exp_z(Q1))

    resolver = ParamResolver({'a': phase})
    result = compute_gate(circuit, resolver)

    np.testing.assert_almost_equal(
        result,
        np.array([[cmath.exp(1j * math.pi * phase / 2), 0],
                  [0, cmath.exp(-1j * math.pi * phase / 2)]]))
```

This test passes, which confuses me, because the gate implemented is 
\exp( i (\pi "phase" / 2)  \sigma_z  )
So ExpZGate(half_turns=1) actually implements a "quarter turn" instead of a "half_turn", and  ExpZGate(half_turns=2) is not the identity.

**Comment by dkafri** [comment]
From discussions I've had with others on the team, at least 3 other people using Cirq have found this confusing. Two have reported adding bugs to their code due to misunderstanding what half_turns means. I suggest using `periods', with periods=1.0 corresponding to exactly the identity (not up to global phase).

**Comment by vtomole** [comment]
How about "degrees" instead? `RZ(qubit, 90)`

**Comment by Strilanc** [comment]
What do people think of `exponent` instead of `half_turns`? That's unambigous.

**Comment by kevinsung** [comment]
I strongly agree with `exponent`.

**Comment by dkafri** [comment]
I think you should not need to know the specific convention of the gate in order to guess what the argument should be. For example, is cirq.RZ(theta) equal to 

exp(i theta \sigma_z)  

or

|0 >< 0 | +  exp(i theta) |1 > < 1 |

In the first case, the period is \theta = \pi, while in the second case the period is \theta = \2 pi.
But if I specify periods = 0.5, I know that in *both* cases I will get a Z gate.

**Comment by Strilanc** [comment]
This has now been fixed. `cirq.ZPowGate` takes an exponent, and `cirq.Rz` takes rads.
