### ISSUE TITLE
For circuit diagram exponents equal to 0, output "^0" instead of "^(0)"

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1180]
It was an unexpected side effect of the fractional exponents change that caused us to output `(0)` instead of `0.0`; might as well go all the way.

**Comment by Strilanc** [comment]
@zoltanegyed

**Comment by MichaelBroughton** [comment]
For anyone looking to resolve: all of the work to fix this can be done in: `_formatted_exponent` in `cirq/circuits/circuit.py`

**Comment by vtomole** [comment]
@Strilanc 
```
def test_diagram_wgate():
    qa = cirq.NamedQubit('a')
    test_wgate = cirq.PhasedXPowGate(
        exponent=0, phase_exponent=0.43)
    c = Circuit([Moment([test_wgate.on(qa)])])
    cirq.testing.assert_has_diagram(c,
                                    """a: ---PhasedX(0.43)^0---""",
                                    use_unicode_characters=False)
```
Passes on my machine off of the latest code in master. May you point me to an example where this is not the case?

Thanks.

**Comment by Strilanc** [comment]
Example repro:

```
import cirq
print(cirq.Circuit.from_ops(cirq.X(cirq.NamedQubit('q'))**0))
```

Prints:

```
q: ───X^(0)───
```

**Comment by vtomole** [comment]
Was able to reproduce as soon as I made that comment. Should have edited instead of deleted. Thanks.
