### ISSUE TITLE
Make markdown-to-rst conversion work within Args, Returns, and other sub-sections

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1188]
Currently the conversion cuts off just before those sections start in docstrings, to avoid interacting with Napoleon too much.

**Comment by dabacon** [comment]
This is a bit vague, but my guess is that this is a task to make
```convert_markdown_mathjax_for_rst```
from `docs/conf.py` to work with the code the that the Napolean extension (Google docstrings) has processed i.e.  the code that is skipped here https://github.com/quantumlib/Cirq/blob/6271cb62ddfc0ba9121140a60cc7e1faf39da77e/docs/conf.py#L96

**Comment by balopat** [comment]
This is for sphinx originally - the devsite works well. Closing.
