### ISSUE TITLE
Remove `cirq.Tolerance`

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1190]
This class ended up being nothing more than a variation on passing `atol` arguments, so it's not pulling enough weight to justify being in the API.

**Comment by andbe91** [comment]
Hi @Strilanc 
This looks like a simple enough issue to start my contributions with. Just to make sure I understand, you only want it removed from the API, i.e. basically removing the import from the __init.py__ in the root directory?

**Comment by vtomole** [comment]
@andbe91 I've started working on this but i didn't officially claim it so it's up to @Strilanc to decide; but yes, remove every reference to `Tolerance` (removing tolerance.py. e.t.c).

**Comment by andbe91** [comment]
@vtomole since you have already started, it might be better if I work on another issue. Please let me know if you want me to take over for some reason.

**Comment by Strilanc** [comment]
@vtomole is correct; this would involve completely deleting the class

**Comment by Strilanc** [comment]
That being said, I think the main important arguments to propagate are `atol` and `rtol`, no need for the nan ones.

**Comment by vtomole** [comment]
This is done. Please close.

**Comment by dabacon** [comment]
We might want to take a pass through code to insure that we are using atol and rtol as parameters when it makes sense (probably most of the time)
