### ISSUE TITLE
xmon native gates should be extended to include all single qubit gates

### ISSUE THREAD

**Issue by dlyongemallo** [quantumlib/Cirq#1195]
In particular, the random circuit generator to produce the circuits for https://github.com/sboixo/GRCS/tree/master/inst/cz_v2 (https://arxiv.org/abs/1807.10749) add an initial and a final moment of Hadamards on every wire, but the xmon devices do not support the Hadamard gate.

**Comment by dabacon** [comment]
We should be careful here since adding composite gates can result in behavior that does not closely track hardware.

**Comment by dlyongemallo** [comment]
I'm having the problem that the randomly generated circuits from `generate_supremacy_circuit_google_v2_bristlecone` _always_ have a Moment of Hadamard gates at the input and output.

The following code fails:

```
  circuit = supremacy_v2.generate_supremacy_circuit_google_v2_bristlecone(n_rows=3, cz_depth=4, seed=0)
  device = cg.Bristlecone
  s1 = moment_by_moment_schedule(device, circuit)
  protos = list(cg.schedule_to_proto_dicts(s1))
```

With the error:

```
File "xmon_device.py", line 79, in duration_of
    raise ValueError('Unsupported gate type: {!r}'.format(operation))
ValueError: Unsupported gate type: cirq.H.on(cirq.GridQubit(0, 5))
```

**Comment by dabacon** [comment]
This should now be handled by the serializable gate set as well as custom optimizers for the different gate sets (though of course this later is not unique).
