### ISSUE TITLE
Add release notes

### ISSUE THREAD

**Issue by Ashalynd** [quantumlib/Cirq#1207]
Verifying #1206 , I have realized that there aren't release notes for Cirq yet. I suggest adding them, it would at least make it easy to track issues which might occur in different versions.

**Comment by vtomole** [comment]
Agree. We should add them on here: https://github.com/quantumlib/Cirq/blob/master/release.md

**Comment by Ashalynd** [comment]
Oh I see, thanks for pointing that out. Usually such things are a bit more "in your face", e.g they are called "release_notes" or "changelog" (like e.g. in one of [Qiskit](https://github.com/Qiskit/qiskit-terra/blob/master/CHANGELOG.rst) repos), which is why I was confused.

**Comment by dabacon** [comment]
Should we close this or should we consider duplicating the github release notes into a file?

**Comment by dabacon** [comment]
I'm going to close, though there might be consideration in documentation for pointing to the release notes more prominently.
