### ISSUE TITLE
Consistent Protocol testing functionality relies on implicit imports

### ISSUE THREAD

**Issue by dstrain115** [quantumlib/Cirq#1235]
testing/consistent_protocols_test.py and ops/controlled_gate_test both rely on gates within the test itself, which creates a representation of cirq.testing.consistent_protocols_test.GoodGate, for instance.

This is not actually imported, so certain environments (internal Google, for instance) fail these tests when you try to eval those repr() strings.  

Either the test needs to move those gates to something actually imported by the class, or we need to change the implementation of consistency better (not eval the strings or not use the fully qualified classname maybe?)

**Comment by Strilanc** [comment]
We could pass explicit globals into the eval method. That might work.

**Comment by dstrain115** [comment]
So, part of this is solved, but there is still an issue, since the representation on line 121 of controlled_gate_test still relies on an implicit import:
        return ('cirq.ops.controlled_gate_test.'
                'GateUsingWorkspaceForApplyUnitary()')

Since the internal Google build splits the library code and the test code, cirq.ops.controlled_gate_test is not part of the cirq import, so the problem still exists.  However, the problem is now contained to those two gates within controlled_gate_test.
