### ISSUE TITLE
Remove OptimizationPass

### ISSUE THREAD

**Issue by bryano** [quantumlib/Cirq#1241]
From @Strilanc: "it's nothing but a definition of a particular kind of Callable (and not even a complicated one)"

**Comment by iamvamsi** [comment]
I am planning to pick this up too. 
@bryano / @Strilanc : Can you please provide the context around this ?

**Comment by bryano** [comment]
@vtomole is already taking a crack at this in #1248.

**Comment by iamvamsi** [comment]
Cool.
