### ISSUE TITLE
Parameter resolver cannot resolve simple arithmetics

### ISSUE THREAD

**Issue by hwjclaire** [quantumlib/Cirq#1262]
I am writitng a simple script and got an error. Is this expected? 
For larger circuit this is inconvenient.

circuit = cirq.Circuit()
x = cirq.NamedQubit('x')
a = cirq.Symbol('a')
circuit.append(cirq.H(x)**(1.2*a))
print(circuit)

TypeError: unsupported operand type(s) for *: 'float' and 'Symbol'

**Comment by dabacon** [comment]
Yes this is a known issue.  #393 or #961 would both solve this.  Please chime in on those, as this is creeping up in our prioritization.

**Comment by vtomole** [comment]
This works now that we've moved to sympy but i don't think the `repr` of the circuit is correct.

**Comment by Strilanc** [comment]
Yes, this is now fixed.

If a repr is incorrect, open as separate issue.
