### ISSUE TITLE
Engine params  should be on job not program

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#1263]
This is using old way of specifying parameters.

**Comment by iamvamsi** [comment]
@dabacon : Dave, I am planning to take this up. Can you please help me with a little more context around the same.

**Comment by dabacon** [comment]
Parameters used to live on the program proto.  But we updated the api so that they can go on the job (the engine api accepts both right now).  So we need to move Cirq over to using this new way of specifying the parameters.  Essentially this means refactoring the engine api calls so that the parameter sweeps get passed to the job and not the program.  I'd start by looking at the api protos for job and program and seeing the differences, then tracing through the cirq engine code to see where they are being used.  You will likely need to refactor where the params are passed in.  OK to making breaking cirq changes for the engine code here.

**Comment by iamvamsi** [comment]
Thanks Dave.

**Comment by dabacon** [comment]
This has been done.
