### ISSUE TITLE
matplotlib 3.0.2 compatible?

### ISSUE THREAD

**Issue by jiapei100** [quantumlib/Cirq#1269]
**cirq 0.4.0 has requirement matplotlib~=2.2, but you'll have matplotlib 3.0.2 which is incompatible.**

**Comment by vtomole** [comment]
You have matplotlib `3.0.2` but we use `~2.2`. Let me know if it works after `pip install --ignore-installed matplotlib==2.2`.

**Comment by vtomole** [comment]
@Strilanc Any reason for sticking to `~=2.2`

**Comment by vtomole** [comment]
Hey @jiapei100, did you run into a problem using `matplotlib 3.0.2` with Cirq?

**Comment by vtomole** [comment]
Closing. Feel free to re-open if you run into matplotlib version problems.
