### ISSUE TITLE
Define `_control_` protocol and utility method

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1285]
A common thing that people want to do to operations is to control them. For example, this is intrinsic to how phase estimation works. A global utility method `cirq.control` that worked on any gate or OP_TREE would make that easier. Additionally, there would be a `_control_` protocol that gates with more efficient control mechanisms (e.g. decomposing a fredkin using two CNOTs and a Toffoli instead of three Toffolis) could define.

The signature of `_control_` would be `(self, control: cirq.QubitId)` and the result type would vary from object to object (e.g. gates would return gates but operations would return operations).

The signature of the global utility method would be `def control(controllee: Union[Gate, OP_TREE], control_qubit: Optional[Qubit] = None)`. If the control qubit is set to `None`, that means the user wants to specify it later in order to get an operation (i.e. it should work the way `ControlledGate(gate)` works, except it will also apply to operations).

If the control qubit is specified, then the method will attempt to use the controllee's `_control_` method or else fall back to strategies based on the controllee's known unitary or known decomposition in order to return a controlled result. Otherwise it fails.

**Comment by Strilanc** [comment]
Also, once `cirq.control` exists, we can add `controlled_by(control)` to `Operation` if we want.

**Comment by smitsanghavi** [comment]
For _control_ on a gate to return a gate when given the control qubit, do we have a concept of adding only a partial set of qubits to the gate and specifying the rest later?

**Comment by Strilanc** [comment]
- for control(operation, qubit), use ControlledOperation
- for control(operation, None), raise an error explaining a qubit is needed for operations
- for control(gate, None), use ControlledGate
- for control(gate, qubit), make new type SpecifiedControlGate (or alternatively merge this concept into ControlledGate)
