### ISSUE TITLE
Set a default value for atol where it appears?

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#1286]
Interestingly, `assert_allclose_up_to_global_phase` has a comment explicitly recommending against specifying a default atol:
```
def assert_allclose_up_to_global_phase(
        actual: np.ndarray,
        desired: np.ndarray,
        *,  # Forces keyword args.
        rtol: float = 1e-7,
        atol: float,  # Require atol to be specified
        equal_nan: bool = True,
        err_msg: Optional[str] = '',
        verbose: bool = True) -> None:
```
This was suggested by @Strilanc in https://github.com/quantumlib/Cirq/pull/729. @dabacon

**Comment by dabacon** [comment]
Part of the reason to make sure to specify atol for `assert_all_close_up_to_global_phase` is likely that we are modeled after numpy's downstream `is_close`.  Numpy's method is not symmetric.  The guidance in documentation https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.isclose.html is that you should select this carefully (also known as until your tests pass).  That said, even numpy has defauls for rtol and atol.  

My suggestion is that if our tools delegate `rtol` and `atol` they should use numpy's defaults.

**Comment by Strilanc** [comment]
I think for testing methods it is best for each test to specify its tolerance. It is convenient to have default tolerances (and we do have this in some places) but really it is something that should be thought about for each comparison IMO. I'll close this pending someone else feeling strongly enough to re-open it.
