### ISSUE TITLE
Noisy simulations should allow mixed state inputs

### ISSUE THREAD

**Issue by karlunho** [quantumlib/Cirq#1287]
This feature needed for VQE algorithm for a few of the QML. Although this isn't realizable in HW yet, there is some plans in the future to enable this.

**Comment by karlunho** [comment]
Michael will like implement this. We'll discuss with this in more detail with Dave and Craig.

**Comment by dabacon** [comment]
We have two simulation techniques in process: one which is a full density matrix the other of which is for probabilistic pure state simulations (also long term there is continuous time).  It makes sense that these simulators should support initial state preparation with 1) full density matrix, 2) eigenvalue and eigenvectors of full density matrix.  When we do this we will need an initial state preparation gate.  So yes we should add this.

**Comment by raminhalavati** [comment]
@dabacon,
Is there a time line for this?

**Comment by dabacon** [comment]
The first type of simulator (full density matrix) is in flight and should be done by end of this week.  Second one is likely another week after that.

**Comment by raminhalavati** [comment]
Great! Thanks.

**Comment by Strilanc** [comment]
This has been added to the density matrix simulator, but still needs to be added to the mixture simulator (which doesn't exist yet).

**Comment by Strilanc** [comment]
Subsumed by https://github.com/quantumlib/Cirq/issues/1383
