### ISSUE TITLE
Enable Entanglement Entropy Calculations in Cirq

### ISSUE THREAD

**Issue by karlunho** [quantumlib/Cirq#1289]
R

@dabacon Can you take a look if you think this is something we should put in ?

**Comment by michaelstreif** [comment]
Calculating the entanglement entropy gives insight into the mechanisms of the quantum calculations and is therefore an important quantity to find useful quantum algorithms. It moreover helps to estimate the required resources for classical simulations when using TNT.

I think this would be of help for research and simulations, but not really when using the real device. We already  have functions calculating the entanglement entropy, given the output of the cirq simulator.

**Comment by dabacon** [comment]
I think adding support for this would be good.  It is definitely useful for simulations.  We already have the beginnings of denisty matrices appearing in Cirq.

**Comment by dabacon** [comment]
This is implemented in `cirq.von_neumann_entropy`
