### ISSUE TITLE
Occupation number representation of LinearOperators

### ISSUE THREAD

**Issue by viathor** [quantumlib/Cirq#1309]
Filing for discussion and implementation tracking of occupation basis representation for the LinearOperator introduced in #1299, see the PR for context.

Rationale: Hamiltonians used in quantum simulation applications tend to have an efficient representation in this basis

Caveats: The above suggests that LinearOperator with this representation should not automatically compute its standard or Pauli basis expansions.

**Comment by dabacon** [comment]
If we go down this direction it seems like we should consider it as part of a generic addition of support for  basis expansions outside of the pauli basis (all hail the hegemony of the Pauli matrices!)
