### ISSUE TITLE
Add Neutral Atom device

### ISSUE THREAD

**Issue by karlunho** [quantumlib/Cirq#1310]
UWisconson would like to add Neutral Atoms to Cirq.

**Comment by c-poole** [comment]
We'd like to incorporate support for neutral atom devices and in particular the Atomic Qubit Array (AQuA) device at the University of Madison Wisconsin. A goal of the project is to be able to accurate perform simulations of the device including its various connectivity and timing constraints as well as its native gate set, all of which Cirq seems like a good match for.
