### ISSUE TITLE
Circuit optimizations should remove empty Moments

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#1316]
Sometimes running a circuit optimizer leaves Moments empty. What reason is there to keep them around? They add some overhead when iterating through the circuit and also make text diagrams take up more space. I'm not too familiar with the code of the optimizers and it could be the case that removing empty Moments doesn't fit nicely into the logic there.

**Comment by balopat** [comment]
I can take a look at this, it would give me a good opportunity to learn about the optimizers.

**Comment by Strilanc** [comment]
After discussion, we decided not to do this. It's finnicky to add it to all the optimizers, and it creates redundant work. Thanks @balopat for trying to fix it and pointing out how awkward it was.
