### ISSUE TITLE
Flaky test in acquaintance gates `test_swap_network_gate_equality`

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1329]
This test fails sporadically:

```
@pytest.mark.parametrize('part_len_sets',
        [[[randint(1, 5) for _ in range(randint(2, 7))] for _ in range(5)]])
    def test_swap_network_gate_equality(part_len_sets):
        acquaintance_sizes = [None, 0, 1, 2, 3]
        swap_gates = [cirq.SWAP, cirq.CNOT]
        equals_tester = ct.EqualsTester()
        for args in product(part_len_sets, acquaintance_sizes, swap_gates):
            first_gate = cca.SwapNetworkGate(*args)
            second_gate = cca.SwapNetworkGate(*args)
>           equals_tester.add_equality_group(first_gate, second_gate)
```

**Comment by bryano** [comment]
#1331

**Comment by bryano** [comment]
I'm not sure I understand. Is the problem that there is some probability that there are k<5, maybe even k=1, unique part_lens generated? If so, we could just bump up the number of randomly generated tuples until the probability of there being too few unique ones is acceptably small.

**Comment by Strilanc** [comment]
The problem is that, because you are iterating over `set(items_to_test)` instead of over `items_to_test`, it no longer makes any sense to assert that the items are not equal (which is an implicit thing that equals tester is doing). An equality method that was just `return True` would pass the test. We want such equality methods to fail the test.

**Comment by bryano** [comment]
I don't think that's quite right. The things whose equality is being tested are `SwapNetworkGate(*args)`. For each (unique) value of args, _two_ objects are created and those two be equal to each other and unequal to everything else. So it doesn't seem like a tautological equality method would pass the test.

**Comment by Strilanc** [comment]
Ooooh I see, the set is on the parameters. My mistake.
