### ISSUE TITLE
Unable to verify Cirq : python -c 'import cirq; print(cirq.google.Foxtail)' on Mac OS

### ISSUE THREAD

**Issue by pradeep6** [quantumlib/Cirq#1336]
The installation of the Cirq was successful, but when I am trying to run run the command

python -c 'import cirq; print(cirq.google.Foxtail)' for verification. It is showing the below error.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cirq'

Please help me to solve this issue

**Comment by Strilanc** [comment]
Could you post a log of the bash commands you ran in order to install cirq, before running this command? Did you install into a virtual environment, are you using python 2 vs 3, etc.

**Comment by pradeep6** [comment]
(env) MacBook-Pro:~ unomahaqcl$ cd /Users/unomahaqcl/Library/Python/3.7/bin
(env) MacBook-Pro:bin unomahaqcl$ python3 -m venv env
(env) MacBook-Pro:bin unomahaqcl$ source ./env/bin/activate
(env) MacBook-Pro:bin unomahaqcl$ python -c 'import cirq; print(cirq.google.Foxtail)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cirq'

**Comment by dabacon** [comment]
You did a "pip install cirq" earlier?  Could you verify that in the virtual environment that you have cirq installed?  "pip freeze" will show you what is installed. Make sure you are in the environment when you do this: "source ./env/bin/activate" before running "pip freeze"

Also you should verify that the python you are using for the python -c "import cirq; print(cirq.google.Foxtail)" command is the one that is being used by the virtual environment.

**Comment by pradeep6** [comment]
Still the same issue after trying this

(env) Konetis-MacBook-Pro:~ unomahaqcl$ python -c 'import cirq; print(cirq.google.Foxtail)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cirq'
(env) Konetis-MacBook-Pro:~ unomahaqcl$ pyhton3 --version
-bash: pyhton3: command not found
(env) Konetis-MacBook-Pro:~ unomahaqcl$ python3 --version
Python 3.7.2
(env) Konetis-MacBook-Pro:~ unomahaqcl$ source ./env/bin/activate
(env) Konetis-MacBook-Pro:~ unomahaqcl$ python -c 'import cirq; print(cirq.google.Foxtail)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cirq'
(env) Konetis-MacBook-Pro:~ unomahaqcl$ pip install --user cirq
Collecting cirq
  Using cached https://files.pythonhosted.org/packages/99/b7/df9b3297b5ef6e03e31ea86ed7f3532a5b386002365a983536881f9f272c/cirq-0.4.0-py3-none-any.whl
Collecting protobuf~=3.5 (from cirq)
  Using cached https://files.pythonhosted.org/packages/18/e7/785830a65d1f1faba7dccfa8314f7afded1db8cc2860218226ba4b3f6150/protobuf-3.6.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting networkx~=2.1 (from cirq)
  Downloading https://files.pythonhosted.org/packages/f3/f4/7e20ef40b118478191cec0b58c3192f822cace858c19505c7670961b76b2/networkx-2.2.zip (1.7MB)
    100% |████████████████████████████████| 1.7MB 6.7MB/s 
Collecting google-api-python-client~=1.6 (from cirq)
  Downloading https://files.pythonhosted.org/packages/55/e9/e8fb2e3a031cb69b9524b80a92b126665d9a17421700a219555e3233ab6a/google_api_python_client-1.7.8-py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 12.3MB/s 
Collecting sortedcontainers~=2.0 (from cirq)
  Downloading https://files.pythonhosted.org/packages/13/f3/cf85f7c3a2dbd1a515d51e1f1676d971abe41bba6f4ab5443240d9a78e5b/sortedcontainers-2.1.0-py2.py3-none-any.whl
Collecting scipy (from cirq)
  Using cached https://files.pythonhosted.org/packages/c2/7b/370891c7686e598c59890588722c1d1c2b485953c4b127b7b752accbddb6/scipy-1.2.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting numpy~=1.12 (from cirq)
  Downloading https://files.pythonhosted.org/packages/46/e4/4a0cc770e4bfb34b4e10843805fef67b9a94027e59162a586c776f35c5bb/numpy-1.16.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (13.9MB)
    100% |████████████████████████████████| 13.9MB 1.9MB/s 
Collecting typing-extensions (from cirq)
  Using cached https://files.pythonhosted.org/packages/0f/62/c66e553258c37c33f9939abb2dd8d2481803d860ff68e635466f12aa7efa/typing_extensions-3.7.2-py3-none-any.whl
Collecting requests~=2.18 (from cirq)
  Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 18.2MB/s 
Collecting matplotlib~=2.2 (from cirq)
  Using cached https://files.pythonhosted.org/packages/ee/c4/bf82dc7ee81ac798cd64d8ec0884c07d59f82f45f4faf878a860c1c1d487/matplotlib-2.2.3-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting six>=1.9 (from protobuf~=3.5->cirq)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./env/lib/python3.7/site-packages (from protobuf~=3.5->cirq) (40.7.2)
Collecting decorator>=4.3.0 (from networkx~=2.1->cirq)
  Using cached https://files.pythonhosted.org/packages/f1/cd/7c8240007e9716b14679bc217a1baefa4432aa30394f7e2ec40a52b1a708/decorator-4.3.2-py2.py3-none-any.whl
Collecting httplib2<1dev,>=0.9.2 (from google-api-python-client~=1.6->cirq)
  Downloading https://files.pythonhosted.org/packages/ce/ed/803905d670b52fa0edfdd135337e545b4496c2ab3a222f1449b7256eb99f/httplib2-0.12.0.tar.gz (218kB)
    100% |████████████████████████████████| 225kB 21.5MB/s 
Collecting google-auth>=1.4.1 (from google-api-python-client~=1.6->cirq)
  Downloading https://files.pythonhosted.org/packages/4e/85/71b2dfbf5b4241cd031cc333ed71f90a271074a97cb2c517bb65f07a1a90/google_auth-1.6.2-py2.py3-none-any.whl (73kB)
    100% |████████████████████████████████| 81kB 19.6MB/s 
Collecting uritemplate<4dev,>=3.0.0 (from google-api-python-client~=1.6->cirq)
  Downloading https://files.pythonhosted.org/packages/e5/7d/9d5a640c4f8bf2c8b1afc015e9a9d8de32e13c9016dcc4b0ec03481fb396/uritemplate-3.0.0-py2.py3-none-any.whl
Collecting google-auth-httplib2>=0.0.3 (from google-api-python-client~=1.6->cirq)
  Downloading https://files.pythonhosted.org/packages/33/49/c814d6d438b823441552198f096fcd0377fd6c88714dbed34f1d3c8c4389/google_auth_httplib2-0.0.3-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests~=2.18->cirq)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 22.2MB/s 
Collecting urllib3<1.25,>=1.21.1 (from requests~=2.18->cirq)
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 30.5MB/s 
Collecting certifi>=2017.4.17 (from requests~=2.18->cirq)
  Downloading https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 26.6MB/s 
Collecting idna<2.9,>=2.5 (from requests~=2.18->cirq)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 13.4MB/s 
Collecting cycler>=0.10 (from matplotlib~=2.2->cirq)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib~=2.2->cirq)
  Using cached https://files.pythonhosted.org/packages/de/0a/001be530836743d8be6c2d85069f46fecf84ac6c18c7f5fb8125ee11d854/pyparsing-2.3.1-py2.py3-none-any.whl
Collecting python-dateutil>=2.1 (from matplotlib~=2.2->cirq)
  Using cached https://files.pythonhosted.org/packages/74/68/d87d9b36af36f44254a8d512cbfc48369103a3b9e474be9bdfe536abfc45/python_dateutil-2.7.5-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib~=2.2->cirq)
  Using cached https://files.pythonhosted.org/packages/68/f2/21ec13269a420c063a3d7d8c87dac030da7b00fc6b27fa88cfb1c72a645b/kiwisolver-1.0.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pytz (from matplotlib~=2.2->cirq)
  Downloading https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 4.0MB/s 
Collecting cachetools>=2.0.0 (from google-auth>=1.4.1->google-api-python-client~=1.6->cirq)
  Downloading https://files.pythonhosted.org/packages/39/2b/d87fc2369242bd743883232c463f28205902b8579cb68dcf5b11eee1652f/cachetools-3.1.0-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from google-auth>=1.4.1->google-api-python-client~=1.6->cirq)
  Downloading https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.2.1 (from google-auth>=1.4.1->google-api-python-client~=1.6->cirq)
  Downloading https://files.pythonhosted.org/packages/da/98/8ddd9fa4d84065926832bcf2255a2b69f1d03330aa4d1c49cc7317ac888e/pyasn1_modules-0.2.4-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 16.9MB/s 
Collecting pyasn1>=0.1.3 (from rsa>=3.1.4->google-auth>=1.4.1->google-api-python-client~=1.6->cirq)
  Downloading https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl (73kB)
    100% |████████████████████████████████| 81kB 18.8MB/s 
Installing collected packages: six, protobuf, decorator, networkx, httplib2, cachetools, pyasn1, rsa, pyasn1-modules, google-auth, uritemplate, google-auth-httplib2, google-api-python-client, sortedcontainers, numpy, scipy, typing-extensions, chardet, urllib3, certifi, idna, requests, cycler, pyparsing, python-dateutil, kiwisolver, pytz, matplotlib, cirq
  Running setup.py install for networkx ... done
  Running setup.py install for httplib2 ... done
  The scripts pyrsa-decrypt, pyrsa-encrypt, pyrsa-keygen, pyrsa-priv2pub, pyrsa-sign and pyrsa-verify are installed in '/Users/unomahaqcl/Library/Python/3.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The scripts f2py, f2py3 and f2py3.7 are installed in '/Users/unomahaqcl/Library/Python/3.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script chardetect is installed in '/Users/unomahaqcl/Library/Python/3.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed cachetools-3.1.0 certifi-2018.11.29 chardet-3.0.4 cirq-0.4.0 cycler-0.10.0 decorator-4.3.2 google-api-python-client-1.7.8 google-auth-1.6.2 google-auth-httplib2-0.0.3 httplib2-0.12.0 idna-2.8 kiwisolver-1.0.1 matplotlib-2.2.3 networkx-2.2 numpy-1.16.1 protobuf-3.6.1 pyasn1-0.4.5 pyasn1-modules-0.2.4 pyparsing-2.3.1 python-dateutil-2.7.5 pytz-2018.9 requests-2.21.0 rsa-4.0 scipy-1.2.0 six-1.12.0 sortedcontainers-2.1.0 typing-extensions-3.7.2 uritemplate-3.0.0 urllib3-1.24.1
You are using pip version 18.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(env) Konetis-MacBook-Pro:~ unomahaqcl$ cd /Users/unomahaqcl/Library/Python/3.7/bin
(env) Konetis-MacBook-Pro:bin unomahaqcl$ python3 -m venv env
(env) Konetis-MacBook-Pro:bin unomahaqcl$ source ./env/bin/activate
(env) Konetis-MacBook-Pro:bin unomahaqcl$ python -c 'import cirq; print(cirq.google.Foxtail)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cirq'
(env) Konetis-MacBook-Pro:bin unomahaqcl$ pip install --user cirq
Collecting cirq
  Using cached https://files.pythonhosted.org/packages/99/b7/df9b3297b5ef6e03e31ea86ed7f3532a5b386002365a983536881f9f272c/cirq-0.4.0-py3-none-any.whl
Collecting matplotlib~=2.2 (from cirq)
  Using cached https://files.pythonhosted.org/packages/ee/c4/bf82dc7ee81ac798cd64d8ec0884c07d59f82f45f4faf878a860c1c1d487/matplotlib-2.2.3-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting networkx~=2.1 (from cirq)
  Using cached https://files.pythonhosted.org/packages/f3/f4/7e20ef40b118478191cec0b58c3192f822cace858c19505c7670961b76b2/networkx-2.2.zip
Collecting requests~=2.18 (from cirq)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting sortedcontainers~=2.0 (from cirq)
  Using cached https://files.pythonhosted.org/packages/13/f3/cf85f7c3a2dbd1a515d51e1f1676d971abe41bba6f4ab5443240d9a78e5b/sortedcontainers-2.1.0-py2.py3-none-any.whl
Collecting typing-extensions (from cirq)
  Using cached https://files.pythonhosted.org/packages/0f/62/c66e553258c37c33f9939abb2dd8d2481803d860ff68e635466f12aa7efa/typing_extensions-3.7.2-py3-none-any.whl
Collecting numpy~=1.12 (from cirq)
  Using cached https://files.pythonhosted.org/packages/46/e4/4a0cc770e4bfb34b4e10843805fef67b9a94027e59162a586c776f35c5bb/numpy-1.16.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting protobuf~=3.5 (from cirq)
  Using cached https://files.pythonhosted.org/packages/18/e7/785830a65d1f1faba7dccfa8314f7afded1db8cc2860218226ba4b3f6150/protobuf-3.6.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting scipy (from cirq)
  Using cached https://files.pythonhosted.org/packages/c2/7b/370891c7686e598c59890588722c1d1c2b485953c4b127b7b752accbddb6/scipy-1.2.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting google-api-python-client~=1.6 (from cirq)
  Using cached https://files.pythonhosted.org/packages/55/e9/e8fb2e3a031cb69b9524b80a92b126665d9a17421700a219555e3233ab6a/google_api_python_client-1.7.8-py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib~=2.2->cirq)
  Using cached https://files.pythonhosted.org/packages/68/f2/21ec13269a420c063a3d7d8c87dac030da7b00fc6b27fa88cfb1c72a645b/kiwisolver-1.0.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting python-dateutil>=2.1 (from matplotlib~=2.2->cirq)
  Using cached https://files.pythonhosted.org/packages/74/68/d87d9b36af36f44254a8d512cbfc48369103a3b9e474be9bdfe536abfc45/python_dateutil-2.7.5-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib~=2.2->cirq)
  Using cached https://files.pythonhosted.org/packages/de/0a/001be530836743d8be6c2d85069f46fecf84ac6c18c7f5fb8125ee11d854/pyparsing-2.3.1-py2.py3-none-any.whl
Collecting pytz (from matplotlib~=2.2->cirq)
  Using cached https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl
Collecting six>=1.10 (from matplotlib~=2.2->cirq)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting cycler>=0.10 (from matplotlib~=2.2->cirq)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting decorator>=4.3.0 (from networkx~=2.1->cirq)
  Using cached https://files.pythonhosted.org/packages/f1/cd/7c8240007e9716b14679bc217a1baefa4432aa30394f7e2ec40a52b1a708/decorator-4.3.2-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests~=2.18->cirq)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests~=2.18->cirq)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests~=2.18->cirq)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests~=2.18->cirq)
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./env/lib/python3.7/site-packages (from protobuf~=3.5->cirq) (40.6.2)
Collecting httplib2<1dev,>=0.9.2 (from google-api-python-client~=1.6->cirq)
  Using cached https://files.pythonhosted.org/packages/ce/ed/803905d670b52fa0edfdd135337e545b4496c2ab3a222f1449b7256eb99f/httplib2-0.12.0.tar.gz
Collecting google-auth-httplib2>=0.0.3 (from google-api-python-client~=1.6->cirq)
  Using cached https://files.pythonhosted.org/packages/33/49/c814d6d438b823441552198f096fcd0377fd6c88714dbed34f1d3c8c4389/google_auth_httplib2-0.0.3-py2.py3-none-any.whl
Collecting google-auth>=1.4.1 (from google-api-python-client~=1.6->cirq)
  Using cached https://files.pythonhosted.org/packages/4e/85/71b2dfbf5b4241cd031cc333ed71f90a271074a97cb2c517bb65f07a1a90/google_auth-1.6.2-py2.py3-none-any.whl
Collecting uritemplate<4dev,>=3.0.0 (from google-api-python-client~=1.6->cirq)
  Using cached https://files.pythonhosted.org/packages/e5/7d/9d5a640c4f8bf2c8b1afc015e9a9d8de32e13c9016dcc4b0ec03481fb396/uritemplate-3.0.0-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.2.1 (from google-auth>=1.4.1->google-api-python-client~=1.6->cirq)
  Using cached https://files.pythonhosted.org/packages/da/98/8ddd9fa4d84065926832bcf2255a2b69f1d03330aa4d1c49cc7317ac888e/pyasn1_modules-0.2.4-py2.py3-none-any.whl
Collecting cachetools>=2.0.0 (from google-auth>=1.4.1->google-api-python-client~=1.6->cirq)
  Using cached https://files.pythonhosted.org/packages/39/2b/d87fc2369242bd743883232c463f28205902b8579cb68dcf5b11eee1652f/cachetools-3.1.0-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from google-auth>=1.4.1->google-api-python-client~=1.6->cirq)
  Using cached https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting pyasn1<0.5.0,>=0.4.1 (from pyasn1-modules>=0.2.1->google-auth>=1.4.1->google-api-python-client~=1.6->cirq)
  Using cached https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl
Installing collected packages: kiwisolver, six, python-dateutil, pyparsing, pytz, numpy, cycler, matplotlib, decorator, networkx, urllib3, idna, chardet, certifi, requests, sortedcontainers, typing-extensions, protobuf, scipy, httplib2, pyasn1, pyasn1-modules, cachetools, rsa, google-auth, google-auth-httplib2, uritemplate, google-api-python-client, cirq
  The scripts f2py, f2py3 and f2py3.7 are installed in '/Users/unomahaqcl/Library/Python/3.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Running setup.py install for networkx ... done
  The script chardetect is installed in '/Users/unomahaqcl/Library/Python/3.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Running setup.py install for httplib2 ... done
  The scripts pyrsa-decrypt, pyrsa-encrypt, pyrsa-keygen, pyrsa-priv2pub, pyrsa-sign and pyrsa-verify are installed in '/Users/unomahaqcl/Library/Python/3.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed cachetools-3.1.0 certifi-2018.11.29 chardet-3.0.4 cirq-0.4.0 cycler-0.10.0 decorator-4.3.2 google-api-python-client-1.7.8 google-auth-1.6.2 google-auth-httplib2-0.0.3 httplib2-0.12.0 idna-2.8 kiwisolver-1.0.1 matplotlib-2.2.3 networkx-2.2 numpy-1.16.1 protobuf-3.6.1 pyasn1-0.4.5 pyasn1-modules-0.2.4 pyparsing-2.3.1 python-dateutil-2.7.5 pytz-2018.9 requests-2.21.0 rsa-4.0 scipy-1.2.0 six-1.12.0 sortedcontainers-2.1.0 typing-extensions-3.7.2 uritemplate-3.0.0 urllib3-1.24.1
You are using pip version 18.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(env) Konetis-MacBook-Pro:bin unomahaqcl$ pip freeze
(env) Konetis-MacBook-Pro:bin unomahaqcl$ source ./env/bin/activate
(env) Konetis-MacBook-Pro:bin unomahaqcl$ pip freeze
(env) Konetis-MacBook-Pro:bin unomahaqcl$ python -c 'import cirq; print(cirq.google.Foxtail)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cirq'

**Comment by pradeep6** [comment]
I am completely new to Cirq, am I doing something completely wrong? Please guide me. 

FYI: Initially, when I tried to install Cirq. I got Permission error. So I have included --user in my installation command. Am I facing this issue due to that change?

**Comment by Strilanc** [comment]
I think the issue is that when you pass `--user` to pip it is installing it somewhere different than in the virtual environment. When you `pip install cirq` after running `source ./env/bin/activate` you still get a permission error?

Try this:

```
source ./env/bin/activate
python -m pip install cirq
python -c 'import cirq; print(cirq.google.Foxtail)'
```

If that works, then I think we need to update all our docs to use `python -m pip` instead of just `pip`. I've seen it be more reliable in the past.

**Comment by pradeep6** [comment]
Hi Guys, When I am trying to run the same commands from pycharm. I am getting the below error. Can you please help me with this?

/Users/unomahaqcl/PycharmProjects/untitled/venv/bin/python cirq
/Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'cirq': [Errno 2] No such file or directory

Process finished with exit code 2

**Comment by Strilanc** [comment]
Why would you expect `python cirq` to do something? You're asking python to invoke a file named cirq.
