### ISSUE TITLE
Implement ControlledOperation._apply_unitary_

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1337]
- Copy over the implementation from ControlledGate and tweak it to work in the new context
- Then rewrite ControlledGate's apply unitary to delegate to ControlledOperation's

**Comment by balopat** [comment]
Happy to pick this up.

**Comment by balopat** [comment]
I understand the first bit :) 
The second bit I have a problem with - not sure how to delegate to ControlledOperation's method as `ApplyUnitaryArgs` only knows the indices of the qubits - hence there are no actual qubits passed to  `_apply_unitary_` - how do I create an `ControlledOperation` instance without qubits from the gate? Maybe I'm missing something and qubits can be recovered from `ApplyUnitaryArgs`?

**Comment by balopat** [comment]
#1346 has the first bit done.

**Comment by Strilanc** [comment]
You can just make some arbitrary qubits, e.g. `LineQubit.range(...)`. Alternatively, you can extract into a common utility method and call that.
