### ISSUE TITLE
Make OS specific dev install instructions

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1347]
Currently we assume a unix environment https://cirq.readthedocs.io/en/stable/development.html

**Comment by Strilanc** [comment]
We should also try to simplify the install, e.g. not depend on virtualenvwrapper and use a similar process to openfermioncirq where we leverage pip's -e argument.

**Comment by dabacon** [comment]
Do we have a handle on how these install instructions should differ?

I think we already recommend using `pip -e` in recommendations.

**Comment by balopat** [comment]
Duplicate of #1121.
