### ISSUE TITLE
EigenGate assumes a certain set of constructor parameters for all subclasses

### ISSUE THREAD

**Issue by verult** [quantumlib/Cirq#1354]
The logic here assumes that subclasses have `exponent` and `global_shift` constructor parameters, no more no less. Is that intentional?

https://github.com/quantumlib/Cirq/blob/dc1294f54118a9a4f92546ca13780b91615dd675/cirq/ops/eigen_gate.py#L118-L122

**Comment by c-poole** [comment]
The documentation for that method explicitly states that child classes should override that method if the constructor signature is different.

**Comment by verult** [comment]
Sorry didn't see that, thanks!
