### ISSUE TITLE
Measurement should implement channel

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#1356]
Because it is a channel.

**Comment by dabacon** [comment]
Proposal:

If a gate implements channel and measurement_key, then when simulated it will record results in measurements and outputs will be conditional on this.  If it only implements channel, then the measurement results are not recorded, and outputs will need to be at least density matrices but recording that the information was not recorded.

**Comment by Strilanc** [comment]
If a measurement is not recorded, and you are performing a density simulation, do we randomly pick one of the outcome branches (project to one of the poles) or do we keep going with a mixture of both (project to the Z axis)?

**Comment by Strilanc** [comment]
@dabacon verify if this is done

**Comment by Strilanc** [comment]
@dabacon says done
