### ISSUE TITLE
Channels should support keys for labeling outcomes during simulations

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#1357]
there should be a way to get results out during simulation

**Comment by dabacon** [comment]
Adding _measurement_key_ protocol.

**Comment by dabacon** [comment]
There is a concrete proposal to move to a protocol `_acts_on_` and this would be fixed as part of this.

**Comment by 95-martin-orion** [comment]
Absorbing into #3566 to capture more recent discussion.

**Comment by 95-martin-orion** [comment]
Duplicate of #3566
