### ISSUE TITLE
Test display methods in abstract classes

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#1359]
Right now the compute_displays_sweep methods are only tested via a test on an impl.  This can cause a problem if the interface needs to be refactored, in that the impl may satisfy the contract that the methods need, but the interface may no longer obey that contract.  Adding a single test for the methods that rely on the abstract classes will avoid that and make refactoring code safe and easier.

**Comment by Ashalynd** [comment]
Is this about adding a test for compute_displays_sweep in SimulatesIntermediateWaveFunction class?

**Comment by Strilanc** [comment]
I think @dabacon means that we should have tests that take a proposed implementation and exercise it to verify that they satisfy the interface's contract. For example, we have generic gate tests that check that things like `_unitary_` and `_decompose_` are returning consistent results.

**Comment by dabacon** [comment]
Displays are no longer supported.  Closing.
