### ISSUE TITLE
Use math.gcd in eigengate?

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#1370]
My pytest in verbose mode is dominated by a trillion of these warnings.  Was there a reason we were not using math.gcd()?  (3to2 problem?)
```
/tmp/test-cirq-yd_i4r4g/cirq/ops/eigen_gate.py:325: DeprecationWarning: fractions.gcd() is deprecated. Use math.gcd() instead.
  t = t * r // fractions.gcd(t, r)
```

**Comment by vtomole** [comment]
I know that we didn't get this before verbose mode on Travis because we were using an old version of pytest. Since updating pytest to `3.8` to be able to run  `pytest-benchmark` (https://pytest-benchmark.readthedocs.io/en/latest/index.html), we now see them.

**Comment by dabacon** [comment]
Changing it to math.gcd makes a test fail :(

**Comment by Strilanc** [comment]
It's because of the python 2 compatibility.

... we could consider dropping that, now that e.g. numpy is dropping it. There's a lot more momentum away from it.
