### ISSUE TITLE
Drop support for Python 2

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#1372]
Some third party libraries that Cirq uses are phasing out Python 2 support (https://github.com/quantumlib/Cirq/issues/1370). I think we should do the same.

See https://github.com/quantumlib/Cirq/issues/731 for opposing arguments.

**Comment by Strilanc** [comment]
@babbush what is your opinion on this? Do you think openfermion users are still very attached to python 2?

**Comment by hugovk** [comment]
Python 2.7 is EOL on 2020-01-01.

See https://python3statement.org/#sections30-projects for a list of projects which have pledged to drop support in or before 2020.

**Comment by babbush** [comment]
OpenFermion users would probably survive if we dropped python 2 support. If we do this can we also drop 3.4 and 3.5 support and just focus on 3.6? I'm also curious what @jarrodmcc and @ncrubin think.

**Comment by babbush** [comment]
I mean if numpy is dropping python 2 support in 2020 then we'd have no business maintaining it!

**Comment by hugovk** [comment]
> If we do this can we also drop 3.4 and 3.5 support and just focus on 3.6?

At least Python 3.4 is EOL next month (2019-03-16), and I've seen a few other projects also ditching 3.5 to make full use of the new features in 3.6+.

**Comment by ncrubin** [comment]
I would hope all new users would opt for python3 development but I don't think it's too large a problem to support python2 until EOL.  Given the tooling we have for testing in a python2 environment it's not too much of a burden to develop 3.6 code without features that can be translated back to 2.7 (for example, this means don't use @ for matrix multiplication).  

As for the numpy argument...sure...but...tensorflow still supports 2.7, 3.3-6 . :)

**Comment by hugovk** [comment]
TensorFlow is also dropping 2.7 on 2020-01-01.

https://github.com/python3statement/python3statement.github.io/pull/179

**Comment by Strilanc** [comment]
It sounds like 2020-01-01 is a Schelling point for dropping support. I vote we drop it then.

**Comment by vtomole** [comment]
We've decided to drop earlier than 2020 (next release) if no one complains.

**Comment by vtomole** [comment]
@dabacon @Strilanc @viathor  

Anything we've missed?

**Comment by Strilanc** [comment]
I think this is done enough to close. Whatever's left can be eroded gradually.

Good job victory!
