### ISSUE TITLE
Density matrix simulator should be optimized for terminal measurements

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#1381]
similar to other simulators.

**Comment by Strilanc** [comment]
Instead of running the density simulation once per repetition, run it once and then sample from the final density matrix multiple times. Works almost exactly the same as in the sparse wavefunction simulator; there is existing code to sample from the density matrix.

**Comment by balopat** [comment]
I'm happy to look into this, it seems doable in 2 weeks.
