### ISSUE TITLE
Add Monte-Carlo simulation

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#1383]

**Comment by Strilanc** [comment]
Needs to allow ability to input mixed states (as in https://github.com/quantumlib/Cirq/issues/1287 )

**Comment by dabacon** [comment]
This is done to a first order.

There is some future work that we could do: for projective measurements outside of the computational basis we could support these as stochastic simulation.

We could also make it easy to run distributed versions of this code.
