### ISSUE TITLE
Sweeps such as `cirq.Linspace` should accept `sympy.Symbol`s (by turning them into strings)

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1397]
This code, which currently causes exceptions:

```python
var = sympy.Symbol('x')
return cirq.Linspace(var, 0, np.pi, 100)
```

should have the equivalent behavior as this code:

```python
return cirq.Linspace('x', 0, np.pi, 100)
```

via `Linspace` checking for `sympy.Symbol` and calling `str` on it to get the actual key if so.

**Comment by vtomole** [comment]
I'll take this.

**Comment by timothyman** [comment]
@vtomole Feel free to completely ignore this, if you have spent significant time on this already, but I have a pull request ready to go for this. I can wait for the next "good first issue", no problem.

I have a question about my implementation, though. Right now I do a type-check whether the `key` is of `sympy.Symbol` before calling `str`, but I'm wondering if that is at all necessary? Anything can be used as a `key`, as long as it's a string? Can we just call `str` on any input?

**Comment by vtomole** [comment]
@timothyman It's yours!

**Comment by timothyman** [comment]
Thanks, @vtomole!

**Comment by Strilanc** [comment]
@timothyman I would avoid just calling `str` on the input, because that will mask mistakes where a nonsensical value is entered. Also, it would do things like cause the number 1 and the qubit LineQubit(1) to map down to the same thing, which is probably not desirable.
