### ISSUE TITLE
cirq/sim/sparse_simulator_test::test_simulate_random_unitary is flaky

### ISSUE THREAD

**Issue by bryano** [quantumlib/Cirq#1425]
Sometimes compares unitaries that are equal only to 6 decimals rather than the specified 7.

**Comment by bryano** [comment]
In pytest2, in case that's relevant.

**Comment by vtomole** [comment]
Please re-open if you are able to reproduce this and still want it solved then leave a comment on how you setup your environment so that i may do the same.

**Comment by vtomole** [comment]
Got it: This is what's happening: https://travis-ci.com/quantumlib/Cirq/jobs/206539331

```python
import numpy as np

a = np.array([ 0.85355335+0.35355335j,  0.14644665-0.35355335j,
         0.35355335+0.1464466j , -0.35355335+0.85355324j])

b = np.array([ 0.85355339+0.35355339j,  0.14644661-0.35355339j,
         0.35355339+0.14644661j, -0.35355339+0.85355339j])

np.testing.assert_almost_equal(a, b), decimals=6) # passes
np.testing.assert_almost_equal(a, b) # fails

```

I'm going to change it to 6 decimal places to fix.
