### ISSUE TITLE
sparse_simulator should allow np.complex256

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1426]
But note that this field doesn't exist on windows, so we need to do a check in a way that won't fail when np.complex256 doesn't exist (e.g. by using `getattr`)

**Comment by tanujkhattar** [comment]
@95-martin-orion Can you mark this as pre/post 1.0?

**Comment by 95-martin-orion** [comment]
Actually just going to close this - experiments since this was posted indicate that increasing float precision does not significantly improve simulation fidelity.
