### ISSUE TITLE
cannot import name 'TYPE_CHECKING'

### ISSUE THREAD

**Issue by omarcostahamido** [quantumlib/Cirq#1427]
I need to run python 3.5.1
everytime I start with simple import cirq, I get:
ImportError: cannot import name 'TYPE_CHECKING'

Any ideas?

**Comment by vtomole** [comment]
`TYPE_CHECKING` is not available in `python 3.5.1`(https://github.com/sphinx-doc/sphinx/issues/4725#issuecomment-372331201). Please upgrade your Python interpreter.

@Strilanc  Should we support these Python versions hence reverting `TYPE_CHECKING`?  I found some Sphinx code that does it: https://github.com/sphinx-doc/sphinx/pull/4735/files

**Comment by Strilanc** [comment]
Hi @omarcostahamido,

Unfortunately, I think this issue will be resolved by adding version 3.5.0 and 3.5.1 to the unsupported versions lists in `setup.py`. Thank you for letting us know this incompatibility was present. We use `TYPE_CHECKING` pretty extensively and don't intend to remove it. The type information we expose won't work without it (or at least won't work as well).

My recommended workaround is to update your version of python, which presumably requires fixing whatever is forcing you to use 3.5.1.
