### ISSUE TITLE
Doc string of CZPowGate: definition of g

### ISSUE THREAD

**Issue by andyliphys** [quantumlib/Cirq#1448]
The doc string states that the unitary matrix of `CZPowGate(exponent=t)` is:

    [[1, 0, 0, 0],
     [0, 1, 0, 0],
     [0, 0, 1, 0],
     [0, 0, 0, g]]

where `g = exp(i·π·t/2)`.

When I try `cirq.CZPowGate(exponent=1.)._unitary_()`, it gives

    array([[ 1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j]])

It appears that the factor g should be `g = exp(i·π·t)` instead, which seems also consistent with the circuit generated from the gate.

PS: I am on cirq v0.4.0.

**Comment by viathor** [comment]
Fixed by #1453.
