### ISSUE TITLE
Make methods like `random_superposition` sample from the Haar measure

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1451]
Currently, the outputs of some of the random_x testing methods are non-uniform over the space of relevant objects. Replaced the biased sampling with an unbiased sampling method.

**Comment by hsim13372** [comment]
Could I possibly work on this? 

If I didn't misunderstand, do we want to sample a Haar random pure state?
If so, I think you can do this by applying a Haar-random unitary to a product state (e.g. all-zero state), but I wasn't sure if this is the most efficient/direct way to do this.

**Comment by c-poole** [comment]
I think the method you propose would work but the issue I see with it is that in order to produce a d-dimensional random quantum state you need to produce a d x d dimensional unitary. Since d is already 2^qubits, this becomes a memory hog very quickly.

**Comment by hsim13372** [comment]
That's a good point. I just didn't know of a more memory-efficient method.

**Comment by c-poole** [comment]
Appendix A of https://arxiv.org/pdf/quant-ph/9804024.pdf gives a method for uniformly sampling the PDF of a N-dimensional quantum state. A PDF doesn't uniquely determine a quantum state, but I would expect that putting i.i.d. uniformly distributed phases on each term should produce a uniform quantum state.

**Comment by kevinsung** [comment]
@Strilanc I think for `random_superposition` you mean that it should sample from the uniform measure, which it already does.

**Comment by hsim13372** [comment]
Hmm I think you're right, @kevinsung. I just checked and convinced myself that the way it's currently implemented is sampled uniformly. 

Maybe the only thing would be a minor documentation fix:

```def random_superposition(dim: int) -> np.ndarray:
    """
    Args:
        dim: Specified size returns a 2^dim length array.
    Returns:
        Normalized random array.
    """
    state_vector = np.random.standard_normal(dim).astype(complex)
    state_vector += 1j * np.random.normal(dim)
    state_vector /= np.linalg.norm(state_vector)
    return state_vector```

changing `dim` to `2**dim` in the code or changing the "2^dim" in the documentation to "dim."

**Comment by Strilanc** [comment]
Oh, it's using a gaussian already? My mistake.

There *is* at least one instead of a TODO saying that code needs to be updated to sample from the Haar measure.

To close this issue, just verify and document that all these methods sample from the Haar measure.

**Comment by hsim13372** [comment]
I verified and documented these methods and made a pull request. 

Just to check, I removed `* 2 - 1` from `m = np.random.randn(dim, dim) * 2 - 1` in the function that generates a random orthogonal matrix. May I ask what the reason for these operations was? I could've been wrong to remove them!
