### ISSUE TITLE
Get rid of MultiQubitGate

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1461]
Now that `Gate` implements a `validate_args` that checks the qubit count, `MultiQubitGate` does nothing but replace `def num_qubits(self): return X` with `super().__init__(X)`, which is not enough to justify its existence.

Find all cases where `MultiQubitGate` is used and replace them with inheritance from just `Gate` with a defined qubit count.

**Comment by balopat** [comment]
I'm happy to pick this up

**Comment by davemc84** [comment]
Hi @balopat - if there is any grunt work associated with this one that you might be looking to offload, I would be more than happy to help out. Please do not hesitate to reach out!

**Comment by balopat** [comment]
Thank you @davemc84 - it wasn't that bad!
