### ISSUE TITLE
HPowGate issues

### ISSUE THREAD

**Issue by yudongcao** [quantumlib/Cirq#1474]
I have been playing with gates such as `cirq.H**0.4` which is a Hadamard gate that is exponentiated:
```python
import cirq
c = cirq.Circuit()
q = cirq.LineQubit(0)
g = cirq.H(q)**0.4
isinstance(g, cirq.HPowGate)
```

I thought this should be an instance of `HPowGate` as defined [here](https://github.com/quantumlib/Cirq/blob/master/cirq/ops/common_gates.py). But the above code returns `False`. Also if we run
```python
c.append(g)
print(c)
```

the result shows `0: ───H───`. What happened to the exponent?

**Comment by Strilanc** [comment]
Oops, the implementation of `HPowGate._circuit_diagram_info_` was not updated when an exponent was added. Thank you for catching this.

**Comment by vtomole** [comment]
So that's the `repr` issue i was referring to here: https://github.com/quantumlib/Cirq/issues/1262. I'll take this.

**Comment by vtomole** [comment]
*Not `repr` but `print`

**Comment by vtomole** [comment]
@yudongcao With respect to `isinstance`,  Your `g` is a `GateOperation` and `HPowGate` a `Gate` I think.
`isinstance(g, cirq.ops.gate_operation.GateOperation)` works.
CC: @Strilanc

**Comment by viathor** [comment]
Re `isinstance` returning `False` above: @vtomole 's explanation is correct.

```python
In [1]: import cirq

In [2]: g = cirq.H**0.4

In [3]: isinstance(g, cirq.HPowGate)
Out[3]: True
```

**Comment by yudongcao** [comment]
I see. So once there is a concrete qubit that the gate is set to act on, the gate object becomes `GateOperation`. What if I want to determine what type of gate a `GateOperation` represents, is there a way to retrieve that information? In other words, if `g = cirq.H(q)**0.4`, what can I do to `g` to know for sure that it comes from an `HPowGate`?

**Comment by viathor** [comment]
Yes, like this:

```python
In [1]: import cirq

In [2]: q = cirq.LineQubit(0)

In [3]: op = cirq.H(q)**0.4

In [4]: isinstance(op, cirq.HPowGate)
Out[4]: False

In [5]: isinstance(op.gate, cirq.HPowGate)
Out[5]: True
```

See also #1472 for a possible new way being added.

**Comment by yudongcao** [comment]
I see. Thanks for your help!
