### ISSUE TITLE
Simplify python_requires procedure

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#1478]
`python_requires=('>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*, !=3.5.0, !=3.5.1')` is easier to read as `python_requires=('>=2.7, >=3.5.2')`.

Thanks @hugovk for the suggestion.

**Comment by hugovk** [comment]
I believe `python_requires=('>=2.7, >=3.5.2')` will still match 3.0 - 3.4 because they're bigger than 2.7.

This simplification can only be done when dropping 2.7:

```python
python_requires=('>=3.5.2')
```

**Comment by vtomole** [comment]
Got it. That's why it was like that.
