### ISSUE TITLE
Make LaTex/PDF images better, stop using qcircuit

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1492]
Currently, Cirq's pdf output is in contrib because it's not particularly good. The margins are messed up, there's no boxing of multiqubit gates, etc, etc. Someone needs to go over this functionality and polish polish polish polish.

For example, we could directly use TIKZ (or some other library) instead of qcircuit (which has serious limitations). We could add boxing information to the diagram info emitted by gates. Etc Etc. This is a very open ended issue.

**Comment by vtomole** [comment]
Look into qpic: https://github.com/quantumlib/Cirq/issues/1290

**Comment by andbe91** [comment]
I might pick this up.

Are there any specifications or requirements of the pdf output? If you could provide some examples of how you would like certain algorithms to be rendered, that would be helpful.

**Comment by Strilanc** [comment]
I don't have any hard concrete specifications, which is part of why I labelled this a "project". Part of it is to decide on a good tradeoff between what is achievable and what looks good.

That being said, here are some specific points that I thought of:

- CNOT gates should turn into a black circle connected to a big circled plus
- CZ gates should be two linked black circles
- Gates from the same moment should appear in the same column if possible. Ideally, there would be an indicator when a moment gets spread over multiple columns (due to linking lines overlapping otherwise).
- op.controlled_by(q) should look reasonable: a black circle on q linked to the rest of op.
- If the qubits of a multi-qubit gate are contiguous and in the right order, you should get a box over them describing the gate.
- If the qubits are contiguous but in the wrong order, or non-contiguous, this needs to be indicated in some reasonable way.
- It should be possible for a gate to describe itself as multiple separate boxes. For example, an addition has an input and an output and they do not have to be contiguous with each other. Similarly, swapping two blocks have qubits has two clear separated parts.
- The latex output should be derived from the same diagram info as the text diagram output. This likely requires extending this diagram info to include more information.

**Comment by dabacon** [comment]
Let's track this here and close #1290

**Comment by tanujkhattar** [comment]
Also tracked in https://github.com/quantumlib/Cirq/issues/5895, closing this is as duplicate
