### ISSUE TITLE
float128 not supported on my Windows Anaconda

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#1511]
```(base) C:\>python
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.array([1,1,1],dtype=np.float128)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'numpy' has no attribute 'float128'
>>>
```

@c-poole I ran into this while running pytest on my Windows. Does pytest pass for you on Windows?

**Comment by vtomole** [comment]
This seems to be a win32 bug: https://github.com/winpython/winpython/issues/613

**Comment by vtomole** [comment]
I suggest we replace `np.float128` with `np.longdouble` and `np.complex256` with `np.clongdouble`. These won't change anything on Linux but it will give us `np.float64` and `np.complex128` on Windows and won't break tests on Windows builds (this change also depends on how many devs we have on Windows ).

Kind of related: @Strilanc  Should we add a Windows build on our Travis?

**Comment by LuisM78** [comment]
Hi, Is there a solution for this problem? I am using Windows 10. can you please point me to the right install for numpy? 
Thanks,
Luis

**Comment by vtomole** [comment]
We already solved this; by not using float128. What commands are you getting to run into this error?

**Comment by LuisM78** [comment]
Hi, I am using in a function.
def softmax(x):
    x = np.array(x, dtype=np.float128)
    e_x = np.exp(x)
    return e_x / e_x.sum(axis=0) 

I have np version 1.15.4

**Comment by vtomole** [comment]
The snippet you posted doesn't use Cirq.

**Comment by LuisM78** [comment]
yes, sorry... 
I couldn't figure out how to do it in Windows. So I switched to an Ubuntu virtual box and created a python environment with the specific pip requirements and versions ... and problem solved...
Thank you!
Luis

**Comment by hafez-ahmad** [comment]
any support for windows 10 and python 3.8, I am getting the same error.
AttributeError: module 'numpy' has no attribute 'float128'

**Comment by balopat** [comment]
@hafez-ahmad can you share the code you're using where you're running into this using Cirq?

**Comment by hafez-ahmad** [comment]
@balopat here it is https://github.com/josuemtzmo/trackeddy/issues/9

**Comment by vtomole** [comment]
@hafez-ahmad  That code doesn't use Cirq.
