### ISSUE TITLE
Give a descriptive error when asked to simulate a circuit with unresolved parameters

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1515]
I think the reason https://github.com/quantumlib/Cirq/issues/1514 was reported as a bug is because the current error that results from this mistake is so bad that it looks like a bug in cirq. Both cirq.Simulator and cirq.google.XmonSimulator should check if `cirq.is_parameterized(circuit)` before continuing into the numerical simulation, and if so then raise an exception describing the problem.

This error should raise both when attempting to `run` a parameterized circuit (e.g. you forgot to use `run_sweep`) and when sweeping and you forget a parameter.

**Comment by Strilanc** [comment]
Here is a repro:

```
import cirq
import sympy.abc
q = cirq.LineQubit(0)
c = cirq.Circuit.from_ops(cirq.X(q)**sympy.abc.x)
cirq.Simulator().run(c)
```

Errors with this:

```
TypeError: Can't simulate operations that don't implement SupportsUnitary, SupportsApplyUnitary, SupportsMixture, SupportsChannel or is a measurement: (cirq.X**sympy.Symbol('x')).on(cirq.LineQubit(0))
```

But should actually error with this:

```
ValueError: Can't simulate. Circuit has unresolved parameterized operations. Check that you passed a parameter resolver, and that it specifies all the necessary parameters.

Here are the unresolved operations: [...]
```

**Comment by davemc84** [comment]
Thanks very much for the context @Strilanc.  I would be more than happy to give this one a try.

**Comment by Strilanc** [comment]
It's all yours!
