### ISSUE TITLE
Raise an error when attempting to sample a circuit with no measurements

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1519]
Should apply in the SparseSimulator, DensitySimulator, WaveFunctionSimulator, and XmonSimulator.

Introduce a utility method `has_measurements` on `Circuit` to avoid too much code duplication.

**Comment by dabacon** [comment]
This code is in run?

**Comment by Strilanc** [comment]
Could you point at it? When I run a circuit with no measurements I just get an empty trial result. For example, `cirq.Simulator().run(cirq.Circuit())` produces no error.

**Comment by dabacon** [comment]
Whah?  I was asking whether you want to put this in the "run*" methods?  

Yeah current behavior is that no measurements produce an empty trial result.

**Comment by Strilanc** [comment]
Oh, I thought you were asking "is this code in run".

Yes, I think it should be limited to the `run` methods, because the `simulate` methods have useful outputs when given no measurements.

**Comment by smitsanghavi** [comment]
I can take this.

**Comment by smitsanghavi** [comment]
@Strilanc I'm curious, you listed these 4 Simulators specifically. What kind of simulators should not throw error here? Is there an underlying property here that we can use in a parent class itself?

**Comment by Strilanc** [comment]
I was just trying to list them all. I think this applies globally to any simulator, as long as we're talking about sampling the measurement results.
