### ISSUE TITLE
Is it possible to start a simulation with a random initial state?

### ISSUE THREAD

**Issue by bpcarlos** [quantumlib/Cirq#1521]
Wondering if I can create a random initial state by modifying the 2^n vector amplitudes (instead of starting every simulation at |000...00>) and then apply quantum gates to this state.

**Comment by vtomole** [comment]
Hi @bpcarlos. We use Github issues for tracking requests and bugs. Please copy and paste this question to the [Quantum Computing Stack Exchange](https://quantumcomputing.stackexchange.com/) with a `cirq` tag.

Thank you,
Victory

**Comment by bpcarlos** [comment]
OK, thank you @vtomole

**Comment by vtomole** [comment]
Hey @bpcarlos, does this [answer](https://quantumcomputing.stackexchange.com/a/5902/362) work for you?
