### ISSUE TITLE
mux's sample runs wrong simulator

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#1543]
Currently mux's sample checks "has_unitary" on a circuit.  That does a check to see if the measurements are all terminal and if not, returns false.  But this is not correct for deciding to use sparse simulator: if the measurements in the middle are there the sparse simulator will be faster because it is doing a pure state simulation.  

The use of asking about terminal measurements in _has_unitary_ feels a bit wrong to me (it was unexpected for me when tracking this down).

**Comment by dabacon** [comment]
Oh this also will pick the wrong one for Monte Carlo simulation.

**Comment by dabacon** [comment]
@Strilanc thoughts on the has_unitary method on circuit?

**Comment by Strilanc** [comment]
Hmm I see. I thought that I was calling the purely wavefunction simulator. I still don't really get what you mean when you say "sparse" in the name.

Is there any situation where we would want to perform a density matrix simulation?

**Comment by dabacon** [comment]
Sparse refers to that you are not keeping the unitary in memory (so sparse matrix multiplication).  We could rename PureStateSimulator.

You want density matrix simulation when you want an actual density matrix, or the channel cannot be a mixture (generalized phase damping, for instance).

**Comment by Strilanc** [comment]
`PureStateSimulator` would be much better.

**Comment by dabacon** [comment]
This looks to be fixed.
