### ISSUE TITLE
Add examples that use PauliString on readthedocs

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#1550]
Since we are slowly moving it out of `contrib`, we need to have a paragraph or two in the readthedocs that explains it.

**Comment by RankJay** [comment]
Hi @vtomole ,
I would like contribute by solving this issue, if it's still open.

**Comment by RankJay** [comment]
Hi @vtomole,
can you once share the link of readthedocs and PauliString file, I am unable to find it.
Thanks for your assistance.

**Comment by vtomole** [comment]
Here are the docs: https://github.com/quantumlib/Cirq/tree/master/docs.
Here is pauli string: https://github.com/quantumlib/Cirq/blob/master/cirq/ops/pauli_string.py

**Comment by vtomole** [comment]
Fixed by https://github.com/quantumlib/Cirq/pull/3654
