### ISSUE TITLE
check/format-incremental not matching Travis

### ISSUE THREAD

**Issue by bryano** [quantumlib/Cirq#1580]
Locally, check/format-incremental says no changes needed, but on Travis:
```
-            [] if horizontal_lines is None else
-            list(horizontal_lines))  # type: List[_HorizontalLine]
+            [] if horizontal_lines is None else list(horizontal_lines)
+        )  # type: List[_HorizontalLine]
```

**Comment by bryano** [comment]
Lots more examples if needed.

**Comment by vtomole** [comment]
Could you please link to the file that does this so i may reproduce it?

**Comment by bryano** [comment]
The most recent commit on #1236 passes the formatting test on Travis, but check/format-incremental returns a lot of suggested changes.

**Comment by bryano** [comment]
For the inverse (passing locally but failing on Travis), see the immediately prior commits.

**Comment by Strilanc** [comment]
What version of yapf are you using?

**Comment by bryano** [comment]
0.27.0

**Comment by Strilanc** [comment]
I'm able to reproduce this locally. This is a duplicate of https://github.com/quantumlib/Cirq/issues/1598 . If you sync with master (`git pull upstream master`) the problem will go away.
