### ISSUE TITLE
Proposal: Remove "pytest (without contrib)" from travis build

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#1586]
What's the reason for https://github.com/quantumlib/Cirq/blob/9f4200874f1867e511f91fe396fe55c57f1c7bdb/.travis.yml#L44 if incremental coverage tests everything?

**Comment by Strilanc** [comment]
The reason is that when we do a release of cirq we don't include the (possibly large) contrib dependencies. If the pytest without contrib fails, that means the package will fail when installed.
