### ISSUE TITLE
Add measurement constraints to xmon_device

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#160]
@maffoo says sets of qubits have to be measured at the same time as each other always.

**Comment by vtomole** [comment]
Hey @maffoo, how's this going?

**Comment by vtomole** [comment]
Pinging @Strilanc too.

**Comment by vtomole** [comment]
Looks like @mafoo is back, so i'll ping him again :)

**Comment by Strilanc** [comment]
This is de-facto obsolete now. Related: https://github.com/quantumlib/Cirq/pull/2141
