### ISSUE TITLE
Inverted Control Support

### ISSUE THREAD

**Issue by c-poole** [quantumlib/Cirq#1601]
In practice implementing an inverted control is as simple as sandwiching the control in your controlled gate that you want inverted with X gates, but some qubit architectures (neutral atoms being one that I'm aware of) that support multiple controls may also support having some of the controls inverted while others are not. We may want an implementation of this "native" version of an inverted control.

**Comment by Strilanc** [comment]
If someone wants to have a go at generalizing ControlledOperation to include the inversion information, feel free. That would be a reasonable place to start, and we could grow it from there to cover things like the controlled_by protocols.

**Comment by dabacon** [comment]
This is done with concept of `control_values`.  There is a question of a further generalization in which the different basis states are mapped to different operations, but closing this for now.
