### ISSUE TITLE
Dependency error from albumentations in cirq >0.5

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#1607]
In colab.research.google.com in a python3 notebook run
```!pip install cirq==0.5 --quiet```
results in 
```ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.8 which is incompatible.```

**Comment by dabacon** [comment]
So this isn't coming from any of our pip installed components.  

I get it in colab because they have a newer version of imgaug but also albumentations.

**Comment by c-poole** [comment]
I imagine this has persisted into 0.6?

**Comment by dabacon** [comment]
This still exists in 0.8:
`ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.`

**Comment by dabacon** [comment]
Correction, this no longer appears when installing cirq 0.8.  Closing
