### ISSUE TITLE
cirq logo / taglines

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#161]
Let's see everyone's ideas.

e.g. good contributor tagline idea from @DanielSank: "I ran away to join the cirqus"

e.g. bad logo idea: the text "circuit", but a hand has smashed in from the right and dragged down the "u" so it snags on the "c" and bends to form a "q". The remaining "it" falls out of view.

**Comment by dabacon** [comment]
![cirq_logo_color](https://user-images.githubusercontent.com/87974/43107076-40eeb2b0-8e90-11e8-9bc1-08aad0d53ed2.png)
