### ISSUE TITLE
Non-parametrized sympy literals as numbers?

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#1611]
````
 import cirq
 import sympy

 c = cirq.Circuit()
 q = cirq.NamedQubit('q')
 c.append(cirq.Rx(sympy.pi)(q))
 c.append(cirq.Ry(sympy.pi * 2 / sympy.cos(3))(q))   
 cirq.Simulator().run(c) 
 ````
 fails with `Can't simulate unknown operations that don't specify a _unitary_ method, a _decompose_ method, (_has_unitary_ + _apply_unitary_) methods,(_has_mixture_ + _mixture_) methods, or are measurements.: cirq.Rx(sympy.pi).on(cirq.NamedQubit('q'))` -- which could be led back to `if protocols.is_parameterized(rads)` returns `True ` for `sympy.Basic` objects. 

However, as sympy objects are acting most of the time as numbers - the printout of the circuit is

```
 q: ───Rx(pi)───Ry(2*pi/cos(3))───
```

Which is very nice vs the numpy version:

```
 q: ───Rx(π)───Ry(1.9800000000000004π)───
```

Where this came up: when importing QASM files (#1602), the printed circuits look significantly better when the angles read in symbolically. I did convert them to float of course but I feel like we are losing information there.  

Not sure what the implications on performance or functionality, but it looks like something worthwhile to think about as sympy expressions might be more precise/offer more functionality through symbolic manipulation.

What do you think?

**Comment by c-poole** [comment]
I think we can get away with resolving this issue without too much fuss. Instead of returning `True` if we find a `sympy` object, return the `is_number` property of the object in the `is_parametarized` function.
`if isinstace(val, sympy.Basic):
    return val.is_number
`

**Comment by c-poole** [comment]
I just tried my suggestion and surprisingly only one test failed. It was due to numpy complaining about not knowing how to multiply sympy constants with standard numpy data types. This can be patched over by making the appropriate numeric casts inside _apply_unitary_, and _unitary_ for each gate in the repository but that is a bit more fuss than I had originally anticipated. I just tried it with Rx and Ry and got your code snippet to run after adding a measurement to the circuit. I can take this issue if there is interest in this feature. @balopat, @Strilanc , @dabacon thoughts?

**Comment by dabacon** [comment]
I think the proposed solution keeps the meaning of `is_parameterized` clean.  It does however mean that consumes of the objects need to always try to cast numeric values when they are consumed.  It would be good to try the solution to see what those later look like and if they are maintainable / reasonable

**Comment by dabacon** [comment]
Verified that this is still an issue.

**Comment by mpharrigan** [comment]
Should we keep this open?

**Comment by balopat** [comment]
We totally can, there was not much movement on it - if the impact is not too bad on performance with all the casting in `__unitary__` for every parametrizable gate, then we can have this just for the sake of prettier circuit outputs. Do you see this valuable? Why did you comment on it? Just reviewing stale closed issues or because it came up in a use case?
