### ISSUE TITLE
Implement unit test for timedelta for multiplication with floats

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#1618]
https://github.com/quantumlib/Cirq/blob/a38267f0e8791fc325ef4970da56133f2aaf11d4/cirq/schedules/schedule_test.py#L181 is no longer relevant now that we're off Python 2. We should implement this test.

**Comment by timothyman** [comment]
That comment was there to clarify the now missing annotation that that test should not run (and will not pass) in Python 2 because timedelta doesn't support multiplication with floats. The test itself uses that functionality and is passing in Python 3. 

This issue can be closed.
