### ISSUE TITLE
Conditional incoherent amplitude displays are showing wrong magnitudes

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1619]
Example: https://algassert.com/quirk#circuit=%7B%22cols%22%3A%5B%5B%22H%22%2C%22H%22%2C%22H%22%5D%2C%5B%22%E2%80%A2%22%2C%22Z%22%5D%2C%5B%22Amps1%22%5D%2C%5B%5D%2C%5B%22Amps1%22%2C1%2C%22%E2%80%A2%22%5D%2C%5B%5D%2C%5B%22Amps1%22%2C1%2C%22%E2%97%A6%22%5D%5D%7D

![image](https://user-images.githubusercontent.com/79941/57491756-e7a99680-7272-11e9-8a43-c1517e332f84.png)

Adding controls results in the total squared amplitude being less than 100%.

**Comment by vtomole** [comment]
Wong tracker?

**Comment by Strilanc** [comment]
Whoops.
