### ISSUE TITLE
Optimization barrier?

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#164]

**Comment by andyliphys** [comment]
Is there any update with the optimization barrier?

**Comment by dabacon** [comment]
@andyliphys do you have a good use case, we haven't encountered many and wanted to understand before implementing.

**Comment by andyliphys** [comment]
The initial motivation is that when I compile a circuit with measurement gates, it raises an error
```
ValueError: Adjacent Exp11 operations: W(0.325)^0.5287110447050094((1, 1)) and W(0.552)^-0.5270693014384051((1, 2)) and CZ((0, 0), (0, 1)) and XmonMeasurementGate('2')((0, 2)).
```
and I think that an optimization barrier in front of the measurement gates will solve the problem.

Nonetheless, I solved the problem by optimizing the circuit without measurement gates first and then appending the measurement gates to it.
And I agree with you that the optimization barrier is not an urgent feature.

**Comment by andyliphys** [comment]
@dabacon `cirq.google.optimized_for_xmon(circuit, new_device=cirq.google.Foxtail)`

**Comment by Strilanc** [comment]
@andyliphys could you provide code that causes that issue? optimized_for_xmon is not supposed to fail like that in the first place. It may have been fixed by https://github.com/quantumlib/Cirq/issues/795

**Comment by andyliphys** [comment]
```
import cirq
qubit = [cirq.GridQubit(0, 0), cirq.GridQubit(0, 1), cirq.GridQubit(0, 2)]

circuit = cirq.Circuit()
circuit.append([cirq.CZ(qubit[0], qubit[1]), cirq.CZ(qubit[1], qubit[2])])

measure_circuit = cirq.Circuit()
measure_circuit.append([cirq.MeasurementGate(key='0').on(qubit[0]),
                        cirq.MeasurementGate(key='1').on(qubit[1]),
                        cirq.MeasurementGate(key='2').on(qubit[2])])

cirq.google.optimized_for_xmon(circuit, new_device=cirq.google.Foxtail)
cirq.google.optimized_for_xmon(circuit + measure_circuit, new_device=cirq.google.Foxtail)
```

`cirq.google.optimized_for_xmon(circuit, new_device=cirq.google.Foxtail)` works perfectly.
However, `cirq.google.optimized_for_xmon(circuit + measure_circuit, new_device=cirq.google.Foxtail)` gives an error `ValueError: Adjacent Exp11 operations: CZ((0, 1), (0, 2)) and XmonMeasurementGate('0')((0, 0)).`

**Comment by vtomole** [comment]
@andyliphys The program you posted currently runs with no errors on the master branch after some minor adjustments.

```
import cirq
qubit = [cirq.GridQubit(0, 0), cirq.GridQubit(0, 1), cirq.GridQubit(0, 2)]

circuit = cirq.Circuit()
circuit.append([cirq.CZ(qubit[0], qubit[1]), cirq.CZ(qubit[1], qubit[2])])

measure_circuit = cirq.Circuit()
measure_circuit.append([cirq.MeasurementGate(num_qubits=1, key='0').on(qubit[0]),
                        cirq.MeasurementGate(num_qubits=1, key='1').on(qubit[1]),
                        cirq.MeasurementGate(num_qubits=1, key='2').on(qubit[2])])

cirq.google.optimized_for_xmon(circuit, new_device=cirq.google.Foxtail)
cirq.google.optimized_for_xmon(circuit + measure_circuit, new_device=cirq.google.Foxtail)
```

CC: @Strilanc

**Comment by andyliphys** [comment]
@vtomole Thanks. Just check that the bug is fixed in release v0.4.0.

**Comment by vtomole** [comment]
@andyliphys  Nice! Could you please close this then?

**Comment by andyliphys** [comment]
@vtomole I cannot close the issue since it is created by @Strilanc.
