### ISSUE TITLE
Add links to issues next to TODO comments

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#1642]
There're currently ~20 TODOs in the repository.
 For example:
https://github.com/quantumlib/Cirq/blob/7fcda9361a3fb2b58ef914a0fce7573b2a83c6f9/cirq/sim/sparse_simulator.py#L295

We should link to the corresponding issues alongside these TODO comments or create the issues and then link them if they don't exist.

**Comment by Hancockan** [comment]
Assign this to me

**Comment by cjcarey** [comment]
Assign this to me

**Comment by vtomole** [comment]
@cjcarey Creating 20 issues at once might be too much. Open 5 for now. Link to this issue when creating.

**Comment by cjcarey** [comment]
@vtomole I created 5 new issues and made a new pull request for the spelling error. When should I have the rest of the TODO statements completed

**Comment by vtomole** [comment]
@cjcarey Creating that many issues at once was not as spammy as i thought it would be. How about we just finish it all right now?

**Comment by cjcarey** [comment]
I think I got everything.. let me know if I missed something!

**Comment by vtomole** [comment]
@cjcarey That's it. Thanks for doing this.

**Comment by mpharrigan** [comment]
A lot of the issue titles don't make sense out of context

**Comment by vtomole** [comment]
Hey @cjcarey, please add more context to the issues you created. It's a good exercise in learning the code base.

**Comment by dabacon** [comment]
We need to reaudit these todo issues.

**Comment by dabacon** [comment]
I went over all TODO and added issues for all of them.  I also edited the issues to make sure they were clear on the issue.  Closing.
