### ISSUE TITLE
 `Y^-0.5` not being converted to `PhasedX(-0.5)^0.5` on Ion related tests in Windows.

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#1662]
As a reference: https://travis-ci.com/quantumlib/Cirq/jobs/201514754

For ` test_convert_to_ion_circuit`

```
E       AssertionError: Circuit's text diagram differs from the desired diagram.
E
E       Diagram of actual circuit:
E       (0, 0): ───X───────MS(0.25π)───X^-0.5──────────MS(0.25π)───
E                          │                           │
E       (0, 1): ───Y^0.5───MS(0.25π)───Y^-0.5───S^-1───MS(0.25π)───
E
E       Desired text diagram:
E       (0, 0): ───X───────MS(0.25π)───X^-0.5─────────────────────MS(0.25π)───
E                          │                                      │
E       (0, 1): ───Y^0.5───MS(0.25π)───PhasedX(-0.5)^0.5───S^-1───MS(0.25π)───
E
E       Highlighted differences:
E       (0, 0): ───X───────MS(0.25π)───X^-0.5──────────█████████──████████████
E                          │                           ████████████
E       (0, 1): ───Y^0.5───MS(0.25π)───█████████████████████████──████████████

```

For `test_decomposition`
```
E       AssertionError: Circuit's text diagram differs from the desired diagram.
E
E       Diagram of actual circuit:
E       0: ───Y^0.5───Z───MS(0.25π)───Y^-0.5───S^-1───
E                         │
E       1: ───────────────MS(0.25π)───X^-0.5──────────
E
E       Desired text diagram:
E       0: ───Y^0.5───Z───MS(0.25π)───PhasedX(-0.5)^0.5───S^-1───
E                         │
E       1: ───────────────MS(0.25π)───X^-0.5─────────────────────
E
E       Highlighted differences:
E       0: ───Y^0.5───Z───MS(0.25π)───███████████████████████████
E                         │
E       1: ───────────────MS(0.25π)───X^-0.5──────────███████████
```
CC: @mlihc15 , @c-poole

**Comment by c-poole** [comment]
iirc, This discrepancy didn't show up the first time you tried a windows build in Travis. If that is correct, could you provide some detail on what changed between then and now in the build?

**Comment by mlihc15** [comment]
Is it a problem with rendering PhasedX gates in particular or is it a problem with optimizers.merge_single_qubit_gates_into_phased_x_z?

**Comment by vtomole** [comment]
@c-poole These tests weren't in the codebase last time I ran the Windows Travis build (about a month ago).

**Comment by vtomole** [comment]
@mlihc15 Yeah, this probably doesn't have to do with the rendering because the only problem we seem to be having here is `Y^-0.5` not being converted to `PhasedX(-0.5)^0.5`. This seems to be related to Windows somehow.

**Comment by c-poole** [comment]
If you try to construct a `PhasedX(-0.5)^0.5` cirq will recognize that as a `Y^-0.5` and return that instead, but this relies on the -0.5 in the PhasedX passing a float equality comparison, so it isn't too terribly surprising that floating point comparisons are causing system dependent differences. What seems to matter in this test is whether the circuits produced are equivalent and whether they pass the `validate_circuit` method of `ion_device`. I rewrote the tests with this in mind and they pass so I'll put in a PR for it.
