### ISSUE TITLE
Grid or Lattice helper class

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#1671]
There are a lot of very common things you want to do especially in variational algorithms for lattice type models.  
* Give me Operation X between every horizontal bond in two layers.
* Give all single qubit gates on the "even" sublattice
* Iterate over rows, apply same sequence of gates across the column
* etc.
These sort of things sort of belong in device, but it feels like this will be shared across a lot of lattices like devices.

**Comment by vtomole** [comment]
This sounds familiar to what @bryano  has been working on.

**Comment by Strilanc** [comment]
I think this is obsoleted by `GridQubit.rect` existing and general python functionality for looping when creating circuits. Getting into sub-lattices is probably too specialized.
