### ISSUE TITLE
PauliString constructor should accept (but filter out) cirq.I (identity) values

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1675]

**Comment by dabacon** [comment]
I think this shows how PauliString is broken.

I think instead you should make Pauli String know about identities.  I mean it already knows about qubits.  I think we are making the mistake of "implicit" identities being used (which is fine, as far as it goes), and then the current situation where "I" is somehow special.

**Comment by Strilanc** [comment]
It's pretty common for data structures to have a canonical form that they normalize to. In this case our canonical form is "identities are omitted, because otherwise it makes equality and hash codes slower".

Are you advocating for `print(cirq.I(a) * cirq.X(b))` to print out `I(a) * X(b)` instead of `X(b)`?

**Comment by vtomole** [comment]
@Strilanc Is this right?

```
>>> import cirq
>>> a = cirq.LineQubit(1)
>>> b = cirq.LineQubit(2)
>>> print(cirq.I(a) * cirq.X(b))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for *: 'GateOperation' and 'SingleQubitPauliStringGateOperation'
```

**Comment by Strilanc** [comment]
That's an example of what should start working to fix this issue.

**Comment by timothyman** [comment]
I just submitted #1765

**Comment by mpharrigan** [comment]
Does #1765 actually address this, specifically during construction of the `PauliString`?
