### ISSUE TITLE
Follow method style guide for gates

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#1681]
We currently have `cirq.Rx` which is a method, not a gate.  Method names should be snake case.  This is confusing since it makes it seem that `cirq.Rx` is a class name.  Especially considering that users expect there to be a `cirq.Rx` gate and not `cirq.XPowGate`

**Comment by vtomole** [comment]
What is the method style guide? Is it snake case? You are saying that we should rename methods like `cirq.Rx` to a snake case convention?

**Comment by dabacon** [comment]
Yep, methods should be snake_case.

**Comment by viathor** [comment]
#2508 is a duplicate of this issue. I'll close this one since the other one has a more thorough discussion of the conventions we considered.
