### ISSUE TITLE
Raise an error when attempting to sample a circuit with duplicate measurement keys

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1687]
This should be raising an error:

```python
import cirq
q = cirq.LineQubit(0)
c = cirq.Circuit.from_ops(
     cirq.measure(q, key='b'),
     cirq.measure(q, key='a'),
     cirq.measure(q, key='a'))
cirq.sample(c)
```

Instead it returns malformed data:

```
a=00
b=0
```

**Comment by iamvamsikrishnad** [comment]
I'll take a stab at it. Can you please assign it to me.

**Comment by iamvamsikrishnad** [comment]
@Strilanc : Can you please let me know if this sounds okay ?

**Comment by Strilanc** [comment]
That is not sufficient, because operations may be appended into circuits dynamically via append, iadd, etc.

We can either enforce this at the circuit level by checking at all edit points or at the simulator level by checking at all entry points.

I do think we should check in Moment's constructor, as a sanity check.

**Comment by iamvamsikrishnad** [comment]
Thanks @Strilanc 

I am almost finished with the coding. One question I have before submitting PR is:
how to deal with measurements with not key provided (as I see that the cirq.measure doesn't need key as mandatory arg). This creates two cases where all the measurements are provided without keys and the case where some measurements has keys and some don't.

**Comment by iamvamsikrishnad** [comment]
https://github.com/quantumlib/Cirq/pull/1746/files
