### ISSUE TITLE
Replace TrialResult data and query methods with a '.data' pandas.DataFrame attribute

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1689]
Pros:

- Less work for us.
- Easier to learn for users / user knowledge generalizes beyond cirq.
- The pandas API is already way better than ours w.r.t. handling data.
- run_sweep and run can have the same output type.

Cons:

- Less control over the format. E.g. we can't add sympy symbol support to the filtering.
- There's no longer metadata like "number of repetitions" associated with the result object. No natural place to put information such as "this is the random seed that was used".

@dabacon @mpharrigan @maffoo @babbush

**Comment by maffoo** [comment]
How about if `TrialResult` "has a" dataframe rather than "is a" dataframe? Then we have a place to tack on extra metadata if needed or add some helper methods to do things like translate sympy queries into the data frame. Can also easily just get the data frame itself and discard the rest of the trial result if that's all you need.

**Comment by Strilanc** [comment]
I think we should not add any of our own filtering or aggregation methods, because they will behave differently than the pandas ones and this will create opportunities for [mode errors](https://en.wikipedia.org/wiki/Mode_(user_interface)#Mode_errors).

I would prefer to just return the dataframe because it's one less thing to teach ("don't forget to put `.data`), but I agree that we may have to return a compound object that has a dataframe in addition to metadata.

**Comment by viathor** [comment]
FWIW, complex numbers are supported in pandas:

```
In [1]: import numpy as np, pandas as pd

In [2]: pd.DataFrame(np.random.randn(2, 2) + 1j*np.random.randn(2, 2))
Out[2]: 
                                           0                                           1
0  (0.8085296905025485+0.21843211625055653j)    (-2.3254358862574604-0.676186251066216j)
1  (1.1482814917465722-0.13174530925455633j)  (-1.9747558058497554-0.34006501400069955j)
```
