### ISSUE TITLE
Should we bump our minimum python 3 version?

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1693]
Seeing as how we're dropping python 2 support, this seems like a natural time to do it.

I've run into a few issues recently w.r.t. things existing in the `typing` module or not. We could also start using features like data classes and attribute/variable type annotations.

**Comment by vtomole** [comment]
+1 for bumping.

**Comment by vtomole** [comment]
> data classes

So, versions `3.7+`

**Comment by c-poole** [comment]
The biggest issue I see with doing something like this is whether or not we are limiting integration of cirq into projects that operate on earlier python 3 versions. We may want a release that is compatible with 3.5/3.6 so that it isn't a jump from 2.7, >=3.5 to 3.7 only

**Comment by dabacon** [comment]
https://www.jetbrains.com/research/python-developers-survey-2018/ contains some info on version adoption

**Comment by dabacon** [comment]
I'm not very familiar with how backward incompatible 3.x versions are.

FWIW: colab uses 3.6.7.

**Comment by Strilanc** [comment]
We definitely don't want to become incompatible with colab.

**Comment by vtomole** [comment]
Based on Dave's link, 54 percent of the users surveyed are on Python 3.6 vs 11% on 3.5.

**Comment by Strilanc** [comment]
I think I've thought of a hacky solution to the 3.5-is-forever-confusingly-broken problem.

When we release the next package, we mark it as compatible with 3.5 (and even 2.7). But at import time we check if the version is 3.5, and if it is then we blow up with an error message saying "you either need to upgrade to python 3.5 or you need to install the old version of cirq==0.whatever".

This transforms a confusing error into a very loud and explained error, at the cost of doing the wrong thing for people who wanted `pip install cirq` to actually install the old version. But we keep telling people not to do that, so it may be acceptable.

**Comment by terrillfrantz** [comment]
Folks, I am just a lurker to the thread at this point, but such a strong 
message is a good thing to do for those of us not using Cirq everyday, 
or are entirely new to it. Saves everyone--the noob and the development 
community--a lot of pain as you can well imagine.
