### ISSUE TITLE
Circuit + OP_TREE

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#1698]
Since `circuit += op_tree` works, I propose to let `circuit + op_tree` work too.

**Comment by Strilanc** [comment]
Makes sense to me.

**Comment by gauravMann** [comment]
I am willing to take this up. I have read the contributor's guide, and set up my local environment.

**Comment by vtomole** [comment]
@gauravMann Go for it!

**Comment by Strilanc** [comment]
Ah right, I forgot about the device inter-compatibility check. That's important to keep. The validation of moments in `other` can be delegated to `copy.__iadd__`, but the validation of moments in `self` would stay.

**Comment by gauravMann** [comment]
Hi @Strilanc I apologize for the delay. 
Please review the pull request [https://github.com/quantumlib/Cirq/pull/1762](url)
