### ISSUE TITLE
cannot import name 'TYPE_CHECKING' in python 3.7

### ISSUE THREAD

**Issue by iamvamsikrishnad** [quantumlib/Cirq#1701]
While using python-3.7 and running 
`python -m pip install -r dev_tools/conf/pip-list-dev-tools.txt`
throws an error:

> pylint 2.3.1 has requirement astroid<3,>=2.2.0, but you'll have astroid 2.1.0 which is incompatible.

Updating the requirement of astroid in pip-list-dev-tools.txt to 2.2.* makes it work.

**Comment by vtomole** [comment]
Hey @iamvamsikrishnad, this was a compromise we had to make to be on a latest version of pylint while getting around this bug:
https://github.com/quantumlib/Cirq/blob/1e6436c136dbe94a62970fa64692d27ed8f919c8/dev_tools/conf/pip-list-dev-tools.txt#L21

**Comment by iamvamsikrishnad** [comment]
Hi,
Thanks for the reply. I am not sure I totally follow you. 
Yes it (https://github.com/PyCQA/astroid/issues/650) is a issue in 3.5.2 and hence astroid was pinned to version 2.1.*, but that is breaking it for users on python 3.7. I believe we need to find a fix for both versions right ?

**Comment by vtomole** [comment]
>  I believe we need to find a fix for both versions right ?

Yes, the fix is solving that issue that you linked which is still open. I've spent an hour or two playing around with astroid to try to fix that bug with no luck.

**Comment by iamvamsikrishnad** [comment]
In that case, Can you please keep this issue open.

**Comment by vtomole** [comment]
This issue is not a bug in cirq. It's a bug in astroid.

**Comment by iamvamsikrishnad** [comment]
I'd leave it up to your judgement. 
I feel since the cirq installation is failing because of the dependencies, we should track it here as a cirq bug as well.

**Comment by vtomole** [comment]
The cirq installation does't fail because of this. It throws a warning that the versions of astroid and pylint are not compatible. If i'm wrong about this let me know. Also, the title of this issue doesn't seem to match what we are discussing right now.

**Comment by iamvamsikrishnad** [comment]
Sure.
