### ISSUE TITLE
Write `optimization` chapter on readthedocs

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#1703]

**Comment by balopat** [comment]
I'm happy to take this on - I'm digging into the optimizers anyway.

**Comment by vtomole** [comment]
Thank you!

**Comment by dstrain115** [comment]
I am going to take this, since I am revamping the documentation.

**Comment by dstrain115** [comment]
See #2884

**Comment by dstrain115** [comment]
Wrote a section here:
https://cirq.readthedocs.io/en/latest/circuits.html#Circuit-Optimizers
