### ISSUE TITLE
Is python3-tk still a system requirement?

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1728]
We had this requirement because of matplotlib, but I just tried uninstalling python3-tk from my machine and then plotting stuff and it worked.

Note that we did switch to a more recent version of matplotlib: https://github.com/quantumlib/Cirq/pull/1684 . But in my testing the old version also worked..

**Comment by vtomole** [comment]
tkinter is packaged with the Python 3+ installs. Seems like i wasn't the only one having problems reproducing this: https://stackoverflow.com/questions/25905540/importerror-no-module-named-tkinter.  I'll remove this as part of the "Remove Python 2 support" issue.
