### ISSUE TITLE
PROPOSAL: merge sim.run and sim.run_sweep into sim.sample

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1739]
After https://github.com/quantumlib/Cirq/issues/1689 is resolved, the return type of both sim.run and sim.run_sweep will be identical. The only difference between them is that one takes a sweep and one takes a parameter resolver. But we can use a common parameter for both cases, so that a sweep is called in exactly the same way as a non-sweep, just with parameters = a sweep instead of parameters = a dict.

I also think that `sample` is less ambiguous than `run`.

**Comment by dabacon** [comment]
Need to remember to update documentation on rename of sample and run.  

Should there be a similar refactoring for the simulate method?

**Comment by Strilanc** [comment]
Yes, `simulate` should become e.g. `final_wavefunction` or `sample_wavefunction`.

**Comment by dabacon** [comment]
Sampler ended up being a different concept, with run being reserved to return the TrialResult while sample returns the dataframe.  TrailResult also gives access to the dataframe via `data`.
