### ISSUE TITLE
Partially support QUIL

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#1742]
We currently support QASM output and there is some work being done by @balopat for QASM imports. We should also support QUIL (https://arxiv.org/abs/1608.03355)  because it's another popular ISA that's currently used. We can't support the whole instruction set because it's meant for hybrid architectures, but we can support whatever our QASM implementation supports.

**Comment by aditya-giri** [comment]
@vtomole what would it take to get this done if I'm new to the code but I've worked with Qiskit previously and continue to do so?

**Comment by vtomole** [comment]
@aditya-giri You can start with https://github.com/quantumlib/Cirq/issues/2983

**Comment by aditya-giri** [comment]
@vtomole Sure, lemme just familiarize myself with the code a little and then I'll get started. Would you be able to help me with that? Also can you look at #2862? Looks like some low hanging fruit for me to pick off.

**Comment by vtomole** [comment]
@aditya-giri Sure. it's good to start with `good first issues` if you are beginning. I just assigned that to you.

**Comment by aditya-giri** [comment]
Great, thanks!

**Comment by vtomole** [comment]
We now have [quil_import](https://github.com/quantumlib/Cirq/tree/master/cirq-core/cirq/contrib/quil_import) and [quil_ouput](https://github.com/quantumlib/Cirq/blob/master/cirq-core/cirq/circuits/quil_output.py).

**Comment by vtomole** [comment]
We now have [quil_import](https://github.com/quantumlib/Cirq/tree/master/cirq-core/cirq/contrib/quil_import) and [quil_ouput](https://github.com/quantumlib/Cirq/blob/master/cirq-core/cirq/circuits/quil_output.py).  Feel free to re-open if we missed something.
