### ISSUE TITLE
Automerge script doesn't understand "one approved one disapproved" review status

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1755]
E.g. see behavior in https://github.com/quantumlib/Cirq/pull/1745

**Comment by dabacon** [comment]
What is desired behavior?  I think in this case it makes sense that the disapprove should have to marked as stale in order to submit?

Code that would need to be modified if we change this is https://github.com/quantumlib/Cirq/blame/master/dev_tools/auto_merge.py#L731

**Comment by balopat** [comment]
I haven't seen this behavior for a while now and I'm sure there were PRs with both request for changes and approval on them. Putting needs-repro on it, which will mark this issue stale eventually.

**Comment by dabacon** [comment]
Per previous comment, this doesn't seem to be happening, and last comment is 1.5 years old.  Closing.
