### ISSUE TITLE
Is anyone still using `continuous-integration/check.sh` ?

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1760]
In my own workflow I've switched over entirely to the scripts in the `check/` folder, which are significantly faster (if not quite as bullet proof in terms of agreeing with Travis-ci).

I ask because without maintenance these scripts gradually bit-rot and stop working. E.g. @cduck had some trouble with continuous-integration/check.sh .

**Comment by vtomole** [comment]
I was about to make this issue.

CC: @dabacon

**Comment by bryano** [comment]
I use `continuous-integration/simple_check.sh`.

**Comment by dabacon** [comment]
I haven't been using it.  Do we have a script that runs all the relevant scripts in the check folder?

**Comment by Strilanc** [comment]
No, there's not a "run all" script.

Because we now have continuous integration checks across platforms, it's not actually possible for one person to run all the checks anymore (without VMs anyways).

**Comment by dabacon** [comment]
Yes I understand that.  But right now it is annoying that there isn't one thing I can run which gives me some idea that the build is going to fail or not.  Instead I run each of these by hand.
```
check/format-incremental --apply
check/pylint
check/mypy
check/pytest-changed-files
```
though sometimes I do the incremental coverage.   It would be nice to have a single script that does this

**Comment by Strilanc** [comment]
We could definitely add an `all` script.

It would be a bit unusual for the `all` script to apply formatting changes instead of checking for them.

**Comment by bryano** [comment]
@dabacon `simple_check.py` does the latter three things (with coverage). Its omission of the formatting I think is just because it hasn't been updated since formatting was introduced.

**Comment by c-poole** [comment]
I've been using pytest on my own machine and relying on travis to tell me what else I need to fix.

**Comment by dabacon** [comment]
Oops.  fat moused the button
