### ISSUE TITLE
Add Reset channel

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1774]
The reset channel is equivalent to performing an unobserved measurement which then controls a bit flip onto the targeted qubit. It is also equivalent to tracing out a qubit and then swapping a fresh 0 qubit into the system.

**Comment by andbe91** [comment]
I'd like to work on this (I need this for a simulation I'm doing anyway). 
I looked a bit at the channel protocol and I think that I have an idea on how to implement this.

My idea is the following:
The measurement Kraus operators are `[[1,0],[0,0]]` and `[[0,0],[0,1]]`, where the latter corresponds to the 1 state. If we measure 1, we apply a Y-gate with the unitary `[[0,-1],[1,0]]`, i.e. the second Kraus operator becomes `[[0,-1],[1,0]] * [[0,0],[0,1]] = [[0,-1],[0,0]]`. So to implement this in Cirq, I just make a class analogous to e.g.  the PhaseDampingChannel, but with the `_channel_` method returning `(np.array([[1, 0], [0,0]]), np.array([[0, -1], [0, 0]]))`

Does this sound reasonable?
Should there be a probability of applying the reset or not?
What is a good circuit diagram symbol in this case?

**Comment by cduck** [comment]
That is the correct channel (although applying X also works).  I would suggest implementing this like `AmplitudeDampingChannel` or `GeneralizedAmplitudeDampingChannel`.

@dabacon might have ideas for a diagram symbol.  `R` makes sense but might be confused with rotation.  `|0⟩` and `|0>` (for ASCII mode) could work.
