### ISSUE TITLE
Incompatible with matplotlib 3.1.1

### ISSUE THREAD

**Issue by Roger-luo** [quantumlib/Cirq#1778]
Any reason why cirq is not using a conditional dependency for visualization? e.g allow using `pip install cirq[matplotlib]` to enable matplotlib visualization. This can be quite annoying on servers. 

I think it is related to #1269

**Comment by Strilanc** [comment]
I think visualization is going to be a core feature, so it doesn't make sense to move this into an optional dependency. Is there a way to have a variant that *omits* the visualization instead?

**Comment by dabacon** [comment]
I don't think such a variant exists that excludes packages.

I think there exists a workaround which is to do your work in a virtual environment or container where you have better control over your defaults and don't use system defaults.  

I'm going to close this as we don't currently have a plan to make a minimal dependency version of Cirq.
