### ISSUE TITLE
Syntactic sugar for cirq.Circuit.from_ops (?)

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#1787]
When using cirq, you'll typically want to create a circuit. As far as I can tell, the most common way of doing that is with `cirq.Circuit.from_ops`. Since this is so common, it *might* be nice to have a shorter alias. Maybe `cirq.ascircuit(...)` by analogy to `np.asarray`. What do you think?

**Comment by bryano** [comment]
Why don't we just allow arbitrary op_trees in the `Circuit` constructor?

**Comment by Strilanc** [comment]
Now that we have the convention about moments going in without being reflowed, `from_ops` is in fact a strict superset of the constructor. Allowing `cirq.Circuit(OP_TREE)` could be reasonable.
