### ISSUE TITLE
sim.Simulator() is very slow

### ISSUE THREAD

**Issue by XiaoMiQC** [quantumlib/Cirq#1804]
sim.Simulator() is significantly slower than a couple of weeks ago. qubit_characterizations_test.py now takes 50s to run as opposed to a few seconds before. Has there been some recent change to the simulator?

**Comment by dabacon** [comment]
Pandas maybe?

**Comment by c-poole** [comment]
I just ran qubit_characterizations_test.py on a branch up to date with the repository and it completed in under 5 seconds. How up to date is your branch?

**Comment by Strilanc** [comment]
I modified `TrialResult` to lazily compute the pandas dataframe, and also to store int instead of Series[boolean]. That may explain the time going back down.

**Comment by XiaoMiQC** [comment]
I just merged with master and run the tests again. They are back to the original speed (~3 s to complete qubit_characterizations_test.py).
