### ISSUE TITLE
Rename TrialResult to just Result (with deprecated TrialResult for compatibility)

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1808]

**Comment by dabacon** [comment]
This seems reasonable.  I suspect not many people use TrialResult directly as a name, only as a consumer (Though maybe if they are doing type annotations).

**Comment by balopat** [comment]
Related #3257

**Comment by tonybruguier** [comment]
Would https://github.com/quantumlib/Cirq/pull/3344 be a reasonable attempt?

**Comment by balopat** [comment]
Closed in #3344.
