### ISSUE TITLE
Add documentation demonstrating usage of new TrialResult for common tasks

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1809]

**Comment by MichaelBroughton** [comment]
This issues seems pretty outdated. One thing I did wonder as a follow on is do we have a notebook or guide on all the different simulation techniques one can use in Cirq (each of which can produce their own `***TrialResult` objects) ?

**Comment by dstrain115** [comment]
I vote that we close this issue since this is quite outdated.  We can open a new issue if there are specific things that we want to document.
