### ISSUE TITLE
Have standardized global methods for going from List[int] + shape to index

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1812]
Would be used e.g. when packing down measurement results into an integer.

The endian-ness of this method has to be big endian in order to match the convention set by np.kron.

**Comment by cduck** [comment]
Also the inverse function from index + shape to List[int].

**Comment by Strilanc** [comment]
Fixed in https://github.com/quantumlib/Cirq/pull/1811 by big_endian_int_to_digits and friend
