### ISSUE TITLE
Nightly dev builds

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#1819]
Releasing dev builds to pypi is currently done manually and in an ad hoc manner.  We could move to nightly builds.

**Comment by Strilanc** [comment]
Sounds reasonable. Any suggestions on what would actually be producing the builds? Some kind of cron job running on Travis?

**Comment by balopat** [comment]
We could use Cloud Build on GCP as well.

**Comment by dabacon** [comment]
I'm looking into this.

Current idea is that we will do dev builds to a separate cirq-dev pypi package on every commit to master.  We can use travis's deploy functionality to do this I think.

**Comment by dabacon** [comment]
We now have builds that deploy on every successful new merge.  These are pushed to "cirq-dev" which is owned by "quantumlibdev".

**Comment by vtomole** [comment]
YAY!!

**Comment by vtomole** [comment]
Look for a new way of doing this.

**Comment by dabacon** [comment]
Think we can close this again since we are back doing this?  Or was there some other way we wanted to look to do this?

**Comment by vtomole** [comment]
I think it's good! :+1:
