### ISSUE TITLE
ModuleNotFoundError: No module named 'cirq'

### ISSUE THREAD

**Issue by Rbatistab** [quantumlib/Cirq#1823]
Hi everyone!
I'm new to cirq, and have just installed OpenFermion, wich works correctly, and cirq (https://buildmedia.readthedocs.org/media/pdf/cirq/stable/cirq.pdf), all the installation went fine, with:

> python -m pip install --upgrade pip
> python -m pip install cirq
> python -c "import cirq; print(cirq.google.Foxtail)"

worked all good, but when I try to compile a small test (bellow), I get this error:

> ModuleNotFoundError: No module named 'cirq'

Does anybody know what is going on?

Small test:
import  openfermion
import  openfermioncirq  as  ofc
from openfermion.hamiltonians import MolecularData

# Set parameters to make a simple molecule.
diatomic_bond_length = .7414
geometry = [('H', (0., 0., 0.)), ('H', (0., 0., diatomic_bond_length))]
basis = 'sto-3g'
multiplicity = 1
charge = 0
description = str(diatomic_bond_length)
#filename ='h_2mlc'

#Make molecule and print out a few interesting facts about it.
h_2molecule = MolecularData(geometry, basis, multiplicity,
                         charge, description)

hamiltonian = h_2molecule.get_molecular_hamiltonian()

qubits = cirq.LineQubit.range(4)
circuit = cirq.Circuit.from_ops(
        ofc. simulate_trotter (
            qubits,
            hamiltonian,
            time =1.0,
            n_steps =1,
            order =0,
            algorithm=ofc.trotter.LOW_RANK,
            omit_final_swaps=True)
        )

cirq.merge_single_qubit_gates_into_phased_x_z(circuit)
print (circuit.to_text_diagram(use_unicode_characters=False ) )

Thanks a lot!

**Comment by vtomole** [comment]
Are you using the same interpreter that you ran `python -c "import cirq; print(cirq.google.Foxtail)"` with when you try to run Openfermion?

**Comment by Strilanc** [comment]
You're most likely running the tests in a different virtual environment. For example, if you are running the tests from PyCharm, you need to tell it to use the virtualenv into which you installed cirq.

**Comment by Rbatistab** [comment]
Hi! Well, I think I do, but I'm very new in Python
I installed Anaconda 3.7, and in the navigator work with spyder
The first time I installed cirq I got this error:

> rbatista@rbatista-Lenovo-B40-80:~/OpenFermion-Cirq$ python -m pip install -e .
> Obtaining file:///home/rbatista/OpenFermion-Cirq
> openfermioncirq requires Python '>=3.6.5' but the running Python is 2.7.15

But managed to change to python 3 and the installation worked, and also tried this

> ~/OpenFermion-Cirq$ python3 -m pip install -e .

which also worked

**Comment by Rbatistab** [comment]
> You're most likely running the tests in a different virtual environment. For example, if you are running the tests from PyCharm, you need to tell it to use the virtualenv into which you installed cirq.

Thanks! I will just try now!

**Comment by Strilanc** [comment]
I am going to close this issue since it has more to do with python environments than cirq. But feel free to ask for more help.
