### ISSUE TITLE
Make --actually-quiet work in the windows tests on Github Actions

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1826]
https://github.com/quantumlib/Cirq/pull/1825 added `--actually-quiet` parameter to `check/pytest` to suppress progress output from pytest in travis logs.

This is done by piping through `grep -Pv '^(.\[0m)?[\.FEsx]+(.\[36m)?\s+\[\s*\d+%\](.\[0m)?$'` which detects lines like

```
........................................................................ [ 12%]
........................................................................ [ 13%]
................................................ss...................... [ 14%]
...........ss........................................................... [ 15%]
........................................................................ [ 16%]
........................ssssssssss................                       [100%]
```

accounting for the possibility of color codes being present.

However, this does not work in the windows tests build. E.g. https://travis-ci.com/quantumlib/Cirq/jobs/216688375

The grep filter needs to be modified somehow, but I'm not sure how. I think pytest uses colorama https://github.com/tartley/colorama/ for cross-platform coloring, but it's not clear to me why this would cause the filter to fail.

**Comment by dabacon** [comment]
I worry a bit about --actually-quiet parameter because if you don't know about it, travis logs can be less useful (why doesn't it show the tests running like when I use check locally).

**Comment by mpharrigan** [comment]
A data point: I thought everything was broken during #1992 because there was no terminal output (in addition to the wonky matplotlib behavior)

**Comment by Strilanc** [comment]
@mpharrigan @dabacon You don't find that the amount of dot output was becoming problematically large? When a test fails, the output is hidden way down instead of being right in view.

If there was some way for us to trigger Travis' log folding behavior on the progress, that would solve both issues.

**Comment by dabacon** [comment]
Still a problem after move to Github Actions.

**Comment by pavoljuhas** [comment]
Obsolete.  The `--actually-quiet` option was removed in #5868.
