### ISSUE TITLE
Can we bump the google.protobuf pinned dependency version to ~=3.9?

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1831]
There are deprecation warnings being triggered by 3.5.

**Comment by dabacon** [comment]
We are currently at 3.8.0, but I still see a lot of these warnings.  

@maffoo is there a reason for us not to go to 3.9?

**Comment by maffoo** [comment]
Should be ok to go to 3.9. We're still on 3.8 internally, but it's an easy upgrade.

**Comment by dabacon** [comment]
We bumped to 3.11
