### ISSUE TITLE
Add FAQ.md

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#1833]
`What is the difference between Cirq and Qiskit, Q# e.t.c?` is one i've been asked a lot. I can't remember others so post them on this comment section.

**Comment by Strilanc** [comment]
How do I do a noisy simulation?

How do I run on real hardware?

How do I control a gate?

**Comment by pavoljuhas** [comment]
Stale, closing.  We can ask users to post to [StackExchange](https://quantumcomputing.stackexchange.com/questions/tagged/cirq) and answer them there, should there be recurring questions.
