### ISSUE TITLE
Deprecate ParamResolver

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1837]
ParamResolver is a class that adds nothing beyond `Dict[str, float]` except a `value_of` method that does this:

```
        if isinstance(value, str):
            return self.param_dict.get(value, sympy.Symbol(value))
        if isinstance(value, sympy.Basic):
            v = value.subs(self.param_dict)
            return v if v.free_symbols else float(v)
        return value
```

I suggest we move this logic into the `resolve_parameters` protocol (if it's not already there) and then delete the ParamResolver class.

**Comment by dabacon** [comment]
SG. I guess resolving symbolic formulas would also follow into this protocol?

**Comment by Strilanc** [comment]
Yes

**Comment by peterse** [comment]
+1. This class just makes parametrization more opaque for new users in my experience

**Comment by dabacon** [comment]
We haven't had objections to this proposal, removing proposal from title.

**Comment by dabacon** [comment]
At Cirq Cync it was decided we should do this.

**Comment by 95-martin-orion** [comment]
Update from 2021: this is no longer desirable IMO. The `ParamResolver` class includes a memoization scheme for rapid resolution of previously-encountered mappings, which would not be possible if functionality were moved to `cirq.resolve_parameters`.

**Comment by maffoo** [comment]
+1 to what @95-martin-orion said. Also, having our own wrapper around `Dict` gives us a place to document that `ParamResolver` is supposed to be immutable (or to enforce immutability in some way _a la_ #4329.
