### ISSUE TITLE
Version Update

### ISSUE THREAD

**Issue by sashananda** [quantumlib/Cirq#1838]
How do I update to cirq version 0.5? I currently have version 0.4, and am getting an import error when I try to import the DensityMatrixSimulator (which I assume is a problem that is arising from having the old version)

**Comment by vtomole** [comment]
`pip install cirq --upgrade`

**Comment by vtomole** [comment]
Accidentally closed. @sashananda  Did the command i posted work?

**Comment by vtomole** [comment]
I'm going to close this as stale. Feel free to ping me if the command I suggested doesn't work.
