### ISSUE TITLE
Add SpecificQubitsDevice

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#184]
`UnconstrainedDevice` is too unconstraining.

**Comment by vtomole** [comment]
What would `SpecificQubitsDevice` look like? How would it be different from `UnconstrainedDevice`?

**Comment by Strilanc** [comment]
`SpecificQubitsDevice` would require operations to only apply to a given set of qubits specified at initialization time of the device class instance. It wouldn't apply any locality constraints.

**Comment by dabacon** [comment]
I think this isn't really that useful.  Going to close unless someone comes up with a good use case.
