### ISSUE TITLE
Phase out SupportsPhase protocol

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#1850]
The use case I have in mind is defining this protocol for SWAP. This is useful, for instance, for the EjectZ optimizer because one can pass a Z gate through a SWAP as follows:
```
0: ───Z^theta───×───
                │
1: ─────────────×───
```
=
```
0: ───×─────────────
      │
1: ───×───Z^theta───
```
So I think the `phase_by` function signature should be changed from
```
def phase_by(val: Any,
             phase_turns: float,
             qubit_index: int,
             default: TDefault = RaiseTypeErrorIfNotProvided):
```
to
```
def phase_by(val: Any,
             phase_turns: float,
             qubit_index: int=None,
             qubits: Sequence[cirq.Qid]=None,
             phased_qubit: cirq.Qid=None,
             default: TDefault = RaiseTypeErrorIfNotProvided):
```
Then `phase_by` for SWAP would return an `OP_TREE`.

**Comment by mpharrigan** [comment]
We could also special case swaps in EjectZ for a quick and dirty solution

@Strilanc what do you think about @kevinsung 's proposed changes? also cc @dabacon

**Comment by mpharrigan** [comment]
Initially: add in swap gate and fsim gate (with the one theta that works) support as hardcoded cases in EjectZ.

Later: delete phase_by protocol after hardcoding remaining cases.

**Comment by dabacon** [comment]
I'm trying to reconcile the title of this issue with the description which appears to mean to augment the phase_by protocol.

What would be even better is if we could generalize this protocol for describing the logic behind these types of transforms.

**Comment by kevinsung** [comment]
@dabacon I think what happened was that we discussed this issue during a Cirq sync and then decided to instead remove the SupportsPhase protocol using the plan in @mpharrigan's comment. Then I changed the title of this issue.

**Comment by dstrain115** [comment]
Do we still have this protocol?  If we are still going to remove this, we should do it before 1.0.

**Comment by dstrain115** [comment]
Adding back to triage/discuss since @tanujkhattar did not see a reason to deprecate it.

**Comment by dabacon** [comment]
We can probably keep it.  It's an example of a very specific protocol tightly coupled to a particular transformer, which is not great.

**Comment by dstrain115** [comment]
It was decided to keep this protocol after all.  The consensus in cirq cync was that this didn't really affect anyone negatively and did provide some small value, so that we would keep it in.

The above functionality to propagate Z's through swaps had already been added to EjectZ.

Closing this issue.
