### ISSUE TITLE
cirq.I doesn't have an on_each() method

### ISSUE THREAD

**Issue by cduck** [quantumlib/Cirq#1855]
This is because `IdentityGate` doesn't subclass `SingleQubitGate`.  Instead `I = IdentityGate(num_qubits=1)`.

`cirq.H`, `X`, `T`, etc. all have `for_each()` so I expected `cirq.I` to also have this method.

**Comment by Ashalynd** [comment]
Doe they? There isn't a for_each method, but there is on_each, which is supported by IdentityGate as well: see cirq/cirquits/circuit_test.py.

**Comment by cduck** [comment]
Yes, I meant `on_each`.

Another class called `IdentityGate` is defined for a test ([cirq/circuits/circuit_test.py#L1488](https://github.com/quantumlib/Cirq/blob/master/cirq/circuits/circuit_test.py#L1488)) but the class of `cirq.I` is [cirq/ops/common_gates.py#L587](https://github.com/quantumlib/Cirq/blob/master/cirq/ops/common_gates.py#L587).  The first one subclasses `SingleQubitGate` but the second one doesn't.
