### ISSUE TITLE
./check/doctest should also execute code after "Example:" in docstrings

### ISSUE THREAD

**Issue by cduck** [quantumlib/Cirq#1856]
Currently it only executes code after ">>> " and checks the output with the following line.

**Comment by Strilanc** [comment]
We're not consistent enough about the example being code in a particular format in order to do this. I think I would prefer to require that examples follow the `>>>` convention.

**Comment by mpharrigan** [comment]
Pycharm has good support for `>>>`

**Comment by dabacon** [comment]
A quick grep shows we have very little use of `Example:` that has code after it.  Going to close as I think we don't have enough usage of this.  I believe one can always use `>>>` after example as a workaround as is done for example in https://github.com/quantumlib/Cirq/blob/33194ad3a2f4c28c48417876ff7dd1a6732d3e41/cirq/sim/density_matrix_simulator.py
