### ISSUE TITLE
Methods to return common sets of gates

### ISSUE THREAD

**Issue by peterse** [quantumlib/Cirq#1859]
It would be convenient to have access to some getters that would return iterables of gates of a specific type. For example:
```
def get_parametrized_single_qubit_gates():
    return [ cirq.Rx, cirq.Ry, cirq.Rz]

def get_unparametrized_two_qubit_gates():
    return [cirq.CNOT, cirq.SWAP]
```
etc.

This is something I end up re-writing a lot when benchmarking or composing partially random circuits

**Comment by balopat** [comment]
Thank you for filing this @peterse! 

This sounds like a useful index for gates. An idea here is to have a single query function that would scan the list of all gates and can take parameters like:
- num_qubits
- is_parameterized

We can start there and then we can build more functionality as required. What other "queries" do you typically use @peterse?

**Comment by dabacon** [comment]
@tanujkhattar Maybe something to add to common_gate_families?

**Comment by mpharrigan** [comment]
@tanujkhattar is this in your purview?

**Comment by mpharrigan** [comment]
@tanujkhattar bump; please update

**Comment by tanujkhattar** [comment]
I see a few problems which such getters: 
1. It's not clear what a gettr like `get_parametrized_single_qubit_gates` should return. Why should it return only `[ cirq.Rx, cirq.Ry, cirq.Rz]` and not include other parameterizable single qubit gates like `PhasedXPowGate`, `PhasedXZGate`  (the problem becomes more complicated for 2 qubit gates, of which we have many) etc.
2. These lists are likely going to become stale as more gate types get added and would be hard to keep them up to date. There's also issues around updating the lists in a backward compatible way -- For example: do we keep the output of `get_parametrized_single_qubit_gates` stable across versions? 
3. Another issue is that many of the gate types in Cirq won't have definitive values for properties like `num_qubits` or `is_parameterized` till they are actually initialized. For example: we can have a `cirq.QuantumFourierTransformGate(k)` on k qubits. Should a getter that returns all single qubit gates also return `cirq.QuantumFourierTransformGate(1)` ? What about more complex types like `cirq.ControlledGate` ? 

IMO, I think such methods belong to the user code where the user knows exactly what they want to include in these lists and the convenience methods can be written once and shared across library. 

I'm curious to hear if others think differently, or else I think we can mark this as won't fix and close this.

**Comment by tanujkhattar** [comment]
From cirq sync:

We might want to do this for more specific gate classes, like cliffords or paulis. We should close this issue as it's too generic, and @dabacon will open a new issue to track adding more specific gate classes.
