### ISSUE TITLE
./check/format-incremental --apply is not idempotent

### ISSUE THREAD

**Issue by cduck** [quantumlib/Cirq#1861]
Sometimes `./check/format-incremental --apply` removes an empty line that wasn't in the original diff.  This causes a second call to `./check/format-incremental --apply` to make more changes even though the first call succeeded (exit code 0).

Step to reproduce:
- Remove a function at the end of a file where the second to last function was never formatted.
- Leave an extra trailing newline.
- Run `./check/format-incremental --apply`.  The newline is removed and the exit code is 0.
- Run `./check/format-incremental --apply` again.  The last line of the function is formatted.

**Comment by mpharrigan** [comment]
Anecdotally, I've run into similar issues typically with the formatting of the imports in the various `__init__.py`s

**Comment by dabacon** [comment]
For anyone who wants to investigate this, probably you need to understand this perl gem
`perl -ne 'chomp(); if (/@@ -\d+(,\d+)? \+(\d+)(,)?(\d+)? @@/) {$end=$2+($4 or 1)-1; print "--lines=$2-$end "}' \`
in format-incremental.  A good test file is `grover.py` following @cduck s instructions.

**Comment by joelmasters** [comment]
Has this been solved? I haven't been able to reproduce the issue. Following @cduck s instructions:

> Step to reproduce:
> 
> * Remove a function at the end of a file where the second to last function was never formatted.
> * Leave an extra trailing newline.
> * Run `./check/format-incremental --apply`.  The newline is removed and the exit code is 0.
> * Run `./check/format-incremental --apply` again.  The last line of the function is formatted.

To test, I added the following functions just above the `if __name___` statement (in this case in `grover.py`) and committed the changes:

```
def test_func():
        # Creating this function to test out a bug
      print(f'testing function')


def test_func_for_removal():
    # Creating this function to be removed
    print(f'function for removal')


if __name__ == '__main__':
    main()
```

Next, I deleted `test_func_for_removal():` and left an extra trailing newline:

```
def test_func():
        # Creating this function to test out a bug
      print(f'testing function')



if __name__ == '__main__':
    main()
```

Then, I ran `./check/format-incremental --apply`, and got the correctly formatted (and output `1 file reformatted`):

```
def test_func():
    # Creating this function to test out a bug
    print(f'testing function')


if __name__ == '__main__':
    main()
```

If I run `./check/format-incremental --apply` again, I get no additional changes as the output `1 file left unchanged`.

Am I missing something? Thanks

**Comment by maffoo** [comment]
This was reported before we switched to using [black](https://github.com/psf/black) for formatting instead of the previous [yapf](https://github.com/google/yapf) (https://github.com/quantumlib/Cirq/pull/3516). The older formatter had idempotency problems like this, but we haven't seen them with black. Will close this issue.
