### ISSUE TITLE
add check for docs generation

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#1866]
If a PR contains changes in the `docs` folder, we should make sure the docs can be generated. 

I'm a bit worried about the extra time this would add, as a full site build is pretty slow currently, ~5 mins 10 seconds on my Mac locally.

We should try to make it as fast / maybe incremental, if possible.

**Comment by andbe91** [comment]
I second this. However most of the fixes in #1981 where to the docstrings themselves, so I wonder if its enough to just check for changes to the docs folder or if we actually need to check for all PRs.

The most time consuming part is the auto generation of stubs. I will look into if this can be done incrementally.

**Comment by dabacon** [comment]
This is one of the github actions now.
