### ISSUE TITLE
Duplicated formulae in the docs

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#1881]
On my Pixel's Chrome formulae show up duplicated:
![Screenshot_20190726-083340](https://user-images.githubusercontent.com/635073/61963376-4502d900-af80-11e9-88f8-01300b17f0f0.png)

**Comment by vtomole** [comment]
This is not only on mobile.

**Comment by vtomole** [comment]
This is because the formulas are defined twice; in Latex and in a `gif`. For example

```
![Energy: $E(s_1,\dots,s_n) = \sum_{<i,j>} J_{i,j}s_i s_j + \sum_i h_i s_i$](resources/EnergyDef.gif)
```
We should remove the `.gif` and define the formulas in Latex

```
$E(s_1,\dots,s_n) = \sum_{<i,j>} J_{i,j}s_i s_j + \sum_i h_i s_i$
```

**Comment by andbe91** [comment]
Also in [https://cirq.readthedocs.io/en/stable/simulation.html](https://cirq.readthedocs.io/en/stable/simulation.html) under **Monte Carlo simulations of noise**

**Comment by Strilanc** [comment]
I think this is leftover from before we added latex support.
