### ISSUE TITLE
dev and contrib requirements inconsistent

### ISSUE THREAD

**Issue by viathor** [quantumlib/Cirq#1885]
I just rebuilt my virtualenv and noticed an error about inconsistent requirements:

```
ERROR: qiskit 0.6.1 has requirement ply>=3.10, but you'll have ply 3.4 which is incompatible.
```

It seems that our contrib requirements explicitly call for ply 3.4 while dev requirements call for qiskit 0.6.* and thus implicitly for ply >=3.10.

I checked whether the tests in qasm_import (the contrib package that uses ply) pass with 3.10 and they do. Time to bump ply to 3.10?

**Comment by vtomole** [comment]
If i recall, we decided on `3.4` to be compatible with google3.

CC: @balopat

**Comment by viathor** [comment]
Steps to reproduce, including tests sensitive to ply version:

```
$ pip install -r dev_tools/conf/pip-list-dev-tools.txt
[...forces ply>=3.10...]
$ pytest cirq/contrib/qasm_import/
[...tests pass...]
$ pip install -r cirq/contrib/contrib-requirements.txt
[...reverts back to ply=3.4 and shows the error...]
ERROR: qiskit 0.6.1 has requirement ply>=3.10, but you'll have ply 3.4 which is incompatible.
[...]
$ pytest cirq/contrib/qasm_import/
[...now tests fail...]
```

**Comment by balopat** [comment]
We chatted with @dstrain115 about this back in May: https://github.com/quantumlib/Cirq/pull/1613#discussion_r282248630
What do you think about `ply>=3.4`?
On the long run someone could take on upgrading the google3 ply version...

**Comment by dstrain115** [comment]
Yeah, I think we should change to "ply>=3.4" unless there's a good reason to pin to that exact version.

**Comment by balopat** [comment]
SGTM. And just to be a bit more specific: in cirq/contrib/qasm_import only the qiskit tests fail as latest qiskit requires latest ply. All the other functionality is compatible with latest ply versions.
