### ISSUE TITLE
Remove qiskit dependency from contrib

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#1887]
We only use it in `consistent_qasm.py` and `consistent_qasm_test.py` and it causes warnings like https://github.com/quantumlib/Cirq/issues/1885. Could we do without it?

**Comment by cduck** [comment]
I believe its optional already.  If Qiskit isn't installed, those tests don't run.

**Comment by vtomole** [comment]
Ah okay. I've renamed the issue.

**Comment by viathor** [comment]
Qiskit 0.6 is in [our dev requirements](https://github.com/quantumlib/Cirq/blob/master/dev_tools/conf/pip-list-dev-tools.txt). Ply 3.4 is in [our contrib requirements](https://github.com/quantumlib/Cirq/blob/master/cirq/contrib/contrib-requirements.txt).

Related: see #1885 for details of the conflict in the versions of the ply package.

**Comment by vtomole** [comment]
So many `requirement.txt`s

**Comment by viathor** [comment]
Indeed :-)
