### ISSUE TITLE
Sparse simulator does not support `initial_state` typecasting

### ISSUE THREAD

**Issue by peterse** [quantumlib/Cirq#1888]
```
circuit = cirq.testing.random_circuit(2, 4, 0.9)
inititial_state = np.array([1, 0, 0, 0], dtype=np.complex128)
cirq.Simulator().simulate(circuit, inititial_state=initial_state)
```
throws the error
```
ValueError: State has invalid dtype. Expected <class 'numpy.complex64'> but was complex128
```

**Comment by peterse** [comment]
This might be duplicate of  #871 but its worth clarifying the docstring in the meantime. From `Simulator`:

>         If the initial state is an int, the state is set to the computational
>         basis state corresponding to this state. Otherwise  if the initial
>         state is a np.ndarray it is the full initial state. In this case it
>         must be the correct size, be normalized (an L2 norm of 1), and
>         be safely castable to an appropriate dtype for the simulator.

But `np.float32` (which throws the same error) should safely cast to `np.complex64` no?

**Comment by dabacon** [comment]
This is fixed.
