### ISSUE TITLE
Do optimizations inline when possible

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#192]
One problem with the current optimization passes is that they tend to create a lot of new moments, because they delete the existing gates then insert a bunch of new ones as one big clump that shifts the whole circuit.

It would be better, both aesthetically and in terms of predictability, if the optimizations first tried to place gates in the voids left by the removed gates.

**Comment by dabacon** [comment]
Does `PointOptimizationSummary` take care of this?

**Comment by vtomole** [comment]
@Strilanc Ping

**Comment by Strilanc** [comment]
Yeah, this is fixed enough to close. It could be better, though...
