### ISSUE TITLE
Feature request: Optimizer to push moments backwards

### ISSUE THREAD

**Issue by dstrain115** [quantumlib/Cirq#1932]
The current default insert strategy is to push the gates to the earliest possible moment.  This makes sense to compress the circuit as much as possible, but this creates a ragged frontier at the end of the circuit.  For instance, you may want to do all measurements at the end of the circuit simultaneously, rather than create them in different moments, since cirq has pushed them forward.

It may be worth having a way to insert gates with a LATEST strategy rather than EARLIEST.  However, the problem is that you don't know the correct way to do this until the circuit is complete.  So, the best way to do this to create a circuit where everything is pushed as late as possible while still keeping the circuit compressed is to create an Optimization pass that does the same thing as insert strategy EARLIEST except in reverse and stacks things up against the last operations.

**Comment by bryano** [comment]
It seems better to achieve this by having an insert method that respects moments in the op_tree.

**Comment by cduck** [comment]
@bryano All the insert methods already support this:
```
cirq.Circuit.from_ops(
    cirq.X(cirq.LineQubit(0)),
    cirq.X(cirq.LineQubit(0)),
    cirq.Moment([
        cirq.measure(*cirq.LineQubit.range(2), key='a'),
        cirq.measure(*cirq.LineQubit.range(2, 4), key='b'),
    ])
)
0: ───X───X───M('a')───
              │
1: ───────────M────────

2: ───────────M('b')───
              │
3: ───────────M────────
```

**Comment by bryano** [comment]
Ah, I didn't realize that was implemented. Why not just do that then if you want all measurements in the final moment?

**Comment by bryano** [comment]
For reference, I was thinking of #1246; apparently not _all_ insert methods support this yet..

**Comment by cduck** [comment]
My bad.

**Comment by maffoo** [comment]
@bryano, the idea here is not _only_ to place all terminal measurements in the same moment, but more generally to transform a circuit by pushing _all_ gates toward the end of the circuit to do them as late as possible (relative to the final moment, which is typically just measurements). This is a very natural transformation to want from a hardware perspective, since any idle time after a gate is just a source of decoherence.

**Comment by cduck** [comment]
I agree.  Here are two ways to do this currently:
```
cirq.Circuit.from_ops(
    cirq.freeze_op_tree(cirq.flatten_op_tree([

    cirq.X(cirq.LineQubit(0)),
    cirq.X(cirq.LineQubit(0)),
    cirq.measure(*cirq.LineQubit.range(2), key='a'),
    cirq.measure(*cirq.LineQubit.range(2, 4), key='b'),
        
    ]))[::-1],
    strategy=cirq.InsertStrategy.EARLIEST
)[::-1]
```
```
def make_latest(circuit):
    return cirq.Circuit.from_ops(
        cirq.freeze_op_tree(circuit.all_operations())[::-1],
        strategy=cirq.InsertStrategy.EARLIEST
    )[::-1]
```

What do you think of this API in addition to a circuit optimizer?
```
c = cirq.Circuit.from_ops(cirq.X..., strategy=cirq.InsertStrategy.LATEST)
c.append(cirq.Y..., strategy=cirq.InsertStrategy.LATEST)
```
```
0: ───X───X───X───Y───Y───Y───M───

1: ───────────X───────────Y───M───
```

**Comment by daxfohl** [comment]
I'd be willing to take this. So it looks like we need a new `InsertStrategy.LATEST` and handle that in `circuit.insert/append`, and then a circuit optimizer `Compact` that takes an `InsertStrategy` and recreates the circuit with the provided `InsertStrategy`? Is the expectation that the optimizer will optimize the circuit in place, or return the optimized circuit?

**Comment by daxfohl** [comment]
Is there a bug in the existing implementation of EARLIEST?

    circuit = cirq.Circuit(
        cirq.X(cirq.LineQubit(0)),
        cirq.X(cirq.LineQubit(0)),
        cirq.X(cirq.LineQubit(0)),
        cirq.X(cirq.LineQubit(1)),
        cirq.measure(*cirq.LineQubit.range(2), key='a'),
        strategy=cirq.InsertStrategy.EARLIEST,
    )
    circuit.insert(3, cirq.Y(cirq.LineQubit(1)), strategy=cirq.InsertStrategy.EARLIEST)
    print(circuit)


produces

    0: ───X───X───X───M('a')───
                      │
    1: ───X───────Y───M────────

I would have expected Y to be inserted immediately after the X.

**Comment by daxfohl** [comment]
Probably need help understanding all the strategies before taking this one in earnest. I'd have also expected `INLINE` here to leave the top line unaffected:


    circuit = cirq.Circuit(
        cirq.X(cirq.LineQubit(0)),
        cirq.X(cirq.LineQubit(0)),
        cirq.X(cirq.LineQubit(0)),
        cirq.X(cirq.LineQubit(0)),
        cirq.X(cirq.LineQubit(0)),
        cirq.X(cirq.LineQubit(0)),
        cirq.X(cirq.LineQubit(0)),
        cirq.X(cirq.LineQubit(1)),
        cirq.measure(*cirq.LineQubit.range(2), key='a'),
        strategy=cirq.InsertStrategy.EARLIEST,
    )
    circuit.insert(3, [cirq.Y(cirq.LineQubit(1)), cirq.Z(cirq.LineQubit(1))], strategy=cirq.InsertStrategy.INLINE)
    print(circuit)

output:
    
    0: ───X───X───X───────X───X───X───X───M('a')───
                                          │
    1: ───X───────Y───Z───────────────────M────────

**Comment by maffoo** [comment]
I'm not sure something like `InsertStrategy.LATEST` is the right way to approach this. I think a circuit transformation or optimization pass that runs _after_ a circuit is constructed by whatever other means makes more sense. The main issue is that when doing a "latest" strategy you really want to insert gates in reverse order and all of the insertion and circuit construction functions process gates in order instead.

**Comment by daxfohl** [comment]
Makes sense. I did a local prototype of `InsertStrategy.LATEST`, and couldn't figure out a good way to make it intuitive. As you'd mentioned, if you add your gates in the normal order, the resulting layout is the same as `InsertStrategy.EARLIEST` because it's adding each gate to the LATEST *at that time*, which also happens to be the EARLIEST. So like you said, what's needed is a post-construction optimization.

---

So, in this optimization step, do we want to move the measurements so they all align at the end? e.g.

    0: ───X───X───X───M('a')───

    1: ───X───M('b')───

becomes

    0: ───X───X───X───M('a')───

    1: ───────────X───M('b')───

---

Or do we only care about the operations that happen before the measurement, in which case

    0: ───X───X───X───M('a')───

    1: ───X───M('b')───

stays unchanged but

    0: ───X───X───X───M('a')───

    1: ───X───────────M('b')───

becomes

    0: ───X───X───X───M('a')───

    1: ───────────X───M('b')───

My understanding from the conversation is we want the first interpretation. But if we go that way, doesn't that actually give qubit[1] *more* time to decohere?
