### ISSUE TITLE
Proposal: operator tags

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#1940]
When building a circuit is often useful to have some extra information about certain parts of the circuit.  For example you may want to preserve a certain part of the circuit while performing a transformation (optimization pass).  There isn't a great way to do this right now, but we were able to tag our operations, then we could use the tag to do this.

Tagging could also be used for diagrams.

Tagging might also be important when differentiating different "types" of gates for the same unitary.  For example sometimes exp(iZt) can be compiled out of a circuit, but sometimes you want it to stick around.

**Comment by dabacon** [comment]
Thoughts?

**Comment by dabacon** [comment]
Amusingly got a request for this today from someone else.

**Comment by dstrain115** [comment]
It seems like it would be low effort and generally useful for a variety of tasks.

It seems like there are a fair amount of different tasks where we have a generally accepted behavior or optimization pass, except we want to ignore one specific use case, so this would be a good way to accomplish all of those kinds of tasks.

**Comment by dabacon** [comment]
Another question is whether Gates should also have tags.  Any gate with a tag transfers it to its operator when applied using `on`

**Comment by dabacon** [comment]
Another question is about equality.  I guess gates and ops with different tags need to not be different.  I was going to lazily add the tags, but if we want that to work then there is a bit more work.

**Comment by mpharrigan** [comment]
How much structure do you want tags to have? A string field? a list of strings? something more like an enum?

**Comment by dabacon** [comment]
list of strings was my thought

**Comment by dstrain115** [comment]
This has been done in #2407

**Comment by 95-martin-orion** [comment]
> This has been done in #2407

Correction: #2407 was dropped in favor of #2670, which has been submitted.
