### ISSUE TITLE
pytest fails but travis says green

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#1945]
https://travis-ci.com/quantumlib/Cirq/jobs/225040090

```
4 failed, 7087 passed, 26 skipped, 3 warnings in 96.07 seconds
The command "check/pytest --ignore=cirq/contrib --benchmark-skip --actually-quiet" exited with 0.
```

**Comment by cduck** [comment]
This has been a problem at least since #1937 and there were test failures in #1937 when it was merged.

**Comment by cduck** [comment]
The --actually-quiet flag is causing check/pytest to always exit with 0 (success).

**Comment by dabacon** [comment]
ha was just reading that code.  guess today is bash script day

**Comment by dabacon** [comment]
is it because while the pytest fails the grep suceeds?

**Comment by cduck** [comment]
Yes.  I'm making a PR for my fix.
