### ISSUE TITLE
Engine api does not support sampler for program object in Engine

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#1948]
Engine that creates program and job needs support as well as just "create program" then use this as a sampler.

**Comment by dabacon** [comment]
Oh just found it.  

Actually we need to make sure that QuantumEngineSampler also supports the Program object in engine

**Comment by dabacon** [comment]
The Sampler interface has a fundamental problem that it assumes that you pass in a program each time

**Comment by Strilanc** [comment]
We could definitely generalize sampler to have some concept of passing in a program reference

**Comment by dabacon** [comment]
Fixed in #1982
