### ISSUE TITLE
Automerge bot is not merging.

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#1966]
See: https://github.com/quantumlib/Cirq/pulls

**Comment by dabacon** [comment]
yeah because @Strilanc  is out and it requires some auth on his machine.  I have instructions for doing this but haven't fixed it since it is easier to wait for @Strilanc to get back (Monday-ish)

**Comment by vtomole** [comment]
Ah yes. That manually reset Craig has to do every once in a while haha.

**Comment by vtomole** [comment]
I'll let this stay open for if we ever manage to automate that auth part.

**Comment by dabacon** [comment]
Back up and running.

**Comment by vtomole** [comment]
Thanks!
