### ISSUE TITLE
Schedule and Circuit should use device

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#199]
This may be a duplicate.  

Right now Schedule takes a device, but doesn't use it.  For example I can add a scheduled operation for a gate that does not match what the device says it should be.  I think schedules should always use the device?

Circuit right now doesn't take a device.  I propose that it should take a device, which by default can be an unconstrained device.  

Right now there is some ambiguity in device's methods.  For instance validate_scheduled_operation takes a schedule and a scheduled_operation, but doesn't say whether that operation is required to be part of the schedule or not.  We'd need to make sure this was clear.  We'd also need to add a similar method validate_circuit_operation for circuits.

**Comment by c-poole** [comment]
@strilanc this should be closed

**Comment by dabacon** [comment]
Schedule and Circuit currently take device.  There is likely more work on this boundary, but I think these should be opened as separate issues.
