### ISSUE TITLE
ControlledOperation objects do not (un)pickle

### ISSUE THREAD

**Issue by salperinlea** [quantumlib/Cirq#1991]
Python version 3.6.8
Cirq Version = 0.6.0.dev (also in 0.5.0)

Attempting to unpickle any ops.ControlledOperation object, either by pickle or by dill, results in an error.

Code to reproduce:

```
import pickle
import cirq
import sympy

dump=pickle.dumps(cirq.Rx(sympy.Symbol('param')).on(cirq.LineQubit(0)).controlled_by(cirq.LineQubit(1)))
load=pickle.loads(dump)
```

Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sumneralperin-lea/anaconda3/envs/quantum/lib/python3.6/pickle.py", line 1558, in _loads
    encoding=encoding, errors=errors).load()
  File "/Users/sumneralperin-lea/anaconda3/envs/quantum/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/Users/sumneralperin-lea/anaconda3/envs/quantum/lib/python3.6/pickle.py", line 1323, in load_newobj
    obj = cls.__new__(cls, *args)
TypeError: __new__() missing 2 required positional arguments: 'controls' and 'sub_operation'
```
Extra info/commentary:

Though this issue doesn't reside exclusively in cirq, it does restrict the (full) use of cirq with some standard python modules. In my particular use case, it prevents use of the multiprocessing module to parallelize the simulation of circuits.

**Comment by cduck** [comment]
This is happening because ControlledOperation is doing custom object creation inside `__new__`.  In this case the logic in `ControlledOperation.__new__` could be moved to `__init__` to fix this issue.
