### ISSUE TITLE
check/pytest-and-incremental-coverage matplotlib window appears

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#1992]
Running check/pytest-and-incremental-coverage on my linux workstation pops up a matplotlib figure window but instead of showing the plot, it just has whatever was drawn on the screen before the window popped up. It stays there for the duration of the test, but does eventually go away. Taken with the lack of output on the command line, it gave me the strong impression that the tests were hung; although they did end up completing.

**Comment by cduck** [comment]
This is another reason we shouldn't call `show` inside plotting functions (#1890).

**Comment by Strilanc** [comment]
This is due to the call to `results_1.plot()` in `cross_entropy_benchmarking_test.py`, which triggers a call to `plt.show()`. We need to either remove the call to show, or gate it behind a parameter.

**Comment by c-poole** [comment]
Did the recent change to a headless backend during tests fix this?

**Comment by mpharrigan** [comment]
seems fixed for me
