### ISSUE TITLE
Energy function on first page of Cirq tutorial incorrectly rendered in readthedocs view

### ISSUE THREAD

**Issue by td2014** [quantumlib/Cirq#1995]
Hi.  On the first page of the Cirq tutorial:  https://cirq.readthedocs.io/en/stable/tutorial.html the rendered energy function appears corrupt.  Actually, the first two equations that appear have the same issue.  This seems to only be on the HTML page, not what is in the github repo.  The items circled below should be removed.
<img width="762" alt="Screen Shot 2019-08-21 at 7 06 51 AM" src="https://user-images.githubusercontent.com/3465912/63439323-a92f8600-c3e2-11e9-8a43-62ffe7f2eafb.png">

Thanks.

**Comment by vtomole** [comment]
Hey @td2014 that is the stable version of the docs and this has been fixed on the latest https://cirq.readthedocs.io/en/latest/tutorial.html.

**Comment by vtomole** [comment]
PS: That error will automatically be fixed on the next release. Thanks for opening up this issue!
