### ISSUE TITLE
Mention the difference between stable docs and latest docs.

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#1996]
Stable is usually behind latest which can cause some confusion depending on which version you are reading and whether or not you are using `cirq-dev` or `cirq-release`.

See: https://github.com/quantumlib/Cirq/issues/1995

**Comment by bt3gl** [comment]
Hi, @vtomole  I was working on #2542 and realized this problem. So I can fix this one too. 
When you say "mention", you mean in the document page (i.e. https://cirq.readthedocs.io/en/(latest||stable)/tutorial.html), correct? Or somewhere else?

**Comment by vtomole** [comment]
We should mention it on the README.

**Comment by bt3gl** [comment]
#2549 was merged, so we can close this
