### ISSUE TITLE
Move state validation functions out of `sim` module?

### ISSUE THREAD

**Issue by peterse** [quantumlib/Cirq#2000]
I've needed to validate input wavefunctions and density matrices in a few functions that act on input states (e.g. `linalg.wavefunction_partial_trace_as_mixture`, `linalg.subwavefunction`, `ops.PauliString.expectation`) but can't import `to_valid_state_vector` and `to_valid_density_matrix` at the module level without causing a circular import (`sim` imports from `linalg` and `ops`).

It might make sense to move these validation functions out of sim to clean up the dependencies here and for future functions that need to check the validity of an input state

**Comment by peterse** [comment]
xref #1975

**Comment by dabacon** [comment]
These have been moved to the qis module.
