### ISSUE TITLE
Implement more complete JSON serialization for sympy

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#2014]
Follow up to https://github.com/quantumlib/Cirq/pull/1880#pullrequestreview-278642567

It would be ideal if sympy itself had a serialization format. However, the most promising candidate `srepr` looks to be horribly unsafe to parse on untrusted input. 

https://github.com/quantumlib/Cirq/pull/1880 adds support for `sympy.Symbol`, but we'll probably need support for more constructs; at least arithmetic

**Comment by dabacon** [comment]
More support has been added for simple math.  Do we have more we'd like to add?  I'd recommend we close until we see if there is more complicated math that starts showing up that we need to serialize.

**Comment by mpharrigan** [comment]
Sounds good to me!
