### ISSUE TITLE
Add `check/pylint-changed-files` script

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2021]
Linting the code base is beginning to take an unreasonably large amount of time. It would be convenient to be able to only lint files that changed.

Basically, this change amounts to rebasing the diffs of `check/pytest-changed-files` vs `check/pytest` onto `check/pylint`.

Note that `check/all` has an `--only-changed-files` flag, and when this flag is set it should call the only-changes version of pylint.

Should also update `docs/development.md`

**Comment by dabacon** [comment]
check/pytest-changed-files now exists and check-all with --only-changed-files uses it.  Can be a considerable savings.
