### ISSUE TITLE
Add docstring to cirq/contrib/paulistring/init.py 

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2022]
A good place to start in debugging this is studying the build logs.

**Comment by andbe91** [comment]
It's not showing up since there is nothing to show. `cirq.paulistring` is a module and [cirq/contrib/paulistring/__init__.py](https://github.com/quantumlib/Cirq/blob/master/cirq/contrib/paulistring/__init__.py) does not have a docstring.

**Comment by Patil2099** [comment]
@vtomole What String I have to add? Can I work on this issue?
Thanks!

**Comment by vtomole** [comment]
Sure. Add a sentence about what the `paulistring` module is about. I'll let you figure it out from the source.

**Comment by hanusaj** [comment]
Assign this to me
