### ISSUE TITLE
Cancel all jobs / all jobs under program

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#2030]
* List programs
* List jobs under a program
* List all active or running jobs (not sure if api supports this)
* Cancel all jobs
* Cancel all jobs under a program

**Comment by dabacon** [comment]
* get_processor

**Comment by dabacon** [comment]
get processor and list calibrations are done.  But all in first batch are not currently supported.

**Comment by balopat** [comment]
List programs, List jobs under a program, list all active or running jobs are done. 
--- these are the only ones missing now: 

Cancel all jobs under a program - we could implement this by the cancel_job() one by one 
Cancel all jobs - in a project? we could also implement this by running cancel_job() one by one 

@wcourtney is there a plan for "cancel call for multiple job_ids" in the service?

**Comment by 95-martin-orion** [comment]
Pinging @wcourtney - is this still necessary? Or close if it's done.

**Comment by wcourtney** [comment]
We don't have any plans for bulk cancellation in the API. We could provide a "kill switch" helper for this if we think it's common - list jobs filtered by state (RUNNING or READY) and cancel each. I expect that the issue with doing this today is that we use a blocking API interface, but we're looking into migrating to an asyncio format that should make this more bearable.

The semantics of "cancelling a program" are strange and I think it would be a low priority until at least one user other than Dave thinks about "programs" :-).

**Comment by wcourtney** [comment]
Closing as Won't Fix - let's rely on asyncio support. Feel free to re-open if you this is a higher priority than I suspect.
