### ISSUE TITLE
Should we start using `import cirq` at top level inside cirq?

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2035]
Now that we are using python 3, importing is much lazier and it's possible for us in many situations to just `import cirq` instead of individual modules.

Pros:

- Much simpler to import functionality. Don't have to remember where things are.
- Internal code will look more like external code.

Cons:

- Further obscures the dependencies between files and modules. If you think the dependency graph is already a mess *now*... well...
- Might complicate unit testing when using mocks. Or might make it easier. Unclear.
- Programmer has to understand when the imported value is used eagerly (e.g. as a base class or unquoted type annotation) vs lazily (e.g. in the body of a method that's not run at import time). 
    - Note that the eager-vs-lazy determination is technically a global property. A method in one module may be invoked during the initialization of another module (e.g. `X = XPowGate()` would invoke `Gate.__init__`).

**Comment by cduck** [comment]
The closing PR implements @Strilanc's idea (1) and solves (2) with a test that verifies import order.
