### ISSUE TITLE
A question on PauliString exponentiating

### ISSUE THREAD

**Issue by Psrit** [quantumlib/Cirq#2047]
I was using `PauliString` to implement some operations like `exp(i t X Y) |00>`, but I found that the simulated state vector did not match the one given out by directly using numpy matrix multiplication (by a global phase). The code I used is:
```python
import unittest

import cirq
import numpy as np


class PauliStringTest(unittest.TestCase):
    def test_exponential(self):
        from scipy.linalg import expm
        t = np.random.random() * 10 * np.pi
        q = cirq.LineQubit.range(2)
        p = cirq.PauliString(
            {q[0]: cirq.X, q[1]: cirq.Y},
            # coefficient=2.0
        )
        pauli_string_exponential = np.exp(1.0j * t * p)

        circuit = cirq.Circuit()
        circuit.append(pauli_string_exponential)
        simulator = cirq.Simulator()
        result = simulator.simulate(circuit, initial_state=0)
        simulated_state = result.final_simulator_state.state_vector

        pauli_string_exponential_matrix = expm(
            1.0j * t * np.kron(cirq.unitary(cirq.X), cirq.unitary(cirq.Y))
        )
        exact_state = pauli_string_exponential_matrix @ np.array([1, 0, 0, 0])

        print(simulated_state, exact_state)

        self.assertTrue(np.allclose(
            simulated_state, exact_state
        ))
```

Then I tried to test the simplest case `exp(i t X) |0>`, the results still differed. I found in `cirq/ops/pauli_string_test.py`, there are test cases in `test_exponentiate_single_value_as_exponent`, which assert that `e^(-i X(q) 0.25 π) = Rx(0.25 π).on(q)`. However, in the definition of `cirq.Rx`, `Rx(rads) = e^(-i X rads / 2)` (similar for Y & Ry, Z & Rz).

Diving into the source code of `PauliString.__rpow__`, I thought it was the `half_turns` variable that led to the question. If we added `coefficient=2.0` into the arguments when creating the PauliString, the test case above would pass, and the definitions of R{α=X, Y, Z} would be matched.

So maybe we should replace `half_turns` with `turn = 2.0 * math.log(base) * (-self.coefficient.imag / math.pi)` in `PauliString.__rpow__`?

**Comment by dabacon** [comment]
This does look broken to me. @viathor for comment.

**Comment by kevinsung** [comment]
This was fixed by https://github.com/quantumlib/Cirq/pull/2989. Note, however, that we will be removing support for applying `np.exp` to gate, since `np.exp` means element-wise exponentiation. This is being tracked at https://github.com/quantumlib/Cirq/issues/2710.
