### ISSUE TITLE
Engine doesn't serialize lists of dicts of params

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#2061]
Passing in a list of dicts to a param sweep doesn't serialize to the v2 protos
```
params=[{'a': 1, 'b': 2}, {'a':2, 'b':3}]
```

**Comment by dstrain115** [comment]
Being solved by PR #2080

**Comment by dstrain115** [comment]
You should now be able to serialize flattened sweeps and lists of dicts, as long as you make them a ListSweep.

e.g.  params=ListSweep([{'a': 1, 'b': 2}, {'a':2, 'b':3}])
