### ISSUE TITLE
Support differentiation of gates that are parameterized

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#2069]
Sympy supports differentiation
https://docs.sympy.org/latest/tutorial/calculus.html

Current `cirq.unitary` doesn't return a matrix if the gate is parameterized.  But we could make it return the formulas, and the this would allow us to perform symbolic differentiation using Sympy.

This would be a very useful primitive for simulation in quantum machine learning.

**Comment by trevormccrt** [comment]
I don't think I quite understand the end goal here. Are you trying to enable something like calculating a symbolic expectation value/partial of and expectation value with respect to a symbol? Or something more intermediate?

**Comment by dabacon** [comment]
The derivative of the unitary of a circuit / gate / op with respect to it's parameters is well defined, it just isn't necessarily a circuit itself (for example if your gate is exp(i (alpha |0><0|) the derivative turns this into a circuit with a post select |0><0| element).  This could be useful for work where you need to calculate this for other uses.

**Comment by balopat** [comment]
@MichaelBroughton do you think something like this would be useful in Cirq? If not, we can close this in my opinion.

**Comment by MichaelBroughton** [comment]
We have a lot of this in TFQ already. Can definitely close.
