### ISSUE TITLE
Add _kak_ protocol for two qubit gates

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2070]

**Comment by dabacon** [comment]
A protocol because we want to be able to provide efficient decomposition without doing all the hard numerical math?

**Comment by balopat** [comment]
Related to #1071.

**Comment by balopat** [comment]
This would be to speed up KAK decomposition in known cases. Instead of relying on the generic KAK decomposition algorithm which is slow, this would provide predefined shortcuts for the decomposition algorithm.

**Comment by balopat** [comment]
closing, will track on #1071
