### ISSUE TITLE
Gate logarithm

### ISSUE THREAD

**Issue by viathor** [quantumlib/Cirq#2071]
Every quantum gate can be thought of as a unitary operator or as evolution under a given Hamiltonian. IOW, one can reason about gates either downstairs or upstairs of the exponential map sending anti-Hermitian operators to the unitary group.

For user convenience, we should introduce a protocol that enables users to ask a gate for its corresponding Hamiltonian.

One use-case for this arises in two-qubit gate compilation where a user may want to check whether a given input gate evolves the state under a given interaction.

**Comment by bryano** [comment]
I implemented this for the fermionic simulation gates in [OFC #353](https://github.com/quantumlib/OpenFermion-Cirq/pull/353).

**Comment by balopat** [comment]
Discussed at Cirq Cynq - the use case seems unclear here. If this would be useful for someone, please comment. Otherwise we'll close it in 60 days.

**Comment by viathor** [comment]
Some information about a Hamiltonian corresponding to a unitary can be obtained using the KAK decomposition which is already in cirq. Perhaps, this is sufficient and we can close this issue. In any case, it would be useful to see a concrete use-case for this before we implement.
