### ISSUE TITLE
Add little endian versions of bit and digit packing functions

### ISSUE THREAD

**Issue by cduck** [quantumlib/Cirq#2076]
Currently only there are only functions that convert from bit or digit lists to ints with the big endian convention (first digit in the list is the most significant). 
 Little endian versions would be useful (e.g. https://github.com/quantumlib/Cirq/pull/2074#discussion_r321009818 and https://github.com/quantumlib/Cirq/pull/2074#discussion_r321012340).

Functions to add to cirq/value/digits.py:
- `little_endian_bits_to_int`
- `little_endian_int_to_bits`
- `little_endian_digits_to_int`
- `little_endian_int_to_digits`

**Comment by maffoo** [comment]
Is there a reason we need both endiannesses in cirq? I haven't followed the referenced issue so I don't have much context, but having both endiannesses floating around seems like a potential source of nasty bugs.

**Comment by cduck** [comment]
I agree.  This came up while I was modifying simulator code that internally uses little endian for sampling measurements.  The function `slice_for_qubits_equal_to` uses little endian and now is a backward compatibility issue if it is changed.

**Comment by cduck** [comment]
In #2074, I just fixed the wave function simulator to use big endian internally.  Now `slice_for_qubits_equal_to` is the only function I'm aware of that uses little endian.

**Comment by Strilanc** [comment]
This appears to be fixed now.
