### ISSUE TITLE
Windows build is sometimes failing on travis

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#2082]
Windows tests appear broken
https://travis-ci.com/quantumlib/Cirq/jobs/231923888
it looks like this broke it
https://github.com/quantumlib/Cirq/pull/2063

**Comment by vtomole** [comment]
I wonder how the build passed with failing tests.

**Comment by cduck** [comment]
Error log:
```
$ powershell -command 'Set-MpPreference -DisableArchiveScanning $true'
before_install.2
0.97s$ powershell -command 'Set-MpPreference -DisableBehaviorMonitoring $true'
before_install.3
1.02s$ powershell -command 'Set-MpPreference -DisableRealtimeMonitoring $true'
before_install.4
40.39s$ choco install python --version 3.7.3
before_install.5
0.03s$ export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
before_install.6
6.05s$ python -m pip install --upgrade pip wheel
install.1
86.62s$ python -m pip install -r requirements.txt
install.2
62.72s$ python -m pip install -r cirq/contrib/contrib-requirements.txt
install.3
53.92s$ python -m pip install -r dev_tools/conf/pip-list-dev-tools.txt
156.63s$ check/pytest --benchmark-skip --actually-quiet
........................................................................ [  0%]
........................................................................ [  1%]
........................................................................ [  2%]
.
.
.
........................................................................ [ 97%]
........................................................................ [ 98%]
.......................................................
The command "check/pytest --benchmark-skip --actually-quiet" exited with 3.
```
Notice that it stops before 99%.

**Comment by Strilanc** [comment]
@dstrain115 has also seen this failure, but on one of his PRs. Based on his description, it seems to randomly come and go. I suspect debugging it will require quite a lot of bisecting and repeating.

**Comment by dabacon** [comment]
```--actually-quiet``` is that burying the actual error messages?

**Comment by cduck** [comment]
I got a job to fail with the verbose flag: https://travis-ci.com/quantumlib/Cirq/jobs/231970083

It fails right after `cirq/work/pauli_sum_collector_test.py::test_pauli_string_sample_collector_extra_qubit_x The command "check/pytest --benchmark-skip -v" exited with 3.`

**Comment by dabacon** [comment]
So helpful: "Exit code 3: | Internal error happened while executing tests"

**Comment by cduck** [comment]
The test after that is `cirq/work/sampler_test.py::test_sampler_fail PASSED`.

**Comment by dabacon** [comment]
Async code.  Hahah yeah that wouldn't surprise me.

**Comment by cduck** [comment]
Now it crashed on `test_pauli_string_sample_collector_extra_qubit_x`.  https://travis-ci.com/quantumlib/Cirq/builds/126289206
```
cirq/work/pauli_sum_collector_test.py::test_pauli_string_sample_collector_identity PASSED [ 98%]
cirq/work/pauli_sum_collector_test.py::test_pauli_string_sample_collector_extra_qubit_z PASSED [ 98%]
The command "check/pytest --benchmark-skip -v" exited with 3.
```

**Comment by dabacon** [comment]
Should we disable this test for Windows?

**Comment by cduck** [comment]
This could be pointing out an actual issue on Windows.  I wouldn't disable unless I know that this is caused by with async code on Windows only in pytest.

**Comment by dabacon** [comment]
Does anyone have a windows device to easily debug this and not have to use travis to make it fail?

**Comment by c-poole** [comment]
I can take a look

**Comment by Strilanc** [comment]
Stale
