### ISSUE TITLE
Make publicly available cirq colabs

### ISSUE THREAD

**Issue by iamvamsi** [quantumlib/Cirq#209]
As we recently made colab publicly available (https://colab.research.google.com/), I thought it is a good idea to make examples we are building also available in colab.

**Comment by vtomole** [comment]
Pardon my ignorance on Colab, but isn't it a Jupyter notebook that runs on the cloud? If so, what does "making it publicly available" mean? Evaluating `!pip install cirq` would get you ready to go.

**Comment by Strilanc** [comment]
This issue is from before cirq was a public repository, and before it existed as a pip package, when we wanted external collaborators to be able to try it. It's obsolete now, or at least trivial (as you note @vtomole ; just `!pip install cirq`).
