### ISSUE TITLE
Add xtalk for 2 qubit operations in AQT device

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2091]
https://github.com/quantumlib/Cirq/blob/941e2b46f03d98526f0750e4640bd02e074391ab/cirq/aqt/aqt_device.py#L89.

@pschindler  Let me know if I should assign this issue to you.

**Comment by pschindler** [comment]
@vtomole Yes please do so.

**Comment by pschindler** [comment]
Crosstalk for the MS operation has been included in PR #2578
