### ISSUE TITLE
Proposal: Merge QuantumEngineSampler and Engine

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#2095]
Often when writing code that uses Engine you really want a Sampler so that you can easily swap in a simulator. It seems unwieldy to have both these classes around and one kind of has to look around or be told about QuantumEngineSampler to realize it exists.

**Comment by kevinsung** [comment]
Ok the plan is to make Engine implement Sampler by moving keyword arguments from Engine.run to Engine.__init__.

**Comment by maffoo** [comment]
It would also be useful to implement a "copy" method that creates a new engine instance with some parameters changed (for example you might want to change `JobConfig` or `priority` but leave auth info the same). Then you can do things like:
```python
engine = Engine(...)
engine.copy(priority=10).run(low_priority_job)
engine.copy(priority=99).run(high_priority_job)
```
