### ISSUE TITLE
Engine should retry retriable errors (with backoff or a finite number of tries)

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#2099]
For example 503 errors.

**Comment by dabacon** [comment]
```
---------------------------------------------------------------------------
HttpError                                 Traceback (most recent call last)
<ipython-input-2-99f02a240e61> in <module>
     52     p1_landscape.collect_p1_landscape_data(
     53         params=params,
---> 54         problem_base_dir=os.path.expanduser('~/cirq-results/problems')
     55     )

~/Projects/qaoa-experiment/qaoa_experiment/experiments/p1_landscape/data_collection.py in collect_p1_landscape_data(params, base_dir, problem_base_dir)
    151             t0 = timeit.default_timer()
    152             result = sampler.run(program=circuit,
--> 153                                  repetitions=params.n_shots)
    154             t1 = timeit.default_timer()
    155             execution_time = t1 - t0

~/Projects/cirq-internal/cirq_internal/devices.py in run(self, program, param_resolver, repetitions)
    281             repetitions=repetitions,
    282             processor_ids=[self.processor_id],
--> 283             gate_set=SYCAMORE_FISHFOOD,
    284         )
    285 

~/Projects/Cirq/cirq/google/engine/engine.py in run(self, program, program_id, job_config, param_resolver, repetitions, priority, processor_ids, gate_set)
    249                            priority=priority,
    250                            processor_ids=processor_ids,
--> 251                            gate_set=gate_set))[0]
    252 
    253     def program_as_schedule(self, program: TProgram) -> schedules.Schedule:

~/Projects/Cirq/cirq/google/engine/engine_job.py in __iter__(self)
    112 
    113     def __iter__(self):
--> 114         return iter(self.results())
    115 
    116     def __str__(self):

~/Projects/Cirq/cirq/google/engine/engine_job.py in results(self)
     85                     break
     86                 time.sleep(0.5)
---> 87                 job = self._refresh_job()
     88             self._raise_on_failure(job)
     89             self._results = self._engine.get_job_results(self.job_resource_name)

~/Projects/Cirq/cirq/google/engine/engine_job.py in _refresh_job(self)
     58     def _refresh_job(self) -> Dict:
     59         if self._job['executionStatus']['state'] not in TERMINAL_STATES:
---> 60             self._job = self._engine.get_job(self.job_resource_name)
     61         return self._job
     62 

~/Projects/Cirq/cirq/google/engine/engine.py in get_job(self, job_resource_name)
    502         """
    503         return self.service.projects().programs().jobs().get(
--> 504             name=job_resource_name).execute()
    505 
    506     def get_job_results(self,

~/environments/cirq-dev/lib/python3.6/site-packages/googleapiclient/_helpers.py in positional_wrapper(*args, **kwargs)
    128                 elif positional_parameters_enforcement == POSITIONAL_WARNING:
    129                     logger.warning(message)
--> 130             return wrapped(*args, **kwargs)
    131         return positional_wrapper
    132 

~/environments/cirq-dev/lib/python3.6/site-packages/googleapiclient/http.py in execute(self, http, num_retries)
    853       callback(resp)
    854     if resp.status >= 300:
--> 855       raise HttpError(resp, content, uri=self.uri)
    856     return self.postproc(resp, content)
    857 

HttpError: <HttpError 503 when requesting https://quantum.googleapis.com/v1alpha1/projects/cirq-test/programs/c44c3c9e-2de3-4fed-b5f9-04336275cf24/jobs/job-O61FWD?alt=json returned "The service is currently unavailable.">
````

**Comment by dabacon** [comment]
---------------------------------------------------------------------------
HttpError                                 Traceback (most recent call last)
<ipython-input-2-99f02a240e61> in <module>
     52     p1_landscape.collect_p1_landscape_data(
     53         params=params,
---> 54         problem_base_dir=os.path.expanduser('~/cirq-results/problems')
     55     )

~/Projects/qaoa-experiment/qaoa_experiment/experiments/p1_landscape/data_collection.py in collect_p1_landscape_data(params, base_dir, problem_base_dir)
    151             t0 = timeit.default_timer()
    152             result = sampler.run(program=circuit,
--> 153                                  repetitions=params.n_shots)
    154             t1 = timeit.default_timer()
    155             execution_time = t1 - t0

~/Projects/cirq-internal/cirq_internal/devices.py in run(self, program, param_resolver, repetitions)
    281             repetitions=repetitions,
    282             processor_ids=[self.processor_id],
--> 283             gate_set=GATE_SET,
    284         )
    285 

~/Projects/Cirq/cirq/google/engine/engine.py in run(self, program, program_id, job_config, param_resolver, repetitions, priority, processor_ids, gate_set)
    249                            priority=priority,
    250                            processor_ids=processor_ids,
--> 251                            gate_set=gate_set))[0]
    252 
    253     def program_as_schedule(self, program: TProgram) -> schedules.Schedule:

~/Projects/Cirq/cirq/google/engine/engine_job.py in __iter__(self)
    112 
    113     def __iter__(self):
--> 114         return iter(self.results())
    115 
    116     def __str__(self):

~/Projects/Cirq/cirq/google/engine/engine_job.py in results(self)
     85                     break
     86                 time.sleep(0.5)
---> 87                 job = self._refresh_job()
     88             self._raise_on_failure(job)
     89             self._results = self._engine.get_job_results(self.job_resource_name)

~/Projects/Cirq/cirq/google/engine/engine_job.py in _refresh_job(self)
     58     def _refresh_job(self) -> Dict:
     59         if self._job['executionStatus']['state'] not in TERMINAL_STATES:
---> 60             self._job = self._engine.get_job(self.job_resource_name)
     61         return self._job
     62 

~/Projects/Cirq/cirq/google/engine/engine.py in get_job(self, job_resource_name)
    502         """
    503         return self.service.projects().programs().jobs().get(
--> 504             name=job_resource_name).execute()
    505 
    506     def get_job_results(self,

~/environments/cirq-dev/lib/python3.6/site-packages/googleapiclient/_helpers.py in positional_wrapper(*args, **kwargs)
    128                 elif positional_parameters_enforcement == POSITIONAL_WARNING:
    129                     logger.warning(message)
--> 130             return wrapped(*args, **kwargs)
    131         return positional_wrapper
    132 

~/environments/cirq-dev/lib/python3.6/site-packages/googleapiclient/http.py in execute(self, http, num_retries)
    853       callback(resp)
    854     if resp.status >= 300:
--> 855       raise HttpError(resp, content, uri=self.uri)
    856     return self.postproc(resp, content)
    857 

HttpError: <HttpError 503 when requesting https://quantum.googleapis.com/v1alpha1/projects/cirq-test/programs/c44c3c9e-2de3-4fed-b5f9-04336275cf24/jobs/job-O61FWD?alt=json returned "The service is currently unavailable.">

**Comment by wcourtney** [comment]
Resolved with https://github.com/quantumlib/Cirq/pull/2156
