### ISSUE TITLE
Implement Quantum Volume algorithm

### ISSUE THREAD

**Issue by KevinVillela** [quantumlib/Cirq#2111]
Spoke with @mpharrigan about this. It'd be nice to have an implementation of the Quantum Volume algorithm described at https://arxiv.org/abs/1811.12926. Note that OpenQASM has the first part of this, [creating the model circuit](https://github.com/Qiskit/openqasm/blob/5fb61893661261b7211942dc04ee85f8fd845f2a/benchmarks/quantum_volume/quantum_volume.py).

If someone could assign this issue to me, I'd greatly appreciate it :)

**Comment by vtomole** [comment]
The referring pull request has been merged. Please reopen if it's not done yet @mpharrigan @KevinVillela .

**Comment by vtomole** [comment]
Sorry! Only the `HOG` portion is done.

**Comment by KevinVillela** [comment]
Yup, I'm working on the next part now :)

**Comment by KevinVillela** [comment]
I believe this is done now, anyone can feel free to re-open and assign to me if they see something I missed. Thanks!
