### ISSUE TITLE
Add PauliSum-level expectation from density matrix without validation

### ISSUE THREAD

**Issue by trevormccrt** [quantumlib/Cirq#2118]
If a user is confident their density matrix is valid, it would be good if they could calculate the expectation value without the additional overhead of an eigenvalue decomposition or numerical error causing this computation to error out (especially when the density matrix represents a nominally pure state). @peterse thoughts?

**Comment by Strilanc** [comment]
We have many linalg methods with `check_preconditions=True` on them. You could add such a thing to the method.

I'm a bit surprised that validating the density matrix involves taking an eigendecomposition. Shouldn't checking that it is Hermitian with unit trace be sufficient?

**Comment by trevormccrt** [comment]
The eigendecomp is to check positive-definiteness. I'll go ahead and add something along those lines to both expectation methods in a way that makes sense.

**Comment by Strilanc** [comment]
Ah I see, the eigenvalues (-1, +2) or (-0.5, 0.5, 0.5) would pass the Hermitian-and-unit-trace test.

If you pick a random vector and multiply it by (D-I)^N where D is the density matrix and N is very large (use repeated squaring), the vector will diverge to infinite size iff there's any negative eigenvalues (note that there can't be any positive eigenvalues larger than 1 if there are no negative eigenvalues given the unit trace constraint). But unfortunately this is worse complexity than eigendecomposition.

https://scicomp.stackexchange.com/questions/12979/testing-if-a-matrix-is-positive-semi-definite suggests we should use the Cholesky decomposition https://en.wikipedia.org/wiki/Cholesky_decomposition https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.cholesky.html

**Comment by peterse** [comment]
Performance certainly checks out, especially since the cholseky timing is the _worst case_ for input validation:
```
>>> timeit.timeit('np.linalg.cholesky(b)', setup='import numpy as np; a = np.random.random((128,128)).astype(np.complex6
4); b = (a @ a.T); b = b + b.T; b / np.trace(b)', number=1000)
1.3936694000149146
>>> timeit.timeit('np.linalg.eigvalsh(b)', setup='import numpy as np; a = np.random.random((128,128)).astype(np.complex6
4); b = (a @ a.T); b = b + b.T; b / np.trace(b)', number=1000)
6.356422999990173
>>> timeit.timeit('np.linalg.eigvals(b)', setup='import numpy as np; a = np.random.random((128,128)).astype(np.complex64
); b = (a @ a.T); b = b + b.T; b / np.trace(b)', number=1000)
54.523648499976844
```
