### ISSUE TITLE
op_serializer fails on gates parameterized by algebraic expressions

### ISSUE THREAD

**Issue by trevormccrt** [quantumlib/Cirq#2122]
For example, if i create a circuit including `cirq.X ** a/2` where `a` is a sympy symbol, op_serializer.py fails in the _check_value method with the following error:

`ValueError: Expected type convertible to float but was <class 'sympy.core.mul.Mul'>`

@Strilanc do you know if not supporting this is intentional, or has it just never been added?

**Comment by trevormccrt** [comment]
@dabacon any thoughts on this? I figure it might have something to do with what you guys want to support on the engine side of things.

**Comment by dabacon** [comment]
If your circuits have formulas you need to flatten them.  See [https://github.com/quantumlib/Cirq/blob/master/cirq/study/flatten_expressions.py](https://github.com/quantumlib/Cirq/blob/master/cirq/study/flatten_expressions.py). 

We can consider making this automatic by default, but we need to be careful with too much automagic that people don't understand.

**Comment by peterse** [comment]
related: #2358

**Comment by dabacon** [comment]
This now uses the func arg language construction for a small subset of symbolic expressions.
