### ISSUE TITLE
test_implied_job_config_project_id() and test_implied_job_config_gcs_prefix() failing on my local machine and travis osx build

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2124]
```google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started```

https://travis-ci.com/quantumlib/Cirq/jobs/234202807

**Comment by vtomole** [comment]
These tests don't exist anymore. Syncing with master.

**Comment by vtomole** [comment]
That didn't work. Reopening.

**Comment by Hancockan** [comment]
Currently experiencing this issue on Ubuntu 18.04.2 after running `pytest .`
