### ISSUE TITLE
Create benchmark test suite for different simulators

### ISSUE THREAD

**Issue by karlunho** [quantumlib/Cirq#2139]
A number of groups would like to contribute their simulators to Cirq. This should be relatively easy by creating a class that implements Sampler (samples from the output distribution) or SimulatesAmplitudes (given output bitstring, outputs amplitude) Interface.

We would need a benchmark script to show how much faster the simulator is compared to the default simulator, but also to just double check that the simulator functionality is working.

**Comment by dabacon** [comment]
See #1088 for a similar request.  We have a skeleton that can easily be used to generate this data.  As mentioned in that issue, there is currently a benchmarking repo which includes Cirq (but not qsim):
https://github.com/Roger-luo/quantum-benchmarks/blob/master/RESULTS.md 

My concern with this is mostly that this adds a lot of dependencies mostly just for comparison's sake.  I would suggest if we want to do this it ends up outside of Cirq, maybe this could be in ReCirq.  This is a great intern or 20% project.

**Comment by mpharrigan** [comment]
Gonna take the executive decision to close this as no longer in scope for cirq; the linked issue has been closed
