### ISSUE TITLE
Consistently call things "state_vector"

### ISSUE THREAD

**Issue by peterse** [quantumlib/Cirq#2143]
Nitpick: Its hard to keep track of how a method acting on [an object representing a discrete quantum state] is named. This may cause confusion and also stymie autocomplete.

Right now, functions in `wave_function.py` are named like "state vector" or just "state", while `Circuit.final_wavefunction`, PauliStrings, PauliSums, and a few linalg transformations are named like "wavefunction". (I acknowledge that this inconsistency has gotten a lot worse following some of my own recent PRs :/ )

**Comment by dabacon** [comment]
We should probably avoid `state` as it is too generic and we do have notions of simulator state.

Github needs a "vote on this issue" feature.

At the top level from `__init__.py` here is the status:

Currently methods in `qis` use `state_vector` in method names except `validate_normalized_state`.  `state_vector` is also used in `measure_state_vector` and `sample_state_vector` in `sim`.  6 total uses.

`wavefunction` is used in `sim` for `final_wavefunction`.  In `linalg` we have `subwavefunction` (separates state if it is seperable) and `wavefunction_partial_trace_as_mixture`.  3 total uses.

`state` is used in `plot_state_histogram` and in simulator for simulator state.  

Let's vote on this at the next Cirq Cync.

**Comment by dabacon** [comment]
At Cirq Cync we decided that we should use "state_vector".  

From notes:
"all API names should say state_vector, docstrings should say state_vector first"

To do this we will need to first deprecate wavefunction methods and add state_vector methods.  This will go out in 0.9.0.  For 0.10.0 we will then remove deprecated methods.

**Comment by dabacon** [comment]
Fixed in #3022 but will take deprecation process to fully clean up.
