### ISSUE TITLE
Change input to SimulatesAmplitudes.compute_amplitudes from 2-d numpy array to 1-d int sequence

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#2151]
@viathor are you doing this in #2114 ? If not I can do it.

**Comment by viathor** [comment]
I'd rather keep the PR focused on one change, so nope. Feel free to do this. If you don't have time, I can also take it. Your call.

**Comment by kevinsung** [comment]
Ok I'll do it.
