### ISSUE TITLE
Doing noisy simulation is unintuitive

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#2176]
To set up the most basic noisy simulation, you need three jargony-named things:

```python
cirq.DensityMatrixSimulator(noise=cirq.ConstantQubitNoiseModel(qubit_noise_gate=cirq.DepolarizingChannel(p=0.005)))
```

Opening this based on real user research :) Despite my hints, the user could not find the correct incantation to find a depolarizing noise model. One thing they tried is using `AQTNoiseModel`.

**Comment by Strilanc** [comment]
I would say it's one jargony-named thing:

```
cirq.sample(
    circuit,
    noise=cirq.ConstantQubitNoiseModel(cirq.depolarize(p=0.005)))
```

Maybe what we could do is permit stuff like:

```
cirq.sample(
    circuit,
    noise=cirq.depolarize(p=0.005))
```

with the understanding that when the noise model is a single qubit operation it automatically gets wrapped?

**Comment by mpharrigan** [comment]
`cirq.sample` isn't a good choice for testing code that uses a `Sampler` that you want to run via quantum engine

**Comment by mpharrigan** [comment]
I think it would ease a lot of confusion if there was something named `DepolarizingNoiseModel`

**Comment by Strilanc** [comment]
I see, you don't just want "the most basic noise simulation" you want to make a noisy sampler specifically.

Auto-wrapping single qubit operations into noise models would still make sense in that context.

We could generalize `cirq.Simulator()` to include density matrix simulation, and have a `with_noise(noise)` method on it.

**Comment by Strilanc** [comment]
Creating a noise model type for every noisy channel operation type would be quite a lot of duplication. Having `cirq.depolarize(p)` play double duty as a de-facto noise model would be superior IMO.

**Comment by Strilanc** [comment]
I'm liking the idea of generalizing simulator more and more. I'll bring it up at the meeting.

**Comment by dabacon** [comment]
This now exists for single qubit noise.
