### ISSUE TITLE
PauliString.pass_operations_over doesn't accept Pauli

### ISSUE THREAD

**Issue by JulianSKelly** [quantumlib/Cirq#2179]
`PauliString.pass_overations_over` only accepts `SingleQubitCliffordGate`. For example:

```python
q = cirq.NamedQubit('q0')
pauli_string = cirq.PauliString({q: cirq.X})
op = cirq.X.on(q)
pauli_string.pass_operations_over([op])
```
raises `TypeError: Unsupported operation: cirq.X.on(cirq.NamedQubit('q0'))`

The expected use-case is AFAICT:
```python
q = cirq.NamedQubit('q0')
pauli_string = cirq.PauliString({q: cirq.X})
op = cirq.SingleQubitCliffordGate.from_pauli(cirq.X).on(q)
pauli_string.pass_operations_over([op])
```

This is pretty awkward given the constructor takes a `Pauli`.

**Comment by JulianSKelly** [comment]
There is a test explicitly for this behavior: https://github.com/quantumlib/Cirq/blob/116fbf5480c40a04af64aad4cb006db3adb5ffac/cirq/ops/pauli_string_test.py#L613-L617

**Comment by Strilanc** [comment]
This is a usability bug. The code and the test should be fixed to work when given `cirq.X`, `cirq.Y`, `cirq.Z`, `cirq.CNOT`, etc.

If we're feeling really ambitious, we should make stuff like `cirq.SingleQubitMatrix` work when it happens to approximately encode a Clifford. That would require writing a matrix-to-clifford method.

I suspect there are several other places where the "Clifford" gates interop poorly with the "normal" gates.
