### ISSUE TITLE
How will we keep the service-submitting code in sync with the simulator-submitting code in terms of gate set support

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#218]
If the simulator automatically and transparently decomposes Hadamards into supported gates, should we also do the same thing for calls to the service?

**Comment by dabacon** [comment]
I think we've found that doing these transforms automatically causes confusion.  Suggest we close this issue?

**Comment by dabacon** [comment]
This isn't really in the scope of Cirq.  This is tracked on service side where we do proper integration testing.
