### ISSUE TITLE
PauliString should accept List[Operation] in constructor

### ISSUE THREAD

**Issue by JulianSKelly** [quantumlib/Cirq#2180]
Usage is a bit awkward that we need a dict in the constructor. Specifically:

```python
q = cirq.NamedQubit('q0')
pauli_string = cirq.PauliString({q: cirq.X})
```
But this doesn't work
```python
q = cirq.NamedQubit('q0')
pauli_string=cirq.PauliString([cirq.X(q)])
```

**Comment by JulianSKelly** [comment]
I'm going to give fixing this a shot for my own edification.

**Comment by Strilanc** [comment]
Assigned it to you.

**Comment by JulianSKelly** [comment]
@Strilanc what do you think about `from_single` accepting a single `Operation` argument over what it takes now:

https://github.com/quantumlib/Cirq/blob/116fbf5480c40a04af64aad4cb006db3adb5ffac/cirq/ops/pauli_string.py#L57-L61

**Comment by Strilanc** [comment]
I think that this change to the constructor should deprecate that method. If you're feeling ambitious, `from cirq._compat import deprecate` and decorate `from_single` with it.

**Comment by Strilanc** [comment]
And you'd set "fix" to like "call `cirq.PauliString([op])` instead"
