### ISSUE TITLE
Support measurement outside of the computational basis

### ISSUE THREAD

**Issue by cjcarey** [quantumlib/Cirq#2191]
https://github.com/quantumlib/Cirq/blob/7fcda9361a3fb2b58ef914a0fce7573b2a83c6f9/cirq/sim/sparse_simulator.py#L295

https://github.com/quantumlib/Cirq/blob/2efc8ab8f6a9fbfb3239b78001abb0c046a05449/cirq/sim/sparse_simulator.py#L346

**Comment by vtomole** [comment]
There is a typo in the comment for that method.
https://github.com/quantumlib/Cirq/blob/7fcda9361a3fb2b58ef914a0fce7573b2a83c6f9/cirq/sim/sparse_simulator.py#L293

Please open a pull request that fixes it.

**Comment by cjcarey** [comment]
@vtomole To clarify, you want me to open a pull request that fixes the spelling error in computational?

**Comment by vtomole** [comment]
@cjcarey  Yes.

**Comment by jitendrs** [comment]
can you please assign it to me @vtomole

**Comment by vtomole** [comment]
You have it! Thanks.

**Comment by jitendrs** [comment]
@vtomole Thanks mate.

**Comment by jitendrs** [comment]
Changes have been committed with another pull request.
https://github.com/quantumlib/Cirq/pull/2197
Please makr duplicate issue.

**Comment by jitendrs** [comment]
@vtomole please close this issue.

**Comment by vtomole** [comment]
@jitendrs  Where was this fixed? https://github.com/quantumlib/Cirq/pull/2269 was not merged?

**Comment by jitendrs** [comment]
This was fixed in #2321. Please check and close this issue.

**Comment by jitendrs** [comment]
@vtomole please close this issue. since it was fixed in #2321

**Comment by vtomole** [comment]
@jitendrs Give me a code snippet of this then i will close.

**Comment by jitendrs** [comment]
@vtomole code snippet is on another issue, both request are for same issue. 
https://github.com/quantumlib/Cirq/issues/2273

**Comment by dabacon** [comment]
Duplicate of #1357 so closing.  Don't think the linked code solves the problem mentioned.
