### ISSUE TITLE
Deprecate v1 proto methods in grid_qubit

### ISSUE THREAD

**Issue by cjcarey** [quantumlib/Cirq#2193]
https://github.com/quantumlib/Cirq/blob/b0096307da010a050d67c28fa55d1797d210b366/cirq/devices/grid_qubit.py#L188

https://github.com/quantumlib/Cirq/blob/b0096307da010a050d67c28fa55d1797d210b366/cirq/devices/grid_qubit.py#L176

**Comment by dabacon** [comment]
Fixed in #2231
