### ISSUE TITLE
Check if circuit is empty in aqt_sampler

### ISSUE THREAD

**Issue by cjcarey** [quantumlib/Cirq#2194]
https://github.com/quantumlib/Cirq/blob/dd0934d833e1659951d6f9283c7f38355ba4d64e/cirq/aqt/aqt_sampler.py#L60

**Comment by pschindler** [comment]
This has been addressed in PR #2578

**Comment by vtomole** [comment]
Thanks @pschindler . We will close these issues once that PR is merged.
