### ISSUE TITLE
Add more detail in Gates doc

### ISSUE THREAD

**Issue by cjcarey** [quantumlib/Cirq#2204]
https://github.com/quantumlib/Cirq/blob/ca7d55422eb53bb3962209aba7527f01cd3ba0b4/docs/gates.md

Gates under heading "Other Common Gates" should be described in more detail. Under Xmon gates, cirq.Z / cirq.Rz must have more detail added.

**Comment by dstrain115** [comment]
Revamped gates document and added more detail throughout.
