### ISSUE TITLE
Use apply_channel similar to apply_unitary.

### ISSUE THREAD

**Issue by cjcarey** [quantumlib/Cirq#2211]
https://github.com/quantumlib/Cirq/blob/dd0934d833e1659951d6f9283c7f38355ba4d64e/cirq/sim/density_matrix_simulator.py#L441

https://github.com/quantumlib/Cirq/blob/dd0934d833e1659951d6f9283c7f38355ba4d64e/cirq/sim/density_matrix_simulator.py#L300

**Comment by balopat** [comment]
These TODOs have been removed / resolved since then.
