### ISSUE TITLE
Implement model circuit and run it

### ISSUE THREAD

**Issue by cjcarey** [quantumlib/Cirq#2213]
https://github.com/quantumlib/Cirq/blob/284499ddf3b50faea1ac9a15e28bb6b9fe306d58/examples/advanced/quantum_volume.py#L128

**Comment by KevinVillela** [comment]
This should be fixed now, see contrib/quantum_volume. Can someone with permissions close it, please?

**Comment by vtomole** [comment]
Note to anyone: Remove that `TODO` line when possible.

**Comment by KevinVillela** [comment]
Thanks! That TODO should be gone: https://github.com/quantumlib/Cirq/blob/master/cirq/contrib/quantum_volume/quantum_volume.py
