### ISSUE TITLE
Handle all coefficients in NotImplementedError

### ISSUE THREAD

**Issue by cjcarey** [quantumlib/Cirq#2214]
https://github.com/quantumlib/Cirq/blob/1788d077dc2231dbd6755bb209b650ce9d1200ea/cirq/contrib/paulistring/clifford_optimize.py#L101

**Comment by dabacon** [comment]
@cduck is the original author of this optimizer and it was later refactored.  My suspicion is that those are the only phases that can be handled, then this should likely become an assert.

**Comment by dstrain115** [comment]
This code no longer exists.  Closing.
