### ISSUE TITLE
Send circuits to Quantum Engine in batches

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#2226]
Each call to Quantum Engine incurs a large overhead in network latency. Currently the only way to batch jobs (and hence reduce this overhead) is to use parameter sweeps. However, it is well known that parameter sweeps have serious limitations, such as the inability of many circuit optimizers to handle parameters. It would be very useful to be able to send non-parameterized circuits in batches too.

@dabacon

**Comment by dstrain115** [comment]
This is now completed.  See https://cirq.readthedocs.io/en/latest/google/engine.html#running-circuits-in-batch for details.

**Comment by dabacon** [comment]
#3135 for follow up thoughts on the interface
