### ISSUE TITLE
Should cirq.experiments methods be at top level?

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#2233]
A bunch of them are missing from the top level `cirq` namespace, but there are some. Do we want them there or should these be in `cirq.experiments`?

**Comment by Strilanc** [comment]
I think if they were at the top level then we might want "experiment" in the name. "rabi_oscillations" is not enough information on its own to describe what will happen.

**Comment by balopat** [comment]
Related to #3228. While the strategy is not fully defined yet, we are moving towards the direction of moving experiments somewhere :) It might end up in its own package / distro or (I'd prefer) in ReCirq.

**Comment by mpharrigan** [comment]
I'd vote for avoiding putting them in the top-level namepsace. And, of course, when a given experiment starts getting complex it should be considered for ReCirq

**Comment by MichaelBroughton** [comment]
TODO: 
1. Determine which (if any) symbols have leaked from the module level to the top level namespace.
2. Which of existing cirq.experiments should move to ReCirq ?

**Comment by dstrain115** [comment]
@pavoljuhas This is an old issue that I am going through.  Can we just answer 'no' to this question and close this issue?

**Comment by pavoljuhas** [comment]
> @pavoljuhas This is an old issue that I am going through. Can we just answer 'no' to this question and close this issue?

Yes, sounds like a good choice.  The last addition to the top-level cirq from cirq.experiments was over 2 years ago in #4854 and we guarantee a backward compatibility for version 1.x.

**Outcome:** Let us keep the cirq namespace as is.  Let us not add any further items from cirq.experiments without a strong reason.
