### ISSUE TITLE
Add hidden shift example

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2252]
https://arxiv.org/abs/quant-ph/0211140

**Comment by bradyb** [comment]
This seems cool, I'll give it a shot.

**Comment by sebgrijalva** [comment]
What's the status on this one? I have some time to work on it if some help is needed.

**Comment by vtomole** [comment]
Ping @bradyb .

**Comment by bradyb** [comment]
ah, I got a little busy, I'm going to unassign.

**Comment by vtomole** [comment]
@sebgrijalva I assigned it to you. Personally, I found https://www.nature.com/articles/s41467-019-13534-2 more useful than the paper i linked above. Have fun!!

**Comment by balopat** [comment]
Was added in #3052, closing.
