### ISSUE TITLE
Put all simulators under one roof of Cirq.Simulator

### ISSUE THREAD

**Issue by MichaelBroughton** [quantumlib/Cirq#2256]
Modify `cirq.Simulator()` so it knows which backend to delegate to when simulating circuits. If there is noise go to `DensityMatrixSimulator` etc.

**Comment by vtomole** [comment]
Could we also add an optional flag like `cirq.Simulator(simulator='density')` so the user can decide explicitly?

**Comment by Strilanc** [comment]
Eh, I think specifying `DensityMatrixSimulator` if you want a density matrix simulator is fine. Having it also as an argument to Simulator, and a stringly typed one at that, seems unnecessary.

**Comment by kevinsung** [comment]
It's not as simple as defaulting to DensityMatrixSimulator if there is noise. For instance, if the noise is coherent then it's still better to use the wavefunction simulator.

**Comment by dabacon** [comment]
For the reason @kevinsung lists I don't think this is feasible. If we were to put this in `Simulator` code one would have no way to do the monte carlo pure state simulator.
