### ISSUE TITLE
PauliSum should support multiplication with PauliSum and raising to integer power

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#2265]

**Comment by trevormccrt** [comment]
You beat me to this! An example of how we want this to behave:

```python
(cirq.X(bit_0) + cirq.Y(bit_0)) *  (cirq.X(bit_1) + cirq.Y(bit_1)) = (cirq.X(bit_0) * cirq.X(bit_1)) + (cirq.X(bit_0) * cirq.Y(bit_1)) + (cirq.Y(bit_0) * cirq.X(bit_1)) + (cirq.Y(bit_0) * cirq.y(bit)_1)


```

**Comment by kevinsung** [comment]
In your example, `*` should denote plain (matrix) multiplication, not the tensor product. The tensor product is implicit in the fact that `cirq.X(bit_0)` represents `X ⊗ I`, `cirq.X(bit_1)` represents `I ⊗ X`, etc.
