### ISSUE TITLE
PauliSum/Lineardict missing some input checking

### ISSUE THREAD

**Issue by trevormccrt** [quantumlib/Cirq#2267]
If you multiply a paulisum by another paulisum (which is not currently supported), lineardict allows the computation until it fails cryptically in LinearDict.clean.

**Comment by aliiitarek** [comment]
Can you give an example to reproduce this issue @trevormccrt ?

**Comment by dabacon** [comment]
I believe that PauliSum now supports multiplication so this is obsolete.
Example
```
a = cirq.NamedQubit('a')
p = (cirq.PauliString([cirq.X(a)]) + cirq.PauliString([cirq.Z(a)])) * (cirq.PauliString([cirq.X(b)]) + cirq.PauliString([cirq.Z(b)]))
```
returns a valid `cirq.PauliSum`
