### ISSUE TITLE
Add validation for Kraus operators 

### ISSUE THREAD

**Issue by peterse** [quantumlib/Cirq#2271]
Many of the methods involving noise/channels mention that the matrices making up a mixture or channel must satisfy \sum_{k=0}^{r-1} A_i^\dagger A_i = I. This is never enforced, which allows the user to simulate unphysical systems and get invalid density matrices (see example below).

Validation is easy enough (`assert np.sum([m.T @ m for m in object._channel_()`) but I'm not sure where to put this @Strilanc ? Ideally this will be called exactly once, before a call to `simulate`. 

Code Example:
```
from typing import Iterable

import cirq
import numpy as np

class UnnormalizedChannel(cirq.GeneralizedAmplitudeDampingChannel):
    """Overwrite the correct amplitude damping channel with a bad one."""
    def _channel_(self) -> Iterable[np.ndarray]:
        p0 = 1
        sqrt_g = np.sqrt(self._gamma)
        return (
            p0 * np.array([[1., 0.], [0., 1.]]),
            p0 * np.array([[0., sqrt_g], [0., 0.]]),
        )


def unnormalized_channel(gamma):
    return UnnormalizedChannel(1.0, gamma)


q0 = cirq.LineQubit(0)
bad_noise_inst = unnormalized_channel(0.3)
c = cirq.Circuit.from_ops(cirq.X(q0), bad_noise_inst.on(q0))
dm = cirq.DensityMatrixSimulator().simulate(c).final_density_matrix
kraus_sum = np.sum(m.T @ m for m in bad_noise_inst._channel_())
print(np.allclose(kraus_sum, np.eye(2)))
print(np.isclose(np.trace(dm), 1.0))
```
which prints
```
>>> False
>>> False
```

**Comment by dabacon** [comment]
One first suggestion is that we should add a testing method that checks this. 

My opinion is just as we don't enforce _unitary_ returns a unitary (because checking it each time would be costly), I think we just need to make it easier for people to test that their channel is OK.

**Comment by c-poole** [comment]
We have routines in `cirq.linalg.predicates` that check for a variety of potential qualities. I would suggest adding some additional methods like `is_cp` and `is_cptp` there for the users to apply on their constructions themselves. We could potentially add a flag in simulate and run which when true performs quantum computing validity checks on the circuit but I'm not convinced whether that would add much benefit if we had a more complete list checks for individual operations in linalg.

**Comment by balopat** [comment]
+1 for using predicate and I like the `is_cp`, `is_cptp` checks.

**Comment by balopat** [comment]
@peterse are you still planning to work on this?

**Comment by peterse** [comment]
oops, sorry for taking so long. I'm struggling to find time to contribute so I'm going to unassign myself for now

**Comment by verult** [comment]
Keeping this before-1.0 as new validation will tighten the API. cc @95-martin-orion
