### ISSUE TITLE
Add `value: int = 1` parameter to `cirq.one_hot`.

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2273]
Instead of putting a 1 at one place, it puts the given value.

**Comment by sycramore** [comment]
Cannot find the function you are refering to. Could you tell me which one you mean exactly or precise your suggestion please?

**Comment by Strilanc** [comment]
It's in `cirq/linalg/states.py`, line 21.

**Comment by jitendrs** [comment]
Please assign it to me. I will update it. @Strilanc

**Comment by vtomole** [comment]
Hey @jitendrs, we've assigned you 3 `first issues` already. Is it okay if we assign you this after you finish one of them?

**Comment by jitendrs** [comment]
hey, @vtomole I don't have any Issue in my queue. That's the reason I was hunting for work.

**Comment by vtomole** [comment]
> I don't have any Issue in my queue

What do you mean? You have https://github.com/quantumlib/Cirq/issues/2191, https://github.com/quantumlib/Cirq/issues/877 and https://github.com/quantumlib/Cirq/issues/338.

**Comment by vtomole** [comment]
Oh wow. I am so sorry.

**Comment by vtomole** [comment]
I've assigned you.

**Comment by jitendrs** [comment]
No Worries Mate. Thanks @vtomole

**Comment by jitendrs** [comment]
Please close this issue since we have merged the same code on #2321.
https://github.com/quantumlib/Cirq/pull/2321
