### ISSUE TITLE
Unable to setup environment from development page.

### ISSUE THREAD

**Issue by jkc1113** [quantumlib/Cirq#2274]
I am trying to set up my environment for development with Cirq. Currently a large number of tests fail when I run "pytest ." as instructed in the "Setting up an environment" section of the development page. I believe this may have something to do with the fact that I could not run "cat apt-system-requirements.txt dev_tools/conf/apt-list-dev-tools.txt | xargs sudo apt-get install --yes" as instructed because I'm on a windows machine. I looked up the packages that get installed by this command and could not find windows equivalents for all of them. As far as setting up a virtual environment I used conda instead of virtualenvwrapper. I was able to add all the required packages within the environment with pip (not including the ones mentioned above).

**Comment by jkc1113** [comment]
This is not an immediate issue as I am just going to use ubuntu on virtualbox going forward.

**Comment by Strilanc** [comment]
There are windows specific install instructions that don't mention apt. Try following those and us know if you still run into problems. It would be helpful if you included an example of the errors you are seeing.

**Comment by dabacon** [comment]
@jkc1113 please reopen this if the windows specific install instructions do not work for you.  They are located at
https://cirq.readthedocs.io/en/stable/install.html#installing-on-windows
