### ISSUE TITLE
Define async result type for engine calls

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#228]

**Comment by dabacon** [comment]
#1982 #1875

**Comment by dabacon** [comment]
Does this make sense any more?  Was the idea for jobs to have an async method that returns the results?

**Comment by MichaelBroughton** [comment]
FYI Going to hijack this issue label section briefly for testing in Triage party

**Comment by tanujkhattar** [comment]
This is probably stale by now. @verult Please reopen the issue if you think this is still relevant. I'll go ahead and close it.

**Comment by verult** [comment]
+1 Engine now has async methods which can be awaited on, so I believe this is obsolete. cc @wcourtney
