### ISSUE TITLE
Windows builds are all failing

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2283]
Example: https://travis-ci.com/quantumlib/Cirq/jobs/243569608

```
$ powershell -command 'Set-MpPreference -DisableArchiveScanning $true'
The command "powershell -command 'Set-MpPreference -DisableArchiveScanning $true'" failed and exited with 1 during .
```

**Comment by c-poole** [comment]
These problems seem to be happening because of a flaky interaction with the "Disabling Windows Defender" stage that appears to be present on the Windows Travis builds. Whether or not that stage succeeds seems to be a function of the powershell commands in the before_install section.

**Comment by dabacon** [comment]
I guess we should be able to write this so that if it fails that is OK (since that would just make the test slower)?

If it is flaky we should probably report it https://travis-ci.community/c/environments/windows

**Comment by dabacon** [comment]
Alternatively we could not put the disabling in "before install"?  
https://travis-ci.community/t/windows-builds-time-out-during-cache-restore/4642/5

**Comment by c-poole** [comment]
From the looks of it we don't have to because by default there is a disabling step that attempts to do it for us. The problem is that that disabling step doesn't always work. If it doesn't work, the build seems to pass, but the installs take longer.

**Comment by c-poole** [comment]
Have the matplotlib and powershell changes fixed this issue? I haven't had an errant failure in any of my commits but I'm only one data point.

**Comment by vtomole** [comment]
There is no Window's-based failure on master for past 2 weeks. @Strilanc PR to fix this hasn't been reviewed yet.
