### ISSUE TITLE
Automate API reference documentation

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2285]
Currently, it is very easy to accidentally forget to add a cirq method or class to the API reference. There's probably dozens missing. Here is my proposal for fixing this:

1. Introduce decorators like `@cirq._internal.doc(category='circuits')` and helper methods like `cirq._internal.documented_constant(val, category='ops')`. These decorates and methods build up a global list of documented things.
2. Add a test that fails if any top-level class or method has not been doc'd, similar to the json serialization test.
3. Have a script that basically imports cirq and dumps the list of documented things into a `.rst` file that is the api reference.

**Comment by cduck** [comment]
Suggestion: Make the functions no-ops during normal execution (just like typing.cast) to reduce import-time overhead.

**Comment by Strilanc** [comment]
I'm not sure how much that will save, since I'm imagining the bodies consisting of basically `some_list.append(the_thing)`. The string construction would all happen basically unconditionally.

**Comment by mpharrigan** [comment]
You can probably maneuver sphinx autodoc/autosummary to do what you want without putting annotations everywhere
