### ISSUE TITLE
Installing Cirq on Alpine Linux

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#2289]
Is Cirq supported on Alpine Linux? I've been using the following steps to attempt to install Cirq in an Alpine-based Docker image:

```
# Base OS is alpine:latest
$ apk update
$ apk add g++ make gsl-dev git
$ apk add python3-dev py-pip pkgconfig
$ pip3 install --upgrade pip
$ pip3 install -U cirq
```

The above script produces the error:
`The following required packages can not be built: * freetype, png`

Modifying the script to explicitly add these packages (freetype, libpng) causes it to take considerably longer (5+ minutes) before failing with:
`numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.`

I can provide additional error log details if needed.

**Comment by 95-martin-orion** [comment]
Update: We were able to install using the following commands:
```
$ apk add libpng-dev freetype-dev
$ apk add python3-dev python3-tkinter
$ apk add py3-scipy py-numpy-dev
$ apk add openblas-dev
$ pip3 install --upgrade pip
$ pip3 install cirq
```

**Comment by vtomole** [comment]
Might want to add other dockerfiles besides [Ubuntu](https://github.com/quantumlib/Cirq/blob/master/Dockerfile). Every dockerfile needs to be in it's own directory; so maybe we can have a `dev_tools/docker/apline/Dockerfile` e.t.c. Opinions @Strilanc ?

**Comment by Strilanc** [comment]
That particular docker environment is for development I think, so it makes sense for it to be in dev_tools.
