### ISSUE TITLE
Deprecate Engine.run and Engine.run_sweep

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#2294]
https://github.com/quantumlib/Cirq/pull/2096#pullrequestreview-287747568

**Comment by dabacon** [comment]
@Strilanc so now I can only use sample and I will always lose the id of any program or job I created.  This seems like a problem to me.

**Comment by dabacon** [comment]
We ended up with a pattern where the sample is gotten from the engine and these other methods still exist.  See discussion in linked PR for why we can't remove them.  These were refactored.  Closing.
