### ISSUE TITLE
Convert documentation to jupyter notebooks. 

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#2310]
These display nicely in github, and we can directly link to opening them in colab and other places where you can run the notebooks.

**Comment by mpharrigan** [comment]
nbsphinx also works well

**Comment by bt3gl** [comment]
Hi, kindly assign this to me, as I am aiming to resolve it in #2542 .

**Comment by vtomole** [comment]
Closed by https://github.com/quantumlib/Cirq/pull/2713
