### ISSUE TITLE
Mixture and Channel do not have performant variants, and the protocols do not mesh quite correctly.

### ISSUE THREAD

**Issue by MichaelBroughton** [quantumlib/Cirq#2311]
It is currently not possible to apply a mixture without generating huge matrices. There also appears to be a missing concept around the notion of a "reset", which should be usable inside of monte carlo unitary simulations but currently forces the density matrix simulator.

**Comment by MichaelBroughton** [comment]
Plan to fix this problem by adding a new Monte-Carlo simulator to the sim directory and also modify mux to send noisy circuits that can be simulated without the need for a full density matrix to it, before falling back to the density matrix simulator

**Comment by dabacon** [comment]
We now have `apply_channel` and `apply_mixture`.   @Strilanc is working on a common method `_act_on_` which may end up deprecating these.
