### ISSUE TITLE
Getting AttributeError while running example from README.rst

### ISSUE THREAD

**Issue by jitendrs** [quantumlib/Cirq#2341]
Error log:

Backend MacOSX is an interactive backend. Turning interactive mode on.
Traceback (most recent call last):
 Cirq_example/example.py", line 13, in <module>
    cirq.measure(qubit, key ='m')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cirq/circuits/circuit.py", line 106, in __init__
    self._device.validate_circuit(self)
**AttributeError: 'GateOperation' object has no attribute 'validate_circuit'**

OS:- macOS
Python version: 3.7

**Comment by vtomole** [comment]
What version of Cirq are you running?

**Comment by vtomole** [comment]
The examples run on the code that is currently on master. Install using `~/Cirq$pip install e .`

**Comment by jitendrs** [comment]
Thanks it works.!
