### ISSUE TITLE
Qubits shouldn't be mutable

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#2356]
```python
import cirq
q1 = cirq.LineQubit(1)
circuit = cirq.Circuit(cirq.X(q1))
print(circuit)
q1.x = 2
print(circuit)
```

```
1: ───X───
2: ───X───
```

**Comment by Strilanc** [comment]
Agreed.

LineQubit and GridQubit should have their values hidden behind property methods.

**Comment by dabacon** [comment]
A new way to remap qubits!  (j/k).  Yes to immutable.

**Comment by mpharrigan** [comment]
We can also consider using dataclasses with `frozen=True`, which offers a stronger form of immutability

**Comment by bt3gl** [comment]
Could you please assign this issue to me? (#2385)

**Comment by fedimser** [comment]
Can you please assign this to me?
@vtomole @Strilanc
