### ISSUE TITLE
Add over- and under-rotation noise models

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#2365]
- Add Gaussian noise with specified mean and standard deviation

**Comment by Strilanc** [comment]
So this would like, replace all X, Y, and PhasedX gates with variants that rotate by epsilon more? Or would it also affect some other gates?

**Comment by kevinsung** [comment]
I think we'll want to be more general than that. For instance, #1001 requests the ability to add Gaussian noise. I also think we might want to let the user specify which gates are affected. I'm not sure yet what this will look like. @dabacon might have thoughts.

**Comment by dstrain115** [comment]
Closing as obsolete.  This request is too vague and could be implemented in too many ways, and it's not clear what people would want.

If people want this noise model, they can implement themselves or add it to contrib.
