### ISSUE TITLE
Add BB84 example

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2367]
https://en.m.wikipedia.org/wiki/BB84

We have an "Alice and Bob" example you can use as inspiration: https://github.com/quantumlib/Cirq/blob/master/examples/bell_inequality.py

**Comment by deadbeatfour** [comment]
I'd like to work on this, please!

**Comment by vtomole** [comment]
@deadbeatfour Have fun!!

**Comment by deadbeatfour** [comment]
Hey! I've added a file with the program. I'd love some feedback.

**Comment by dabacon** [comment]
A basic example exists.
