### ISSUE TITLE
Implement quil_output.py

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2386]
This will be similar to QASM output: https://github.com/quantumlib/Cirq/blob/master/cirq/circuits/qasm_output.py
but for QUIL (https://arxiv.org/abs/1608.03355). Use the QUIL specification (https://github.com/rigetti/quil/blob/master/spec/Quil.md) as a reference when making this program.

This will require a design. https://github.com/quantumlib/Cirq/issues/1548#issuecomment-485039043 is a good example. Please add a design to this ticket before implementing the program.

A comparison of how this should work like QASM output:

**Below is an example of how Cirq outputs QASM:**

```python
q0, = _make_qubits(1) # create one quantum bit
output = cirq.QasmOutput((cirq.X(q0),), (q0,)) #apply the X gate to the quantum bit
assert (str(output) ==
"""OPENQASM 2.0; # Describes the version of QASM
include "qelib1.inc";  # Import a predefined gate library


// Qubits: [q0]
qreg q[1]; # initialize a quantum register


x q[0]; # Apply the X gate to the defined qubit
""") # The output is the cirq circuit converted to  a string that represents the QASM program
```

**Below is an example of how Cirq will output QUIL:**
```python
q0, = _make_qubits(1)
output = cirq.QuilOutput((cirq.X(q0),), (q0,))
assert (str(output) == """X 0"""
```

**Comment by hanusaj** [comment]
Assign to me.

**Comment by hanusaj** [comment]
# Preliminary design document - Looking for feedback for more to add and outline

# Design for export to QUIL in Cirq

To output a circuit to QUIL format in Cirq, the following call can be made:

**Below is an example of printing the QUIL output in Cirq:**

```
q0, = _make_qubits(1)
output = cirq.QuilOutput((cirq.X(q0),), (q0,))
print(output)
```

**The print statement would output the following:**

```
# Created from Cirq
X 0
```


## Gate Conversion Rules for Standard QUIL Gates

| Cirq Gate     | QUIL Gate | Notes                                                        |
| ------------- | --------- |:------------------------------------------------------------ |
| Cirq.H        | H         | Hadamard gate                                                |
| Cirq.X        | X         | Pauli X (PI rotation over X-axis) aka "NOT" gate             |
| Cirq.Y        | Y         | Pauli Y (PI rotation over Y-axis)                            |
| Cirq.Z        | Z         | Pauli Z (PI rotation over Z-axis)                            |
| Cirq.RX       | RX        | Rotation around the X-axis by given angle                    |
| Cirq.RY       | RY        | Rotation around the Y-axis by given angle                    |
| Cirq.RZ       | RZ        | Rotation around the Z-axis by given angle                    |
| Cirq.S        | S         | PI/2 rotation over Z-axis (synonym for r2)                   |
| Cirq.T        | T         | PI/4 rotation over Z-axis (synonym for r4)                   |
| Cirq.CZ       | CZ        |  A gate that applies a phase to the \|11⟩ state of two qubits. |
| Cirq.FREDKIN  | CSWAP     | A controlled swap gate |
| Cirq.CSWAP    | CSWAP     | Controlled swap aka "Fredkin" gate                           |
| Cirq.Identity | I         | A Gate that perform no operation on qubits.                  |
| Cirq.CX       | CNOT      | Controlled Pauli X (PI rotation over X-axis) aka "CNOT" gate |
| Cirq.CCX      | CCNOT     | Toffoli aka "CCNOT" gate                                     |
| Cirq.TOFFOLI  | CCNOT     | Toffoli aka "CCNOT" gate                                     |
| Cirq.SWAP     | SWAP      | Swaps the state of two qubits. |
| Cirq.ISWAP    | ISWAP     | Rotates the \|01⟩-vs-\|10⟩ subspace of two qubits around its Bloch X-axis. |
| Cirq.ISWAP    | PSWAP     | Not sure if supported |
| Cirq.ISWAP    | CPHASE00  | Not sure if supported |
| Cirq.ISWAP    | CPHASE01  | Not sure if supported |
| Cirq.ISWAP    | CPHASE10  | Not sure if supported |
| Cirq.ISWAP    | CPHASE    | Not sure if supported |

## Implementation

For each Cirq gate that can be output to a standard QUIL gate, a quil representation was add to the gate. 

**Below is an example of the quil function for the X gate:**

```
def _quil_(self, args, qubits):
    return args.format("X {0}", qubits[0])
```

**Comment by vtomole** [comment]
@hanusaj  Looks fine to me so far. CPHASE is supported in Cirq as `cphase = cirq.CZPowGate(exponet=t)`. QUIL defines it as

```
DEFGATE CPHASE(%alpha):
    1, 0, 0, 0
    0, 1, 0, 0
    0, 0, 1, 0
    0, 0, 0, cis(%alpha)
```

Look at the matrix of  ` CZPowGate` https://github.com/quantumlib/Cirq/blob/190c41fb95a422d5828f74054b50f3ce16e20bb8/cirq/ops/common_gates.py#L605.


The other CPHASE gates are not supported by Cirq. We will need to add them.

**Comment by hanusaj** [comment]
# Preliminary design document

# Design for export to QUIL in Cirq

To output a circuit to QUIL format in Cirq, the following call can be made:

**Below is an example of printing the QUIL output in Cirq:**

```
q0, = _make_qubits(1)
output = cirq.QuilOutput((cirq.X(q0),), (q0,))
print(output)
```

**The print statement would output the following:**

```
# Created from Cirq
X 0
```


## Gate Conversion Rules for Standard QUIL Gates

| Cirq Gate      | QUIL Gate | Notes                                                        |
| -------------- | --------- |:------------------------------------------------------------ |
| Cirq.H         | H         | Hadamard gate                                                |
| Cirq.X         | X         | Pauli X (PI rotation over X-axis) aka "NOT" gate             |
| Cirq.Y         | Y         | Pauli Y (PI rotation over Y-axis)                            |
| Cirq.Z         | Z         | Pauli Z (PI rotation over Z-axis)                            |
| Cirq.RX        | RX        | Rotation around the X-axis by given angle                    |
| Cirq.RY        | RY        | Rotation around the Y-axis by given angle                    |
| Cirq.RZ        | RZ        | Rotation around the Z-axis by given angle                    |
| Cirq.S         | S         | PI/2 rotation over Z-axis (synonym for r2)                   |
| Cirq.T         | T         | PI/4 rotation over Z-axis (synonym for r4)                   |
| Cirq.CZ        | CZ        |  A gate that applies a phase to the \|11⟩ state of two qubits. |
| Cirq.FREDKIN   | CSWAP     | A controlled swap gate |
| Cirq.CSWAP     | CSWAP     | Controlled swap aka "Fredkin" gate                           |
| Cirq.Identity  | I         | A Gate that perform no operation on qubits.                  |
| Cirq.CX        | CNOT      | Controlled Pauli X (PI rotation over X-axis) aka "CNOT" gate |
| Cirq.CCX       | CCNOT     | Toffoli aka "CCNOT" gate                                     |
| Cirq.TOFFOLI   | CCNOT     | Toffoli aka "CCNOT" gate                                     |
| Cirq.SWAP      | SWAP      | Swaps the state of two qubits. |
| Cirq.ISWAP     | ISWAP     | Rotates the \|01⟩-vs-\|10⟩ subspace of two qubits around its Bloch X-axis. |
| **_Cirq.PSWAP_** | PSWAP     | Need to implement. See section below. |
| Criq.CZPowGate | CPHASE    | A gate that applies a phase to the \|11⟩ state of two qubits. |
| **_Cirq.CZPowGate00_** | CPHASE00  | Need to implement. See section below. |
| **_Cirq.CZPowGate01_** | CPHASE01  | Need to implement. See section below. |
| **_Cirq.CZPowGate10_** | CPHASE10  | Need to implement. See section below. |

_Italic and bold means we will be implementing them_

## Implementation

For each Cirq gate that can be output to a standard QUIL gate, a quil representation was add to the gate. 

**Below is an example of the quil function for the X gate:**

```
def _quil_(self, args, qubits):
    return args.format("X {0}", qubits[0])
```

### Unsupported Gates

The gates will be added to [common_gates.py](https://github.com/quantumlib/Cirq/blob/190c41fb95a422d5828f74054b50f3ce16e20bb8/cirq/ops/common_gates.py).

The matrices for each of the gates can be found below. They will also include the ``_quil_`` function which will output according to [Quil.md](https://github.com/rigetti/quil/blob/master/spec/Quil.md) or [this](https://arxiv.org/abs/1608.03355) documentation.

**PSWAP --> Cirq.PSWAP**

```
    1, 0,           0,           0
    0, 0,           cis(%theta), 0
    0, cis(%theta), 0,           0
    0, 0,           0,           1
```

**CPHASE00 --> Cirq.CZPowGate00**

```
    cis(%alpha), 0, 0, 0
    0,           1, 0, 0
    0,           0, 1, 0
    0,           0, 0, 1
```

**CPHASE01 --> Cirq.CZPowGate01**

```
    1, 0,           0, 0
    0, cis(%alpha), 0, 0
    0, 0,           1, 0
    0, 0,           0, 1
```

**CPHASE10 --> Cirq.CZPowGate10**

```
    1, 0, 0,           0
    0, 1, 0,           0
    0, 0, cis(%alpha), 0
    0, 0, 0,           1
```

**Comment by vtomole** [comment]
@hanusaj  `common_gates.py` contains too many gates already. Let's create a `cphase_gates.py` and write `PSWAP` in `cirq/ops/swap_gates.py`. Use https://github.com/quantumlib/Cirq/blob/15c142df5b1d27bdd42bd5b3f9330cf0c5af4e9b/cirq/ops/swap_gates.py#L257 as a reference on how to define `PSWAP` (they are very similar).

**Comment by Strilanc** [comment]
Do we really need to add all these CZ variants? How about a single `TwoQubitDiagonalGate` to accompany `ThreeQubitDiagonalGate`?

**Comment by vtomole** [comment]
@Strilanc okay let's do that.

**Comment by hanusaj** [comment]
# Design for export to QUIL in Cirq

To output a circuit to QUIL format in Cirq, the following call can be made:

**Below is an example of printing the QUIL output in Cirq:**

```
q0, = _make_qubits(1)
output = cirq.QuilOutput((cirq.X(q0),), (q0,))
print(output)
```

**The print statement would output the following:**

```
# Created from Cirq
X 0
```


## Gate Conversion Rules for Standard QUIL Gates

| Cirq Gate      | QUIL Gate | Notes                                                        |
| -------------- | --------- |:------------------------------------------------------------ |
| Cirq.H         | H         | Hadamard gate                                                |
| Cirq.X         | X         | Pauli X (PI rotation over X-axis) aka "NOT" gate             |
| Cirq.Y         | Y         | Pauli Y (PI rotation over Y-axis)                            |
| Cirq.Z         | Z         | Pauli Z (PI rotation over Z-axis)                            |
| Cirq.RX        | RX        | Rotation around the X-axis by given angle                    |
| Cirq.RY        | RY        | Rotation around the Y-axis by given angle                    |
| Cirq.RZ        | RZ        | Rotation around the Z-axis by given angle                    |
| Cirq.S         | S         | PI/2 rotation over Z-axis (synonym for r2)                   |
| Cirq.T         | T         | PI/4 rotation over Z-axis (synonym for r4)                   |
| Cirq.CZ        | CZ        |  A gate that applies a phase to the \|11⟩ state of two qubits. |
| Cirq.FREDKIN   | CSWAP     | A controlled swap gate |
| Cirq.CSWAP     | CSWAP     | Controlled swap aka "Fredkin" gate                           |
| Cirq.Identity  | I         | A Gate that perform no operation on qubits.                  |
| Cirq.CX        | CNOT      | Controlled Pauli X (PI rotation over X-axis) aka "CNOT" gate |
| Cirq.CCX       | CCNOT     | Toffoli aka "CCNOT" gate                                     |
| Cirq.TOFFOLI   | CCNOT     | Toffoli aka "CCNOT" gate                                     |
| Cirq.SWAP      | SWAP      | Swaps the state of two qubits. |
| Cirq.ISWAP     | ISWAP     | Rotates the \|01⟩-vs-\|10⟩ subspace of two qubits around its Bloch X-axis. |
| Cirq.SwapPowGate | PSWAP     | The SWAP gate, possibly raised to a power, exchanges qubits. |
| Criq.CZPowGate | CPHASE    | A gate that applies a phase to the \|11⟩ state of two qubits. |
| Cirq.TwoQubitDiagnalGate | CPHASE00  |  |
| Cirq.TwoQubitDiagnalGate | CPHASE01  |  |
| Cirq.TwoQubitDiagnalGate | CPHASE10  |  |

_Italic and bold means we will be implementing them_

## Implementation

For each Cirq gate that can be output to a standard QUIL gate, a quil representation was add to the gate. 

**Below is an example of the quil function for the X gate:**

```
def _quil_(self, args, qubits):
    return args.format("X {0}", qubits[0])
```

### Non-Standard Cirq Gates

For Cirq gates that are not standard gates in QUIL, the ``DEFGATE`` keyword will be used to output a new gate in QUIL that can be used to represent the Cirq gate. For example:

**Cirq.FSimGate**

```
DEFGATE FSIMGATE:
    1, 0             , 0             , 0
    0, cos(%theta)   , -i*sin(%theta), 0
    0, -i*sin(%theta), cos(%theta)   , 0
    0, 0             , 0             , exp(-i*%phi)
```

### Cirq ResetChannel

A ``_quil_`` function will be added the the Cirq ResetChannel to be able to output the ResetChannel with the ``RESET`` keyword to QUIL.

### Cirq Measure

The cirq.measure function results in the ``MEASURE`` keyword in QUIL.

### Cirq Circuits

The Cirq circuits will be defined in Cirq using the ``DEFCIRCUIT`` keyword. For example:

**Bell Inequality**

```
DEFCIRCUIT BELLINEQUALITY q0, q1, q2, q3:
    H q0
    CNOT q0, q1
    X q0
    H q2
    H q3
    CNOT q2, q0
    CNOT q3, q1
    
    MEASURE q0
    MEASURE q1
    MEASURE q2
    MEASURE q3
```

**Comment by vtomole** [comment]
@hanusaj 

Please edit you design instead of adding new ones from now on because they are pretty large.

> Non-Standard Cirq Gates

There other non-standard gates in Cirq besides `fsim`. Please list all the ones that you intend to define `__quil__` for

> The Cirq circuits will be defined in Cirq using the DEFCIRCUIT keyword.

I don't know what this means. Cirq circuits will not be defined in Cirq using the `DEFCIRCUIT` keyword. Please explain.

Most of the operations in Cirq will need `_quil_`. Some of them might be too big to use `DEFGATE`. That's where `DEFCIRCUIT` might come into the picture (you can use an operation's `_decompose_` method to define this.


You need to add `CONTROLLED`, `DAGGER`, and `FORKED`, and `WAIT` to your design  e.t.c. This design doesn't address everything on https://github.com/rigetti/quil/blob/master/spec/Quil.md.

**Comment by alexandrupaler** [comment]
@vtomole @hanusaj will this interface be usable to execute computations on Rigetti machines from Cirq?

**Comment by vtomole** [comment]
@alexandrupaler Yes. The QUIL code that Cirq generates makes it possible to run programs writen in Cirq to run on Rigetti's QVM like so

```
$ docker pull rigetti/qvm
$ cat test.quil
H 0
$ cat test.quil | docker run --rm -i rigetti/qvm

$ Classical memory (low -> high indexes):
    No memory.
Amplitudes:
    |0>: 0.7071067811865475,                                    P= 50.0%
    |1>: 0.7071067811865475,                                    P= 50.0%

```

Same with the [optimizing compiler](https://github.com/rigetti/quilc) and on their hardware using https://github.com/rigetti/rpcq/. We are just generating QUIL and adding instructions on how users can leverage Rigetti's infrastructure. Similar to  https://github.com/quantumlib/Cirq/issues/2541.
