### ISSUE TITLE
AttributeError: 'GateOperation' object has no attribute 'validate circuit'

### ISSUE THREAD

**Issue by AbhishekSalaria** [quantumlib/Cirq#2400]

**Comment by vtomole** [comment]
Hey @AbhishekSalaria you are probably trying to run a `0.6` cirq program on a `0.5` version. See: https://github.com/quantumlib/Cirq/issues/2341

**Comment by vtomole** [comment]
@AbhishekSalaria I'm going to close this. Please ping me if what I previously posted doesn't work for you.

**Comment by AbhishekSalaria** [comment]
You can close it , thank you :)
