### ISSUE TITLE
Add dev_tools/docker/alpine/Dockerfile

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2403]
See https://github.com/quantumlib/Cirq/issues/2289 for context.

**Comment by jitendrs** [comment]
@vtomole can you please assign it to me?

**Comment by jitendrs** [comment]
@vtomole can you please review and approve pull request

**Comment by vtomole** [comment]
@jitendrs I'll review it first thing in the morning!

**Comment by jitendrs** [comment]
@vtomole Thanks, mate.
