### ISSUE TITLE
PointOptimizer that respects moment structure

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#2406]
Right now ops get flattened during initialization of PointOptimizationSummary and during circuit.insert_at_frontier. Would be nice to be able to transform circuits in a more structured way

**Comment by tanujkhattar** [comment]
I'll marked this as fixed given the new moment preserving primitives, which are now intended to replace PointOptimizer completely. Please feel free to file another issue if you run into a scenario where the newly added moment preserving primitives are not sufficient and you need a moment preserving version of PointOptimizer.

**Comment by tanujkhattar** [comment]
https://github.com/quantumlib/Cirq/pull/5154 adds a tutorial to Cirq on new transformer infrastructure, with details of newly added moment preserving primitives.
