### ISSUE TITLE
cirq.measure should accept List[Qid] the same way "on_each" does.

### ISSUE THREAD

**Issue by zchen088** [quantumlib/Cirq#2408]

**Comment by Strilanc** [comment]
You mean the way it auto-flattens the list if you pass it in by accident instead of `*args` passing it? Makes sense.

**Comment by dixr** [comment]
I second that.

The usecase is similar to the one discussed for on_each in #1624 and was fixed for on_each with #1674

We should have it for cirq.measure too.

**Comment by acdotts** [comment]
@googlebot I signed it!
