### ISSUE TITLE
Is there a way to ask a Circuit "what are all of your measurement keys?"

### ISSUE THREAD

**Issue by zchen088** [quantumlib/Cirq#2411]

**Comment by Strilanc** [comment]
I wonder if this is something that should fall under the purview of `cirq.measurement_key`? Main issue being that it's not just one key...

**Comment by dabacon** [comment]
This is an argument for making the measurement keys (plural) that @Strilanc has advocated.

**Comment by Strilanc** [comment]
`cirq.measurement_keys(circuit)`
