### ISSUE TITLE
DensityMatrixSimulator().simulate() return value type annotation

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#2413]
Should be `DensityMatrixTrialResult`. Due to inheritance, it is `SimulationTrialResult` leading to problems if you actually try to use it

https://github.com/quantumlib/Cirq/pull/2308#issuecomment-546538095

**Comment by Ashalynd** [comment]
Shouldn't there be some consistency? E.g. all simulate() methods should return SimulationTrialResult which then can be cast to the corresponding type. (Thought it seems odd too)

**Comment by daxfohl** [comment]
@balopat This has been fixed for a while and can be closed.

**Comment by mpharrigan** [comment]
Fixed by #3818
