### ISSUE TITLE
Circuit + Moment doesn't work if Moment is ahead.

### ISSUE THREAD

**Issue by jaeyoo** [quantumlib/Cirq#2415]
For 0.6.0dev, c is a cirq.Circuit() and m is a cirq.Moment().

new_c = c[:j] + m + c[j:] works well without error, but

new_c = m +  c[:j] + c[j:] shows error like: 

TypeError: unsupported operand type(s) for +: 'Moment' and 'Circuit'

Could you please add this feature or is it intended?

**Comment by jaeyoo** [comment]
Currently, I'm just using a hack like: cirq.Circuit(m1) + c[:j] + m2 + c[j:], which looks unhappy.

**Comment by c-poole** [comment]
`Circuit` is missing an `__radd__` method that will fix this. We can and definitely should put this in.

**Comment by jaeyoo** [comment]
Thanks a lot

**Comment by jaeyoo** [comment]
Please check this PR #2418. How can I add you as a reviewer and myself to assignee?

**Comment by jaeyoo** [comment]
PR #2418 is merged.
