### ISSUE TITLE
Serializer : AttributeError: 'ControlledOperation' object has no attribute 'gate'

### ISSUE THREAD

**Issue by jaeyoo** [quantumlib/Cirq#2416]
File "/usr/local/google/home/jaeyoo/git/Cirq/cirq/google/serializable_gate_set.py", line 136, in serialize_op
    gate_type = type(gate_op.gate)

AttributeError: 'ControlledOperation' object has no attribute 'gate'

When I try to serialize a circuit with "cirq.ControlledGate(cirq.Z).on(q0, q1)", It shows the above error. (yes, ControlledOperation doesn't have "gate" : https://github.com/quantumlib/Cirq/blob/master/cirq/ops/controlled_operation.py#L25).
Is it intended or am I doing wrongly? 
CZ, CZPowGate is possible to be serialized because they are eigen gates. That means, do I have to use them always for serialization? What if I want to make C-ZZ operator and serialize it, how can i do it?

**Comment by maffoo** [comment]
It should work if you create a CZPowGate instead of using ControlledGate(cirq.Z), but this may depend on which gate set you are trying to serialize to. It looks like we don't have a good way of supporting controlled operations in SerializableGateSet, so we will have to add support for that.

**Comment by Strilanc** [comment]
Yeah, this is a good example of how consuming gates is complicated by the ability to specify them in multiple ways.

**Comment by Ashalynd** [comment]
Would it make sense for the serializer to check that an unknown gate is equivalent to one of the known serializable gates, as a relatively quick workaround? (May be not by default, but as an option)

**Comment by jaeyoo** [comment]
Yes, what I am implementing requires conditioning any DensePauliString and any PauliSum. I've tried maffoo's suggestion by using ConvertToCzAndSingleGates to use CZPowGate only, but it shows errors:
`
>>> import cirq
>>> import sympy
>>> a = sympy.Symbol('a')
>>> b = cirq.Ry(a).on(cirq.GridQubit(0,0))
>>> c = cirq.Circuit([b])
>>> c
cirq.Circuit([
    cirq.Moment(operations=[
        cirq.Ry(sympy.Symbol('a')).on(cirq.GridQubit(0, 0)),
    ]),
])
>>> print(c)
(0, 0): ───Ry(a)───
>>> d = cirq.ConvertToCzAndSingleGates().optimize_circuit(c)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/jaeyoo/git/tfq/Cirq/cirq/circuits/optimization_pass.py", line 127, in optimize_circuit
    opt = self.optimization_at(circuit, i, op)
  File "/usr/local/google/home/jaeyoo/git/tfq/Cirq/cirq/optimizers/convert_to_cz_and_single_gates.py", line 95, in optimization_at
    else self._on_stuck_raise))
  File "/usr/local/google/home/jaeyoo/git/tfq/Cirq/cirq/protocols/decompose.py", line 273, in decompose
    error = on_stuck_raise(item)
  File "/usr/local/google/home/jaeyoo/git/tfq/Cirq/cirq/optimizers/convert_to_cz_and_single_gates.py", line 82, in _on_stuck_raise
    "known unitary effect on 1 or 2 qubits.".format(op))
TypeError: Don't know how to work with cirq.Ry(sympy.Symbol('a')).on(cirq.GridQubit(0, 0)). It isn't composite or an operation with a known unitary effect on 1 or 2 qubits.
`
Could you give me more advices?

**Comment by jaeyoo** [comment]
Ok, I found out a way. Close this issue and open the new issue related to cirq.decompose()

**Comment by vipasu** [comment]
@jaeyoo Could you say more about the workaround to for your example? Also interested in ways to make more gates serializable with sympy symbols.
