### ISSUE TITLE
Add GmonDevice and Sycamore chip

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#2427]

**Comment by dstrain115** [comment]
Devices can now be found in https://github.com/quantumlib/Cirq/blob/master/cirq/google/devices/known_devices.py

Sycamore and Sqrt_iswap gate sets can be found here:
https://github.com/quantumlib/Cirq/blob/master/cirq/google/gate_sets.py#L34

Optimizers can be found here:
https://github.com/quantumlib/Cirq/blob/master/cirq/google/optimizers/optimize_for_sycamore.py#L76

These should all be accessible at the cirq.google namespace.

Documentation is newly committed at:
https://github.com/quantumlib/Cirq/blob/master/docs/google/devices.md
It should appear on readthedocs after the next documentation build.

Closing this ticket.
