### ISSUE TITLE
(re-)register deserializer for QuantumVolumeResult

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#2445]
following #2443

cc @KevinVillela

**Comment by KevinVillela** [comment]
Thanks for the heads up - @Strilanc was saying that we can probably put the Quantum Volume stuff into cirq/experiments now. Happy to do that if it makes sense.

**Comment by Strilanc** [comment]
Yes, that would resolve this issue (+ restoring the entries in the big json dictionary)

**Comment by KevinVillela** [comment]
I tried moving the file, but then I realized that it actually depends on something else in contrib - cirq.contrib.routing :\ https://github.com/quantumlib/Cirq/blob/master/cirq/contrib/quantum_volume/quantum_volume.py#L11. That means we don't want to pull it in, right? Is routing something we want in regular Cirq, or do we need another solution for json-ifying things in contrib?

**Comment by KevinVillela** [comment]
Couple of other options:
  - Re-write quantum_volume.py to take in an arbitrary routing function, which would be called with ccr.route_circuit. This isn't ideal because routing is kind of a central part of the algorithm.
 - Just move QuantumVolumeResult (which has no contrib dependencies) out of contrib temporarily.

**Comment by mpharrigan** [comment]
If we do have an `experiments/` module, the code will likely need to depend on contrib-quality code. Any experiment worth its salt will identify functionality not *strictly* associated with the experiment itself but either (a) not worth it (for the experiment developer) to put in the (large) effort to move to cirq-proper, or (b) slightly too specific to alleviate concerns of cirq becoming bloated

**Comment by Strilanc** [comment]
It might be worth putting the effort into getting parts of routing into the main library. I know that people are using it, which is a strong indicator.

**Comment by mpharrigan** [comment]
I suspect we'll soon and have experiment code that uses contrib code outside of whether routing is ready to graduate or not
