### ISSUE TITLE
Travis misc check installs requirements unnecessarily

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2446]
https://travis-ci.com/quantumlib/Cirq/jobs/250854540

![image](https://user-images.githubusercontent.com/79941/67817614-46560d00-fa6b-11e9-92fd-89c7fbc2bc88.png)

I thought that leaving out the 'install' field in the travis.yaml would result in no install steps. I believe this is a default step. So maybe 'install' is needed with a blank entry? Just needs to be checked.

**Comment by himanshujaju** [comment]
`install: skip` should be the intended solution?
https://docs.travis-ci.com/user/job-lifecycle/#skipping-the-installation-phase

**Comment by vtomole** [comment]
It worked. Thank you @himanshujaju .
