### ISSUE TITLE
`protocols/json.py` confuses python path

### ISSUE THREAD

**Issue by peterse** [quantumlib/Cirq#2447]
Running python from within the protocols directory causes `protocols/json.py` to shadow json, resulting in `AttributeError: module 'json' has no attribute 'loads'` (for example).

This makes running individual tests in protocols slightly confusing. Does the module need to be named `json.py`?

**Comment by maffoo** [comment]
Same problem for `cirq.google` package, but I think the solution is the same. There are just too many possible name collisions to be able to avoid them all, so the best thing is to use namespaces (they are a [honking great idea](https://www.python.org/dev/peps/pep-0020/) after all :-) ). CD'ing into a package hierarchy puts subpackages onto your python path, which breaks package namespacing.

**Comment by peterse** [comment]
>  it's best to never cd inside a python package hierarchy.

Fair enough.
