### ISSUE TITLE
pylint failure on travis that is unrelated to PR changes

### ISSUE THREAD

**Issue by maffoo** [quantumlib/Cirq#2466]
I just had this [pylint failure](https://travis-ci.com/quantumlib/Cirq/jobs/251552372) on travis in a file that was not touched in my PR. I have seen similar issues locally where pylint detects problems in completely unrelated files. I think @Strilanc mentioned that this might be due to pylint caching information about various files, but in any case it would be good to fix it to make the lint job more robust.

**Comment by MichaelBroughton** [comment]
Pretty sure this is good to close (PR'd a fix that got entirely merged out when I merged master), have you had it recently @maffoo ?

**Comment by maffoo** [comment]
I don't get any lint failures on master, so that's good. I don't see that we've actually fixed whatever was causing local lint and travis lint to disagree, but it's probably not actionable, so I'll close for now.
