### ISSUE TITLE
Angles in radians (rather than turns or half turns)

### ISSUE THREAD

**Issue by viathor** [quantumlib/Cirq#2472]
I've come to think that use of radians for things like phase angles would lead to more readable code. Specifically, presence of pi in an expression acts as a "unit", hinting the reader that the quantity they're looking at is an angle.

Such values would also be directly comparable to expressions encountered in textbooks, papers, blogs etc.

OTOH, counting turns leads to values that are easier to mix up with other quantities. Also, it's generally unclear whether we count full turns or half turns.

This issue proposes to replace all turns and half turns with angles in radians, i.e. expressions like

```python
p = np.exp(2j * np.pi * phase_turns)
```
would become

```python
p = np.exp(2j *  phase_rads)
```

Thoughts?

**Comment by mpharrigan** [comment]
Where do you want this? In the constructor of gates? Is is similar to the difference between `XPowGate` and `Rx`?

**Comment by dabacon** [comment]
Somewhat related discussion which points out problems with PowGate and Rot gates : #1800

**Comment by balopat** [comment]
Discussed at Cirq Cynq: 
- we should make this issue a bit more specific around what the change that we propose here
- other thoughts: 
     - half turns are useful for high precision / exact calculations but are less user-friendly (surprising when you're coming from typical textbook context) 
     - maybe offer both rads and half_turns?
