### ISSUE TITLE
ReadTheDocs build is failing despite local builds succeeding

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2476]

**Comment by vtomole** [comment]
This is referring to the `build erroed` we've been seeing in docs?

**Comment by mpharrigan** [comment]
from the readthedocs logs it *seems* to be failing when installing contrib requirements. It fails while installing tensorflow with an out-of-memory error

**Comment by dabacon** [comment]
@dstrain did you run into this while pushing documentation for 0.8.0?

**Comment by mpharrigan** [comment]
I think this was fixed long ago. The readthedocs dashboard shows nothing but success https://readthedocs.org/projects/cirq/builds/ and the 0.8.0 docs are built and served as "stable"
