### ISSUE TITLE
Add --incremental argument to dev_tools/build_docs

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2477]
Almost everything sphinx does is determined by `docs/api.rst`. If you change that file to only mention a single class, the docs build finishes in seconds with output for that class.

1. Iterate files that are modified and end in `.py` but not `_test.py`. Further iterate their exposed values via `inspect.getmembers`. Put the member names (not qualified by package) into a set S.
2. Temporarily rename `api.rst` to `api.rename_back_to_rst`.
3. Generate `changed_api.rst` with only the entries from `api.rst` whose unqualified name is in S.
4. Build docs.

Corner cases:

- If `api.rst` itself was modified, just do a normal docs build.
- If no non-test python files were modified, don't worry about the api reference being empty from the build.

**Comment by mpharrigan** [comment]
We should also include the `sphinx-quickstart`-style `Makefile` in `docs/` for familiarity with other python/sphinx projects

**Comment by dabacon** [comment]
This is a duplicate of #2278  Closing that one as this has better details.

**Comment by mpharrigan** [comment]
Did you close this by accident?

Duplicate of #2704 as well?

My comment (about adding Makefile) has been done

**Comment by dabacon** [comment]
Oops good catch.

**Comment by balopat** [comment]
As devsite is coming, I'm going to close this.
