### ISSUE TITLE
Implement cirq.eigencomponents()

### ISSUE THREAD

**Issue by jaeyoo** [quantumlib/Cirq#2492]
Conclusion of discussion in #2481 .

**Comment by tonybruguier-google** [comment]
Sent:
https://github.com/quantumlib/Cirq/pull/3197

Happy to withdraw if misguided.

**Comment by balopat** [comment]
To clarify, an implementation of `cirq.eigen_projectors/vectors/values` would be something that is fast for `EigenGate`s (using its eigencomponents method) but it falls back to numpy's linear algebra methods in the general case.

**Comment by MichaelBroughton** [comment]
This looks like it's in now. Going to close.
