### ISSUE TITLE
TypeError: 'Moment' object is not subscriptable

### ISSUE THREAD

**Issue by jaeyoo** [quantumlib/Cirq#2493]
The following error looks weird to me.
```python
>>> a = cirq.Circuit(cirq.X(cirq.GridQubit(0,0))**sympy.Symbol('a'))
>>> a
cirq.Circuit([
    cirq.Moment(operations=[
        (cirq.X**sympy.Symbol('a')).on(cirq.GridQubit(0, 0)),
    ]),
])
>>> a[0][0].gate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'Moment' object is not subscriptable
```
Because we provide the following iterator property of Moment:
```python
>>> for moment in a:
...   for op in moment:
...     print(op.gate)
... 
X**a
```
Is it ok to add subscriptability into Moment?

**Comment by mpharrigan** [comment]
It behaves like a python `set`. There's no "order" to the operations in a moment, per se. You could also imagine having indexing work by qubit (so it behaves like a `dict`) rather than by op index

**Comment by kevinsung** [comment]
Internally Moment stores its operations as a tuple. If we only need setlike behavior then we should change it to a set.

**Comment by mpharrigan** [comment]
xref #1913

**Comment by jaeyoo** [comment]
I see then it is a set, and behaviors as intended. Thanks.
