### ISSUE TITLE
Add CZRotation?

### ISSUE THREAD

**Issue by andbe91** [quantumlib/Cirq#2502]
After the addition of `ISwapRotation` in #2488, would it make sense to also add a `CZRotation` gate which takes the controlled angle as an argument? I usually find myself working mostly with angles, for instance for varitional algorithms, so I currently have to convert to exponents when creating circuits in Cirq.

**Comment by Strilanc** [comment]
I'm worried that the matrix of this gate would be ambiguous to users. What's the matrix at pi/2?

1. A Controlled Rz, which the name reads like, would be `diag(1, 1, -i, i)`.
2. Most other R / rotation gates have the form `e^(i G t)`, implying the matrix `diag(-i, -i, -i, i)`
3. If this is strictly an angle conversion, the matrix would be `diag(1, 1, 1, i)`.

**Comment by andbe91** [comment]
I see what you mean. 3 is what I had in mind, and that is also what `cirq.CZ**0.5` yields. I think the trouble is due to what global phase one uses for the Rz gate that is controlled? For instance,
``` python
print(cirq.allclose_up_to_global_phase(cirq.unitary(cirq.Rz(np.pi).controlled(1)), cirq.unitary(cirq.CZ)))
False
print(cirq.allclose_up_to_global_phase(cirq.unitary(cirq.ZPowGate().controlled(1)), cirq.unitary(cirq.CZ)))
True
```
which was a bit confusing to me at first.

Regardless, I think that it is quite common to want a gate with `exp(i*theta/4*(ZZ-ZI-IZ)) = diag(1, 1, 1, e^(i*theta))`. Perhaps a good name and documentation can minimize any ambiguity?

**Comment by balopat** [comment]
Hi @andbe91 - with the `TwoQubitDiagonalGate` since then there is yet another way to achieve this:

```
np.testing.assert_allclose(np.diag([1,1,1,1j]), cirq.unitary(cirq.TwoQubitDiagonalGate([0,0,0, np.pi/2])))
```

An idea here could be `CPhase` (similar to the quil version) which could be a shortcut to TwoQubitDiagonalGate.
What do we think about that name?

**Comment by balopat** [comment]
Also @viathor, not sure if you want to work on this - but you are assigned.

**Comment by andbe91** [comment]
```
CPhase(theta) = cirq.TwoQubitDiagonalGate([0,0,0, theta])
```
definitely seems logical to me. I'll let others decide on naming and if it is something we want.

**Comment by balopat** [comment]
Discussed on Cirq Cynq: 

``
cirq.cphase(angle) --> cirq.CZPowGate ** f(angle)
``
