### ISSUE TITLE
final_wave_function doesn’t have the ignore_terminal_measurements argument

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2505]

**Comment by dabacon** [comment]
The one on `circuit` does, the one in `mux` does not (also now called `final_state_vector`).

**Comment by dabacon** [comment]
Actually I'm not sure the one mux should have this.  It already is a very odd thing to have something that modifies the meaning of the circut on `Circuit`.  It's another thing to have it on the simulation.

**Comment by balopat** [comment]
It already has this - closing.
