### ISSUE TITLE
Naming rotations

### ISSUE THREAD

**Issue by viathor** [quantumlib/Cirq#2508]
This issue seeks to settle the naming convention for factory functions that produce gate instances given rotation angles. I found the following factories:

```
Rx, Ry, Rz, GivensRotation, ISwapRotation, MS
```

These are clearly inconsistent. Proposals:

1. `Rx, Ry, Rz, Rgivens, Riswap, Rms`
2. `rx, ry, rz, rgivens, riswap, rms`
3. `XRotation, YRotation, ZRotation, GivensRotation, ISwapRotation, MSRotation`
4. `x_rotation, y_rotation, z_rotation, givens_rotation, iswap_rotation, ms_rotation`

I'm uneasy about conventions that lead to names like `cirq.rms` since this may be interpreted as "root mean square".

To broaden the set of examples, here are some names we may reasonably anticipate in future: 

```
Rzz, pauli_string_rotation
```

Context: [comment](https://github.com/quantumlib/Cirq/commit/5c13dea6ead7dc3721c1a84c523dd1e5d805bef0#commitcomment-35820146)

Thoughts?

**Comment by dabacon** [comment]
related #1681

**Comment by dabacon** [comment]
I think method names should follow style conventions, so `snake_case`.  When I see `cirq.Rx` I think it is a class and start looking around for the class definition.  Maybe,
5. `rx, ry, rz, givens, iswap, ms`.
I think the factory methods main benefit is being short-cuts.

**Comment by viathor** [comment]
I agree about `snake_case` (hence conventions 2 and 4).

Convention 5 is inconsistent with its use of the `r` prefix.

**Comment by dabacon** [comment]
I think calling a unitary gate a rotation is kind of redundant.  "Rotation about givens" or "Rotation about Molmer-Sorenson" seems odd to me.

**Comment by viathor** [comment]
Good point. I'm starting to like 5. One more concern with it though: `cirq.iswap` and `cirq.ISWAP` meaning slightly different things is potentially confusing and error-prone.

**Comment by viathor** [comment]
Thought about it and I think I'm willing to accept `cirq.iswap` and `cirq.ISWAP` given that they would actually enter python expressions quite differently: one as a function call like `cirq.iswap(np.pi/5)` and the other standalone or exponentiated, e.g. `cirq.ISWAP**0.5`. This use is also consistent with the naming convention which implies the former is a function and the latter is a constant.

Thoughts?

**Comment by Strilanc** [comment]
> Rx, Ry, Rz, Rgivens, Riswap, Rms

`Rms` reads like root mean square.
`Rgivens` and `Riswap` are sorta logical given the first three, but very weird on their own.
Violates python naming convention.

> rx, ry, rz, rgivens, riswap, rms

`Rms` reads like root mean square.
`Rgivens` and `Riswap` are sorta logical given the first three, but very weird on their own.
Semi-violates python naming convention in that there would normally be an underscore after the `r`.

> XRotation, YRotation, ZRotation, GivensRotation, ISwapRotation, MSRotation

The names for X/Y/Z are too long IMO. The most common gates should have short names.
`MSRotation` seems wrong; like saying `HadamardRotation`. I get what it means but it's odd.
Violates python naming convention.

> x_rotation, y_rotation, z_rotation, givens_rotation, iswap_rotation, ms_rotation

Too long x/y/z.
`ms_rotation` seems strange.

> rx, ry, rz, givens, iswap, ms.

Lacks consistency across them, but honestly I like this one the best by far. Avoiding the rotation word for two qubit operations seems to be a good idea.

**Comment by viathor** [comment]
Agreed, commented on the `iswap` vs `ISWAP` concern [above](https://github.com/quantumlib/Cirq/issues/2508#issuecomment-550596699).

**Comment by viathor** [comment]
In #2526 I have forced keyword parameter passing to differentiate `cirq.ISWAP` and `cirq.iswap`. I'm curious what y'all think about this and whether you'd like to see this convention employed consistently for all the six factory functions. Admittedly,

```python
cirq.rx(rads=np.pi/2)
```

is little longer than `cirq.rx(np.pi/2)`, but I don't find it excessively verbose. I also like explicit units since they make the code more comprehensible to new cirq users.

WDYT?

**Comment by viathor** [comment]
Oops, didn't actually intend to close this until all changes are in.

**Comment by viathor** [comment]
Also, FTR: from last meeting the convention we'll follow here is:

```
rx, ry, rz, riswap, givens, ms
```

**Comment by mpharrigan** [comment]
> Avoiding the rotation word for two qubit operations seems to be a good idea.

What about `rzz`

**Comment by mpharrigan** [comment]
> In #2526 I have forced keyword parameter passing to differentiate cirq.ISWAP and cirq.iswap

Am I taking crazy pills or did you change it to `riswap`?

**Comment by viathor** [comment]
> Am I taking crazy pills or did you change it to riswap?

No crazy pills appear to have been ingested. We've decided in the meeting `cirq.riswap` was better than `cirq.iswap` so I've updated my PR. I've also recorded the change of plans in [the comment above](https://github.com/quantumlib/Cirq/issues/2508#issuecomment-554087655).

**Comment by viathor** [comment]
> What about `rzz`

Sure, this is consistent with the convention we've settled on.

**Comment by mpharrigan** [comment]
ok
