### ISSUE TITLE
pytest prints "Segmentation fault" after succeeding

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2509]
For example, try `pytest cirq/ops/fsim_gate_test.py`:

```
======== test session starts ========
platform linux -- Python 3.7.3, pytest-3.8.2, py-1.8.0, pluggy-0.13.0
benchmark: 3.2.2 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: [...]/cirq, inifile:
plugins: benchmark-3.2.2, cov-2.5.1
collected 22 items                                                                                                        

cirq/ops/fsim_gate_test.py ......................                                                                   [100%]

======== warnings summary ===============
[... site-packages/jsonschema/compat ...]
=========== 22 passed, 2 warnings in 0.26 seconds ==========
Segmentation fault
```

I've narrowed this down to the line `import qiskit` inside of the qasm compatibility tests. I've confirmed that a python file containing nothing except `import qiskit` prints the segfault message.

Best guess: the version we are targeting has bit-rotted and we need to bump it.

**Comment by MichaelBroughton** [comment]
I just ran that on my machine and didn't get a segfault. For reference I have qiskit 0.6.1 and qiskit aer 0.3.2 installed on my venv

**Comment by Strilanc** [comment]
Those ones. Very strange.

I also wasn't able to update qiskit without blowing away my virtual environment first. Regardless, I'm not seeing the issue anymore after increasing the qiskit version to 0.13. So I'll consider this issue closed once that gets merged.
