### ISSUE TITLE
Effectively can't subclass IdentityGate

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#2517]
The `on` method always returns an operation with gate `IdentityGate` not my subclass. This has seriously messed me up and wasn't always the case

**Comment by mpharrigan** [comment]
git blame shows #1765

**Comment by mpharrigan** [comment]
update: it returns an `IdentityOperation` which obliterates the custom logic in my subclass

**Comment by Strilanc** [comment]
You can override `on`, but as noted in https://github.com/quantumlib/Cirq/issues/2520 the proper fix is likely to just delete the now-redundant `IdentityOperate`.

**Comment by dabacon** [comment]
I believe this has been fixed with the removal of `IdentityOperation`.
