### ISSUE TITLE
Proposal: remove Operation and store qubit ids in Gate

### ISSUE THREAD

**Issue by maffoo** [quantumlib/Cirq#252]
I think we should consider removing the `Operation` class and storing the qubits a `Gate` applies to directly in the gate instance. One problem with `Operation` is that we lose type information about the gate inside it, for example we made `Operation` support raising to a power for convenience, but this actually only works if the gate it contains is an extensible gate, so you might get a `TypeError` at runtime and mypy can't help. We also lose information about the roles of different qubits on a multi-qubit gate. For example, if we have `CNOT.on(q0, q1)`, which of those is the target and which the control? If the `CNOT` gate constructor itself takes qubits as arguments we could do `CNOT(control=q0, target=q1)` and any code that comes across a `CNOT` gate will be able to see these qubit roles directly.

One thing we would lose by doing this is the ability to generically "remap" operations to different qubits, for example if an optimizer needs to move gates around. But we could add an abstract method on `Gate` to do this sort of generic remapping that would construct a new instance on different qubits to enable support for this.

Another thing I discussed with @Strilanc is that if gates are _always_ applied to qubits, then there might be confusion about what the matrix for a known-matrix gate means. But I think having gates applied to qubits helps even here. If you ask a gate for its matrix, you can also ask it for the "basis" and it can give its list of qubits which (along with a tensor product convention) tells how to interpret the matrix. If you try to multiply matrices for two gates, that only makes sense if they have the same basis. Also, you could ask the qubit for its matrix in a different basis, so for example if I have `gate = CNOT(control=q2, target=q5)` I could ask for `gate.matrix(basis=[q0, q1, q2, q3, q4, q5, q6, q7])`.

One other thing I'll note is that the Gate/Operation split is not reflected in the protos; there the messages like `ExpW` contain the qubits they apply to as well as the other parameters. So unifying Gate and Operation in cirq would reduce some impedance mismatch with converting to/from protos (we might want to rename the `Operation` proto to `Gate` though).

I know this would be a large change but I think it would simplify things for users. Thoughts?

**Comment by c-poole** [comment]
@Strilanc good to close

**Comment by vtomole** [comment]
Second part is done but `Operation` still exists. 

https://github.com/quantumlib/Cirq/blob/1e6436c136dbe94a62970fa64692d27ed8f919c8/cirq/ops/raw_types.py#L231

@Strilanc Considered done?

**Comment by Strilanc** [comment]
I consider this to be closed. We need Operation (unitary with specified qubits) because it is the fundamental thing circuits use, and we need Gate (unitary with unspecified qubits) because it's such as a common concept.

**Comment by dabacon** [comment]
(nit nit operation is more than just unitary, gate is more a factory than a keeper of unitary)
