### ISSUE TITLE
should circuits using symbols suggest that the user implement flattening?

### ISSUE THREAD

**Issue by peterse** [quantumlib/Cirq#2534]
Would it make sense for a param resolver containing many sympy expressions to warn the user of potential slowdowns and point the user towards the flattening utilities? 

Looking at @dstrain115's fix in #1899 ([comment](https://github.com/quantumlib/Cirq/issues/1899#issuecomment-545200718)) a user can potentially improve the simulation time of circuits containing symbols by orders of magnitude using flattening utilities from study.flatten_expressions. I was unaware of this until recently, and I imagine general users may be puzzled by the slowdown incurred by (un-flattened) sympy parameterization.

**Comment by dabacon** [comment]
Is there a reason we shouldn't just flatten for users?  User has original parameters and circuits with formulas.  We calculate new parameters where there are no formulas.  Use that for simulation or execution.  All user cares about is associating original parameters with these results, or am I missing something?

**Comment by balopat** [comment]
Discussed at Cirq Cynque:
- there is no really a good place to warn the user about this 
- maybe we could introduce an analyze method that could tell whether the circuit would benefit from flattening or not
- autoflattening: we have to look into this if it would actually add value/benefit  -- marking as needs-feasibility

**Comment by peterse** [comment]
Yea its worth checking whether flattening makes as much of a difference after #3205
