### ISSUE TITLE
Major goal: gate set concept and device refactor

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2537]
- Need clarity around amount of verification when mutating circuits

**Comment by alexandrupaler** [comment]
@Strilanc : For the Cirq bootcamps I am using a device that has a method to check if a gate belongs to a certain supported gate set. That method is also used for a kind of automatic compilation, by calling `cirq.decompose` with the `keep` parameter.

You can see an example of the method [here](https://github.com/alexandrupaler/fondq/blob/97953e24f5d7e31e92987893acab2ce46c361d2c/fondq_device.py#L57) 

I have a repo with this solution at [https://github.com/alexandrupaler/fondq](https://github.com/alexandrupaler/fondq)

**Comment by balopat** [comment]
This made it to the roadmap: #3243

**Comment by balopat** [comment]
I'm going to actually close this, as we will tackle this as part of the gate set and device hierarchy items and there is no need to track twice.
