### ISSUE TITLE
Major goal: improve sampler interface to support batching/async

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2538]

**Comment by balopat** [comment]
Batching is added.
Async is still outstanding.

**Comment by maffoo** [comment]
Updates:
- We added `duet` as a dependency of `cirq-core` and have stubbed out async versions of `run`, `run_sweep`, and `run_batch` on `cirq.Sampler`.
- We updated the gapic generated code for the quantum engine API which includes async support with asyncio (https://github.com/quantumlib/Cirq/pull/5139).
- We have a prototype of adding async support to various `Engine*` classes (https://github.com/quantumlib/Cirq/pull/5219).

**Comment by maffoo** [comment]
There are some additional things we want to add (proper async interface to Quantum Engine, "dynamic" batching that adapts based on request size, etc), but I think the sampler interface itself is in reasonable shape, so we can probably close this and address further improvements in separate issues/PRs.
