### ISSUE TITLE
Add documentation on how to run Cirq's qasm_ouput on Q#

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2541]
Use the QASM -> Q# translator : https://github.com/Microsoft/Quantum/pull/58

**Comment by vtomole** [comment]
**Add qsharp as a contrib dependency: https://pypi.org/project/qsharp/** 
Option 1. Compile https://github.com/qsharp-community/qsharp-integrations/blob/master/src/OpenQasmReader/Parser.cs and add `Parser.exe` to `contrib`/`dev_tools`.

` mono Parser.exe Microsoft.Quantum.SanityTests tests/OpenQasmReader.Tests/TestFunctions/CNot.qasm > Cnot.qs`

```python
import qsharp

from  Microsoft.Quantum.Samples.OpenQasmReader.Tests.Validate import CNot
_ = CNot.simulate()
```
Option 2: Translate `Parser.cs` to `qsharp_qasm_parser.py` and add it to `contrib`

```python
import qsharp
cnot_qasm_to_qsharp = qasm_read.qsharp("﻿// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
creg c[2];
H q[0]; 
cx q[0],q[1];
measure q -> c;")

CNot= qsharp.compile(cnot_qasm_to_qsharp)
_ = CNot.simulate()
```

**Comment by Strilanc** [comment]
Option 3:

Add an "interop.rst" to documentation explaining how to do this.

**Comment by vtomole** [comment]
Closed by https://github.com/quantumlib/Cirq/pull/4530 that allows us to skip the translation to `qasm`.
