### ISSUE TITLE
Readthedocs is still showing docs from v0.5.0

### ISSUE THREAD

**Issue by cduck** [quantumlib/Cirq#2543]
https://cirq.readthedocs.io/en/stable/index.html

#2542 pointed out that "Qudits" is missing from the menu and readthedocs says it's displaying the docs for `e8f9323b` (the hash of the commit tagged v0.5.0).  Also the title of the page is "Cirq: A python library for NISQ circuits — Cirq **0.5.0** documentation"

@Strilanc Do you need to tell readthedocs the new `stable` version?

**Comment by vtomole** [comment]
Fix by removing TensorFlow dependency.
