### ISSUE TITLE
Test cirq.experiments in JSON round trip test

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#2544]

**Comment by KevinVillela** [comment]
FYI https://github.com/quantumlib/Cirq/pull/2559 pulls out the JSON roundtrip function into the cirq.testing package and uses it to test a class in cirq.contrib. I think you can build on that to test the classes in cirq.experiments.

**Comment by dstrain115** [comment]
There is now a comprehensive test for JSON round trip for all classes that are exposed at the top-level unless they are specifically and deliberately excluded.
