### ISSUE TITLE
built-protos Travis job failing

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#2565]
affecting #2563 and #2564 

```
java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /home/travis/.cache/bazel/_bazel_travis/a837620217d59b3397b001d4ebbcabeb/external/zlib/zlib-1.2.11.tar.gz: connect timed out
```

**Comment by Strilanc** [comment]
This is the same thing that happened the last time we had build protos as a build check. At some random point in time, a library started failing to download and all the builds broke.

I'll turn it off again, and push back against turning it on if this can't be fixed.

**Comment by Strilanc** [comment]
@zaqqwerty any idea why this is flaky again?
