### ISSUE TITLE
Density matrix simulator simulates noise incorrectly

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#2567]
The code below constructs two circuits, each with one measurement gate that should have the same measurement results. Instead, one measures 0 and the other measures 1.
```
import cirq

q = cirq.LineQubit(0)
circuit1 = cirq.Circuit(cirq.measure(q))
circuit2 = circuit1 + cirq.I(q)

print('Circuit 1:')
print(circuit1)
print()
print('Circuit2:')
print(circuit2)
print()

simulator = cirq.DensityMatrixSimulator(noise=cirq.X)
result1 = simulator.run(circuit1, repetitions=10)
result2 = simulator.run(circuit2, repetitions=10)

print('Result 1:')
print(result1)
print()
print('Result 2:')
print(result2)
print()
```
Output:
```
Circuit 1:
0: ───M───

Circuit2:
0: ───M───I───

Result 1:
0=1111111111

Result 2:
0=0000000000
```

**Comment by kevinsung** [comment]
The reason this happens is that if all measurements are terminal, the code will first simulate all noisy moments and then simulate all measurements. This is incorrect for Circuit 1 above because the moment with the measurement gets simulated (with a bit flip) before the measurement itself is simulated.

However, I think this example raises the question of whether the output of Circuit 1 is actually the correct one (putting aside the fact that in this case it resulted from incorrect behavior). It seems a bit strange to specify a bit flip noise model but have all the measurements be perfect because the noise is applied after the measurement rather than before.

**Comment by Ashalynd** [comment]
This is partially fixed by #2487 which is in the review queue.

**Comment by kevinsung** [comment]
In what way is it partially fixed? Would it change the output of my code snippet?

**Comment by Ashalynd** [comment]
Oh I see, this is a different issue. That PR added the option to not perform perfect measurements during the simulation.

**Comment by Ashalynd** [comment]
Well, I have run your code with ignore_measurement_results=True and it looks even stranger:
```
import cirq

q = cirq.LineQubit(0)
circuit1 = cirq.Circuit(cirq.measure(q))
circuit2 = circuit1 + cirq.I(q)

print('Circuit 1:')
print(circuit1)
print()
print('Circuit2:')
print(circuit2)
print()

simulator = cirq.DensityMatrixSimulator(noise=cirq.X, ignore_measurement_results=True)
result1 = simulator.run(circuit1, repetitions=10)
result2 = simulator.run(circuit2, repetitions=10)

print('Result 1:')
print(result1)
print()
print('Result 2:')
print(result2)
print()
```
```
Circuit 1:
0: ───M───

Circuit2:
0: ───M───I───

Result 1:
0=1111111111

Result 2:

```

Looks like terminal measurements have some special treatment now, which feels wrong.

**Comment by Ashalynd** [comment]
Found where it happens in density_matrix_simulator.py:

```
    def _run(self, circuit: circuits.Circuit,
             param_resolver: study.ParamResolver,
             repetitions: int) -> Dict[str, np.ndarray]:
        """See definition in `cirq.SimulatesSamples`."""
        param_resolver = param_resolver or study.ParamResolver({})
        resolved_circuit = protocols.resolve_parameters(circuit,
                                                        param_resolver)
        self._check_all_resolved(resolved_circuit)

        if circuit.are_all_measurements_terminal():
            return self._run_sweep_sample(resolved_circuit, repetitions)
        return self._run_sweep_repeat(resolved_circuit, repetitions)
```

`self.run_sweep_sample` directly calls `step_result.sample_measurement_ops` and `self.run_sweep_repeat` does more nuanced things (including dephasing).

Not yet sure what is the best way to fix this.

**Comment by Strilanc** [comment]
I think the correct fix for this issue is to modify the "simulate then sample" optimization to discard all operations that come after measurements. The optimization could also be extended to apply to any circuit where all measurements are outside of each other's "light cone" if we wanted to be ambitious.

**Comment by kevinsung** [comment]
@Strilanc what you propose would not fix this issue. In my opening post, the incorrect behavior arises in simulating Circuit 1, which does not have any operations after measurements.

One possible way to fix this is: when all measurements are terminal, simulate the noisy circuit _ignoring_ the measurements. Then perform the measurements.

**Comment by kevinsung** [comment]
Actually, what you said makes sense; we just need to discard the operations _after_ applying the noise model.

**Comment by kevinsung** [comment]
@Ashalynd the issue you raised has to do with the `ignore_measurement_results` flag, and not the `noise` argument. I think main issue there is that when `ignore_measurement_results` is set to True, then `simulator.run` should not return any measurement results. I opened #2777 for this issue.
