### ISSUE TITLE
Should ConstantQubitNoiseModel apply noise first rather than second?

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#2570]
https://github.com/quantumlib/Cirq/blob/e90430598d43bf124844c41c08663c9bafd5f9b7/cirq/devices/noise_model.py#L204-L209

As you can see, the original moment gets applied, then the noisy moment. This means that the measurement results of measurement gates are not affected by the noise, which may be surprising. For instance, a circuit consisting only of measurements will be sampled as if it is noiseless.

**Comment by dabacon** [comment]
Yeah generally this is probably not what is desired. I would suggest that we start by adding the ability to toggle between before and after and add deprecation warning about the default for this being switched.

**Comment by mpharrigan** [comment]
Also see in cirq.contrib.noise_models how measurement is special-cased

**Comment by 95-martin-orion** [comment]
@dkafri Which of these (noise before or after the affected gate) is more consistent with the error-to-noise pipeline? I think it's feasible to make this change, but if noise-after-gate is a better match for what we measure from hardware then it's not worth the switch.

**Comment by dabacon** [comment]
In general when I've had to do simulations for error corrections, I need both before and after.  After for after preparation steps, before for gates and measurements.  I think if we have to chose one, before is better, but just wanted to point out that this makes the preparation errors hard to use.

**Comment by dkafri** [comment]
Dave makes a good point. What I've done in the past is just specify a flag for whether to prepend vs append errors.

**Comment by tanujkhattar** [comment]
From cirq sync:

Defaulting to before will cause a breaking change. Let's provide an optional parameter to users to prepend instead of append. 

From hardware team's perspective, it before/after shouldn't matter much.
