### ISSUE TITLE
Simulators should expand their concept of "terminal measurements"

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#2577]
Currently terminal measurements mean there are no gates after measurements. However, the measurement in the circuit
```
0: ───M───I───
```
is still "terminal" in the sense that it can be sampled repeatedly from the same state rather than executing the circuit once for each repetition.

**Comment by balopat** [comment]
Interesting! Where did this come up? Can you explain the use case?
Also, how far do you think this should go? Check for each measurement that the ops after it are equivalent to identity? Or just identity is sufficient?

**Comment by kevinsung** [comment]
Using the identity gate was a bad example. What matters is that the state evolution leading up to the measurement is deterministic, so that the circuit leading up to the measurement only needs to be simulated once. Any gates occurring after the measurement have no effect on the measurement.

I think I was inspired to open this after observing the bug #2567 . It's an extension of an idea underlying the fix for that bug. Actually this is a less ambitious version of a suggestion made in a comment on that bug, https://github.com/quantumlib/Cirq/issues/2567#issuecomment-582689783:
> I think the correct fix for this issue is to modify the "simulate then sample" optimization to discard all operations that come after measurements. The optimization could also be extended to apply to any circuit where all measurements are outside of each other's "light cone" if we wanted to be ambitious.

**Comment by balopat** [comment]
Discussed on Cirq Cynque: it is a bit unclear in what cases this would help. Caching the statevector before the first measurements would be one way to implement this. Marking it as needs-more-evidence for now. If someone feels strongly about this please comment / reopen after this gets closed.
