### ISSUE TITLE
What is the point of TrialResult.from_single_parameter_set?

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#2582]
https://github.com/quantumlib/Cirq/blob/f14ed20545338f404516c55fd150daa8cbfd292f/cirq/study/trial_result.py#L118-L133

All it does is forward to the default constructor.

**Comment by vtomole** [comment]
Ping @Strilanc

**Comment by dabacon** [comment]
I don't see a use.  We should deprecate and then delete.

**Comment by balopat** [comment]
Agreed with the deprecation - I know that it is used in TFQ - not sure why - so we should definitely be careful deprecating it.

**Comment by zaqqwerty** [comment]
Wanted to mention that we removed this stray use from TFQ in the PR [here](https://github.com/tensorflow/quantum/pull/400)

**Comment by balopat** [comment]
Thanks for the info @zaqqwerty!
