### ISSUE TITLE
Add DiagonalTwoQubitGate

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2587]
```python
def CZPowGate00(g):
      return np.array([[g, 0, 0, 0],
         [0, 1, 0, 0],
         [0, 0, 1, 0],
         [0, 0, 0, 1]])
``` 
e.t.c

These pyquil built-in gates: https://github.com/rigetti/pyquil/blob/2f7e4b4dd5edcb99da1f5e7d8f4459ba11e81af3/pyquil/gates.py#L298 are needed to be compatible with QUIL. See:  https://github.com/quantumlib/Cirq/issues/2386

**Comment by balopat** [comment]
Resolved in #3211
