### ISSUE TITLE
Default names can fail on Engine

### ISSUE THREAD

**Issue by wcourtney** [quantumlib/Cirq#2590]
When no program name is provided, we create a random one because names must be unique: https://github.com/quantumlib/Cirq/blob/1c5084a8d87ad0c93fb1932362a827540262224e/cirq/google/engine/engine.py#L462

If the name already exists, the creation request will fail with a 209 ALREADY_EXISTS error. For these default names, we should probably recover by choosing a new one and trying again.

**Comment by Strilanc** [comment]
It would be acceptable to increase the length from 6 to 16 and append the current date as six digits. You'd need on the order of a trillion jobs in a day to have any reasonable chance of a collision.
