### ISSUE TITLE
Examples: Add end-2-end example for Sampling Random Circuits (Quantum Supremacy)

### ISSUE THREAD

**Issue by karlunho** [quantumlib/Cirq#2596]
We should have an end-2-end example for sampling random circuits. Ideal example will have the following requirements:

1. Show creation of random circuit for both "easy" and "hard" random circuit defined in the supremacy paper
2. Show creation of random circuit for patch, elided, and full random circuits defined in the supremacy paper
3. Usage of Sycamore device and Sycamore Gates
4. Show that one can call a noisy quantum simulator to represent the actual quantum computer. We should also have some placeholder code that showing calling of the actual quantum computer.
5. Showing that we can calculate fidelity of Random Circuit using Cirq's circuit simulator.
6. Showing that we can use qFlex to perform "noisy sampling" of the quantum circuit on a classical device.

**Comment by dstrain115** [comment]
I don't think anyone is clamoring for this anymore, and, if so, they should add it to the existing implementation in ReCirq:
https://github.com/quantumlib/ReCirq/tree/master/recirq/beyond_classical
