### ISSUE TITLE
Add binary literal example to compute_amplitudes_sweep and compute_amplitudes methods of SimulatesAmplitudes class.

### ISSUE THREAD

**Issue by iamvamsikrishnad** [quantumlib/Cirq#2603]
The signature of compute_amplitudes_sweep and compute_amplitudes requires bitstrings to be a list of int's. Because of the semantics in python3 of not allowing leading zeros for int's (https://stackoverflow.com/questions/36386346/syntaxerror-invalid-token) this can be confusing.

For eg: if I want to measure a bitstring 0010, I need to provide 10 as input to the bitstring which is confusing to the user.

I propose to change the type of bitstrings to Sequence[str].

**Comment by dabacon** [comment]
I think the way to do this in python is to use the binary prefix: `0b0010` or `0B0010`.  I'm going to change this to adding binary as example usage.

**Comment by viathor** [comment]
> For eg: if I want to measure a bitstring 0010, I need to provide 10 as input to the bitstring which is confusing to the user.

Not at all. To measure bitstring 0010, you need to provide 2 as input which you may choose to write as 0b0010 or 0b10 or 0x2 or 2 or even 0o2 (no longer fashionable).
