### ISSUE TITLE
cirq.contrib.qasm_import.qasm.QasmParser(): Add support for u1(lambda) gate

### ISSUE THREAD

**Issue by ccalaza** [quantumlib/Cirq#2607]
I was testing the compatibility between Cirq-0.7.0.dev and QASM by running the following code: 

```
import cirq
from cirq.contrib import qasm_import

qasm =  """
        OPENQASM 2.0;
        include "qelib1.inc";

        qreg q[5];
        creg c[5];
        
        // SUPPORTED GATES:        
        u2(0, pi/2) q[1];
        u3(pi, pi/2, 0) q[2];
        
        h q[0];
        x q[1];
        y q[2];
        z q[3];
        id q[4];
        
        s q[0];
        sdg q[1];
        t q[2];
        tdg q[3];
        
        rx(0.5) q[0];
        ry(0.25) q[1];
        rz(pi) q[2];
        
        cx q[0], q[1];
        cy q[2], q[3];
        cz q[0], q[1];
        ch q[2], q[3];
        
        ccx q[0], q[1], q[2];
        swap q[0], q[1];
        cswap q[0], q[1], q[2];
        
        measure q[1] -> c[4];
        measure q[0] -> c[0];
        
        // UNSUPPORTED GATES:        
        //u1(pi/2) q[0];
        //barrier q;
        //reset q[0];
        
        //crz(pi) q[0], q[1];
        //cu1(pi) q[0], q[1];
        //cu3(0, pi, pi/2) q[0], q[1];
        """

circ = cirq.Circuit(qasm_import.circuit_from_qasm(qasm))
circ
```
when I noticed that some of the gates are not yet supported (i.e. all the gates below the "UNSUPPORTED GATES" comment). I was not surprised to see that barrier, reset or these weird control gates do not work, but u1 is one of the 5 basis gates in QASM and Cirq does not seem to recognize it yet. Is this a bug or is there any reason behind this?

**Comment by vtomole** [comment]
@ccalaza  `u1` is not added, but you can use `rz` as a replacement.

**Comment by ccalaza** [comment]
I can also use u2 or u3, as u1 is a specific version of these more general gates. There is definitely several ways to work around this. 

I just opened the issue because it will confuse people who are not aware of this down the line, and it seems that QasmUGate class can very easily deal with this gate:
cirq.circuits.qasm_output.QasmUGate(0, 0, lmda) == u1(lmda) == rz(lmda)

**Comment by vtomole** [comment]
Thanks for raising this issue: I've opened up a pull request that addresses it: https://github.com/quantumlib/Cirq/pull/2608
