### ISSUE TITLE
MemoryError: Unable to allocate array with shape (562949953421312,) and data type complex64

### ISSUE THREAD

**Issue by chlorophyll-zz** [quantumlib/Cirq#2614]
Running this Simulation in Colab Notebook with 49 Qubits
https://colab.research.google.com/drive/1bOg47bXV9lmUQqnJDn7jAbKvn5kOeBXN#scrollTo=x-0EyYgnh4Wg
`

Error:

> MemoryError                               Traceback (most recent call last)
> <ipython-input-15-c3efcef97d94> in <module>()
>     107 circuit.append(one_step(h, jr, jc, 0.1, 0.2, 0.3))
>     108 circuit.append(cirq.measure(*qubits, key='x'))
> --> 109 results = simulator.run(circuit, repetitions=1)
>     110 print(results.histogram(key='x'))
>     111 
> 
> 6 frames
> /usr/local/lib/python3.6/dist-packages/cirq/linalg/states.py in one_hot(index, shape, value, dtype)
>      38     if index is None:
>      39         index = 0 if isinstance(shape, int) else (0,) * len(shape)
> ---> 40     result = np.zeros(shape=shape, dtype=dtype)
>      41     result[index] = value
>      42     return result
> 
> MemoryError: Unable to allocate array with shape (562949953421312,) and data type complex64

The same Simulation runs without this error for 36 Qubits

**Comment by ccalaza** [comment]
You are trying to allocate memory worth (562949953421312 * 64) bit = 36028797018963970 bit =~ 4.5 Petabyte, whereas my guess is that 36 qubits would require approx 550 Gigabyte (still a lot but within reasonable limits for a big machine).

**Comment by chlorophyll-zz** [comment]
@ccalaza yes, for the 36 Qubits, the Machine Crashes with OOM, but without this specific error.
