### ISSUE TITLE
Make cirq.GridQubit + cirq.GridQubit work

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2637]
```cirq.GridQubit(a, b) + (c, d)``` works

```cirq.GridQubit(a, b) + cirq.GridQubit(c, d)``` does not work

The latter should act like the former.

**Comment by maffoo** [comment]
Not sure how I feel about this. It seems odd to use GridQubit as a "delta" on another grid qubit.

**Comment by Strilanc** [comment]
The use case I ran into was defining a layout in grid qubits, and then passing in the center. It made sense for the function call to expose the center as a grid qubit, and for the internals to be defined on grid qubits, and then the offset operation is natural.
