### ISSUE TITLE
Add a simulator in the style of the paper `Classical algorithms for quantum mean values`

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2638]
Calculating mean values is very NISQY. VQE, QAOA e.t.c: https://arxiv.org/abs/1909.11485

**Comment by crystalzhaizhai** [comment]
Could you please assign it to me?

**Comment by kevinsung** [comment]
These are classical algorithms; why do they belong in Cirq?

**Comment by vtomole** [comment]
These are classical algorithms in the sense that CHP (https://www.scottaaronson.com/chp/) is a classical algorithm that simulates certain types of quantum circuits efficiently on a classical computer. It's in the same vein as the [clifford](https://github.com/quantumlib/Cirq/tree/master/cirq/sim/clifford) simulator. These algorithms calculate: Given a short depth circuit `U` and an observable  `O`, calculate `<0|U^+OU|0>`. Some structures of this observable can be calculated efficiently with these algorithms (Positive semi definite, close to I, hermitian).
