### ISSUE TITLE
Implement `__add__` for cirq.Moment

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2641]
I'd like to be able to write `circuit[index] += cirq.X(qubit)` to append an operation into a moment inside a circuit. This requires defining an `__add__` operation for moment.

Note that moments are immutable, so do not implement `__iadd__`; just `__add__`.

**Comment by fedimser** [comment]
Hi. I would like to work on it.

**Comment by vtomole** [comment]
Closed by https://github.com/quantumlib/Cirq/pull/2665
