### ISSUE TITLE
Discussion: Add `barrier`?

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2642]
The `barrier` directive will tell optimizers which instructions not to touch. Something like

```python
circuit = cirq.Circuit(
    cirq.H(qubit1)
    cirq.barrier_start(qubit0)
    cirq.X(qubit0)**0.5, 
    cirq.barrier_start(qubit0)
    cirq.measure(qubit0, key='m')  
)

cirq.optimize_circuit(circuit)
```
What are your opinions on this? @mpharrigan @cduck @viathor @maffoo @Strilanc @dstrain115 @kevinsung

**Comment by vtomole** [comment]
I don't know if this already exists.

**Comment by dstrain115** [comment]
My alternative idea is to be able to tag operations with a Tag.  One possible tag would be a DoNotTouch tag for optimizers to leave it alone, but the concept would be general enough that you could tag operations like ColorBlue to show up in a different color on a diagram or something like that.

I have a design doc for this coming soon.

What do you think?

**Comment by vtomole** [comment]
That is better. Tagging https://github.com/quantumlib/Cirq/issues/1940.
