### ISSUE TITLE
Cirq tests appear to be failing

### ISSUE THREAD

**Issue by KevinVillela** [quantumlib/Cirq#2646]
I have two PRs that are completely unrelated: https://github.com/quantumlib/Cirq/pull/2645 and https://github.com/quantumlib/Cirq/pull/2629. They both cause the same (unrelated to the PRs) tests to fail: https://travis-ci.com/quantumlib/Cirq/jobs/267385668. Running the following on my machine passes in either of these PRs passes:
$ pip install --upgrade pip setuptools wheel
$ python -m venv venv
$ source venv/bin/activate
$ python -m pip install -r requirements.txt
$ python -m pip install -r cirq/contrib/contrib-requirements.txt
$ python -m pip install -r dev_tools/conf/pip-list-dev-tools.txt
$ ./check/all

**Comment by maffoo** [comment]
Looks like all the failures are related to sympy.  A new version 1.5 was just released: https://github.com/sympy/sympy/releases/tag/sympy-1.5, so we might need to pin the sympy version in requirements.txt until we can fix compatibility issues.

**Comment by Strilanc** [comment]
It's because Rational is now considered to be a number, causing it to loss precision when being serialized.
