### ISSUE TITLE
CNOT gate issue with IonDevice and **

### ISSUE THREAD

**Issue by DenisKatic** [quantumlib/Cirq#2662]
Example:

        device, qubits = get_aqt_device(2)
        circuit = cirq.Circuit(device=device)
        circuit.append([
            cirq.Ry(rads=0.1).on(qubits[0]),
            cirq.CNOT(qubits[0], qubits[1]) **0.5
        ])

Error:
ValueError: ('Got unknown gate:', cirq.PhasedXPowGate(phase_exponent=1.0, exponent=0.6183667022230277).on(cirq.LineQubit(1)))

**Comment by vtomole** [comment]
Ping @pschindler

**Comment by DenisKatic** [comment]
Thanks

**Comment by vtomole** [comment]
@DenisKatic 

```python
import cirq

from cirq.aqt.aqt_device import get_aqt_device

device, qubits = get_aqt_device(2)
circuit = cirq.Circuit(device=device)
circuit.append([
        cirq.Ry(rads=0.1).on(qubits[0]),
        cirq.CNOT(qubits[0], qubits[1]) **0.5
    ])
```

Works on my machine.

**Comment by DenisKatic** [comment]
@vtomole 
Thanks for your reply
I tried to understand why you didn't get the issue:

If I use the cirq.Simulator it works, but if I try to use AQTSimulator, AQTSampler or AQTSamplerLocalSimulator instead, it returns the "unknown gate" issue.

I was talking with AQT and they confirmed the issue and replied:
We confirm your error. We checked with an XX gate rather than CNOT and it does the right thing. It could be that the sqrt is not well described (think about the +- you could put in front of the gate, and the square of it would still give you a CNOT), which is why it doesn't work that way.

Maybe this helps and thanks for your effort

**Comment by dabacon** [comment]
It appears to me that the PhasedXPowGate was not supported until #2801 .  I believe this is fixed (don't get error).  Please reopen if this is currently still not working and you are on Cirq 0.8.
