### ISSUE TITLE
cirq.PauliSumCollector() shows error if it is called in a thread.

### ISSUE THREAD

**Issue by jaeyoo** [quantumlib/Cirq#2664]
By default policy of asyncio, it creates its event loop only if it is called by the main thread. When this `cirq.PauliSumCollector()` is called by another thread, it doesnt create its event loop and raises `RuntimeError`. 

So I suggest adding new event loop explicitly inside `Collector` ([here](https://github.com/quantumlib/Cirq/blob/55c159071fbea7baf81c40dbfa9c619f4ee2a843/cirq/work/collector.py#L135-L138))
```python
asyncio.set_event_loop(asyncio.new_event_loop())
```

**Comment by balopat** [comment]
From what I'm gathering this is the calling threads' responsibility to bind an event_loop. Cirq is a library - I don't think it should create new event loops. How are you calling `cirq.PauliSumCollector`?
