### ISSUE TITLE
API reference for cirq.Sweepable gives description of Union

### ISSUE THREAD

**Issue by dkafri** [quantumlib/Cirq#2669]
[Reference](https://cirq.readthedocs.io/en/stable/generated/cirq.Sweepable.html#cirq.Sweepable)
I.e., it describes how to use Union from the typing library.
Is this the intended documentation?

**Comment by vtomole** [comment]
It's not.  Might be a bug in `def document`.

**Comment by vtomole** [comment]
@dkafri This has been fixed.
