### ISSUE TITLE
Permutation Gate

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#2671]
That permutes qubits. There's `cirq.interop.QuirkQubitPermutationGate` which does what I want but a) it's not part of the main set of cirq ops and b) it requires an "identifier" and "name" which are superfluous

**Comment by bryano** [comment]
There's also `cirq.contrib.acquaintance.LinearPermutationGate`.

**Comment by balopat** [comment]
It seemed easy enough to pull it out from quirk - raised #3298. Let me know if this meets your needs @mpharrigan. 
Regarding the acquaintance - I don't understand yet why we need a SWAP gate in the constructor - but it feels like that with a bit of work we could make maybe this lightweight `QubitPermutationGate` the parent of the acquaintenance hierarchy? @bryano?

**Comment by bryano** [comment]
The `swap_gate` attribute is so that the gates can be used in the fermionic context (i.e. with `swap_gate=ofc.FSWAP`).
