### ISSUE TITLE
Update version release docs

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2690]
The cirq package documentation is out of date w.r.t. the tooling. In particular, the dev docs talk about using package creation scripts in a way that doesn't make sense since cirq-untsable was introduced.

development.md is not under dev section of docs

mention that first verify will likely fail

type "take not of this value"

Initial draft below

0. Prepare

    a) Make sure you're on an up to date master branch and in cirq's root directory.

    ```bash
    git checkout master
    git pull origin master  # or upstream master
    git status  # should be no pending changes
    ```    

    b) Ensure you have pypi and test pypi accounts with access to cirq distribution

    visit test.pypi.org
    your environment should contain TEST_PYPI_USERNAME etc

    c) What version are you releasing?

    ```bash
    VER=VERSION_YOU_WANT_TO_RELEASE  # e.g. "0.7.0"
    NEXT_VER=NEX_VERSION  # e.g. "0.8.0"
    ```

1. Create a release branch called "v${VERSION}-dev".

    ```bash
    git checkout master -b "v${VER}-dev"
    sed magic _version.py

    git add _version.py 
    git commit -m "bla bla"
    git push origin "v${VER}-dev"
    ```

2. Bump the development version on master. master branch should never see a non-dev version specifier.

    ```bash
    git checkout master -b "version_bump_${NEXT_VER}"
    sed magic _version.py .dev
    git add _version.py
    git commit -m "bla bla"
    git push origin "version_bump_${NEXT_VER}"
    ```

3. Create a binary distribution wheel. This is the package that will go to pypi.

    ```bash
    python3 setup.py -q bdist_wheel
        ls dist  # should only contain ONE file
    ```

4. Upload the package to test pypi and verify that it works.

    a) Upload

    ```bash
    twine upload --repository-url=https://test.pypi.org/legacy/ -u="$TEST_TWINE_USERNAME" -p="$TEST_TWINE_PASSWORD" "dist/*"
    ```

    b) Automated verification

    ```bash
    # NOTE: FIRST RUN WILL LIKELY FAIL
    ./dev_tools/packaging/verify-published-package.sh --test "${VER}"
    ```

    c) Manual verification

    ```bash
    mkvirtualenv tmp --python=/usr/bin/python3
    pip install -r requirement.txt -r cirq/contrib/contrib-requirements.txt -r dev requirements
    pip install --index-url=https://test.pypi.org/simple/ cirq=="${VER}"
    python -c "import cirq; print(cirq.__version__)"
    python  # just do some stuff checking that latest features are present
    ```

5. Draft a GitHub release and a release announcement email.

    a) Summarize changes since last release.
    b) Include the binary wheel as an attachment to the github release.

6. Release the prod and verify.

     a) Upload

    ```bash
    twine upload --username="$PROD_TWINE_USERNAME" --password="$PROD_TWINE_PASSWORD" "dist/*"
    ```

    b) Automated verification

    ```bash
    # NOTE: FIRST RUN WILL LIKELY FAIL
    ./dev_tools/packaging/verify-published-package.sh --prod "${VER}"
    ```

    c) Manual verification

    ```bash
    mkvirtualenv "verify_${VER}"
    pip install cirq
    python -c "import cirq; print(cirq.__version__)"
    ```

7. Publish the github release and send the announcement email to cirq-notify

**Comment by dstrain115** [comment]
Random addendums before I forget:
6b should be "./dev_tools/packaging/verify-published-package.sh "${VER}" --prod"
6c should include python version
7 should email to cirq-announce@

**Comment by dstrain115** [comment]
As Adam points out, the version name must be of the form v0.7.0 or else various regexes will fail.

**Comment by dstrain115** [comment]
I have updated release docs.  See #3136 for the latest improvements that Balint discovered when running through the procedure.
