### ISSUE TITLE
Remove deprecated functions with v0.7 deadline

### ISSUE THREAD

**Issue by cduck** [quantumlib/Cirq#2691]
From a quick search, I found 3 deprecated functions (all the old commutes_with functions) that are planned to be removed by (before?) version 0.7.0.  Now that v0.7.0 is out, these can be removed.

- https://github.com/quantumlib/Cirq/blob/ed6188b05ac8121a6ed33af7f98d32b8b80be093/cirq/ops/pauli_gates.py#L58
- https://github.com/quantumlib/Cirq/blob/ed6188b05ac8121a6ed33af7f98d32b8b80be093/cirq/ops/clifford_gate.py#L235
- https://github.com/quantumlib/Cirq/blob/ed6188b05ac8121a6ed33af7f98d32b8b80be093/cirq/ops/pauli_string.py#L563

**Comment by crystalzhaizhai** [comment]
Could you please assign it to me?

**Comment by vtomole** [comment]
Closed by https://github.com/quantumlib/Cirq/pull/2707
