### ISSUE TITLE
Expand SWEEP_LIKE to work for {'t': [0, 1, 3]}

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2698]
Currently if you make a call like `sampler.sample(circuit, params={'t': range(5)})` it doesn't work, because it expects e.g. a list of dictionaries instead of a dictionary containing lists. For convenience we should just support both cases. Check if the input is a dictionary with list values (and possibly singletons too), and if so take the cartesian product of the various entries and turn it into a sweep.

Test cases:

```
assert cirq.to_sweeps({'t': [0, 2, 3]}) == (
    cirq.to_sweeps([{'t': 0}, {'t': 2}, {'t': 3}]}))

assert cirq.to_sweeps({'t': [0, 1], 's': [2, 3], 'r': 4}) == (
    cirq.to_sweeps([
        {'t': 0, 's': 2, 'r': 4},
        {'t': 0, 's': 3, 'r': 4},
        {'t': 1, 's': 2, 'r': 4},
        {'t': 1, 's': 3, 'r': 4},
    ]))
```

**Comment by crystalzhaizhai** [comment]
Could you please assign it to me?

**Comment by kevinsung** [comment]
The following code still doesn't work:
```python
import cirq
import sympy

a = cirq.LineQubit(0)
circuit = cirq.Circuit(cirq.X(a)**sympy.Symbol('t'),
                        cirq.measure(a, key='m'))
params = {'t': [0.3, 0.5]}
sim = cirq.Simulator()
result = sim.run_sweep(circuit, params=params)
```

**Comment by maffoo** [comment]
I think we decided not to do this so that you can resolve list-valued parameters (we have use cases for this internally). Also, there's an ambiguity if you have multiple parameters; given `{'a': [1, 2], 'b': [3, 4]}` should that do a cartesian product sweep over `a` and `b` or a zip sweep? Instead you need to make the sweep explicit at the top level, either as `[{'t': 0.3}, {'t': 0.5}]` or using actual sweep objects: `cirq.Points('t', [0.3, 0.5])`.

**Comment by kevinsung** [comment]
If that's the case, then we need to roll back https://github.com/quantumlib/Cirq/pull/2786. That PR already partially implemented this feature, using the Cartesian product definition.

**Comment by balopat** [comment]
Cirq Cynq: 

Verdict: we'll keep the dict shorthand but with explicit methods
Two new methods  

```
dict_to_zip_sweep()
dict_to_product_sweep()
```

And then the "inconsistency" will be resolved via removing this functionality from `to_sweeps`. 
Deprecation logic: 

- https://github.com/quantumlib/Cirq/blob/master/cirq/study/sweepable.py#L58 should warn about deprecation
- should call into `dict_to_product_sweep()`

**Comment by crystalzhaizhai** [comment]
I just caught up with the thread this morning. When I first implemented it, not familiar enough with types, I wasn't aware that the tests should logically extend to the use case of to_resolver method. It's great someone brought it up.

For the benefits of our future new contributors, how do we enforce consistency of functionally parallel methods?

**Comment by balopat** [comment]
I just found https://github.com/quantumlib/Cirq/issues/3018 which is exactly the deprecation issue for this.

**Comment by kevinsung** [comment]
@crystalzhaizhai That's a difficult problem in general. You definitely implemented the feature satisfactorily as it was requested. The inconsistent behavior actually results from how we already inconsistently use `to_sweeps` versus `to_resovlers` so it definitely wasn't your fault.

**Comment by crystalzhaizhai** [comment]
@kevinsung It's great you pointed out the bug. Motivated me to think about the problem in general context. If I recalled correctly, you had a related pull request. Do you still plan to work on this? If so, I will change the assignee to you. If not, I can continue to fix it.

**Comment by kevinsung** [comment]
@crystalzhaizhai I have opened #3333 to fix this and would appreciate your review.
