### ISSUE TITLE
Docs generation is very slow

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#2704]
It takes ~minutes to build the docs from scratch. It really seems to get bogged down reading and writing the autodoc `generated/` files. However, other projects seem to get away with using autodoc and at least as many functions that need documenting without these long build times. I'm worried there's a lot of custom processing hacked into `conf.py` that could be slowing things down

**Comment by mpharrigan** [comment]
Confirming my suspicions; blanking out the contents of `api.rst` makes everything go nice and quick

**Comment by balopat** [comment]
1) While it's not a perfect solution, I added the `fast` flag to `dev_tools/docs/build_rtd_docs.sh` - this speeds up the build using parallelization. 
2) in ~2 months we'll be retiring sphinx 

I will close this issue if that's okay, please reopen if you don't agree.
