### ISSUE TITLE
Add `sample_measurement_ops()` to `SimulationTrialResult`

### ISSUE THREAD

**Issue by verult** [quantumlib/Cirq#2705]
Currently only `StepResult` implements `sample_measurement_ops()`, which is only available to simulators that computes intermediate steps.

https://github.com/quantumlib/Cirq/blob/bc858fc9523b34a6cf02cd5c58d58382ea31ec27/cirq/sim/simulator.py#L439

It (and also the associated abstract method `sample()`) should also be added to `SimulationTrialResult` to make it easy for simulators that only provide a final state (implements `SimulateFinalState`) to sample from it.

I'm happy to take a stab at it!

@Strilanc @viathor

**Comment by dstrain115** [comment]
Cirq cync: @95-martin-orion will look at this and decide on whether a convenience method is needed.

**Comment by verult** [comment]
Use case no longer exists, closing
