### ISSUE TITLE
Remove support for np.exp

### ISSUE THREAD

**Issue by jaeyoo** [quantumlib/Cirq#2710]
I am really confused of this exponentiation that I expected as exp(-1j X).
```python
>>> np.exp(-1j*cirq.X(q))      
cirq.rx(np.pi*0.3183098861837907).on(cirq.GridQubit(0, 0))
```
In fact, the definition of cirq.rx(r) is cirq.XPowGate(exponent=r/np.pi, global_shift=-0.5).
Because cirq.XPowGate(exponent=t) is
        [[g·c, -i·g·s],
         [-i·g·s, g·c]]   = g ( I c - i X s)
    where:
        c = cos(π·t/2) = cos(r/2) 
        s = sin(π·t/2) = sin(r/2)
        g = exp(i·π·t/2) = exp(i r/2) 
since the global_shift = -0.5, exp(i * pi * global_shift * exponent) = exp(i * pi * -0.5 * r/pi) = exp(-i0.5r) = g' = 1/g, so the final equation is g'g ( I c - i X s) = I cos(r/2) - i X sin(r/2)

However, when I remember the Euler formula like identity equation, exp(-1j r X) = I cos(r) - i X sin(r). Could you help me?

**Comment by jaeyoo** [comment]
In details, the following equations seem to miss coefficient factor 2.
```python
>>> cirq.unitary(np.exp(-1j*np.pi*cirq.X(q))) # -iX
array([[0.+0.j, 0.-1.j],
       [0.-1.j, 0.+0.j]])
>>> cirq.unitary(np.exp(-1j*np.pi*cirq.Y(q))) # -iY
array([[ 0.+0.j, -1.+0.j],
       [ 1.+0.j,  0.+0.j]])
>>> cirq.unitary(np.exp(-1j*np.pi*cirq.Z(q))) # -iZ
array([[0.-1.j, 0.+0.j],
       [0.+0.j, 0.+1.j]])
```
They all should be `np.pi/2`, not `np.pi`

**Comment by kevinsung** [comment]
Indeed, there is a factor of 2 missing in the line
https://github.com/quantumlib/Cirq/blob/0882abb751005191f12d9bae410c9851ea705041/cirq/ops/pauli_string.py#L613
I'd like to note however that though this functionality seems convenient, it changes the meaning of `np.exp` from its normal meaning, which is _element-wise_ exponentiation. Thus there is a case to be made to not have this functionality at all. But if we are to keep it then `half_turns` should be multiplied by 2.

**Comment by kevinsung** [comment]
At Cirq sync we decided to drop this functionality (support for `np.exp`).

**Comment by jaeyoo** [comment]
Thank you for the clarification :)

**Comment by kevinsung** [comment]
This issue should remain open until we remove the functionality.

**Comment by dabacon** [comment]
Is there an issue to where dropping np.exp is discussed?

**Comment by kevinsung** [comment]
No, we discussed it during Cirq sync. The reason we decided to drop it is that `np.exp` means element-wise exponentiation, which is not what we implemented.

**Comment by dabacon** [comment]
Making this the bug to track removing support for np.exp since it is elementwise exponentiation.  #2741 is issue to define `cirq.exp`.

**Comment by kevinsung** [comment]
We should probably do this in two steps:
1. Fix the actual bug
2. Drop the functionality

**Comment by dabacon** [comment]
There is no longer any `exp` methods on gates in Cirq, so this is now fixed as far as I can tell.
