### ISSUE TITLE
Add tooling that tests Jupyter notebooks.

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2711]
We tried doing it here: https://github.com/quantumlib/Cirq/pull/1934, but it's clear that this should be a separate issue on it's own.

There are two options i can think of right now:
- Test the same way we do our `.md` (snippet tests)
- Bake tests into the notebooks: https://github.com/akaihola/ipython_pytest for example

**Comment by mpharrigan** [comment]
I've had some success by putting this in a file called `notebooks_test.py`

```python
import nbformat
from nbconvert.preprocessors import ExecutePreprocessor
import os

NOTEBOOKS_DIR = os.path.dirname(os.path.abspath(__file__))


def run_notebook(name):
    # https://nbconvert.readthedocs.io/en/latest/execute_api.html
    with open(f'{NOTEBOOKS_DIR}/{name}.ipynb') as f:
        nb = nbformat.read(f, as_version=4)
    ep = ExecutePreprocessor(timeout=60, kernel_name='python3')
    ep.preprocess(nb, {'metadata': {'path': NOTEBOOKS_DIR}})


def test_name_of_notebook():
    run_notebook('Name-Of-Notebook')
```

**Comment by vtomole** [comment]
Ping @bt3gl

**Comment by vtomole** [comment]
This is becoming very important as the number of notebooks is increasing.

**Comment by bt3gl** [comment]
@vtomole I just saw this, I can work on it this weekend/next week. If this is ok, could you please assign it to me?

**Comment by vtomole** [comment]
@bt3gl Thanks for doing this. Don't forget https://github.com/quantumlib/Cirq/pull/2713#issuecomment-583175086 too.

**Comment by balopat** [comment]
Given the crazy amount of notebooks coming and going now with QPolish, this is a must. I raised a PR for a version that runs the pip installs in isolated envs.
