### ISSUE TITLE
cirq.Simulator.compute_amplitudes not well documented

### ISSUE THREAD

**Issue by karlunho** [quantumlib/Cirq#2730]
We should add some documentation on how to use cirq.Simulator.compute_amplitudes . There is no documentation in https://cirq.readthedocs.io/en/stable/generated/cirq.Simulator.html , or in the simulator tutorial https://cirq.readthedocs.io/en/stable/simulation.html

**Comment by kevinsung** [comment]
The method _is_ documented at https://cirq.readthedocs.io/en/stable/generated/cirq.Simulator.html: it's listed under "Methods", and clicking on it links to the full method documentation. Though it does look like that documentation could be expanded a bit.

As for adding it to the tutorial, I think it would make a much more compelling example once Cirq has a tensor network simulator that does not explicitly store the entire wavefunction.

**Comment by MichaelBroughton** [comment]
We've moved to new docs infra and this appears to have more complete docs now.
