### ISSUE TITLE
Give moment a name that can be used for debugging

### ISSUE THREAD

**Issue by ijdavis** [quantumlib/Cirq#2740]
Debugging a large quantum circuit is difficult because as the code changes it is very difficult to keep track of what action is performed at each simulation step. If the action of adding a sequence of gate operations to a circuit could have an optional string identifier, user defined function to be called with an established protocol before and after the execution of the gates when simulating a strong tie in could be immediately achieved between what gates have been added to a circuit, and much later in the logic when the simulator actually executes these gates. 

Eg:

def show(stepno [Step number], step [step data], after [True/False], id [identifier]):
   show_change(step.state_vector(), after, id)
 
circuit.append(gates, id="Perform H*n", before=show, after=show)

-- all named parameters optional

Regards, Ian
textserver.com@gmail.com

**Comment by dstrain115** [comment]
I am not sure I understand this feature.  Will the recent addition of tags work to fix this problem?

You can now tag Operations with meta-data, such as strings.  Would this work for your use case?
https://github.com/quantumlib/Cirq/blob/master/cirq/ops/raw_types.py#L406

**Comment by dabacon** [comment]
Note that one can do this already using code like this
```
q = cirq.LineQubit(0)
circuit = cirq.Circuit(cirq.X(q), cirq.H(q))
simulator = cirq.Simulator()
for step, x in enumerate(simulator.simulate_moment_steps(circuit)):
    print(f'Step: {step} Last moment: [{circuit[step]}] State: {x.state_vector}')
```

**Comment by dabacon** [comment]
The only thing I can think beyond this that would help is if Moments could have user defined names.  Potentially this could also be used in more detailed diagraming as well.

**Comment by dabacon** [comment]
I'm going to change this over to the moment labeling suggestion, since I think you can do step through circuits nicely with step numbers and access to the last moment using the above pattern.

**Comment by alexandrupaler** [comment]
Moment names would be a nice feature for debugging and visualisations.

I have also met situations where subcircuits (a sequence of moments) would be great to be named. Could sequences of moments with the same name (e.g. SUBCIRC) be drawn under the same moment parantheses?
```
\-----------/
   SUBCIRC
```

**Comment by dabacon** [comment]
We likely need some notion of collections of `Moments` in order to get control flow to work, so I think we would want to understand that before adding this behaviors, but it is a good suggestion modulo that.

**Comment by mpharrigan** [comment]
xref #3235

**Comment by verult** [comment]
cc @95-martin-orion - is the request in https://github.com/quantumlib/Cirq/issues/2740 handled by subcircuits?

**Comment by 95-martin-orion** [comment]
Subcircuits don't solve the issue as stated in the first comment (though Dave's suggestion seems like a reasonable way to do that), but they resolve everything discussed afterwards; subcircuits are labeled in diagrams and simplify thinking about large, repetitive circuits.

**Comment by verult** [comment]
Ack, closing. @ijdavis @alexandrupaler please feel free to reopen if suggestions in this thread don't satisfy your use cases.
