### ISSUE TITLE
Importing 'XmonSimulator'

### ISSUE THREAD

**Issue by shaksham95** [quantumlib/Cirq#2745]
Hello All,

I am trying to experiment with a code that requires 'XmonSimulator' but while trying to import this, I am getting the following error:

![image](https://user-images.githubusercontent.com/7498849/73922623-7aa15b00-48ef-11ea-9e19-76ea7b80f2bf.png)

Can you please suggest what should I do?

**Comment by vtomole** [comment]
Hey @shaksham95 , XmonSimulator was deleted from Cirq. Use the `from cirq import Simulator` that you have.

**Comment by vtomole** [comment]
@shaksham95 I'll close this. Feel free to reopen if you have any more question related to this issue.
