### ISSUE TITLE
NEW_THEN_INLINE design issue

### ISSUE THREAD

**Issue by ijdavis** [quantumlib/Cirq#2750]
The insert strategy NEW_THEN_INLINE should not be an option provided to a circuit, but rather an option attached to a gate.  This is because if you write code that yields gates and then embed those gates in a circuit using cirq.Circuit.from_ops there is no ability (without creating moments) to specify how the moments should be constructed.

Food for thought

Ian
textserver.com@gmail.com

**Comment by vtomole** [comment]
Hey @ijdavis , How about https://github.com/quantumlib/Cirq/issues/2775?

**Comment by ijdavis** [comment]
I think it would be a good idea to replace the circuit default strategy
with the opposite extreme .. compress nothing.  The automatic compression
has the problem that when one is creating a sequence of gates to add to a
circuit one must constantly break the gates into moments in order to
manually force the desired moments for both functional and visual reasons.
It is visually displeasing to have H's applied to every line which don't
line up.  While in my code I don't much care if gates are executed
sequentially I often do care very much if they are executed at the same
time or in the wrong order, and I am having to jump through hoops to stop
this default behaviour.  So at present you are making the default the
unsafe action, not the safe action.  It would be more sensible to have a
strategy that said merge into earliest moment when one actually wanted this
behaviour, than to have CIRQ default to this potentially undesirable
behaviour unless you tell it not to

To explain I've found the easiest way to sensibly debug circuits is to add
a one line identity to the circuit which exists merely to do some printing
of what the state is when this identity matrix is actioned.   But as things
currently are it is very hard to ensure that the identity is executed in
the order that gates are added and if it gets executed out of order its
usefulness as a debugging tool is destroyed.  You are basically assuming
when you optimise that gates don't have side effects and clearly within
simulations they can have side effects.

I also rather think you muddied waters in having circuit as one concept and
gate as another.  One should be able to nest circuits as readily as one
nests gates, and to print gates as readily as one prints circuits.

And I'd love better ability to debug executing code.

Regards, Ian

**Comment by Strilanc** [comment]
I think that this is a reasonable idea, but I don't think that it provides enough benefit to outweigh the cost implementing it and explaining it. The insertion into circuits is already unfortunately complicated..

**Comment by mpharrigan** [comment]
I think there are some good points raised here, but I don't think we're going to add insertion operations to gates per se. I also don't think we want to change the default circuit construction or risk breaking everyone's code. 

I'm going to close this, but we can continue the discussion on #2775 and also #3235 for your other "nesting" point
