### ISSUE TITLE
SimulationTrialResult usability

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#2755]
I'm always baffled by the members of this class. If you do a wavefunction simulation you need `result.final_state` but if you do a density matrix simulation you need `result.final_density_matrix`. 

The state vector / wavefunction terminology rears its head when you're trying to use `PauliString.expectation_from_xxx`

```python
term.expectation_from_wavefunction(result.final_state)
term.expectation_from_density_matrix(result.final_density_matrix)
```

**Comment by dabacon** [comment]
Is your main issue with the naming?  i.e. is #2143 your beef?

**Comment by mpharrigan** [comment]
Yes, closing as duplicate
