### ISSUE TITLE
Add support for indexing circuits and moments by qubits

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2762]
It would be convenient if we could slice circuits and moments by qubit instead o fjust by index. For example:

```python
# returns an empty moment if no operation on qubit, otherwise a moment containing the single operation
moment[qubit]  

# returns Circuit([moment[qubit] for moment in circuit])
circuit[qubit] 

circuit[ [qubit1, qubit2] ]

circuit[0:10, qubit1)

# range support
line_qubit1:line_qubit2 has obvious interpretation
grid_qubit_1:grid_qubit_2 could be corners of rectangle?
```

In general the goal is for the indexing to behave like existing python slicing, and e.g. numpy slicing (probably we can't make mutable views). Any implementation should go over the relevant cases.

**Comment by cduck** [comment]
I'm worried about relying on type to distinguish moment index from qubit index.  Because of numpy, I would be surprised if `object[indices0, indices1] == object[indices1, indices0]` even if `indices1` is a list of qubits.

If this is implemented, I think it's more important to maintain the invariant `obj[x, y] == obj[x, y]` no matter the types of `x` and `y`.

The API I would expect is this:
```python
# Returns a new circuit containing the first 10 moments
circuit[0:10]
# Returns a circuit (with the same number of moments) containing only operations that touch qubit.
# (Or maybe return just a list of operations to better agree with moment[qubit].
#  Pad with identity gates?)
circuit[:, qubit]
# Returns a circuit (with the same number of moments) containing only operations that touch any of [qubit1, qubit2].
circuit[:, [qubit1, qubit2]]
assert circuit[0:10, qubits] == circuit[0:10][:, qubits] == circuit[:, qubits][0:10] == circuit[:, qubits][0:10, :]
assert circuit[5, qubit] == circuit[5][qubit]  # A single operation (or KeyError)
assert circuit[5, [qubit1, qubit2]] == circuit[5][[qubit1, qubit2]]  # A moment

circuit[qubit]  # TypeError or IndexError

moment[qubit]  # Returns the **operation** that touches qubit or KeyError.
moment[[qubit1, qubit2]]  # Returns a moment containing only operations touching any of [qubit1, qubit2]

# Ranges
line_qubit1:integer:line_qubit2
grid_qubit_1:int_or_pair_of_int:grid_qubit_2?
```

**Comment by fedimser** [comment]
Hi. I would like to implement this. Can someone please assign this to me?
@Strilanc @cduck

**Comment by kevinsung** [comment]
@cduck I agree with you. But I don't understand the part about ranges. What does the integer or pair of integers in the middle of the slice mean?

**Comment by cduck** [comment]
For LineQubit it's the optional step size.  For GridQubit it's the optional x and y step sizes.  I don't know how useful this is but it's part of the slice API.

**Comment by cduck** [comment]
Which is more intuitive for you?  Momemt[qubit] is type Moment or type Operation?

**Comment by kevinsung** [comment]
Moment[qubit] should be an Operation.

Ah so you meant to write `line_qubit1:line_qubit2:integer` instead of having integer in the middle.

**Comment by cduck** [comment]
Yes.  My mistake.
