### ISSUE TITLE
repr(PauliString) on one qubit doesn't round-trip

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#2771]
```python
In[23]: ps = cirq.Z(q0)*1
In[24]: repr(ps)
Out[24]: 'cirq.Z.on(cirq.LineQubit(0))'
In[26]: type(ps)
Out[26]: cirq.ops.pauli_string.PauliString
In[28]: type(eval(repr(ps)))
Out[28]: cirq.ops.pauli_string.SingleQubitPauliStringGateOperation
```

and it is no longer a PauliString

**Comment by kevinsung** [comment]
`ps == eval(repr(ps))` is True though, which is perhaps all that matters.

**Comment by mpharrigan** [comment]
If you try to include a single-qubit pauli string as part of an object for the `json_serialization` test it doesn't work because it compares `jsonify(ps) == jsonify(eval(repr(ps)))`

**Comment by cduck** [comment]
Should `cirq.testing.assert_equivalent_repr` also test `repr(val) == repr(eval(repr(val)))`?

**Comment by Ashalynd** [comment]
AFAIK Python types by themselves aren't expected to be round-trippable.

**Comment by Strilanc** [comment]
`SingleQubitPauliStringGateOperation` inherits from `PauliString`, so it is technically still a pauli string.

**Comment by 95-martin-orion** [comment]
Is this still an issue?

**Comment by mpharrigan** [comment]
the behavior has not changed (I just ran the snippet provided)
