### ISSUE TITLE
Switch from Travis CI to Github Actions

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#2785]
Github Actions is [free for public repositories](https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#about-billing-for-github-actions) and allows [up to 20 concurrent runners per repo](https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits). We should consider migrating from Travis CI to use Actions instead.

Some sample conversion steps can be seen [here](https://github.com/anapaulagomes/from-travis-to-github-actions), and the full documentation for workflow config is available on the [Github help site](https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow).

**Comment by 95-martin-orion** [comment]
@Strilanc - following up on offline discussion. In my personal experience, Github Actions are very user-friendly: you can pretty much write a script and the matrix of conditions to run it under, and Actions will happily trundle through them.

**Comment by vtomole** [comment]
Relevant: https://github.com/quantumlib/Cirq/actions, https://github.com/quantumlib/Cirq/pull/2733/files

**Comment by dabacon** [comment]
This has been done
