### ISSUE TITLE
Point to style.md in developer documentation.

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#2787]
In the "developer documentation" https://cirq.readthedocs.io/en/stable/dev/index.html it would be nice to have a reference for how we import things 

- users `import cirq` and use `cirq.Thing` for everything
- library code imports "second level" modules e.g. `from cirq import ops` and then uses `ops.Thing` except in type annotations which should use `'cirq.Thing'` 
- Non-flattened submodules: I don't actually know, xref https://github.com/quantumlib/Cirq/pull/2748#discussion_r376561854 but I think we wanted people to do `import cirq.google as cg`

**Comment by kevinsung** [comment]
That information currently lives in [style.md](https://github.com/quantumlib/Cirq/blob/master/style.md).

**Comment by mpharrigan** [comment]
Ah. we should put that in the developer documentation
