### ISSUE TITLE
Local Development Setup Errors

### ISSUE THREAD

**Issue by BillGatesNephew** [quantumlib/Cirq#2791]
I'm trying to setup the project for local development on my macbook following the guide in `./docs/development.md`, and I run all of the steps (with the exception of the apt-system-requirements installation which I manually installed all the packages for) up until the `pytest .` step. When I run the tests I pass most but the following tests fail:
```
cirq/linalg/decompositions_perf_test.py EEEEEEEEEEEEEEEE                 [ 24%]
cirq/optimizers/decompositions_test.py ................................F [ 78%]
..........................................                               [ 78%]
cirq/protocols/json_serialization_test.py ............xx.x.x..x.x...xx.x [ 85%]
.x............x.x........x..........x.......xx...xx.xxx..x.xxx..x..x..xx [ 85%]
..x..x.x.x......xxxxx................................................... [ 86%]
...........................................................              [ 87%]
cirq/sim/simulator_test.py ..............F...                            [ 90%]
cirq/testing/asynchronous_test.py FF                                     [ 94%]
cirq/work/collector_test.py ..F...                                       [ 98%]
cirq/work/pauli_sum_collector_test.py FF...                              [ 98%]
cirq/work/sampler_test.py F....F                                         [ 98%]
cirq/work/work_pool_test.py FFFFFFFFFFF                                  [ 98%]
examples/examples_perf_test.py EEEEEEEEEE                                [ 99%]
```

Looking at the more detailed results it seems like for pytest the fixture `benchmark` isn't being found. I'll try to dig around some more to see if I can figure out how to fix it, but any help would be appreciated. I attached the full test log below. 

[test.TXT](https://github.com/quantumlib/Cirq/files/4256259/test.TXT)

**Comment by BillGatesNephew** [comment]
After poking around I tried running the `./check/pytest` script instead, which seems to pass mostly fine with the exception of the following test:
```
cirq/protocols/json_serialization_test.py .............xx...x.x...xxx.x.....x........x........xxxx......xx..x.xx..x...x.x.x.x....x.x..x. [ 85%]
..x.....xx...x.x..x.x.xx..xx............................................................................................................ [ 87%]
...                                                                                                                                      [ 87%]
```
Should these test cases be the ones to be concerned with as far as local development goes?

**Comment by vtomole** [comment]
> Looking at the more detailed results it seems like for pytest the fixture benchmark isn't being found


You need to `pip install -r dev_tools/conf/pip-list-dev-tools.txt`. I'm surprised this is not mentioned in that doc. Feel free to make a pull request for it.

> Should these test cases be the ones to be concerned with as far as local development goes?

Don't worry about these. We expect them to fail. See:
https://github.com/quantumlib/Cirq/blob/dec73130604956aa1ffc722f5a4263dab23eb265/cirq/protocols/json_serialization_test.py#L428

**Comment by BillGatesNephew** [comment]
@vtomole ok I updated it in #2792
