### ISSUE TITLE
Autosquash bot

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#2799]
As a contributor it is frustrating to having to keep pressing the "Merge with master" button on my PRs. Also, the Cirq mergebot is flaky / rarely up. 

What do you think about https://github.com/marketplace/actions/autosquash?

**Comment by dabacon** [comment]
I don't see a drawback except I would miss CirqBot's cute little face.  

There is no reason we couldn't enable it and test it out for a while while keeping old autobot around.

**Comment by balopat** [comment]
I'm going to close this - the decision for now is to keep running Cirq automerge bot.
