### ISSUE TITLE
Add matrix documentation for `class YYPowGate`

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2806]
Should be similar to `class XXPowGate` https://github.com/quantumlib/Cirq/blob/329765a96ec98e5856ba95ff41dec58f1e110452/cirq/ops/parity_gates.py#L37

**Comment by ishanrai05** [comment]
@vtomole Hi! Can I work on this?

**Comment by vtomole** [comment]
@ishanrai05 Sure!!
