### ISSUE TITLE
Find a QIS partner for cirq

### ISSUE THREAD

**Issue by viathor** [quantumlib/Cirq#2809]
Go through existing open source packages for quantum information science in python and see whether we can partner with one.

Context: #2763. See that issue for some basic info about [qiskit](https://qiskit.org/) and [qutip](http://qutip.org/).

If we don't find one that easily interoperates with cirq, we will instead implement some basic functionality in cirq.

**Comment by dabacon** [comment]
I think we have decided to roll our own?  In my own investigation I preferred qutip.

**Comment by vtomole** [comment]
Yeah, I prefer the rolling on own so we don't add another dependency.
