### ISSUE TITLE
Quantum information science subpackage

### ISSUE THREAD

**Issue by viathor** [quantumlib/Cirq#2810]
If #2809 turns up nothing, we'll implement some QIS functionality in cirq. I'm filing this issue to request comments on the name of the possible future QIS subpackage in cirq. A few options to get us started:
1. `cirq.qis`
2. `cirq.quantum_info`
3. `cirq.quantum_information`

My preference is 1. It is short and is consistent with some other second-level subpackages in cirq (e.g. ops instead of operations and linalg instead of linear_algebra). Option 2 is consistent with `qiskit.quantum_info`. Option 3 is the most descriptive.

@dabacon @Strilanc @kevinsung

**Comment by vtomole** [comment]
+1 for choice 1.

**Comment by kevinsung** [comment]
Choice 1 sounds good to me. Even if we do decide to partner with another package, we'll need a place for the code being moved in #2808 and maybe a few core qis functions that we want to implement ourselves.

**Comment by Strilanc** [comment]
+1 for 1

**Comment by dabacon** [comment]
Qis it is!
