### ISSUE TITLE
classical controlled operations/gates

### ISSUE THREAD

**Issue by alexandrupaler** [quantumlib/Cirq#2812]
Are there plans to support classically controlled gates? Would this be of interest?

**Comment by vtomole** [comment]
https://github.com/quantumlib/Cirq/issues/887 is needed in Cirq. is this related?

**Comment by alexandrupaler** [comment]
Thank you. It is related, but my question started without considering classical registers, although results would need to be stored somewhere.

I was asking because would like to design. optimize and verify teleported-like implementations of circuits consisting entirely of single qubit initialisations, CNOTs and a final round of measurements that control controlled gate/operations (I call this ICM in https://arxiv.org/abs/1509.02004)

Should I close this issue or keep it?

**Comment by vtomole** [comment]
Keep it.

**Comment by balopat** [comment]
The answer is yes, this is coming next quarter. See the roadmap item #3234.
