### ISSUE TITLE
EngineJob.results() shouldn't give up

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#2817]
Right now if you check for results for more than 500 seconds, it just gives up. In practice, this causes more harm than good. It can take down a whole run (by raising an exception) if someone or many someones slots in a sufficient amount of work in front of you in the queue

**Comment by dabacon** [comment]
On the other hand we have had loser who have "lost their server" and could not figure out how to shut down their job.

Maybe the solution is to set this at a day or something like that.

**Comment by dstrain115** [comment]
Timeout is now configurable and defaults to not timing out.
