### ISSUE TITLE
ZerosSampler

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#2818]
Often it is useful to test your workflow can successfully collect data without caring too much about what that data is. 

I propose a `ZerosSampler` that just immediately returns a bunch of zeros but otherwise follows the `cirq.Sampler` interface. This can also run the program through the proto serialization routines to verify that the gateset is correct. 

One final use case for this is profiling the "classical overhead" when running a complicated pipeline by removing the quantum part

**Comment by fedimser** [comment]
Hi. I would like to implment this. Can you please assign me?
@dstrain115

**Comment by dstrain115** [comment]
Assigned.  You were not able to assign yourself?

**Comment by dabacon** [comment]
The serializable gate set is specific to Google, so I would suggest this as a separate sampler.
