### ISSUE TITLE
Include backwards compatibility shims for cirq.contrib.noise_models

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#2826]
#2734 broke noise models. I'm using them. It should be easy to provide deprecated shims

**Comment by 95-martin-orion** [comment]
Making actual shims for these (i.e. backed by the other single-noise-type models) would require proper support for noise model composition, which is still in limbo.

In order to keep these around, we need to reinstate their fully-implemented versions.

**Comment by mpharrigan** [comment]
Oh. We should definitely keep them around until they can be replaced with composed noise models, at which point we should introduce shims with a deprecation warning
