### ISSUE TITLE
Add U3 gate

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2828]
![15fd2c46-bcdd-4941-a97a-205710b38619](https://user-images.githubusercontent.com/8405160/76337672-b0a67600-62c5-11ea-961f-0ae985a5b28f.png)

Source of  image: https://subscription.packtpub.com/book/application_development/9781789136432/app01/app01lvl1sec101/qubits-states-and-gates-in-terms-of-matrices

**Comment by cduck** [comment]
I think that is already implemented as part of the QASM output/import code: https://github.com/quantumlib/Cirq/blob/292080453e22e91dc5658a0cfa5043539944a950/cirq/circuits/qasm_output.py#L30

**Comment by vtomole** [comment]
Ah nice! Thanks @cduck

**Comment by rht** [comment]
Would be nice if this has a more easily discoverable name like `UGate` or `U3Gate`.
