### ISSUE TITLE
Move jupyter notebooks from `examples` to `examples/notebooks` directory

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2829]
`QAOA_Demo.ipynb` and `Rabi_Demo.ipynb`. Also, are notebook names supposed to be cased like that? If so we should rename `quantum_walks_tutorial.ipynb`

**Comment by joshp112358** [comment]
Hi, I can do this.

**Comment by vtomole** [comment]
Fixed by https://github.com/quantumlib/Cirq/pull/2831
