### ISSUE TITLE
Use relevant gate info in metrics-to-noise model

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#2832]
Split off from #2807. This issue specifically tracks improvements in the parameters of noise applied to specific gate types; at the time of writing, all non-measurement gates generate the same DepolarizingChannel regardless of type or duration.

**Comment by 95-martin-orion** [comment]
As noted in PR #2715, since the data for this model is Google-specific, we should move it to `cirq.google` when we get the chance.

**Comment by dstrain115** [comment]
@95-martin-orion Is this bug still useful?  If so, can you add more information about it so it can be done by a contributor?  Otherwise, let's close it.

**Comment by 95-martin-orion** [comment]
IMO #4640 and related issues and sub-PRs have resolved this. If we want further changes to the metrics-to-noise conversion process, it should be filed under a separate issue.
