### ISSUE TITLE
[Question] javascript/typescript/wasm support

### ISSUE THREAD

**Issue by ArturJS** [quantumlib/Cirq#2835]
@dstrain115 
Firstly, I must admit that this is a great library. Thanks a lot!
Secondly, I have a few questions:
 - Do you plan to implement javascript/typescript, say, `Cirq.js` library in order to have a huge community of javascript devs?
 - if you're not really sure about separated javascript library, what do you think about something akin to https://github.com/quantastica/qconvert-js in order to have a javascript representation of this library that can we easily converted to `*.py` and can be run on Python?
 - If both above is not feasible, apparently worth it considering the usage of [Pyodide](https://github.com/iodide-project/pyodide) in order to have a portable WASM library?

**Comment by dstrain115** [comment]
There are no current plans to convert Cirq to javascript.  

In terms of inter-operability with other quantum languages, Cirq already has output to QASM and plans to have interoperability with quil.

**Comment by ArturJS** [comment]
@dstrain115 Ok, thanks for the information!
Closing as resolved.

**Comment by vtomole** [comment]
Hey @ArturJS. We kind of have this. We support [Quirk](https://github.com/Strilanc/Quirk). See https://github.com/quantumlib/Cirq/tree/master/cirq/contrib/quirk.

**Comment by vtomole** [comment]
I reopened this issue so you can try out the Quirk support. Please let us know if it does what you are looking for.

**Comment by ArturJS** [comment]
@vtomole Wow, didn't know about that.
I'm gonna try out it the next week, when I have spare time for implementing a small prototype with this.
Thanks!

**Comment by alexandrupaler** [comment]
I think the goal of ArturJS would be to fully run Cirq in the browser as a webassembly package.

Would be interesting to see working, and pyodide certainly would help. Performance of Cirq would however be unknown, but maybe not really a dramatic decrease. With eg Quirk as frontend the use cases would exist.

For example, I ported pyzx to pyodide and experimented with combing in the browser C++ code for circuit compilation to use quirk as frontend. All code below still experimental.

[1] https://quantumresource.github.io/zxQentiana/
[2] https://alexandrupaler.github.io/quantjs/

**Comment by ArturJS** [comment]
@alexandrupaler Thanks a lot for the useful links!
Btw, I've found one more)
https://github.com/joastbg/quant-js

**Comment by alexandrupaler** [comment]
Indeed there are more projects doing quantum-something with webassembly. A useful use case could be where GUI and framework are joined.

**Comment by ArturJS** [comment]
@alexandrupaler Yeah, cannot wait when I have time to connect this with https://www.tensorflow.org/quantum 
Hope it will exponentially decrease the time for at least some machine learning approaches in the near future =)

**Comment by vtomole** [comment]
@ArturJS I do like the idea of having a https://www.tensorflow.org/js combined with `Cirq.js` or something. As @dstrain115 said, we currently don't have the resources to get into this. If you want to implement it, that would be awesome.

**Comment by ArturJS** [comment]
@vtomole 
>" https://www.tensorflow.org/js combined with Cirq.js" - hmm, sounds very interesting =)
I'll create a basic setup for the project and will let you know about the progress.
