### ISSUE TITLE
QuantumEngine's ability to sweep is not at parity with the simulator

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#2836]
I just got this error message:

```
TypeError: Unrecognized sweepable type: <class 'str'>.
sweepable: a
```

trying to run with
```python
    for ptup in sweep.param_tuples():
            tot_circ = circuit + cirq.measure(*qubits, key='z')
            sampler.run(tot_circ, ptup, 20_000)
```

where `sweep` is a `cirq.Product` of `cirq.Linspace`. This works fine through the simulator

**Comment by mpharrigan** [comment]
update: passing `dict(ptup)` has fixed it. This behaviour should be consistent with the simulator, though

**Comment by dstrain115** [comment]
This is a very old issue.  As mpharrigan pointed out, dict(ptup) should fix this.  The second argument should be a ParamResolverOrSimilarType which is a mapping from key to value (not a tuple).  

This is now consistent between both types, as it now fails the simulator as well.  I don't think that allowing tuples as a parameter resolver is intended behavior, so I am closing this issue.
