### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by muhammetfaik** [quantumlib/Cirq#2841]
Code and Error:
```
qubit = cirq.GridQubit(0, 0)
AttributeError: module 'cirq' has no attribute 'GridQubit'
```

**Comment by vtomole** [comment]
Hey @muhammetfaik , What version of Cirq are you using?

**Comment by cduck** [comment]
I've seen this issue (where Cirq is an empty package) after installing both `cirq` and `cirq-unstable `.  If this is the case, uninstalling both then reinstalling one solves the issue.

**Comment by muhammetfaik** [comment]
Thanks
