### ISSUE TITLE
Ubuntu 16.04.6 LTS pip3 install and not work

### ISSUE THREAD

**Issue by catafest** [quantumlib/Cirq#2842]
I try to used with python on Ubuntu 16 LTS
```
$ pip3 install cirq --user
Requirement already satisfied: cirq in ./.local/lib/python3.5/site-packages (0.5.556)

```
When I try to run it: 
```
$ python3
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cirq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'cirq'
```

**Comment by jitendrs** [comment]
I think you have two different python 3.5 version install on your machine. 
locate python3 installation path and search for cirq library in its site-packages directory. 
 you can try to install with below command as well to install in current python pointing version and cross check if you can import afterwards, 
python3 -m pip install cirq

**Comment by surarijit** [comment]
Please delete multiple versions of python 3 installed, or to be on the safe side create a virtual environment first and then install Cirq inside it.

**Comment by vtomole** [comment]
@catafest Feel free to reopen this if the stated solutions don't solve your problem.
