### ISSUE TITLE
Switch over to github actions

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2858]
It sounds like github actions is just better than travis-ci. We should switch over.

@95-martin-orion and @MichaelBroughton have used this in other repos and may be able to answer questions.

**Comment by 95-martin-orion** [comment]
Some sample Github Actions workflows: [qsim](https://github.com/quantumlib/qsim/blob/master/.github/workflows/bazeltest.yml), [TFQuantum](https://github.com/tensorflow/quantum/blob/master/.github/workflows/ci.yaml)

Related discussion: issue #2785, PR #2733

**Comment by vtomole** [comment]
Closed for https://github.com/quantumlib/Cirq/issues/2916
