### ISSUE TITLE
Cirq Tutorial - links broken

### ISSUE THREAD

**Issue by m-pedro** [quantumlib/Cirq#2887]
All the links under the "Next Steps" section of the Cirq Tutorial are broken. See here:
https://github.com/quantumlib/Cirq/blob/master/docs/tutorial.ipynb

**Comment by vtomole** [comment]
@dstrain115 Looks like we are still linking to `.md` files in that section. I'm assuming follow up pull requests are going to address this.

**Comment by m-pedro** [comment]
Added this to #2890:
The Examples link under "Next Steps" in the Cirq Tutorial is broken: https://github.com/quantumlib/Cirq/blob/master/docs/tutorial.ipynb.
It should point here:
https://github.com/quantumlib/Cirq/tree/1daad398783964cc9b1965ae957812b5ca1f1395/examples

**Comment by dstrain115** [comment]
All the links should be fixed now.  Let me know if you find any others that are broken.
