### ISSUE TITLE
Add a docstring that summarizes protocols in cirq/protocols/__init__.py

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2888]
https://github.com/quantumlib/Cirq/blob/master/cirq/protocols/__init__.py

**Comment by MrSaral** [comment]
Can I work on this? I am new around here, is there any slack communication channel?

**Comment by vtomole** [comment]
We have a [gitter channel](https://gitter.im/cirqdev).

**Comment by MrSaral** [comment]
#2939 Please review

**Comment by balopat** [comment]
This is a dupe of https://github.com/quantumlib/Cirq/issues/2973
