### ISSUE TITLE
Specify input range for Pauli gates/normalize output

### ISSUE THREAD

**Issue by thubregtsen** [quantumlib/Cirq#2915]
When performing Pauli x rotations, the values are not normalized after a rotation larger than pi. 

Code example:
```python    q = cirq.GridQubit.rect(1,1)
    circuit = cirq.Circuit(
      cirq.rx(angle(3*np.pi/2)).on(q[0])
    )
    simulator = cirq.Simulator()
    results = simulator.simulate(program=circuit, qubit_order=q).final_state
```

Example output:
[-0.70710677+0.j          0.-0.70710677j]

Assumption: even though the state is correct, I would say the expected behavior would be to output a normalized state (no minus in the |0>)

I would propose one of the following
* A range indication in the manual https://cirq.readthedocs.io/en/stable/generated/cirq.rx.html#cirq.rx 
* A normalization of the state

Of course, I might also miss something more fundamental, which I would be open to hear more about

**Comment by dabacon** [comment]
I don't think this is the range that is causing the problem as you will also not get a fully normalized state if you do smaller angles.

At some point we did normalize between steps (we did this in old xmon sim), but we no longer appear to do this.

Suggest we add this back, though this will slow down simulation.

**Comment by dstrain115** [comment]
@viathor to clarify intent behind this bug, tentative decision from circ cync is not to fix this.
