### ISSUE TITLE
Add Github Worflow for unstable builds

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2916]
Move the code in https://github.com/quantumlib/Cirq/blob/master/.travis.yml to a corresponding one in https://github.com/quantumlib/Cirq/tree/master/.github/workflows.

**Comment by jitendrs** [comment]
can you assign it to me @vtomole

**Comment by dabacon** [comment]
This is for unstable builds, correct (no longer called dev builds, though we have that name in the scripts).

**Comment by vtomole** [comment]
That's right; just re-titled the issue.

**Comment by jitendrs** [comment]
@vtomole is this still valid issue?

**Comment by vtomole** [comment]
@jitendrs  Yes.

**Comment by balopat** [comment]
@vtomole I'll close this - it seems that everything is moved to Github Worklfow now. Please reopen / ping me if I'm missing something!
