### ISSUE TITLE
Context should be optional for initializing EngineProcessor

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#2941]
Initializing a `cirq.google.EngineProcessor` requires providing an EngineContext, but simply passing `cirq.google.engine.engine.EngineContext()` works so that should be used by default. Also, shouldn't EngineContext be exposed outside the file level?

**Comment by dabacon** [comment]
Yes it should be exposed in `cirq.google`.

I don't think it should be default.  Technically it is a mutable container and one should not use mutable objects as defaults and instead use None.

**Comment by dabacon** [comment]
Oh I see this looks like a bug where the code is 
```
if not context:
```
and should be
```
if context is None:
```

**Comment by dabacon** [comment]
And noticed this refers to EngineProcessor not Engine so yes, should use a default of None.

**Comment by dabacon** [comment]
Looks like this is ubiquitous in the constructors of the Engine objects.

**Comment by dabacon** [comment]
Oh I see.  The idea is that you should only get to `EngineProcessor` via `Engine`.  Constructing it directly isn't what is intended.  This is why `EngineContext` is not exposed except at the file level. 

I think we need to document this at least in the constructor that you should be getting this object through Engine.

**Comment by dstrain115** [comment]
I think this is an old issue that can likely be closed, maybe after verifying or adding a snippet to a docstring.
