### ISSUE TITLE
EngineProcessor should return Device intead of proto

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#2949]
Currently we have get_device_specification, but that returns a proto.  Typically you take that and then pass it directly to a SerializableDevice.from_proto.  It would make more sense, I think to just have get_device() on the EngineProcessor which returns the cirq.Device object.

Is there something in the proto that doesn't end up in the device that is important?

**Comment by dstrain115** [comment]
Completed in #2954
