### ISSUE TITLE
Mølmer–Sørensen gate should be disentangled from XX parity gate

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#2958]
The Mølmer–Sørensen gate is nothing more than 
`ops.XXPowGate(exponent=rads*2/np.pi, global_shift=-0.5)`
But in general that gate is usually only called that by the ion trap community (since it referes to a specific very cool trick to couple via an oscillator mode).  Right now we special case XXPowGate names when it is this gate.  

This also leads to a strange coupling between ops and ion, not in code but in naming.

I think we could make the MS gate just the `XXPowGate` with the name change in ion.  If that were done then consumers who don't know about ions could consume it as a `XXPowGate` while it would show up ion trap code as desired.

**Comment by tanujkhattar** [comment]
> I think we could make the MS gate just the XXPowGate with the name change in ion
I'll create a new `MSGate` in `ion_gates.py` which derives from `XXPowGate` and would show the correct name in `repr`, `str` etc. Does this sound good?

**Comment by Strilanc** [comment]
You should also remove the MS naming from XXPowGate as part of adding it into MSGate.
