### ISSUE TITLE
Add to heatmap visualization tests

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#2969]
In the `test_colorbar` test there is a comment about testing that the position size and pad arguments are respected.

**Comment by ybc1991** [comment]
I think I can contribute to this issue

**Comment by ybc1991** [comment]
Looks like that more works besides the test are required. For instance:
```python
value_map = {
    (qubit.row, qubit.col): np.random.random() for qubit in cirq.google.Bristlecone.qubits
}

heatmap = cirq.Heatmap(value_map)
heatmap.set_colorbar(position='left') # specific the colorbar to left instead of right (allowed by current design)
heatmap.plot()
```

Will generate the overlap between colorbar and heatmap:
![image](https://user-images.githubusercontent.com/16711681/105103915-3064ab80-5a66-11eb-9e64-a21a3128b3d1.png)

**Comment by balopat** [comment]
Thanks for jumping in! Yeah, that looks like a bug - if you can fix it while you're adding the tests that would be great!

**Comment by balopat** [comment]
After reviewing your PR and playing with it - this is not a bug, this is the default behavior of the plotting framework. It is the user's responsibility to provide the right amount of padding which they can. So ignore my previous comment.

**Comment by ybc1991** [comment]
Yes, I also realize it. That is just the default pad with 2% is not good for other position. But I do plan to modified the behavior of default pad into like followings, wdyt?

```python
def set_colorbar(
  self, position: str = 'right', size: Optional[str] = None, pad: Optional[str] = None,
  **colorbar_options: Any,
) -> 'Heatmap':
  assert position in ["left", "right", "top", "bottom"]
  if size is None:
      size = "5%"
  if pad is None:
      pad_default_dict = {"left": "13%", "right": "2%", "top": "6%", "bottom": "10%"}
      pad = pad_default_dict[position]
```

**Comment by balopat** [comment]
I guess this is a nice feature to help the user, but I'm not fully convinced that it's worthwhile - these defaults really depend on the font size of the left axis label, for example. What if someone changes it?  How will we know that the defaults are broken now? I guess we could write tests for the default case and ensure that there is no overlap between the different axes. But that sounds like a lot of effort for something the user might tune to their liking anyway.

**Comment by ybc1991** [comment]
Yeah, agree that the default pad size is not static. And detecting the collision between the axes then setting the pad for it sounds difficult and unnecessary. I will just leave this function as used to be.
