### ISSUE TITLE
sphynx/readthedocs not listing/generating class method documentation

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2978]
For example, https://cirq.readthedocs.io/en/stable/generated/cirq.Moment.html has no list of the methods of `cirq.Moment`.

**Comment by Strilanc** [comment]
The relevant file to edit is probability `docs/conf.py`, which is the sphynx configuration code. For example, this is where the "skip member" method is defined ( https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#skipping-members ).

I recommend that, when testing changes, you temporarily reduce `api.rst` to only mention a single class. This makes document generation *way* faster. Taking seconds instead of minutes.

**Comment by dabacon** [comment]
I've looked into this and it is really wanky.  One problem is that the skip method is not correct as it ignores the `skip` variable.  But even when you fix that sphix seems to run the skip method twice, and the first time it runs it ignores the result.  This results in generated every method for a class, even after correctly configuring sphinx to only keep some methods.   

Going to poke around a bit more, but right now the only real option is either a) include all methods (which includes all possible dunder methods) or b) roll back the @documentation annotation to remove the skip logic.

**Comment by dabacon** [comment]
I've confirmed that this was broken by #2659
