### ISSUE TITLE
Improvements to QUIL output

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2983]
Related to: https://github.com/quantumlib/Cirq/issues/2386 and https://github.com/quantumlib/Cirq/pull/2903/files

1. Simplify ` def _quil_` in `quil_output.py` That huge `return` statement can be simplified with a permutation.
2. Fix https://github.com/quantumlib/Cirq/pull/2903/#discussion_r412376163

**Comment by hanusaj** [comment]
1. Adding a `gates_defined` variable to the `QuilFormatter` to replace the `rename_defgates` function.
2. Properly test the `fallback` function in the `_write_quil` function.

**Comment by vtomole** [comment]
Fixed by @karalekas.
