### ISSUE TITLE
Changing qubits in PointOptimizer causes ValueError

### ISSUE THREAD

**Issue by dstrain115** [quantumlib/Cirq#2990]
The cirq.PointOptimizer class assumes that an optimizer won't change qubits (or at least won't change qubits in a way that pushes the new gate backwards).   If two gates are modified in the same moment to use the same qubits, a ValueError is raised.

A check similar to https://github.com/quantumlib/Cirq/blob/master/cirq/circuits/optimization_pass.py#L128
needs to be added at or around Line 148 to detect this condition and adjust the 'i' index or frontier accordingly.

A minimal example that causes the issue is below.
```
class EverythingIs42(cirq.PointOptimizer):
      def optimization_at(self, circuit, index, op):
        if len(op.qubits) == 1:
          gate = op.gate
          new_op = op.gate(cirq.LineQubit(42))
          return cirq.PointOptimizationSummary(clear_span=1,
                                             clear_qubits=op.qubits,
                                             new_operations=new_op)

c=cirq.Circuit(cirq.X(cirq.LineQubit(0)), cirq.X(cirq.LineQubit(1)))
EverythingIs42().optimize_circuit(c)
```

**Comment by tanujkhattar** [comment]
I have sent a PR which tries to resolve this, but there is one inherent issue with trying to address this problem. If two gates in the same moment are changed to act on the same Qubit, what should be the ordering in which these two gates are applied on the Qubit? This will become implementation dependent and I'm not sure if that's something we want. Let me know your thoughts on this.
