### ISSUE TITLE
Find a better pattern for implementing control and target keywords and us for control gates.

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#3011]
Currently `CXPowGate` has a special override of `on` which allows one to pass in `control` and `target` when turning into a `GateOperation`.  It seems like we never followed up to do this for any other gates, and if we are going to do this we shouldn't do it in a one off manner.

**Comment by Strilanc** [comment]
At the very least the code can be simplified to `def on(self, target, control)` instead of the args/kwargs stuff that's there.

I'm fine with deprecating it.

**Comment by dabacon** [comment]
discussed at Cirq Cync: vote was to keep it, but to do it in a way that is not adding this code to every gate.

**Comment by dstrain115** [comment]
Discussion from cirq cync: cut this.
