### ISSUE TITLE
Subwavefunction documentation does not render LaTeX correctly

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#3023]
https://cirq.readthedocs.io/en/latest/generated/cirq.subwavefunction.html?highlight=subwavefunction#cirq.subwavefunction

**Comment by dabacon** [comment]
Hm, doesn't look like an LaTeX in doc strings is rendering
https://cirq.readthedocs.io/en/stable/generated/cirq.bit_flip.html

**Comment by dabacon** [comment]
Don't work on this until we have documentation upgrade done.

**Comment by balopat** [comment]
This looks good on the new site (http://go/q-stage/cirq/api_docs/python/cirq/linalg/sub_state_vector). Closing.
