### ISSUE TITLE
Random single qubit circuits always have empty moments

### ISSUE THREAD

**Issue by rmlarose** [quantumlib/Cirq#3028]
Single qubit circuits returned from [testing.random_circuit](https://github.com/quantumlib/Cirq/blob/master/cirq/testing/random_circuit.py#L38) are always empty with the default gate domain. For example:

```python
from cirq.testing import random_circuit

circuit = random_circuit(qubits=1, n_moments=4, op_density=0.99)
print(circuit)  # Blank

print(circuit.moments)
[cirq.Moment(), cirq.Moment(), cirq.Moment(), cirq.Moment()]
```

The reason is that the [default gate domain](https://github.com/quantumlib/Cirq/blob/master/cirq/testing/random_circuit.py#L23) contains two-qubit gates, so [`max_arity = 2`](https://github.com/quantumlib/Cirq/blob/master/cirq/testing/random_circuit.py#L89) which prevents any gates from being added to single qubit circuits.

This can be fixed by passing in a `gate_domain` with only one-qubit gates, but it seems useful to have the default behavior return non-empty circuits.

**Proposed change:** If the number of qubits is one, only select from single-qubit gates in the provided gate domain.

For example:

```python
if n_qubits == 1:
    gate_domain = {key: val for key, val in gate_domain.items() if val == 1}
```

Does this sound reasonable? If so I can submit a PR with this change.

**Comment by dabacon** [comment]
This seems reasonable to me. Could you also update the doc string to specify that the default is to use the `DEFAULT_GATE_DOMAIN` including noting the special case you are adding (The param currently doesn't document this)?  (I'd also maybe use a different word that `arity` or at least clarify it in the doc string, it's not a term that is universally understood).
