### ISSUE TITLE
Support multi-qubit measurements in `cirq.plot_state_histogram`

### ISSUE THREAD

**Issue by cduck** [quantumlib/Cirq#3031]
Quote from the docstring: "Currently this function assumes each measurement gate applies to only a single qubit."

Currently, I get an incorrect histogram if I didn't read the docstring and used a multi-qubit measurement (I always make circuits like this):
```python
qubits = cirq.LineQubit.range(3)
c = cirq.Circuit(
    (cirq.X**0.4).on_each(*qubits),
    cirq.measure(*qubits),  # One multi-qubit measurement
)
cirq.plot_state_histogram(cirq.sample(c, repetitions=10000))
# Incorrect output, no warning or error
```
![index2](https://user-images.githubusercontent.com/2476062/82605089-e5c42400-9ba4-11ea-8eb5-516586620a45.png)

If I use single-qubit measurement gates, I get the expected histogram:
```python
qubits = cirq.LineQubit.range(3)
c = cirq.Circuit(
    (cirq.X**0.4).on_each(*qubits),
    cirq.measure_each(*qubits),  # One measurement per qubit
)
cirq.plot_state_histogram(cirq.sample(c, repetitions=10000))
```
![index](https://user-images.githubusercontent.com/2476062/82605108-ebba0500-9ba4-11ea-9752-f337ecab1d26.png)

This looks like it could be fixed by adding some logic to `plot_state_histogram` (https://github.com/quantumlib/Cirq/blob/master/cirq/study/visualize.py#L22) that checks for multi-qubit measurements and either correctly interpret them or raise an error.

**Comment by AnimeshSinha1309** [comment]
I have made a quick-fix, I guess. Can you tell me what would be better, to raise an error/warning or to add said logic? Adding said logic does not seem hard, just a little longer. I don't know if it's the right way to get `n_qubits` by splitting by `,`, please suggest a better way if there is one.

**Comment by AnimeshSinha1309** [comment]
Along with the 2 code sample provided above being made equivalent, I have also made a mixture of single and mutli-qubit measurements work the same. Please tell me if some other combinations might have been expected. Just h-stacking the results worked.
```python
    c3 = cirq.Circuit(
        (cirq.X**0.4).on_each(*qubits),
        cirq.measure(*qubits[:2]),  # One multi-qubit measurement
        cirq.measure_each(*qubits[2:]),  # One single-qubit measurement
    )
    r3 = cirq.sample(c3, repetitions=10000)
    cirq.plot_state_histogram(r3)
```
