### ISSUE TITLE
Math for Bell Inequality?

### ISSUE THREAD

**Issue by cubicgate** [quantumlib/Cirq#3032]
Is it possible for someone to explain the math behind the Bell inequality example:
https://github.com/quantumlib/Cirq/blob/master/examples/bell_inequality.py ?

   Thanks!

**Comment by vtomole** [comment]
Hey @cubicgate. The math for this example is in section `15.2` of these lecture notes (https://homepages.cwi.nl/~rdewolf/qcnotes.pdf). We would love it if you added this math to that `bell_inequality.py` file. Let me know if you have questions about those equations.

**Comment by cubicgate** [comment]
Thanks @vtomole for this reference. Section 15.2 uses R(theta) which is a real-value matrix, but the bell_inequality.py program used X^-0.25 and X^0.5. Both of these X matrices have imaginary parts, so I am not sure how to translate the math in Section 15.2 into your X matrices. In a typical textbook, people tend to use just the Bell state, but you applied X^-0.25 after the Bell state. I tried to remove this matrix, but got a probability like 64%. It seems that these X matrices are important here.

**Comment by vtomole** [comment]
@cubicgate Ah. Now i understand why you filed this issue. It deviates significantly from how this is usually taught. Since this is an example, we should modify this program to better reflect what most people are familiar with.

**Comment by cubicgate** [comment]
@vtomole I think there is a great value for others to learn the math from this program since it is not the typical way of doing the math. If you can provide any help in this regard, that will be fantastic.

**Comment by sebgrijalva** [comment]
Maybe I can try to expand the math in the example (perhaps comparing it to deWolf's 15.2?)

**Comment by cubicgate** [comment]
Thanks @sebgrijalva ! I would love to learn from you.

**Comment by lucidteamug** [comment]
@cubicgate Did you make any progress? I am curious about this issue and would like to work with you if you still have room.

**Comment by cubicgate** [comment]
Thanks @lucidteamug ! I do not know any process on this.

**Comment by lucidteamug** [comment]
@sebgrijalva sebgrijalva  Did you make any progress? I am curious about this issue and would like to work with you if you still have room.

**Comment by lucidteamug** [comment]
@cubicgate Thanks~

**Comment by vtomole** [comment]
@cubicgate @sebgrijalva  @lucidteamug

It doesn't matter what bases Alice and Bob measure in as long as the angle between them is pi/4 radians. From https://algassert.com/quantum/2015/10/11/Bell-Tests-vs-No-Communication.html, it says:
>  If one of the entangled qubits is measured along an axis v, the other is measured along an axis w, and the angle between v and w is θ, then the proportion of agreeing outcomes is cos^2(θ/2).

(cos(pi/8))^2 ~= 85

The confusing part for me was that i was reading this program wrong. I thought it was measuring in the same basis, but it's not. It made sense for me to move the other gate down to where the basis rotations are made 

```python
# Prepare shared entangled state.
    circuit.append([
        cirq.H(alice),
        cirq.CNOT(alice, bob),      
        
    ])
   ....
    # Players do their basis operations based on their referee's coin.
    circuit.append([
        cirq.X(alice)**-0.25,
        cirq.CNOT(alice_referee, alice)**0.5,
        cirq.CNOT(bob_referee, bob)**0.5,
    ])


```

The "-0.25" on the X gate is that "-pi/4" rotation. Does this make sense?

**Comment by SamarthVadia** [comment]
Hi,

I also find the method of implementation in this example not straight-forward. I agree with @vtomole that it should be modified to better represent how it is usually taught. I have changed the example to correspond to the De Wolf's lecture notes by defining and implementing a controlled-Rotation gate. The modified example is here: https://github.com/SamarthVadia/Cirq/blob/bellexample/examples/bell_inequality.py

Have a look if it makes the example more intuitive. I'll be happy to expand the math if needed and create a pull request if it makes sense to change it in the master!
@cubicgate @sebgrijalva @lucidteamug

**Comment by vtomole** [comment]
@SamarthVadia We've voted to leave the example as-is and instead explain how it doesn't matter what basis is used. Does my previous comment make sense to you?

**Comment by cubicgate** [comment]
Thanks @SamarthVadia ! I like your example with a good reference!

**Comment by IlyaHomka** [comment]
@SamarthVadia thank you very much for a comprehensive explanation of the Bell theorem and its implementation. Dear  @vtomole could you add an explanation or short comments in the file bell_inequality.py for the future because I was confused with the of the file and the choice of gate X? (The Bell inequality relates the mean value of outcomes for Alice and Bob  
 [Michael A. Nielsen, Isaac L. Chuang - Quantum Computation and Quantum Information 10th Anniversary Edition-Cambridge University Press (2011), p. 115]).

**Comment by SamarthVadia** [comment]
Thank you everyone for the feedback!
@vtomole Yes, I find your comment on rearranging the X^-0.25 useful. I still think it is a good idea to make a native Cirq example simple and intuitive. However if it is discussed and voted to keep the example as-is, there's an argument for it that you emphasize in your comment and is explained in the blog about basis. It is a bit of an exercise but can be useful for the beginners. 
In that case, shall I move and update my docstring explanation to original example?

**Comment by vtomole** [comment]
@SamarthVadia  Let's leave the program as-is with your documentation saying "usually it's implemented like this, but we implemented it like this. They do the same thing because `explain why they both accomplish the same goal` . "

**Comment by vtomole** [comment]
This has been merged. I will close this. @cubicgate feel free to re-open if it hasn't addressed your concerns.
