### ISSUE TITLE
Circuits with qubits that are not acted upon.

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#3034]
Right now the qubits in a circuit are taken from the operations in the moments.  But there are cases where I want a circuit that operates on some qubits but not all of them (for example random circuits may generate circuits which don't act on some qubits).  This should be a case we can handle without too many hacks.  Right now I can hack by adding an identity gate for the qubit I want to include, but that seems....hacky.

**Comment by cduck** [comment]
Currently the circuit's device specifies its qubits (but this isn't used for the diagram right now).  What is the application where you want a circuit to use a set of qubits separate from the context of a device?

**Comment by mpharrigan** [comment]
I've run into this trying to show a circuit diagram for a part of a circuit

**Comment by balopat** [comment]
Discussed on Cirq Cynque: 
- the use cases seem to be one-off ones for now - i.e. an argument of qubits for diagramming should be sufficient to handle this
