### ISSUE TITLE
Changing Qubits in PointOptimizer leads to implementation dependent behaviour

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#3044]
Following up on #2990, `PointOptimizer` does not handle changing qubits well and the behaviour is undefined (many edge cases with different unintuitive outcomes). Eg:

```
class EverythingIs42(cirq.PointOptimizer):
      def optimization_at(self, circuit, index, op):
        if len(op.qubits) == 1:
          gate = op.gate
          new_op = op.gate(cirq.LineQubit(42))
          return cirq.PointOptimizationSummary(clear_span=1,
                                             clear_qubits=op.qubits,
                                             new_operations=new_op)
```

- Case-1

    - Input
    ```
    c=cirq.Circuit(cirq.X(cirq.LineQubit(0)), cirq.X(cirq.LineQubit(1)))
    EverythingIs42().optimize_circuit(c)
    ```
    - Output
    ```
    ValueError
    ```

- Case-2

    - Input
    ```
    c=cirq.Circuit(cirq.X(cirq.LineQubit(0)), cirq.Z(cirq.LineQubit(1)), cirq.Y(cirq.LineQubit(42)))
    EverythingIs42().optimize_circuit(c)
    ```
    - Output
    ```
    42: ───X───Z───Y───
    ```

- Case-3

    - Input
    ```
    c=cirq.Circuit(cirq.Z(cirq.LineQubit(1)), cirq.X(cirq.LineQubit(0)), cirq.Y(cirq.LineQubit(42)))
    EverythingIs42().optimize_circuit(c)
    ```
    - Output
    ```
    42: ───Z───X───Y───
    ```

Inconsistencies:
* Case-1 should not be a value error if Case-2 and Case-3 are not.
* Case-2 and Case-3 have the same input circuit but their optimised output is different, since the operators are non-commuting.

Expected behavior
* When changing the qubit on an operation, check whether the target qubit already has an operation in this moment (either due to previous qubit-change optimisations in the same moment or the input circuit itself has another operation on the qubit).
* If the new operation commutes will all the existing operations identified above, add the operation.
* else, raise an error.

**Comment by dabacon** [comment]
Discussion at Cirq Cync.  We should enforce that PointOptimizer does not allow adding qubits.  This should include a good error message when that constraint is violated.

**Comment by tanujkhattar** [comment]
This was resolved by [PR3016](https://github.com/quantumlib/Cirq/pull/3016)
