### ISSUE TITLE
Bugfix 0.8 release with documentation fix

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#3049]
#3048 fixes a regression where our documentation for 0.8 has all methods missing from the api docs.  We should make a bug fix release, and then push a new version of docs to readthedocs.

**Comment by dabacon** [comment]
Note that LaTeX in doc string is still broken, but I think that is OK.  Working on fixing that now (it's also a beast).

**Comment by dstrain115** [comment]
cirq 0.8.1 was released.
