### ISSUE TITLE
Avoid calling optimizers in optimizers

### ISSUE THREAD

**Issue by viathor** [quantumlib/Cirq#3050]
In review of #2955, @mrwojtek pointed out that optimizers should avoid calling other optimizers and instead leave any further optimization (such as merging single-qubit gates) up to the caller.

I agree with this since it makes it more explicit in the client code what optimizations actually take place and hence what output is produced. It can also reduce the number of calls to optimizers in some cases (e.g. when multiple optimizers are used).

In fact we already follow this approach in all optimizers except `decompose_two_qubit_interaction_into_four_fsim_gates_via_b`.

This issue is a request for comments on whether we want to remove

```python
    MergeSingleQubitGates().optimize_circuit(circuit)
    DropEmptyMoments().optimize_circuit(circuit)
```

from the end of that optimizer and whether we should adopt the rule of leaving such additional optimization steps up to the user in future optimizers.

**Comment by dabacon** [comment]
My intuition is that optimizers shouldn't call optimizers because it violates single use.  

For this specific case we should talk about this at Cirq Cync since it breaks an existing "api".
