### ISSUE TITLE
Fourier Transform demo fails due to incorrect return type

### ISSUE THREAD

**Issue by AnimeshSinha1309** [quantumlib/Cirq#3053]
The following piece of code throws an exception (error message below) when being executed:
https://github.com/quantumlib/Cirq/blob/2c3e6a8a2a12d4783da9d99afa3c70924c3bb733/examples/quantum_fourier_transform.py#L37-L40

A deprecated `WaveFunctionTrialResult` is returned by the function, instead of the promised `SimulationTrialResult`. I believe this is due to version conflicts, but I am running on colab and am pretty sure that everything is up-to date.
https://github.com/quantumlib/Cirq/blob/caab356e771d7d8cee27175c9640187f5fbcdfe9/cirq/sim/simulator.py#L202

The following error gets thrown (similar message even from a direct copy of the code and a fresh cirq install on Colab):
```
AttributeError                            Traceback (most recent call last)
<ipython-input-4-0399a87f440e> in <module>()

<ipython-input-4-0399a87f440e> in main(self)
     42         simulator = cirq.Simulator()
     43         result = simulator.simulate(qft_circuit)
---> 44         print('\nFinalState', np.around(result.final_state_vector, 3))

AttributeError: 'WaveFunctionTrialResult' object has no attribute 'final_state_vector'
```

**Comment by dabacon** [comment]
I am unable to reproduce this either locally or with a colab at HEAD.

This is a good question though: should we be taking care to keep examples in sync with last release and not HEAD?

How are you installing cirq on colab?  I used `!pip install git+https://github.com/quantumlib/cirq` and also tried `!pip install cirq-unstable` and both of those worked.

**Comment by AnimeshSinha1309** [comment]
I was using the stable version of cirq and trying to run the demo on that, I am starting out on Cirq and was unaware that I should have run them on unstable/master. You are right, both those work.

Anyways, here is the notebook that did not work because I was using the stable version.  https://colab.research.google.com/drive/1uwJjOvRa1REHLIgIzhfxc_tg9Z9Yo9H2?usp=sharing

I am closing this issue since it does not exist on master.

**Comment by vtomole** [comment]
@dabacon We've already made the decision that examples should be up to date with HEAD.

**Comment by dabacon** [comment]
@vtomole thanks!
