### ISSUE TITLE
Missing documentation for some cirq.linalg.* functions

### ISSUE THREAD

**Issue by cduck** [quantumlib/Cirq#3068]
`cirq.linalg.deconstruct_single_qubit_matrix_into_angles` in particular.  It is not exported to the top-level `cirq.*` namespace so maybe the documentation script is missing them?

In this case, `deconstruct_single_qubit_matrix_into_angles` should probably be added to `cirq/__init__.py` since the rest of `cirq.linalg` is there.

**Comment by dabacon** [comment]
Where are you looking at the docs?  Readthedocs?  The build docs script output?

**Comment by cduck** [comment]
Readthedocs: https://cirq.readthedocs.io/en/stable/api.html#algebra-and-representation

**Comment by cduck** [comment]
These are the URsL where I might expect it to be:
https://cirq.readthedocs.io/en/stable/generated/cirq.deconstruct_single_qubit_matrix_into_angles.html
https://cirq.readthedocs.io/en/stable/generated/cirq.linalg.deconstruct_single_qubit_matrix_into_angles.html

Latest:
https://cirq.readthedocs.io/en/latest/generated/cirq.deconstruct_single_qubit_matrix_into_angles.html
https://cirq.readthedocs.io/en/latest/generated/cirq.linalg.deconstruct_single_qubit_matrix_into_angles.html

**Comment by dabacon** [comment]
Yeah the doc coverage test only looks at a few namespaces for methods (`cirq`,`cirq.experiments`, `cirq.testing`, and `cirq.google`), so it would not fail if this were not at top level.  It would get generated by inclusion into the api.rst.
