### ISSUE TITLE
Named Qid

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#3069]
GridQubit and LineQubit have Qid versions, but there is no version of this for NamedQubit.

**Comment by dabacon** [comment]
@cduck was there a reason for not doing NamedQubit?

**Comment by cduck** [comment]
No reason other than to keep the number of different qid classes small.  Also GridQid was added later to match LineQid.

`NamedQubit('a').with_dimension(3)` works just fine but `LineQid.range()` is nice to have.

**Comment by dabacon** [comment]
Yeah I noticed it works, I guess the only thing you really lose is the type information (and maybe a less nice repr and str)?

**Comment by oliverob** [comment]
I think I would like to have a crack at this, as a first contribution. Is it simply matter of copying the format of LineQubit and GridQubit, but altering the functions to work like NamedQubit?

**Comment by cduck** [comment]
Yes, looking at LineQubit/LineQid and using the same structure for NamedQubit/NamedQid should be all that's needed.  Also take a look at the unit tests for them in the corresponding *_test.py files.
