### ISSUE TITLE
QubitOrder should be called QidOrder

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#3074]
Right?

**Comment by cduck** [comment]
There are many things already called '*qubit*' when I added qudits to Cirq.  At the time, we decided not to rename the large number of function and argument names already in Cirq, especially since qudits are a minor use case.

**Comment by balopat** [comment]
Discussed on Cirq Cynque: 
1. even if we'd rename it, a better name would be quditorder.
2. to benefit our users, we will keep the more familiar qubitorder

Closing.
