### ISSUE TITLE
sqrtISWAP serializer doesn't like rz, ry, rx

### ISSUE THREAD

**Issue by peterse** [quantumlib/Cirq#3078]
The `cirq.rz` helper function ([cirq.ops.common_gates:1045](https://github.com/quantumlib/Cirq/blob/d998b3afe20dd6783e00dcc2590ba0f162b95af7/cirq/ops/common_gates.py#L1045)) converts inputs to half turns (radians?) by dividing by sympy.pi for parametrized inputs, but this division is actually expressed as `sympy.Mul(sympy.Pow(sympy.pi, sympy.Integer(-1))`

The `sympy.Pow` part of that expression then causes problems with serializers that expect only `Mul` and `Add` in Sympy expressions (i.e. [cirq.google.arg_func_langs:143](https://github.com/quantumlib/Cirq/blob/d998b3afe20dd6783e00dcc2590ba0f162b95af7/cirq/google/arg_func_langs.py#L143)) 

Would it make more sense to convert all forms of `rz` inputs (symbolic or not) with division by `np.pi`?

reproducing code:
```
# This introduces `Pow`:
contains_pow = sympy.Symbol('x') / sympy.pi
for arg in contains_pow.args:
  print(arg, type(arg))
>>> x <class 'sympy.core.symbol.Symbol'>
>>> 1/pi <class 'sympy.core.power.Pow'>

# This casts to float:
no_pow = sympy.Symbol('x') / np.pi
for arg in no_pow.args:
  print(arg, type(arg))

>>> 0.318309886183791 <class 'sympy.core.numbers.Float'>
>>> x <class 'sympy.core.symbol.Symbol'>

# Serializer chokes up on Pow due to sympy.pi division
q0 = cirq.GridQubit(0, 0)
c0 = cirq.Circuit(cirq.rz(sympy.Symbol('x')).on(q0))
c1 = cirq.Circuit(cirq.ZPowGate(exponent=sympy.Symbol('x')/np.pi, global_shift=-0.5).on(q0) )

cirq.google.SQRT_ISWAP_GATESET.serialize(c0) # Throws ValueError: Unrecognized arg type: <class 'sympy.core.power.Pow'>
cirq.google.SQRT_ISWAP_GATESET.serialize(c1) # Works fine
```

@dstrain115

**Comment by dabacon** [comment]
Was there a reason not to support `Pow` in the language (or division for that matter)?  Worry about divide by zero?
