### ISSUE TITLE
Extend cirq.vis.Heatmap to visualize two-qubit interactions

### ISSUE THREAD

**Issue by mrwojtek** [quantumlib/Cirq#3088]
Currently cirq.vis.Heatmap supports plotting of single-qubit to float maps.

It would be very useful to be able to plot a two-qubit interaction between qubits on a grid, for example like the plot on Fig. S40 a) (page 43) of the supremacy supplementary paper: https://arxiv.org/abs/1910.11333

Direct application of this could be a visualization of cirq.google.Calibration data (each parameter could just have a plot() method for example).

**Comment by balopat** [comment]
Thank you @mrwojtek for the suggestion! Would 

For the record this is the image:

![image](https://user-images.githubusercontent.com/635073/90181127-cdf3da80-dd64-11ea-9708-73af797b04a2.png)

Example test data from `cirq.CalibrationData['two_qubit_sycamore_gate_xeb_cycle_total_error']` which returns the metric for a given edge on a chip. 

```
{
(cirq.GridQubit(3, 2), cirq.GridQubit(4, 2)):[0.004619111460557768],
(cirq.GridQubit(4, 1), cirq.GridQubit(4, 2)):[0.0076079162393482835],
(cirq.GridQubit(4, 1), cirq.GridQubit(5, 1)):[0.010323903068646778],
(cirq.GridQubit(4, 2), cirq.GridQubit(4, 3)):[0.00729037246947839],
(cirq.GridQubit(4, 2), cirq.GridQubit(5, 2)):[0.008226663382640803],
(cirq.GridQubit(4, 3), cirq.GridQubit(5, 3)):[0.01504682356081491],
(cirq.GridQubit(5, 0), cirq.GridQubit(5, 1)):[0.00673880216745637],
(cirq.GridQubit(5, 1), cirq.GridQubit(5, 2)):[0.01020380985719993],
(cirq.GridQubit(5, 1), cirq.GridQubit(6, 1)):[0.005713058677283056],
(cirq.GridQubit(5, 2), cirq.GridQubit(5, 3)):[0.006431698844451689],
(cirq.GridQubit(5, 2), cirq.GridQubit(6, 2)):[0.004676551878404933],
(cirq.GridQubit(5, 3), cirq.GridQubit(5, 4)):[0.009471810549265769],
(cirq.GridQubit(5, 3), cirq.GridQubit(6, 3)):[0.003834724159559072],
(cirq.GridQubit(5, 4), cirq.GridQubit(6, 4)):[0.010423354216218345],
(cirq.GridQubit(6, 1), cirq.GridQubit(6, 2)):[0.0062515002303844824],
(cirq.GridQubit(6, 2), cirq.GridQubit(6, 3)):[0.005419247075412775],
(cirq.GridQubit(6, 2), cirq.GridQubit(7, 2)):[0.02236774155039517],
(cirq.GridQubit(6, 3), cirq.GridQubit(6, 4)):[0.006116965562115412],
(cirq.GridQubit(6, 3), cirq.GridQubit(7, 3)):[0.005300336755683754],
(cirq.GridQubit(6, 4), cirq.GridQubit(6, 5)):[0.012849356290539266],
(cirq.GridQubit(6, 4), cirq.GridQubit(7, 4)):[0.007785990142364307],
(cirq.GridQubit(6, 5), cirq.GridQubit(7, 5)):[0.008790971346696541],
(cirq.GridQubit(7, 2), cirq.GridQubit(7, 3)):[0.004104719338404117],
(cirq.GridQubit(7, 3), cirq.GridQubit(7, 4)):[0.009236765681133435],
(cirq.GridQubit(7, 3), cirq.GridQubit(8, 3)):[0.024921853294157192],
(cirq.GridQubit(7, 4), cirq.GridQubit(7, 5)):[0.0059072812181635015],
(cirq.GridQubit(7, 4), cirq.GridQubit(8, 4)):[0.004990546867455203],
(cirq.GridQubit(7, 5), cirq.GridQubit(7, 6)):[0.007852170748540305],
(cirq.GridQubit(7, 5), cirq.GridQubit(8, 5)):[0.006424831182351348],
(cirq.GridQubit(8, 3), cirq.GridQubit(8, 4)):[0.005248674988741292],
(cirq.GridQubit(8, 4), cirq.GridQubit(8, 5)):[0.014301577907262525],
(cirq.GridQubit(8, 4), cirq.GridQubit(9, 4)):[0.0038720100369923904],
}
```

The solution would convert the data in `cirq.Calibration.heatmap` to the plot.

**Comment by crystalzhaizhai** [comment]
<img width="797" alt="qubit_interactions" src="https://user-images.githubusercontent.com/31509747/93839592-4f7f3800-fc42-11ea-9bb0-24831cd5924b.png">

**Comment by crystalzhaizhai** [comment]
> Thank you @mrwojtek for the suggestion!
> 
> For the record this is the image:
> 
> ![image](https://user-images.githubusercontent.com/635073/90181127-cdf3da80-dd64-11ea-9708-73af797b04a2.png)
> 
> Example test data from `cirq.CalibrationData['two_qubit_sycamore_gate_xeb_cycle_total_error']` which returns the metric for a given edge on a chip.
> 
> ```
> {
> (cirq.GridQubit(3, 2), cirq.GridQubit(4, 2)):[0.004619111460557768],
> (cirq.GridQubit(4, 1), cirq.GridQubit(4, 2)):[0.0076079162393482835],
> (cirq.GridQubit(4, 1), cirq.GridQubit(5, 1)):[0.010323903068646778],
> (cirq.GridQubit(4, 2), cirq.GridQubit(4, 3)):[0.00729037246947839],
> (cirq.GridQubit(4, 2), cirq.GridQubit(5, 2)):[0.008226663382640803],
> (cirq.GridQubit(4, 3), cirq.GridQubit(5, 3)):[0.01504682356081491],
> (cirq.GridQubit(5, 0), cirq.GridQubit(5, 1)):[0.00673880216745637],
> (cirq.GridQubit(5, 1), cirq.GridQubit(5, 2)):[0.01020380985719993],
> (cirq.GridQubit(5, 1), cirq.GridQubit(6, 1)):[0.005713058677283056],
> (cirq.GridQubit(5, 2), cirq.GridQubit(5, 3)):[0.006431698844451689],
> (cirq.GridQubit(5, 2), cirq.GridQubit(6, 2)):[0.004676551878404933],
> (cirq.GridQubit(5, 3), cirq.GridQubit(5, 4)):[0.009471810549265769],
> (cirq.GridQubit(5, 3), cirq.GridQubit(6, 3)):[0.003834724159559072],
> (cirq.GridQubit(5, 4), cirq.GridQubit(6, 4)):[0.010423354216218345],
> (cirq.GridQubit(6, 1), cirq.GridQubit(6, 2)):[0.0062515002303844824],
> (cirq.GridQubit(6, 2), cirq.GridQubit(6, 3)):[0.005419247075412775],
> (cirq.GridQubit(6, 2), cirq.GridQubit(7, 2)):[0.02236774155039517],
> (cirq.GridQubit(6, 3), cirq.GridQubit(6, 4)):[0.006116965562115412],
> (cirq.GridQubit(6, 3), cirq.GridQubit(7, 3)):[0.005300336755683754],
> (cirq.GridQubit(6, 4), cirq.GridQubit(6, 5)):[0.012849356290539266],
> (cirq.GridQubit(6, 4), cirq.GridQubit(7, 4)):[0.007785990142364307],
> (cirq.GridQubit(6, 5), cirq.GridQubit(7, 5)):[0.008790971346696541],
> (cirq.GridQubit(7, 2), cirq.GridQubit(7, 3)):[0.004104719338404117],
> (cirq.GridQubit(7, 3), cirq.GridQubit(7, 4)):[0.009236765681133435],
> (cirq.GridQubit(7, 3), cirq.GridQubit(8, 3)):[0.024921853294157192],
> (cirq.GridQubit(7, 4), cirq.GridQubit(7, 5)):[0.0059072812181635015],
> (cirq.GridQubit(7, 4), cirq.GridQubit(8, 4)):[0.004990546867455203],
> (cirq.GridQubit(7, 5), cirq.GridQubit(7, 6)):[0.007852170748540305],
> (cirq.GridQubit(7, 5), cirq.GridQubit(8, 5)):[0.006424831182351348],
> (cirq.GridQubit(8, 3), cirq.GridQubit(8, 4)):[0.005248674988741292],
> (cirq.GridQubit(8, 4), cirq.GridQubit(8, 5)):[0.014301577907262525],
> (cirq.GridQubit(8, 4), cirq.GridQubit(9, 4)):[0.0038720100369923904],
> }
> ```
> 
> The solution would convert the data in `cirq.Calibration.heatmap` to the plot.

The prototype produced the following figure

![Uploading qubit_interactions.png…]()

**Comment by crystalzhaizhai** [comment]
The prototype produced the following figure:

<img width="797" alt="qubit_interactions" src="https://user-images.githubusercontent.com/31509747/93839675-8ce3c580-fc42-11ea-9c28-1430261896d4.png">

**Comment by balopat** [comment]
That looks awesome! Thank you for picking this up!

**Comment by balopat** [comment]
This is closed now, thanks @crystalzhaizhai!

**Comment by balopat** [comment]
Ah I haven't realized that #3351 was merged into a branch - @crystalzhaizhai, this is really not something we typically do. Reopening the issue.

**Comment by balopat** [comment]
I realized that there are a couple of issues with the current printing: 
- the boundaries of the qubits are not clear, as we have grids. 
- the axes are reversed weirdly
- smaller test cases plot weirdly into the negative

```
cirq.InterHeatmap({
    (cirq.GridQubit(0, 0), cirq.GridQubit(0, 1)): 0.1,
    (cirq.GridQubit(0, 1), cirq.GridQubit(0, 2)): 0.2,
    (cirq.GridQubit(1, 0), cirq.GridQubit(0, 0)): 0.3,
}).plot()
```

![image](https://user-images.githubusercontent.com/635073/105432301-3eecc780-5c0c-11eb-96ba-367e99b18294.png)

in case of the sycamore connectivity graph (cirq.google.Sycamore) there is a shift in the position of the annotations - they are not on the boundaries of the qubits anymore: 

![image](https://user-images.githubusercontent.com/635073/105432453-85422680-5c0c-11eb-8123-185663b463d5.png)

I'm actively looking at these issues and will sort them out. 
The feature branch has been deleted and I'm going to open a PR based on my fork that is based on @crystalzhaizhai's initial work.

**Comment by tanujkhattar** [comment]
xref #3642
