### ISSUE TITLE
Broken decompositions_test

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#3103]
test_single_qubit_op_to_framed_phase_form_output_on_example_case has flaked out on me.

**Comment by dabacon** [comment]
This looks like it is blocking submissions to master, so may not even be a flake.

**Comment by dabacon** [comment]
```
E       Mismatched elements: 2 / 4 (50%)
E       Max absolute difference: 1.
E       Max relative difference: 1.41421356
E        x: array([[ 7.071068e-01-2.236690e-17j, -2.707207e-16-7.071068e-01j],
E              [-7.071068e-01+3.735782e-16j, -2.707207e-16-7.071068e-01j]])
E        y: array([[7.071068e-01+5.551115e-17j, 5.551115e-17-7.071068e-01j],
E              [5.551115e-17-7.071068e-01j, 7.071068e-01+5.551115e-17j]])
```

**Comment by dabacon** [comment]
it looks like the code that fixes for global phase isn't working for this case?  Cannot repo on my local box.

**Comment by dabacon** [comment]
Hypothesis is that this might be a numpy update.  https://pypi.org/project/numpy/#history was just updated to 1.19.  I confirmed that the last successful build was on 1.18 and the new failures are 1.19.  Checking to see if pinning fixes.

**Comment by dabacon** [comment]
Confirmed that penning to 1.16 numpy makes test pass.

**Comment by dabacon** [comment]
confirmed that is also fine a numpy 1.18

**Comment by tai271828** [comment]
confirmed that
  - numpy 1.19.0rc1 breaks decompositions_test
  - numpy 1.18.5 passes decompositions_test

**Comment by tai271828** [comment]
The same test case will pass with numpy=1.19.0 on my local machine (amd64, ubuntu 16.04.6). I dived into the difference between my local run and the github action CI, and the eigen vector from `np.linalg.eig(mat)` of  https://github.com/quantumlib/Cirq/blob/master/cirq/optimizers/decompositions.py#L142 differs.

**Comment by mpharrigan** [comment]
This test is failing for me. It's currently xfailed on windows with a reference to #2468 which is closed

**Comment by tai271828** [comment]
@mpharrigan may you please share your debugging information to us? e.g.

1. The output of `pip list`, or any method that could tell us your numpy version
2. Which cirq version you are using?

**Comment by maffoo** [comment]
Is this the only blocker for numpy 1.19? @dabacon, are you actively working on fixing the test?

**Comment by balopat** [comment]
The real test for `single_qubit_op_to_framed_phase_form` is in `test_single_qubit_op_to_framed_phase_form_equivalent_on_known_and_random` that covers the actual decomposition. The test that fails depends on a particular order and factors of the eigenvectors that makes it fail on different platforms and numpy versions. The solution to this is to remove the test.

On my Mac (where the tests pass):

```
mat: [[ 0.85355339+0.35355339j -0.35355339-0.14644661j]
 [ 0.35355339+0.14644661j  0.85355339+0.35355339j]]
 vals: [1.        +2.22044605e-16j 0.70710678+7.07106781e-01j]
 vecs: [[7.07106781e-01+0.j         3.88578059e-16+0.70710678j]
 [2.77555756e-16+0.70710678j 7.07106781e-01+0.j        ]]
u: [[7.07106781e-01-0.j         2.77555756e-16-0.70710678j]
 [3.88578059e-16-0.70710678j 7.07106781e-01-0.j        ]]
r: (0.7071067811865475+0.7071067811865475j) <---- (0.7071067811865475+0.7071067811865477j)/(1.0000000000000002+2.220446049250313e-16j)
g: (1.0000000000000002+2.220446049250313e-16j)

```

On a failed Ubuntu test:

```
mat: [[ 0.85355339+0.35355339j -0.35355339-0.14644661j]
 [ 0.35355339+0.14644661j  0.85355339+0.35355339j]]
 vals: [1.        +0.j         0.70710678+0.70710678j]
 vecs: [[-2.48353790e-16-0.70710678j -1.02857486e-16+0.70710678j]
 [ 7.07106781e-01+0.j          7.07106781e-01+0.j        ]]
u: [[-2.48353790e-16+0.70710678j  7.07106781e-01-0.j        ]
 [-1.02857486e-16-0.70710678j  7.07106781e-01-0.j        ]]
r: (0.7071067811865475+0.7071067811865475j) <---- (0.7071067811865475+0.7071067811865475j)/(1+0j)
g: (1+0j)
```

If I multiply up by sqrt(2) the diff is even more obvious: 

Left side is Mac (passes) right side is Ubuntu (failed): 
![image](https://user-images.githubusercontent.com/635073/94186967-55109400-fe75-11ea-9c8b-096a912d7a12.png)

The second eigenvector (column vector in vec) matches, it is `[1j, 1]`, however the first one Ubuntu numpy version has the eigenvector `[-1j, 1]` while the Mac one `[1, j]` i.e there is a factor of 1j difference. 

It seems like that a factor of norm 1 of the eigenvectors is not guaranteed in numpy. Which should be fine in the case of this particular decomposition. 

As for the windows tests, both **the order of the eigenvectors** _and_ **their factors** are different from the Mac execution:

```
mat: [[ 0.85355339+0.35355339j -0.35355339-0.14644661j]
 [ 0.35355339+0.14644661j  0.85355339+0.35355339j]]
 vals: [1.        +1.j 1.41421356-0.j]
 vecs: [[1.+0.j 0.-1.j]
 [0.-1.j 1.+0.j]]
u: [[1.+0.j 0.+1.j]
 [0.+1.j 1.+0.j]]
r: (0.9999999999999998-1.0000000000000002j) <---- (1.4142135623730945-3.1401849173675503e-16j)/(0.9999999999999997+0.9999999999999997j)
g: (0.9999999999999997+0.9999999999999997j)
```
