### ISSUE TITLE
Incompatible requirement: protobuf==3.8.0

### ISSUE THREAD

**Issue by DaniloZZZ** [quantumlib/Cirq#3110]
Hello

When installing cirq 0.8.1 using pip

```ERROR: google-api-core 1.21.0 has requirement protobuf>=3.12.0, but you'll have protobuf 3.8.0 which is incompatible.```

cirq has a requirement ```protobuf == 3.8.0 ```. this is incompatible with what other dependency wants.

```
> cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
...
> pip --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
```

**Comment by vtomole** [comment]
Does `pip install google-api-core 1.17.0 ` fix it?

**Comment by DaniloZZZ** [comment]
Yeah, I eventually solved the issue with manually installing `pip intsall google-api-core==1.14.0`, the lowest supported by cirq. Does this mean that pip is that bad at dependency solvig?

**Comment by dabacon** [comment]
I looks like the upper bound our requirements file is too high.
```google-api-core[grpc] >= 1.14.0, < 2.0.0dev```
If you had 1.21 installed before installing cirq it would not have downgraded and you'll get this error, I believe.  Once you downgraded it all worked. 

Since this is for 0.8.1 we would need to do a bug release to fix this.  (At head this isn't a problem since we have protobuf~=3.11.0 which I believe will give use 3.12)

**Comment by DaniloZZZ** [comment]
For anyone also facing this issue: the problem with manual installation of `google-api-core` is that it's actually `google-api-core[grpc]`. I used a hard-coded version of api-core in a CI script, and it failed on missing grpc. In my case, adding ` 'google-api-core[grpc]<=1.14.0',` to my setup.py file fixes the issue.

**Comment by balopat** [comment]
https://github.com/googleapis/python-api-core/blame/02d25799243bd76ac76423a08c063a2bee8d11e4/setup.py `google-api-core 1.20` is the last that has `protobuf >= 3.4.0`. So we could put an upperbound on that as @dabacon said. 

Alternatively we could upgrade our protobuf requirement. What are the constraints around that?

**Comment by balopat** [comment]
We will release next week a bug release on this!
