### ISSUE TITLE
Noise model details unclear

### ISSUE THREAD

**Issue by obriente** [quantumlib/Cirq#3139]
Something I just ran into in the docs - when we use a noise channel in a simulator does this occur per gate, or per qubit per moment?

I can't seem to find this anywhere, perhaps it should be added to the docs in a few places, as it's pretty relevant.

**Comment by dabacon** [comment]
Yes I agree this is very unclear.  Different noise models handle this noise differently, they basically transform the moments by adding extra noise operations.  These can depend on what is in the moment, for example.  So you could have a noise model that depends on which two qubit gate was executed.

**Comment by obriente** [comment]
I'll go and try to add details to the docstrings of the functions in ops/_common_channels - at least here it should be clear. Will need someone to check though as I could get this quite wrong.

**Comment by obriente** [comment]
Aaaand reading over the code I just realised how this is implemented and that it is well-documented.

Nevermind my stupidity.
