### ISSUE TITLE
setup a CHANGELOG.md

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3143]
It is fairly common to have a portable, human readable changelog for OSS projects. I think we should have one. For more background - I mostly agree with the reasons listed in https://keepachangelog.com/en/1.0.0/ 

My main motivation would be to introduce an "Unreleased" section, that would talk about Deprecations, Breaking changes and other notices that we can start to build before the releases. 

PR authors would be asked to think about whether this PR:
- encompasses a change worthy of mentioning (a full feature, bugfix of an issue, a final PR of a larger feature) 
- or not (typos, part of a larger feature that spans across multiple PR) 

It is also an opportunity to highlight awesome new features.

**Comment by dstrain115** [comment]
SGTM.  Maybe let's raise it at the next cirq cync and get broad approval?

**Comment by balopat** [comment]
> SGTM. Maybe let's raise it at the next cirq cync and get broad approval?

Sounds good!

**Comment by vtomole** [comment]
We (kind of) voted against this: https://github.com/quantumlib/Cirq/issues/1207.

**Comment by balopat** [comment]
Thank you for that pointer @vtomole!!! 

In my opinion we should reconsider given these arguments:  
- It is hard to keep a list of "unreleased" changes in Github releases
    - users won't see it
    - not everyone has access to creating Drafts 
- Github releases list releases in temporal format. When we move to multiple supported versions (after 1.0), we'll have this mixed bag of things like [here](https://github.com/kubernetes/kubernetes/releases).  

Great point on the directory structure + long file. I checked on kubernetes and this is what they've come up with: 
https://github.com/kubernetes/kubernetes/tree/master/CHANGELOG - we could adopt this format if our changelog really becomes that long. 

Finally, I think a CHANGELOG.md is still a bit more discoverable than Github releases in its current form, and portable - you can have a look at it in your IDE, no need for a browser.

**Comment by balopat** [comment]
Alternative idea: we could use the github wiki [like SciPy does](https://github.com/scipy/scipy/pull/7794#issuecomment-329409333) but add the link from somewhere visible to it.

**Comment by MichaelBroughton** [comment]
This never really caught on for one reason or another. Going to close for now.
