### ISSUE TITLE
Moment should have `operation_at`

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#3145]
There is a method called this on `Circuit`. It would make sense to live on `Moment` and then the circuit method could dispatch to it

**Comment by balopat** [comment]
This sounds like a reasonable and simple improvement, though moment can be indexed with the qubit (`moment[q]` returns the operation on that qubit), isn't it superfluous to introduce `operation_at`?

**Comment by mpharrigan** [comment]
Oh I didn't realize you could index into it like that. In any event, `Circuit.operation_at` should use that functionality

**Comment by balopat** [comment]
That is true, we could use moment[q] in Circuit.operation_at - just to clarify do you think it would be valuable to add `operation_at` to Moment as well as it might be more discoverable than the indexing?

**Comment by mpharrigan** [comment]
I can't speak for everyone, but I would have found it if it was called `operation_at` :)

**Comment by exAClior** [comment]
Hi, would it be possible for me to try and add `operation_at` to Moment? I might need to read the relevant codes first as I am not entirely familiar with them.

**Comment by balopat** [comment]
You got it! Thanks for volunteering!

**Comment by balopat** [comment]
ping @exAClior - are you looking at this? Thank you!

**Comment by exAClior** [comment]
> ping @exAClior - are you looking at this? Thank you!

Yes, I finished adding the feature, but I need to add tests for that piece of code. I will update it tonight.
