### ISSUE TITLE
Better representation for QPUs

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3149]
From @mpharrigan: Consider tying together some of the related concepts: device object, sampler, device calibration, and device name, supported gatesets into an easy-to-get nicely-named object. 
A version of these classes in ReCirq: https://github.com/quantumlib/ReCirq/blob/master/recirq/engine_utils.py#L232

**Comment by mpharrigan** [comment]
Related / possible dupe: https://github.com/quantumlib/Cirq/issues/2820

**Comment by balopat** [comment]
It is, closing as a dupe.
