### ISSUE TITLE
`final_wavefunction` is deprecated wrong

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#3170]
If you use `cirq.final_wavefunction` it says:

```
  /.../: DeprecationWarning: final_state_vector was used but is deprecated.
  It will be removed in cirq v0.10.0.
  Use `cirq.final_state_vector` instead.
```

**Comment by mpharrigan** [comment]
there is a test: `mux_test:test_deprecated` that must be broken as well. It uses `cirq.testing.assert_logs`

**Comment by balopat** [comment]
This is an issue with the deprecation function's text itself - I'll have a look

E.g.

```
>>> cirq.QFT(*cirq.LineQubit.range(3))
<input>:1: DeprecationWarning: qft was used but is deprecated.
It will be removed in cirq v0.10.0.
Use cirq.qft instead.
```

**Comment by balopat** [comment]
The tests are just matching on the substring of the new function name to be there but not the structure of the whole text.

**Comment by mpharrigan** [comment]
the mux test deprecated searches for both the new name *but also* the old function name which *isn't* (wasn't ... I see you've already fixed the underlying issue) in the message
