### ISSUE TITLE
Broken Link of Variational Algorithm on Documentation Page

### ISSUE THREAD

**Issue by shadab-entrepreneur** [quantumlib/Cirq#3178]
**Description of the issue**
Under the [Advanced Tutorials](https://cirq.readthedocs.io/en/stable/examples.html#advanced-tutorials) section on documentation page, [Variational Algorithm](https://cirq.readthedocs.io/en/latest/tutorials/variational_algorithms.html) link is broken

**How to reproduce the issue**
Go to this [page](https://cirq.readthedocs.io/en/stable/examples.html#advanced-tutorials) and check for the link of Variational Algorithm

**Comment by balopat** [comment]
Thank you for letting us know @shadab-entrepreneur! Would you be open to fix it? We are open for PRs! :)

**Comment by shadab-entrepreneur** [comment]
Sure @balopat 
I'm new to the documentation of Cirq, can you please point me to the file from where these notebooks are getting rendered?

**Comment by shadab-entrepreneur** [comment]
Sure @balopat

**Comment by balopat** [comment]
Fixed in #3178
