### ISSUE TITLE
QCircuit does not render gates that cross each other correctly

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#3183]
**Description of the issue**

QCircuit creates extra wires in diagram.

**How to reproduce the issue**

Here is a circuit where CNOTs pass over each other:
```
q0, q1, q2, q3 = cirq.LineQubit.range(4)
c = cirq.Circuit(cirq.CX(q0, q2), cirq.CX(q1, q3))
print(c)
```
prints
```
      ┌──┐
0: ────@─────
       │
1: ────┼@────
       ││
2: ────X┼────
        │
3: ─────X────
      └──┘
```
If you run this through the qcircuit convertor,
```
cirq.contrib.qcircuit.circuit_to_latex_using_qcircuit(c)
```
it produces output
```
\Qcircuit @R=1em @C=0.75em {
 \\
 &                      & \qw    &         \qw    &         \qw    &     &\qw\\
 &\lstick{\text{0}}& \qw& \qw    &\control \qw    &         \qw    & \qw &\qw\\
 &\lstick{\text{1}}& \qw& \qw    &         \qw\qwx&\control \qw    & \qw &\qw\\
 &\lstick{\text{2}}& \qw& \qw    &\targ    \qw\qwx&         \qw\qwx& \qw &\qw\\
 &\lstick{\text{3}}& \qw& \qw    &         \qw    &\targ    \qw\qwx& \qw &\qw\\
 &                      & \qw\qwx&         \qw    &         \qw    & \qwx&\qw\\
 \\
}
```
you can see there are extra wires here not corresponding to any of the four qubits.  Compiling this in LaTeX confirms that the diagram is broken.

**Cirq version**
pip installed cirq-unstable
0.9.0.dev

**Comment by balopat** [comment]
Thanks for opening! This could be a great first issue for someone in the community to pick up. 

Here's the compiled latex for reference:

![image](https://user-images.githubusercontent.com/635073/88974451-7d14ba00-d26d-11ea-8751-b9e5190ddd93.png)

**Comment by exAClior** [comment]
Hello @balopat @dabacon , may I try to work on this one? I presume I would try to modify the corresponding function under the branch 0.9.0.dev? If so, do I need some special qualifications to be able to see that branch? Thanks in advance for your help.

**Comment by balopat** [comment]
Hey @exAClior, thank you for volunteering! Yes, please, have a look, let me know if you get stuck! 
0.9.0.dev means currently that that's the `master` version. Just checkout master in your fork, create a branch based on that and raise a PR against the `master` in this repo!
