### ISSUE TITLE
Customizing MatrixGate circuit diagram info

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#3184]
Currently MatrixGate plots an entire matrix when displayed in a circuit.  For single qubit gates this is usually OK, but for two qubit gates the gates end up being pretty monstorous.  I've taken to hacking _circuit_diagram_info_ in this case, but I think it would be nice if there was a way to do this at construction time, i.e.
```cirq.MatrixGate(u, circuit_diagram_info=lambda or diagram info)```

**Comment by cduck** [comment]
This sounds like a job for tags.

**Comment by balopat** [comment]
@cduck what is your thinking around tags here? Use tags as a mechanism to override the circuit_diagram_info for any operation? 

Anyway - I marked this as a good first issue - it should be easy for anyone to implement whichever the decision. But please discuss the design first here before opening the PR.

**Comment by cduck** [comment]
Previously, @dstrain115 listed "gate color in a diagram" as one of the use cases of tags.  One option could be to define a tag that means "use a compact gate representation".

In terms of design, this would require:
- Make the circuit diagram drawer check for this tag.
- Add an attribute to `CircuitDiagramInfoArgs` that tells gates to return compact diagram info.
- Add support for this attribute in `MatrixGate`.

---
For @dabacon's use case, instead of applying the formatting to each `MatrixGate`, it might make more sense for `Circuit.to_circuit_diagram` to have a `compact` parameter that it passes to gates through the `CircuitDiagramInfoArgs` to make this easy to use on the entire circuit.

**Comment by mpharrigan** [comment]
A related note if anyone takes this on: currently in the SVG circuit code, I hack anything with a newline in it to just display as a `?` :)

**Comment by Strilanc** [comment]
I agree that this makes sense. For example, when converting from a circuit specified in another system (e.g. U3 in qiskit) this would be a fast way to convert the gate while preserving some debugging information like the name.

**Comment by thanacles** [comment]
Unless I'm missing something, it feels like the idiomatic solution to this is to extend MatrixGate and override _circuit_diagram_info_.

```
import cirq
from cirq import protocols
import numpy as np

class PrettyMatrix(cirq.MatrixGate):
    def _circuit_diagram_info_(
        self, args: 'cirq.CircuitDiagramInfoArgs'
    ) -> 'cirq.CircuitDiagramInfo':
        channels = [f'#{i}' for i in range(0, len(self._qid_shape))]
        return protocols.CircuitDiagramInfo(wire_symbols=channels)

a = cirq.NamedQubit('a')
b = cirq.NamedQubit('b')

QFT2 = np.array([[1, 1, 1, 1],
                 [1, 1j, -1, -1j],
                 [1, -1, 1, -1],
                 [1, -1j, -1, 1j]]) * 0.5
my_qft2 = PrettyMatrix(QFT2)
print(cirq.Circuit(cirq.H(a), my_qft2(a,b), cirq.H(b)))
```

If the ask is to have the ability to override the circuit diagram display of the gate with an arbitrary display, then I think it would be best to do the above.  If however we want to officially support a specific, more condensed display, then we should define what that display is before work on this bug.  Let me know if I'm missing something.

**Comment by balopat** [comment]
I'm not against it - I like the simplicity of it, but it requires the user to specify the tag. I think that might solve it for some users. If someone wants an automated solution instead (e.g. with a `compact` flag) - please comment here.
