### ISSUE TITLE
Optimization Pass that runs through optimizations until no further are needed

### ISSUE THREAD

**Issue by akshajgaur** [quantumlib/Cirq#3185]
I think that it would be very helpful if we had an optimization pass that ran many optimizations for maximal gate reduction. I have been running: 

```
optimized_for_xmon -> MergeInteractions -> MergeSingleQubitGates -> EjectZ -> EjectPhasedPaulis -> DropEmptyMoments
```

Is there a better order/pass than this (including cliffords), and if there was, would adding 1 pass help.

**Comment by balopat** [comment]
Hi @akshajgaur, thanks for opening this. Yeah, that would be great if could give minimal circuits. However, to my knowledge global optimization of a circuit is QMA hard in the general case. 
This tells me that it would be hard to pin down the exact optimizations that would result in a minimal circuit and that the exact list of steps would be different for different circuits. Thus I don't think that there is a single recipe that can work for all circuits. Exploring that space sounds expensive, so I would shy away from that too. 

Having said all that - if you find a paper that has solid foundations for large classes of circuits that can beat the current optimizers that would be interesting to explore!  

Out of curiosity - what kind of circuits are you running (arithmetic, chemistry, textbook algos, etc?)?
