### ISSUE TITLE
Tensor product of 2 state vectors

### ISSUE THREAD

**Issue by zohimchandani** [quantumlib/Cirq#3188]
Ia there a way to tensor product 2 state vectors?

**Comment by balopat** [comment]
Hi @zohimchandani, in general states are represented as numpy arrays of the probability amplitudes which then you can use np.kron to provide the tensor product, i.e. there is no special representation in Cirq. If you are thinking about tensor product of basis states, there is a PR that is going that direction: https://github.com/quantumlib/Cirq/pull/3171. What are you trying to achieve?

**Comment by balopat** [comment]
_Please note_: Usage related questions usually go to Quantum Stack Exchange with the cirq tag. Closing, as this is not an issue per se.
