### ISSUE TITLE
Can cirq  work on Large-scale distributed platform？Such as a cluster of GPUs or  a cluster of CPUs?

### ISSUE THREAD

**Issue by amandalqy** [quantumlib/Cirq#3189]
Can cirq  work on Large-scale distributed platform？Such as several machines each with one cpu, or several machines each with one gpu, or several gpus on one machine?

**Comment by balopat** [comment]
Hi @amandalqy - thank you for your question. 

Yes, Cirq can work on a large scale distributed platform using [qsim](https://github.com/quantumlib/qsim). More specifically you would need to use [qsimh](https://github.com/quantumlib/qsim/blob/master/docs/usage.md#qsimh_amplitudes-usage) via Qsimcirq. 

Please note: Usage related questions usually go to Quantum Stack Exchange with the cirq tag. Closing, as this is not an issue per se.
