### ISSUE TITLE
Approximately equal circuits with symbols not detected by cirq.approx_eq

### ISSUE THREAD

**Issue by zaqqwerty** [quantumlib/Cirq#3192]
**Description of the issue**
Circuits with symbols are determined to be unequal by `cirq.approx_eq` when they should be approximately equal.

**How to reproduce the issue**

```python
q = cirq.GridQubit(0, 0)
s = sympy.Symbol("s")

no_symbol_1 = cirq.Circuit(cirq.rz(1.515)(q))
no_symbol_2 = cirq.Circuit(cirq.rz(1.510)(q))
print(cirq.approx_eq(no_symbol_1, no_symbol_2, atol=0.1))

symbol_1 = cirq.Circuit(cirq.rz(1.515*s)(q))
symbol_2 = cirq.Circuit(cirq.rz(1.510*s)(q))
print(cirq.approx_eq(symbol_1, symbol_2, atol=0.1))
```
First output is `True`, second output is `False`

**Cirq version**
0.8.2

**Comment by balopat** [comment]
Thank you for filing this @zaqqwerty - this should work. Either approx_eq should throw an error if the arguments are parametrized that it's not supported or support it properly. This behavior is a silent failure. Marked it as a bug. 

It also seems like a self contained issue, perfect for contributors to pick up!

**Comment by tonybruguier-google** [comment]
Is help still needed on this? I am looking for a good first issue.

**Comment by zaqqwerty** [comment]
Thanks for offering to help!  Of the options Balint listed, most helpful would be to figure out how to make:
```python
symbol_1 = cirq.Circuit(cirq.rz(1.515*s)(q))
symbol_2 = cirq.Circuit(cirq.rz(1.510*s)(q))
print(cirq.approx_eq(symbol_1, symbol_2, atol=0.1))
```
output `True`.

**Comment by balopat** [comment]
It's all yours @tonybruguier-google - thanks for volunteering!

**Comment by tonybruguier-google** [comment]
Sent:
https://github.com/quantumlib/Cirq/pull/3195

Note that I changed the test case. It seems that it compares 5e-3*s/pi which can be big if s is large. Happy to change the PR, of course.
