### ISSUE TITLE
upgrade to numpy 0.19

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3210]
Discover all the issues / test failures related to numpy 0.19 and upgrade our requirements.txt.
More context: https://github.com/quantumlib/Cirq/pull/3106

**Comment by exAClior** [comment]
Hi @balopat, I just updated NumPy to 1.19 and ran check/all | grep numpy, it seems like every test passed and no warning regarding NumPy has been raised. But there is a mention that "Importing from numpy.matlib is deprecated since 1.19.0" which is related to quimb package that was used.

**Comment by abhik-99** [comment]
Can I help on this if needed?

**Comment by balopat** [comment]
@exAClior - that sounds great - can you confirm that #3105 and #3103 - the currently known broken tests - are passing by raising a PR? @abhik-99  - I would leave this with @exAClior if he is interested.

**Comment by exAClior** [comment]
@balopat Just a quick update, I ran the following commands `pytest ./cirq/ion/convert_to_ion_gates_test.py` for #3105 and `pytest ./cirq/optimizers/decompositions_test.py` for #3103 and they did pass with no problem at all. 
My python version is 3.8.5 and the numpy version is 1.19.1. 
However, as I am trying to create a PR to report this, I pulled from the latest upstream/master I ran `./cirq/check/all`, it was not happy at all. I think pylint does not treat a overloaded function very nicely. This morning everything runs fine. I don't know if it is the last commit on master that creates this problem. I could go ahead revert the last commit on my fork and investigate

**Comment by balopat** [comment]
I would be wary of using python 3.8 - I think that has it's own bag of issues (#3194). I would suggest solving this using a python 3.7 env first.

**Comment by exAClior** [comment]
> I would be wary of using python 3.8 - I think that has its own bag of issues (#3194). I would suggest solving this using a python 3.7 env first.

Thank you so much for your advice. It turned out that I am not installing the requirement for checkers and etc correctly. But numpy 1.19.1 should work. I am double testing everything before I create the PR.
