### ISSUE TITLE
Fluent syntax for applying controlled gates

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#322]
Conditional gates right now rely on ordering of qubits to distinguish the control.  

We could add a GateFeature which has
from(qubits)
to(qubits)
which chains and produces on(qubits suitably ordered)

**Comment by ptrc-n** [comment]
I would like to work on that issue.
This would be my very first contribution though.

Should someone assign that issue to me before i start working on it?
Any further hints i should consider, other than those in the contributer guide, are highly appreciated.

**Comment by Strilanc** [comment]
I would say this is a good one. Just do the first part and ignore everything I said after that.

Modify CNOT's `on` method to take `**kwargs`. Check for the presence of `control` and `target` keywords (with fallback to positional arguments). If `Gate.__call__` does not have `**kwargs`, add it and forward it into `Gate.on`.

**Comment by ptrc-n** [comment]
Guess the issue could be closed
