### ISSUE TITLE
Multi-qubit channels

### ISSUE THREAD

**Issue by viathor** [quantumlib/Cirq#3220]
In [cirq/ops/common_channels.py](https://github.com/quantumlib/Cirq/blob/master/cirq/ops/common_channels.py) cirq implements a number of common quantum operations. All of them act on single-qubits only, but some of them (e.g. depolarizing channel) have clear definitions for multiple qubits. We should generalize them to handle multiple qubits.

**Comment by tonybruguier** [comment]
So, I think following Nielsen and Chuang, the formula for the depolariazation matrix is 

I / 2**n = \sum (P_i . rho . P_i) / 2**(2n)

Right? If so, maybe I could take a crack at this?

**Comment by tonybruguier** [comment]
@viathor What other channel would you like to have multi-qubit (besides depolarization)? I could have some extra time.

**Comment by viathor** [comment]
I think all other channels in [common_channels.py](https://github.com/quantumlib/Cirq/blob/master/cirq/ops/common_channels.py) don't need special generalization since their natural action on multiple qubits is the tensor product of their action on individual qubits (this is different from the depolarizing channel).

That said, #3262 only generalizes the asymmetric depolarizing channel. Once it is merged, you should be able to use your new generalized asymmetric depolarizing channel to also generalize the symmetric one (note that the symmetric one is called simply `DepolarizingChannel`).

**Comment by tonybruguier** [comment]
@balopat balopat You can assign this issue to me, if you want.

**Comment by viathor** [comment]
We should also generalize the symmetric depolarizing channel.

**Comment by tonybruguier** [comment]
Yes, I would be happy to take this on. I probably can't get around to it until this weekend. Would that be ok?

**Comment by viathor** [comment]
Sure! That is completely fine.

Thank you for working on this! We really appreciate your help!

**Comment by tonybruguier** [comment]
Sent #3361

**Comment by viathor** [comment]
AFAICT, the only thing remaining before we can close this issue is the TODO in common_channels.py.

**Comment by tonybruguier** [comment]
I sent #3363 for review. No hurry at all.

**Comment by viathor** [comment]
I think this is done. Thank you, @tonybruguier ! :-)

**Comment by tonybruguier** [comment]
You're welcome. Thanks for letting me learn.
