### ISSUE TITLE
Add run_batch to Sampler interface

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#3224]
This would be similar to `run_async`, in that it simply defers to `run` or `run_sweep`, and should be overridden by parent classes that can sample batches more efficiently. It would be overridden in QuantumEngineSampler.

If this should be done, I'm willing to work on it.

**Comment by zaqqwerty** [comment]
Great to see this issue opened, wanted to say that for samplers intended to be used with TFQ, `run_batch` would be a really helpful addition to the API.

**Comment by balopat** [comment]
Discussed on Cirq Cynq - this sounds like a good idea. Please go ahead!
