### ISSUE TITLE
Classical Control: Classical Data Registers

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3231]
**Problem:** 
When running on hardware Cirq supports two uses of classical data.  The first is in the supplying of classical information to a circuit as a parameter.  The second is as the measurement outcomes recorded in the measurement dictionary.   This is not sufficient for future needs (see Feedforward #3232 and Flow Control #3234).  Further the output of running a Cirq circuit, measurement dictionaries, is overly restrictive and more general measurement results (IQ points, for example) should be supported.  Cirq also lacks the ability to specify classical data which can be loaded by a user, used during running of a circuit, and read out at the end of the circuit.  This feature is to add the ability to support classical data.

**Rough requirements:**

- Allow classical data of different types and sizes.
- Allow this data to be populated by hardware during measurement or execution of a circuit.
- Allow the data to be used to control in the future execution of a circuit
- Allow the data to be specified at runtime before a circuit executes.
- Allow the data to be read out and returned after the execution of the circuit, extending the measurement dictionary concept 
- Support only data that can be serialized
- Support serialization of the specification of the classical data itself

**Comment by smitsanghavi** [comment]
Should this be added to the 2021 roadmap given that it's the precondition for the above 3 linked issues?

**Comment by 95-martin-orion** [comment]
After further consideration, I don't think these concerns are relevant to Cirq outside of the built-in simulators:

- Allow [classical] data to be populated by hardware during measurement or execution of a circuit.
- Allow [classical] data to be used to control in the future execution of a circuit

Cirq constructs only really matter during translation from and to the Cirq format; any handling of measurement results during circuit execution is the sole responsibility of the device / simulator.

**Comment by mpharrigan** [comment]
@95-martin-orion is this before or after 1.0?

**Comment by 95-martin-orion** [comment]
This is functionally complete as of #4781.
