### ISSUE TITLE
Expand measurement results

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3233]
**Problem**: Cirq’s implementation of measurements is a model in which binary outcomes come from measurements in the computational basis.  There are a variety of cases in which measurements are more general than this.  For experimental implementation measurement results are often not just binary, but can correspond to more general floating point data, such as IQ points in superconducting qubits.  Another example is that the outcomes may be more rich, such as ternary outcomes.  Further measurements in Cirq are simple key value maps, but if measurements are to be used in feedforward or data flow, then these may need to be stored in classical registers and used later in a circuit.  Further there is inconsistent use of these measurement results in the results produced by simulators, samplers, and run methods.  

**Depends on:** Classical data (#3231). 
**Rough requirements:**

- Allow more than just binary values to be used for measurements
- Be compatible with solutions to classical data / feedforward.

**Comment by 95-martin-orion** [comment]
Between #4274 being resolved and #3868 being closed, I think this has been appropriately addressed. The only remaining open item is #3808, which has been marked post-1.0.
