### ISSUE TITLE
Classical Control: Subcircuits

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3235]
**Problem**: Cirq currently supports circuits, which are made of a series of moments, each moment is made up of different operations that act on disjoint sets of qubits.  These are meant to represent as closely as possible the execution of the circuit on hardware (the exception being that some gates are virtual and compiled out the circuit at runtime).  In addition there is the concept of a noise model, which, at runtime, adds on extra operations to a moment.  Stepping through a simulation with noise has the same iteration order as stepping through the moments, but with extra noise model operations per moment.  This feature would be to add some notion of grouping or subcircuits.  This is likely a necessary feature for the Flow Control issues listed above.  It would also be useful for compilation in order to delineate structures that could and could not be broken (in addition to the pragmas supplied by tags).  Such structures could presumably be used to replace noise models.

**Is coupled to feature:** Flow control (#3234), Feedforward (#3232)

**Rough requirements:**

- Add an abstraction to group portions of circuits
- Be able to deal with disjoint groups of qubits
- Maintain the ability to write unrolled moment by moment circuits
- Be flexible enough to supply information to executors which, may interpret the grouping as it executes the subgroup.
- Potentially be able to specify execution time information that can change the ordering of the execution
- Be serializable

**Comment by 95-martin-orion** [comment]
The core feature here has been resolved, and this is currently acting as an umbrella issue. The only remaining sub-issue marked for resolution before 1.0 is #3613; let's get that sorted and then reassign this to after 1.0.

**Comment by dstrain115** [comment]
This umbrella issue has been mostly or totally resolved.  Closing this issue.
