### ISSUE TITLE
Compiling: Compiling Building Blocks

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3239]
**Problem:** We currently handle compiling to a native gate set in an ad hoc manner.  In general the problem of compiling from one gate set to another is a difficult general problem.  However there may be places where we can provide various general methods for doing this gate compiling.  For example it is likely possible to support compiling general parameterized single qubit gates to simple parameterized gate sets.  There are also likely cases where this is true for some two qubit gate sets.

**Rough requirements:**

- Make a general single qubit parameterized gate set compiler.
- Identify other common gate compiling building blocks

**Comment by vtomole** [comment]
@tanujkhattar please leave a comment as to why this is closed.

**Comment by tanujkhattar** [comment]
This is closed in favour of more specific issues like adding support for 2 Qubit Heuristic Compilation (#4362) and refactoring `CircuitDag` and make it a useful IR that can be used for improving existing optimizers and potentially creating new optimizers (#4494)

This particular issue does mention any concrete work items and exploring useful compilation building blocks is an open ended research problem. We'd generally prefer having github issues that can be closed after getting a concrete item done.
