### ISSUE TITLE
Gatesets

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3243]
**Problem:** Cirq currently has no definition of a gateset outside of the serialized gate sets in cirq/google, which don’t really have a gate set that includes basic operations like testing for inclusion or creating new gate sets from older ones.  The serialized gate set also couples gatesets and serialization, which should be separate concerns. This feature would add a new concept to Cirq,  gatesets.  Gate sets would be like abstract sets, i.e. they should support contains, set equality and inequality, and set creation via operations like intersection, union, etc.  One would be able to test whether a gate, or a gate class, is in a gateset.  A complicating factor here is parameterized gates. Uses for gate sets include being able to specify gate sets for devices, separate from serialization, verifying that circuits are constructed entirely from gates in a gate set, and being the input and output of gate compilers.  

**Rough requirements:**

- Gate sets satisfying abstract set interface
- Testing gate inclusion in gate sets
- Allow devices to include gate sets which are validated by the device
- Be serializable such they can be read from a hardware provided device specification.

**Comment by tanujkhattar** [comment]
Approved RFC: https://tinyurl.com/cirq-gatesets

**Comment by tanujkhattar** [comment]
Work on Gatesets has been completed and we have `cirq.Gateset` and `cirq.GateFamily` abstractions now. There are couple of open issues for adoption of gate families for specific use-cases (like #4585), but those are tracked independently and this roadmap item can now be closed.
