### ISSUE TITLE
Devices: Hierarchy of devices

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3245]
**Problem:** For the validation component of a device, one often works with a standard connectivity of the device.  Currently these are hidden away in specific device implementations like ion trap, neutral atoms, contrib’s hypergraph devices, and the Google hardcoded devices and Google serializable device specifications.  Many of them couple durations with gate specifications.  This feature would be to commonize and systemize the base constructions for the geometric constraints of these devices and move them into Cirq proper.  Placement codes then could be specialized to work with particular versions of these types of devices, providing the necessary hooks to understand the geometric constraints of these systems.

**Depends on feature:** Separate concerns in devices (#3244)

**Rough requirements:**

- Define line device, grid device, graph device, and hypergraph device
- These should be easily definable from common data structures, i.e. for grid devices from text diagrams, for graph devices from networkx or adjacency matrices, etc.  It should also be possible to get these from the devices.

**Comment by balopat** [comment]
related #3020

**Comment by MichaelBroughton** [comment]
This has been resolved by the device refactor. Adding the `metadata.nx_graph` items alongside the device placement functionality in cirq workflow tools broadly captures the functionality here. We can re-open new issues if we have more specific concerns going forward.
