### ISSUE TITLE
Rename or refactor "study" module

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#3257]
Is it just me or is the name "study" confusing? I always forget what is and is not in it. Usually I confuse it with "value." Perhaps it makes sense to merge the two?

**Comment by balopat** [comment]
No objections on Cirq Cynque.

**Comment by thanacles** [comment]
@balopat I can work on this.  Since it would be a breaking change, should we deprecate the stuff in study?  I imagine flatten_expressions would go in params.

**Comment by balopat** [comment]
Thank you @thanacles - good question....
We might have to do this in two steps: 

1. rename `study` -> `params`: 
    a. add `deprecated_submodule` (see other examples in `cirq-core/cirq/__init__.py`) for it, with deprecation deadline 0.13. 
    b. Release v0.12, remove the deprecated submodule reference in v0.13.dev
3. move results out of `params`: 
    a.  create `results` package and point deprecation wrappers for param.Result and other attributes to the new package, deadline 0.14
    b.  release v0.13, remove the deprecated references in v0.14.dev

**Comment by kevinsung** [comment]
I'm fine with close this.
