### ISSUE TITLE
Sweeping repetition count of circuit fragment

### ISSUE THREAD

**Issue by viathor** [quantumlib/Cirq#3266]
**Is your feature request related to a use case or problem? Please describe.**

Oftentimes one has a circuit whose portion is to be repeated a number of times and one would like to sweep the repetition count. Example and context for this issue: implementing CPMG pulse train in cirq, see #3255.
 
**Describe the solution you'd like**

Current workaround entails parametrizing each repeated instance with a boolean parameter, so we end up with a number of parameters equal to the maximum of the repetition count. Ideally, we'd only need one parameter for this - repetition count.

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P2 - we should do it in the next couple of quarters

**Comment by balopat** [comment]
Related #3235

**Comment by balopat** [comment]
Discussed on Cirq Cynq, no objections - we just need to think through the design around this.

**Comment by balopat** [comment]
Subcircuits + loops should help in this 
cc @95-martin-orion

**Comment by 95-martin-orion** [comment]
`CircuitOperation` is pretty close to supporting this - all we need is to allow `repetitions` to take a `Symbol`, and for the parameter resolution methods to check `repetitions` for parameters.

Actually sending circuits with this feature to hardware is another matter; that behavior is tracked by #3634.

**Comment by daxfohl** [comment]
Requires #4888 or #4274

**Comment by daxfohl** [comment]
Added a "repeat_until" option to circuitoperation here: https://github.com/quantumlib/Cirq/compare/master...daxfohl:repeatuntil?expand=1, to go in after https://github.com/quantumlib/Cirq/issues/4274. That logic will also allow variable repetitions.

(Note if we also do #4884 we get this for free, as the symbolic repetition parameter and a repeat-until condition will be exactly the same thing).

**Comment by daxfohl** [comment]
@viathor #5043 will address this.
