### ISSUE TITLE
Prevent installing both cirq and cirq-unstable.

### ISSUE THREAD

**Issue by maffoo** [quantumlib/Cirq#3267]
**Is your feature request related to a use case or problem? Please describe.**

If `cirq-unstable` is installed in a virtualenv and you `pip install cirq`, the virtualenv gets into a bad state. This is because they are different packages with separate metadata, but they put the python code in the same location in a `cirq` folder in site-packages. So pip thinks both are installed but in fact only the most-recently installed package is "active".

If you try to fix such a situation by uninstalling one package, the code gets removed but pip still thinks the other package is installed. The other package is now in a broken state (can't be imported, etc.). The only way to recover is to uninstall _both_ packages and then install one of them again.

**Describe the solution you'd like**

I'd like `pip install cirq` to fail if `cirq-unstable` is installed, and vice-versa. I did a quick glance at setuptools docs to see if there is some way to specify packages that _must not_ be present, but I couldn't see anything. It also doesn't seem to work to add a package requirement like `cirq != *`. I'm not sure if there's any other mechanism we can use to accomplish this.

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle 

We have internal workarounds for this to try to keep people's virtualenvs in a good state if they accidentally install both versions, but it'd be great if we could prevent the problem from happening at all.

**Comment by balopat** [comment]
This sounds like a useful feature, I don't know immediately how to resolve it, but in theory it might be possible. Will flip to `triage/accepted` when we have a way to do this.

**Comment by balopat** [comment]
Idea: the problem is that `cirq-unstable` is a different package from `cirq`, while in reality is just a different version. 
Maybe we should publish [pre-releases](https://pip.pypa.io/en/stable/reference/pip_install/#pre-release-versions) to the cirq package from master, and then `pip install cirq --pre` would simply pull the latest pre-release version from pypi. 
Thoughts?

**Comment by maffoo** [comment]
I think we used to do something like that, but then changed to use a different package for the unstable releases instead. You're right that just having one pypi package would fix the problem and it's probably the "correct" way to do thing. I don't remember the reasoning for created a separate package, but perhaps @Strilanc or @dabacon can say more.

**Comment by balopat** [comment]
I posted a [question on SO](https://stackoverflow.com/questions/65097736/throw-error-from-setup-py-when-detecting-conflicting-package) about this after a bit of experimentation.

**Comment by balopat** [comment]
There is no way to implement this using the two separate packages. The main reason is that setuptools will build the wheel and the wheel has no means to specify post/pre install hooks. See [this SO answer](https://stackoverflow.com/questions/24263774/post-install-script-after-installing-a-wheel?lq=1).

The remaining options:

1. Embrace the different packages - in the end the whole tensorflow ecosystem embraced it with tensorflow and tf-nightly
2. Package is called `cirq` for both
   2.a: we publish daily 5-10 pre-releases to main cirq - I don't love this as it clutters the page
   2.b: we publish the dev cirq to a different repository, e.g. anaconda.org or test.pypi.org and then users will have to provide the `--extra-index-url` flag

**Comment by maffoo** [comment]
My instinct is to prefer 2a. I think 1 is going to get even harder in the future due to recent pip resolver changes where it tries to be more strict about installing dependencies, and 2b also makes life more difficult for anyone who want to use the pre-release versions.

If we needed to limit to just one nightly pre-release per day, that would probably be ok. People who need to track more granularly than that can always check out the source and build a wheel for themselves.

**Comment by balopat** [comment]
Sounds good, 2a it is - I'm going to merge tomorrow https://github.com/quantumlib/Cirq/pull/3527 unless no-one objects loudly :)
