### ISSUE TITLE
cannot import name from 'cirq.google'

### ISSUE THREAD

**Issue by mx73** [quantumlib/Cirq#3277]
**Description of the issue**
I'm doing some tutorial jupyter notebook, and I cannot import anything from `cirq.google`, not just `XmonSimulator`. I'm running lubuntu 18.04, python 3.8, jupyter_core 4.6.3, and cirq 0.8.2. What can I do?

**How to reproduce the issue**

```
from cirq import Simulator
from cirq.google import XmonSimulator
```

<details>
It returns

> ImportError                               Traceback (most recent call last)
> <ipython-input-7-102d70c9eca5> in <module>
>       4 
>       5 from cirq import Simulator
> ----> 6 from cirq.google import XmonSimulator
> 
> ImportError: cannot import name 'XmonSimulator' from 'cirq.google' (/home/doki/miniconda3/envs/mycirq/lib/python3.8/site-packages/cirq/google/__init__.py)

</details>

**Cirq version**
0.8.2

**Comment by balopat** [comment]
Thanks @vtomole  - based on @mx73's thumbs up, this seems to be the solution. Closing.
