### ISSUE TITLE
Refactor cirq.Moment to support efficiently finding operations by qubit

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#3278]
A common access pattern, when optimizing or analyzing a quantum circuit, is to check whether there is an operation at a particular place at a particular time. For example, when inserting into a circuit, finding the first moment that has no operation on certain qubits is necessary. cirq.Circuit supports efficient access by time, but not by place. This is fundamentally due to cirq.Moment being a list of operations.

I suggest that we refactor cirq.Moment (preserving backwards compatibility) to always have, or lazily create on demand, an internal dictionary mapping qubits to operations. This dictionary can then be used in other operations on moment, to give them better asymptotic guarantees.

**Comment by balopat** [comment]
Are you referring to roughly making this method cache its results? 

https://github.com/quantumlib/Cirq/blob/64939e53cfbbcf4984a254d3dc68690da9dd27de/cirq/ops/moment.py#L287-L295

```
cirq.Circuit(cirq.X.on(a), cirq.Y.on(b), cirq.X.on(a))[0][a]
```
works nicely: 

```
cirq.X(cirq.LineQubit(0))
```

Also xref #3145.

**Comment by wingers** [comment]
Hi @balopat, I'd like to work on this.

**Comment by balopat** [comment]
You got it @wingers! Thanks for taking it on!
