### ISSUE TITLE
"Number of circuits and sweeps must match" -- run_batch

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#3285]
I have a list of non-parameterized, non-sweepy circuits and thought I could just not pass `params_list` but it insists that it be of equal length to the number of circuits. 

1. the default value shouldn't be `None` if that doesn't actually work (?)
2. can I pass a list of `None`s? can we make this happen automatically?

**Comment by kevinsung** [comment]
I agree that users shouldn't be forced to pass parameters. It should just work.
