### ISSUE TITLE
Fix all latex expressions without enclosing $ signs

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3286]
We should fix all latex expressions that have no $ sign around them. I found one in channel: https://github.com/quantumlib/Cirq/blob/master/cirq/protocols/channel.py

In the new devsite both the inline (single $) and paragraph ($$) latex works so we should make sure we use them!

**Comment by TanveshT** [comment]
Hey, @balopat while addressing this issue I tried testing the `$` symbol inline and even for paragraphs apparently it is not working on my local machine. Can you suggest any solution for this? The `$` are getting printed as normal text.

**Comment by balopat** [comment]
Hi @TanveshT thanks for taking a stab at this! There is no easy way to do this just yet. The devsite (our new site in the works based on the tensorflow.org engine) engine is not available externally yet, and the sphinx (our old and current site) does not support the latex conversion (and we won't invest in it). 

So the only way to fix this will be to manually copy paste the formulae to double check that they make sense for example in the channel.py case you could use hackmd.io: https://hackmd.io/HYSbEqOrTMCEqRadAXtxEQ

**Comment by TanveshT** [comment]
Okay @balopat I will look into it and fix it asap.

**Comment by rheaparekh** [comment]
Hi @balopat, I made the corresponding changed needed for this issue. However, I forgot to first claim the issue. I don't think I saw anyone working on this, so is it fine if I go ahead and make a pull request?

**Comment by balopat** [comment]
Awesome, thank you @rheaparekh, yes please open the PR!

**Comment by balopat** [comment]
This is done.
