### ISSUE TITLE
Make optimizers consistent: in-place vs functional

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3290]
We have both @dabacon to comment on the details.

**Comment by mpharrigan** [comment]
I think this refers to the circuit-transforming optimizers and whether they should modify a circuit in place or return a copy with the desired modifications.

As a point of evidence, in ReCirq qaoa experiment I wrap all circuit transformers into a functional version with `mutate=False` as a default keyword argument: https://github.com/quantumlib/ReCirq/blob/master/recirq/qaoa/gates_and_compilation.py#L670

**Comment by balopat** [comment]
Cirq Cynque discussion: 

- slight preference towards functional direction. 
- we should have consistency
- only one standard way should exist 
- deprecation is going to be a bit tricky

**Comment by daxfohl** [comment]
This approach is especially nice when combined with pipeline operators. IDK if there's a way to do that in python. (Mostly F# background).

**Comment by MichaelBroughton** [comment]
Transformers superceed this. Always returns new circuit. Closing.
