### ISSUE TITLE
simulator benchmark interface/object

### ISSUE THREAD

**Issue by alexandrupaler** [quantumlib/Cirq#3293]
**Is your feature request related to a use case or problem? Please describe.**

Simulating a circuit should give feedback resource statistics used during simulation.

**Describe the solution you'd like**

An object that can be populated by simulator interfaces and returned with simulator calls.

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P1 - I need this no later than the next release (end of quarter) -- but this does not mean Cirq has to implement it
P3 - it is an idea I'd like to discuss / suggestion based on principle

**Comment by balopat** [comment]
Thanks for filing @alexandrupaler! This sounds interesting - what kind of resource statistics are you looking for specifically?

**Comment by balopat** [comment]
Discussed at Cirq Cynq: 
* due to the specificity of each simulators this would be hard to abstract out into an interface
* even within simulators this is a hard problem to exactly measure - estimation is more typical (e.g. see quimb) than explicit measurement

**Comment by Ashalynd** [comment]
Suggestion: consider using https://docs.python.org/3/library/resource.html , which provides information about system resources used by a program.
