### ISSUE TITLE
Move random circuits to ReCirq

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#3327]
The circuits in 
`generate_boixo_2018_supremacy_circuits_v2.py`
feel much more like they belong in ReCirq than in cirq.google

**Comment by balopat** [comment]
Agreed!

**Comment by mpharrigan** [comment]
I think this refers to [cirq.experiments.google_v2_supremacy_circuit](https://github.com/quantumlib/Cirq/commits/master/cirq/experiments/google_v2_supremacy_circuit.py) rather than the above named file in `cirq.google`.

**Comment by mpharrigan** [comment]
xref https://github.com/quantumlib/Cirq/pull/2235

**Comment by mpharrigan** [comment]
xref #3775

**Comment by dstrain115** [comment]
This doesn't sound too difficult, and between Matt and I, we should move this to ReCirq before 1.0
