### ISSUE TITLE
`cirq.num_qubits` protocol on Gate classes

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#3341]
I would like to use the `cirq.num_qubits` protocol on gate classes

```python
cirq.num_qubits(cirq.X)
>>>1

cirq.num_qubits(cirq.XPowGate)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-50-ac8f0eb43a74> in <module>
----> 1 cirq.num_qubits(cirq.XPowGate)

~/cirq/cirq/cirq/protocols/qid_shape_protocol.py in num_qubits(val, default)
    158     """
    159     num_getter = getattr(val, '_num_qubits_', None)
--> 160     num_qubits = NotImplemented if num_getter is None else num_getter()
    161     if num_qubits is not NotImplemented:
    162         return num_qubits

TypeError: _num_qubits_() missing 1 required positional argument: 'self'

```

cc @cduck 

**Cirq version**
HEAD

**Comment by mpharrigan** [comment]
Thing being Python, you can do the following underhanded thing:

```python
cirq.XPowGate._num_qubits_(None)
>>> 1
```

**Comment by cduck** [comment]
What would the protocol do for gates like MeasurementGate that take a variable number of qubits to `__init__`?

If you decorate `_num_qubits_` with `@staticmethod` or `@classmethod` it might just work.

**Comment by mpharrigan** [comment]
For variable qubit gates, then the `default` argument will come into play and by default default raise a TypeError.

I agree with your diagnosis that those decorators could do the trick

**Comment by satw1knandala** [comment]
I can work on this if no one else is on it already. Let me know @balopat @cduck @mpharrigan

**Comment by dstrain115** [comment]
This actually works now.  Closing this issue.
