### ISSUE TITLE
FSIM_GATESET should support FSimGate(0, pi)

### ISSUE THREAD

**Issue by mrwojtek** [quantumlib/Cirq#3345]
**Is your feature request related to a use case or problem? Please describe.**
Use case: it supports CZ gate but not FSimGate(0, pi), which is the same.

**Describe the solution you'd like**
Support FSim(0, pi)

**[optional] Describe alternatives/workarounds you've considered**

**[optional] Additional context (e.g. screenshots)**

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P1 - I need this no later than the next release (end of quarter)

**Comment by mrwojtek** [comment]
Please hold on with this feature (it might not be a Cirq issue in the end but a bug of some kind). I'll update this later.

**Comment by balopat** [comment]
Sounds good - thanks Wojtek

**Comment by mrwojtek** [comment]
In the end, everything seems to be alright on the Cirq side!
