### ISSUE TITLE
Physical Z length may be incorrect in the documentation

### ISSUE THREAD

**Issue by btchiaro** [quantumlib/Cirq#3354]
**Description of the issue**

In the documentation the physical z is listed as having a typical length of 12 ns: https://github.com/quantumlib/Cirq/blob/master/docs/google/devices.md#physical-z-gates

I believe that the physical z is typically 10 ns long, with 5 ns pads before and after.

**Comment by btchiaro** [comment]
@dstrain115

**Comment by balopat** [comment]
Discussed on Cirq Cynque: 
 - This should be changed to 20ns + we should mention that this is subject to change 
 - when we can retrieve this from the device, we should have a snippet retrieving gate lengths

**Comment by dstrain115** [comment]
Sure, I will take care of this shortly.

We can retrieve gate lengths, but the problem is that some gates have multiple different durations depending on parameters (z can be 0 or 20ns and Fsim can be 0, 12 or 32)
