### ISSUE TITLE
_write_annotations in cirq.vis.Heatmap produces wrong result

### ISSUE THREAD

**Issue by crystalzhaizhai** [quantumlib/Cirq#3356]
**Description of the issue**
_write_annotations method adopted the mesh.get_paths() which groups edges together to find the cells to be annotated. Under certain use cases, the method would group the wrong edges together that forms "empty cells" instead of the correct cells.

To reproduce the wrong result, use an input contain has empty cells.

```
def _write_annotations(self, mesh: mpl_collections.Collection,
                           ax: plt.Axes) -> None:
        """Writes annotations to the center of cells. Internal."""
        for path, facecolor in zip(mesh.get_paths(), mesh.get_facecolors()):
            # Calculate the center of the cell, assuming that it is a square
            # centered at (x=col, y=row).
            vertices = path.vertices[:4]
            row = int(round(np.mean([v[1] for v in vertices])))
            col = int(round(np.mean([v[0] for v in vertices])))
            annotation = self.annot_map.get((row, col), '')
            if not annotation:
                continue
            face_luminance = relative_luminance(facecolor)
            text_color = 'black' if face_luminance > 0.4 else 'white'
            text_kwargs = dict(color=text_color, ha="center", va="center")
            text_kwargs.update(self.annot_kwargs)
            ax.text(col, row, annotation, **text_kwargs)
```

**Cirq version**
0.9.0 dev

**Comment by balopat** [comment]
Hi @crystalzhaizhai, thank you for filing the issue! Can you provide a small code to reproduce the issue you are seeing?

**Comment by crystalzhaizhai** [comment]
@balopat Sorry just saw the comment! I opened this bug per @pingyeh 's request. Do you have a immediate example at hand?

My current [implementation](https://github.com/quantumlib/Cirq/pull/3351) took out this part of code and adopted a different solution.

@pingyeh mentioned in our 1:1 that he wants to fix this bug and add rendering to the graph in this quarter. Please let me know if you are still interested in working on this.

**Comment by balopat** [comment]
Got it, thanks for the clarification - I'm marking it as triage/accepted.

**Comment by tanujkhattar** [comment]
`cirq.vis.Heatmap` has been refactored. I'm closing this for now. Please reopen / file a new bug if find any error in the new implementation.
