### ISSUE TITLE
float32 parameters leads to significant performance loss of parameter resolver

### ISSUE THREAD

**Issue by therooler** [quantumlib/Cirq#3359]
**Description of the issue**
Calling `cirq.resolve_parameters` to resolve the parameters of a symbolic circuit with `np.float32` parameters leads to a significant performance loss. I ran into this bug while working on loading circuit parameters from a `.npy` file on [this TensorQuantum Dataset PR](https://github.com/tensorflow/quantum/pull/304). Verifying that the circuits produced the expected wave functions took ~30 minutes on the CI, since we have to check hundreds of circuits. On further investigation, I discovered that the parameters were 32-bit, and casting them to 64-bit decreased the parameter resolve time by a large margin.

**How to reproduce the issue**

```python

import cirq
import sympy
import time
import numpy as np
from collections import namedtuple
import matplotlib.pyplot as plt


def unique_name():
    """Generator to generate an infinite number of unique names.

    Yields:
        Python `str` of the form "theta_<integer>".

    """
    num = 0
    while True:
        yield "theta_" + str(num)
        num += 1


def time_resolve_param(dtype, nspins, max_depth):
    depth_grid = list(range(2, max_depth, 2))
    times = []
    for depth in depth_grid:
        qubits = cirq.GridQubit.rect(nspins, 1)

        # Symbolic parameters
        name_generator = unique_name()
        symbol_names = [next(name_generator) for _ in range(depth)]
        symbols = [sympy.Symbol(name) for name in symbol_names]

        # Random values with dtype
        params = np.random.randn(2 * depth).astype(dtype)
        params = dict(zip(symbol_names, params.flatten()))

        # Define the circuit.
        circuit = cirq.Circuit(cirq.H.on_each(qubits))
        zipped_qubits = list(zip(qubits, qubits[1:]))
        for d in range(depth):
            for q1, q2 in zipped_qubits:
                circuit.append(cirq.ZZ(q1, q2)**(symbols[d]))

        # Resolve parameters and time
        resolve_start = time.time()
        param_resolver = cirq.resolve_parameters(circuit, params)
        t_param = time.time() - resolve_start
        times.append(t_param)

    return depth_grid, times


if __name__ == "__main__":
    NSPINS = 10
    MAXDEPTH = 50
    grid, times_32 = time_resolve_param(np.float32, NSPINS, MAXDEPTH)
    _, times_64 = time_resolve_param(np.float64, NSPINS, MAXDEPTH)

    plt.plot(grid, times_32, label='np.float32')
    plt.plot(grid, times_64, label='np.float64')
    plt.xlabel('circuit depth')
    plt.ylabel('time (s)')
    plt.legend()
    plt.grid()
    plt.show()


```
This produces the following figure

![float32_vs_float64_paramresolver](https://user-images.githubusercontent.com/32705838/94204975-4edbe100-fe90-11ea-9d2a-630f10e31aba.png)

As we can see, with increasing circuit depth the time it takes to resolve the 32-bit parameters creates a massive slowdown.

**Cirq version**
Cirq 0.8.2

**Comment by maffoo** [comment]
There's a special case in `resolve_parameters` to handle floats: https://github.com/quantumlib/Cirq/blob/master/cirq/study/resolver.py#L93. It currently checks `isinstance(value, float)` which on 64-bit python seems to be True for `np.float64` but False for `np.float32`:
```
In [1]: isinstance(np.float64(1), float)                                                                 
Out[1]: True

In [2]: isinstance(np.float32(1), float)                                                                 
Out[2]: False
```
Perhaps instead we could for example expand the list of types, or do something like `isinstance(value, numbers.Number)`.

**Comment by therooler** [comment]
Right. But than integers also make it through, I don't know if that will lead to unexpected behavior.
```
isinstance(1, numbers.Number)
>>> True
```

Changing it to `isinstance(value, (float, np.float32))` would solve the issue I had. Alternatively, the `resolve_parameters` docstring could mention that we expect Python `float` or `np.floatx` on x-bit python. It's kind of a fluke that I stumbled upon this, just because I accidentally stored parameters as `np.float32` when I'm on 64-bit Python.

**Comment by balopat** [comment]
Adding https://github.com/quantumlib/Cirq/pull/3366 - I think the conservative solution here to add np.float32 is a fine 
incremental step. I opened a PR to add this in #3366.

I would be open to create a more generic solution which matches and returns number literals, maybe relying on `numbers.Number` - One of the problem with `numbers.Number` is that it matches things like `sympy.S.NegativeOne`, so we'll have to think a bit harder to introduce that level of generic support.

**Comment by balopat** [comment]
I have a fix that provides pass-through for `numbers.Number` instances and the sympy constants.

The speedup is there now for np.float32 as well: 

![image](https://user-images.githubusercontent.com/635073/94633252-c186fb00-029a-11eb-863a-e73b772ded24.png)

**Comment by therooler** [comment]
Great!
