### ISSUE TITLE
Use pydata_google_auth instead of colab for Engine auth

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3368]
# Problems
Using google-colab as the dependency is problematic because: 
 - On jupyter locally we have issues because of exactly google-colab: #3318 
 - it has all sorts of issues with python 3.8 
 - it's heavyweight

# Recommendation 

I'd suggest using instead pydata_google_auth for auth. It is light weight and works on both colab (installed by default) and jupyter notebooks (we can install it as part of the notebook).

```python
# The Google Cloud Project id to use.
project_id = 'your project' #@param {type:"string"}

def setup_auth():
  """Runs the user through the Google OAuth process """
  try: 
     import pydata_google_auth
  except: 
     !pip install pydata_google_auth
  import pydata_google_auth
  return pydata_google_auth.get_user_credentials(
    ['https://www.googleapis.com/auth/cloud-platform'],
  )


print("Getting OAuth2 credentials.")
print("Press enter after entering the verification code.")
credentials = setup_auth()
print("Authentication complete.")

try: 
    import cirq 
except:     
    !pip install cirq

print("Cirq is installed.")

import cirq

# Create an Engine object to use, providing the project id and the args
# used for authentication (produced by running the authentication above).
engine = cirq.google.Engine(project_id=project_id, service_args = {'credentials': credentials} )
```

# Caveat

This creates a global var called "credentials" which is an OAuth2 token. This might be undesirable, we can try to hide it and work with the `GOOGLE_APPLICATION_CREDENTIALS` env var - which is a bit better as the user's code won't have direct access to the creds - it needs to read the creds file which the env var is pointing to. 

_Originally posted by @balopat in https://github.com/quantumlib/Cirq/pull/3365#r497614032_

**Comment by balopat** [comment]
cc @dstrain115 wdyt?

**Comment by dstrain115** [comment]
I think this is fine.  It is a BSD-3 clause license, which I think is okay, but it might be worth checking out to verify that this is an acceptable license.

**Comment by balopat** [comment]
The problem I have with pydata_google_auth is that it uses PyData for the consent screen which is unfamiliar for the users. 
![image](https://user-images.githubusercontent.com/635073/97620988-8124b500-19df-11eb-8c06-203ca9a8ae9f.png)

Colab uses Google Cloud SDK which is also different from the Quantum Computing Service. @dstrain115 have we ever thought of creating an oauth consent page for QCS? I guess I can look into that.

**Comment by dstrain115** [comment]
Can we just warn the user that they will have to authenticate via pydata?

**Comment by balopat** [comment]
Thanks for the follow-up idea - I should have captured this - based on our chat on Friday I will do the following: 

I will make the colab auth conditioned on colab being detected. Otherwise it will assume "advanced" usage and won't help with the interactive login. I'll make this very clear in the comments in the cells. If the jupyter user is not logged in, they will get DefaultCredentialsError. We can also catch that error within the cell and add some more context and instructions if we feel that it's needed.

Yes we could just warn the user about the pydata consent screen - but I'm not too hot on pydata anymore. It introduces yet another third-party library as dependency and it would require passing the credentials explicitly to `cirq.google.Engine`.

I'm going to close this issue for now - we can reconsider it in case we/users don't like the new version.
