### ISSUE TITLE
Setup docstring linting 

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3388]
**Is your feature request related to a use case or problem? Please describe.**

Docstrings are a returning issue on PRs, it would be great if we could automate the feedback on them as well for Google style docstrings.

**Describe the solution you'd like**

Setup the [docstyle](http://pylint.pycqa.org/en/latest/technical_reference/extensions.html#pylint-extensions-docstyle) and [docparams](http://pylint.pycqa.org/en/latest/technical_reference/extensions.html#pylint-extensions-docparams) plugins. 

**What is the urgency from your perspective for this issue? Is it blocking important work?**
P2 - we should do it in the next couple of quarters

**Comment by divya-mohan0209** [comment]
@balopat :  I'd like to help out in this endeavour since I've some experience in RTD & Sphinx.  Would you still be needing help?

**Comment by balopat** [comment]
Hi @divya-mohan0209 - that would be great! Our .pylintrc lives under dev_tools/conf. We are following Google style.  Please raise a PR and we can discuss the breakages and how to fix them, which flag to turn on or off!

**Comment by thanacles** [comment]
The new PR for this issue is: https://github.com/quantumlib/Cirq/pull/4267

**Comment by thanacles** [comment]
OK, an incremental linter was too intrusive as it requires a significant refactor for even individual files.  I vote for @balopat 's Idea to  use `# pylint: disable=missing-raises-doc` for all the cases where the refactor is not trivial.

**Comment by balopat** [comment]
Sounds good to me! :) Thank you for bearing with us through this!

**Comment by thanacles** [comment]
This is follow up from discussion on PR #4345

@mpharrigan @balopat Maybe we should go through the docparams lint rules and decide which ones we actually want. Here they are with notes:

differing-param-doc (W9017) - "%s" differing in parameter documentation Please check parameter names in declarations.
10 occurrences

differing-type-doc (W9018) - "%s" differing in parameter type documentation Please check parameter names in type declarations.
0 occurrences

multiple-constructor-doc (W9005) - "%s" has constructor parameters documented in class and __init__ Please remove parameter declarations in the class or constructor.
0 occurrences

missing-param-doc (W9015) - "%s" missing in parameter documentation Please add parameter declarations for all parameters.
In a current PR, reviewers have said this would be useful

missing-type-doc (W9016) - "%s" missing in parameter type documentation Please add parameter type declarations for all parameters.
38 occurrences

missing-raises-doc (W9006) - "%s" not documented as being raised Please document exceptions for all raised exception types.
Already implemented

useless-param-doc (W9019) - "%s" useless ignored parameter documentation Please remove the ignored parameter documentation.
0 occurrences

useless-type-doc (W9020) - "%s" useless ignored parameter type documentation Please remove the ignored parameter type documentation.
0 occurrences - no cost and some benefit

missing-return-doc (W9011) - Missing return documentation Please add documentation about what this method returns.
218 occurrences

missing-return-type-doc (W9012) - Missing return type documentation Please document the type returned by this method.
105 occurrences

missing-yield-doc (W9013) - Missing yield documentation Please add documentation about what this generator yields.
118 occurrences

missing-yield-type-doc (W9014) - Missing yield type documentation Please document the type yielded by this method.
64 occurrences

redundant-returns-doc (W9008) - Redundant returns documentation Please remove the return/rtype documentation from this method.
12 occurrences

redundant-yields-doc (W9010) - Redundant yields documentation Please remove the yields documentation from this method.
1 occurrence

**Comment by dabacon** [comment]
This has created 13 pages of files with TODOs!  I'm going to start hacking on them, it's a good way for me to read code that has been added since I stopped paying as much attention :)
