### ISSUE TITLE
LaTeX output requires amsmath?

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#339]
I'm not sure if this is an issue but the latex would not compile unless I imported the package `amsmath` due to the use of the control sequence `\text`. Is the `\text` necessary?

**Comment by dabacon** [comment]
https://texfaq.org/FAQ-mathstext

I don't think requiring amsmath is onerous (it's pretty standard), and it seems that \text is the best solution.  I'm going to close unless someone really objects and has a better solution.
