### ISSUE TITLE
Fix validate_normalized_state requiring complex64

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#3394]
~~Inconsistent use of np.complex64 vs np.complex128 results in undesirable behavior such as~~

Calling `validate_normalized_state` fails despite not specifying a required dtype: 

```python
state = cirq.testing.random_superposition(4)
cirq.validate_normalized_state(state, qid_shape=(2, 2))
```
giving a ValueError:
```
ValueError: state_vector has invalid dtype. Expected <class 'numpy.complex64'> but was complex128
```

**Comment by kevinsung** [comment]
We should probably use complex64 due to space and time savings. The drawback is that numpy uses complex128 by default, so users creating numpy arrays using numpy will either have to tell numpy to use complex64, or tell Cirq that they are using complex128.

**Comment by Strilanc** [comment]
To me it looks like the bug here is "validate" assuming complex64 is required, instead of only doing that if the user asks for it.

**Comment by satw1knandala** [comment]
hi, I can tackle this. please assign me if you need it

**Comment by kevinsung** [comment]
@satw1knandala I've already submitted #3428, which fixes this.
