### ISSUE TITLE
NEQR example request in Cirq for QIMP

### ISSUE THREAD

**Issue by sgangoly** [quantumlib/Cirq#3406]
Hi Gurus, 

I am trying out Quantum Image Analysis for quantum machine learning classification of Gravitational Lenses. 

NEQR reference:  https://link.springer.com/article/10.1007/s11128-013-0567-z

The first step would be to try to use NEQR (as FRQI is good only for grey scale) for 256 RGB to process the image. Hence, I was wondering if there would be any known NEQR code samples in Cirq around please? 

The nest step will trying to use TensorFlow Quantum to classify them...

Shall appreciate any kind guidance. 

With sincere gratitude

santanu

**Comment by vtomole** [comment]
Hey @sgangoly , I don't have access to that article.

**Comment by sgangoly** [comment]
Hi @vtomole , it appears also to be downloadable from researchgate: https://www.researchgate.net/publication/257641933_NEQR_A_novel_enhanced_quantum_representation_of_digital_images

**Comment by vtomole** [comment]
@sgangoly Thanks for the accessible link.

**Comment by Strilanc** [comment]
The answer to your question is that there isn't a NEQR example in cirq. We'd be open to a code sample being contributed to the docs. Although it sounds like in your case the sample may be more appropriate for tensorflow quantum.

I'm going to close this as "question answered".
