### ISSUE TITLE
MatrixGate

### ISSUE THREAD

**Issue by rezah** [quantumlib/Cirq#3408]
Is there any way to transform an arbitrary two-body MatrixGate into given logical raw gates? and or in an approximate way. It seems the decomposition class does not work here.

**Comment by balopat** [comment]
Thank you for your question @rezah! We prefer taking questions on Quantum StackExchange - we also monitor that for `cirq` tags - it serves really well as a searchable database for knowledge.

To answer it: You should look at `cirq.two_qubit_matrix_to_operations` for the raw unitary of your MatrixGate. It uses the KAK decomposition to decompose it to two-qubit and one-qubit gates.

**Comment by balopat** [comment]
I'm going to assume that this helped. Please reopen, comment if you need more information.
