### ISSUE TITLE
Single qubit clifford XZ decomposition is missing two Cliffords

### ISSUE THREAD

**Issue by zchen088** [quantumlib/Cirq#3411]
**Description of the issue**
See title

**How to reproduce the issue**

```python
import cirq.experiments.qubit_characterizations as ceqc
print(len(ceqc._single_qubit_cliffords().c1_in_xz))  # should be 24, but is 22
```

**Cirq version**
0.9.0.dev

**Comment by maffoo** [comment]
In addition, is possible to change the XZ decomposition to use ZXZ instead of XZX so that each clifford has at most 1 microwave gate?
