### ISSUE TITLE
Add Github new issue workflows for more issue types

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3412]
We have templates for feature requests and bugs.

I think we should have templates for:
- kind/docs (Documentation bug or feature request) 
- kind/design-issue (Design discussions that are not yet feature requests) 
- kind/health (Issues related to technical debt, testing, release, etc.) 
- kind/deprecation (An issue to deprecate a feature) 
- kind/task (contributors only)

**Comment by dstrain115** [comment]
We have a generic issue template, and I don't think we get enough issues to write templates for each type.  Closing this issue.
