### ISSUE TITLE
Enable CI job for testing commits on master

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3413]
When we migrated to Github Actions we did did not add the tests on master to the workflows. While most issues are supposed to be caught on the checks on each PR and we don't merge without the branch being up to date with master, I think it still can serve some purpose to run these tests on the actual commits to have final proof that everything is passing on master. In my experience in some rare cases issues can still happen on master - especially if someone accidentally pushes to master directly, or some other esoteric scenarios involving Github problems.

The second part of this is that the build status badge on our README points to an old Travis build - we should point to the new build status instead.

**Comment by mpharrigan** [comment]
@MichaelBroughton is this still relevant?

**Comment by mpharrigan** [comment]
@MichaelBroughton bump
