### ISSUE TITLE
DLL not found (Installation on Windows)

### ISSUE THREAD

**Issue by apassenger** [quantumlib/Cirq#3421]
Dear All,

I tried to install cirq on windows as described here: https://cirq.readthedocs.io/en/stable/docs/install.html#installing-on-windows

And the library succefully installed but I cannot import cirq. When I tried "import cirq"  I am getting "DLL not found" error

How can I solve my problem?

Best regards

**Comment by balopat** [comment]
Thanks for filing @apassenger - can you please provide more details? I could not reproduce the issue:

![image](https://user-images.githubusercontent.com/635073/96275623-cdefa100-0f86-11eb-9ace-ec7aa37ec82a.png)

It would be great to know the exact error message. 
Also the python version you are using and what `pip list` shows.

Thanks!

**Comment by apassenger** [comment]
Hello,
Thanks for your answer and sorry for my late answer. Here are my all messages:
![er1](https://user-images.githubusercontent.com/25195538/96349769-72becb00-10ba-11eb-8a15-d5c2d3705a49.PNG)
![e2](https://user-images.githubusercontent.com/25195538/96349772-794d4280-10ba-11eb-8fd3-d6eb471adfd5.PNG)

**Comment by vtomole** [comment]
@apassenger Looks that error is in `matplotlib`. Try downgrading your version of `matplotlib` and try again like https://stackoverflow.com/questions/24251102/from-matplotlib-import-ft2font-importerror-dll-load-failed-the-specified-pro.

**Comment by apassenger** [comment]
Hello,
Thanks a lot :) 
I needed to upgrade matplotlib, after that I have 3-4 similar error and I did the same thing for the other libraries and now it is working 
Thanks again and I am closing to issue :)
