### ISSUE TITLE
Installing Cirq on Windows 10

### ISSUE THREAD

**Issue by apassenger** [quantumlib/Cirq#3441]
Hello,
I al trying to install cirq for Window 10 and Installation was completed successfully. However I have some import error:
What is the problem?

**Comment by apassenger** [comment]
Sorry I tought I added images but I cannot upload any images via GitHub
Here my error images: https://ibb.co/6vMRK6n

**Comment by apassenger** [comment]
Ok I don't know what is this problem and how I can fix it but I log in Windows 10 with another user so It is for me ok

**Comment by balopat** [comment]
This seems to me an environment issue. Can you do `pip install --force-reinstall -U cirq` and try again?

**Comment by balopat** [comment]
> Ok I don't know what is this problem and how I can fix it but I log in Windows 10 with another user so It is for me ok

How did you install things? If different users have different experience, then it might be that the original installation ended up in some sort of privileged location that not all users have access to. Does the user that works have admin rights? Does the other one not? Anyway, this clue points to an environment issue as well. 

Another thing I would try is the [`--user` flag](https://stackoverflow.com/questions/42988977/what-is-the-purpose-of-pip-install-user) with pip install. 

I hope this helps, please report back the results - I'd love to capture the learnings in our getting started guide for Windows!

**Comment by balopat** [comment]
Finally another clue - as this is scipy related maybe forcing a downgrade will help based on this [SO thread](https://stackoverflow.com/questions/62566691/error-when-loading-scipy-oserror-winerror-126-the-specified-module-could-not)
