### ISSUE TITLE
Should an IonDevice accept any qubit type?

### ISSUE THREAD

**Issue by rmlarose** [quantumlib/Cirq#3447]
Some docstrings ([here](https://github.com/quantumlib/Cirq/blob/master/cirq/ion/ion_device.py#L26)) state qubits are one a line, while others ([here](https://github.com/quantumlib/Cirq/blob/master/cirq/ion/ion_device.py#L42)) state qubits are identified by their x, y location. I believe the latter is a typo due to the [annotation](https://github.com/quantumlib/Cirq/blob/master/cirq/ion/ion_device.py#L34).

If so, should `__init__` raise an error if the input qubits are not `LineQubit`s? (The `at` and `neighbors_of` methods assume `LineQubit`s.)

**Comment by balopat** [comment]
I agree - I think we should expect `LineQubit`s - now we have an ion-computing expert, @dabacon can you chime in?

**Comment by dabacon** [comment]
@dabacon was off talking to money people but now he is back and much happier to not have to listen to quantum hype.

LineQubit makes the most sense, even though there is all to all connectivity, when addressing in hardware it makes sense to address on a line.  

The documentation has been fixed, but probably good to be defensive and throw a TypeError in the constructor.
