### ISSUE TITLE
How to apply for access to Google Hardware?

### ISSUE THREAD

**Issue by josealvarez97** [quantumlib/Cirq#3471]
Sorry for asking here, but the documentation is rather obscure on this topic (https://cirq.readthedocs.io/en/latest/docs/google/access.html). How do I apply for access to Google Hardware. In particular, access to Google Cloud's Quantum Engine API. (IBM's Quantum Lab is rather accessible, so I wonder why Google's Quantum Engine isn't.)

I am an undergraduate student at Minerva Schools at Keck Graduate Institute who would like to explore a capstone project that relates to quantum software. Any help/advice is highly appreciated.

**Comment by karlunho** [comment]
Hi,

We are currently testing our service with a very limited set of collaborators. I recommend you to check out cirq, and experiment with qsim for your undergraduate project. Using qsim, you should be able to simulate up to 30 some qubit on a beefy workstation.

**Comment by josealvarez97** [comment]
Thanks @karlunho, I will do that.
