### ISSUE TITLE
Fix testing for example notebooks

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3502]
We should lift the fidelity estimation notebook into our regular docs/tutorials folder.

Currently it's also untestable as it fails with:

```
Exception encountered at "In [2]":
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-8c00c9255350> in <module>
      2 import cirq
      3 from cirq.contrib.svg import SVGCircuit
----> 4 import examples.direct_fidelity_estimation as dfe
      5 
      6 qubits = cirq.LineQubit.range(3)

ModuleNotFoundError: No module named 'examples'
```

**Comment by unaiic** [comment]
@balopat Lifting the notebook is trivial, but where can the `direct_fidelity_estimation.py` file be put? This is the only place where an `import example.Something` is done. I don't see a good place for it to be imported. However, I don't know whether removing the notebook is an option either.

**Comment by tonybruguier** [comment]
Also affecting stabilizer_code if #3935 gets accepted.

**Comment by dstrain115** [comment]
All of these notebooks are automatically tested in the nightly docs build.  I think this bug is obsolete.
