### ISSUE TITLE
PointOptimizationSummary results in an infinite loop

### ISSUE THREAD

**Issue by wjy99-c** [quantumlib/Cirq#3511]
**Description of the issue**
When I set `clear_span` to negative, `PointOptimizationSummary` result in an infinite loop
**How to reproduce the issue**

```

return cirq.PointOptimizationSummary(
    clear_span=-1,
    clear_qubits=op.qubits,
    new_operations=[
        cirq.X.on_each(*op.qubits),
        cirq.X.on_each(*op.qubits),
        cirq.CZ(*op.qubits),
    ]
)

```

It also happens when I set `clear_qubits` to some unregistered qubits. I think it should give an exception instead of running endlessly.

**Cirq version**
0.9.0

**Comment by 95-martin-orion** [comment]
Thanks for filing this issue! I agree that the right solution here would be to validate the values of `clear_span` and `clear_qubits` in the `PointOptimizationSummary`. You're welcome to open a PR with the fix, or one of our maintainers should get to it within a week.

**Comment by BillGatesNephew** [comment]
Should `clear_span` allow for `0` to be a valid value? Also @wjy99-c, do unregistered qubits here refer to qubits that are just not in the set of qubits acted on by the operations in the parameter `new_operations`?

**Comment by wjy99-c** [comment]
Should `clear_span` allow for 0 to be a valid value? -> Seems the program also run endlessly for `0`
For the unregistered qubits, I mean:

```
            return cirq.PointOptimizationSummary(
                clear_span=1,
                clear_qubits=(cirq.GridQubit(2,1),cirq.GridQubit(1,2)),
                new_operations=[
                    cirq.X.on_each(*op.qubits),
                    cirq.X.on_each(*op.qubits),
                    cirq.CZ(*op.qubits),
                ]
            )
```
With
`input_qubits = [cirq.GridQubit(i, 0) for i in range(qubit_count)]`

**Comment by BillGatesNephew** [comment]
Adding the check for `clear_span <= 0` was easy enough, but I'm not familiar enough with `PointOptimizationSummary` to be sure how to check for these unregistered qubits other than seeing if they're in the qubits acted on by the `new_operations`. Looks like @Strilanc was the original author of this class; maybe he can offer some insight?

**Comment by balopat** [comment]
The `PointOptimizer` class itself is the main consumer for the `optimization_at` method, and that's the only context that knows about the Circuit instance itself. We could do the validation at this line: https://github.com/quantumlib/Cirq/blob/a0ee113f0f776242263f75822bc4cebadd85a0bc/cirq/circuits/optimization_pass.py#L144 or even better, we could have a `self._validated_optimization_at` method that does the assertions on the implemented `optimization_at` method - and we would call the validated version in `optimize_circuit`.

**Comment by mpharrigan** [comment]
@tanujkhattar do you want to take this

**Comment by 95-martin-orion** [comment]
`PointOptimizationSummary` is deprecated in favor of Transformers.
