### ISSUE TITLE
Consider adding StateVectorMixin to ProductState, _NamedOneQubitState

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3517]
StateVectorMixin provides a couple of useful features on the state vector itself. `ProductState` and `_NamedOneQubitState` and its subclasses could benefit from it. 

cc @mpharrigan wdyt?

**Comment by mpharrigan** [comment]
The mixin uses `qubit_map` which is designed for a vector (aka ndarray) based representation so you can map qubits to indices in a contiguous array. ProductState is like a dictionary (so this isn't applicable) and NamedOneQubitState only has one qubit (per its name (it's also named per its name)).

Is `StateVectorMixin` used anywhere? Either "no" or my pycharm is broken :)

**Comment by vtomole** [comment]
According to @viathor , this points to a more general problem of Cirq not having a philosophy with which to make technical decisions when it come to state representation. He'll file an issue about this.
