### ISSUE TITLE
Functionality decoupling for "_strat_commutes_from_operation"

### ISSUE THREAD

**Issue by akushnarov** [quantumlib/Cirq#3529]
Move "commutes" check from the protocols to the "Operation" class.
- Now: "_strat_commutes_from_operation" is a part of [commutes_protocol.py](https://github.com/quantumlib/Cirq/blob/master/cirq/protocols/commutes_protocol.py)
- Should be: part of "\_commutes\_" in [ops.Operation](https://github.com/quantumlib/Cirq/blob/master/cirq/ops/raw_types.py)
(This is related to the #3274) 

P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle

**Comment by balopat** [comment]
This sounds like a good idea in principle, but maybe there was a reason that it lives in the protocol module. Would you like to try if it will work on the Operation class? It should be quick to try to make all the tests pass.

**Comment by akushnarov** [comment]
Hey @balopat, I did some research and here is the following output:
- it's possible to move the logic from `_strat_commutes_from_operation` to the Operation class (with some adjustments)
- if the functionality is moved, the tests from `protocols/commutes_protocol_test.py` fail (the reason is not in the moved code itself)

The reason of test fail is in the  class "GateOperation" which implements `_commute_` with the `self.gate._commutes_on_qids_`:
`
def _commutes_(self, other: Any,
                   atol: float) -> Union[bool, NotImplementedType, None]:
        return self.gate._commutes_on_qids_(self.qubits, other, atol=atol)
`
but that method itself does nothing, but returns NotImplemented:
`
def _commutes_on_qids_(self, qids: 'Sequence[cirq.Qid]', other: Any,
                           atol: float
                          ) -> Union[bool, NotImplementedType, None]:
        return NotImplemented
`

**So my suggestion would be**:
- move the `_strat_commutes_from_operation` functionality to the Operation
- remove `_commute_` from the `GateOperation` (anyway it does nothing)
- adjust the tests

**Comment by vtomole** [comment]
@akushnarov 

What is gained by this change?

**Comment by akushnarov** [comment]
Hi @vtomole 

- _Reason for having this request_: Moving the Operation's `_commute_` functionality from the general "commute strategy" (which should not know anything about object types and should only orchestrate the commute logic) to the Operation class (where the commute functionality should be controlled)

- _What is done in the [code](https://github.com/quantumlib/Cirq/pull/3548)_: 1) Moved the functionality from the strategy to Operation class; 2) Adjusted depending class (especially GateOperation), which didn't have correctly implemented `_commutes_` (it returned `NotImplemented` in any case); 3) Adjusted code formatting according to the git pull request checks (e.g. cirq/ops/pauli_string.py)

- _What is gained?_: Code decoupling. Easier code management and debugging for the commute functionality. From my point of view each class should contain information about commute logic by itself and commute strategy should only take care of the smooth `cirq.commute(...)` functionality (orchestrate).

**Comment by akushnarov** [comment]
Hey @vtomole, just curious if you need anything else from my side?

**Comment by vtomole** [comment]
Hey @akushnarov, i just saw this. I've been very busy with other things and will be for the foreseeable future. @balopat, can you see this through?

**Comment by balopat** [comment]
Hey guys, sure, I'll have a look - thanks @vtomole for the feedback so far and @akushnarov for taking this on!

**Comment by akushnarov** [comment]
Back to work here

**Comment by akushnarov** [comment]
Fixed and merged here: https://github.com/quantumlib/Cirq/issues/3695
