### ISSUE TITLE
Notebooks: incorrect URLs to QuantumLib site

### ISSUE THREAD

**Issue by nlbao** [quantumlib/Cirq#3541]
**How to reproduce the issue**
* Open a notebook, for example: https://github.com/quantumlib/Cirq/blob/master/docs/gates.ipynb
* Look for the ***"View on QuantumLib"*** link --> it incorrectly points to https://www.example.org/cirq/....

**Cirq version**
0.10.0.dev

**Comment by balopat** [comment]
Thanks for noticing, this is intended. It is a temporary situation - we are working on a new site, so these are placeholders - sorry for the confusion!
