### ISSUE TITLE
Expression-to-symbol maps in ParamResolver are ignored

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#3550]
**Description of the issue**

Mapping expressions to symbols in `ParamResolver` is ignored during resolution. Expressions to values, however, work as expected - at least for basic cases. 

**How to reproduce the issue**

Expressions to values:
```
a, b, c, d = [sympy.Symbol(x) for x in 'abcd']
r = cirq.ParamResolver({a: b + c, b + c: 2})
cirq.resolve_parameters(a, r)  # returns 2
```

Expressions to symbols:
```
a, b, c, d = [sympy.Symbol(x) for x in 'abcd']
r = cirq.ParamResolver({a: b + c, b + c: d})
cirq.resolve_parameters(a, r)  # returns b + c, not d
```

**Additional comments**

I'm not convinced that there's an active use case for this behavior that couldn't be achieved with e.g. `{a: b + c, b: d - c}`. My recommendation here would be to only allow symbols in the key list for ParamResolvers.

**Cirq version**

0.10.0.dev

**Comment by viathor** [comment]
I agree we should only allow symbols and not expressions as keys.

Expression keys seem to have a poor cost/benefit ratio. Specifically, on one hand there don't seem to be many compelling use-cases and on the other any practical implementation is likely to fail to be completely general leading to arbitrary and unclear scope of what is and isn't handled.
