### ISSUE TITLE
Docs build is failing

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3554]
Since the black formatter merge the RTD builds are failing with some weird pip error:

https://readthedocs.org/projects/cirq/builds/

Need to look into it and resolve it if the error is on our end or report it to the RTD team if it's on their end.

**Comment by maffoo** [comment]
Could this be an issue with the new dependency resolver in pip 20.3? It was just released today and changes the default dependency resolver, which has been causing problems in various places.
