### ISSUE TITLE
Expose Kraus operator selection in simulators

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#3566]
**Is your feature request related to a use case or problem? Please describe.**

For debugging purposes, it would be useful for the operator selected in Channels and Mixtures to be exposed to the user.

**Describe the solution you'd like**

Allow Channels and Mixtures to specify a measurement key for which simulators can populate results. Among other things, this is consistent with the treatment of `is_measurement` as a method for checking whether an operator is deterministic.

Ideally, this could look like this bad pseudocode-y example:
```
circuit = cirq.Circuit(
  cirq.Channel(
    [cirq.X(a), cirq.Y(a), cirq.Z(a), cirq.I(a)],
    key='xyzi')
)

results = simulator.run(circuit)
results['xyzi']  # contains one of {0, 1, 2, 3} depending on the operator selected
```

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P1 - needed for trajectory simulation, which is planned for end of Q1 2021

**Comment by 95-martin-orion** [comment]
For context: the probabilities of each operator in a `Channel` are dependent on the state vector when the operator is applied, whereas the probability of applying each operator in a `Mixture` is hardcoded by the user.

Sadly, this naming is confounded by `DepolarizingChannel` and similar objects, which despite their names are actually `Mixtures`.

**Comment by 95-martin-orion** [comment]
Duplicate of #1357.

**Comment by viathor** [comment]
Should we close this issue or #1357? This has a better description, so close #1357?

**Comment by 95-martin-orion** [comment]
Keeping this issue, though #1357 has some good historical details around the `measurement_key` protocol.

**Comment by balopat** [comment]
I realized that this is basically part of the roadmap item: #3241
