### ISSUE TITLE
Docs: Quantum operator representations

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3575]
I think it would be great for our users to have a page or extend some of our pages in our documentation describing the different kind of representations we have for operators and what features each have and how they interrelate. 

Currently the list would be: 
- Unitary operators: gate/operation + unitary protocol 
- Quantum channels: 
    - channel protocol - good for quantum trajectory simulations and noise models 
    - mixture protocol for unitary mixtures - which is good for performance as the probabilities are not state dependent  
- Measurement: 
    - MeasurementGate 
    - [future] Channel with measurement keys 
- Observables: 
    - PauliString - for pure paulis, that are closer to experimentally viable measurements
    - PauliSum - for convenience of summing up expectation values from PauliStrings, also to represent arbitrary operators in the Pauli basis
    - Observable measurement framework 

And then if we introduce butterfly (Dirac?) operators - they would be a sparse representation for arbitrary operators relying on the Dirac formalism, where you can capture things like projectors. 

We should also capture where there are nice interoperability between these representations - e.g. PauliSum and PauliString and Dirac operators can be added and multiplied together.

**Comment by rmlarose** [comment]
I like this idea, especially concerning observables where (to my knowledge) examples are a bit lacking. PauliSum's and PaulSumCollector's could even be used in some existing tutorials on variational algorithms, if desired.

**Comment by balopat** [comment]
ref https://github.com/quantumlib/Cirq/issues/1550

**Comment by balopat** [comment]
Discussed on Cirq Cynque: this will be very helpful in mapping theoretical understanding to the framework.
