### ISSUE TITLE
Rewrite complicated checks in python

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3577]
Python should be more maintainable and testable than bash. This issue is about replacing complicated logic in bash scripts with testable python code. This would remove the necessity of dev_tools/bash_scripts_test.py as well, which is a bit brittle as it depends on the output of the scripts.

**Comment by pavoljuhas** [comment]
For now it seems less work to patch potential bugs in `check/something-changed` scripts than to redo their logic in Python.
That said, some scripts could be replaced with a direct checking tool execution.

Closing.  Superseded by #6800
