### ISSUE TITLE
cirq._compat.proper_repr and numpy arrays of datetimes

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#3582]
Currently, `cirq.compat.proper_repr` of a numpy array of datetimes cannot be evaluated because the `dtype` argument is not valid python

```python
a = np.array([datetime.datetime.now()], dtype=np.datetime64)
Out[6]: array(['2020-12-03T16:27:03.422008'], dtype='datetime64[us]')

# Current proper_repr
"np.{}".format(a.dtype)
Out[8]: 'np.datetime64[us]'

# possible change
"np.{!r}".format(a.dtype)
Out[9]: "np.dtype('<M8[us]')"
```

This would be a breaking change and could make reprs less pretty:

```python
b = np.ones(4)
"np.{!r}".format(b.dtype)
Out[11]: "np.dtype('float64')"
"np.{}".format(b.dtype)
Out[12]: 'np.float64'
```

---

A bigger issue is whether we should have repr be a full serialization format. Most other Python projects don't do this. In fact, we have to use our own repr for numpy arrays because numpy (helpfully!) will truncate large arrays. Dataclasses should autogenerate reprs, but it doesn't use the fully qualified name of the class (i.e. `cirq.Thing`).

We've sortof hitched our wagon to the star of verbose-repr in the JSON serialization test. However, in the past I had some success with putting whatever single-line code I want in the json_test_data/*.repr files instead of the actual result of a `repr()` call. ~~I don't know if this still works or if a check has been introduced to outlaw this~~ I verified that there's no check that `repr()` matches `*.repr`.

**Comment by Strilanc** [comment]
Can we check for datetime when producing the repr, and special case the dtype?

I feel pretty strongly about reprs being pastable into a REPL to get test cases.

**Comment by balopat** [comment]
From the [python docs for `__repr__`](https://docs.python.org/3/reference/datamodel.html#object.__repr__): 

> If at all possible, this should look like a valid Python expression that could be used to recreate an object with the same value (given an appropriate environment). If this is not possible, a string of the form <...some useful description...> should be returned.

I believe that we are in the former category. I also like Craig's suggestions regarding special casing the dtype - it is totally possible as an option number 4 in https://github.com/quantumlib/Cirq/pull/3374/files/5925b8aff6ffaa1c2d94d9e43850cc816f65c939#r538956429 - which wouldn't break anyone as the datetime dtypes are broken currently anyway. 

Happy to discuss it more on Cirq Cynq today.

**Comment by mpharrigan** [comment]
We discussed at Cirq Cync and there was some appetite for potentially truncating numpy arrays that are too big but much less appetite for falling back on numpy and dataclasses' default reprs and removing some of the `cirq.` prefixing. 

> Can we check for datetime when producing the repr, and special case the dtype?

I have done this in #3374 

It was also noted that my complaining about friction writing Cirq reprs was noted and I'm at liberty to bring it up again if I run into it again.
