### ISSUE TITLE
Consider representing negative loops differently in CircuitOperations

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3613]
It's great to see the loop number in the diagram! 

However, repetition allows for negative numbers - it gets a bit weird to interpret that - what should we do there? 

```
0: ───X───@───────────────────────────────────────────
          │
          │   Circuit_0x3e1e26fbfddf8277:
          │   [ 1: ───X───@───          ]
1: ───Y───X───[           │             ]─────────────
              [ 2: ───Y───X───          ]
              [                         ]
              [ 3: ───Z───────          ](loops=-4)
              │
2: ───Z───────#2──────────────────────────────────────
              │
3: ───────────#3──────────────────────────────────────
```

Maybe print the circuit in reverse + reverted operations? As that's what is happening under the hood. 
Or we can explicitly say † , inverse or ^-1 somewhere in the header?

_Originally posted by @balopat in https://github.com/quantumlib/Cirq/pull/3580#discussion_r542641437_

**Comment by 95-martin-orion** [comment]
See #3605 for discussion on out-of-line subcircuit diagrams, which may be able to share the format we decide on here.

**Comment by 95-martin-orion** [comment]
Child of #3235

**Comment by 95-martin-orion** [comment]
This looks like a diagram-formatting issue, which I'm inclined to punt to after 1.0. @dabacon, do you see part of this that needs resolved before then?
