### ISSUE TITLE
Handle recursive parameter resolution in CircuitOperation

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#3619]
**Is your feature request related to a use case or problem? Please describe.**

Child of #3235.

CircuitOperation implicitly relies on single-step parameter resolution for its internal parameter mappings. This is inconsistent with the default behavior of `ParamResolver`, which is to resolve parameters recursively (see PR #3538).

**Describe the solution you'd like**

`CircuitOperation` should accept `resolve_parameters(..., recursive=True)` and handle it in a manner consistent with `ParamResolver` (within reason).

**[optional] Describe alternatives/workarounds you've considered**

Disabling recursive resolution for CircuitOperation (current behavior)

Changing default resolution behavior to single-step

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P2 - we should do it in the next couple of quarters

**Comment by mpharrigan** [comment]
Discussed at cirq cync. Default to single step and keep the error message would be a minor breaking change but the behavior would be most predictable

**Comment by daxfohl** [comment]
Would it be better to have the handlers for parameter resolution be `_resolve_parameter_` (singular) that takes a single kvp, and the calling protocol function itself responsible for the looping? Also possibly should parameters be specified as a kvp sequence instead of a dictionary, so that the ordering is explicit? (Granted python 3.6 and up dictionaries are ordered, but still).

**Comment by daxfohl** [comment]
I was thinking this would be a quick fix, but I assume it's not or it would've been done already. Do you have any thoughts on the matter that you can note here?

By `recursive` does that mean it would have to recur through the subcircuit operations, or does it just mean recurring through the local symbols of the CircuitOperation, (or does it mean both)?

**Comment by 95-martin-orion** [comment]
> I was thinking this would be a quick fix, but I assume it's not or it would've been done already. Do you have any thoughts on the matter that you can note here?

I haven't looked at this in a while, but discussion on #3538 demonstrates why this is potentially complicated. In summary:

- CircuitOperation currently expects single-step resolution (e.g. `{a: b, b: a}` maps a to b and b to a)
- This is in direct conflict with recursive resolution behavior (where `{a: b, b: a}` throws an infinite-loop error)
- Changing over in a backwards-compatible way potentially affects many `_resolve_parameters_` calls

A breaking change could probably resolve this; at the time, we opted to keep things stable. You're welcome to take a look, especially given #5016 (which I agree stems from this).
