### ISSUE TITLE
[docs] SimulatorStep.set_state doesn't exist

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3623]
See the question on : https://quantumcomputing.stackexchange.com/questions/15187/access-and-set-state-during-quantum-computation-simulation-in-cirq

1. This part of the docs is pointing to a set_state() method wrongly, instead it should be `set_state_vector()`. 
2. Also, we should point to the API docs when referencing methods.
3. set_state_vector should get some docsstrings - it's a public method

![image](https://user-images.githubusercontent.com/635073/102815142-c2529900-4380-11eb-8a58-d24df828aa5f.png)

**Comment by unaiic** [comment]
@balopat You are referring to [this ](https://github.com/quantumlib/Cirq/blob/7a335e3ef297057b4a12f7c21d4e8dd426b44ca0/cirq/sim/sparse_simulator.py#L367)one, right? I can work on this.

**Comment by balopat** [comment]
Yes! Great, thank you @unaiic - it's all yours!

**Comment by unaiic** [comment]
@balopat Thank you. I have a question:
> 2. Also, we should point to the API docs when referencing methods.

This applies to all notebooks or only to this one?
