### ISSUE TITLE
ParallelGateOperation does not support JSON serialization

### ISSUE THREAD

**Issue by chiefnoah** [quantumlib/Cirq#3624]
**Description of the issue**

`ParallelGateOperation` does not appear to support json serialization using `cirq.to_json`.

**How to reproduce the issue**

```python
import cirq
circuit = cirq.Circuit()
qubit_a = cirq.NamedQubit('a')
qubit_b = cirq.NamedQubit('b')
pgo = cirq.ParallelGateOperation(gate=cirq.Y, qubits=[qubit_a, qubit_b,])
circuit.append(pgo)
text = cirq.to_json(circuit)

# `TypeError: Object of type ParallelGateOperation is not JSON serializable`
```
**Cirq version**

0.9.1

**Comment by balopat** [comment]
Thanks for opening the issue @chiefnoah! I put in a quick fix, you should be able to use it with `pip install cirq --pre`.
