### ISSUE TITLE
Update chemistry notebook to latest OpenFermion/PySCF versions

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3627]
#3626 pinned openfermion and openfermionpyscf as a temporary fix. 
This issue is to update the notebook based on the latest version of the API.

**Comment by balopat** [comment]
cc @rmlarose - will you have bandwidth to fix this?

**Comment by rmlarose** [comment]
Can do!

**Comment by rmlarose** [comment]
Question for @ncrubin or @kevinsung 

Most API changes are very small except for the [variational energy calculation](https://quantumai.google/cirq/tutorials/educators/chemistry#variational_energy_calculation) section, in particular the line

```python
import openfermioncirq as ofc

ansatz = ofc.LowRankTrotterAnsatz(hamiltonian)
```

The [ofc.variational](https://github.com/quantumlib/OpenFermion-Cirq/tree/master/openfermioncirq/variational) module was not copied over when merging OpenFermion-Cirq into OpenFermion (https://github.com/quantumlib/OpenFermion/pull/619#issue-455358865). Is there a new equivalent of the `ofc.LowRankTrotterAnsatz` in OpenFermion? Or should this section be removed from the docs now?

**Comment by kevinsung** [comment]
@rmlarose Indeed, we decided to scrap the old ofc.variational module, and there is no equivalent of ofc.LowRankTrotterAnsatz in OpenFermion, so that section of the docs should be removed.
