### ISSUE TITLE
Efficient proto serialization of FrozenCircuit

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#3634]
**Is your feature request related to a use case or problem? Please describe.**

Part of #3235.

PR #3480 added a lookup table for constants in the circuit proto. Extending this table to more complex objects should help reduce the amount of network traffic required when using Quantum Engine.

**Describe the solution you'd like**

FrozenCircuits are a prime candidate for storing in the constants table, as they are often fairly large and may be repeated several times within a circuit.

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P2 - we should do it in the next couple of quarters

**Comment by 95-martin-orion** [comment]
Blocked on #3678. Workarounds are possible, but messy.

**Comment by 95-martin-orion** [comment]
It should be noted that proto serialization of `FrozenCircuit` - efficient or not - is currently unavailable, as the serializers have no assigned behavior for handling `CircuitOperation`. Decomposing the circuit in advance avoids this issue, but also removes all of the intended benefits of using `CircuitOperation`s in the first place.

**Comment by 95-martin-orion** [comment]
It may be possible to enable more general proto compression with tools provided by gRPC: [SetCompressionLevel](https://grpc.github.io/grpc/cpp/classgrpc_1_1_server_builder.html#ae10c6dc23ec295695710c0b4c14f9353)

**Comment by maffoo** [comment]
I wonder if we should consider making a v3 proto format to handle subcircuits, instead of trying to force them into the current format which has various problems? If we do want to ahead with adding support in v2, then I think we can work around #3678 in this particular case fairly easily, by checking for `CircuitOperation` explicitly before we check `op.gate` to pick a serializer. This seems like a fairly natural special case since `CircuitOperation` is so different from other operations.

**Comment by 95-martin-orion** [comment]
> I wonder if we should consider making a v3 proto format to handle subcircuits, instead of trying to force them into the current format which has various problems?

It seems like v3 proto is still a topic under discussion, and may take some time to be fully realized. In order to make subcircuits available to QCS as soon as possible, I plan to continue work on this, but please keep me in the loop on the v3 proto plans.

**Comment by 95-martin-orion** [comment]
As described in #4336, this issue is now effectively resolved; however, additional proto optimizations are still possible.

**Comment by 95-martin-orion** [comment]
> As described in #4336, this issue is now effectively resolved; however, additional proto optimizations are still possible.

Due to backwards-compatibility issues with QCS, this was rolled back. A roll-foward is under development.

**Comment by dabacon** [comment]
Marked as before, but could be after if there is no core code that needs to be changed.

**Comment by 95-martin-orion** [comment]
This has been demonstrated to work and documented in #5221.
