### ISSUE TITLE
To be confirmed: Inconsistency in controlled gate unitary between v0.8.2 and v0.9.1

### ISSUE THREAD

**Issue by Kee-Wang** [quantumlib/Cirq#3636]
I found the unitary after applying `.cotrolled()` on `rz` behaves differently for version v0.8.2 and v0.9.1 which causes trouble.

The simplest code that that reproduce this issue on my computer is:
```
import cirq
import numpy as np

rz = cirq.rz(np.pi)
crz= rz.controlled()
u = cirq.unitary(crz)
print(u)
```

If I run this on v0.8.2, I got 
```
[[0.-1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.-1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.-1.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+1.j]]
```

If I run with v0.9.1, I got
```
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.-1.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+1.j]]
```

Can anyone else reproduce this issue? 

The former converted the control into `CZPowGate` and the later is simply a controlled version of `ZPowGate`. 

If I understand it correctly, controlled `ZPowGate` is turned into `CZPowGate` only when at least the global shift of `ZPowGate` is 0, as shown [here](https://github.com/quantumlib/Cirq/blob/d58423a3f06dd0a40fd8acfdd006d9a876274a7c/cirq/ops/common_gates.py#L515-L560), but the phase of a `Rz` is -0.5 not 0 so it should never be turned into a `CZPowGate`, is that right?

What is even more confusing is that I did not see any changes of `controlled` method for version v0.8.2 and v0.9.1 so I would naively believe they should behave the same.

**Comment by smitsanghavi** [comment]
Just to confirm, the latter behavior is correct as we should not be converting `rz.controlled` to `CZPowGate`. The behavior change you mention above was intentional, #3113. 

Is the main question that v0.8.2 and v0.9.1 have identical code for this part?

**Comment by Kee-Wang** [comment]
> Just to confirm, the latter behavior is correct as we should not be converting `rz.controlled` to `CZPowGate`. The behavior change you mention above was intentional, #3113.
> 
> Is the main question that v0.8.2 and v0.9.1 have identical code for this part?

Thanks for the confirmation.  Are you asking if I used the same Python code I showed above, but with different Cirq versions? Then yes I did. I ran the identical Python code with different Cirq versions.

Also would you agree with the following sum up for the people who might get confused by definitions of gates? 
The `cirq.rz(theta).controlled()` is implemented in:
1. v0.8.2 as:
```
[[1,0,0,0]
 [0,1,0,0],
 [0,0,1,0],
 [0,0,0,g]]
```
where `g = exp(i·theta)`. This is implemented via [`CZPowGate`](https://quantumai.google/reference/python/cirq/ops/CZPowGate). 

2. v0.9.1 as:
```
[[1,0,0,0]
 [0,1,0,0],
 [0,0,a,0],
 [0,0,0,b]]
```
where `a = e^{i·theta/2}` and `b = e^{- i·theta/2}`. This is implemented via a controlled method of [`ZPowGate`](https://quantumai.google/reference/python/cirq/ops/ZPowGate).

The update of definition for the `rz.controlled` from v0.8.2 to v0.9.1 was intentional since the later is the correct one.

**Comment by smitsanghavi** [comment]
That's correct. I'll close the issue for now, please reopen if any of your questions were unanswered.
