### ISSUE TITLE
Devices: Full Clifford group gates support

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3639]
**Feature**: Full Clifford group support

**Problem**: Currently Clifford group gates are supported via the addition of the _act_on_ to gates in Cirq (this is a work in progress).  This means only certain gates can be simulated.  One could instead support the entire Clifford group via it’s specification of a symplectic matrices plus a vector describing the phases of the Pauli group.  In addition this would include better support for the Pauli group and stabilizer groups to the level of supporting NISQ quantum error correction work (error mitigation)

**Rough requirements:**

* Define general clifford group gates
* Use in clifford simulators but also in normal simulations
* Make clean support for Pauli group and stabilizer codes.

**Comment by smitsanghavi** [comment]
Prior discussion on similar lines (I think): https://github.com/quantumlib/Cirq/issues/2423#issuecomment-606522903

For the record, we already support detecting arbitrary 2x2 unitaries as Clifford or not (as the fallback strategy if the `_act_on_` method isn't implemented). Generalizing this to larger unitary matrices was considered too expensive at the time.

**Comment by 95-martin-orion** [comment]
@MichaelBroughton is this resolved as of #4791?

**Comment by 95-martin-orion** [comment]
Confirmed with Mike, this is complete.
