### ISSUE TITLE
Visualizations: States, devices, gates

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3642]
**Feature**: State, device, gate visualizations

**Problem**: Currently there is a visualization of state vectors as a bar graph, but very little to visualize states or results.  This feature would be to provide these visualizations.  In addition there are visualizations specific to device characterizations: the coupling heatmap as well as integrated histograms.  

**Rough requirements:**

- Bloch sphere, density matrix visualizations
- Coupling heatmaps and integrated histogram visualizations for metrics.
- Kak decomposition visualizations

**Comment by tanujkhattar** [comment]
RFC: https://tinyurl.com/cirq-visualizations

**Comment by 95-martin-orion** [comment]
Cirq sync: this is complete...enough. We can open new issues if more visualizations are needed.
