### ISSUE TITLE
Fix styling in 404 RTD page + potential smart redirect

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3648]
The redirect pages on readthedocs are missing styling. 
E.g.: https://cirq.readthedocs.io/en/stable/generated/cirq.PauliString.expectation_from_state_vector.html
![image](https://user-images.githubusercontent.com/635073/103953741-89901f00-50f7-11eb-9d5d-f6625af628f2.png)

This should be easy to fix. The other issue is that for reference docs the user now have to find that same page in the new structure. Maybe we could add some Javascript magic to extract the target page from the current URL and do a JS based redirect instead of the HTML based one.

**Comment by tonybruguier** [comment]
I think I can repro.

It seems the index page has the right path, but not the 404 one:
```
/google/.../github/Cirq [03:45 PM]$ cat rtd_docs/_build/html/index.html  | grep style
      <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
      <link rel="stylesheet" href="_static/css/theme.css" type="text/css" />
      <link rel="stylesheet" href="_static/tweak-style.css" type="text/css" />
```
versus:
```
/google/.../github/Cirq [03:45 PM]$ cat rtd_docs/_build/html/404.html | grep style
      <link rel="stylesheet" href="/en/latest/_static/pygments.css" type="text/css" />
      <link rel="stylesheet" href="/en/latest/_static/css/theme.css" type="text/css" />
      <link rel="stylesheet" href="/en/latest/_static/tweak-style.css" type="text/css" />
```

I am not sure why.

**Comment by dabacon** [comment]
I'd like to see if we can get a redirect working as part of the launch.

**Comment by dstrain115** [comment]
@dabacon It looks like the redirect is working to the quantum AI homepage (there's just a five second delay).  RTD has been deprecated for over a year now, so I don't think it's worth fixing styling or making a smart redirect.  I vote we close this issue.

@dabacon If you agree, can you close this?

**Comment by dabacon** [comment]
yep
