### ISSUE TITLE
CircuitOperation doesn't enforce FrozenCircuit

### ISSUE THREAD

**Issue by jarthurgross** [quantumlib/Cirq#3651]
**Description of the issue**

Part of #3235.

`cirq.CircuitOperation` happily takes a `cirq.Circuit` as input to its constructor, but then has issues due to the fact that it's not a `cirq.FrozenCircuit`.

**How to reproduce the issue**

```
>>> import cirq
>>> q = cirq.LineQubit(0)
>>> circuit = cirq.Circuit(cirq.X(q))
>>> circuit_op = cirq.CircuitOperation(circuit)
>>> print(circuit_op)
AttributeError: 'Circuit' object has no attribute 'serialization_key'
>>> frozen_circuit_op = cirq.CircuitOperation(cirquit.freeze())
>>> print(frozen_circuit_op)
0: ───Circuit_0xfbab027cc6c20e45:───
      [ 0: ───X───              ]
```

**Cirq version**
0.10.0.dev

**Comment by smitsanghavi** [comment]
I can add the validation and throw a TypeError
