### ISSUE TITLE
Add docstring for `cirq.QasmOutput`

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#3658]
**Is your feature request related to a use case or problem? Please describe.**
The use case is documentation.

**Describe the solution you'd like**
Basically something like the docstring used here: https://github.com/quantumlib/Cirq/blob/d58423a3f06dd0a40fd8acfdd006d9a876274a7c/cirq/circuits/qasm_output.py#L86

**What is the urgency from your perspective for this issue? Is it blocking important work?**

We should do it in the next couple of quarters

**Comment by unaiic** [comment]
I'd like to work on this. If I understand correctly, docstring for the constructor of `cirq.QasmOutput` is missing, right?

**Comment by vtomole** [comment]
@unaiic That's right. Thanks for picking this up!
