### ISSUE TITLE
Proposal: cirq.circuits.immutable

### ISSUE THREAD

**Issue by daxfohl** [quantumlib/Cirq#3668]
**Is your feature request related to a use case or problem? Please describe.**

The core data classes of cirq are based on a mutable OO class hierarchy. This feature request offers to replace or augment these with an immutable variant.

A number of the issues we come across in cirq are, I don't want to say "caused by mutable / OO inheritance structure", but at least less likely to occur or simpler to solve in a more functional framework. Some examples:

* #3290: Inconsistent optimizers
* #3246: Circuit construction
* #2775: Circuit as simple container
* #2164: Deprecate TwoQubitGate/ThreeQubitGate
* #1246: Change insert methods to preserve moments
* Several more....

Additionally, several of the feature requests and roadmap items in the pipeline are features that map well to functional programming:

* #3242: Gate relationships
* #3238: Circuit transformer organization
* #3235: Subcircuits
* #1859: Methods to return common sets of gates
* #2072: Gate AST
* #1409: How do we make translation and simulation fit
* #970: Transform to parameterized circuit
* #935: Optimization algorithm abstraction
* etc.

**Describe the solution you'd like**

* We make the core classes: Qubit, Gate, Moment, Circuit immutable, based on immutable data structures.
  * These objects will expose "mutators" that return a new object rather than updating the original.
  * The "mutators" will be kept to the bare minimum needed to support the basic mutations of object.
  * Higher-level mutations (e.g. `insert_batch`) can then be extracted to external "builder" classes such that our core data classes remain unpolluted.
* These core classes should expose the same **read** interface as the existing mutable classes.
  * This will allow them to be used interchangeably with the simulators.
* Optimizers will need to be rewritten to return copies rather than modify-in place.
  * This will resolve the consistency issue #3920.
* We should have a pipelining operator that will make builder/optimizer syntax clean.
  * Ideally something like Elm/F#/Elixir: `build_circuit(my_gates) |> append(other_gates) |> optimize_push_z |> align_left`.
  * (Closest I see in Python would be like `pipe(build_circuit(my_gates), append(other_gates), optimize_push_z, align_left)`).

The advantage here is that once this is finished, the core data classes will all be simple, self-contained, and we'll likely rarely have to touch them again. All "logic" can be extracted to functions external to the core classes. This reduces the need to worry about whether you may have broken something that the class or some child class depends on.

**[optional] Describe alternatives/workarounds you've considered**

None of the above *requires* immutability. We can fine-tune our class hierarchies and possibly get rid of most of the problems.

Concerns are numerous:

* Python doesn't have a strong ecosystem around immutability (I think)
* Immutability usually comes with performance impact. Circuits are relatively small though.
* Full backwards compatibility will be a challenge.

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle.

**Comment by mpharrigan** [comment]
Discussed at cirq cync; most things are already immutable(ish). @daxfohl to go through and find specific stragglers

**Comment by daxfohl** [comment]
I'm closing this. The scope is too broad, and, as mentioned, most stuff is already immutable. There may be some targeted things we can do like creating "mutator" functions for the frozen circuit. But those can be raised as needed on their own.
