### ISSUE TITLE
Cirq tutorial ?

### ISSUE THREAD

**Issue by mertbozkir** [quantumlib/Cirq#3676]
**Is there any cirq video tutorial ?**

**I don't know where to ask this questions. If it's wrong I can close this issue.**

**My problem is: I didn't find any video tutorial for Cirq. I want to learn this framework, but I don't know where to start**

**If any experts here, What would you suggest/recommend ?**

**Comment by 95-martin-orion** [comment]
Hi @mertbozkir,

I'm not aware of any video tutorials for Cirq, but the [website](https://quantumai.google/cirq) has a number of text-based tutorials you can work through. I recommend checking out the [basic tutorial](https://quantumai.google/cirq/tutorials/basics) to get started, then reading through the pages under the "Guide" tab to learn more about each component.

Hope this helps, and welcome to Cirq!

**Comment by mertbozkir** [comment]
Thank you so much @95-martin-orion. I appreciate it for this resources, but I have already knew them. My learning style is based on Video or images. :)) 
I will start this cirq website.

**Comment by rmlarose** [comment]
There are a few recordings from the Quantum Educators Workshop on https://quantumai.google/education, and a few more videos on the same page.

**Comment by mertbozkir** [comment]
@rmlarose omg. Thank you Mr. Ryan, I can see now.  That's great opportunity to dive in :)
