### ISSUE TITLE
Need more visualizations for qubit picking from calibration metrics

### ISSUE THREAD

**Issue by karlunho** [quantumlib/Cirq#3681]
When using the quantum computer, I would like to pick the best qubits and the best 2-qubit gates for my experiment based on the calibration metrics.

Currently, the calibration.heatmap('two_qubit_parallel_sqrt_iswap_gate_xeb_average_error_per_cycle') allows me to see the 1 qubit metrics, but doesn't allow me to see the 2-qubit metrics

**Describe the solution you'd like**

In an ideal world, there will be a heatmap showing the 2-qubit fidelities of all the two-qubit metrics ([link](https://quantumai.google/cirq/google/calibration)).  In addition to seeing all the two-qubit grids, it would be nice to have CDFs plots as well (similar to Google's internal reports). 

I'd also like to see a grid showing which qubits have high coherent error, which is equal to (two_qubit_parallel_sqrt_iswap_gate_xeb_average_error_per_cycle -  two_qubit_parallel_sqrt_iswap_gate_xeb_incoherent_error_per_cycle), in order to avoid qubits with high coherent error for my experiment.

Lastly, a tutorial would be helpful for visualization

**[optional] Describe alternatives/workarounds you've considered**

**[optional] Additional context (e.g. screenshots)**

The following [bug](https://github.com/quantumlib/Cirq/issues/3088) would help quite a bit. 

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P1 - I need this no later than the next release (end of quarter)

**Comment by tanujkhattar** [comment]
xref #3642
