### ISSUE TITLE
Add `ReviewNB`

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#3683]
**Is your feature request related to a use case or problem? Please describe.**
This will make it easier for us to review Jupyter notebooks from the Github UI. I'm surprised Github doesn't already have this baked in. I won't be surprised if they end up adding something similar in the future.

**Describe the solution you'd like**
Signup for https://www.reviewnb.com through `quantumlib`. It should be free with our public repos.

**What is the urgency from your perspective for this issue? Is it blocking important work?**
P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle

**Comment by balopat** [comment]
Thanks for the idea - I think we can give it a go as it does not require write permissions for code.

![image](https://user-images.githubusercontent.com/635073/105253189-d7634900-5b33-11eb-9a9c-041c7b46072e.png)

Write access to PRs is not that damaging (https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-pull-requests), so if it would misbehave we can limit the impact.

**Comment by balopat** [comment]
Here's a test PR: https://github.com/balopat/Cirq/pull/8

**Comment by balopat** [comment]
@quantumlib/cirq-maintainers what do you think?

**Comment by 95-martin-orion** [comment]
This seems like a no-brainer, seeing as Tensorflow Quantum has it installed. For example: https://github.com/tensorflow/quantum/pull/428

**Comment by balopat** [comment]
Alrighty, I installed it. Happy ReviewNB-ing!
