### ISSUE TITLE
Make cirq.final_state_vector and cirq.AbstractCircuit.final_state_vector consistent

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3693]
There are some inconsistencies that we should resolve: 

- `cirq.final_state_vector` does not have ignore_terminal_measurements - we should decide if we want this everywhere or not, but inconsistency is the worst 
- the `AbstractCircuit` version seems to have its own simulator (iterating through unitaries) instead of using Simulator - we should have AbstractCircuit delegate to cirq.final_state_vector or similar...

**Comment by 95-martin-orion** [comment]
This has sat around for long enough that _both_ methods are out of date. I'd like to consolidate on:
```python
def final_state_vector(
    circuit: 'cirq.CIRCUIT_LIKE',  # cirq.fsv() only
    *,
    initial_state: 'cirq.STATE_VECTOR_LIKE' = 0,
    param_resolver: 'cirq.ParamResolverOrSimilarType' = None,
    qubit_order: 'cirq.QubitOrderOrList' = ops.QubitOrder.DEFAULT,
    ignore_terminal_measurements: bool = True,
    dtype: Type[np.number] = np.complex64,
    seed: 'cirq.RANDOM_STATE_OR_SEED_LIKE' = None,
) -> 'np.ndarray':
    # invoke cirq.Simulator(...).simulate(...)
```
This involves:
- For `Circuit`, adding `param_resolver` and `seed` and dropping `qubits_that_should_be_present`
- Also for `Circuit`, enforcing kwargs instead of positional args
- For the top-level method, adding `ignore_terminal_measurements`

**Comment by daxfohl** [comment]
xref https://github.com/quantumlib/Cirq/issues/5242

**Comment by 95-martin-orion** [comment]
But wait, there's more!
- The two methods have different default final measurement behavior (`Circuit` ignores them, `cirq` fails on them)
    - `ignore_terminal_measurements` is a strange parameter in general. At best, it's a "I know what I'm doing" flag for people to get state vectors out of circuits with measurements, but a default of `True` completely undermines that.
- The two methods use different default dtypes (`Circuit` uses `complex128`, `cirq` uses `complex64`)
    - Cirq is wildly inconsistent about which of these to use (48 and 53 files for 64 and 128, respectively), but the simulators prefer `complex64` so that's what I'll use here.
    - Our results show that double-precision floats don't significantly improve simulation fidelity over single-precision.
