### ISSUE TITLE
Inconsistency with named args for atol in _commutes_ methods

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3695]
There seems to be some inconsistency around _commutes_ methods in the codebase, whether we force `atol` to be named parameter or not:

![image](https://user-images.githubusercontent.com/635073/105259766-42ffe300-5b41-11eb-9c96-211d02c77d87.png)

_Originally posted by @balopat in https://github.com/quantumlib/Cirq/pull/3548#r561446265_

**Comment by 95-martin-orion** [comment]
My vote is for requiring `*`:
- Using `*` is less ambiguous about the type of tolerance expected (relative vs. absolute)
- The protocol (`_strat_commutes_from_commutes_`) uses `*`
- Magic methods are private, so adding `*` would not be a breaking change

**Comment by akushnarov** [comment]
Happy to work on this, since I already have some experience in `_commute_` functionality

**Comment by 95-martin-orion** [comment]
Thanks for jumping on this, @akushnarov! Feel free to request review directly from me on the eventual PR.
