### ISSUE TITLE
CODEOWNERS test failure in master

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#3702]
**Description of the issue**

PR #3700 hit failures in its CODEOWNERS test, despite not changing CODEOWNERS files.

**How to reproduce the issue**

_Known to work:_
Re-run the checks on #3700.

_Alternative (had issues locally with installing codeowners):_
On the master branch:
```
pip install .
# If codeowners is not properly installed, all tests are skipped.
pytest dev_tools/codeowners_test.py  
```

**Cirq version**

v0.10.0.dev

**Comment by balopat** [comment]
Looking!
