### ISSUE TITLE
Upgrade codeowners to 0.2.0

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3704]
https://github.com/quantumlib/Cirq/issues/3702 was fixed by pinning codeowners to 0.1.2. 
In the new version we have windows support (so we can add to requirements.txt) but maybe there is a bug as we have test failures. We'll need to investigate.

**Comment by balopat** [comment]
This is blocked by a bug in the tool: https://github.com/sbdchd/codeowners/issues/13

**Comment by unaiic** [comment]
@balopat It seems sbdchd/codeowners#13 was fixed. Maybe we can upgrade codeowners to 0.2.0, 0.2.1 or even 0.3.0 (it was released 8 days ago), and add it to requirements.txt. What do you think?

**Comment by dstrain115** [comment]
I think this was done in #4131.  This dependency is no longer pinned.
