### ISSUE TITLE
automerge bot sometimes stops working

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3705]
Today (1/25) the automerge labels are not picked up. 
I checked the GKE workload, and it seems to be running. However, the logs stopped on 1/20 after a merge. 
![image](https://user-images.githubusercontent.com/635073/105773073-16b8dd80-5f18-11eb-8148-55a482c1c4c4.png)

**Comment by balopat** [comment]
Seemingly the CPU requests totally stopped after that merge

![image](https://user-images.githubusercontent.com/635073/105773448-c0986a00-5f18-11eb-9460-b421a96bf03d.png)

**Comment by balopat** [comment]
Not sure what the root cause was. However there were no redeployments from master either as the trigger (redeploy-automerge-on-push-to-master) was set to manual for some reason. I changed that to every push on master. This redeployment should restart the automerge bot and fix this stalling.

**Comment by dstrain115** [comment]
Obsolete issue.
