### ISSUE TITLE
_resolve_parameters_ changes are not backwards-compatible

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#3714]
**Description of the issue**

External code that defined a `_resolve_parameters_` magic method for Cirq 0.9 is broken by #3546, which changed the function signature for that method in a non-backwards-compatible way.

**How to reproduce the issue**

Construct a parameterized circuit in Cirq v0.10.0-dev, then attempt to run it in the latest version of qsim.

**Cirq version**

Occurs when upgrading from v0.9.* to v0.10.0-dev

**Comment by 95-martin-orion** [comment]
Since `_resolve_parameters_` is a private method (has a leading underscore), we can just make `cirq.resolve_parameters` backwards-compatible. This requires fixing some incorrect behavior in qsim (https://github.com/quantumlib/qsim/pull/278), but is _much_ cleaner to implement.

**Comment by balopat** [comment]
For completeness sake: 

repro code: 

```
from qsimcirq import QSimCircuit
import cirq

cirq.resolve_parameters(param_resolver=cirq.ParamResolver(param_dict={'a':1}),
                        val=QSimCircuit(cirq.Circuit()),
                        recursive=False)

```

Exception:

```
Traceback (most recent call last):
  File "/Users/balintp/Library/Application Support/JetBrains/PyCharm2020.2/scratches/qsimcirq_bla.py", line 6, in <module>
    recursive=False)
  File "/Users/balintp/dev/proj/Cirq/cirq/protocols/resolve_parameters.py", line 157, in resolve_parameters
    result = NotImplemented if getter is None else getter(param_resolver, recursive)
TypeError: _resolve_parameters_() takes 2 positional arguments but 3 were given
```
