### ISSUE TITLE
Inconsistency in check/pylint

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#3716]
**Description of the issue**

PR #3698 hit the following pylint errors:
```
************* Module cirq.study.sweepable
cirq/study/sweepable.py:17:0: W0611: Unused Dict imported from typing (unused-import)
************* Module cirq.optimizers.align_right
cirq/optimizers/align_right.py:17:0: W0611: Unused ops imported from cirq (unused-import)
************* Module cirq.optimizers.align_left
cirq/optimizers/align_left.py:17:0: W0611: Unused ops imported from cirq (unused-import)
```
These files were not modified in this PR; as far as I can tell, the issues above were introduced in #3643 and #3644. Strangely, those PRs did not get flagged by the pylint checker.

I have confirmed that all three PRs listed here used `pylint-2.6.0` in their checks.

**How to reproduce the issue**

Unclear. It seems like `check/pylint` behaves inconsistently in PR tests; we should double-check that it's set up correctly.

**Cirq version**
v0.10.0-dev

**Comment by 95-martin-orion** [comment]
I was not able to reproduce this locally on branch `95-martin-orion:cirq-expects-values`, despite both issues being present on inspection.

**Comment by balopat** [comment]
On My Mac, I see only the `Unused Dict imported from typing (unused-import)` error, the other too doesn't show up. It's odd that pylint is inconsistent between environments.

**Comment by tonybruguier** [comment]
I can find some issues locally. I'm using ubuntu and it happens to be an ec2 instance, so I could share access with someone if they want to repro (or run some commands to help track things).

**Comment by 95-martin-orion** [comment]
Marking resolved since I can't remember seeing this since the two PRs above.
