### ISSUE TITLE
Can't use cirq.Simulator() in a multiprocessing closure (unable to pickle)

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#3717]
When using python's `multiprocessing`, the function closure must be pickleable so that it can be shipped off to the subprocesses. This means you can't use lambdas or anything. A common workaround is to define a helper closure class

```python
class _SimulateClosure:
  def __init__(self, simulator):
    self.simulator = simulator

  def __call__(self, circuit):
     return self.simulator.simulate(circuit)

def do_it():
  circuits = ...
  _simulate = SimulateClosure(cirq.Simulator())
  with multiprocessing.Pool() as pool:
    pool.map(_simulate, circuits)
```

Fails! With the very cryptic "TypeError: can't pickle module objects" But I'm not pickleing a module object!! Well, after some digging and a hat tip to https://stackoverflow.com/a/59832602, we actually are. Our old friend `np.random`, which is the default random generator. A partial solution is to explicitly construct `cirq.Simulator(seed=np.random.RandomState())`, but be very careful; see below.

**Comment by cduck** [comment]
I agree this is an issue.  However, I think a subtle problem with your solution of `seed=np.random.RandomState()` will cause the simulator in each process to get the same sequence of random numbers.

**Comment by mpharrigan** [comment]
Yes, that's very important to point out. In my specific case, it works since I'm just using the `simulate()` method (without measurements or any stochasticity). If I could pass something that says "no randomness please" I would, but `None` causes it to default to `np.random`. I'll update the original post so no one gets the wrong idea.

**Comment by daxfohl** [comment]
Could you have each process create its own simulator instead of pickling one? 

Otherwise, maybe we extract the RNG from simulator itself and instead pass it explicitly into 'run' etc? Then each process can just create its own rng to use.

**Comment by mpharrigan** [comment]
we could also change the constructor's default argument from `np.random` to `None` and then have `if random_state is None: random_state = np.random`

**Comment by mpharrigan** [comment]
You have to be a little bit careful because if you get a bunch of these simulators creating themselves at the same time in each process, they could happen to get seeded to the same state if they draw their seed from the current time.

**Comment by pavoljuhas** [comment]
> You have to be a little bit careful because if you get a bunch of these simulators creating themselves at the same time in each process, they could happen to get seeded to the same state if they draw their seed from the current time.

You can generate a list of unique seeds in the main process and pass them zipped with circuits to the mapped worker function.  That way each function call would have a unique seed to create its own simulator.
In fact, the initial example, if pickleable, would run simulations with the same seed.  multiprocessing by default forks child processes, so they would end up with numpy RNG in identical state.

**Comment by mpharrigan** [comment]
It's still kindof annoying that you need to generate a bunch of random seeds in the case where you're not actually using any randomness, i.e. if you're calling `simulate`. For @jarthurgross , there's even less randomness needed when doing a density matrix simulation :)
