### ISSUE TITLE
Automerge bot blames lack of "cla/google" for no reason

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3736]
I've seen this error before when cirqbot gets confused...we should have a look for cases when lack of "cla/google" is blamed for no reason and fix it in CirqBot.

_Originally posted by @balopat in https://github.com/quantumlib/Cirq/issues/3706#issuecomment-772226393_

**Comment by balopat** [comment]
Other PRs that had this issue: https://github.com/quantumlib/Cirq/pulls?q=is%3Apr+is%3Aclosed+%22Missing+statuses%3A+%5B%27cla%2Fgoogle%27%5D%22

**Comment by dstrain115** [comment]
Obsolete, as there is automerge in GH now.
