### ISSUE TITLE
Flake: density_matrix_simulator_test.py::test_simulate_compare_to_state_vector_simulator

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3763]
On an unrelated change I saw this failure on the coverage tests.

https://github.com/quantumlib/Cirq/pull/3738/checks?check_run_id=1857693314

```
FAILED cirq/sim/density_matrix_simulator_test.py::test_simulate_compare_to_state_vector_simulator[complex64-circuit9]
1 failed, 10002 passed, 81 skipped, 63 xfailed, 12577 warnings in 464.32s (0:07:44)
```

see [logs_3596.zip](https://github.com/quantumlib/Cirq/files/5946979/logs_3596.zip)

**Comment by balopat** [comment]
confirmed - just a simple rerun made it pass: https://github.com/quantumlib/Cirq/pull/3738/checks?check_run_id=1858461253

**Comment by mpharrigan** [comment]
anyone know if this is still an issue @MichaelBroughton ?

**Comment by mpharrigan** [comment]
presumably fixed; feel free to re-open
