### ISSUE TITLE
python 3.9 support

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3772]
As per our - not yet documented (https://github.com/quantumlib/Cirq/issues/3347) - python policy we should support 3 versions of python at a time. In Oct 2020, the stable version of Python 3.9.0 was released, we should support it. 
This means adding 3.9 to the test matrix in .github/workflows/ci.yml `python-version: [ '3.7', '3.8' ]` for Ubuntu, Windows and MacOS builds, and working out all the dependency kinks. 

@kevinsung started to pave the way with the [issues](https://github.com/quantumlib/Cirq/issues?q=is%3Aissue+is%3Aopen+label%3Apython3.9) he opened, someone just needs to work through them.

**Comment by kevinsung** [comment]
Due to https://github.com/quantumlib/Cirq/issues/3769 it looks like this depends on numba releasing version 0.53.0.
