### ISSUE TITLE
Add single_gate_in_moment or similar

### ISSUE THREAD

**Issue by dstrain115** [quantumlib/Cirq#3773]
**Is your feature request related to a use case or problem? Please describe.**

We are noticing lots of cases where we are trying to pull out the gate used in a moment (for instance, if it is a two-qubit layer, to figure

**Describe the solution you'd like**

A function in cirq.Moment for get_single_gate_from_moment that returns the gate if there is only a single gate or if all gates are the same, or None if the gates do not match.

**[optional] Describe alternatives/workarounds you've considered**

Writing my own function over and over in various places.

**[optional] Additional context (e.g. screenshots)**

This comes up a lot in Calibration API.

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle 

See Pyle PR issue 18837 for motivation.

**Comment by dstrain115** [comment]
Added to discussion to verify that we want to add this to the Moment class.

**Comment by madhurimaparuchuri** [comment]
Hi, is this issue open, asking based on conversation here : https://github.com/quantumlib/Cirq/pull/4354#issuecomment-1093382159

**Comment by mpharrigan** [comment]
This still seems like a good idea to me

**Comment by dstrain115** [comment]
After attempting to implement this method, it was abandoned due to problems in the details for instance, how to distinguish whether two gates are the same or now.  All of the ideas seemed to make decisions that the user may or may not want.  For instance, are two gates the same if some of their parameters are different, what if they have tags, etc.

I don't think it's worth trying to disambiguate these, since the code for this can be easily written based on the specific user intent.
