### ISSUE TITLE
[Docs] Colab Python is 3.6, but >=3.7 is now required

### ISSUE THREAD

**Issue by rmlarose** [quantumlib/Cirq#3774]
Python 3.6 support was dropped in #3574, but Python 3.6.9 is the default version in Colab. So, after the next release, docs currently couldn't be run in Colab despite the prominent "Run in Google Colab" button in each.

For example, if I try to install from master on Colab now:

```python
!pip install git+https://github.com/quantumlib/Cirq
```

I get:

```text
Collecting git+https://github.com/quantumlib/Cirq
  Cloning https://github.com/quantumlib/Cirq to /tmp/pip-req-build-1_l01hxm
  Running command git clone -q https://github.com/quantumlib/Cirq /tmp/pip-req-build-1_l01hxm
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
ERROR: Package 'cirq' requires a different Python: 3.6.9 not in '>=3.7.0'
```

Apparently there are ways to install different Python versions in Colab, e.g. as described [here](https://stackoverflow.com/questions/63867581/install-python-3-7-via-google-colab-as-default-python).

**Comment by balopat** [comment]
Yeah, this is definitely a tricky situation. For now we still work mostly on 3.6. Colab will get their version sorted out sooner or later, they are actively working on it. 

However, the particular error you pointed out only happens when you install from git as the `python_require` config is used by setup.py. However, the distributed wheel from pypi does not check for this - the solution is to use `pip install cirq --pre`.

**Comment by balopat** [comment]
> Apparently there are ways to install different Python versions in Colab, e.g. as described [here](https://stackoverflow.com/questions/63867581/install-python-3-7-via-google-colab-as-default-python).

That seems like a local runtime spun up to connect to. That's not something feasible for us.

**Comment by balopat** [comment]
I'm going to close this - given that we have a workaround for the actual issue. However, if this bites us in some way, we'll need to figure it out - we can reopen it again.

**Comment by rmlarose** [comment]
> However, the distributed wheel from pypi does not check for this - the solution is to use `pip install cirq --pre`.

Ah! I didn't know this. Agree it should be closed - thanks!
