### ISSUE TITLE
q1 == q1 but hash(q1) != hash(q2)

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#3777]
I'm having trouble reproducing this, but I'm in a situation where the thing in the title is happening with `GridQubit`. I've narrowed it down to the fact that the cached `cirq.GridQubit._hash` values are different and recomputing them with `cirq.Qid.__hash__(q1)` gives correct, identical hash functions.

My leading theory is that I'm loading a previously-pickled gridqubit, a copy is being made somewhere and the hash is recomputed. The hash value of `Qid` (the class) is part of the hash input, which could differ over python instantiations

**Comment by mpharrigan** [comment]
xref https://github.com/quantumlib/Cirq/pull/3375

relevant: https://docs.python.org/3/library/pickle.html#handling-stateful-objects

**Comment by maffoo** [comment]
We should probably make the hash deterministic, e.g.
```python
self._hash = hash(self.row) ^ hash(self.col)
```
