### ISSUE TITLE
Drop python 3.6 support as soon as Colab supports 3.7

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3800]
As soon as Colab supports 3.7, we should drop 3.6 support - this is expected within Q1 2021.

**Comment by unaiic** [comment]
Now Colab supports Python 3.7.10, so I think now it's a good time to drop support for Python 3.6.

**Comment by balopat** [comment]
Ooo nice! One thing I realized is that internally Google is still on Python 3.6 in a lot of places so we won't be able to drop it :(

**Comment by balopat** [comment]
@unaiic - thanks for pointing this out - I'm going to close this!
