### ISSUE TITLE
Give EqualsTester to the world?

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#3806]
I find myself missing Cirq's EqualsTester outside of Cirq (yes such a thing exists!), and don't necessarily want to import all of Cirq.  Would be nice if there were a home for it outside of Cirq.  Do the quantumlib folks have any plans for this?  If quantumlib doesn't have a desire to do this, I think I will use the Apache 2 to create a new version with a proper NOTICE about its origin.

**Comment by Strilanc** [comment]
It is handy, isn't it?

I say go ahead and pull it out and put it on pypi.

**Comment by dabacon** [comment]
Thanks @Strilanc went ahead and did this (thought you might say this).  I have a version up and running in a package called pymore: https://github.com/dabacon/pymore  Welcome comments over there.  I think this is also one open issue which I think I know how to solve.

**Comment by balopat** [comment]
Very nice! +1
