### ISSUE TITLE
FrozenCircuit should be able to equal Circuit

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#3807]
In python, freezing an object does not make it unequal. For example:

```
assert frozenset([1, 2]) == set([1, 2])
# passes
```

Currently cirq is breaking this convention:

```
assert cirq.Circuit().freeze() == cirq.Circuit()
# fails
```

Note that this doesn't require the hash codes to be equal. Circuit should still have no hash code, because it is mutable.

**Comment by balopat** [comment]
Yeah, I pointed this out to @95-martin-orion (https://github.com/quantumlib/Cirq/pull/3445#discussion_r513054808) and then it got lost in the PR shuffles. I agree!

**Comment by 95-martin-orion** [comment]
I wasn't aware of the PYthon convention around this - will have a PR out momentarily.
