### ISSUE TITLE
Error of multiplicative_group function in Shor.ipynb tutorial

### ISSUE THREAD

**Issue by ybc1991** [quantumlib/Cirq#3814]
**Description of the issue**
The implementation of multiplicative_group function in [Shor.ipynb](https://quantumai.google/cirq/tutorials/shor) tutorial is wrong. 

**How to reproduce the issue**
The code in the notebook is
```
"""Function to compute the elements of Z_n."""
def multiplicative_group(n: int) -> List[int]:
    """Returns the multiplicative group modulo n.

    Args:
        n: Modulus of the multiplicative group.
    """
    assert n > 2
    group = [1, 2]
    for x in range(3, n):
        if math.gcd(x, n) == 1:
            group.append(x)
    return group
```
Here `group`  initialized as `[1, 2]`. However, element 2 should not be included always. For example, when `n = 6`, the result should be `[1,5]`. It is easy to fix it by changing the function into 
```
    ...
    group = [1]
    for x in range(2, n):
          ...
```
There is no propagation of error since this function is not used afterward. But it is not good to keep the wrong implementation.

**Cirq version**
Irrelevant.

**Comment by rmlarose** [comment]
Ah yeah, thanks for noting this. Pesky even primes
