### ISSUE TITLE
Is anyone using CircuitDag?

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#3816]
I did some digging, since I've never personally used CircuitDag. I see it was added here https://github.com/quantumlib/Cirq/pull/759 in response to this feature request: https://github.com/quantumlib/Cirq/issues/547. Searching for usages turns up some utility in `cirq.contrib.routing`. Otherwise, my reading of these issues and some personal intuition is that this class was originally a "solution looking for a problem". Even in the case with of https://github.com/quantumlib/Cirq/pull/3599, we found out that CircuitDag was close but not what we wanted.

One way of moving forward with https://github.com/quantumlib/Cirq/pull/3599 is to extend CircuitDag to do what we need for factorizing circuits, but I think we'd need a better set of use cases.

Another proposal is to deprecate CircuitDag from main cirq prior to 1.0, move the functionality to `cirq.contrib.routing` and wait on a full design for the time at which we add routing to main-cirq

cc @bryano @cduck @Strilanc

**Comment by balopat** [comment]
Cirq Cynque verdict: deprecate nicely into contrib, where it will fall into the "archive" category eventually as we dismantle contrib.

**Comment by dstrain115** [comment]
@tanujkhattar What is the action item here?  Should we deprecate CircuitDag?

**Comment by tanujkhattar** [comment]
+1, let's deprecate and move to contrib.
