### ISSUE TITLE
[doc] New hardware vendor getting started

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3820]
It would be great to have a doc that lists all the different things a hardware provider can and should do when integrating with Cirq. Namely, 
- write an RFC 
- documentation (follow the notebook guidelines)
    - access and auth (if available) 
    - getting started guide 
- integration process (external vs internal module) 
- design - interfaces to implement (Sampler, Device, ...)  
  - create device abstraction / operation validation for supported gateset 
  - noise model 
  - come up with serialization (or use cirq.to_json) 
  - ensure Simulators work (built-in, qsim)
  - integrate service (if available) 
  - 
 
and more...

Related #3245.

**Comment by dstrain115** [comment]
Discussion from cirq cync: let's still do this, but it can be done after 0.15
