### ISSUE TITLE
Clean up disparity in simulator implementation styles

### ISSUE THREAD

**Issue by daxfohl** [quantumlib/Cirq#3825]
Sparse and Clifford both have a proper `ActOnXXXStateArgs` where they maintain simulator state, and those are explicitly checked throughout the cirq codebase with `isinstance` checks that alter behavior of different operations depending on the args. This was first added in #3019 with the `act_on` protocol.

DensityMatrix and MPS both have self-contained state (_StateAndBuffers and MPSState, respecively).

Should we change it to be consistent?

cc @Strilanc

**Comment by daxfohl** [comment]
Discussed in gitter, I'll look into moving density matrix simulator into the ActOn format.

**Comment by tanujkhattar** [comment]
One downside of discussing stuff on gitter and referencing here is that the discussion on gitter can get lost (though I was able to find it for this issue :)), so in general I would propose that we should copy paste discussion on github issues as well, for future reference.

**Comment by daxfohl** [comment]
Sure, the TLDR of the discussion was:

1. Do we like the `ActOn` pattern? --answer: yes
2. Is there anything preventing its adoption in DensityMatrix or MPS? --answer: don't think so, try it out and create PR if it works.
