### ISSUE TITLE
Add support for serializing enum.Enum classes

### ISSUE THREAD

**Issue by maffoo** [quantumlib/Cirq#3853]
**Is your feature request related to a use case or problem? Please describe.**

In #3821 I added a `cirq.Alignment` enum and attempted to make it serializable. Unfortunately, it's not possible to define `_json_dict_` on an enum subclass because enum reserves single underscore `_names_` for internal use. To allow serializing enums we would need to do something different. For now, I've marked the enum as not yet serializable. We have a few other enums, e.g. in the placement/routing code, but none of them are serializable.

**Describe the solution you'd like**

It'd be great if there were a somewhat generic way to make enums serializable, something like `json_serializable_dataclass` but specific to enums.

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle

**Comment by 95-martin-orion** [comment]
Some ideas that have been thrown around for this:

1. Provide a default JSON conversion for enum types, e.g. `{ cirq_type: {enum_type} value: {enum_value} }`
    * Defining enum conversion separate from the enums themselves may be confusing
2. Use strings and `Literal` types instead of enums, e.g. `{enum_type} = Literal[{enum_value_1}, ..., {enum_value_N}]`
    * Puts the onus on users/developers to know this convention

**Comment by 95-martin-orion** [comment]
General recommendation here is to not use the `Enum` class; trying to get a change to Enum accepted into Python is pretty much the only full solution to this, but it would take a very long time for that to be available to Cirq.
