### ISSUE TITLE
stable and latest document link in the readme

### ISSUE THREAD

**Issue by ybc1991** [quantumlib/Cirq#3858]
**Description of the issue**
The latest and stable document link in README are all pointed to the main page of cirq. The raw code of README:
> Documentation for the latest **pre-release** version of cirq (tracks the repository's master branch; what you get if you ``pip install --pre cirq``), is available at `cirq.readthedocs.io/latest <https://quantumai.google/cirq/>`_.
> 
> Documentation for the latest **stable** version of cirq (what you get if you ``pip install cirq``) is available at `cirq.readthedocs.io/stable <https://quantumai.google/cirq/>`_.

Should we update it into 
https://quantumai.google/reference/python/cirq/all_symbols  for the stable
https://quantumai.google/reference/python/cirq/all_symbols?version=nightly for the latest?

**Comment by balopat** [comment]
Yes! Thanks for catching that!!!
