### ISSUE TITLE
N-qubit diagonal gate

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3866]
**Is your feature request related to a use case or problem? Please describe.**

Quantum oracles implementing functions of type f: {0,1}^n -> {1,-1} (n is the number of qubits) can be represented as diagonal gates. Currently Cirq only has a ThreeQubitDiagonalGate. For larger oracles one can use the MatrixGate, however there is no decomposition logic implemented for it. 

**Describe the solution you'd like**

1. `DiagonalGate`
```
qubits = cirq.LineQubit.range(6)
c = cirq.Circuit(cirq.DiagonalGate([1,-1,1,1,1,-1])(qubits)) 
print(c) 
```

Should provide a meaningful circuit diagram. 

2. Decomposition 
```
a,b,c = cirq.LineQubit.range(3)
cirq.decompose(cirq.DiagonalGate([1,-1,1])(a,b,c)) 
```
should provide a list of 1 and 2 qubit gates that allows for implementation of this gate on hardware. 

**[optional] Additional context (e.g. screenshots)**

This came up during implementing the Fourier checking algo as a tutorial: https://github.com/quantumlib/Cirq/issues/3687

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle

**Comment by vtomole** [comment]
It looks like https://github.com/quantumlib/Cirq/pull/3890 took care of this. Please re-open if there is more work to do here.
