### ISSUE TITLE
export_to_quirk_test.py super fragile

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#387]
Got this while running on a different system whose floating point implementation seems to be different:

_______________________ test_various_unknown_gate_types ________________________

    def test_various_unknown_gate_types():
        a = cirq.NamedQubit(u'a')
        b = cirq.NamedQubit(u'b')
        circuit = cirq.Circuit.from_ops(
            cirq.X(a)**(1/5),
            cirq.Y(a)**(1/5),
            cirq.Z(a)**(1/5),
            cirq.CZ(a, b)**(1/5),
            cirq.google.ExpWGate(axis_half_turns=0.25)(a),
            cirq.google.ExpWGate(half_turns=1, axis_half_turns=cirq.Symbol(u'r'))(a)
        )
       assert circuit_to_quirk_url(circuit,
                                    escape_url=False,
                                    prefer_unknown_gate_to_failure=True) == u"""
            http://algassert.com/quirk#circuit={"cols":[
                [{"id":"?",
                  "matrix":"{{0.9045084971874737+0.29389262614623657i,
                              0.09549150281252627+-0.29389262614623657i},
                             {0.09549150281252627+-0.29389262614623657i,
                              0.9045084971874737+0.29389262614623657i}}"}],
                [{"id":"?",
                  "matrix":"{{0.9045084971874737+0.29389262614623657i,
                              0.29389262614623657+0.09549150281252627i},
                             {-0.29389262614623657+-0.09549150281252627i,
                              0.9045084971874737+0.29389262614623657i}}"}],
                [{"id":"?",
                  "matrix":"{{1.0+0.0i,0.0+0.0i},
                             {0.0+0.0i,0.8090169943749475+0.5877852522924731i}}"}],
                ["UNKNOWN", "UNKNOWN"],
                [{"id":"?",
                  "matrix":"{{0.0+6.123233995736766e-17i,
                              0.7071067811865476+0.7071067811865475i},
                             {0.7071067811865476+-0.7071067811865475i,
                              0.0+6.123233995736766e-17i}}"}],
                ["UNKNOWN"]
            ]}
        """.replace(u'\n', u'').replace(u' ', u'')
E       assert 'http://algas...["UNKNOWN"]]}' == 'http://algass...["UNKNOWN"]]}'
E         Skipping 71 identical leading characters in diff, use -v to show
E         - 4508497187+0.293892626146i,0.0954915028125+-0.293892626146i},{0.0954915028125+-0.293892626146i,0.904508497187+0.293892626146i}}"}],[{"id":"?","matrix":"{{0.904508497187+0.293892626146i,0.293892626146+0.0954915028125i},{-0.293892626146+-0.0954915028125i,0.904508497187+0.293892626146i}}"}],[{"id":"?","matrix":"{{1.0+0.0i,0.0+0.0i},{0.0+0.0i,0.809016994375+0.587785252292i}}"}],["UNKNOWN","UNKNOWN"],[{"id":"?","matrix":"{{0.0+6.12323399574e-17i,0.707106781187+0.707106781187i},{0.707106781187+-0.707106781187i,0.0+6.12323399574e-17i}}"}],["UNKNOWN"]]}
E         + 45084971874737+0.29389262614623657i,0.09549150281252627+-0.29389262614623657i},{0.09549150281252627+-0.29389262614623657i,0.9045084971874737+0.29389262614623657i}}"}],[{"id":"?","matrix":"{{0.9045084971874737+0.29389262614623657i,0.29389262614623657+0.09549150281252627i},{-0.29389262614623657+-0.09549150281252627i,0.9045084971874737+0.29389262614623657i}}"}],[{"id":"?","matrix":"{{1.0+0.0i,0.0+0.0i},{0.0+0.0i,0.8090169943749475+0.5877852522924731i}}"}],["UNKNOWN","UNKNOWN"],[{"id":"?","matrix":"{{0.0+6.123233995736766e-17i,0.7071067811865476+0.7071067811865475i},{0.7071067811865476+-0.7071067811865475i,0.0+6.123233995736766e-17i}}"}],["UNKNOWN"]]}
E         Detailed information truncated (-6 more lines), use "-vv" to show

These tests probably need to be written to not rely on precision of the math?

**Comment by dabacon** [comment]
@Strilanc is this still a bug or has it been fixed?

**Comment by Strilanc** [comment]
Fixed by https://github.com/quantumlib/Cirq/commit/2bb6b6debcc161b68f23252f177f7b687a697ba8#diff-c765623fc99ada0bed8f33de3ddd831d
