### ISSUE TITLE
Circuit api documentation ignoring lists

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#3883]
**Description of the issue**
The documentation for Circuit on https://quantumai.google/reference/python/cirq/circuits/Circuit is very much not formatting in a readable manner.  Compare to the documentation in circuit.py it seems to not be showing the lists.

![image](https://user-images.githubusercontent.com/87974/110167697-f697fc00-7daa-11eb-9a33-6a9fea5b1279.png)

**How to reproduce the issue**

Visit the documentation page :)

**Comment by balopat** [comment]
This will change as soon as we publish the released devsite in ~1hour. 
If you click on `See Nightly,` you'll see the latest changes fix the docstring!
