### ISSUE TITLE
GlobalPhaseOperation within CircuitOperation is not applied correctly to the whole circuit

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3884]
**Is your design idea/issue related to a use case or problem? Please describe.**

With @ybc1991  we are working on the "decomposable" N-qubit diagonal gate #3866. Here, it would be nice to be able to add the global phase of the operation stemming from the first angle. `cirq.ThreeQubitDiagonalGate` gets around this by adding in the global phase to the rotation gates as a shift. If we use `cirq.GlobalPhaseOperation` the problem is that `cirq.ControlledGate(cirq.DiagonalGate))` won't work out of the box - because `cirq.ControlledOperation(cirq.GlobalPhaseOperation)` does not behave well.

**Describe your design idea/issue**

The main issue is that `GlobalPhaseOperation` is qubitless. This is technically correct...a global phase `exp(2 pi i theta)` has ambiguity in its representation: it could be represented with a scalar (current solution), or a diagonal gate with `exp(2 pi i theta)` in all diagonal elements spanning any subset of the qubits. 

The design issue here is that Operations in Cirq meant to be reused in local contexts - that's when issues arise: 

1. `cirq.ControlledOperation` should work with most operations - barring that they have a known decomposition. However, an operation that does not have qubits cannot be made local. Here are some fun examples:

```
In [16]: cirq.unitary(cirq.GlobalPhaseOperation(-1).controlled_by(cirq.LineQubit(1)))
Out[16]: 
array([[ 1,  0],
       [ 0, -1]])
```
2. `cirq.CircuitOperation` seems to ignore it? It should propagate it properly to the top level, right?

```
In [21]: cirq.Circuit(cirq.X(cirq.LineQubit(2)), cirq.CircuitOperation(cirq.Circuit(cirq.GlobalPhaseOperation(-1)).freeze()))
Out[21]: 2: ───X───
```

**Comment by smitsanghavi** [comment]
example 2 looks like a bug, the global phase should be propagated from inside a subcircuit. I don't see much of an issue with example 1. When the controlling qubit is `|1>`, the controlled operation is being applied. What is the expected output?
`
array([[ -1,  0],
       [ 0, -1]])
`? Should the phase stay global even when controlled?

**Comment by balopat** [comment]
1.
  a.) You are totally right that this might actually be correct :) I guess I was expecting some kind of error. But you are right the Phase (Z) operation can be thought of a controlled operation (if 1 then phase). No, the phase should not stay global when controlled - it should be applied only to the controlled subspace. 
  b.) We also ran into some kind of `qubit_order` issue that I couldn't reproduce...if we run into it again, I'll add it here. (I _think_ it was the `ValueError("Don't know how to interpret <{}> as a Basis.".format(val))` with `C(0,-1)` when we were trying to call `cirq.unitary` but I just can't reproduce it!)
2. I agree that this is a bug - we should think about it more carefully!

**Comment by ybc1991** [comment]
The qubit order error can be reproduced like this:
```
op = cirq.ControlledOperation(controls=cirq.LineQubit.range(1), 
                              sub_operation=cirq.GlobalPhaseOperation(-1))
print(circ.unitary(op))
```
You will encounter

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-a848c4e99b9e> in <module>()
      1 op = cirq.ControlledOperation(controls=cirq.LineQubit.range(1), 
      2                               sub_operation=cirq.GlobalPhaseOperation(-1))
----> 3 print(circ.unitary(op))

1 frames
/usr/local/lib/python3.7/dist-packages/cirq/circuits/circuit.py in unitary(self, qubit_order, qubits_that_should_be_present, ignore_terminal_measurements, dtype)
    962             raise ValueError('Circuit contains a non-terminal measurement.')
    963 
--> 964         qs = ops.QubitOrder.as_qubit_order(qubit_order).order_for(
    965             self.all_qubits().union(qubits_that_should_be_present)
    966         )

/usr/local/lib/python3.7/dist-packages/cirq/ops/qubit_order.py in as_qubit_order(val)
    123         if isinstance(val, QubitOrder):
    124             return val
--> 125         raise ValueError("Don't know how to interpret <{}> as a Basis.".format(val))
    126 
    127     def map(

ValueError: Don't know how to interpret <C(0, -1)> as a Basis.
```

**Comment by smitsanghavi** [comment]
Interesting. I'm not getting the above error. I am getting the array that Balint noted in the original comment. Maybe the typo `cirq->circ` in the print statement is the issue above? Though I don't know how that happened unless some other (maybe older cirq) import has been aliases as `circ`

**Comment by ybc1991** [comment]
It is because of the typo! Now it makes sense. In the case `circ` is defined, `circ.unitary(op)` will think `op` passed as the `qubit_order` argument. Of course, it cannot interpret it and report this error.  (circ and cirq is so easy to mistyped :/ )

**Comment by balopat** [comment]
Nice job digging out the issue @ybc1991  (I couldn't find it in the colab history, though I did not look hard). Mystery solved!!!

**Comment by smitsanghavi** [comment]
I can take this up
