### ISSUE TITLE
Drawing a circuit nicely.

### ISSUE THREAD

**Issue by chitramdasgupta** [quantumlib/Cirq#3885]
Printing a circuit looks very dull and boring. Is there a way to make the circuits look a little nicer with colors and shapes when printed or drawn like in qiskit?

The reason I am asking for this feature is because I have a blog where I write about quantum computing and I would like to add code examples written using cirq. If there is a way to make circuits look nice, I will use cirq in my blog.

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle

**Comment by vtomole** [comment]
Hey @chitramdasgupta, You an draw nicer looking diagrams than the ones from printing the circuits if you have Jupyter notebook

```python
import cirq
from cirq.contrib.svg import SVGCircuit

a, b = cirq.LineQubit.range(2)
SVGCircuit(cirq.Circuit(cirq.X(a), cirq.CNOT(a,b)))
```

![Screenshot from 2021-03-08 11-26-45](https://user-images.githubusercontent.com/8405160/110357728-3821e480-8001-11eb-9126-1d3558f3bf4a.png)

**Comment by vtomole** [comment]
@chitramdasgupta I just filed https://quantumcomputing.stackexchange.com/questions/16521/in-cirq-how-do-you-display-circuit-diagrams-that-are-prettier-than-the-ones-d. Please re-open this issue if you have more questions.
