### ISSUE TITLE
docs: "Used in the tutorials - Quantum Chess" link is broken (CNOT, CCNOT pages)

### ISSUE THREAD

**Issue by mattxwang** [quantumlib/Cirq#3946]
**Description of the issue**

Hi, I'm an undergraduate student currently using Cirq in a quantum computing class. I was poking around in the docs, and on the [`cirq.ops.CCNOT`](https://quantumai.google/reference/python/cirq/ops/CCNOT) documentation page, the link "[Quantum chess](https://quantumai.google/cirq/quantum_chess/concepts)" (under Used in the notebooks > Used in the tutorials) leads to a 404. Not sure if the notebook/page got moved, or if it's just a dead reference.

This is also replicable on other pages that link to the Quantum chess docs, like the [`cirq.ops.CNOT`](https://quantumai.google/reference/python/cirq/ops/CNOT) page. 

More than happy to try to resolve this issue since it's a quick docs fix, just want to make sure I'm not making a mistake or anything!

**How to reproduce the issue**

Go to the [`cirq.ops.CCNOT`](https://quantumai.google/reference/python/cirq/ops/CCNOT) documentation page and click "[Quantum chess](https://quantumai.google/cirq/quantum_chess/concepts)".

**Cirq version**

N/A

**Comment by balopat** [comment]
Thanks for opening @mattxwang - this is indeed an issue - we are aware of it and working at fixing it - the automation  behind the "Used in notebooks" section is going wrong somewhere.

**Comment by yashk2810** [comment]
This is now fixed. Thank you for your patience!

**Comment by mattxwang** [comment]
> This is now fixed. Thank you for your patience!

Great, thank you both for the quick reply 😊  I'll close this issue then!
