### ISSUE TITLE
Density matrix simulator support for SimulatesExpectationValues

### ISSUE THREAD

**Issue by zaqqwerty** [quantumlib/Cirq#3964]
**Is your feature request related to a use case or problem? Please describe.**

The density matrix simulator does not inherit from `cirq.sim.simulator.SimulatesExpectationValues`.

**Describe the solution you'd like**

I would like to be able to use this interface with the density matrix simulator:
```python
q0 = cirq.GridQubit(0, 0)
test_circuit_noise = cirq.Circuit(cirq.depolarize(p=1.0)(q0))
test_op = cirq.PauliSum() + cirq.Z(q0)
cirq.DensityMatrixSimulator().simulate_expectation_values(test_circuit_noise, test_op)
```
The reason we want to use this interface is to support expectation value simulations for noisy circuits that do not support materializing the density matrix explicitly.

**[optional] Describe alternatives/workarounds you've considered**

**[optional] Additional context (e.g. screenshots)**

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle

**Comment by 95-martin-orion** [comment]
I fully support adding this feature. In the meantime, let me recommend using [qsimcirq](https://quantumai.google/qsim/tutorials/qsimcirq) - it supports noisy circuit simulation and the `simulate_expectation_values` interface, and is considerably faster and more memory-efficient than the built-in density matrix simulator. Note however that its results are stochastic, meaning that you'll need to run multiple repetitions to get accurate expectation values.
