### ISSUE TITLE
PhasedXZGate has_channel evaluates to True but channel returns NotImplemented 

### ISSUE THREAD

**Issue by dkafri** [quantumlib/Cirq#3965]
**Description of the issue**
See code below
**How to reproduce the issue**

```python
import cirq
 
op = cirq.PhasedXZGate(axis_phase_exponent=-0.5, x_exponent=-0.5,
                       z_exponent=1).on(cirq.GridQubit(3, 3))
assert cirq.has_channel(op)
try:
    cirq.channel(op)
except TypeError as error:
    print(f'Got error {error}')
```

<details>
Print statement reads:

Got error object of type '<class 'cirq.ops.gate_operation.GateOperation'>' does have a _channel_, _mixture_ or _unitary_ method, but it returned NotImplemented.

</details>

**Cirq version**
0.9.0
0.10.0.dev

**Comment by 95-martin-orion** [comment]
The root cause appears to be that the `has_(channel|mixture)` functions allow decomposition, but the `channel` and `mixture` methods do not. (Notably, the `unitary` method _does_ allow decomposition.)

Since `PhasedXZGate` implements `_has_unitary_` but not `_unitary_`, it behaves as described above.

**Comment by 95-martin-orion** [comment]
Recommended fix would be to invoke the lower protocols in `channel` and `mixture` rather than using `getattr`.

**Comment by ftqc2050** [comment]
Discussed on Cirq Cynque: 

- we should do decomposition in channel as well, but behave differently in different situations: 
- if val is unitary - just do it 
- if it's not and notices "large amount of combinatorial explosion" (e.g. in noisy cases) then it would short-circuit

**Comment by balopat** [comment]
Discussed on Cirq Cynque: 

- we should do decomposition in channel as well, but behave differently in different situations: 
- if val is unitary - just do it 
- if it's not and notices "large amount of combinatorial explosion" (e.g. in noisy cases) then it would short-circuit
