### ISSUE TITLE
NumPy deprecation warnings

### ISSUE THREAD

**Issue by unaiic** [quantumlib/Cirq#3975]
**Description of the issue**
When running Pytest checks, NumPy (version 1.20) throws some deprecation warnings, [here ](https://github.com/quantumlib/Cirq/pull/3974/checks?check_run_id=2208712674)for instance.

We could update our sources to keep them updated, assuring that the suggested changes are compatible with older versions of NumPy.

**Comment by dabacon** [comment]
#4072

**Comment by dabacon** [comment]
Think I have squashed them all.  Qiskit currently has the remaining ones I see.
