### ISSUE TITLE
SingleQubitCliffordGate does not properly serialize to JSON

### ISSUE THREAD

**Issue by jarthurgross** [quantumlib/Cirq#3980]
**Description of the issue**

`SingleQubitCliffordGate`s write incomplete information to JSON, and their type cannot be understood by the JSON deserializer.

**How to reproduce the issue**

```python
>>> import cirq
>>> print(cirq.__version__)
0.10.0
>>> q = cirq.LineQubit(0)
>>> json_text = cirq.to_json(cirq.SingleQubitCliffordGate.X(q))
>>> print(json_text)
{
  "cirq_type": "GateOperation",
  "gate": {
    "cirq_type": "SingleQubitCliffordGate"
  },
  "qubits": [
    {
      "cirq_type": "LineQubit",
      "x": 0
    }
  ]
}
>>> deserialized_gate = cirq.read_json(json_text=json_text)
ValueError: Could not resolve type 'SingleQubitCliffordGate' during deserialization
```

**Cirq version**

0.10.0

**Comment by tanujkhattar** [comment]
This is because `SingleQubitCliffordGate` is [not yet serializable](https://github.com/quantumlib/Cirq/blob/06e48928ed9a504dba0985ed9a4fba33709a783a/cirq/protocols/json_test_data/spec.py#L67)

However, I think we should try to enforce that objects which are not yet serializable throw an error instead out producing incomplete json.

**Comment by jarthurgross** [comment]
That would be seem a step in the right direction. Also would be nice if this was clear in the documentation somewhere (instead of only called out in test files).

**Comment by PoPaT1618** [comment]
I would like to work on this issue.

**Comment by balopat** [comment]
Hi @PoPaT1618 - thank you for volunteering! 
Just to clarify, the following needs to be done: 

- remove `SingleQubitCliffordGate` from this list:
- 
https://github.com/quantumlib/Cirq/blob/a41df7f97a9eddba8fcaa4c19c6366acd67de4de/cirq-core/cirq/protocols/json_test_data/spec.py#L67

**Comment by ishmum123** [comment]
This has been idle for a while. Would you mind if I take a shot at it?

**Comment by PoPaT1618** [comment]
Yes, please take it. I will be able to contribute to Cirq from the month of September.
