### ISSUE TITLE
Whole link is displaying in the web version of the documentation

### ISSUE THREAD

**Issue by FallenApart** [quantumlib/Cirq#3986]
https://github.com/quantumlib/Cirq/blob/e0365e4c5dace99ea2668de69cecda33de33e13c/docs/simulation.ipynb#L160

**Comment by rmlarose** [comment]
I believe this is because of two backticks instead around cirq.Simulator instead of just one like the other links.

Looks like this on the website.

![image](https://user-images.githubusercontent.com/32416820/113441393-3bb84980-93bc-11eb-9d77-8465cf73bc17.png)

**Comment by balopat** [comment]
![image](https://user-images.githubusercontent.com/635073/116590399-8bfacc80-a8d2-11eb-9878-8b2cd70524f7.png)
It seems like that this is fixed now. Closing.
