### ISSUE TITLE
Documentation reference to MSGate is out of date

### ISSUE THREAD

**Issue by cduck** [quantumlib/Cirq#3991]
**Description of the issue**
The doc string [here](https://github.com/quantumlib/Cirq/blob/985b411c42cbd2cd97d21e766d28f1f332cfee8b/cirq/ops/parity_gates.py#L60) refers to `cirq.MSGate` which appears to have moved to `cirq.ion.ion_gates.MSGate`.

**How to reproduce the issue**
Look at https://quantumai.google/reference/python/cirq/ops/XXPowGate: "See also: `cirq.MSGate`".

**Cirq version**
0.10.0 and 0.11.0.dev

**Comment by rmlarose** [comment]
I think its appropriate to just update the docstring, so I opened #3992 for this.
