### ISSUE TITLE
ASCII Formatting Issues

### ISSUE THREAD

**Issue by ldabas** [quantumlib/Cirq#3999]
**Description of the issue**
ASCII Art explaining quantum circuits is misformatted in Intro.ipynb  notebook for introduction to Cirq.
**How to reproduce the issue**
This issue is found on computers that use Japanese as the system language.

<details>

The introduction to Cirq ipynb notebook describes quantum circuits using ASCII art, however, all the ASCII art is moved to the right and mis-formatted for me.

</details>

**Comment by balopat** [comment]
Thanks for opening! Closing as dupe of https://github.com/quantumlib/Cirq/issues/3998.
