### ISSUE TITLE
Rounding error while printing solution of "Exercise: Custom Controlled Rx gate" in docs/tutorials/educators/intro.ipynb

### ISSUE THREAD

**Issue by Chen-Jialin** [quantumlib/Cirq#4005]
**Description of the issue**
In file [docs/tutorials/educators/intro.ipynb](https://github.com/quantumlib/Cirq/blob/master/docs/tutorials/educators/intro.ipynb), section [**Exercise: Custom Controlled Rx gate**](https://colab.research.google.com/github/quantumlib/Cirq/blob/master/docs/tutorials/educators/intro.ipynb#scrollTo=y63aDja8R4rc&line=1&uniqifier=1), the exercise requires you to customize a controlled Rx gate. The solution code provided for the exercise is
```python
#@title Expand to view the solution
"""Defining a custom controlled cirq.Rx gate."""
class CRx(cirq.TwoQubitGate):
    def __init__(self, theta):
        self.theta = theta

    def _unitary_(self):
        return np.array([
            [1, 0, 0, 0],
            [0, 1, 0, 0],
            [0, 0, np.cos(self.theta/2), -1j * np.sin(self.theta/2)],
            [0, 0, -1j * np.sin(self.theta/2), np.cos(self.theta/2)]
        ])
    
    def _circuit_diagram_info_(self, args):
        return '@', 'Rx({}π)'.format(self.theta / np.pi)


# Print out its unitary.
print(np.around(cirq.unitary(CRx(0.5 * np.pi))))  
```
If you run this solution code, it will return
```
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.-1.j]
 [0.+0.j 0.+0.j 0.-1.j 1.+0.j]]
```
which is not a unitary matrix.

This is because of the use of function `np.around` without specifying number of decimals:
```python
print(np.around(cirq.unitary(CRx(0.5 * np.pi))))
```
so it will round the decimal to one digit.

**Cirq version**
0.10.0

**Comment by tanujkhattar** [comment]
Thank you for catching this. 

I've renamed the title as the solution of the exercise is correct (i.e. the custom CRx gate defined is correct) but printing the unitary matrix of this custom gate has a rounding error.
