### ISSUE TITLE
Support controlled CircuitOperations

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#4007]
**Is your feature request related to a use case or problem? Please describe.**

Unitary `CircuitOperation`s should be possible to wrap in `ControlledOperation`s, just like any other `Operation`. It's not currently clear whether this is the case, or what behavior to expect when this is attempted.

**Describe the solution you'd like**

We should test the existing behavior and update as necessary to allow for controlled `CircuitOperation`s. My initial, possibly naive expectations are that such an operation:
- should decompose into a series of controlled operations, all with the same control qubit
- should still register as a `CircuitOperation` when type-checked
- should occupy all the control qubits and subcircuit qubits for the moment that contains it, with overlap between control and subcircuit qubits prohibited

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P2 - we should do it in the next couple of quarters

**Comment by verult** [comment]
@95-martin-orion does this require API changes to `ControlledOperation`? Marking as before-1.0 for now.

**Comment by 95-martin-orion** [comment]
> @95-martin-orion does this require API changes to `ControlledOperation`? Marking as before-1.0 for now.

Unclear. It's possible this already works, but I don't know if we've verified. @daxfohl, have you tried this combination?

**Comment by daxfohl** [comment]
Basic functionality works. I haven't tried the decompose and such also mentioned in the issue. I'd leave it open.

**Comment by daxfohl** [comment]
Also consider adding a has_unitary(sub_op) in the ControlledGate and ControlledOp constructors. Xref #4476

**Comment by daxfohl** [comment]
Everything in @95-martin-orion list above works except it doesn't check qubit overlap. (It doesn't do that for other types of sub_operations either). It also works for mixtures. (Should it work for channels too?)

So just need to add the overlap check and some tests. Plausibly there should be a check that there's no measurement in sub_op, if it's not too slow.

**Comment by daxfohl** [comment]
Added the above PR to check overlapping. There are already tests for decomposition and such.

Leaving an open question as to whether we want to verify no measurements, or whether channels should work.

**Comment by daxfohl** [comment]
IIUC @Strilanc showed that a controlled channel is not well defined. https://quantumcomputing.stackexchange.com/a/12197/14638

So should we add the check for `has_mixture(sub_operation)` in the ControlledOp constructor? (This would apply to ControlledGate as well).

**Comment by 95-martin-orion** [comment]
> IIUC @Strilanc showed that a controlled channel is not well defined. https://quantumcomputing.stackexchange.com/a/12197/14638
> 
> So should we add the check for `has_mixture(sub_operation)` in the ControlledOp constructor? (This would apply to ControlledGate as well).

Yes, I think that's a necessary check. A related observation: `cirq.measure(q0, key='m').controlled_by(q1)` is currently permitted in circuits, but will crash the simulator. This check would resolve both issues.
