### ISSUE TITLE
Why isn't `def run` from `ionq.Service` in `ionq.Sampler`?

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#4008]
**Is your design idea/issue related to a use case or problem? Please describe.**

`ion.Service ` has a `def run_sweep` but the  `def run` is in `service.py`. What are your thoughts @dabacon?

**Comment by dabacon** [comment]
Sorry missing the question here.  `ion.Service` has `run` but no `run_sweep`.  `ion.Sampler` implements `run_sweep` but is a `work.Sampler` so other methods are implemented by calling this.   Is the question why there is no `run_sweep` in `ion.Service`?  We could add that.  The IonQ API doesn't have a notion of sweep, so I was keeping the service close to the api.

**Comment by vtomole** [comment]
I should should have phrased this question better: Why isn't  the `run` function: https://github.com/quantumlib/Cirq/blob/51b56288fa9a84dff9697524da9ab0a4d57a56f5/cirq/ionq/service.py#L89 in `ionq.Sampler`? https://github.com/quantumlib/Cirq/blob/51b56288fa9a84dff9697524da9ab0a4d57a56f5/cirq/ionq/sampler.py#L24

So we can change the body of the `run` function in `Service` to be

```python

def run(
        self,
        circuit: 'cirq.Circuit',
        repetitions: int,
        name: Optional[str] = None,
        target: Optional[str] = None,
        param_resolver: study.ParamResolverOrSimilarType = study.ParamResolver({}),
        seed: 'cirq.RANDOM_STATE_OR_SEED_LIKE' = None,
    ) -> study.Result:
      
 return sampler.Sampler(service=self, target=target, seed=seed).run(cicuit, repetitions, name, target, param_resolver, seed)
```

I see that if we did do that, we'd be overriding the default `work.Sampler.run`, which calls `run_sweep`: https://github.com/quantumlib/Cirq/blob/51b56288fa9a84dff9697524da9ab0a4d57a56f5/cirq/work/sampler.py#L49 so your statement:

> The IonQ API doesn't have a notion of sweep, so I was keeping the service close to the api.  

Answers my question. Thanks.
