### ISSUE TITLE
Documentation code with dead link

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#4066]
**Description of the issue**

On this documentation page:
https://quantumai.google/reference/python/cirq/experiments/xeb_fitting/characterize_phased_fsim_parameters_with_xeb_by_pair
if you click "View source on GitHub" it does not go to a live link.

**Comment by balopat** [comment]
Oh, I think I know what's happening - the API reference generator has the wrong prefix - it still thinks things are under cirq - but they are in fact under cirq-core/cirq... This is an easy fix for cirq-core stuff but a bit trickier for cirq.google stuff... I'll work on it!

**Comment by balopat** [comment]
Actually I'll reopen this until we published the site.
