### ISSUE TITLE
assert_optimize methods should be less brittle

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#407]
Currently, when we test optimizations, we write little helper methods like this one:

```python
def assert_optimizes(before, after):
    opt = MergeInteractions()
    opt.optimize_circuit(before)

    # Ignore differences that would be caught by follow-up optimizations.
    followup_optimizations = [
        MergeRotations(),
        circuits.DropNegligible(),
        circuits.DropEmptyMoments()
    ]
    for post in followup_optimizations:
        post.optimize_circuit(before)
        post.optimize_circuit(after)

    if before != after:
        print('ACTUAL')
        print(before)
        print('EXPECTED')
        print(after)
    assert before == after
```

The problem with the above method is that it is too specific. It checks for the *exact circuit output*. But really we don't particularly care that the circuit is in some specific order or uses some specific gate set, we care about whether or not it's smaller and whether or not it's correct (i.e. equivalent to the original circuit up to some tolerance.).

We should rewrite all of these methods, and possibly combine them into some utility method, with a signature more along the lines of:

```python
def assert_optimizes(initial_circuit, absolute_error_tolerance, optimizing_function, cost_function, min_improvement=0)
```

Though of course it doesn't have to be exactly that.

**Comment by dabacon** [comment]
Aren't both types of tests desirable.  Sometimes you want to indeed show that it has made improvements.  Sometimes you want to make sure it is working for a specific case you are about and that it does the correct thing during optimization (it could improve metric but be broken).  I'd suggest this is a more of "and also make sure that it makes progress on a metric".

**Comment by tanujkhattar** [comment]
As @dabacon mentioned, it's worth testing specific behavior of the optimizer by comparing to exact circuits. We also don't use the `followup_optimizations` approach after migrating to the cirq transformers. I'll mark the issue as stale and close it now.
