### ISSUE TITLE
Utility method to get the completely-positive-trace-preserving map of a circuit

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#408]
This would be useful for testing optimizations on circuits that involve measurements.

**Comment by balopat** [comment]
@Strilanc This basically means implementing `_has_channel_` and `_channel()_` for cases when there are non-unitary operations in the circuit as well, right? So ` cirq.channel(cirq.Circuit(cirq.DepolarizingChannel(0.3)(cirq.NamedQubit("c"))))` would work too.

**Comment by 95-martin-orion** [comment]
Completed in #4365.
