### ISSUE TITLE
Deprecate PauliTransform?

### ISSUE THREAD

**Issue by ybc1991** [quantumlib/Cirq#4088]
Under the `ops.clifford_gate`, there is a data structure `PauliTransform`, which is just a named tuple

```python
PauliTransform = NamedTuple('PauliTransform', [('to', Pauli), ('flip', bool)])
document(PauliTransform, """+X, -X, +Y, -Y, +Z, or -Z.""")
```

The reason I suggest deprecation is
1. It is only used in `SingleQubitCliffordGate`.
2. For multiple qubits Clifford gate, this named structure doesn't fit.
3. We have a replacement now -- `DensePauliString`.
4. The stabilizers and destabilizers of Clifford Tableau return as `DensePauliString` anyway.

The benefit of keeping `PauliTransform` is it is much more light-weighted than `DensePauliString`.  But I think the benefits is marginal.

**Comment by MichaelBroughton** [comment]
@ybc1991 can we close this ?

**Comment by dabacon** [comment]
@MichaelBroughton  I think this still exists.  This is one to deprecate before 0.15?
