### ISSUE TITLE
Circuit diagram consisting of 12v and 4 ohms and 6 ohms resistors

### ISSUE THREAD

**Issue by Selma020513** [quantumlib/Cirq#4109]
**Is your design idea/issue related to a use case or problem? Please describe.**

**Describe your design idea/issue**

**Comment by vtomole** [comment]
Hey @Selma020513, Cirq is used to create [Quantum circuits](https://en.wikipedia.org/wiki/Quantum_circuit) not [Electrical circuits](https://en.wikipedia.org/wiki/Electrical_network). Please let me know if you have any questions. Thanks.
