### ISSUE TITLE
module 'cirq' has no attribute 'work' or '__version__'

### ISSUE THREAD

**Issue by poojithumeshrao** [quantumlib/Cirq#4112]
**Description of the issue**
module 'cirq' has no attribute 'work' or '__version__'
**How to reproduce the issue**

```
pip install cirq==0.11.0
python -c 'import cirq; print(cirq.__version__)'
```

<details>

AttributeError: module 'cirq' has no attribute '__version__'

</details>

tensorflow_quantum v0.5.0 depends on cirq v0.11.0 I am also unable to import tensorflow_quantum as I get the error

<details>

AttributeError: module 'cirq' has no attribute 'work'

</details>

**Cirq version**
You can get the cirq version by printing `cirq.__version__`. From the command line:

```
AttributeError: module 'cirq' has no attribute '__version__'
```
All earlier versions work very fine. I need this version(0.11.0) as the latest release of tfq depends on this.
Can you please clarify if this is the issue only with me? If true can you please help in rectifying this issue. Thank you in advance

**Comment by poojithumeshrao** [comment]
It is working in a fresh environment

**Comment by rmlarose** [comment]
xref https://github.com/quantumlib/OpenFermion-FQE/issues/90#issuecomment-840983121. I think in any environment that already has an earlier Cirq version, `pip install cirq==0.11.0` leads to a broken installation. 

> It is working in a fresh environment

Alternatively, `pip uninstall cirq` before installing 0.11.0 should work.
