### ISSUE TITLE
Default behavior for missing calibration data

### ISSUE THREAD

**Issue by rmlarose** [quantumlib/Cirq#4117]
**Is your feature request related to a use case or problem? Please describe.**

This came up in #4108. The workflow there is: user-defined circuit -> Floquet / XEB characterizations for each pair in the circuit -> run a Loschmidt echo with each characterization. 

The Loschmidt echo circuit contains two-qubit gates on all pairs. So if the user-defined circuit doesn't have all of these pairs, a [`ValueError`](https://github.com/quantumlib/Cirq/blob/master/cirq-google/cirq_google/calibration/workflow.py#L942-L944) is raised  in [`_make_zeta_chi_gamma_compensation`](https://github.com/quantumlib/Cirq/blob/master/cirq-google/cirq_google/calibration/workflow.py#L895) complaining about the missing pairs.

**Describe the solution you'd like**

Should the default behavior be to skip corrections on missing pairs instead of raising an error? If not the default, can it be made an option?

**[optional] Describe alternatives/workarounds you've considered**

For the tutorial in #4108, I can make it so the "user-defined" circuit has all pairs and this isn't a problem. However, this might not be too useful when someone actually tries to use the tutorial with their circuit.

**What is the urgency from your perspective for this issue? Is it blocking important work?**

Seems P0 if any EAP users want to follow the calibration tutorial, but I can get around it for writing the tutorial so it's not blocking.

**Comment by mrwojtek** [comment]
I purposefully made it hard to do such a things because this degrades the performance of the executed circuits.

Maybe we should discuss first the specific case you have and see what's the best solution there?

**Comment by rmlarose** [comment]
Discussed with Wojtek offline and agreed to close this - moments to characterize should come from the circuit being run (which would prevent this error from ever being raised).
