### ISSUE TITLE
Qubits are not remapped in the default measurement key

### ISSUE THREAD

**Issue by smitsanghavi** [quantumlib/Cirq#4124]
**Description of the issue**
When a measurement operation created from `cirq.measure` without an explicit key is remapped to some other qubit, the measurement key does not update.

**How to reproduce the issue**

```
qubit = cirq.LineQubit(0)
op = cirq.measure(qubit)
assert cirq.measurement_key(op) == str(qubit)

qubit2 = cirq.LineQubit(1)
op2 = op.with_qubits(qubit2)
assert cirq.measurement_key(op2) == str(qubit2)
```

The last assertion will fail because the operation does not really process the key as made of the qubit. This might not strictly be a bug, but it would be much nicer to allow users to assume that when no explicit key is specified, Cirq will be smart enough to key the result by the actual qubit(s) that were operated on.

*This issue is mainly for bookkeeping, I already have a fix planned and ready to go. Part of #4040*

**Comment by smitsanghavi** [comment]
Reopening for discussion on what is the desired behavior here.

If there was no explicitly specified name for the measurement, should the final `Results` object be keyed by the qubits that were measured or the qubits that were originally used to create the operation?

**Comment by 95-martin-orion** [comment]
> If there was no explicitly specified name for the measurement, should the final `Results` object be keyed by the qubits that were measured or the qubits that were originally used to create the operation?

From the discussion on this topic, my takeaway was that measurement keys should be defined at construction time so that it's easy to reference them later on (i.e. without having to manually parse through the circuit). Key-renaming in `CircuitOperation`s runs somewhat contrary to this, but depending on the outcome of #4274 that contradiction may also be removed.
