### ISSUE TITLE
`is_measurement` protocol is slow

### ISSUE THREAD

**Issue by smitsanghavi** [quantumlib/Cirq#4141]
Current is_measurement implementation is slow because:

* It delegates to getting all the measurement keys first and then checks for non-emptyness
* Measurement key protocol iterates through each operation in order and decomposes each until it finds `_measurement_key_` or `_measurement_keys_` implemented.
  * Decomposing can be costly and most of the time would be spent on non-measurement operations.
* There is no early exit. Even if we find a measurement, we aren't declaring victory, we wait to gather **all the keys** and create the full set. This is disastrous for big circuits with terminal measurements.

**Comment by mpharrigan** [comment]
Removing bug label, since nothing is truly broken.

Has this been fixed in #4140?

**Comment by smitsanghavi** [comment]
Yes, it has been fixed in #4140. Closing it now.
