### ISSUE TITLE
Circuit validation tool

### ISSUE THREAD

**Issue by viathor** [quantumlib/Cirq#4142]
**Is your feature request related to a use case or problem? Please describe.**

When attempting to execute on quantum hardware, circuits may be rejected for a variety of reasons such as the presence of unsupported gates or requiring interactions incompatible with device's connectivity.

**Describe the solution you'd like**

It is desirable to have a tool that can test or dry-run a circuit to check for all such rejection conditions before sending the circuit for execution on a quantum device.

**[optional] Describe alternatives/workarounds you've considered**

**[optional] Additional context (e.g. screenshots)**

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P2 - we should do it in the next couple of quarters

**Comment by mpharrigan** [comment]
dupe? https://github.com/quantumlib/Cirq/issues/3960
