### ISSUE TITLE
random qubit order from the outcome of the simulation

### ISSUE THREAD

**Issue by JiahaoYao** [quantumlib/Cirq#4144]
**Description of the issue**

The output of the cirq simulation gives random order? But in the document, it says that from the [tutorial](https://quantumai.google/cirq/simulation)
> The qubit_order argument is optional: when it is omitted, qubits are ordered ascending by their name

I have the line qubits 

```
[cirq.LineQubit(0), cirq.LineQubit(1), cirq.LineQubit(2), cirq.LineQubit(3), cirq.LineQubit(4), cirq.LineQubit(5), cirq.LineQubit(6), cirq.LineQubit(7)]
```

When I do 
```
result = noisy_sim.sample(my_circ, repetitions=n_shots)
```

I sometimes got this, 
```
Index(['q4', 'q3', 'q2', 'q5', 'q6', 'q1', 'q7', 'q0'], dtype='object')
```
and another run 
```
Index(['q6', 'q3', 'q2', 'q1', 'q4', 'q5', 'q7', 'q0'], dtype='object')
```

Is this typical, or I have to state the qubit order, but it seems will use `ops.qubitorder.default` if I didn't declare? So is this the bug for the qubit order from the outcome of the simulation? 

**Cirq version**: 0.10.0

**Comment by daxfohl** [comment]
Hi @JiahaoYao can you provide a complete example?

**Comment by JiahaoYao** [comment]
Hi @daxfohl , let me try to figure out how to provide a clear example. Probably will get back to you at a later time.

**Comment by vtomole** [comment]
Hey @JiahaoYao, a clear example would simply be the whole program that generates the results you are getting. What is your `my_circ` variable set to? How about `noisy_sim`? What method are you calling to get `Index(['q4', 'q3', 'q2', 'q5', 'q6', 'q1', 'q7', 'q0'], dtype='object')`?

**Comment by JiahaoYao** [comment]
Hi @vtomole and @daxfohl , thanks for your patience. Here is the MWE to reproduce the issue: 

```python
import cirq
qr = cirq.LineQubit.range(6)
circuit = cirq.Circuit([cirq.H(qr[0]), [cirq.CNOT(qr[0], qr[i]) for i in range(1, 6, 1)], [cirq.measure(qr[i], key="q{}".format(i)) for i in range(len(qr))]])
result = cirq.Simulator().sample(circuit, repetitions=100)

print(result.columns)
```

Here is also the minimal runnable notebook: [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1x5JbOSJxEw3WzekVcdOAM9wHN5ZcW1MI?usp=sharing)

**Comment by JiahaoYao** [comment]
looks like the ordering of qubit can not be controlled, wonder if this is because the data frame does not preserve the ordering.

**Comment by daxfohl** [comment]
Seems to be a documentation error. I don't see any evidence in the code that this would have ever worked. I tried running this in versions back to 2019 and got similar results.

**Comment by JiahaoYao** [comment]
Hi @daxfohl, thank you for spending time looking into this! I really appreciate it! I very much agree with you and thank you again!
