### ISSUE TITLE
Inconsistencies in user experience when creating circuits with devices. 

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4151]
**Is your design idea/issue related to a use case or problem? Please describe.**
When creating circuits for a particular device, should the users be responsible for ensuring that they only use the native gates in the circuit, and if not, first explicitly convert the circuit to one containing only native gates, using one of the existing compilation tools? Or should the device class be smart enough to do this conversion via the `decompose_operation` method on the device class? 

**Describe your design idea/issue**
For example, a simple QFT circuit on 3 qubits behaves differently when created using an `IonQ` device vs `Sycamore` device. 

### Using IonQ device
The compilation happens as part of the construction because `decompose_operation` as takes care of the steps. 
```python
num_qubits = 2
qubits = cirq.LineQubit.range(num_qubits)
cirq.Circuit(cirq.QuantumFourierTransformGate(num_qubits)(*qubits), device = cirq.ionq.IonQAPIDevice(qubits))
```
compiles fine to the device compatible circuit
```
0: ───Y^0.5──────Z^0.393───XX────────YY────────ZZ─────────Z^(-9/14)───X^0.5──────S───
                           │         │         │
1: ───Z^-0.607─────────────XX^-0.5───YY^-0.5───ZZ^-0.25───X───────────Z^(9/14)───────
```

### Using Sycamore device
The same workflow as above throws an error that the `QFT` gate is not supported. 
```python
num_qubits = 2
qubits = cirq.GridQubit.rect(1, num_qubits, 4, 4)
cirq.Circuit(cirq.QuantumFourierTransformGate(num_qubits)(*qubits), device = cirq.google.Sycamore)
```
gives
```bash
ValueError: qft((4, 4), (4, 5)) is not a supported gate
```

Instead, the circuit first needs to be compiled to device compatible gateset:

```python
num_qubits = 2
qubits = cirq.GridQubit.rect(1, num_qubits, 4, 4)
circuit = cirq.Circuit(cirq.QuantumFourierTransformGate(num_qubits)(*qubits))
cirq.Circuit(cirq.google.ConvertToSycamoreGates().convert(circuit), device = cirq.google.Sycamore)
```

gives the correct device compatible circuit

```
(4, 4): ───PhXZ(a=-1,x=0.393,z=0)────PhX(0.568)^0.586───SYC───PhX(0.0677)─────────SYC───PhX(-0.599)^0.414───Z^(2/3)────────────────────PhXZ(a=0.5,x=0.5,z=0)───PhX(0.568)^0.586───SYC───PhX(0.0677)─────────SYC───PhX(-0.599)^0.414───Z^(2/3)───────────────────PhXZ(a=-0.5,x=0.5,z=0)──────PhXZ(a=-1.11e-16,x=0.724,z=0.0833)───SYC────────────────SYC───PhXZ(a=-0.0833,x=0.724,z=-0.917)───Rz(0.25π)───PhXZ(a=-0.607,x=0.5,z=0)───PhXZ(a=-0.607,x=0,z=-0.893)───
                                                        │                         │                                                                                               │                         │                                                                                                                    │                  │
(4, 5): ───PhXZ(a=0.107,x=0.5,z=0)───PhX(0.355)─────────SYC───PhX(-0.515)^0.523───SYC───Z^-0.926────────────PhXZ(a=-0.893,x=0.5,z=0)───PhX(0.355)─────────────────────────────────SYC───PhX(-0.515)^0.523───SYC───Z^-0.926────────────PhXZ(a=0.107,x=0.5,z=0)───PhXZ(a=0.542,x=0,z=0.917)────────────────────────────────────────SYC───Rx(0.189π)───SYC───PhXZ(a=0.227,x=2.22e-16,z=0.25)────Rz(0.25π)───PhXZ(a=0.554,x=1,z=0)──────PhXZ(a=-0.393,x=0,z=0.893)────

```

**Comment by tanujkhattar** [comment]
As per the discussion #3295, It looks like circuit construction with device attribute should be deprecated.

**Comment by balopat** [comment]
ref #3244 and #3245

**Comment by balopat** [comment]
Discussed on Cirq cynque: 
- we'll punt on this for now - it might not be that big of an issue as well as we are revisiting devices

**Comment by tanujkhattar** [comment]
Let's change the scope of this issue to add support for an explicit compiler for IonQ as we plan on deprecating the device object in a circuit (i.e. `cirq.Circuit( op_list, device = cirq.ionq.IonQAPIDevice(qubits))` would be deprecated)

**Comment by MichaelBroughton** [comment]
@tanujkhattar Can we close this since we aren't attaching devices to circuits anymore ?
