### ISSUE TITLE
Allow MatrixGate to be less strict w.r.t. unitarity

### ISSUE THREAD

**Issue by shukob** [quantumlib/Cirq#4173]
**Is your feature request related to a use case or problem? Please describe.**
If I use an almost unitary (because of numerical error) matrix using e.g. `scipy.linalg.expm` to construct input for `MatrixGate` with `dtype` of `np.complex64`, `allclose` should be less strict for it to pass unitarity check. If I use `np.complex128` instead, it passes but some simulators like `QsimSimulator` do not accept `np.complex128` for its `dtype`.

**Describe the solution you'd like**
I can specify `rtol/atol` for `linalg.is_unitary` as optional arguments to `MatrixGate.__init__`.

**What is the urgency from your perspective for this issue? Is it blocking important work?**
P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle

**Comment by balopat** [comment]
I am actually surprised that atol/rtol is not propagated to the constructor, we typically (should) do that! Good first issue for someone, as it should be relatively easy to introduce these with the same defaults `is_unitary` has.
