### ISSUE TITLE
cirq/protocols/quil.py has no tests

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#4178]
**Description of the issue**

/cirq/protocols/quil.py does not have any tests.  Not sure how it got past the coverage check.  (Quil code in contrib does have tests).

**Comment by balopat** [comment]
I think cirq.circuits.quil_output_test.py covers it...

**Comment by joesho112358** [comment]
I think this might be able to be closed. I do not see that file anymore, and the replacements (I think) look to be tested:
https://github.com/quantumlib/Cirq/blob/master/cirq-rigetti/cirq_rigetti/quil_input.py
https://github.com/quantumlib/Cirq/blob/master/cirq-rigetti/cirq_rigetti/quil_input_test.py

https://github.com/quantumlib/Cirq/blob/master/cirq-rigetti/cirq_rigetti/quil_output.py
https://github.com/quantumlib/Cirq/blob/master/cirq-rigetti/cirq_rigetti/quil_output_test.py

**Comment by dstrain115** [comment]
This has been moved to rigetti and has tests.  Closing.
