### ISSUE TITLE
GateOperation doesn't forward qubits to Gate for _mixture_ and _channel_

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#4186]
I was trying to implement a gate that had a mixture, and noticed implementing `_mixture_` didn't actually work because `GateOperation._mixture_` forwards directly, without giving any qubit information to the gate mixture method (like `_decompose_` does) and without filling in qubit information on the way out. The same appears to be true of `_channel_`.

**Comment by Strilanc** [comment]
Okay, looking at this more, I realize the issue is that I thought I could return things besides unitary matrices in the mixture.

**Comment by viathor** [comment]
@Strilanc Should we close this?

**Comment by Strilanc** [comment]
Discussed at cirq design meeting; should be fixed but not necessarily in the way the title suggests. Mainly we should be able to return things besides matrices from mixture.

**Comment by daxfohl** [comment]
I noticed this when working with DepolarizingChannel from Clifford simulators. It would be nice for Clifford simulators if it could return a mixture of Pauli gates instead of raw matrices. Clifford can't use the matrices directly and has to recompile the matrices into gates, which is slower.

**Comment by daxfohl** [comment]
Dupe of https://github.com/quantumlib/Cirq/issues/1657?

**Comment by MichaelBroughton** [comment]
Gonna close since this does look like a dupe.
