### ISSUE TITLE
Add `circuit.num_operations()`

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#4187]
**Is your feature request related to a use case or problem? Please describe.**
I want the number of operations in a circuit.

**Describe alternatives/workarounds you've considered**
```python
import cirq

qubit = cirq.LineQubit(0)
circuit = cirq.Circuit(cirq.H(qubit))
num_operations = len(list(circuit.all_operations())))
```
**What is the urgency from your perspective for this issue? Is it blocking important work?**
P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle

**Comment by 95-martin-orion** [comment]
Discussed at Cirq sync: difficulty in defining a "canonical" num_operations in the presence of CircuitOperations / classical control make this something that should be handled on a case-by-case basis.
