### ISSUE TITLE
[docs] Error message in output cell

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#4197]
**Description of the issue**

https://quantumai.google/cirq/operators_and_observables#noisy_channels has an output cell with this error message below the result: 

```
/home/kbuilder/.local/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: coroutine 'Collector.collect_async' was never awaited
  """
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

it's in the expectation values section:

![image](https://user-images.githubusercontent.com/635073/121787802-337b4800-cb7d-11eb-9ddd-229344abb781.png)

**Comment by rmlarose** [comment]
#4004 was seeking to address this. Also #4009.

**Comment by dstrain115** [comment]
This seems to be fixed and the warning no longer shows up on the page.
