### ISSUE TITLE
Error from --color argument in check/format-incremental

### ISSUE THREAD

**Issue by asmuzsoy** [quantumlib/Cirq#4211]
**Description of the issue**
When running the format-incremental check, the following error is produced:

```
Comparing against revision 'origin/master'.
Running flynt v.0.64
Running the black formatter...
Usage: black [OPTIONS] [SRC]...
Try 'black -h' for help.

Error: no such option: --color
```
Perhaps disabling the flag would fix this issue.

**How to reproduce the issue**

Running the following in the Cirq directory:
```
./check/format-incremental --apply
```

**Cirq version**
0.11.0

**Comment by vtomole** [comment]
I can't reproduce this error. What do you get when you execute the following on your machine?

```
vtomole@vtomole:~/Cirq$ black --version
black, version 20.8b1
vtomole@vtomole:~/Cirq$ black cirq-core/cirq/circuits/circuit.py --color
All done! ✨ 🍰 ✨
1 file left unchanged.
```

**Comment by asmuzsoy** [comment]
at the time it was 19.10b0. Now, I've upgraded it to 21.6b0 and no longer get the error.

**Comment by vtomole** [comment]
Good stuff 😄 . Note that we default to [20.8b1](https://github.com/quantumlib/Cirq/blob/72993b5081520d144472f37cd76f1cc2c5f990f6/dev_tools/requirements/deps/format.txt#L2).
