### ISSUE TITLE
cirq.MergeInteractions should also allow FSim and other future decompositions

### ISSUE THREAD

**Issue by cduck** [quantumlib/Cirq#4214]
**Is your feature request related to a use case or problem? Please describe.**

Currently the circuit optimizer `cirq.MergeInteractions` produces circuits with CZ (or parameterized CZ) gates by using `cirq.two_qubit_matrix_to_operations()` to decompose arbitrary two-qubit unitaries.  Now that decompositions exist for the FSim gate (`cirq.decompose_two_qubit_interaction_into_four_fsim_gates()` with a different API) and soon the [sqrt-iSWAP gate](#4083), there should be a single or consistent API to access these.

I noticed this while working on #4083.

**Describe the solution you'd like**
`MergeInteractions` and `two_qubit_matrix_to_operations` could have a *gate set* parameter that lets them choose which decomposition to use.  It could simply be an argument `gate=CZ` or `gate=FSim(theta, phi)` but I'm not sure the best design.

**Describe alternatives/workarounds you've considered**
Write separate circuit optimizers for FSim and other primitive gates.

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle

**Comment by 95-martin-orion** [comment]
This is something @tanujkhattar is looking into as part of #3243 - in the long term, we'd like to migrate all of these into the decomposition API. Adding new decompositions before then is fine, but they'll also need to be migrated.
