### ISSUE TITLE
Failed to import Ansatz

### ISSUE THREAD

**Issue by ChrisW918** [quantumlib/Cirq#4238]
I followed the instruction in github to import types of ansatz from _openfermioncirq.varional_ , but it reports the fault:

_ModuleNotFoundError: No module named 'openfermion.ops._givens_rotations'_

I tried to check the _ops_ package, and it turns out that _givens_rotations_ has been removed.

How can I deal with this? Or are there other ways to import ansatz?

**Comment by vtomole** [comment]
Hey, @ChrisW918 . This is an OpenFermion issue. I'm going to close it because it's a duplicate of https://github.com/quantumlib/OpenFermion/issues/732.
