### ISSUE TITLE
rename master to main

### ISSUE THREAD

**Issue by stubbi** [quantumlib/Cirq#4243]
I just realized that the default branch of this repo is called `master`. Should this repo adopt the new `main` branch convention?

In case yes, [this](https://github.com/github/renaming#renaming-the-default-branch-from-master) might help.

**Comment by vtomole** [comment]
What will be gained by renaming? This is probably super bikeshedy 😅

**Comment by vtomole** [comment]
What will be gained by renaming?

**Comment by balopat** [comment]
I was planning to do this in the coming weeks, thanks for bringing it up! 
@vtomole - the industry is moving away from terms with historical baggage of misuse and oppression - e.g. `master`, `blacklist`, `whitelist`, etc. E.g. see https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/ - Github itself is now creating new repos with `main`.

**Comment by vtomole** [comment]
@balopat I see. Good to know!

**Comment by dstrain115** [comment]
This has been completed.
