### ISSUE TITLE
Modify type annotation in FSimGate constructor from float to TParamVal

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4244]
**Description of the issue**
`FSimGate`s  support symbols as valid parameter arguments for `theta` and `phi`.  However, the type annotation in constructor is `float` which can be confusing. 

https://github.com/quantumlib/Cirq/blob/12530f1531e5da663a6b172b1967763e08819912/cirq-core/cirq/ops/fsim_gate.py#L81

Modify the type annotation to `TParamVal` - which is a `Union[float, sympy.Basic]` i.e.

```python
    def __init__(self, theta: value.TParamVal, phi: value.TParamVal) -> None:
```

As a follow up, find and fix other gates in Cirq with a similar issue.

**Cirq version**
0.12.0.dev

**Comment by stubbi** [comment]
@tanujkhattar checking with `grep` shows

```
$ grep -i "theta: float" -r *
cirq-core/cirq/ops/diagonal_gate.py:        self, index: int, bit_flip: int, theta: float, qubits: Sequence['cirq.Qid']
cirq-core/cirq/ops/fsim_gate.py:    def __init__(self, theta: float, phi: float) -> None:
cirq-google/cirq_google/calibration/workflow_test.py:    theta: float, zeta: float, chi: float, gamma: float, phi: float
cirq-google/cirq_google/calibration/workflow_test.py:    theta: float, zeta: float, chi: float, gamma: float, phi: float
cirq-google/cirq_google/optimizers/convert_to_sycamore_gates.py:    theta: float, a: cirq.Qid, b: cirq.Qid
cirq-google/cirq_google/optimizers/convert_to_sycamore_gates.py:def rzz(theta: float, q0: cirq.Qid, q1: cirq.Qid) -> cirq.OP_TREE:
cirq-google/cirq_google/optimizers/convert_to_sycamore_gates.py:def cphase(theta: float, q0: cirq.Qid, q1: cirq.Qid) -> cirq.OP_TREE:
cirq-google/cirq_google/optimizers/convert_to_sycamore_gates.py:def swap_rzz(theta: float, q0: cirq.Qid, q1: cirq.Qid) -> cirq.OP_TREE:
cirq-google/cirq_google/common_serializers.py:def _can_serialize_limited_fsim(theta: float, phi: float):
```

Should it be fixed in the other files as well?

**Comment by stubbi** [comment]
assuming yes, I opened #4266

**Comment by tanujkhattar** [comment]
The main idea behind this request is that we should fix the type annotation from `float` to `Union[float, sympy.Basic]` (i.e. `TParamVal`) wherever the function _**can actually accept symbols**_ but the type annotation is incorrect.  Given this request, I propose we 
- Try to figure out why tools like `mypy` don't already detect the places where type annotation is wrong? (eg: not enough tests covering the different types which can be accepted? or maybe some other issue?)
- For all the places where we are able discover wrong types (eg: by searching for `grep -i ": float" -r *` instead?), we should fix them. 

We could simply start by fixing `FSimGate` but I think figuring out why `mypy` doesn't already complain would be very useful.

**Comment by hohilwik** [comment]
Hi, this is a problem related to #554 as well. Mypy doesn't catch wrong type annotation in many cases. Is there anything I can do in that issue which would help with this?

**Comment by daxfohl** [comment]
@tanujkhattar @MichaelBroughton this was done in #5075

**Comment by dstrain115** [comment]
Per @daxfohl this is complete.
