### ISSUE TITLE
NoCompile Tag for optimizers

### ISSUE THREAD

**Issue by dstrain115** [quantumlib/Cirq#4253]
**Is your feature request related to a use case or problem? Please describe.**
Certain use cases involve creating gates that should not be optimized.  For instance, if you add spin echoes to an idle qubit to decrease dephasing errors, you do not want a merging optimizers to collapse them down again.  Other benchmarking cases may want this as well.

**Describe the solution you'd like**
I would like to add a tag (either to cirq-core or to cirq-google) that specifies that compiles should skip this gate.  Perhaps NoOptimizeTag() or something like that.

**[optional] Describe alternatives/workarounds you've considered**

**What is the urgency from your perspective for this issue? Is it blocking important work?**
P1 - I need this no later than the next release (end of quarter)

High priority nice-to-have, since it is blocking a nice end-to-end example of combining various optimization techniques together in order to increase fidelity.

**Comment by vtomole** [comment]
I thought this was done as part of https://github.com/quantumlib/Cirq/issues/2642.  It seems like `tags` were implemented but not `NoOptimizeTag()`.

**Comment by pgoiporia** [comment]
Hey! I'm new to cirq and I want to create/use a NoOptimizeTag. How should I do it? More specifically, I was hoping to create a cirq equivalent of barriers in qiskit/openqasm, so would there be a way to tag a group of successive operations with a NoOptimizeTag? Thank you!

**Comment by pgoiporia** [comment]
Created a draft pull request for this issue. Created a nocompile tag and edited the drop_negligible optimizer so as to ignore any gate that has a nocompile tag to it. Need to create test cases for the drop_negligible. Will continue editing the other optimizers as well and create tests for them.

**Comment by tanujkhattar** [comment]
We need to further clarify the requirements for supporting `NoCompile` tag in transformers. For example, Let `op` be an operation tagged with `NoCompile` tag which occurs in moment `i`. 

1. An obvious constraint on `op` is that transformers should not merge/decompose/drop the operation `op` and hence `op` should still be present in the circuit. But `2.` and `3.` below are more nuanced.
2. Is it okay if `op` gets shifted to another moment? Or should `op` occur in the same moment `i` ? Some examples in which `op` can get shifted to another moment is when 
    a. We stratify the circuit to align 1/2q gates.
    b. Some other operations to the left of `op` are merged/decomposed, hence destroying the moment structure of the circuit.
3. Is it allowed to move other commuting operations across `op`, without changing `op`? 

I would expect a `NoCompile` tag to satisfy only `1.` and a barrier to satisfy `1.` and `3.`.

**Comment by tanujkhattar** [comment]
All circuit optimizers have been migrated to the new transformer framework, which supports adding no compile tags for every transformer. I'll therefore mark this as complete and close the issue.
