### ISSUE TITLE
Google tutorial docs boilerplate

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#4260]
There's quite a wall of boilerplate code to go along with the cirq.google tutorials to handle the various cases: [simulator, engine] x [colab, ipython, other] x [explicitly set, environment variable].

We should factor this out into a library function that you can call to do auth and get a device and sampler (and maybe an engine? we don't have a simulator analog of engine)

**Comment by balopat** [comment]
I'm totally pro this change, it would cut a lot of the cirq.google notebooks. I think this would be an ideal starter project for someone.

**Comment by AnimeshSinha1309** [comment]
Can you please give an example of such boilerplate code, I want to pick up this issue, but I am new and not sure of what tutorial exactly is being talked about.

**Comment by mpharrigan** [comment]
e.g. cell 3 of https://github.com/quantumlib/Cirq/blob/master/docs/tutorials/google/floquet_calibration_example.ipynb

**Comment by AnimeshSinha1309** [comment]
```python
def get_data(project_id=None, processor_id=None):
    # Body of the function
    return device, sampler, line_length
```

Are these the tasks I am supposed to perform?
1. Make a function in the form of the prototype above
2. Add it to some file, presumably `cirq_google/engine/engine.py`
3. Remove all print statements in the body of the function, add logging if necessary, except for Google Colab authentication

Should the line-length be in the final return type, and are the rest of the steps correct?

**Comment by AnimeshSinha1309** [comment]
I am facing the following issues in executing these plans, I have made a PR of my current state, could someone please let me know if I am on the right track and how to resolve these two issue? Thanks.
> The code that was copied from the tutorials includes `IPython` and `google.colab`, both of which do not have type hints. I am unable to add my stubs. This is what is making the Type check fail.
> The other issue is the coverage, the `authenticate_user` method actually attempts to authenticate on Google cloud, I cannot provide a test project id and processor.
