### ISSUE TITLE
can_add_moment and validate_circuit can be inconsistent

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#4272]
**Is your design idea/issue related to a use case or problem? Please describe.**

`Device.can_add_operation_into_moment` should be the "online" version of at least a subset of the constraints that `Device.validate_circuit` validates. However, one can implement a Device inconsistently. 

**Describe your design idea/issue**

E.g. this imaginary device, that only allows for X gates to be executed in separation from other gates implements this constraint inconsistently. The test below should pass but it fails - as `validate_circuit` shares zero behavior / logic with `can_add_operation_into_moment`. This seems to me like a design flaw.

```
def test_weird_device():
    class LonelyXDevice(cirq.Device):
        def can_add_operation_into_moment(
        self, operation: 'cirq.Operation', moment: 'cirq.Moment'
    ) -> bool:
            return all(not isinstance(op.gate, cirq.XPowGate) for op in moment.operations)

    a,b = cirq.LineQubit.range(2)
    circuit = cirq.Circuit(cirq.X(a))
    d = LonelyXDevice()
    assert not d.can_add_operation_into_moment(cirq.X(b), circuit[0])
    # invalid circuit
    circuit.append(cirq.X(b))
    with pytest.raises(ValueError):
        d.validate_circuit(circuit)
```

Related to: #3295, #3244.

**Comment by dstrain115** [comment]
This can be closed as part of the new Devices API which no longer has can_add moment in the interface.
