### ISSUE TITLE
Remove bazel

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#4280]
**Description of the issue**

Now that there is no dependency of TFQ on our protos (https://github.com/tensorflow/quantum/pull/590), we can remove all the bazel functionality.

**Comment by 95-martin-orion** [comment]
How does this interact with Google-internal usage of Cirq, which is (or will soon be) required for QCS? Presumably, the internal code relies on internal Bazel for building Cirq - we should make sure that those definitions are preserved (even if they move to internal-only).

We can discuss the internal Cirq requirements offline if you have questions.

**Comment by balopat** [comment]
My understanding is that it does not interact with it at all. The BUILD/WORKSPACE files are all excluded in the copybara imports and controlled internally for blaze (otherwise internal targets would need to be open sourced, which would not be too meaningful).
