### ISSUE TITLE
Density matrix factoring incorrect 

### ISSUE THREAD

**Issue by daxfohl** [quantumlib/Cirq#4292]
**Description of the issue**
Ref conversation on #4100
**How to reproduce the issue**

```

put code in code blocks *like this*

```

<details>

put long logs in details blocks *like this*

</details>

**Cirq version**
You can get the cirq version by printing `cirq.__version__`. From the command line:

```
python -c 'import cirq; print(cirq.__version__)'
```

**Comment by mpharrigan** [comment]
For the historical record, can you link to the actual conversation of note and/or summarize the issue in the original post here

**Comment by 95-martin-orion** [comment]
Conversation is in [this comment](https://github.com/quantumlib/Cirq/pull/4100#issuecomment-875169467) and below. Brief summary: density matrix factorization was relying on state vector factorization, which attempted to normalize the factored state. This produced density matrices with trace != 1 when split-state simulation was enabled.
