### ISSUE TITLE
npm issues on PRs

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#4293]
**Description of the issue**

I saw this on two PRs today: 

https://github.com/quantumlib/Cirq/runs/3011265236
https://github.com/quantumlib/Cirq/pull/4004/checks?check_run_id=3011531826

```
Run check/npm ci
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-07-07T17_30_21_900Z-debug.log
Error: Process completed with exit code 1.
```

**Comment by balopat** [comment]
It is probably related to https://github.com/actions/setup-node/issues/268

**Comment by dstrain115** [comment]
@95-martin-orion Can this issue be closed now?
