### ISSUE TITLE
JSON backwards compatibility has been flushed

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#4318]
https://github.com/quantumlib/Cirq/pull/4099 cleared some deprecated classes. Serialized files have a much longer lifespan than code. It was always the intent to keep much longer-term backwards compatibility for data files, especially experimental results which likely have `cirq.TrialResult` classes.

1) the old TrialResult.json should be kept around like the "inward" files 
2) The resolver should re-direct "TrialResult" keys to `cirq.Result`. In some sense, this should have been done along with the initial rename.

**Comment by dstrain115** [comment]
Oops, let's fix this ASAP.
