### ISSUE TITLE
Add `cirq.state_vector_to_probabilities`

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#4322]
**Is your feature request related to a use case or problem? Please describe.**
I need a function that takes in a `state_vector` and returns the probabilities of it's amplitudes.

**Describe the solution you'd like**
Add a `def state_vector_to_probabilities()` to 
https://github.com/quantumlib/Cirq/blob/master/cirq-core/cirq/value/probability.py

**[optional] Describe alternatives/workarounds you've considered**
Defined my own:
```python
from cirq.value.probability import validate_probability
def state_vector_to_probabilities(state_vector: np.ndarray) -> np.ndarray:
      probabilities = np.abs(state_vector) ** 2
      validate_probability(probabilities, "sum of the amplitudes of the state vector")
      return probabilities

```
**What is the urgency from your perspective for this issue? Is it blocking important work?**
P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle

**Comment by Patil2099** [comment]
I would love to take this up.

**Comment by mpharrigan** [comment]
Also go through and see where in Cirq probabilities are being used and replace with this function

**Comment by prathameshbhole** [comment]
Is someone currently working on this issue because the corresponding pull request failed tests and is not updated since past 14 days. I think there is no need to validate the probability if we normalize the state_vector first.

**Comment by vtomole** [comment]
Hey @prathameshbhole, I've pinged @Patil2099.

**Comment by ishmum123** [comment]
Hi @vtomole if no one's working on this ATM I would love to take this up

**Comment by vtomole** [comment]
@ishmum123 It seems like @Patil2099 hasn't responded to my ping. Feel free to look at this issue.

@prathameshbhole Yeah, that's right.

**Comment by ishmum123** [comment]
@mpharrigan there seems to be a quite a few cases where this functionality is being used. Should I try to refactor them?

**Comment by mpharrigan** [comment]
Yes, I believe my comment https://github.com/quantumlib/Cirq/issues/4322#issuecomment-888539664 was me hastily transcribing notes from the Cirq Cync call that requested exactly that.

**Comment by ishmum123** [comment]
@mpharrigan I refactored some of the files. However, these files - 
fidelity_esitmation.py, measures.py, projector.py, state_vector.py, states.py
fail to pass the tests after refactor. Throwing errors along the lines of `shape mismatch` and `invalid norm`
