### ISSUE TITLE
ParamResolver is hashable but mutable

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#4327]
This is bad!

```python
pdict = {'beta': 0.11, 'gamma': 0.3}
pdict
Out[11]: {'beta': 0.11, 'gamma': 0.3}
p = cirq.ParamResolver(pdict)
p
Out[13]: cirq.ParamResolver({'beta': 0.11, 'gamma': 0.3})
hash(p)
Out[14]: 9055359463938249742
pdict['beta'] = 5
p
Out[16]: cirq.ParamResolver({'beta': 5, 'gamma': 0.3})
hash(p)
Out[17]: 9055359463938249742
```

**Comment by balopat** [comment]
X-ref https://github.com/quantumlib/Cirq/issues/1837 - maybe we should just deprecate it?

**Comment by 95-martin-orion** [comment]
> X-ref #1837 - maybe we should just deprecate it?

Added a comment there - IMO, that issue should be closed as obsolete. `ParamResolver` now provides a nontrivial speedup over what is possible with function-based parameter resolution by memoizing complicated parameter mappings.

**Comment by mpharrigan** [comment]
If we deprecate it, should we have a hashable version? Presumably hash support was added for a reason (?)

**Comment by 95-martin-orion** [comment]
The main use case I'm aware of for hashing `ParamResolver` is to support hashable `CircuitOperation`s, but the behavior is as old as the class itself (#96).

**Comment by maffoo** [comment]
Very few things in python are _truly_ immutable; would we be okay just documenting that `ParamResolver` expects that the dict passed to it will not be mutated, or do we want to try to more enforce immutability more strictly? One possibility would be to make a defensive copy of the input dict, as in https://github.com/quantumlib/Cirq/pull/4329, but this may have performance implications in tight loops, such as sweeps over circuits.

**Comment by 95-martin-orion** [comment]
This is already documented:
https://github.com/quantumlib/Cirq/blob/f1ea0bd78ce3b287ca925c2306919134650c2607/cirq-core/cirq/study/resolver.py#L53
I'm loath to introduce performance reductions to ParamResolver specifically as it's part of the cirq-to-qsim translation hot path, which we're actively trying to speed up.

**Comment by dabacon** [comment]
A decision on this should be made, it looks like it is floating without a clear decision on what to do.  Marked triage/discuss to bring this up.

**Comment by mpharrigan** [comment]
I think it's pretty bad that we're caching hashes of a dictionary-like object. Python dictionaries are not hashable because they can mutate. It would be even worse if they cached their hash value.

**Comment by dstrain115** [comment]
Discussion from cirq cync:  One possibility (unverified but might work) is to remove hashing capability from ParamResolver and CircuitOperation.

**Comment by 95-martin-orion** [comment]
Lessons from un-hashing experiment: more pain than it's worth, likely introduces new and exciting issues.

The chosen resolution for this at the Cirq sync is outlined in #5507: we'll make the relevant fields "private" and use properties to at least let mypy identify sketchy behavior.
