### ISSUE TITLE
CircuitOperation should not rely on the hash of a `ParamResolver`

### ISSUE THREAD

**Issue by MichaelBroughton** [quantumlib/Cirq#4332]
**Description of the issue**
If we want to get closer to resolving #1837 and given #4329 , we might want to try and move `CircuitOperation`s hash function off of relying on `ParamResolver`s hash function.
Things like:
```python3
pdict = {'beta': 0.11, 'gamma': 0.3}
p = cirq.ParamResolver(pdict)
assert p.param_dict == {'beta': 0.11, 'gamma': 0.3}
x = hash(p)
p.param_dict['beta'] = 5
x2 = hash(p)
x == x2
True
```
make me a little nervous. What're your thoughts here @95-martin-orion ?

**Comment by 95-martin-orion** [comment]
Added a comment on #1837. What this comes down to is a design decision between high-performance resolution of params and strict adherence to the "don't hash mutable objects" rule: removing the hash (or somehow making `ParamResolver` immutable) might be _possible_, but it will almost certainly slow down our parameter-parsing code.

In my opinion, performance is the more important consideration; if we document it well ([example](https://github.com/quantumlib/Cirq/blob/dc013726c9472d39bc2a3909208e188fb535e081/cirq-core/cirq/study/resolver.py#L49)) and put adequate guardrails in place (like #4329), I think the "mutable" hash is permissible.

**Comment by maffoo** [comment]
+1 for optimizing for performance here. We can put some guardrails around `ParamResolver`, but it's almost impossible to make anything in python _truly_ immutable, so we are probably always going to have to live with problems like this at some level.

**Comment by MichaelBroughton** [comment]
> What this comes down to is a design decision between high-performance resolution of params and strict adherence to the "don't hash mutable objects" rule

Sorry I was more thinking along the lines of "can we make CircuitOperation no longer rely on the hashing ability of ParamResolver". Not nescessarily by removing ParamResolvers ability to hash, but maybe just by removing the call to `hash(paramResolver instance)` the in the hash function of CircuitOperation ? If it's easy enough It'd mean users have one less way to potentially go astray.

**Comment by 95-martin-orion** [comment]
> can we make CircuitOperation no longer rely on the hashing ability of ParamResolver

Probably not? `ParamResolver` is how `CircuitOperation` contains its parameter mappings, so the only ways I can see us getting rid of this dependency are:

1) Remove parameter mapping from `CircuitOperation`
2) Replace `ParamResolver` with a hashable mapping structure (tuple of tuples?)
3) Remove it entirely, and decide we're okay with making meaningfully-distinct `CircuitOperation`s have the same hash

(1) should be avoided unless it's a major issue for users. (2) is possible, but very awkward (which is part of why `ParamResolver` exists). To be honest, I have no idea what the ramifications of (3) would be, it just seems unwieldy to me.

NB that `ParamResolver` is not the only violation of "don't hash immutable objects" in `CircuitOperation`: it also uses `Dict` for qubit and measurement key maps and declares them immutable by fiat (i.e. in docstrings).

**Comment by 95-martin-orion** [comment]
Closing as won't-fix; given the lack of further discussion it looks like we're happy optimizing for performance.
