### ISSUE TITLE
random_quantum_circuit_generation potential speed improvement

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#4337]
As someone who's in the habit of creating a bunch of random quantum circuits, I noticed that it's pretty slow. I ran `snakeviz` on the creation of a lot of random circuits. The total cumulative time is 7.9s and 3.28s was spent in line 658. With some digging: it looks like the while loop to exclude consecutive single-qubit gates is big slow. In particular, it spends a decent amount of time canonicalizing PhasedXZ gates to make sure the current gate isn't the same as the previous one. 

You can very easily imagine switching to sampling gates not by value equality, but by index into the set of possible single qubit gates. You could probably do a more sophisticated way of choosing "random number between 0 and n except for x" than repeatedly sampling and rejecting.

**Comment by mpharrigan** [comment]
I don't think this is skill-level/advanced. only normal cs skills required

**Comment by daxfohl** [comment]
Line 658 of what?

**Comment by mpharrigan** [comment]
Yeah sorry. The file/module name is in the issue title. I could have been much more clear!
