### ISSUE TITLE
Quil output with writable classical memory

### ISSUE THREAD

**Issue by rmlarose** [quantumlib/Cirq#4339]
**Is your feature request related to a use case or problem? Please describe.**

In `QuilOutput`, the [measurement id convention](https://github.com/quantumlib/Cirq/blob/master/cirq-core/cirq/circuits/quil_output.py#L128-L138) returns PyQuil memory declarations that are read-only. From the [PyQuil docs](https://pyquil-docs.rigetti.com/en/v3.0.0/basics.html#qpu-allowable-quil):

```text
The only memory that is writeable is the region named ro, and only through MEASURE instructions. 
All other memory is read-only.
```

This means that measurements are always empty when you run any program from `QuilOutput` (unless you manually change the memory declarations and measurements).

**Describe the solution you'd like**

`QuilOutput` to return a program with writeable memory - namely, a program with a single memory declaration called `"ro"` with a number of bits equal to the number of measurements in the circuit, and all measurements writing into `"ro"`.

**[optional] Additional context (e.g. screenshots)**

Current behavior:

```python
import cirq

q = cirq.LineQubit(0)
circuit = cirq.Circuit(cirq.H(q), cirq.measure(q))
print(circuit.to_quil())
```

Output:

```text
# Created using Cirq.

DECLARE m0 BIT[1]

H 0
MEASURE 0 m0[0]
```

Desired output (`m0` -> `ro`):

```text
# Created using Cirq.

DECLARE ro BIT[1]

H 0
MEASURE 0 ro[0]
```

**[optional] Describe alternatives/workarounds you've considered**

Asking the PyQuil folks to allow additional writable memory references... 🙃

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P2 - we should do it in the next couple of quarters

**Comment by rmlarose** [comment]
> @rmlarose If this is functionality in Cirq-core, do you think we should move it so that it becomes something in cirq-rigetti so that they can look after it ?

Sorry for the late response! I think that certainly makes sense here, but is part of a larger discussion which I don't have the full context on. Thanks Matt for opening the above issue.

Perhaps relevant to the discussion is that Rigetti QCS now installs Cirq and you can, AFAIK, run Cirq circuits directly.

![qcs-cirq](https://user-images.githubusercontent.com/32416820/133124771-36ac38b4-6d54-41e0-bfc9-7fb279c69030.png)

So if you can do Cirq -> QCS directly instead of Cirq -> Quil -> QCS, maybe Cirq -> Quil doesn't need to be user-facing?

**Comment by vtomole** [comment]
>  Cirq -> QCS 

This is via `cirq-rigetti` I'm assuming. If that's the case: 

> Maybe Cirq -> Quil doesn't need to be user-facing

I agree. We added `QuilOutput` because Cirq was not operable with Quil 2 years ago. Now that it is, I don't see a good case for keeping the more "primitive" functionality in Cirq.
