### ISSUE TITLE
cirq.Sampler `program` argument should be `AbstractCircuit`

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#4350]
I'm getting type errors in pycharm when I'm trying to run a FrozenCircuit. I think there should be no downside to switching the type annotation to AbstractCircuit, of which both Circuit and FrozenCircuit derive?

**Comment by maffoo** [comment]
Agreed; there are probably quite a lot of places where we could change `Circuit` type annotations to `AbstractCircuit` instead, but Sampler is certainly one.

**Comment by banrovegrie** [comment]
Hey, I am new to Cirq. I just created the above PR for the issue, could you please check?

**Comment by mpharrigan** [comment]
This is fixed thanks to @banrovegrie . I changed the complexity label lol since it turned out to be a pretty far-reaching change
