### ISSUE TITLE
Accessing individual qubits of a lineQubit object

### ISSUE THREAD

**Issue by kharazity** [quantumlib/Cirq#4351]
As a relatively new user to Cirq, accessing individual qubits from a `LineQubit` object feels cumbersome. From what I understand, you can either put them all in a list method (as in the `range()` method) and access them from the list. Or you can explicitly set variables `q0,...,qN = LineQubit(N+1)`. I think it would be a nice feature to be able to access individual qubits from a `LineQubit` object `q` with an indexing operator like `q[idx]`. As an example, 
```
circuit = cirq.Circuit()
q = LineQubit(num_qubits)
circuit.append(cirq.Gate(q[idx]))
```
Instead of 
```
circuit = cirq.Circuit()
q = LineQubit(num_qubits)
q_range = q.range(num_qubits)
circuit.append(cirq.Gate(q_range[idx]))
```

It seems this sort of functionality exists for the doubly indexed `GridQubit` object, see [this example](https://quantumai.google/cirq/tutorials/basics#qubits). Could something similar to the implementation of the `GridQubit` accessor method be used for a `LineQubit` accessor method?

**Comment by maffoo** [comment]
A `LineQubit` is a single qubit. When you say `LineQubit(n)` it creates one qubit id object which refers to the nth qubit in some line, and if you try to unpack this into separate variables it will fail:
```python
In [1]: a, b, c = cirq.LineQubit(3)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-4a38dccedd6f> in <module>
----> 1 a, b, c = cirq.LineQubit(3)

TypeError: cannot unpack non-iterable LineQubit object
```
The `range` method is actually a static method defined on the `LineQubit` class, so while python makes it possible to call it on an instance it is intended to be called directly on the class instead:
```python
a, b, c = cirq.LineQubit.range(3)
q_range = cirq.LineQubit.range(num_qubits)  # list of length num_qubits
```

**Comment by kharazity** [comment]
Ahh, thanks. Dumb mistake.
