### ISSUE TITLE
cirq-pasqal/requirements.txt isn't filled

### ISSUE THREAD

**Issue by yurivict** [quantumlib/Cirq#4361]
**Description of the issue**

cirq-pasqal imports numpy, etc but it's requirements.txt is empty.

https://github.com/quantumlib/Cirq/blob/master/cirq-pasqal/requirements.txt

**Comment by balopat** [comment]
cirq-pasqal depends on cirq-core which depends on numpy, thus transitively imports it.

**Comment by yurivict** [comment]
```cirq-core``` isn't in ```requirements.txt``` either.

**Comment by balopat** [comment]
I thought it would be in setup.py - but it is not, so this is a bug indeed, I will fix it soon!
