### ISSUE TITLE
Test `test_hilbert_schmidt_inner_product_is_positive_definite[m6]` fails on aarch64 and ppc64le

### ISSUE THREAD

**Issue by ggardet** [quantumlib/Cirq#4379]
**Description of the issue**
Test `test_hilbert_schmidt_inner_product_is_positive_definite[m6]` fails on openSUSE Tumbleweed aarch64/ppc64le

```
[  765s] =================================== FAILURES ===================================
[  765s] _________ test_hilbert_schmidt_inner_product_is_positive_definite[m6] __________
[  765s] 
[  765s] m = array([[ 0.5+0.5j, -0.5-0.5j],
[  765s]        [ 0.5+0.5j,  0.5+0.5j]])
[  765s] 
[  765s]     @pytest.mark.parametrize('m', (I, X, Y, Z, H, SQRT_X, SQRT_Y, SQRT_Z))
[  765s]     def test_hilbert_schmidt_inner_product_is_positive_definite(m):
[  765s]         v = cirq.hilbert_schmidt_inner_product(m, m)
[  765s] >       assert np.isreal(v)
[  765s] E       assert False
[  765s] E        +  where False = <function isreal at 0xffff928f8310>((2.000000000000001+4.930380657631324e-32j))
[  765s] E        +    where <function isreal at 0xffff928f8310> = np.isreal
[  765s] 
[  765s] cirq/linalg/operator_spaces_test.py:166: AssertionError
```

**How to reproduce the issue**
Run test suite on aarch64 or ppc64le.

**Cirq version**
0.9.1

**Comment by viathor** [comment]
@ggardet Do you have more information about how the test fails?

Everyone else: Anyone's got access to the platform? I think you can run this to reproduce:

```
pytest -k test_hilbert_schmidt_inner_product_is_positive_definite cirq-core/cirq/linalg/operator_spaces_test.py
```

**Comment by ggardet** [comment]
> @ggardet Do you have more information about how the test fails?

I forgot to add the log, sorry. I added it to the 1st comment now.

**Comment by balopat** [comment]
A rounding error...`e-32`... we should just use `np.isclose(np.imag(v), atol=1e-16)` or similar.

**Comment by ggardet** [comment]
I can test a patch if needed.

**Comment by dabacon** [comment]
Could someone who has access to this architecture please see if the fix provided works?

@ggardet ?

**Comment by risicle** [comment]
We happen to be putting together the NixOS package for this at the moment and we're finding this _and a few other_ tests are failing on aarch64-linux due to tolerance issues. Full log: https://hydra.nixos.org/log/df0xzjzyvn3g8g9pmaais8y8k5wv3pd3-python3.8-cirq-core-0.13.1.drv

**Comment by ggardet** [comment]
> Could someone who has access to this architecture please see if the fix provided works?
> 
> @ggardet ?

Yes, the fix in #4636 make the test to pass. Thanks!

**Comment by vtomole** [comment]
@ggardet Awesome

@risicle Does this fix work for that NixOS package? Note, you'll need to test on the dev version of Cirq: `pip install cirq==0.14.0.dev20211112014647`

**Comment by dabacon** [comment]
@risicle added fixes for the tests you list.  Could you verify these are now fine.  Thanks!

**Comment by risicle** [comment]
Absolutely. 100%. Perfect - thankyou.
