### ISSUE TITLE
Automerge bot weird recency check problem

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#4408]
**Description of the issue**

This is a highly typical pattern recently, which almost defeats the purpose of automerge and quite annoying -- as it fails after merging master into the branch! 

1. A completely green, but not up to date PR is labeled with automerge
2. the bot merges master into the branch
3. github actions kick off 
4. instead of waiting, the bot claims that required status checks are missing and removes the automerge label

![image](https://user-images.githubusercontent.com/635073/129073330-ce880ab6-aa4c-484c-9815-4759fdf66e82.png)

5. Then I put the automerge label on again
6. bot merges to master happily

--- I think the issue might be with the recency logic determining whether a PR was modified recently or not:

https://github.com/quantumlib/Cirq/blob/master/dev_tools/auto_merge.py#L784

The threshold is 30 seconds currently - we might have to raise that or find a better logic.

**Comment by balopat** [comment]
I think "recently modified" threshold should be moved to 30 minutes instead of 30 seconds - with our PR CI suite running for 20 mins, it is quite likely to have unfinished checks.

**Comment by balopat** [comment]
Confirmed locally that increasing the threshold works.

**Comment by pavoljuhas** [comment]
obsolete
