### ISSUE TITLE
Flake: test_noise_model

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#4426]
**Description of the issue**

We should avoid these kind of tests if possible, the probability of this test failing is larger than desired. 
@asmuzsoy 

https://github.com/quantumlib/Cirq/pull/4424/checks?check_run_id=3315034286

```
=================================== FAILURES ===================================
_______________________________ test_noise_model _______________________________

    def test_noise_model():
        q = cirq.LineQubit(0)
        circuit = cirq.Circuit(cirq.H(q), cirq.measure(q))
    
        noise_model = cirq.NoiseModel.from_noise_model_like(cirq.depolarize(p=0.01))
        simulator = cirq.Simulator(noise=noise_model)
        result = simulator.run(circuit, repetitions=100)
    
>       assert 40 <= sum(result.measurements['0'])[0] < 60
E       assert 64 < 60

cirq-core/cirq/sim/sparse_simulator_test.py:1334: AssertionError
```

**Cirq version**

v0.13.0.dev

**Comment by balopat** [comment]
Well, seed kinda works, but it is an easy way out to make the test pass but the problem is that then it is hard to interpret it - how would you set the bounds then?  We could say that for that given seed 12324, we know exactly the sequence of answers the prng will give in `prng.random()` and `prng.choice()` so we will know that the number of 1s is 44. Is that a meaningful test? Maybe, but we don't know too much about this seed, it kind of raises some extra questions that make the test less focused.

The thing we want to test here really is that whether the noise_model gets applied or not. I would just choose a deterministic noise model, it's simpler to reason about it: 

```
def test_noise_model():
    q = cirq.LineQubit(0)
    circuit = cirq.Circuit(cirq.I(q), cirq.measure(q))
    noise_model = cirq.NoiseModel.from_noise_model_like(cirq.X)
    simulator = cirq.Simulator(noise=noise_model)
    result = simulator.run(circuit, repetitions=100)
    assert result.data['0'].sum() == 100
```

Alternatively you could pass in a Mock noise model and test whether the `act_on()` method was called with the exact state vector...but I think that might be a bit overkill here, especially that that requires understanding the internals of how the Simulator() works...so again, takes away from the focus of the test...

**Comment by daxfohl** [comment]
Yes, go ahead and close. It's not as thorough of a fix as what Balint suggested, but it's one in 900 million flake. https://github.com/quantumlib/Cirq/blob/9fd5af14d1fea2ea702c628834230f9611425523/cirq-core/cirq/sim/sparse_simulator_test.py#L1397
