### ISSUE TITLE
Mypy check fails with `cirq-core/cirq/contrib/acquaintance/gates_test.py:20: error: Module 'numpy.random' has no attribute 'poisson'` on Github Actions

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#4448]
**Description of the issue**
For example: https://github.com/quantumlib/Cirq/pull/4439/checks?check_run_id=3385860749

**Comment by ishmum123** [comment]
Can I help with this one?

**Comment by vtomole** [comment]
Sure. Thanks!

**Comment by vtomole** [comment]
Hey @ishmum123 , it seems like this problem affects all currently open pull requests. If you don't have the bandwidth to fix this ASAP, we can transfer this issue to @MichaelBroughton.

**Comment by ishmum123** [comment]
Please do, I am looking into it RIGHT now but not that confident about speed. Sorry about that

**Comment by vtomole** [comment]
Okay. If your are able to reproduce this problem on your local machine, you should be more than halfway there. Feel free to continue your work until @MichaelBroughton responds.

**Comment by ishmum123** [comment]
sorry I wasn't able to reproduce this locally. This was my best (blind) bet #4451

**Comment by vtomole** [comment]
Lets try replacing 

https://github.com/quantumlib/Cirq/blob/11f751fa62020a521edd25dbd8a4ba9420ca7442/cirq-core/cirq/contrib/acquaintance/gates_test.py#L20

with 

`import numpy` 

and in that file replace `poisson` with `numpy.random.poisson`

**Comment by ishmum123** [comment]
please check now

**Comment by vtomole** [comment]
Nice! That did the trick. Will merge.

**Comment by vtomole** [comment]
Before we merge your fix to `main` branch. Please merge your `ishmum123:mypy-fix` into `ishmum123:add_probabiliy_utility` branch and push it.

**Comment by ishmum123** [comment]
done

**Comment by vtomole** [comment]
I don't see the update on https://github.com/quantumlib/Cirq/pull/4439, also it looks like your cla got reverted in that PR.

**Comment by ishmum123** [comment]
can you please check again?

**Comment by vtomole** [comment]
The cla label is back but not the numpy chnages we made in the other branch. Are you performing `git merge mypy-fix` on your `add_probabiliy_utility` branch?

**Comment by vtomole** [comment]
Okay never mind the merge. We'll just merge main to your branch automatically now that the numpy fixes have been merged.

**Comment by ishmum123** [comment]
Sorry for the confusion

**Comment by vtomole** [comment]
No worries. Again, thanks a lot for the help 😄
