### ISSUE TITLE
Plumb separators argument through to `to_json` function or offer alternative

### ISSUE THREAD

**Issue by jacksonwb** [quantumlib/Cirq#4453]
To support creating minified json representations of cirq objects it would be useful to be able to change the `separators` argument that is passed to `json.dumps` inside the [`to_json`](https://github.com/quantumlib/Cirq/blob/v0.12.0/cirq-core/cirq/protocols/json_serialization.py#L495-L555) function, in the same way as the `indent` argument.

By passing a value of `(',', ':')` along with `indent=None` whitespace can be significantly reduced in long serializations. 

The `separators` argument could either be exposed to the `to_json` method, or another argument like a bool along the lines of `compact` could be passed to do this for the user.

I am happy to submit a PR.

**Comment by 95-martin-orion** [comment]
My gut reaction is that this should be a boolean (e.g. `minified=true`) instead of allowing arbitrary separators, to ensure the result is still able to be parsed by `read_json`. Worth discussing, though, since I'm not deeply familiar with how JSON parsing works.

**Comment by jacksonwb** [comment]
Yeah that seems reasonable. Because the `indent` argument is already exposed, and `minified` implies no indent, I would propose adding a `compact=True` argument that passes `(',', ':')` as separators to `to_json` and when passed with `indent=None` results in a minified json output.

**Comment by mpharrigan** [comment]
@95-martin-orion don't you think we should just follow the existing python API? I would be in favor of just plumbing through relevant parameters from `json.dump`

**Comment by mpharrigan** [comment]
Is there a case for slightly compacting json at the expense of readability when you could just use `to_json_gzip` and get full compression?

**Comment by jacksonwb** [comment]
It would be helpful to able to generate json that can be embedded in larger json objects and easily rendered for human reading, which also does not contain any unnecessary whitespace.

**Comment by 95-martin-orion** [comment]
> @95-martin-orion don't you think we should just follow the existing python API? I would be in favor of just plumbing through relevant parameters from `json.dump`

I just don't see a use case for arbitrary separators. IIUC, the purpose of `cirq.to_json` is to write a JSON file that can be deserialized by `cirq.read_json`. If a user provides anything except `separators=(', ', ': ')` (modulo whitespace), that purpose is no longer fulfilled, since `json.loads` has no equivalent `separators` argument.

If you feel strongly about matching the python API, we should add clear warnings in the docstrings noting this restriction.

**Comment by jacksonwb** [comment]
I think I tend to agree with @95-martin-orion that arbitrary separators may just leave room for accidental mistakes, but am happy to go either way.

**Comment by mpharrigan** [comment]
If it's good enough for Python, I'd think it's good enough for Cirq. It's also helpful to be able to say "all the other arguments are passed to `json.dump`"

**Comment by 95-martin-orion** [comment]
SGTM Matt - let's go ahead with plumbing directly through to `json.dumps` as you've described, with warnings in the docstrings regarding nonstandard separators.

**Comment by vtomole** [comment]
This is done by https://github.com/quantumlib/Cirq/pull/4537

```python
import cirq 
q = cirq.LineQubit(5)
cirq.to_json(cirq.rx(0.123).on(q), separators=(',', ':'), indent=None)
Out[27]: '{"cirq_type":"GateOperation","gate":{"cirq_type":"Rx","rads":0.123},"qubits":[{"cirq_type":"LineQubit","x":5}]}'
```
