### ISSUE TITLE
Bring GateTabulation out of cirq-google to cirq-core

### ISSUE THREAD

**Issue by Ashalynd** [quantumlib/Cirq#4461]
As discussed with @tanujkhattar in #4362, creating a separate issue to track GateTabulation refactoring.

**Comment by tanujkhattar** [comment]
@Ashalynd As part of tracking the progress towards our Cirq 1.0 roadmap items, I wanted to check in on the progress on this issue. Could you start working on it yet?

**Comment by Ashalynd** [comment]
Hi Tanuj, I had to put it on hold for a few weeks due to 80% work. Expect to create a PR this week.

**Comment by tanujkhattar** [comment]
There are some nuances in moving the code to cirq-core, mainly around dealing with [`two_qubit_gates/math_utils.py`](https://github.com/quantumlib/Cirq/blob/master/cirq-google/cirq_google/optimizers/two_qubit_gates/math_utils.py). Ideally, we'd like to move / re-implement the methods present in `math_utils.py` to more appropriate locations in cirq-core. For example,

- `random_qubit_unitary` : Replace usages with `cirq.testing.linalg_utils.random_unitary` 
- `kak_vector_infidelity`, `in_weyl_chamber`, `weyl_chamber_mesh`: Move to `linalg.decompositions.py` ? 
- `unitary_entanglement_fidelity` : Move to `qis.measures.py` ?

One difference in methods implemented in `math_utils.py` vs similar / existing methods in cirq-core is that most of the methods in `math_utils.py` are vectorized for speed. We should discuss the tradeoffs between consistency of the API with other similar methods and importance of vectorization for this use case. There are 3 options:

- Move `math_utils.py` as it is and rename to `gate_tabulation_math_utils.py`. 
- Move out the vectorized methods out to different locations as it is maintaining the existing vectorized API. 
- Move out the methods out to different locations with APIs consistent with existing cirq code and adopt the `GateTabulation` code according to the new API. 


Thoughts? cc @viathor @dabacon @maffoo 
xref : https://github.com/quantumlib/Cirq/issues/4722
