### ISSUE TITLE
Factor interop into 3rd party modules where applicable 

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#4469]
In discussion of https://github.com/quantumlib/Cirq/issues/4339 at the cirq cync, we thought it would be a good idea to think about moving some of the "interop" functionality from cirq-core, especially to_quil into 3rd party modules like cirq-rigetti if one exists. Then issues could be fixed by their rightful codeowners

A question: what will we do with other interop like to_qasm that don't have 3rd party modules to handle?

**Comment by dabacon** [comment]
Xref: #4623

**Comment by dabacon** [comment]
Moved to triage-discuss to get a decision.

**Comment by MichaelBroughton** [comment]
Discussion from Cirq-sync: We have moved quil outputs to cirq-rigetti now and qasm seems universal enough where we can just leave it in cirq-core (since it has no better home we can think of. Same goes for quirk). Going to close for now.
