### ISSUE TITLE
State vector simulator faced with non-unitary operations

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#4476]
Right now, the state vector simulator will stochastically choose a path when it encounters a non-unitary operation (measure, reset, noise). You can get into deep trouble if you e.g. put in a measure operation and then expect to have a state vector that means anything in isolation.

@Strilanc has said: "I regret calling it simulate instead of e.g. sample_final_state_vector. Exactly this kind of ambiguity."

Some of the pauli expectation functions do checking that you don't have any measurements which will likely mess them up in a major way.

1. should we have a method or toggle that will only do pure state dynamics. We can tell people to use this and not shoot themselves in the foot unless they know what they're doing and want a statistical sampling of possible state vectors
2. should we have a method that starts as state vector but will expand into a density matrix if you do a non-unitary operation? This might make sense in the context of #3240 where you want to do a long pure-state simulation and then reset/deallocate a bunch of qubits
3. should everyone just use quimb which never has any of these problems?

**Comment by daxfohl** [comment]
Talked offline, it seems there are a few things we could do.

1. Remove prng from simulators and pass them into the functions that are nondeterministic. This way it is explicit whether the operation you're doing is pure or not. Effort: small, but backwards incompatible.
2. Refactor Operation to come in a hierarchy e.g. Operation > ChannelOperation > MixtureOperation > UnitaryOperation > StabilizerOperation, and have e..g. StateVectorSimulator.simulate_pure only allow Circuit[UnitaryOperation]. Effort: large, value TBD.
3. Allowing DensityMatrixSimulator to use SV or possibly even stabilizer first and promote to DM as necessary seems like a good optimization and I don't see much in the way of it. It's largely independent of everything else here, should be its own issue. Effort: medium.

**Comment by daxfohl** [comment]
xref https://github.com/quantumlib/Cirq/issues/1740

**Comment by dstrain115** [comment]
Proposal in cirq cync:
 - simulate should still work for non-unitary operations
 - Possibly add a field into the result returned
 - Go ahead with #1740 to add sample_final_state_vector()

Not high-priority since this only affects certain use cases of specifically instantiation simulator and calling simulate() with non-unitaries.

**Comment by daxfohl** [comment]
@mpharrigan For item 2 in your list, would you want that to be a special simulator used only by the `mux` module (e.g. `final_state_vector`, `final_density_matrix`, etc, or should DensityMatrixSimulator itself be endowed with this functionality?

**Comment by mpharrigan** [comment]
I'm not sure. I was just brainstorming.

**Comment by daxfohl** [comment]
@mpharrigan I created an implementation https://github.com/quantumlib/Cirq/pull/4488 for item 2, but it was decided in cirq sync that there are not any big real-world use cases for this feature, and so this is not worth the cognitive overhead. So I closed the PR. If there is a real-world use case then I can reopen.

**Comment by mpharrigan** [comment]
Sorry for leading you astray. Thanks for opening the PR anyway.

**Comment by verult** [comment]
What's the most current design proposal? Could it potentially introduce backward-incompatible changes?

**Comment by mpharrigan** [comment]
If i'm reading this correctly, the proposal was

 - simulate should still work for non-unitary operations
 - Possibly add a field into the result returned
 - Go ahead with #1740 to add sample_final_state_vector()

(1) is a no-op

(2) was tried by @daxfohl but then it was nixed

(3) is captured by #1740 

so maybe this issue is redundant?

**Comment by verult** [comment]
Closing this for now per comment above, but please feel free to reopen if you think that's a mistake!
