### ISSUE TITLE
PR Size Label: Both XL and XS labels applied

### ISSUE THREAD

**Issue by cduck** [quantumlib/Cirq#4478]
<img width="724" alt="PR 4473 with both tags" src="https://user-images.githubusercontent.com/2476062/131565808-9af4355d-ab9f-4d8a-afba-93973126e7bf.png">
<img width="725" alt="PR 4467 with both tags" src="https://user-images.githubusercontent.com/2476062/131565824-afe5c7e8-ee20-4772-b792-419b550c5b9a.png">

**Description of the issue**
CirqBot added both the `size: XS` and `size: XL` tags to some PRs when it should have either kept one tag or removed the old tag when adding the second.

**How to reproduce the issue**
My guess:
- Make a small PR that gets labeled XS.
- Make some more commits.
- CirqBot adds the label XL but does not remove XS.

Note: #4467 doesn't look big enough to be categorized as XL.

**Cirq version**
N/A

**Comment by 95-martin-orion** [comment]
Might just be a case of Cirqbot failing to update on a PR (see also: stuck automerge states) - we'll need to reproduce the issue to confirm. Either way, this seems low priority to me unless we have users or automation depending heavily on these labels.
