### ISSUE TITLE
Request ZX TwoQubit Gate

### ISSUE THREAD

**Issue by HuangChiEn** [quantumlib/Cirq#4480]
**Is your feature request related to a use case or problem? Please describe.**
In original, the Fahri et al. proposed classifier is make use of ZX gate, however, the tfq tutorial use the ZZ gate.
At first, I want to custom the ZX Gate but the magic mehod is too complex to override.
For example, __pow__ method, I can not understand how to override. (seems have protocol behind the mul method)

**Describe the solution you'd like**
Maybe you can offer the ZX gate. 

**[optional] Describe alternatives/workarounds you've considered**
x

**[optional] Additional context (e.g. screenshots)**
x

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P2 - we should do it in the next couple of quarters

**Comment by vtomole** [comment]
> For example, pow method, I can not understand how to override.

Did you define your `ZX` gate as an EigenGate?

We have an implementation of this gate in [cirq-superstaq](https://github.com/SupertechLabs/cirq-superstaq/blob/7675cd7d5cd05f57dfefaa46a6efce3af64f9838/cirq_superstaq/custom_gates.py#L73) that you can take the `pow` of like `ZX ** 0.5`.

**Comment by HuangChiEn** [comment]
> > For example, pow method, I can not understand how to override.
> 
> Did you define your `ZX` gate as an EigenGate?
> 
> We have an implementation of this gate in [cirq-superstaq](https://github.com/SupertechLabs/cirq-superstaq/blob/7675cd7d5cd05f57dfefaa46a6efce3af64f9838/cirq_superstaq/custom_gates.py#L73) that you can take the `pow` of like `ZX ** 0.5`. We can add this gate to Cirq's mainline if you'd like to use it.

My fault, I have not to check all documents, many thanks !!

**Comment by HuangChiEn** [comment]
> > For example, pow method, I can not understand how to override.
> 
> Did you define your `ZX` gate as an EigenGate?
> 
> We have an implementation of this gate in [cirq-superstaq](https://github.com/SupertechLabs/cirq-superstaq/blob/7675cd7d5cd05f57dfefaa46a6efce3af64f9838/cirq_superstaq/custom_gates.py#L73) that you can take the `pow` of like `ZX ** 0.5`. We can add this gate to Cirq's mainline if you'd like to use it.

However, I got the following error message while I package the ZX gate into the tfq.layers.PQC, 
![image](https://user-images.githubusercontent.com/52521165/132128417-35214af2-dfe0-4cc0-8682-e373e14557f2.png)

```
    from cirq_superstaq import custom_gates

    def create_quantum_model():
        """Create a QNN model circuit and readout operation to go along with it."""
        data_qubits = cirq.GridQubit.rect(4, 4)  # a 4x4 grid.
        readout = cirq.GridQubit(-1, -1)         # a single qubit at [-1,-1]
        circuit = cirq.Circuit()
        
        # Prepare the readout qubit.
        circuit.append(cirq.X(readout))
        circuit.append(cirq.H(readout))
        
        builder = CircuitLayerBuilder(
            data_qubits = data_qubits,
            readout=readout)
    
        # Then add layers (experiment by adding more).
        builder.add_layer(circuit, cirq.XX, "xx1")
        builder.add_layer(circuit, custom_gates.ZX, "zx1")
    
        # Finally, prepare the readout qubit.
        circuit.append(cirq.H(readout))
    
        return circuit, cirq.Z(readout)

```

Unfortunately, the ZX gate seems not competiable into the tfq.layers.PQC layer by using the same serialize protocol ?

**Comment by vtomole** [comment]
The ZX gate is not part of the Serializable gate set in `cirq_google`. You need to add it like so: https://github.com/quantumlib/Cirq/blob/9349802d924bb5d23753fe0e30e396e0ec84af38/cirq-google/cirq_google/serialization/serializable_gate_set_test.py#L25

**Comment by MichaelBroughton** [comment]
Hi @HuangChiEn I would recommend taking a look at: https://www.tensorflow.org/quantum/api_docs/python/tfq/util/get_supported_gates

In order to check if the gate is supported inside of TFQ. Generally speaking TFQ can't support arbitrary gates.

If you wanted to add it, you could add serialization support here (https://github.com/tensorflow/quantum/tree/master/tensorflow_quantum/core/serialize), add adjoint information in C++ (https://github.com/tensorflow/quantum/blob/master/tensorflow_quantum/core/src/adj_util.h) and add parameter shift information in C++ (https://github.com/tensorflow/quantum/blob/master/tensorflow_quantum/core/ops/tfq_ps_decompose_op.cc).

On another note, if you want to realize a ZX like unitary, you could just sandwich a `cirq.ZZ ** (whatever)` in between two `cirq.H`s on the target qubit and you've got basically the same thing.

**Comment by vtomole** [comment]
^^ Is the right answer. I didn't know this issue leaned more TFQ than Cirq. Hopefully this helps you @HuangChiEn.
