### ISSUE TITLE
IonQ Job should throw TimeoutError when wait time exceeded

### ISSUE THREAD

**Issue by guenp** [quantumlib/Cirq#4507]
**Description of the issue**

Currently, `Job.results()` throws a `RuntimeError` when the job execution exceeds the `timeout_seconds` wait time. It would be more accurate to throw a `TimeoutError` instead.

see cirq-ionq/cirq_ionq/job.py:

https://github.com/quantumlib/Cirq/blob/7759c05fd71673ca58559307c220b5b779bf5bb6/cirq-ionq/cirq_ionq/job.py#L202

**How to reproduce the issue**

```
import cirq
import cirq.ionq as ionq

API_KEY = 'tomyheart' # Replace with your IonQ API key

service = ionq.Service(api_key=API_KEY, 
                       default_target='simulator')

q0, q1 = cirq.LineQubit.range(2)
circuit = cirq.Circuit(
    cirq.X(q0)**0.5,             # Square root of X
    cirq.CX(q0, q1),              # CNOT
    cirq.measure(q0, q1, key='b') # Measure both qubits
)

# create a job
job = service.create_job(circuit, repetitions=100)
job.results(timeout_seconds=0.1) # trigger a timeout
```

<details>

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_6204/2129298043.py in <module>
----> 1 job.results(timeout_seconds=0.01)

~/anaconda3/envs/my-env/lib/python3.7/site-packages/cirq_ionq/job.py in results(self, timeout_seconds, polling_seconds)
    199                 raise RuntimeError(f'Job failed. Error message: {error}')
    200             raise RuntimeError(
--> 201                 f'Job was not completed successful. Instead had status: {self.status()}'
    202             )
    203         # IonQ returns results in little endian, Cirq prefers to use big endian, so we convert.

RuntimeError: Job was not completed successful. Instead had status: ready

</details>

**Cirq version**

0.12.0

**Comment by dabacon** [comment]
Thanks @guenp !  PR out to fix this.

**Comment by dabacon** [comment]
This should be fixed in the prerelease version of Cirq.
