### ISSUE TITLE
Support for OpenQASM 3

### ISSUE THREAD

**Issue by banrovegrie** [quantumlib/Cirq#4509]
**Description of the issue**

Cirq currently has no support for OpenQASM 3. It can be done by writing a lexer and a parser similar to the ones we have for OpenQASM 2.

**Comment by anonymousr007** [comment]
Thanks @vtomole for assigned me this issue :smile:. Yes, I have started to create my RFC.

**Comment by banrovegrie** [comment]
@anonymousr007 any updates on the same?

**Comment by dstrain115** [comment]
This has been completed.

**Comment by Bossy-Ye** [comment]
good
