### ISSUE TITLE
Controlled gate construction cannot construct some cases

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#4512]
**Is your feature request related to a use case or problem? Please describe.**

Suppose you want a three qubit controlled gate like `(|00><00| + |11><11|) X + (|01><01| + |10><10| I` which flips the third qubit if the first qubit is either 00 or 11.  This currently isn't possible to construct given the way cirq specified `control_values`.    This is because `control_values` is a sequence of length equal to the number of controls, and this sequence is either `int`s or sequences of `int`s. In the second case the sequence means "either of these".  Thus you might think this would construct the gate above, but it does not
```
cirq.X(q2).controlled_by(q0, q1, control_values=((0, 1), (0, 1))
```
(this flips the third qubit for all inputs)
Or maybe this
```
cirq.X(q2).controlled_by(q0, q1, control_values=((0, 0), (1, 1))
```
(this flips the third qubit if the first control is zero and the second is one.

**Describe the solution you'd like**

Not sure we can fix this now, as this interface is used throughout :(

Probably the better interface would have been sequence of ints, same interperation, sequence of sequence either zipped up to get possible control positive values, or sequence of sequence where inner sequence is sequence of ints describing a positive control value.  If you really want to include unions for any of these, places where there is an int could have either an indicator value or another sequence to unionize what this means.

**[optional] Describe alternatives/workarounds you've considered**

Create two ops in a row that do what you want.  Custom gate controlled gate.

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P2 - we should do it in the next couple of quarters

**Comment by NoureldinYosri** [comment]
@dabacon could you please review the solution?

**Comment by dabacon** [comment]
The one kind of strange thing about your implementation (which is quite ingenious!) is that the two cases are distinguished by a) list of int or (list of int) and b) list of list of (list of ints).  This is a bit hard for most people to see the difference between, i.e. staring at the list of list of lists to see thats what it is isn't too easy.  What I would suggest is that we keep this "raw" form, but maybe also add some helpers for people to write this, i.e. instead of a) you could provide FreeVars(0, [0,1]) and for b) you could provide ConstrainedVars([0, 1], [0, 1]).  To be clear I think it could also accept the way you have things currently constructed, but just adding this as a convenience I think would make it more usable for most people.

**Comment by NoureldinYosri** [comment]
sounds good, I'll incorporate your suggestion into my code and create a PR

**Comment by daxfohl** [comment]
@NoureldinYosri still working on this? It'll be required for deferred measurements #4818. Or, at least some way of defining the condition "at least one qubit is not zero".

**Comment by daxfohl** [comment]
I think all I'd really need here is just another parameter `control_values_exact`, where you can pass in e.g. `control_values_exact=[(0, 0), (1, 1)]` to construct the condition in the issue description. Is this possible? If this is possible, I think I'd prefer it. That way we can decouple the operation from the class that generates the exact list, freeing up the ability to create whatever kinds of generators we want (boolean expression, sympy, int-to-bits, etc), wherever and wherever we want them.

**Comment by NoureldinYosri** [comment]
@daxfohl my GH-4714  has been pending review for sometime

in the PR I create a ControlValues class which supports the operations needed, the contructor for it can support both the _exact way for defining the allowed values as well as the old way, this way adding support for more ways to define control values would be as simple as creating a child class that reads the new form of input (e.g. list of ints) and set the internal variables correctly and maybe override some internal function(s).

so lets get GH-4714 reviewed and submitted :)
