### ISSUE TITLE
Add new community partners to Ecosystem page

### ISSUE THREAD

**Issue by cognigami** [quantumlib/Cirq#4538]
**Is your feature request related to a use case or problem? Please describe.**
Our ecosystem page has fallen a bit behind the times.

**Describe the solution you'd like**
On the ecosystem page (https://quantumai.google/cirq/ecosystem):

Add:
 - STIM under algo libraries
 - New pacakges under Quantum Cloud Services
   - IonQ
   - Azure
   - Rigetti
- Under Development tools, add Application-related benchmarks

Delete
 -  QFlex under simulators

**What is the urgency from your perspective for this issue? Is it blocking important work?**
P1 - I need this no later than the next release (end of quarter)

**Comment by beaolivei** [comment]
@cognigami I am guessing this one can only be done by someone that works at Google? How could an external contributor get access to this page? 🤔

**Comment by MichaelBroughton** [comment]
The source for the page is right here: https://github.com/quantumlib/Cirq/blob/master/docs/ecosystem.md if approved anyone can open a PR to fix these entries.

**Comment by cognigami** [comment]
Exactly, thanks Michael!

**Comment by vcatherine** [comment]
Also add under Quantum Cloud Services: Microsoft Azure Quantum

**Comment by dabacon** [comment]
This has been updated and will go out to production on next release.
