### ISSUE TITLE
Make measurement key instance variable names consistent

### ISSUE THREAD

**Issue by smitsanghavi** [quantumlib/Cirq#4560]
**Summarize the task**
Make measurement key class variable names consistent for both `string` and `MeasurementKey` types. Channels use `key` and `_key` respectively but `MeasurementGate` uses `key` and `mkey`.

I think `key `and `mkey` are better names and more indicative of the type. Also, the public interfaces of these objects are different. The channels don't expose a `key` attribute but `MeasurementGate `has to continue exposing it as a string or do a deprecation cycle on it.

Updating the channels would also entail inward-ing and recreating the JSON serializations.

**Acceptance criteria - when is the task considered done?**
When the naming is consistent.

**Related**
Related issues: #4040

**Comment by 95-martin-orion** [comment]
I raised this concern in #4497, but it's fairly trivial. Given the removal of string-based keys since this was released, the cost of updating serialization formats, and the lack of activity on this issue, I think we're fine to close it.
