### ISSUE TITLE
Dev page has out of date info about docs.

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#4572]
The [development page](https://quantumai.google/cirq/dev/development) currently references the old and new doc pages, but the old is deprecated or retired?

```
Currently the docs folder serves two sites: the new site that is under construction and the current site that is deployed to readthedocs.io. The new site is currently not available for preview just yet. For the current site, documentation is generated automatically by readthedocs when pushing to master, but you can also generate a local copy by running:


dev_tools/docs/build-rtd-docs.sh
The HTML output will go into the dev_tools/rtd_docs/sphinx/_build directory.
```

Also is it possible to generate docs for the new site in any form locally?

P2 - we should do it in the next couple of quarters

**Comment by MichaelBroughton** [comment]
> The development page currently references the old and new doc pages, but the old is deprecated or retired?

I think we thought about retiring in the past, but there were some packages depending on us that needed our RTD (or something like that) does anyone know if this is still the case ? @vtomole ?

> Also is it possible to generate docs for the new site in any form locally?

Unfortunately no, you can run notebooks locally, but there is no way to stage them for viewing as they would appear on the site without being a Googler.

**Comment by dabacon** [comment]
Is this fixed?

**Comment by ACHirth** [comment]
If the merged removal is sufficient, I think so!

**Comment by augustehirth** [comment]
If the merged removal is sufficient, I think so!
