### ISSUE TITLE
Fix docstrings for gatesets and gate families.

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4590]
**Description of the issue**

Some docstrings in gatesets and gate families are not getting rendered on the website as expected. For example:
1. https://quantumai.google/reference/python/cirq/ops/Gateset#__contains__ : Unintentional box, broken hyperlinks, newline missing between bullets etc.
2. https://quantumai.google/reference/python/cirq/ops/GateFamily#for_example : Ticks in code example instead of syntax highlighting.
3. https://quantumai.google/reference/python/cirq/ops/GateFamily#expandable-1 : Not hyperlinked.

**Cirq version**
0.13dev

**Comment by unaiic** [comment]
I think I could work on this.

**Comment by dabacon** [comment]
I'll take a crack at these.
