### ISSUE TITLE
Single source of truth for versions

### ISSUE THREAD

**Issue by BastianZim** [quantumlib/Cirq#4607]
**Background**

Hi, I'm in the process of adding cirq and all its sub-packages to [conda-forge](https://conda-forge.org). For this, I need to specify the version for all packages separately and was wondering what to use for the source of truth.

**Question**

Currently, each module has its own version file but all versions are the same. Can I expect this to be the same in the future, or might they differ at some point?

**Comment by vtomole** [comment]
> but all versions are the same

How so? Some modules have differing requirements.

**Comment by BastianZim** [comment]
Are you sure, because they all seem the same:

https://github.com/quantumlib/Cirq/blob/1bb755408755cd453b7c91aea80fabfcfd67fc1a/cirq-aqt/cirq_aqt/_version.py#L17
https://github.com/quantumlib/Cirq/blob/1bb755408755cd453b7c91aea80fabfcfd67fc1a/cirq-core/cirq/_version.py#L32
https://github.com/quantumlib/Cirq/blob/1bb755408755cd453b7c91aea80fabfcfd67fc1a/cirq-google/cirq_google/_version.py#L32
https://github.com/quantumlib/Cirq/blob/1bb755408755cd453b7c91aea80fabfcfd67fc1a/cirq-ionq/cirq_ionq/_version.py#L17
https://github.com/quantumlib/Cirq/blob/1bb755408755cd453b7c91aea80fabfcfd67fc1a/cirq-pasqal/cirq_pasqal/_version.py#L17
https://github.com/quantumlib/Cirq/blob/1bb755408755cd453b7c91aea80fabfcfd67fc1a/cirq-rigetti/cirq_rigetti/_version.py#L17
https://github.com/quantumlib/Cirq/blob/1bb755408755cd453b7c91aea80fabfcfd67fc1a/cirq-web/cirq_web/_version.py#L15

**Comment by vtomole** [comment]
I thought you were refraining to `requirements.txt`s. Yes, these should all be the same.

**Comment by BastianZim** [comment]
Ahh ok. Out of personal curiosity, any reason why it's not in one file?

**Comment by dabacon** [comment]
Maybe best solution is to make it forwards compatible with this, use global cirq version unless a separate version is defined in the package.   There could be cases where a non-core package gets borked against an API and the team responsible for that needs to rush a release.

**Comment by BastianZim** [comment]
Since it's a monorepo - would that be possible? If a GitHub release is created all should be updated or it becomes confusing pretty quickly because then the GitHub release doesn't correspond with the included components anymore.  

But just my 2 cents, I don't have any stakes in this.

**Comment by vtomole** [comment]
> Since it's a monorepo

The code is in one repo but each package has it's own pypi artifact.

**Comment by vtomole** [comment]
>  There could be cases where a non-core package gets borked against an API and the team responsible for that needs to rush a release.

Has this been codified somewhere? I know one reason for these sub-packages is to be able to do exactly this but this can make versioning very messy.

**Comment by BastianZim** [comment]
> The code is in one repo but each package has it's own pypi artifact.

Yes but the releases also contain wheels and each package is included in the Source Code attached to the release: https://github.com/quantumlib/Cirq/releases/tag/v0.13.1

**Comment by vtomole** [comment]
If I'm understanding correctly: you are saying that for example, `cirq-0.13.1-py3-none-any.whl` would be confusing if in that `whl` there was a  `cirq_aqt-0.13.2-py3-none-any.whl`. Basically the "real" version pertains to `cirq-core`. Users should pin the specific sub packages to avoid suprises. So instead of `pip install cirq==0.13.1`. They would

```
pip install cirq==0.13.1
pip install cirq-aqt==0.13.2
```

**Comment by BastianZim** [comment]
No sorry, should've been more clear. I'm only talking about GitHub releases.

Here, all wheels for all sub-packages are included and the overall source code with each package but not compiled.

What I mean is the following:

If version _1.1_ is now released but sub-package `y` is at _1.3_ you now have overall GitHub release _1.1_ containing wheel _1.3_. for sub-package `y`.
This would be confusing for me because I would expect release _1.1_ to only contain packages at _1.1_ but again, this is just something personal, nothing that is in the way of conda-forge or anything else so feel free to ignore it. :)

**Comment by vtomole** [comment]
Thanks for clearing that up. We should add this to the docs because I'm sure others will run into the same confusion.

**Comment by BastianZim** [comment]
Happy to leave this issue open if you'd like it for the docs PR, otherwise I'd close it - let me know.

**Comment by vtomole** [comment]
Let's close it.
