### ISSUE TITLE
Define `cirq.ISWAP_INV`, similar to `cirq.SQRT_ISWAP_INV` and replace usages.

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4615]
**Description of the issue**
Similar to `cirq.SQRT_ISWAP_INV`, define a global constant for `cirq.ISWAP_INV` and replace usages of `cirq.ISWAP ** -1` with `cirq.ISWAP_INV`. 

https://github.com/quantumlib/Cirq/blob/7951f84a0110be719c8a9e07aa1ffec2b0a31990/cirq-core/cirq/ops/swap_gates.py#L356

**Cirq version**
0.14.0

**Comment by unaiic** [comment]
I could work on this.

**Comment by vtomole** [comment]
@unaiic I've assigned it to you.

**Comment by MichaelBroughton** [comment]
> and replace usages of cirq.ISWAP ** -1 with cirq.ISWAP_INV

Help me understand here, why is this something we want to change ?

**Comment by vtomole** [comment]
@MichaelBroughton I guess it's more a matter of convenience. @tanujkhattar Should we replace all `** -1` gates with `_INV`?

**Comment by tanujkhattar** [comment]
Yes, it's mostly about consistency. Since we have `SQRT_ISWAP_INV`, we should also have `ISWAP_INV` just to be consistent.
