### ISSUE TITLE
importlib.abc in Python 3.10

### ISSUE THREAD

**Issue by Batmaev** [quantumlib/Cirq#4637]
**Description of the issue**

In Python 3.10.0, the command `import cirq` fails with the error:

```
class InstrumentedFinder(importlib.abc.MetaPathFinder):
AttributeError: module 'importlib' has no attribute 'abc'. Did you mean: '_abc'? 
```

**Workaround**

If one imports `importlib.abc` prior to importing cirq, no error occurs:

```python
from importlib import abc
import cirq
```

**Suggestion**

Probably you should add `from importlib import abc` somewhere in the Сirq's code.

Searching on Google, I've found a similar issue in another project: [grpc/issues/26062](https://github.com/grpc/grpc/issues/26062)

**Cirq version**
0.13.1

**Comment by vtomole** [comment]
Thank you for opening this. Please feel free to work on it.
