### ISSUE TITLE
check/all fails because it runs rigetti tests

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#4660]
One a clean dev install (with qiskit fix #4659) and docker installed, check/all fails becaused it attempts to run the rigetti integration tests.  This is caused by it calling check/pytest-and-incremental-coverage.   In contrast check/pytest does not run these tests.

**Comment by dabacon** [comment]
This really doesn't need to be done before 1.0, it doesn't define a new API.  @dstrain115 @MichaelBroughton

**Comment by dstrain115** [comment]
SGTM.  I'll put it as P1, since it would be nice to fix all these tests and make everything cleaner, but it can be post-poned until after launch.
