### ISSUE TITLE
Enforce [namespace.]classname format for cirq_type

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#4698]
The type-serialization behavior added in #4693 made an implicit assumption that Cirq objects use `object.__class__.__name__` for the "cirq_type" field of their JSON representation, optionally prepended with a namespace. This is consistent with existing Cirq types, but until that PR it was merely a convention; now that code depends on it, we ought to enforce it.

More specifically, this issue recommends moving assignment of the `cirq_type` JSON field from the `_json_dict_` magic method of serializable classes into the `cirq.to_json` protocol. As discussed in the linked issue, this will provide consistent behavior and reduce code redundancy.

**Comment by 95-martin-orion** [comment]
CC @mpharrigan

**Comment by mpharrigan** [comment]
A change that could get us most of the way there is modifying the behavior of `obj_to_dict_helper`
