### ISSUE TITLE
SerializableDevice is not json serializable

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#4699]
At least not JSON-serializable. 

This is a high priority request for cirq.google workflow tools. It's important to be able to save a record of the device you ran on when performing an experiment.

**Comment by maffoo** [comment]
Making this serializable will require getting rid of the lambdas that come in via `_GateDefinition.can_serialize_predicate`.

**Comment by tanujkhattar** [comment]
We should also migrate away from using `_GateDefinition` for gate containment checks and use the new `cirq.GateFamily` and `cirq.Gateset` framework, which is now serializable.

**Comment by 95-martin-orion** [comment]
I see no reason not to accept this item - having such a contradiction of class name and behavior is very silly.

**Comment by dstrain115** [comment]
We can probably deprecate this class after the new device spec goes in.

**Comment by dstrain115** [comment]
This class has been deprecated and is now defunct.
