### ISSUE TITLE
[cirqflow] `ExecutableGroupResultFilesystemRecord.load` should have a resolvers parameter for loading custom types

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4709]
`ExecutableGroupResultFilesystemRecord.load` is used to load an `ExecutableGroupResult` from disk. It does so by calling `cirq.read_json_gzip` with the correct path storing the files on disk.
https://github.com/quantumlib/Cirq/blob/d42e05833953e1285f8175775e6ac5627709b926/cirq-google/cirq_google/workflow/io.py#L47

The current implementation limits the functionality to reading only dataclasses which are already defined in cirq, even though for many types, like `ExecutableSpec` the recommendation is to use an inherited custom defined type which is specific to the problem. 

https://github.com/quantumlib/Cirq/blob/d42e05833953e1285f8175775e6ac5627709b926/cirq-google/cirq_google/workflow/quantum_executable.py#L26

This can be fixed by adding a `custom_resolvers` parameter to the `load` method which appends the custom resolvers with the default resolvers and forwards the updated resolver list to `cirq.read_json_gzip`. 

```python
    def load(
        self,
        *,
        base_data_dir: str = ".",
        custom_resolvers: Optional[Sequence[JsonResolver]] = None,
    ) -> 'cg.ExecutableGroupResult':
```

@mpharrigan

**Comment by mpharrigan** [comment]
The recommended way is to register your resolvers with cirq at import time. For example, in `__init__.py`

```python
from functools import lru_cache
from typing import Optional

from cirq.protocols.json_serialization import ObjectFactory, DEFAULT_RESOLVERS

from .line_topology import (
    LineTopologyLoschmidtSpec, LineTopologyLoschmidtData
)
from .tilted_square_lattice import (
    TiltedSquareLatticeLoschmidtData, TiltedSquareLatticeLoschmidtSpec, process_results,
    flat_results_to_dataframe
)


@lru_cache()
def _resolve_json(cirq_type: str) -> Optional[ObjectFactory]:
    if not cirq_type.startswith('recirq.algo_benchmarks.'):
        return None

    cirq_type = cirq_type[len('recirq.algo_benchmarks.'):]
    return {k.__name__: k for k in [
        TiltedSquareLatticeLoschmidtData, TiltedSquareLatticeLoschmidtSpec,
        LineTopologyLoschmidtData, LineTopologyLoschmidtSpec
    ]}.get(cirq_type, None)


DEFAULT_RESOLVERS.append(_resolve_json)

```

**Comment by mpharrigan** [comment]
Your suggestion is worth considering, though. You could imagine having a custom "reader" and "writer" function to e.g. toggle between writing gzipped or uncompressed json (as well as supporting custom resolvers)

**Comment by dstrain115** [comment]
Decision from cirq cync:  Proposed work-around registering the resolvers with cirq seems to work for this and it seems to be the better solution.  For now, we will close the issue.  If we want to support custom readers or writers as per the last comment, we can open a new issue.
