### ISSUE TITLE
[Named Topologies] Add `nodes_to_linequbits` method to `LineTopology` 

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4710]
Routing utilities currently present in cirq contrib expect a networkx graph of device (/target topology) where each node is a `cirq.Qid`.  `NamedTopology` stores topology graphs where each node is a number / tuple. 
`TiltedSquareLattice` has a `nodes_to_gridqubits` method which can provide a mapping from the graph nodes to the corresponding grid qubits.  
https://github.com/quantumlib/Cirq/blob/d42e05833953e1285f8175775e6ac5627709b926/cirq-core/cirq/devices/named_topologies.py#L233

This can be used to quickly get the graph needed for routing circuits from the topology graph as follows:
```python
routing_graph = nx.relabel_nodes(topology.graph, topology.nodes_to_gridqubits())
```

A similar convenience method, `nodes_to_linequbits`, should be added to the `LineQubit` named topology as well. 

cc @mpharrigan

**Comment by mpharrigan** [comment]
Yeah, I thought about this and almost included it in #4628 but omitted it because I figured it would be less useful for people putting stuff on gridqubit-based devices. 

It would be 
```python
return {i: q for i, q in enumerate(cirq.LineQubit.range(self.n)}
```
