### ISSUE TITLE
Organization (and deprecation) of cirq-core/optimizers in cirq-core/transformers

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4722]
### Background
Currently, all optimizers in cirq are present in a single directory --  `cirq-core/cirq/optimizers/*`. It contains not only transformers (which transform/optimize circuits) but also utility methods like analytical decompositions of matrices into target operations. 
Also, after https://github.com/quantumlib/Cirq/pull/4708 and https://github.com/quantumlib/Cirq/pull/4692; almost all existing optimizers would need to be re-implemented to 
 - Use the newly added moment preserving primitives 
 - Not mutate the input circuits (as proposed in the new transformer API https://tinyurl.com/cirq-circuit-transformers-api)
 

### Proposal

The proposal is to 
1. Create a new `cirq/transformers/` 
2. Move decomposition utilities from `cirq/optimizers` to sub directories under `cirq/transformers/`
3. Deprecate the existing transformers in `cirq/optimizers` in favor of new implementations using the moment preserving primitives and following the new non-mutating API, which would be added at top-level in `cirq/transformers/`.

#### cirq-core/cirq/transformers/heuristic_decompositions/*

- [x] gate_tabulation.py and corresponding math_utils.py (see https://github.com/quantumlib/Cirq/issues/4461)
- [ ] numerical optimization based approximate compilation proposed in https://github.com/quantumlib/Cirq/issues/4362

Note: Heuristic compilation is an active area of research and is an important primitive for compensating for actual gate angles calibrated via techniques like Floquet / XEB calibration. We can expect more primitives to get added here in future. 

#### cirq-core/cirq/transformers/analytical_decompositions/*

- [x] clifford_decomposition.py
- [x] controlled_gate_decomposition.py
- [x] cphase_to_fsim.py
- [x] decompositions.py --> single_qubit_decompositions.py
- [x] three_qubit_decomposition.py
- [x] two_qubit_decompositions.py --> two_qubit_to_cz.py 
- [x] two_qubit_state_preparation.py
- [x] two_qubit_to_fsim.py
- [x] two_qubit_to_sqrt_iswap.py

#### Newer versions of the following existing transformers in `cirq-core/cirq/optimizers/*` will get added in `cirq-core/cirq/transformers/*`
- [x] align_left.py
- [x] align_right.py
- [x] convert_to_cz_and_single_gates.py
- [x] drop_empty_moments.py
- [x] drop_negligible.py
- [x] eject_phased_paulis.py
- [x] eject_z.py
- [x] expand_composite.py
- [x] merge_interactions.py
- [x] merge_interactions_to_sqrt_iswap.py
- [x] merge_single_qubit_gates.py
- [x] stratify.py
- [x] synchronize_terminal_measurements.py
- [x] transformer_primitives.py

### Deprecation Plan
- For analytical decomposers, the existing files will simply get moved from `cirq/optimizers/*` to `cirq/transformers/analytical_decompositions`. Existing methods will go through a deprecation cycle and the change should not impact usages of the form `cirq.<method>`. 
- For existing transformers -- it would be a large breaking change to deprecate all existing transformers in the favour of newer moment-preserving non mutating versions but this is unavoidable and need to happen as part of the larger effort on redesigning transformers. The existing transformers can be left around for a few versions for the user code to get updated since the new versions would be implemented independently of existing versions. 

cc @MichaelBroughton @dstrain115 @dabacon  Thoughts? 
Part of roadmap #3238

**Comment by MichaelBroughton** [comment]
I like the looks of this plan.

> Create a new cirq/transformers/
Move decomposition utilities from cirq/optimizers to sub directories under cirq/transformers/
Deprecate the existing transformers in cirq/optimizers in favor of new implementations using the moment preserving primitives and following the new non-mutating API, which would be added at top-level in cirq/transformers/.

Where possible, I would be in favor of doing this one module at a time and not all at once so multiple people can work on this at once and also take the opportunity for the rewrite/cleanup of their module one module at a time.

**Comment by dstrain115** [comment]
This is fine with me, but we should announce this broadly.  We already mentioned at a cirq cync, but it might be worth an email to cirq-announce.  We could maybe combine this with a forward-looking "What's changing in cirq 1.0" email to all of cirq-announce that explains all the changes we are planning to do.

**Comment by pavoljuhas** [comment]
Picking up expand_composite.py.  Please let me know if someone already works on it.

**Comment by MichaelBroughton** [comment]
Random question: with #4858 do we need `convert_to_cz_and_single_gates.py` anymore ?

**Comment by anonymousr007** [comment]
Hi all, I would like to help with this issue, Can anyone please tell me further details?

**Comment by vtomole** [comment]
From the check list, it seems like the only thing left to close this is https://github.com/quantumlib/Cirq/issues/4362, but @Ashalynd is already working on it.

**Comment by tanujkhattar** [comment]
The task which is still open is about adding a new transformer and not migrating any existing transformer, so I'm going to remove the task from the list and the issue will be tracked independently. 

This particular issue is about migration of all existing optimizers, which has been completed and I'll therefore go ahead and close the issue.
