### ISSUE TITLE
Latest version to Zenodo did not get synced

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#4726]
**Description of the issue**

The last release(s) did not get synced to Zenodo for some reason, it still shows 0.12.0 as the latest. 

![image](https://user-images.githubusercontent.com/635073/144936521-369dcb58-e99a-4e7e-b36e-193796766e63.png)

**Cirq version**
0.13.1

**Comment by 95-martin-orion** [comment]
Pinging @MichaelBroughton for insight. We might have missed a step in the 0.13 release - it's possible that the release doc needs to be updated to include this.

**Comment by MichaelBroughton** [comment]
I wasn't able to find any docs for how this was setup. I'm like 40% sure I can't access the Cirq Github Zenodo entry here when I log in on the website. https://zenodo.org/record/5182845#.YdapfnXMKUk It appears to be linked to the quantumlib organization via webhooks (although I can't seem to get history on them for some reason), @balopat would you be able to give a little more information on how to access this and test it ?

**Comment by balopat** [comment]
Hey @MichaelBroughton,

As, after I left Google, my "owner" status on the project was revoked, it probably removed the authorization for the zenodo github automation integration. Reference docs: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content. 

The bad news is that, surprisingly, Zenodo does not support sharing of uploads between multiple users https://github.com/zenodo/zenodo/issues/151 👎 . The good news is that support is coming soon. 

Options I see: 

1. I opened a ticket to ask about transferring the ownership in the meantime. https://github.com/zenodo/zenodo/issues/2324 If this is possible, I'll transfer it to your user account. 
2. If you want this earlier, you might have to re-establish my owner status on the Cirq repos in the interim :/ 
3. Just wait until (1) is resolved or they deliver https://github.com/zenodo/zenodo/issues/151. 

Any other thoughts?

**Comment by 95-martin-orion** [comment]
Ideally it would be a group account, rather than a person, so that if we encounter this again before their multiple-user support goes through we don't have to do this again. Not sure if there's a good account for that, though.

**Comment by dstrain115** [comment]
I have made an account for quacs@google.com.  Can we transfer ownership to that account?

I have stored the password in our lovely internal password tool.

**Comment by dstrain115** [comment]
Updated Zenodo to cirq 0.14.1 and added instructions on how to do this in the future.
