### ISSUE TITLE
[cirqflow] `ExecutableGroupResultFilesystemRecord.load` should have sensible defaults for `*_paths ` members

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4732]
**Is your feature request related to a use case or problem? Please describe.**
The default `_FilesystemSaver` uses sensible hardcoded path prefixes for storing the runtime config / shared runtime config / executables etc.
https://github.com/quantumlib/Cirq/blob/a0497a411f494498778fae25b20011cd0b8b0eae/cirq-google/cirq_google/workflow/io.py#L142

The sensible defaults take the responsibility of providing explicit names to each file away from the user and are a very useful component. However, there's no easy way to load the results stored by the default file saver. 

**Describe the solution you'd like**

Ideally, it should be possible to identify the results of the default file saver by only providing a `run_id` and `base_data_dir` but currently, one needs to provide explicit values for all three -- `runtime_configuration_path`, `shared_runtime_info_path`,  `executable_result_paths`.

The request is to provide an easy way to load the results stored by the default saver by providing only `run_id` and `base_data_dir`

**What is the urgency from your perspective for this issue? Is it blocking important work?**
P1 - I need this no later than the next release (end of quarter)

cc @mpharrigan

**Comment by mpharrigan** [comment]
I have this function locally. Will push in the near future

**Comment by mpharrigan** [comment]
actually I already opened this draft PR, ptal https://github.com/quantumlib/Cirq/pull/4720

**Comment by mpharrigan** [comment]
done in #4720
