### ISSUE TITLE
`GateOperation._equal_up_to_global_phase_` should use `_group_interchangeable_qubits` for qubit comparison

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4766]
**Is your design idea/issue related to a use case or problem? Please describe.**
`GateOperation._equal_up_to_global_phase_` currently uses `self.qubits != other.qubits` as a comparison criteria to determine if the two operations are applied on the same qubits. It then goes on to determine if the two underlying gates are equal up to global phase. 

https://github.com/quantumlib/Cirq/blob/2e60ca1e49fb608ee4f833c85907abdbd298a75c/cirq-core/cirq/ops/gate_operation.py#L342

However, `GateOperation` uses `self._group_interchangeable_qubits()` for determining the value equality b/w two operations. 

https://github.com/quantumlib/Cirq/blob/2e60ca1e49fb608ee4f833c85907abdbd298a75c/cirq-core/cirq/ops/gate_operation.py#L152

**Describe your design idea/issue**
My proposal is that we should `self._group_interchangeable_qubits()` instead of `self.qubits` for qubit comparison in `_equal_up_to_global_phase_` as well so that it's easier to reuse the implicit  implementation for more complex cases where interchangeable qubits exist.

**Comment by Ashalynd** [comment]
`self.group_interchangeable_qubits` appears to be a potentially costly operation, because it iterates over all the qubits every time when it's called. Should it not instead be re-evaluated only when the qubits have changed between the calls?

**Comment by Ashalynd** [comment]
I can take this if there are no objections.

**Comment by tanujkhattar** [comment]
@Ashalynd Go for it!

**Comment by Ashalynd** [comment]
Thanks!

**Comment by tanujkhattar** [comment]
Closed by #4941
