### ISSUE TITLE
Remove SimulationStep/SimulationResult

### ISSUE THREAD

**Issue by daxfohl** [quantumlib/Cirq#4771]
This would be a big breaking change, so perfectly happy to let it go.

All the simulators use `TActOnArgs` internally, and now SimulationStepResult/SimulationTrialResult are just wrappers around that object. Those classes served a purpose back when all the simulators were implemented independently, but now they feel like unnecessary layers that obfuscate the code. They're also pretty delicate in that we've gone through great lengths to make sure none of the functions accidentally merge separated states yet retain backwards compatibility.

Instead we could yield/return TActOnArgs (after renaming to TSimulatorState or something more reasonable) directly, and that would allow us to ditch the extra layers. Obviously this would be a huge breaking change. But I figure it's now or never so felt like it should be posted here.

@MichaelBroughton cc @95-martin-orion

**Comment by viathor** [comment]
From cirq sync:

Discussion: This is a very breaking change. Also, we should gate this on renaming `TActOnArgs` to something more meaningful.

Conclusion: We probably don't really have time to do this. Maybe reopen some time before 2.0.
