### ISSUE TITLE
Set `atol: float = 1.0e-8` for `cirq.testing.assert_circuits_with_terminal_measurements_are_equivalent`

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#4784]
**Is your feature request related to a use case or problem? Please describe.**
The only place that uses `atol` in that function is `cirq.linalg.linalg.allclose_up_to_global_phase` and it too takes in a default `atol`.

**Describe the solution you'd like**
Make `atol` an optional argument for `assert_circuits_with_terminal_measurements_are_equivalent`.

**[optional] Describe alternatives/workarounds you've considered**
Passing in `1.0e-8` each time I call `assert_circuits_with_terminal_measurements_are_equivalent` which can be a bit of a hassle.

**What is the urgency from your perspective for this issue? Is it blocking important work?**
 
P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle

**Comment by purva-thakre** [comment]
@vtomole @viathor I can take this !

**Comment by vtomole** [comment]
Fixed by https://github.com/quantumlib/Cirq/pull/5017
