### ISSUE TITLE
Deprecate `SingleQubitGate`

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#4790]
**Description of the issue**
`cirq.I` is defined as ` IdentityGate(num_qubits=1)` and since IdentityGate takes in a variable number of qubits, it correctly doesn't inherit `cirq.SingleQubitGate`.
**How to reproduce the issue**
```python
import cirq
print(isinstance(cirq.I, cirq.SingleQubitGate)) # prints `False` instead of `True`
```
**Cirq version**
0.13.0.dev20210929175218

The solution is to make a class for the identity gate that does inherit from `cirq.SingleQubitGate`

```python
import cirq

class IGate(cirq.IdentityGate, cirq.SingleQubitGate):
    def __init__(self) -> None:
        super().__init__(num_qubits=1)

I = IGate()
print(isinstance(I, cirq.SingleQubitGate)) # prints True
```

Or you can use `cirq.num_qubits` for comparison. Relatedly, why wasn't `cirq.SingleQubitGate` wasn't deprecated like https://github.com/quantumlib/Cirq/pull/4207?

**Comment by daxfohl** [comment]
SingleQubitGate is used in the type annotations of several functions, so depreciating would be more invasive. IIRC we were on the fence as to whether we wanted to deprecate it eventually too.

Though since as you mention, there are varadic gates that are sometimes single qubit and sometimes not, it makes me lean toward thinking that having SingleQubitGate as a type is wrong, and we should be doing runtime checks on num_qubits instead. @tanujkhattar

**Comment by maffoo** [comment]
> having SingleQubitGate as a type is wrong, and we should be doing runtime checks on num_qubits instead.

+1

**Comment by tanujkhattar** [comment]
>  it makes me lean toward thinking that having SingleQubitGate as a type is wrong, and we should be doing runtime checks on num_qubits instead.

+1. We should definitely replace all `isinstance` checks with `num_qubits` check in Cirq. I'd also propose that we should try and deprecate `SingleQubitGate` before cirq 1.0, because if we don't, users will end up writing buggy code like `isinstance(g, cirq.SingleQubitGate)`.

**Comment by daxfohl** [comment]
@vtomole Shall we change the issue title to "Deprecate SingleQubitGate" and mark it as accepted?

**Comment by vtomole** [comment]
@daxfohl Yup, done. Thanks!

**Comment by vtomole** [comment]
@dstrain115 Have you started on this? I worked on it today and will open a PR soon.
