### ISSUE TITLE
Utilities for measurement error mitigation using confusion matrix (aka calibration matrix)

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4800]
**Is your feature request related to a use case or problem? Please describe.**
Measurement error is one of the major sources of error when running circuits on the device. A common technique to compensate for the measurement error is to first compute a confusion matrix (aka calibration matrix) by running `2 ** n` circuits to prepare all basis. Measurement outcomes from the i'th circuit becomes the i'th row of the matrix.

The resulting confusion matrix would be the transpose of a stochastic map from final states to measurement outcomes, s.t. `M_obs = CM.T @ M_act`. For 2 qubits, this corresponds to:

```
[ 00o ]         ⎡ Pr(00o|00a) Pr(01o|00a) Pr(10o|00a) Pr(11o|00a) ⎤T      [ 00a ] 
[ 01o ]         ⎢ Pr(00o|01a) Pr(01o|01a) Pr(10o|01a) Pr(11o|01a) ⎥       [ 01a ]
[ 10o ]    =    ⎢ Pr(00o|10a) Pr(01o|10a) Pr(10o|10a) Pr(11o|10a) ⎥  @    [ 10a ] 
[ 11o ]         ⎣ Pr(00o|11a) Pr(01o|11a) Pr(10o|11a) Pr(11o|11a) ⎦       [ 11a ]
```

We can then use the computed confusion matrix to calibrate the measurement results of another experiment on the same qubits as:
```
M_compensated = Inv(CM.T) @ M_obs
```

**Describe the solution you'd like**
We should have utility methods / classes to 
- Compute the confusion matrix given a sampler and list of qubits. 
- Use the confusion matrix for compensating the results of an observed experiment. The inverse of the confusion matrix can be computed either as a Pseudo-Inverse or using least squares method (simple inverse can lead to negative probabilities due to sampling error)
-  Be able to compensate for measurement errors for experiments done on subsets of `n` qubits.
-  Compute tensored confusion matrix on smaller groups of qubits assuming the measurement error is local (this would need `Sum(2 ** k)` circuits instead of `2 ** n`).
- Write tutorials on using these newly added features, similar to https://qiskit.org/documentation/tutorials/noise/3_measurement_error_mitigation.html

**What is the urgency from your perspective for this issue? Is it blocking important work?**
P2 - we should do it in the next couple of quarters

**Comment by crazy4pi314** [comment]
Folks on the Mitiq project are also working on implementing measurement error mitigation: https://github.com/unitaryfund/mitiq/issues/815 that might be a helpful example

**Comment by tanujkhattar** [comment]
We should add this to `cirq/experiments`. Look at potential collaboration opportunities with Unitary Fund.
