### ISSUE TITLE
`cirq.plot_density_matrix` outputs buggy plots (abstract art) and doesn't scale with number of qubits. 

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4804]
**Description of the issue**
`cirq.plot_density_matrix` is buggy and output's random plots (tested in a colab) and would also doesn't scale well with number of qubits. 

My guess is that this due to the magic numbers hardcoded in the code, which should be changed and computed on the fly based on the size of the density matrix. 

https://github.com/quantumlib/Cirq/blob/09a4667e3d1768fc2f1934b18ae52e5b13ecd378/cirq-core/cirq/vis/density_matrix.py#L39

**How to reproduce the issue**

```python
import cirq
cirq.plot_density_matrix(cirq.testing.random_density_matrix(dim=4, random_state = 12345))
```

<details>

![image](https://user-images.githubusercontent.com/7863287/148300842-9c302e93-1437-4e88-8513-0dcb5451186a.png)

</details>

**Cirq version**
0.14.0.dev20220105215702

cc @AnimeshSinha1309

**Comment by dabacon** [comment]
It does look like some sort of abstract art, though :)

**Comment by tanujkhattar** [comment]
@dabacon Updated the title to better reflect what's happening :P

**Comment by AnimeshSinha1309** [comment]
I have no idea how all the multiply operations were written as divide, I had made the mistake but I remember that things were working last I checked. Anyways, fixed this, please lemme know if stuff is working now. Not sure if adding a test here would help, maybe I can add that radius of any circle should not be more than 1 and same with with length of any line.
