### ISSUE TITLE
cirq-rigetti python requirements incompatible with tensorflow

### ISSUE THREAD

**Issue by PatrickSteinmueller** [quantumlib/Cirq#4826]
**Description of the issue**

We currently use tensorflow and tensorflow quantum in our project. Tensorflow uses cirq as backend to simulate the quantum computer. We want to use cirq-rigetti for accessing rigetti devices. However, this is not compatible with tensorflow.

Tensorflow forces numpy 1.19.5, while cirq-rigetti forces the use of pyquil3.0.0 for python >=3.7 which forces numpy>=1.20 (and thus is incompatible)

cirq-rigetti's requirements file suggests pyquil2.28.2 for python < 3.7. pyquil2.28.2 uses numpy 1.19.x and thus this would fit.

However, cirq-rigetti's setup.py file forces python 3.7
 

**How to reproduce the issue**

Install tensorflow, tensorflow-quantum, cirq, cirq-rigetti via pip.

**Comment by 95-martin-orion** [comment]
Discussed at Cirq sync: this should be addressed in Tensorflow Quantum - please raise an issue there.
https://github.com/tensorflow/quantum
