### ISSUE TITLE
Cannot serialize identity gate on Quantum Engine

### ISSUE THREAD

**Issue by viathor** [quantumlib/Cirq#4833]
**Description of the issue**

Cannot serialize identity gate when using SQRT_ISWAP_GATESET.

**How to reproduce the issue**

```python
sampler = engine.get_sampler(processor_id='...', gate_set=cg.SQRT_ISWAP_GATESET)
q = cirq.GridQubit(7, 4)
c = cirq.Circuit(cirq.I(q))
r = sampler.run(c, repetitions=1)
...
ValueError: Cannot serialize op cirq.I(cirq.GridQubit(7, 4)) of type <class 'cirq.ops.identity.IdentityGate'>
```

**Cirq version**

```
0.14.0.dev20211210220312
```

**Comment by tanujkhattar** [comment]
If we decide to add serialization for Identity, it should also be added to the new `CircuitSerializer`. 

https://github.com/quantumlib/Cirq/blob/89f88b01d69222d3f1ec14d649b7b3a85ed9211f/cirq-google/cirq_google/serialization/circuit_serializer.py#L120

**Comment by tonybruguier** [comment]
I might be interested, but I can certainly yield on this one.

**Comment by dstrain115** [comment]
I don't think this gate should be serialized, as it has no effect by design in the hardware (and this serialization is only for Google hardware).

I would support cirq.I gates being stripped by default from serialization.

**Comment by dstrain115** [comment]
Confirmed with @viathor that we should just strip these gates out when serializing.  Let's do this in CircuitSerializer too.  @verult

**Comment by verult** [comment]
Per @maffoo 's [comment](https://github.com/quantumlib/Cirq/pull/4994#pullrequestreview-882489134), there is a use case for serialize identity gates, and they should be serialized along with their tags. And in general, a user's circuit should be serialized as-is as much as possible to avoid surprises.

**Comment by verult** [comment]
@maffoo is identity gate tag serialization a use case we need to support right away? If not, I propose piggybacking on an existing gate type in the `Program` proto until the use case comes along.

**Comment by maffoo** [comment]
Chatted with @verult about this; IMO we should add a separate `IdentityGate` case in the [`Operation` proto](https://github.com/quantumlib/Cirq/blob/master/cirq-google/cirq_google/api/v2/program.proto#L195) if we want to serialize identities, because the serialization tries to preserve gates as closely as possible instead of converting to "equivalent" gates (e.g. we have separate cases for `XPowGate` vs `PhaseXZGate`). Until then, I think we should fail if trying to serialize identity gates, and it would be up to the user to remove them (we can add helper function to do this if needed).

**Comment by tanujkhattar** [comment]
>  (we can add helper function to do this if needed).

Just FYI: We already have `cirq.drop_negligible_operations` transformer to achieve this. 

https://github.com/quantumlib/Cirq/blob/afb62da0e33559a47135094047ce3a872740a17e/cirq-core/cirq/transformers/drop_negligible_operations.py#L26

**Comment by verult** [comment]
What about GlobalPhaseGates? I'm assuming they are ignored by hardware as well, so they should be handled the same way?

**Comment by maffoo** [comment]
Yes, I would suggest handling them in the same way. When serializing, fail if we encounter unsupported gates. We can add transformer support for removing them from circuits, or we can add cases to the Operation proto to allow serializing them if desired.

**Comment by dstrain115** [comment]
We could probably serialize both for ease of user use, but, since this is not backwards incompatible, and there is a easy work-around, I think this can be post-1.0 if necessary.

**Comment by dstrain115** [comment]
@NoureldinYosri This is a low priority item, but if you have time, should be very similar to some similar bugs you handled recently.
