### ISSUE TITLE
`_value_equality_approx_eq` does not handle `_value_equality_values_cls_` for class type comparison  correctly.

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4834]
**Description of the issue**
The `if not isinstance(other, cls_self)` check below enforces that the `other` should be an instance of the same class type, which essentially leads to ignoring `_value_equality_values_cls_` and returns `NotImplemented`. 

https://github.com/quantumlib/Cirq/blob/89f88b01d69222d3f1ec14d649b7b3a85ed9211f/cirq-core/cirq/value/value_equality_attr.py#L92-L102

**How to reproduce the issue**

```python
>>> @cirq.value_equality(approximate=True)
>>> class A(str):
>>>     def _value_equality_values_cls_(self):
>>>         return str
>>>     def _value_equality_values_(self):
>>>         return self
>>> a = A('123')
>>> b = '123'
>>> a._approx_eq_(b, 1e-6)
NotImplemented # This should return True.
```

**Cirq version**
0.14.0.dev

**Comment by viathor** [comment]
+1 we want equality and approximate equality to be consistent
