### ISSUE TITLE
Operations on `MutableDensePauliString` return a `DensePauliString`

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4835]
**Description of the issue**
Doing operations like `__pow__`, `__mul__`, `__rmul__`, `__abs__`, `tensor_product` etc. on a `MutableDensePauliString` return a `DensePauliString` because these methods are inherited from `BaseDensePauliString` which returns `DensePauliString(...)` instead of `type(self)(...)` in these methods. 

https://github.com/quantumlib/Cirq/blob/master/cirq-core/cirq/ops/dense_pauli_string.py#L206-L208

**How to reproduce the issue**

```python
>>> import cirq
>>> m = cirq.MutableDensePauliString("Z")
>>> type(m) == type(-m)
False
```

**Cirq version**
0.14.0.dev

**Comment by tanujkhattar** [comment]
From cirq sync:  +1, should be done.

**Comment by alexandrebouayad** [comment]
Hi, I've opened a PR (#4892). I tried to fix the issue. I also added some typing. I had to modify some tests.

One noticeable induced change that may need to be validated by the reviewer: one cannot multiply a `MutableDensePauliString` object with a `DensePauliString` object anymore (and vise versa).

**Comment by alexandrebouayad** [comment]
@tanujkhattar could someone quickly review my PR? I don't think there's anything complex or obscure here, but I'd still be happy to know if I have correctly tackled the issue. Thanks :)
