### ISSUE TITLE
[cirq-google] Proposal: Remove XmonDevice, Bristlecone, Foxtail and rename optimize_for_xmon.

### ISSUE THREAD

**Issue by MichaelBroughton** [quantumlib/Cirq#4856]
We haven't been using XmonDevices for a while now. We don't have any on engine either. We should probably take this opportunity to cut out XmonDevice and the two subclasses Bristlecone and Foxtail. optimized_for_xmon could also be renamed in the transfer as a part of #4722 to more accurately reflect what use cases it might have now. They are kind of cluttering up the devices story in `cirq-google`.

xref #4744 .

**Comment by wcourtney** [comment]
Related: I also filed a bug about the docs for these at b/180955395.
