### ISSUE TITLE
Make sure all cirq gates decompose to XPow/YPow/ZPow/CZPow + Measurement

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4858]
As part of https://tinyurl.com/cirq-organize-decompose-rfc, we want to make sure that all cirq gates decompose to the XPow/YPow/ZPow/CZPow + Measuremet gateset. 

This issue is to track all the gates where we need to explicitly add a `_decompose_` method to make sure all decompositions end on the above target gateset. 
We should also discuss what happens for gates where trivial decomposition is not present?

1. `MatrixGates` : Should we add an analytical decomposition to the `_decompose_` method of matrix gates?
2. Same question as above for `ControlledGate`s. 

P1 - I need this no later than the next release (end of quarter)

**Comment by vtomole** [comment]
> Should we add an analytical decomposition to the _decompose_ method of matrix gates

How would this work? Is it possible to decompose any arbitrary `MatrixGate` into a target gateset?

**Comment by tanujkhattar** [comment]
@vtomole Yes. We have utilities in Cirq to decompose any arbitrary 2q Matrix Gate into the CZ gateset (see See https://github.com/quantumlib/Cirq/blob/master/cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_cz.py) and there's an open issue https://github.com/quantumlib/Cirq/issues/4022 to add compilation of any arbitrary unitary to 1/2q gates

**Comment by daxfohl** [comment]
I also think we should have `MeasurementGate` with `invert_mask` decompose into a series of pre- and post-measurement `X`s that represent the invert mask (and the subsequent uninversion), so that "measurement" can be a uniquely defined thing.
