### ISSUE TITLE
cirq-rigetti service.run supporting programs

### ISSUE THREAD

**Issue by tom-genmat** [quantumlib/Cirq#4859]
**Is your feature request related to a use case or problem? Please describe.**
would like to run tfq programs with rigetti-cirq on rigetti devices. 

**Describe the solution you'd like**
would like to be able to wrap a program not just a circuit in the service.run function

**[optional] Describe alternatives/workarounds you've considered**
rewrite entire codebase in pyquil + pennylane

**[optional] Additional context (e.g. screenshots)**

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P0 - this should land no later than a week

**Comment by MichaelBroughton** [comment]
Would the TFQ github be a better place for this issue if it's strictly to do with TFQ ?
