### ISSUE TITLE
Fix `circuit.append()` to use `protocols.commute` to verify if two operations can be "crossed" or not.

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4882]
**Description of the issue**
Since #4870 breaks the assumption that two operations acting on disjoint qubits always commute, `circuit.append()` should use `protocols.commute` to find the leftmost moment in which an operation can be inserted. 

As part of the work done for `CCO`, this was implemented by adding a special case of checking whether the current operation is a CCO and if yes, whether the previous moment has a measurement with matching control keys. 

https://github.com/quantumlib/Cirq/blob/90679d27e0967c0a7fe59848e789a5d6ba49b66d/cirq-core/cirq/circuits/circuit.py#L1972-L1975

This is problematic because it works only in one direction and breaks optimizers which relies on doing operations on the circuit in reverse order. 

**How to reproduce the issue**

```python
>>> import cirq
>>> q =  cirq.LineQubit.range(2)
>>> c = cirq.Circuit(cirq.Moment(cirq.X(q[0])), cirq.Moment(cirq.measure(q[1], key="m")), cirq.Moment(cirq.X(q[0]).with_classical_controls("m")))
>>> print(c)
0: ───X───────X───
              ║
1: ───────M───╫───
          ║   ║
m: ═══════@═══^═══
>>> cirq.AlignLeft().optimize_circuit(c) # Works as expected.
0: ───X───X───
          ║
1: ───M───╫───
      ║   ║
m: ═══@═══^═══
>>> cirq.AlignRight().optimize_circuit(c) # Does not work as expected because implementation depends on inserting operations in the reverse circuit.
>>> print(c) # Wrong output
          ┌──┐
0: ───X────X─────
           ║
1: ────────╫M────
           ║║
m: ════════^@════
          └──┘

```

**Cirq version**
0.14.0.dev

**Comment by 95-martin-orion** [comment]
Cirq sync: we support the general idea here (ensure `append` works in both directions), but we need to be careful about using `protocols.commute` for it. For example, appending `X(q1)` after `CX(q0, q1)` should keep the X after the CX, even though the two commute.
