### ISSUE TITLE
Local measurements

### ISSUE THREAD

**Issue by daxfohl** [quantumlib/Cirq#4885]
**Is your feature request related to a use case or problem? Please describe.**

It is possible that subcircuits will contain measurements only intended for use locally to enable classical control logic. It would be nice to be able to make these measurements "local", such that they don't pollute the user's result data or cause naming conflicts unnecessarily.

**Describe the solution you'd like**

Probably an extra argument `cirq.measure(q, key='a', local=True)`. These would be scoped to the subcircuit and not exposed outside of it.

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle

**Comment by 95-martin-orion** [comment]
Result size hasn't been a huge issue for us, and this has the potential to be a large change - let's not prioritize it for now.
