### ISSUE TITLE
Fix import cirq

### ISSUE THREAD

**Issue by quosta** [quantumlib/Cirq#4887]
**Description of the issue**

Using Python 3.10, and the most updated cirq on pip (0.13.1) fails to import properly 

**How to reproduce the issue**
```
>>> import cirq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/cirq/__init__.py", line 15, in <module>
    from cirq import _import
  File "/usr/lib/python3.10/site-packages/cirq/_import.py", line 25, in <module>
    class InstrumentedFinder(importlib.abc.MetaPathFinder):
AttributeError: module 'importlib' has no attribute 'abc'. Did you mean: '_abc'?
```
I can import correctly with:
```
>>> from importlib import abc; import cirq
```

**Comment by vtomole** [comment]
Hey @quosta, this was fixed in https://github.com/quantumlib/Cirq/issues/4637. You can get the fix my installing the [nightly version of Cirq](https://pypi.org/project/cirq/0.14.0.dev20220123212110/). I will close this issue; but please ask questions if you have them.
