### ISSUE TITLE
DepolarizingChannel tries to depolarize measurements and also fails at it

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#489]
Injects a gate after the measurement. Probably shoudn't do any at all.

Also it should perhaps be called DephasingChannel.

**Comment by Strilanc** [comment]
I think the issue is still relevant, but that it should be delayed because of the new work on noise. It will be properly obsoleted at a later time.

**Comment by vtomole** [comment]
@Strilanc Does the recent work on noise obsolete this?

**Comment by Strilanc** [comment]
This is obsolete, although oddly prescient of running into the same issue with the new models. But there's already a bug for that.
