### ISSUE TITLE
Documentation for `cirq.Circuit.prev_moment_operating_on` is incorrect

### ISSUE THREAD

**Issue by perlinm** [quantumlib/Cirq#4894]
**Description of the issue**

The docstring summaries for [`cirq.Circuit.next_moment_operating_on`](https://github.com/quantumlib/Cirq/blob/v0.13.1/cirq-core/cirq/circuits/circuit.py#L269-L272) and [`cirq.Circuit.prev_moment_operating_on` ](https://github.com/quantumlib/Cirq/blob/v0.13.1/cirq-core/cirq/circuits/circuit.py#L321-L327) are identical: both say "Finds the index of the **next** moment that touches the given qubits."

The docstring for `cirq.Circuit.prev_moment_operating_on` should either say "Finds the index of the **previous** moment that touches the given qubits.", or else somehow specify that "next" means "next in a search backwards through the circuit".

**How to reproduce the issue**

See links above, or examine docstring via
```
help(cirq.Circuit.prev_moment_operating_on)
```

**Cirq version**

Issue identical in `cirq` versions `0.13.1` and `0.14.0.dev20220105215702`

**Comment by vtomole** [comment]
Closed by https://github.com/quantumlib/Cirq/pull/4895.
