### ISSUE TITLE
Identify root cause of `notebook==6.4.8` + `coverage==6.3` causing hang in CI and upgrade if needed.

### ISSUE THREAD

**Issue by MichaelBroughton** [quantumlib/Cirq#4897]
**Description of the issue**
`notebook==6.4.8` + `coverage==6.2` causes CI to hang. Right now we are pinned to 6.4.7 and 6.2, with no root cause known. It would be good to investigate this issue further and unpin if possible.

**Cirq version**
```
0.14.0dev
```

**Comment by mhucka** [comment]
Looks like this was fixed some time ago by updating the pinned version numbers.
