### ISSUE TITLE
Migrate ionq_device compilation to circuit transformer

### ISSUE THREAD

**Issue by Cynocracy** [quantumlib/Cirq#4901]
**Summarize the task**
Spin-off from https://github.com/quantumlib/Cirq/pull/4824 to get ionq device prepped for deprecation of `decompose_operation` API in devices.

**Acceptance criteria - when is the task considered done?**
When ionq_device is no longer blocking deprecation of decompose_operation

**Comment by tanujkhattar** [comment]
@Cynocracy Cirq optimizers have been migrated to new transformer framework. Can you now do the migration for ionq device? You should create a new [`TwoQubitCompilationTargetGateset`](https://github.com/quantumlib/Cirq/blob/a7df579023460f9bf64a714a190bf9d7291ecf6a/cirq-core/cirq/transformers/target_gatesets/compilation_target_gateset.py#L120)  for ionq put the decomposition logic there. See other similar implementations of gatesets, like [`CZTargetGateset`](https://github.com/quantumlib/Cirq/blob/a7df579023460f9bf64a714a190bf9d7291ecf6a/cirq-core/cirq/transformers/target_gatesets/cz_gateset.py#L27) in cirq core. 

Please let me know if you have any questions.

**Comment by tanujkhattar** [comment]
https://github.com/quantumlib/Cirq/issues/5028 This issue tracks the migration of optimizers in vendor packages

**Comment by Cynocracy** [comment]
Sure thing, happy to take this one up

**Comment by Cynocracy** [comment]
I was looking into this, and found https://github.com/quantumlib/Cirq/pull/4925 recently that seems to have made changes to how cirq-ionq exposes these, but it doesn't support nqubits > 2 which is strange.

Anyway, it's making my changes a bit more involved than I intiially thought, so just calling it out.

Am shooting to continue to support that high level interface but to use a `[TwoQubitCompilationTargetGateset` "behind the scenes" (while also dropping IonqAPIDevice)

**Comment by Cynocracy** [comment]
Hmm, maybe I'm just not understanding. The diff looks like it tried to preserve behavior.

Going to continue to try to wrap my head around things :) hopefully a PR emerges soon

**Comment by Cynocracy** [comment]
Have my changes staged, but am confused by the sudden appearance of `cirq.PhasedXZGate` in the test output :( I've tried using the base class and TwoQubit[...]

**Comment by Cynocracy** [comment]
The full failure is

```
>           assert VALID_DECOMPOSED_GATES.validate(decomposed_circuit)
E           assert False
E            +  where False = <bound method Gateset.validate of cirq.Gateset(cirq.ops.common_gates.XPowGate, cirq.ops.common_gates.ZPowGate, cirq.CNOT, unroll_circuit_op = True,accept_global_phase_op = True)>(cirq.Circuit([\n    cirq.Moment(\n        cirq.PhasedXZGate(axis_phase_exponent=0.11059847571375991, x_exponent=0.3757376732242559, z_exponent=-0.9918267391627413).on(cirq.LineQubit(0)),\n    ),\n]))
E            +    where <bound method Gateset.validate of cirq.Gateset(cirq.ops.common_gates.XPowGate, cirq.ops.common_gates.ZPowGate, cirq.CNOT, unroll_circuit_op = True,accept_global_phase_op = True)> = cirq.Gateset(cirq.ops.common_gates.XPowGate, cirq.ops.common_gates.ZPowGate, cirq.CNOT, unroll_circuit_op = True,accept_global_phase_op = True).validate
```

And I'm puzzled as how I've changed this behavior at all.

Any ideas?

**Comment by Cynocracy** [comment]
mm, I'm wondering if it's the yield statements and me not understanding where/why things are generators.

**Comment by Cynocracy** [comment]
I am stuck again, still ending up with a cirq.PhasedXZGate in the compiled circuit, which should be broken up. Pushed my latest yield-less changes

**Comment by tanujkhattar** [comment]
@Cynocracy You also need to override the `postprocess_transformers` property of your compilation target gateset and remove `merge_single_qubit_moments_to_phxz` transformer phase. 

See https://github.com/quantumlib/Cirq/blob/45624ff7259f53589c2139c97108d8bf11502173/cirq-core/cirq/transformers/target_gatesets/compilation_target_gateset.py#L114

**Comment by dstrain115** [comment]
See also #5129

**Comment by dstrain115** [comment]
@Cynocracy What is the status of this PR?  Do you still need help with this?  It looks like Tanuj had a suggestion in how to fix this.  Do you think we could either wrap this up, or expose the branch for someone else to finish?

**Comment by tanujkhattar** [comment]
This is fixed by https://github.com/quantumlib/Cirq/pull/5479
