### ISSUE TITLE
Raising tagged operations to a power removes tags. 

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4914]
```python
>>> import cirq
>>> a = cirq.NamedQubit("a")
>>> cirq.Z(a).with_tags("no compile") ** 1  ==  cirq.Z(a).with_tags("no compile")
False # Should be True
```

**Cirq version**
0.14dev

**Comment by tanujkhattar** [comment]
@vtomole I think this should have been done for other operations as well -- eg: `controlled_by`, `phase_by`, `decompose`, `classical_controls` etc. Let's open an issue to discuss it.

**Comment by vtomole** [comment]
Fom Cirq synch:


@95-martin-orion said that this behavior was deliberate cause of how gates can interact with the transformers/decomposers. Opened: https://github.com/quantumlib/Cirq/issues/4956

**Comment by 95-martin-orion** [comment]
> @95-martin-orion said that this behavior was deliberate cause of how tags can interact with the transformers/decomposers.

FWIW, the same is true for **all** `TaggedOperation` methods, not just `__pow__`.
