### ISSUE TITLE
Keeping tags for all `TaggedOperation` methods.

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#4956]
**Is your design idea/issue related to a use case or problem? Please describe.**
This is issue is the same as https://github.com/quantumlib/Cirq/issues/4914 except it's to discuss if we want to follow through with it.

**Comment by tanujkhattar** [comment]
As per discussion in last cirq sync, we should try to deprecate `TaggedOperations` and move tags to `Operation` class itself.

**Comment by vtomole** [comment]
From cirq sync: https://github.com/quantumlib/Cirq/issues/4914#issuecomment-1030137005
