### ISSUE TITLE
Fail fast on measurements in `has_unitary`

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#4959]
`cirq.has_unitary(cirq.measure(...))` should fail without having to attempt the full list of `has_unitary` strategies:

- Measurement is a common, easily-identified operation
- As highlighted in [qsim #502](https://github.com/quantumlib/qsim/pull/502), measurements on 33+ qubits may cause `has_unitary` to break due to the numpy limit of 32 dimensions in an ndarray.

**Comment by viathor** [comment]
Possibly a good idea to do this for circuits, too.

**Comment by tonybruguier** [comment]
@95-martin-orion 
Do you think this issue can be closed? If not, I'm happy to work more on it, of course.

**Comment by 95-martin-orion** [comment]
Looks resolved to me. Thanks for your help!
