### ISSUE TITLE
Add an option to transformers to preserve tags of operations. 

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4969]
Branched off from https://github.com/quantumlib/Cirq/issues/4923. 

For local transformers that act on individual operations (eg: transformers implemented via `map_operations` primitive), we can preserve the tags on the original operation. For non-local transformers, this is not well defined. 

Should we do it? Is there a use case for it? This issue is to track the request and discuss if something like this should be done.

**Comment by 95-martin-orion** [comment]
Set as pre-1.0, but only for the purposes of deciding if we need this.
