### ISSUE TITLE
Should we make `circuit._prev_moment_available` given impact of CCOs ?

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4976]
**Description of the issue**
While editing circuits, we often used `circuit.prev_moment_operating_on(op.qubits, end_moment_index)` to identify the position after which operation `op` can be inserted. This, however, is no longer correct and can lead to subtle errors, like the one came up during review of https://github.com/quantumlib/Cirq/pull/4944

For ex:
```python
>>> import cirq
>>> q = cirq.LineQubit.range(3)
>>> c = cirq.Circuit(
>>>     cirq.measure(q[0], key='m'),
>>>     cirq.X(q[1]).with_classical_controls('m'),
>>>     cirq.Moment(cirq.X.on_each(q[1], q[2])),
>>> )
>>> print(c)
0: ───M───────────
      ║
1: ───╫───X───X───
      ║   ║
2: ───╫───╫───X───
      ║   ║
m: ═══@═══^═══════
>>> op = c[1][q[1]]
>>> c.prev_moment_operating_on(op.qubits, 1) # Returns None, implies 0 as valid position to insert.

>>> c._prev_moment_available(op, 1) # Returns 1 as the valid position to insert.
1
```

We should either update (add a flag?) to `prev_moment_operating_on` s.t. it takes care of CCOs or make `_prev_moment_available` a public method. 

cc @95-martin-orion @daxfohl 

**Cirq version**
0.14dev

**Comment by tanujkhattar** [comment]
As a stretch goal, we should also find all existing usages of `prev_moment_operating_on` and figure out whether it breaks with CCOs and needs to be updated to use `_prev_moment_available`.

**Comment by tanujkhattar** [comment]
Can you give an example where taking an operation as input might be too limiting? Circuits only support inserting operations and when asking the previous moment available for insertion, it seems natural to me to take an operation as input.

**Comment by 95-martin-orion** [comment]
> Can you give an example where taking an operation as input might be too limiting?

This is a fair point - all cases I can come up with eventually want to add an operation anyways, so just using that operation for the check should be fine.

The main reason I raised this is that an operation is strictly more information than the method needs. Taking an operation forces creating a dummy op (e.g. `cirq.measure(*qubits, key='k')`) if there ever is a case where there isn't a relevant operation to use.

**Comment by tanujkhattar** [comment]
> an operation is strictly more information than the method needs

I agree. Maybe we can make this public as it is now and go through a deprecation cycle once we identify need for cases where an operation is not needed?
