### ISSUE TITLE
Move circuit serialization to Gatesets

### ISSUE THREAD

**Issue by verult** [quantumlib/Cirq#4982]
**Is your design idea/issue related to a use case or problem? Please describe.**
This is a refactor instead of solving a particular use case / issue.

**Describe your design idea/issue**
With Google device construction being revisited to leverage `cirq.Gateset` for validation, it would be useful to move circuit serialization (`cirq_google.CircuitSerializer`) and deserialization on server side to take advantage of Gatesets as well, to (1) stay consistent with the device flow in principle and (2) to reuse some of the machinery from the device flow (e.g. the GateFamily lookup table for all device gates).

The current serialization logic works well and is consistent with the planned validation logic, so there's no urgent need for any change. This suggestion is a refactor to simplify the logic. For example:
* Replace [gate type checks](https://github.com/quantumlib/Cirq/blob/aad6c57a7313b1ed7b211e0509cdec48eff2944b/cirq-google/cirq_google/serialization/circuit_serializer.py#L149) with Gateset
* Go back to the Operation proto with [`gate` string](https://github.com/quantumlib/Cirq/blob/aad6c57a7313b1ed7b211e0509cdec48eff2944b/cirq-google/cirq_google/api/v2/program.proto#L191) and `args`, with `gates now referencing a gate / gate type / GateFamily similar to the devices refactor design.

IIRC it was a deliberate decision to decouple program serialization with validation, and to move the program proto to hardcoded gate types. What was the rationale? This proposal is certainly missing half of the story :)

cc @dstrain115 @maffoo @MichaelBroughton @tanujkhattar

**Comment by maffoo** [comment]
I definitely think we should keep the separation between serialization (how do we send gates over the wire) and gatesets (what gates are allowed on a particular device). We will also need a way to serialize gatesets so that we can query the service to find out programmatically what gates a device supports, but I don't think we should go back to the old way of coupling that tightly to gate serialization itself (e.g. using strings to identify gates, and allowing each gateset to define its own set of strings everywhere).

**Comment by MichaelBroughton** [comment]
Also in favor of keeping these things decoupled. We've had issues in the past when we paired up the previous iteration of "Gatesets" in `cirq_google` with serialization and it was not great.

**Comment by verult** [comment]
Keeping them decoupled sgtm. There's a chance supporting serialization may complicate the generation of Gatesets from DeviceSpecification, and may also lead to tight coupling of DeviceSpecification and Program protos.
