### ISSUE TITLE
Records-based ResultDict fails serialization

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#5015]
Example code:

```python
a = cirq.ResultDict(params={}, records={'a': np.array([[[1, 1], [1, 1]], [[1, 1], [1, 1]]])})
aj = cirq.to_json(a)
# ValueError: Cannot extract 2D measurements for repeated keys
```

**Comment by 95-martin-orion** [comment]
CC @daxfohl @maffoo

I think `ResultDict` is new enough that we don't need backwards-compatibility tooling for this, but only if we can resolve it before the rapidly-approaching v0.14 release.

**Comment by maffoo** [comment]
@95-martin-orion, I'm happy to take this if you're busy.

**Comment by 95-martin-orion** [comment]
Thanks @maffoo, that would be great. Note that this needs to be wrapped up before the v0.14 release, which is slated for sometime next week.

**Comment by daxfohl** [comment]
I'd noticed a related thing here: https://github.com/quantumlib/Cirq/pull/4555#issuecomment-1039760100. Should we have `Result.measurements` return the most recent measurement for each key, if there are multiple on that key?

**Comment by maffoo** [comment]
> Should we have Result.measurements return the most recent measurement for each key, if there are multiple on that key?

I'm open to that but I worry it might be confusing that there are two supported ways to access the data (as opposed to one supported way via `.records` and a backwards-compatible `.measurements` property that we can deprecate in the future). If you want the most recent measurement for a key you can get this explicitly from the records with `results.records[key][:,-1,:]`.
