### ISSUE TITLE
Transformers (eg: optimized_for_sycamore) unroll circuit operations by default. 

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#5039]
**Description of the issue**

Calling `cirq.optimized_for_sycamore` on a circuit with a `CircuitOperation` is expected to optimize only the contents of the `CircuitOperation` while preserving the structure, but the circuit is instead flattened.

**How to reproduce the issue**

```
import cirq_google

q0, q1 = cirq.LineQubit.range(2)
cop = cirq.CircuitOperation(
    cirq.FrozenCircuit(
      cirq.H(q0),
      cirq.CX(q0, q1),
      cirq.measure(q0, key='r1a'),
      cirq.measure(q1, key='r1b'),
    )
)
circuit = cirq.Circuit(cop.repeat(3))
syc_circuit = cirq_google.optimized_for_sycamore(circuit)
# circuitops have been flattened
print(syc_circuit)
```

**Cirq version**
0.14.0.dev20220228000741

**Comment by tanujkhattar** [comment]
This is a known issue.  

We need to add support for a `deep=True` flag to all transformers so that when the flag is `True`, the transformer runs recursively inside a circuit operation, or else it directly inspects the contents of the circuit operation and treats it as a "single operation". 

Note that directly inspecting contents of a circuit operation can be useful, for example if we have a 2q circuit operation which implements a unitary that can be more efficiently re-written using an analytical decomposition. We can still brainstorm on whether the newly re-written unitary in this case should be wrapped inside a circuit operation (in the sense that it "preserves" structure) or not.

**Comment by 95-martin-orion** [comment]
I don't think deep/shallow fully describes this issue. Consider:
```python
cop = cirq.CircuitOperation(
  cirq.FrozenCircuit(
    cirq.H(q0),
    cirq.CircuitOperation(
      cirq.FrozenCircuit(
        cirq.CX(q0, q1),
        cirq.measure(q1, key='k')
      ),
    ).repeat(2)
  )
).repeat(5)
```
In order to make this Sycamore-friendly, both the `H` and the `CX` must be converted, which requires stepping into the inner `CircuitOperation` (i.e. `deep=True` behavior), but we also want to keep both `CircuitOperation`s, which IIUC is part of the `deep=False` behavior you describe.

The `ConvertToSycamoreGates` class already has the desired behavior, but it seems like this is now overridden by other sections of `optimized_for_sycamore`.

**Comment by tanujkhattar** [comment]
In my description, `deep=False` will treat the circuit operations similar to other operations in Cirq -- i.e. try to get a unitary and do an optimal decomposition. If not possible, fallback to `cirq.decompose`. Specifying `deep=True` will inspect the type of an operation, and if it's a circuit operation, it will recursively run the same transformer on the wrapped circuit. 

Consider the following example (similar to yours, but the internal wrapped circuit op is unitary and does not contain measurements). 

```python
>>> q0, q1 = cirq.LineQubit.range(2)
>>> cop = cirq.CircuitOperation(
  cirq.FrozenCircuit(
    cirq.H(q0),
    cirq.CircuitOperation(
      cirq.FrozenCircuit(
        cirq.CX(q0, q1),
        cirq.H(q1),
      ),
    ).repeat(2)
  )
).repeat(5)
>>> c = cirq.Circuit(cop)
>>> print(c)

      [           [ 0: ───@─────── ]             ]
      [ 0: ───H───[       │        ]──────────── ]
0: ───[           [ 1: ───X───H─── ](loops=2)    ]────────────
      [           │                              ]
      [ 1: ───────#2──────────────────────────── ](loops=5)
      │
1: ───#2──────────────────────────────────────────────────────

```

1. With  `deep=False`, it considers the entire 2q circuit operation as a single 2q unitary effect and finds optimal analytical decomposition (eg: for sqrt iswaps, using only 2 interacting gates).

```python
>>> cirq.optimize_for_target_gateset(c, gateset = cirq.SqrtIswapTargetGateset())

0: ───PhXZ(a=0.5,x=0.5,z=0.308)───────────iSwap───────PhXZ(a=-0.192,x=1,z=0)───iSwap───────PhXZ(a=-0.192,x=0.5,z=0.692)───
                                          │                                    │
1: ───PhXZ(a=0.192,x=1.02e-08,z=-0.192)───iSwap^0.5────────────────────────────iSwap^0.5───PhXZ(a=-0.0961,x=1,z=0)────────

```


2. With `deep=True` flag, it will inspect every circuit operation and recursively run the optimizer inside the circuit operation. So, the output should be equivalent to:

```python
>>> optimized_cop = cirq.CircuitOperation(
  cirq.FrozenCircuit(
    cirq.optimize_for_target_gateset(cirq.Circuit(cirq.H(q0)), gateset = cirq.SqrtIswapTargetGateset()),
    cirq.CircuitOperation(
      cirq.optimize_for_target_gateset(
          cirq.FrozenCircuit(
            cirq.CX(q0, q1),
            cirq.H(q1),
          ), gateset = cirq.SqrtIswapTargetGateset()
      ).freeze()
    ).repeat(2)
  )
).repeat(5)
>>> cirq.Circuit(optimized_cop)

      [                                [ 0: ───PhXZ(a=0.75,x=0.5,z=0.25)────iSwap───────PhXZ(a=-0.5,x=1,z=0)───iSwap───────PhXZ(a=0,x=0.5,z=0.25)───── ]             ]
      [ 0: ───PhXZ(a=0.5,x=-0.5,z=1)───[                                    │                                  │                                       ]──────────── ]
0: ───[                                [ 1: ───PhXZ(a=-1.0,x=0.75,z=-0.5)───iSwap^0.5──────────────────────────iSwap^0.5───PhXZ(a=-1,x=0.5,z=-0.25)─── ](loops=2)    ]────────────
      [                                │                                                                                                                             ]
      [ 1: ────────────────────────────#2─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ](loops=5)
      │
1: ───#2──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

**Comment by 95-martin-orion** [comment]
> In my description, `deep=False` will treat the circuit operations similar to other operations in Cirq {...}

Thanks for the clarification - I misunderstood the intent before. The `deep=False/True` dichotomy described above fulfills the requirements as I understand them.
