### ISSUE TITLE
Change return type of `SimulatesSamples._run` to `Sequence[ClassicalDataReader]`

### ISSUE THREAD

**Issue by daxfohl** [quantumlib/Cirq#5048]
**Is your feature request related to a use case or problem? Please describe.**

This is a step of #4449 (Keeping track of qubits we measure)

**Describe the solution you'd like**

We are now keeping track of the qubits we measure, in ClassicalDataReader. This data is accessible from the `simulate` method. However from `run`, that calls `_run` internally, which takes the classical data objects and returns a 3D numpy array of raw measurements.

Instead we should have `_run` return the full sequence of `ClassicalDataReader` objects, one per repetition. (from a quick look at the code, it looks like we could do this as a generator method if we want to get fancy -- and it could be useful to enable a do-until loop). This also applies to `StepResult.sample_measurement_ops`, since sometimes `_run` delegates to that (though this method is not abstract, so we could simply create a new method to replace it). We'll also have to adapt qsim to do this.

Once this is done, the last step will be to add a `ResultDict.from_classical_data_objects` factory, and corresponding accessors to get the qubit information.

**Comment by 95-martin-orion** [comment]
Following up on discussion elsewhere - how does this proposal interact with simulators which implement a different subset of simulator APIs than `SimulatorBase`? Notably, `run` and `simulate` come from `SimulatesSamples` and `SimulatesFinalState` respectively, and external simulators which implement one are not obligated to implement the other.

As a concrete example, the [qsim simulator](https://github.com/quantumlib/qsim/blob/master/qsimcirq/qsim_simulator.py) implements `SimulatesSamples` but not `SimulatesIntermediateState`, and this is not expected to change (it would hurt qsim performance). Would this proposal be compatible with how qsim currently functions?

**Comment by daxfohl** [comment]
Definitely needs fleshed out. But IIUC we did essentially the same thing when changing the expected return value of _run from 2D to 3D. (have run_sweep_iter (the calling function) adapt the response if it's the old style, adding a deprecation warning). So I think we should be able to do the same thing here?

**Comment by 95-martin-orion** [comment]
Discussed at Cirq sync - potential performance tradeoffs and complications with qsim need to be investigated before we can commit to this.

**Comment by daxfohl** [comment]
Un-staling
