### ISSUE TITLE
Don't run coverage check when tests fail

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#508]
I thought I already fixed this, but https://travis-ci.com/quantumlib/Cirq/jobs/130987423 from https://github.com/quantumlib/Cirq/pull/507 has failing tests producing a bogus coverage report.

**Comment by vtomole** [comment]
You might have fixed it because i haven't been able to reproduce it. This might have had to do with something else in the PR you are linking. Open if you able to reproduce.
