### ISSUE TITLE
Add 'experiments' package

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#509]
There are several standard experiments that people will want to do on qubits to see how well they work. These include:

- Rabi oscillations
- Ramsey fringes
- Randomized benchmarking
- ...? I'll ask some hardware engineers for others.

It would be nice for us to provide pre-built methods to do these experiments.

An **experiment** differs from an **example** in that *an experiment is useful to users who already fully understand the library*. Experiments provide runtime functionality, whereas examples demonstrate source code in simplified scenarios. We could have an example that runs experiments, but we'd never have an experiment that runs examples.

**Comment by vtomole** [comment]
Done: https://github.com/quantumlib/Cirq/tree/master/cirq/experiments. I'm going to tag https://github.com/quantumlib/Cirq/issues/1002 as it's related.

**Comment by Strilanc** [comment]
So many fixed issues!
