### ISSUE TITLE
Cierra

### ISSUE THREAD

**Issue by ceytah** [quantumlib/Cirq#5104]
**Description of the issue**access check k
35000000512.00 
$$# 
**Cirq version**cierra elaine adkins :trade 

You can get the cirq version by printing `cirq.__version__`. From the command line:

```
python -c 'import cirq; print(cirq.__version__)'
```

Approved, [Cash app]($iwannacat )

*all$$$&# 1008
CierraIDLE-

**Comment by vtomole** [comment]
Hey @ceytah,  https://github.com/quantumlib/Cirq/issues is only for issues related to Cirq. Given that. I'll close this.
