### ISSUE TITLE
Pauli Transfer Matrix (PTM) superoperator

### ISSUE THREAD

**Issue by anonymousr007** [quantumlib/Cirq#5105]
**Is your feature request related to a use case or problem? Please describe.**

- Adds  `PTM` quantum channel 

  - Tensor networks and graphical calculus for open quantum systems
Wood, Biamonte, Cory, Quant. Inf. Comp. 15, 0579-0811 (2015)
Open access: [arXiv:1111.6950v3](https://arxiv.org/abs/1111.6950)

  - Introduction to Quantum Gate Set Tomography
Daniel Greenbaum (2015)
Open access:[arXiv:1509.02921](https://arxiv.org/abs/1509.02921)

**Describe the solution you'd like**

I am working on this.

**Comment by MichaelBroughton** [comment]
```
> Describe the solution you'd like

I am working on this.
```

Could you elaborate a little more on what this means ? Is the plan to add some kind of new feature to our channel modules or some kind of experiment module to compute a PTM or something else entirely ?
