### ISSUE TITLE
[IONQ] Vendor Transformer adoption

### ISSUE THREAD

**Issue by MichaelBroughton** [quantumlib/Cirq#5129]
**Summarize the task**
With broader changes to devices (https://github.com/quantumlib/Cirq/issues/4744) and optimizers/trasnformers (https://github.com/quantumlib/Cirq/issues/4722), vendors might need to update device decomposition to use the newest transformer APIs. At first glance it looks like:

-----------------------------------

`cirq-ionq` has their own devices and should be in a good position to consolidate any missing device info into the metadata fields as well as adapt `decompose_to_device` into a proper transformer.

https://github.com/quantumlib/Cirq/blob/45624ff7259f53589c2139c97108d8bf11502173/cirq-ionq/cirq_ionq/ionq_devices.py#L106

@ColemanCollins @nakardo @gmauricio

**Acceptance criteria - when is the task considered done?**

**Related**

Related issues: #4901 , #5127

**Comment by dabacon** [comment]
@Cynocracy (who should probably be added to the owners)

**Comment by Cynocracy** [comment]
Adding comment so this can be assigned to me
