### ISSUE TITLE
Fix docstrings for type aliases in cirq.circuits.circuit.py

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#5150]
**Description of the issue**
The docstrings for type aliases defined in `cirq.circuits.circuit.py` are not helpful and should be improved / fixed. 

For example:
See https://quantumai.google/reference/python/cirq/circuits/circuit#CIRCUIT_TYPE

Where does the line "[INT_TYPE](https://quantumai.google/reference/python/cirq/circuits/circuit/INT_TYPE): The central part of internal API." comes from? 

The reference pages docstring also looks unrelated to the actual type.

https://quantumai.google/reference/python/cirq/circuits/circuit/INT_TYPE

**Cirq version**
0.15dev

**Comment by maffoo** [comment]
Looks like tensorflow docs have the same issue: https://www.tensorflow.org/addons/api_docs/python/tfa/types

**Comment by maffoo** [comment]
LOL at the docstring showing `TYPE_CHECKING` in the "Other Members" section of the module docs. That should never be shown. How do we file issues like this about the docsite? Would the docsite respect `__all__` if we were to define it?
![Screenshot from 2022-04-08 00-49-39](https://user-images.githubusercontent.com/129268/162390431-91374c6a-ba51-468c-90e1-7f2592b0edd1.png)

**Comment by tanujkhattar** [comment]
Reopening as we should verify after the nightly release that the problem is actually fixed on the docsite.

**Comment by maffoo** [comment]
Looks good in staging:
![Screenshot from 2022-04-11 16-07-55](https://user-images.githubusercontent.com/129268/162847534-395df426-ea6a-4bb0-9feb-4c16369bc377.png)
