### ISSUE TITLE
Gateset: Invalid repr if the gateset is empty

### ISSUE THREAD

**Issue by verult** [quantumlib/Cirq#5197]
**Description of the issue**
If a `Gateset` doesn't contain any gates, the repr contains an extra comma:
https://github.com/quantumlib/Cirq/blob/e31b48d04c7a3dea6bc2e5e320b0c606bbf13700/cirq-core/cirq/ops/gateset.py#L408-L411

@tanujkhattar Should we fix the repr or make empty Gatesets invalid?

**Cirq version**
0.14

**Comment by tanujkhattar** [comment]
We should fix this.
