### ISSUE TITLE
Add a less-accurate check script that runs without creating virtual environments

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#520]
Mirrors an issue in openfermion-cirq: https://github.com/quantumlib/OpenFermion-Cirq/issues/75

For contributors that don't have a debian machine and aren't familiar with virtualenv, this is the difference between being able to run the checks and not being able to run the checks.

**Comment by vtomole** [comment]
Closed by: https://github.com/quantumlib/Cirq/blob/master/continuous-integration/simple_check.sh
