### ISSUE TITLE
Patch release for cirq-ionq

### ISSUE THREAD

**Issue by Cynocracy** [quantumlib/Cirq#5210]
Hi!

I'm hoping to get clarity on whether we're able to do patch releases for specific pypi packages, in this case, cirq-ionq

We recently changed to return a more specific 'target' value in our API, which means https://github.com/quantumlib/Cirq/commit/fe7fe4e1d29e6b5fcc1643c0c73c26f8b37adae1 needs to be released, or cirq will treat 'qpu.target' jobs as being probabilistic simulation results.

Is it possible to do a patch release with this included?

**Comment by Cynocracy** [comment]
Feature-request because not sure what to tag this with :)

**Comment by Cynocracy** [comment]
@MichaelBroughton any more info needed to move forward on this? Thanks for considering it!

**Comment by MichaelBroughton** [comment]
Hmmm can you confirm that if you install the v0.14 release branch and then cherry pick this commit in, it is everything we need (no other follow ons needed) ? If that's the case I will do the same and cut a release on the weekend.

**Comment by Cynocracy** [comment]
Yes, that's right, can confirm

**Comment by Cynocracy** [comment]
And thank you!!

**Comment by MichaelBroughton** [comment]
https://github.com/quantumlib/Cirq/releases/tag/v0.14.1 :)
