### ISSUE TITLE
API docs don't show init when class string is defined

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#5214]
**Description of the issue**

The API docs don't appear to show the doc string for the `__init__` method when there is string supplied to the class string. The doc string for the `__init__` method is often much more useful.

Here is an example:
https://quantumai.google/reference/python/cirq/ops/ResetChannel

**Comment by tanujkhattar** [comment]
xref https://github.com/quantumlib/Cirq/issues/5151

**Comment by tanujkhattar** [comment]
Docstring should go in class definition and not in init.
