### ISSUE TITLE
Docs: Filter out TYPE_CHECKING from public docs

### ISSUE THREAD

**Issue by maffoo** [quantumlib/Cirq#5231]
**Description of the issue**

The `TYPE_CHECKING` variable imported from `typing` shows up in API docs (example: https://github.com/quantumlib/Cirq/issues/5150). We should filter it out, since it's not part of the cirq API. Per @dabacon's [comment](https://github.com/quantumlib/Cirq/pull/5229#issuecomment-1093080151), we should be able to do this in `dev_tools/docs/build_api_docs.py`.

**Comment by tanujkhattar** [comment]
xref https://github.com/quantumlib/Cirq/issues/5151
