### ISSUE TITLE
Documentation on gate constants should show that it is called on Qids

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#5232]
Example is cirq.X which shows up as `cirq.ops.X(*args, **kwargs)`

https://quantumai.google/reference/python/cirq/ops/X

These should show up as constant without the callable args and kwargs.

**Comment by dabacon** [comment]
Oh doh of course it is callable, just with qubits

**Comment by tanujkhattar** [comment]
xref https://github.com/quantumlib/Cirq/issues/5151
