### ISSUE TITLE
Rename ActOnXYZArgs to (say) XYZSimulationState

### ISSUE THREAD

**Issue by daxfohl** [quantumlib/Cirq#5244]
We've mentioned this task a number of times but never explicitly recorded it. I assume we do want to do this?

IIUC the safe way to do this is to rename the existing classes and files to what we want, and use those everywhere. Then create subclasses of each with the old name, and immediately deprecate them? This would break `isinstance(ActOnXYZArgs)`, which seems fairly low-risk. I believe everything else should continue to work.

* [ ] #5293
* [ ] Rename `_create_act_on_args` and `_create_partial_act_on_args` (requires deprecation).
* [ ] Misc "args" and "act_on_args" variables all over, though mostly in `sim`.

**Comment by 95-martin-orion** [comment]
I fully support this, so long as it doesn't introduce collisions with some of the new object names (*QuantumState should be fine...were there others that may be confusing?)

If we reference these in docs, those will also need to be updated.

**Comment by daxfohl** [comment]
Yeah, there are others that would be fairly confusing actually. We already have `DensityMatrixSimulatorState` and `StateVectorSimulatorState` that are completely unrelated. They are used internally but AFAICT they're *only* used as intermediate steps to calculate the final state vector / density matrix. I don't see any public functions that return these to the user. So we may be able to get away with just killing those and calculating the state vector directly from the corresponding `ActOnArgs` variant.

There's also a `CliffordState` that *is* returned in `CliffordTrialResult.final_state`, so we can't just get rid of it without some kind of deprecation. It would be nice to deprecate the `final_state` function and replace it with the one returning the `ActOnChFormArgs`, or just merge its functionality directly into `CliffordTrialResult`.

Once we do that we can remove the `TSimulatorState` from the generics list in `SimulatesIntermediateState`, which would be nice. Unless that would affect qsim.

**Comment by 95-martin-orion** [comment]
Removing the purely-internal types sounds fine to me as long as we're not losing performance or usability as a result.

RE qsim: [QSimSimulator](https://github.com/quantumlib/qsim/blob/4c01007b6a3e4d6c582326274f85fb857d38ca7e/qsimcirq/qsim_simulator.py#L171) does not and will not implement `SimulatesIntermediateState` and has no concept of `StepResult`s. As long as that's compatible with the changes happening here, I'm happy with it.

**Comment by 95-martin-orion** [comment]
As of #5293, this is solved. There's still deprecation to be done, but that will wrap up in time.
