### ISSUE TITLE
Cirq's QASM parser throws an exception for a classical register called `measure`

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#5262]
**Description of the issue**
Qiskit has a verification module that allows one to automatically generate quantum volume circuits. I want to to translate those circuits to Cirq. The problem is that the circuits generated from this module names `measure` as it's classical register which Cirq's QASM parser can't translate.

**How to reproduce the issue**
Install Qiskit on your system then run.

```python
import qiskit.ignis.verification.quantum_volume as qv

from cirq.contrib.qasm_import import circuit_from_qasm
from qiskit.compiler import transpile

rand_circ = qv.qv_circuits([[0,1]])[0][0][0]

t_rand_circ = transpile(rand_circ, basis_gates=['u1','u2','u3','cx'])
print(t_rand_circ.qasm())
# prints 
# OPENQASM 2.0;
# include "qelib1.inc";
# qreg q[2];
# creg measure[2];
# u3(0.95275496,-0.40048302,2.3396091) q[0];
# u3(1.4710132,1.4238801,-0.9022253) q[1];
# cx q[0],q[1];
# u3(0.7076726,-pi/2,-pi/2) q[0];
# u3(2.1567055,2.5482935,0.68681294) q[1];
# cx q[0],q[1];
# u3(0.28381753,-pi,pi/2) q[0];
# u3(1.0477967,0.64780817,-2.5581967) q[1];
# cx q[0],q[1];
# u3(1.4541338,-0.35391366,-1.7202243) q[0];
# u3(1.9771718,0.44431931,-0.27642371) q[1];
# barrier q[0],q[1];
# measure q[0] -> measure[0];
# measure q[1] -> measure[1];

qasm = t_rand_circ .qasm()

circuit_from_qasm(qasm)

```

<details>
Throws

```
QasmException: Syntax error: 'measure'
...creg measure[2];
u3(1.6718223,1.6527282,0.40326598) q[0];
u3(0.18482523,-2.950664,-0.51830493) q[1];
cx q[0],q[1];
u3(0.81029954,-pi/2,-pi/2) q[0];
u3(2.295253,2.7452754,1.007595) q[1];
cx q[0],q[1];
u3(0.57912606,-pi,pi/2) q[0];
u3(1.0477967,0.64780817,-2.5581967) q[1];
cx q[0],q[1];
u3(1.2627735,-0.0088513472,-0.77602329) q[0];
u3(1.0159967,3.1110487,1.918677) q[1];
barrier q[0],q[1];
measure q[0] -> measure[0];
measure q[1] -> measure[1];
        ^
at line 4, column 6
```
</details>

**Cirq version**
Master version

**Comment by daxfohl** [comment]
I think in `_parser.py` we need

```python
    def p_name(self, p):
        """name : ID
        | MEASURE""" # plus some other reserved words from `_lexer.py`
        p[0] = p[1]
        p.set_lineno(0, p.lineno(1))
```
Then update a few parser rules to use `name` instead of `ID`.

**Comment by daxfohl** [comment]
The qiskit library in question has been superseded: https://github.com/Qiskit/qiskit-ignis, in favor or https://github.com/Qiskit/qiskit-experiments.

`measure` is also an invalid creg name in `OPENQASM 2.0` (or at least it doesn't parse on their playground website).

@vtomole can you check if the replacement library has the same issue, and/or whether qiskit can parse its own output? (It looks like the underlying issue, if still there, may be in https://qiskit.org/documentation/_modules/qiskit/circuit/quantumcircuit.html#QuantumCircuit.measure_active, which seems like it should be a bug on the quiskit repo itself.)

**Comment by daxfohl** [comment]
Bug already filled https://github.com/Qiskit/qiskit-terra/issues/7866

**Comment by vtomole** [comment]
Good find. This is Qiskit bug. Qiskit is returning incorrect QASM. This isn't the first time Qiskit's QASM writer has gotten me in trouble: https://github.com/Qiskit/qiskit-terra/issues/8090. I've transferred this issue into a comment in your linked `qiskit-terra` issue. That's enough to close this.
