### ISSUE TITLE
Moment's measurement key objs and control keys should be frozen

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#5298]
Moments are, or should be, immutable.  However currently the return type of `_measurement_key_objs_` returns a set and not a frozenset.  This means one could change this set and modify the Moment.  

This is, however, a breaking change in terms of types, i.e. we would change the return type for `_measurement_key_objs_` to `FrozenSet`.  I'm not sure we have a great way to deprecate return types?

**Comment by maffoo** [comment]
We can leave the return type as `AbstractSet` and return `FrozenSet`, which is a subtype. I would not consider this a backward-incompatible change.

**Comment by daxfohl** [comment]
They're copied before the public protocol returns https://github.com/quantumlib/Cirq/blob/6f5c11e48d98968f5884f3f4efb844d4a1bc930d/cirq-core/cirq/protocols/measurement_key_protocol.py#L182

So this only affects the private method. (Ideally we should have specified the dunder to return a frozenset, then avoid the extra allocation in the public protocol implementation, though that might have created its own issues).
