### ISSUE TITLE
repeat_until incompatible with run repetitions

### ISSUE THREAD

**Issue by daxfohl** [quantumlib/Cirq#5318]
**Description of the issue**

Subcircuits with `repeat_until` can have non-deterministic number of measurements for a given key. `ResultDict` expects a flat array of measurement results. This can cause exceptions when run with multiple repetitions.

**How to reproduce the issue**

```python
def test_repeat_until_repetitions():
    q = cirq.LineQubit(0)
    key = cirq.MeasurementKey('m')
    sim = cirq.Simulator()
    c = cirq.Circuit(
        cirq.CircuitOperation(
            cirq.FrozenCircuit(cirq.X(q) ** 0.2, cirq.measure(q, key=key)),
            use_repetition_ids=False,
            repeat_until=cirq.KeyCondition(key),
        )
    )
    sim.run(c, repetitions=10)
```

Error:
```
cirq-core/cirq/work/sampler.py:53: in run
    return self.run_sweep(program, param_resolver, repetitions)[0]
cirq-core/cirq/sim/simulator.py:73: in run_sweep
    return list(self.run_sweep_iter(program, params, repetitions))
cirq-core/cirq/sim/simulator.py:104: in run_sweep_iter
    records = self._run(
cirq-core/cirq/sim/simulator_base.py:299: in _run
    return {str(k): np.array(v, dtype=np.uint8) for k, v in records.items()}
E   ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (10,) + inhomogeneous part.
```

**Cirq version**
0.15.0.dev

@95-martin-orion @maffoo WDYT?

**Comment by 95-martin-orion** [comment]
This is definitely an issue, but at least it appears contained to this case - AFAIK there's no situation where a measurement would have a different number of qubits across multiple repetitions / appearances within a repetition.

Numpy doesn't seem to have a nice solution for this. The closest I found was [`numpy.ma.array`](https://numpy.org/doc/stable/reference/maskedarray.generic.html#what-is-a-masked-array) (aka masked arrays), which require a bunch of overhead and still don't give the desired behavior in situations like `arr=[[1], [2, 3]]; len(arr[0])`. What currently consumes this data? Could we get away with a simple list-of-lists, or placeholders for unrealized measurements?

Alternatively, this might be a sign that we finally need the "do not expose in results" tag for measurements...

**Comment by maffoo** [comment]
In a case like this I would probably lean toward padding the measurement arrays with zeros to keep the overall shape rectangular. Since the keys that go into computing the loop termination condition are part of the result, the code that analyzes the result can figure out where things terminated on any given repetition of the circuit. I haven't thought too much about this, though.
