### ISSUE TITLE
It's too late to deprecate others using `cirq_type` in their json

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#5337]
There's a bad deprecation warning in the JSON serialization:

```
def _json_dict_with_cirq_type(obj: Any):
    base_dict = obj._json_dict_()
    if 'cirq_type' in base_dict:
        # TODO: upgrade to ValueError in v0.15
        warnings.warn(
            f"Found 'cirq_type': '{base_dict['cirq_type']}' in _json_dict_. "
            f"Custom values of this field are not permitted, and will produce "
            "an error starting in Cirq v0.15.",
            DeprecationWarning,
        )
        return base_dict
    return {'cirq_type': json_cirq_type(type(obj)), **base_dict}
```

**This cannot be changed into an error**. The main guarantee provided by json serialization is that it will continue to work forever. If using this key was going to be an error, it had to start as an error when json serialization was first written. You can't change it now, because that might break things which would mean they wouldn't continue to work forever.

I am aware of specific files out there that use these values, because stimcirq uses these keys for its custom operations. I've serialized circuits that had those operations in it. I expect them to continue to parse.

You are about to make a change that would break the main guarantee provided by json serialization. DO NOT DO THIS. Remove this deprecation warning instead of moving forward with it.

**Comment by maffoo** [comment]
cirq_type will still appear in the serialized file, the warning is saying that your code shouldn't put it there, but rather let the serialization framework do it for you. I don't think there's any compatibility issue with previously-serialized data.

**Comment by maffoo** [comment]
We ran into this internally as well. I think "what to do" is remove the explicit `cirq_type` entry in the dict you are returning, and define a `_json_namespace_` method that returns a string (you are encourage _not_ to use the empty string for this). The serialization framework will add a cirq_type field that is `{json_namespace}.{obj.__class__.__name__}`. If you do change to a non-empty json namespace, say `stim`, then you'll have to update the resolvers dict to be backwards compatibile with older data, something like:
```python
# non-namespaced resolvers, for compatibility with old data.
_JSON_RESOLVERS_DICT_OLD = {
    "CumulativeObservableAnnotation": CumulativeObservableAnnotation,
    "DetAnnotation": DetAnnotation,
    "MeasureAndOrResetGate": MeasureAndOrResetGate,
    "ShiftCoordsAnnotation": ShiftCoordsAnnotation,
    "SweepPauli": SweepPauli,
    "TwoQubitAsymmetricDepolarizingChannel": TwoQubitAsymmetricDepolarizingChannel,
}
JSON_RESOLVERS_DICT = {
    **_JSON_RESOLVERS_DICT_OLD,
    **{'stim.' + k: v for k, v in _JSON_RESOLVERS_DICT_OLD.items()},
    # Add new namespaced resolvers here only.
}
JSON_RESOLVER = JSON_RESOLVERS_DICT.get
```
This is at least how we handled the serialization changes internally. Perhaps @95-martin-orion can weigh in on whether this looks right, and also whether we can improve the deprecation message to make it more clear to people how to address it.
