### ISSUE TITLE
Document the Plethora of PauliStrings.

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#5352]
We have `PauliString`, `MutablePauliString`, `DensePauliString`, and `MutableDensePauliString`, but no discussion of what the difference is between these and when one should use each of these.   The dense ones, to my understanding, have no qubits associated with them, while the non-dense ones have gates associated with them (and so is :( an Operation).   In #5344 I added some documentation to the gate ones, but the documentation for the sparse ones needs to be updated.  Likely they should refer to each other to help clarify.

**Comment by dstrain115** [comment]
@augustehirth We think we should add documentation on pauli strings.  Where does this fit into the doc re-org for 1.0?  Once this is decided, please re-assign back to one of the developers, possibly @tanujkhattar
