### ISSUE TITLE
`DeviceMetadata` should expose a `NamedTopology` instead of `nx_graph` as property

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#5370]
Currenty, `DeviceMetadata` exposes a `nx_graph` property which stores the connectivity / topology information of the device. 

In parallel, we've been developing tools like `cirq.NamedTopology`, to better represent specific classes of device toplogies and build targeted utilities, like qubit placement and routing strategies, which can work with specific types of named topologies. 

I think `DeviceMetadata` should expose a named topology instead of directly exposing an nx_graph for a better integration with rest of the tooling. 

cc @mpharrigan @MichaelBroughton

**Comment by tanujkhattar** [comment]
What if we add a new `NamedTopology` which captures the "this is a general nx.Graph that we can't categorize into any other known topologies" class of graphs? Do you think then returning a named topology would be more useful?

**Comment by mpharrigan** [comment]
I don't know what that would buy us (over having an optional NamedTopology field on devicemetadata). Consuming code will have to handle the cases separately anyways.

**Comment by tanujkhattar** [comment]
Having an optional NamedTopology field on device metadata would, of course, be enough as well. The discussion is to decide between:

1. Having an optional named topology + non-optional nx.Graph: which can be confusing because `metadata.named_topology.graph` and `metadata.nx_graph` would be 2 ways of getting the same graph.
2. Replace nx_graph by a named topology instead and add a new class of named topologies which captures all cases that don't have a better categorization.

**Comment by MichaelBroughton** [comment]
The way I think of NamedTopology is it is more of a mathematical object than it is a physical object like a device graph. If one had a circuit that obeyed a particular topology constraint i.e. it was a TiltedSquareLattice or a Line then the natural way to do that placement would be to do something like:

```python3
desired_topo = <some_named_topology>
graph_to_place_on = device.metadata.nx_graph
possible_placements = cirq.get_placements(graph_to_place_on, desired_topo)
for x in possible_placements:
   whatever
```
I think the `nx_graph` gives us a nice abstraction level and we don't want to hite too much away from the user. WDYT @mpharrigan ?

**Comment by mpharrigan** [comment]
A networkx graph is a microscopic description of nodes and edges whereas a NamedTopology uses few macroscopic variables to imply a graph. The data size of a NamedTopology does not scale with the size of the graph it implies. The data size of a graph does scale with the size of the graph.

**Comment by mpharrigan** [comment]
It's easy and always possible to go from NamedTopology -> Graph. It's difficult and often impossible to go from Graph -> NamedTopology

**Comment by mpharrigan** [comment]
```python

class Image:
  pixels: np.ndarray(ndim=2)

class Animal:
  species: str

  def get_image() -> Image:
    return  Image(pixels=np.load(f"~/animal_photos/{self.species}.jpg"))
```

**Comment by tanujkhattar** [comment]
From cirq sync:

NamedTopologies represent abstract, device independent, topologies. Returning a named topology from a device will have a risk of leaking device specific constraints, like broken qubits, into named topologies. 

We can consider adding the device graph specific properties to device metadata independently, to enable placement and circuit routing routines to make use of these properties. 

@mpharrigan What do you think?

**Comment by mpharrigan** [comment]
yes, that makes sense

**Comment by tanujkhattar** [comment]
Sounds good, I'll go ahead and close this issue.
