### ISSUE TITLE
Make simulation state classes "private"

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#5401]
Subclasses of [SimulationState](https://github.com/quantumlib/Cirq/blob/e68ff85e9bb0c7373572cdc212c10f226cd40b0f/cirq-core/cirq/sim/simulation_state.py#L45) are "behind the curtain", so to speak - they represent the internal workings of the simulation toolkit, and aren't expected to be implemented by users. We should mark these classes as private (e.g. `_QuantumState`) to allow us to continue modifying this behavior post-1.0.

CC @daxfohl

**Comment by daxfohl** [comment]
There's a `SimulationTrialResultBase.get_state_containing_qubit` that leaks the state class. Seems like that could easily be made private though. I'm pretty sure that's the only place.

**Comment by 95-martin-orion** [comment]
Based on discussion in Cirq design meeting and the complexity of the proposed solution, we determined that this causes more confusion than it resolves. Dropping this issue.
