### ISSUE TITLE
Tesselating small TiltedSquareLattice's on big ones

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#5460]
Imagine I have a little 2x2 tilted square lattice circuit that I want to run in all the possible spots on a larger (e.g. 10x8 tilted square lattice) device. I'd like to tessellate my small graph and make sure that no qubits are "overlapping"

**Comment by viathor** [comment]
(Meta: triage/needs-feasibility is not ideal, but is closest triage label to "needs agreed design". Maybe we should have triage/needs-agreed-design? @dstrain115 )
