### ISSUE TITLE
Support confusion maps in defer_measurements

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#5482]
Requested in #5480 as a follow-up for #4348. Confusion maps are a generalization of the previous `invert_mask` behavior in measurements, and the `defer_measurements` transformer should support them.

**Comment by 95-martin-orion** [comment]
CC @tanujkhattar - I marked this as after 1.0 since it looks potentially complicated but non-breaking.

**Comment by daxfohl** [comment]
#5851 did this. Can close this now.

**Comment by pavoljuhas** [comment]
Closed by #5851
