### ISSUE TITLE
Deprecate Engine.run and friends?

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#5505]
@dstrain115 : what's the plan with all the methods on `Engine` that aren't in `AbstractEngine`? I think we should deprecate them and/or modify them to delegate to `EngineProcessor` methods.

**Comment by dstrain115** [comment]
I am not sure about this.  There's a bunch of non-standard features, like sending to multiple processors or sending programs without jobs, etc that I am reluctant to get rid of.  On the other hand, it's not great to have a bunch of methods that are not in the abstract interface.

Bringing in @wcourtney to weigh in.

**Comment by mpharrigan** [comment]
@wcourtney what do you think?

**Comment by mpharrigan** [comment]
bump @wcourtney

**Comment by mpharrigan** [comment]
@wcourtney what do you think?

**Comment by wcourtney** [comment]
> sending to multiple processors or sending programs without jobs

2¢: As I understand it, both of these features are confusing to users. IMO, it's a user win to clean up these legacy features even if it's a bit of work to bring them back. If that happens, I expect that we'll have new requirements for the features and a new model and if there was churn in the meantime, we can skip all intermediate the migration work :-).

**Comment by dstrain115** [comment]
These were removed in the interface and only persist in the implementation.

Also, this is now a duplicate of https://github.com/quantumlib/Cirq/issues/6271
