### ISSUE TITLE
CircuitOperation mutability

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#5507]
```python
import cirq
from cirq import CNOT
from cirq import GridQubit as q

q0, q1 = cirq.LineQubit.range(2)

co = cirq.CircuitOperation(
    circuit=cirq.Circuit(CNOT(q0, q1)).freeze(),
)

circ = cirq.Circuit()
co.qubit_map[q0] = q(5, 5)
co.qubit_map[q1] = q(6, 6)
circ += co

co.qubit_map[q0] = q(7, 7)
co.qubit_map[q1] = q(8, 8)
circ += co

print(len(circ))
print(circ)
```

```
1
           ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
(5, 5): ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

(6, 6): ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

            [ 0: ───@─── ]                                          [ 0: ───@─── ]
(7, 7): ────[       │    ]──────────────────────────────────────────[       │    ]──────────────────────────────────────────────
            [ 1: ───X─── ](qubit_map={q(0): q(7, 7), q(1): q(8, 8)})[ 1: ───X─── ](qubit_map={q(0): q(7, 7), q(1): q(8, 8)})
            │                                                       │
(8, 8): ────#2──────────────────────────────────────────────────────#2──────────────────────────────────────────────────────────
           └────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

note how this results in two operations happening on the same qubit at the same moment

@95-martin-orion  #5502

**Comment by maffoo** [comment]
Yeah, don't do that. Should use `with_qubit_mapping` instead:
```python
import cirq

q0, q1 = cirq.LineQubit.range(2)

co = cirq.CircuitOperation(
    circuit=cirq.Circuit(cirq.CNOT(q0, q1)).freeze(),
)

circ = cirq.Circuit(
    co.with_qubit_mapping({q0: cirq.q(5, 5), q1: cirq.q(6, 6)}),
    co.with_qubit_mapping({q0: cirq.q(7, 7), q1: cirq.q(8, 8)}),
)

print(len(circ))
print(circ)
```
Which gives
```
1
           [ 0: ───@─── ]
(5, 5): ───[       │    ]─────────────────────────────────────────────
           [ 1: ───X─── ](qubit_map={q(0): q(5, 5), q(1): q(6, 6)})
           │
(6, 6): ───#2─────────────────────────────────────────────────────────

           [ 0: ───@─── ]
(7, 7): ───[       │    ]─────────────────────────────────────────────
           [ 1: ───X─── ](qubit_map={q(0): q(7, 7), q(1): q(8, 8)})
           │
(8, 8): ───#2─────────────────────────────────────────────────────────
```

**Comment by 95-martin-orion** [comment]
What this basically comes down to is the fact that `CircuitOperation` is immutable by fiat and not by mechanics. `CircuitOperation` has maps for params, measure keys, and qubits; manually changing these will absolutely make a mess of your circuit.

The reason I don't see tuples as a viable alternative is that `CircuitOperation` is meant for use in big, repetitive circuits. Performance in handling those circuits would suffer if subcircuit map-lookups were replaced with tuple inspection, and I don't really see explicit mutation protection (as opposed to the docstring "this class is immutable" warning) as valuable enough to justify the change.

**Comment by daxfohl** [comment]
Would `_qubit_map: Dict[Qid, Qid]` and `@property def qubit_map(self) -> Mapping[Qid, Qid]: return self._qubit_map` be a useful compromise? It doesn't prevent the misuse, but at least the mypy check would catch it.

**Comment by maffoo** [comment]
@daxfohl, I think that's reasonable. I'd be curious to hear what @mpharrigan thinks. My feeling is that almost nothing in python is ever _truly_ immutable and it's rarely worth trying to make it so; all we can do is communicate the intended immutability to users, and doing that in a way that tools like mypy can check is even better.

**Comment by mpharrigan** [comment]
Yes, nothing is immutable. Copying in the dictionary to a private attribute exposed by a property is as good as it gets. not copying, but still exposing behind a property -- I don't know how this works exactly. Would mypy warn if you did what I did above?

**Comment by 95-martin-orion** [comment]
Decision from Cirq sync: we'll make attributes private (_name + property name) for both CircuitOperation and ParamResolver to mitigate this, as long as it isn't terribly expensive / disruptive.
