### ISSUE TITLE
Remove neutral atoms tutorial?

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#5521]
**Summarize the task**
https://github.com/quantumlib/Cirq/pull/5519 will deprecate and eventually remove `cirq.NeutralAtomDevice` from Cirq. The only place it's used right now is in https://github.com/quantumlib/Cirq/blob/master/docs/tutorials/educators/neutral_atom.ipynb

I propose that we should get rid of the tutorial once the PR is checked in. The same strategy would be followed for ion device tutorial, as discussed in https://github.com/quantumlib/Cirq/issues/5463

cc @augustehirth @aasfaw LMK if the proposal looks good.

**Comment by augustehirth** [comment]
If the tutorial uses deprecated code definitely delete it. If not, might it serve as a useful example for people trying to build custom Devices? Or has Device evolved too far for it to be useful?
