### ISSUE TITLE
Test failures in analytical decomposition transformers

### ISSUE THREAD

**Issue by maffoo** [quantumlib/Cirq#5533]
In #5219 I've started seeing test failures in analytic decomposition tests, see https://github.com/quantumlib/Cirq/runs/6913023342?check_suite_focus=true.

```
FAILED cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_fsim_test.py::test_decompose_two_qubit_interaction_into_two_b_gates[obj10]
FAILED cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_fsim_test.py::test_decompose_two_qubit_interaction_into_four_fsim_gates_equivalence[obj190-fsim_gate190]
```
Possibly related to recent change in default precision (https://github.com/quantumlib/Cirq/pull/5426).

**Comment by tanujkhattar** [comment]
This doesn't seem to be fixed yet.

See: https://github.com/quantumlib/Cirq/runs/6976353468?check_suite_focus=true

**Comment by vtomole** [comment]
[Another one](https://github.com/quantumlib/Cirq/runs/7018027686?check_suite_focus=true)

**Comment by dstrain115** [comment]
Is this fixed now that 128 has been rolled back?

**Comment by dabacon** [comment]
yes fixed.
