### ISSUE TITLE
Cirq docs pages `404s`

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#5547]
**Description of the issue**
This is probably due to our ramp up to `Cirq 1.0`, but none of the links to the Cirq docs that are indexed by Google search work anymore. Even the links in the docs themselves `404`.

**How to reproduce the issue**
Google a Cirq  functionality and click on the first `quantumai.google` link

![Screenshot from 2022-06-17 10-34-00](https://user-images.githubusercontent.com/8405160/174330495-c0ca6187-67d8-4fc1-af9b-0eaedfb1abe0.png)

**Cirq version**
Cirq master and `0.14.1`

**Comment by vtomole** [comment]
This might be more so to Google search indexing than the docs themselves. I can access stuff by going to the `quantumai.google` site so this might not really be a bug. Closing.

**Comment by dstrain115** [comment]
Cirq cync:   Most of these should be fixed now with added redirects.  A few remaining stragglers will remain, but should disappear over time.

**Comment by vtomole** [comment]
Looks like this is not an issue anymore. Will re-open if I run into it again.
