### ISSUE TITLE
UnitSweep should be UNIT_SWEEP

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#5617]
It's a constant, not a class.

**Comment by dstrain115** [comment]
Discussion:  This is a singleton, but it has a different convention than some of the other sweeps.
For consistency with other sweeps, we may want to keep this as camel case.
Other singletons such as Sycamore, Foxtail, also, follow camelcase convention.

**Comment by dabacon** [comment]
Some of the singletons don't though: `Pauli.X`, all our gate constants follow the correct style rule as well.  This may be easy for us to remember, but for users coming in from the outside a strong consistency in style is very helpful. For example knowing the `cirq.CNOT` is a gate instance is useful in that there is often confusion when learning Cirq about gate classes, gate instances, and op instances.
