### ISSUE TITLE
Tiny doc bug: incorrect arg shown to dev_tools/modules.py in dev/modules.md

### ISSUE THREAD

**Issue by mhucka** [quantumlib/Cirq#5637]
**Description of the issue**

In the Cirq [modules](https://quantumai.google/cirq/dev/modules) documentation, at the bottom, the command line to list modules is given as
```
python dev_tools/modules.py --list
```
but in fact, attempting to use `--list` will result in an error, because the argument should actually be `list` (without the dashes).

**How to reproduce the issue**

In a shell, with the current directory being the top of the Cirq repo, running `python dev_tools/modules.py --list` results in the following error:
```
usage: A utility for modules. [-h] {list,print_version,replace_version} ...
A utility for modules.: error: unrecognized arguments: --list
```

**Cirq version**

`0.15.0.dev`

**Comment by dstrain115** [comment]
Discussion: this has already been fixed.

**Comment by vtomole** [comment]
Fixed by https://github.com/quantumlib/Cirq/pull/5638
