### ISSUE TITLE
YPowGate has no dimension

### ISSUE THREAD

**Issue by 95-martin-orion** [quantumlib/Cirq#5647]
Follow-up to #4782: we added a dimension property for X and Z, but Y remains locked to qubits. This seems like an oversight - can we finish out the pauli trio by adding dimensions to YPowGate?

**Comment by 95-martin-orion** [comment]
CC @daxfohl

**Comment by daxfohl** [comment]
X and Z have standard generalizations to higher dimensions https://en.wikipedia.org/wiki/Generalizations_of_Pauli_matrices#Construction:_The_clock_and_shift_matrices

I wasn't able to find a standard for Y. Probably the relation `Y**k = X**0.5 * Z**k * X**-0.5` (or something like that) holds in higher dimensions? If so, we could define Y in higher dimensions via decomposition. (Unless someone with more linear algebra background than me can figure out the actual eigencomponents).

**Comment by dabacon** [comment]
Yeah I don't think there is a canonical definition of a higher order Y operator.  Consider for example`X Z` and `X**(-1)Z`.  In d=2 these are the same, but in d>2 they are different.  So which one are we to chose?

**Comment by daxfohl** [comment]
(Except in other contexts where Y is _the_ canonical higher order operator https://en.m.wikipedia.org/wiki/Fixed-point_combinator#Fixed-point_combinators_in_lambda_calculus) :)
