### ISSUE TITLE
`dev_tools/modules.py` fails with a confusing error if invoked without argument

### ISSUE THREAD

**Issue by mhucka** [quantumlib/Cirq#5702]
**Description of the issue**

The program `dev_tools/modules.py` exits with a confusing and user-unfriendly error message if it is invoked without any arguments. At the same time, it is not obvious (or at least, I haven't found it mentioned in the docs) that _not_ passing any arguments to it is unsupported. 

**How to reproduce the issue**

In a shell, with the current directory being the top level of the Cirq source code repo cloned from GitHub, run the following command:

```
python dev_tools/modules.py
```

<details>

```
Traceback (most recent call last):
  File "/Users/mhucka/project-files/quantum/repos/Cirq/dev_tools/modules.py", line 317, in <module>
    main(sys.argv[1:])  # coverage: ignore
  File "/Users/mhucka/project-files/quantum/repos/Cirq/dev_tools/modules.py", line 309, in main
    f = args.func
AttributeError: 'Namespace' object has no attribute 'func'
```

</details>

**Cirq version**

0.16.0.dev

**Additional comments**

A user coming to Cirq might reasonably try to run `python dev_tools/modules.py`, not knowing ahead of time what arguments are valid. IMHO, it would be more user-friendly if `modules.py` would at least print a help message if invoked without arguments.

**Comment by vtomole** [comment]
@mhucka You can close it. BTW, if the PR description contains `Fixes #PR Number`, a bot will close this issue once that PR is merged.

**Comment by mhucka** [comment]
Oh, good to know! Thanks!
