### ISSUE TITLE
Move `durations_of` and `neigbors_of` methods in AQTDevice to metadata

### ISSUE THREAD

**Issue by pavoljuhas** [quantumlib/Cirq#5726]
**Description of the issue**

Follow-up to the changes requested in #5696.

**Comment by pavoljuhas** [comment]
The AQTDevice.neighbors_of() method can be removed and replaced by LineQubit.neighbor().

I am however not sure about the durations_of method.
The DeviceMetadata does not have an attribute for gate durations.
There is only one derived class, GridDeviceMetadata, which has a gate_durations dictionary,
but AQTDevice is not GridDevice so this class is not appropriate.

@MichaelBroughton , @dstrain115 - should I be adding a new AQTDeviceMetadata class with an extra gate_durations attribute?

**Comment by tanujkhattar** [comment]
You will have to create a new derived class `AQTDeviceMetadata` which exposes the relevant properties / methods like `durations_of` and `neighbors_of`
