### ISSUE TITLE
Modify Alpha notice.  

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#5761]
Currently we have an alpha release statement at bottom of readme.  
```
Cirq is currently in alpha. We may change or remove parts of Cirq's API when making new releases. To be informed of deprecations and breaking changes, subscribe to the [cirq-announce google group mailing list](https://groups.google.com/forum/#!forum/cirq-announce).
```

For 1.0 should we be changing this?

**Comment by tanujkhattar** [comment]
AFAIR, we also have a similar line in many of our docs. For example: https://github.com/quantumlib/Cirq/blob/a2fd90225217d2b0821b5f6c97d75eb3506bb51a/docs/start/intro.ipynb?short_path=f48a42c#L145
