### ISSUE TITLE
Exponentiating a TaggedOperation drops the tag

### ISSUE THREAD

**Issue by verult** [quantumlib/Cirq#5784]
Is this expected?

**How to reproduce the issue**

```
>>> cirq.Z(cirq.LineQubit(0)).with_tags('some_tag') ** 0.5
cirq.S(cirq.LineQubit(0))
```

<details>

put long logs in details blocks *like this*

</details>

**Cirq version**

v1.15.0

**Comment by maffoo** [comment]
The original intent of allowing exponent on operation was so that one could write `cirq.X(q)**p` and have it be the same as `(cirq.X**p)(q)`. This was added long before tags were a thing, but I think it'd make sense to preserve tags when exponentiating.

**Comment by daxfohl** [comment]
#4914

**Comment by verult** [comment]
Thanks for the context - closing
