### ISSUE TITLE
Make CircuitDiagramInfo also support LaTeX

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#579]
Often gates in LaTeX look something like `R_{z}(\theta)`. I think there are three parts of this: the main letter `R`, the subscript `z`, and the angle `\theta` which will be in rads, not half-turns.

Another thing is that when possible, people like to draw two-qubit gates as a single box with two lines going into it and the description of the gate in the center of the box. Using the qcircuit functionality in contrib, two-qubit gates always look like two separate boxes connected by a line.

It would be cool to take care of this stuff automatically.

**Comment by dabacon** [comment]
The code to produce qcircuit LaTeX currently uses the circuit info object.  It does output code that has single boxes for multiqubit gates.

I think the question that remains here is whether there should be a way to specify gates as @kevinsung suggested, i.e. should the information that is returned by gates include an explicit LaTeX version R_z(\theta).

I'm going to title this to reflect that.  Please let me know if I've misidentified this issue.

**Comment by tanujkhattar** [comment]
Adding better latex support for diagrams using QPIC is currently tracked in https://github.com/quantumlib/Cirq/issues/5895

Closing this as a duplicate
