### ISSUE TITLE
Cirq overview page at https://quantumai.google/cirq could mention availability of QVM

### ISSUE THREAD

**Issue by mhucka** [quantumlib/Cirq#5803]
**Is your feature request related to a use case or problem? Please describe.**

The Overview page at <https://quantumai.google/cirq> currently does not mention the availability of the [quantum virtual machine](https://quantumai.google/quantum-virtual-machine). One only finds mention of the QVM by clicking on the "Simulate" page link in the top banner. This is a little bit hard to find.  It seems like it would help if the QVM was mentioned right on the overview/front page itself.  

**Describe the solution you'd like**

It would be help for the QVM to be mentioned right on the page somewhere. One idea is to mention it in the "Features" section, perhaps as an additional link in the "Simulation" box (like "Simulation with the QVM" or something like that). 

![image](https://user-images.githubusercontent.com/1450019/180059061-2a573060-dc80-4fa2-853d-7caf81fedf53.png)

But that's just one idea. Maybe another placement would be better.

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle

**Comment by mhucka** [comment]
I should add that this isn't meant as an annoying "why have you fixed this yet?" kind of issue – I know full well the QVM was only just announced, and of course one can't expect everything to be done everywhere all at once. This is just a "mentioning this very nonurgent thing in passing in case it's not on anyone's radar yet" kind of report.

**Comment by dabacon** [comment]
Flagging this for @augustehirth

**Comment by augustehirth** [comment]
Added!
