### ISSUE TITLE
"Textbook algoritheets"

### ISSUE THREAD

**Issue by mhucka** [quantumlib/Cirq#5806]
**Description of the issue**

There's an obvious typo on the page at <https://quantumai.google/education>. I would offer a PR to fix it but I haven't figured out where the source pages are kept. In a past Cirq Cynq, I was advised to report such issues in this issue tracker, so here it is.

![image](https://user-images.githubusercontent.com/1450019/180354272-20a7d78d-4d2d-4d30-a73f-d7ae94915b4d.png)

**Comment by thisisjaymehta** [comment]
I dont think that webpage is sourced from this repo.

**Comment by mhucka** [comment]
> I dont think that webpage is sourced from this repo.

I agree! But in a not-too-long-ago Cirq Cynq, I specifically asked about where to report issues on such pages because I couldn't find the right repo. People said they didn't think there was a public repo for them, and said to report them here anyway.

And so, here we are.

**Comment by augustehirth** [comment]
We've got a fix for this in the pipeline. Ty for letting us know!

**Comment by dabacon** [comment]
What is an algoritheets? lol

**Comment by augustehirth** [comment]
Dunno but it should be fixed :)
