### ISSUE TITLE
Is Cirq planning to support Honeywell quantum computers?

### ISSUE THREAD

**Issue by yurivict** [quantumlib/Cirq#5813]
[Honeywell quantum computers](https://www.honeywell.com/us/en/company/quantum/quantum-computer)

**Comment by vtomole** [comment]
Hey @yurivict, we already support Honeywell. See this [Getting Started With Honeywell Notebook](https://github.com/quantumlib/Cirq/blob/f3987d528156f1f746b73fd7b3ca9bdb7e0bd2c3/docs/hardware/azure-quantum/getting_started_honeywell.ipynb).
