### ISSUE TITLE
`AbstractCircuit.freeze` should not reallocate moments

### ISSUE THREAD

**Issue by maffoo** [quantumlib/Cirq#5816]
**Description of the issue**

When freezing circuits, `Moment` instances should be reused since they are immutable. This was previously the case, but seems to have changed recently (possibly due to https://github.com/quantumlib/Cirq/pull/5332).

**How to reproduce the issue**

```
In [1]: q = cirq.q(0)

In [2]: c = cirq.Circuit(cirq.X(q), cirq.measure(q))

In [3]: f = c.freeze()

In [4]: [mc is fc for mc, fc in zip(c, f)]
Out[4]: [False, False]
```

**Cirq version**

1.1.0.dev20220801180412

**Comment by daxfohl** [comment]
Yes, looks like it was from https://github.com/quantumlib/Cirq/pull/5332. The `with_operations` below is what does it.  `Moment.with_operations` creates a new Moment even if the input list is empty.

https://github.com/quantumlib/Cirq/blob/65ebb4a4d4a7b8b15e766b486e19582c634c1641/cirq-core/cirq/circuits/circuit.py#L1823

You could either change the code here to skip the `with_operations` call if there are no operations to append, or alternatively, have `Moment.with_operations` return `self` if the input is empty.

**Comment by verult** [comment]
From Cirq sync - this will be considered a bug fix as it returns the API behavior to the original intention.
