### ISSUE TITLE
Strange behavior after upgrading to cirq 0.1.0

### ISSUE THREAD

**Issue by andreamari** [quantumlib/Cirq#5819]
After upgrading to cirq v0.1.0 the following code doesn't work (runs forever):
```python
circuit = cirq.Circuit(cirq.H.on(cirq.LineQubit(0)))
circuit.append(circuit)
```
It used to work with cirq v0.15.0  . 
 
Not sure if this is an actual bug since appending a mutable object to itself ( `circuit.append(circuit) ) it's probably a bad idea and one should probably avoid it in the first place.

Still, I am reporting this fact here since that code used to work before upgrading.

FYI: the following code works as expected: 

```python
circuit = cirq.Circuit(cirq.H.on(cirq.LineQubit(0)))
circuit.append(circuit.copy())
```

**Comment by vtomole** [comment]
This is the PR  that causes it: https://github.com/quantumlib/Cirq/pull/5332. Specifically this change: https://github.com/quantumlib/Cirq/pull/5332/files#r940546694. Pinging @daxfohl.

**Comment by daxfohl** [comment]
I see, looks like passing the circuit into itself would cause the iterator to infinite loop there. Wrapping in a list should fix it: `for moment_or_op in list(ops.flatten_to_ops_or_moments(moment_or_operation_tree)):`. Feel free to make the change; my time for cirq is limited these days.

**Comment by andreamari** [comment]
Thanks for the quick reply and fix!
