### ISSUE TITLE
Add a classical simulator to Cirq

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#5822]
The feature request is to add a classical simulator which can simulate X / CNOT and multi-controlled X gates, similar to `ToffoliSimulator` in Q# 

See https://docs.microsoft.com/en-us/azure/quantum/machines/toffoli-simulator 

cc @mpharrigan to add more context

P2 - we should do it in the next couple of quarters 

cc @augustehirth This would need documentation once we get this done.

**Comment by daxfohl** [comment]
Note we've got a very basic implementation already in the test case for custom_simulator: https://github.com/quantumlib/Cirq/blob/master/cirq-core/cirq/contrib/custom_simulators/custom_state_simulator_test.py

I recommend starting there, copying it to its own non-test file, and then fleshing it out with @cduck's code linked in #3079.

**Comment by daxfohl** [comment]
Also note one feature missing from @cduck's implementation is decomposition strategy as a fallback. (I noticed this in MPS simulator too--probably this logic should go into SimulatorBase so that all the simulators do a decomposition fallback by default).

**Comment by dstrain115** [comment]
I have a student who can do this project.

**Comment by mpharrigan** [comment]
@daxfohl the example custom simulator doesn't support things like e.g. CNOT. Do we have to switch on the gate type in `_act_on_fallback_`? It's probably necessary for gates themselves to declare how to operate on computational basis states like how gates know how to act on a state vector

**Comment by daxfohl** [comment]
Correct, @cduck's implementation has the proper state transition logic. My example shows how to integrate into the custom simulator infrastructure so that you get subcircuit traversal, classical control, etc. for free. So the actual implementation needs to combine these two things.

**Comment by mpharrigan** [comment]
How though? Is _act_on_fallback_ supposed to interrogate the gate to see if it has a magic method that knows how to act on a classical state?

**Comment by daxfohl** [comment]
Using protocols, like https://github.com/cduck/cirqtools/blob/master/cirqtools/classical_simulator.py#L118-L149.

**Comment by mpharrigan** [comment]
I was imagining having methods on classical gates that could express their classical action on a bitstring without tensoring up a unitary

**Comment by daxfohl** [comment]
I see, yeah you could make a new protocol like `apply_to_bitstring(bitstring) -> bitstring` and supplement cduck's method like

```python
        if cirq.has_application_to_bitstring(op):
           state = cirq.apply_to_bitstring(op, state, indices)
        elif cirq.has_unitary(op):
            self._simulate_unitary(op, state, indices)
        else:
            self._simulate_mixture(op, state, indices)
```
or something along those lines. That way you get the `apply_to_bitstring` shortcut plus the ability to fall back to unitary if that protocol was not implemented on the gate.

**Comment by verult** [comment]
From Cirq sync: reverting back to accepted. @viathor let us know if there's anything you'd like to discuss

**Comment by viathor** [comment]
Oh, I think I added triage/discuss by accident (probably missed that the issue already had a triage/* label).

**Comment by tanujkhattar** [comment]
@mpharrigan As discussed offline, can you write a brief comment / code piece describing how the simulator using the protocol to act on a numpy array and falling back to the unitary application would look like? And potential advantages and challenges in using the protocol to act on 2D numpy arrays for sampling multiple classical input states in a vectorized fashion? 


@dstrain115 How's the progress on this with the student? Are there any roadblocks in the initial exploration?

**Comment by navaro1** [comment]
Hello, I'd like to take a stab at this issue. I was not involved before. Will read through current implementation and comment history and then provide a comment with my understanding and strategy for the implementation.

**Comment by tanujkhattar** [comment]
@navaro1 Thanks! I've assigned the issue to you. Looking forward to your follow up summary comment.

**Comment by navaro1** [comment]
Here are some key points from the discussion and potential strategy:

1. A basic implementation already exists in the [test case for custom_simulator](https://github.com/quantumlib/Cirq/blob/master/cirq-core/cirq/contrib/custom_simulators/custom_state_simulator_test.py), and it's recommended to start from there.
2. Implement `_act_on_fallback_` similar to the code in @cduck [`classical_simulator`](https://github.com/cduck/cirqtools/blob/master/cirqtools/classical_simulator.py#L118-L149)
3. A new protocol like `apply_to_bitstring(bitstring) -> bitstring` could be created, which then could be leveraged to improve the implementation.

Questions (cc: @tanujkhattar):
1. Should the simulator code be put in `cirq-core/cirq/sim` or in the other directory?

**Comment by navaro1** [comment]
I can see that there is PR for classical simulator already - https://github.com/quantumlib/Cirq/pull/6124. I think it would make sense to reassign this issue to author of that PR for now.

**Comment by dstrain115** [comment]
This has been completed.
