### ISSUE TITLE
Packaged sampling for integration with dataframe encodings for supervised learning (Automunge)

### ISSUE THREAD

**Issue by gatorwatt** [quantumlib/Cirq#5827]
**Is your feature request related to a use case or problem? Please describe.**

Hello, I have drafted a RFC and wanted to invite any feedback or suggestions for sponsorship. Welcome any opportunity to discuss prior to formalizing. I am looking for a sponsor.

The draft RFC is provided here: [tinyurl.com/4v54kmf6](https://tinyurl.com/4v54kmf6)

**Describe the solution you'd like**

I have developed a library for dataframe encodings for supervised learning ("Automunge"), and a means to integrate quantum sampling into the supervised learning workflow which I refer to as "non-deterministic inference". I am looking for means to integrate a packaged solution for sampling from Google Cloud hardware, which is discussed further in the draft RFC.

**[optional] Describe alternatives/workarounds you've considered**

Currently the Automunge library workflow supports sampling from any hardware by way of channeling externally sampled entropy seeding as an array of integers, I expect it could benefit simplicity of user workflow to package sampling operations through a Numpy.Generator formatted wrapper.

**[optional] Additional context (e.g. screenshots)**

Please see the draft RFC draft for further detail.

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P1 - I need this no later than the next release (end of quarter)

I am operating on the premise that this functionality could become of benefit to matters related to applications in pandemic response. I am lacking sufficient validations to state this authoritatively. An urgent matter that could be of benefit would be more extensive validations than what was performed in my paper [Stochastic Perturbations of Tabular Features for Non-Deterministic Inference with Automunge](https://arxiv.org/abs/2202.09248).

**Comment by gatorwatt** [comment]
Looking for a sponsor

**Comment by dstrain115** [comment]
Preliminary decision from cirq cync is that this is an application of quantum computing and probably does not belong in the framework, but rather in a separate library.  We are more than happy to help assist in any integration problems and possibly to link in the ecosystem page once it is complete.

**Comment by gatorwatt** [comment]
Dear TensorFlow Quantum Team. In the time since attempting to reach out to you and your colleagues at Deepmind on this matter I have appeared to lose any access to reach in online interactions. I am concerned that there may be some form of regulatory matters in play that I am not aware of but am not sure in what manner as none have been communicated to me. Similarly, I have been unable to locate any academic or public official in the Florida ecosystem that has been willing to have a conversation with me about my work or my research, despite getting papers related to the Automunge library accepted to workshops at several high profile AI research conferences like NeurIPS, ICLR, and ICML. I am partly concerned that my attempts to reach out to a small number of public officials to identify channels for peer review or input could have been misinterpreted as having some agenda other than attempting to contribute to scientific research for purposes of advancing national interests. I could really use some form of mentor or channel for collaboration, which was among the reasons that I attempted to become a volunteer resource for your TensorFlow Quantum library around two years ago for a short period. Would it be possible to establish some form of dialogue outside of the formal weekly meetings that I previously attended?
- Nicholas Teague

**Comment by dstrain115** [comment]
Hi, Nicholas.  Thanks for reaching out.  I am sorry to hear about your difficulties in getting a response.  This proposal is over a year old, but this is what I recall from our discussion at the cirq sync:

1) This is the cirq repository, not the Tensorflow Quantum repository.  As such, it is primarily concerned with construction of quantum circuits and their simulation rather than machine learning or data processing algorithms.
2) cirq is primarily a framework to create quantum circuits and does not (aside from a handful of pedagogical examples) include applications of quantum computing or full-fledged experiments.
3) For these applications (including quantum machine learning techniques), we recommend that users create their own library that uses cirq as a dependency, rather than directly build it into cirq.

If you would like to discuss further on how to use cirq as a dependency, you can join our bi-weekly developer meetings.  Instructions on how to join are found at https://quantumai.google/cirq.

**Comment by gatorwatt** [comment]
I was trying to invite a partnership to establish new business. I lack significant resources and could benefit from some show of support however that could manifest. The document access you requested is now granted, as a clarification there has since been an update to licensing and patent status.
________________________________

**Comment by dstrain115** [comment]
After reviewing the RFC, I think the assessment stands.  Random sampling (or even verified random sampling) would qualify as an application of quantum computing and quantum circuits, and would not be suitable to add directly to the cirq library.  Implementing a cirq.sampler as a numpy.Generator random number generator would also have limited use outside of this specific application.

Of course, you are more than welcome to develop these applications in your own repository and use cirq (it's open source after all) and we would definitely encourage it!

**Comment by gatorwatt** [comment]
Looking for a sponsor
