### ISSUE TITLE
Speed up Circuit construction

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#5833]
We should see if we can get the circuit construction time down, perhaps by invoking a builder pattern.

Here is an example of the speed of circuit construction (variance will be quite high, just doing a single time), but this is good for order of magnitudes
```
import cirq
import time
import matplotlib.pyplot as plt

def build_circuit(n, d):
    qubits = cirq.GridQubit.rect(n, 1)
    c = cirq.Circuit()
    for _ in range(d):
        for q in qubits:
            c.append(cirq.X(q))
    return c


xs = []
ys = []
for n in [1, 10, 100, 1000,]:
    for d in [1, 10, 100, 1000,]:
        start = time.time()
        build_circuit(n, d)
        delta = time.time() - start
        xs.append(n * d)
        ys.append(delta)

plt.xlabel("Number of qubits times depth")
plt.ylabel("Time (seconds)")
plt.loglog(xs, ys, 'o')
```
which produces the following
![image](https://user-images.githubusercontent.com/87974/186007869-988a73e9-f6e6-4696-8a00-849c898a65be.png)

**Comment by daxfohl** [comment]
If you create a list of the qubits and then create a circuit from the list, that should give _much_ faster construction times than appending to the circuit one-by-one.

**Comment by verult** [comment]
- https://github.com/quantumlib/Cirq/pull/5845 contains benchmarks to help define goals for performance improvements
- Please help add any improvements you can think of in the meantime!

**Comment by tanujkhattar** [comment]
I believe this can be closed after https://github.com/quantumlib/Cirq/pull/5898
