### ISSUE TITLE
Devcontainer specification

### ISSUE THREAD

**Issue by cgranade** [quantumlib/Cirq#5896]
**Description of the issue**

If possible, it'd be really helpful to provide a [devcontainer](https://code.visualstudio.com/docs/remote/create-dev-container) specification that would allow spinning up a container for Cirq in VS Code or GitHub Codespaces. In this case, that would likely consist of a post-create script that calls `pip install -r requirements.txt; pip install -e .` for each subpackage, I believe?

**Comment by tanujkhattar** [comment]
Is this a VSCode specific concept? I would imagine most vscode users would create the `devcontainer.json` file themselves. Unless this is a general concept that can be used across different IDEs, we should probably not add it as part of the repository.
