### ISSUE TITLE
`PauliString`s and `SingleQubitPauliStringGateOperation`s are iterables on qubits, which can lead to weird inconsistencies.

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#5912]
**Description of the issue**
```python
>>> import cirq
>>> from typing import Iterable
>>> q = cirq.NamedQubit("q")
>>> isinstance(cirq.H(q), Iterable) 
False # Regular cirq.Operation's should not be iterables, so this is expected.
>>> isinstance(cirq.X(q), Iterable) 
True # However, single qubit pauli operations are iterables; which is weird
>>> [*cirq.X(q)]
[cirq.NamedQubit('q')] # Iterating on the gate returns a qubit, which is even more weird. 
```

This happens because single qubit pauli's derive from `cirq.PauliString`, which 
https://github.com/quantumlib/Cirq/blob/994dba13c67ab54b9a654ae21b4c29aa3763d1f6/cirq-core/cirq/ops/pauli_string.py#L1129

and `cirq.PauliString` has a `__getitem__` defined; which makes it an iterable on qubits as well.

```python
>>> q = cirq.LineQubit.range(2)
>>> ps = cirq.X(q[0]) * cirq.Y(q[1])
>>> [*ps]
[cirq.LineQubit(0), cirq.LineQubit(1)] # I would have expected [cirq.X(q[0]), cirq.Y(q[1])] ?
```

This behavior, that certain cirq operations are iterables on qubits can lead to potential inconsistencies; especially when writing protocols (like `cirq.unitary()`) which have multiple fallback strategies to compute the value of an object using, for example it's decomposition (if the object is iterable, then a fallback strategy is to consider the decomposition of the object as the items yielded by iterating on the object). 

Another major consideration while thinking about a potential fix is to figure out if this is a bug or a backwards incompatible change with regards to Cirq versioning policy. 

**Cirq version**
1.0

**Comment by tanujkhattar** [comment]
Is it possible to preserve the `__getitem__` while getting rid of the fact that pauli string is an iterable on qubits -- answer here is probably no. 

```python
>>> ps[q[0]] # much more common <-- can we support this? 
>>> for qubit in ps: # significant more weird and less common <-- and get rid of this? 
```

For example, Can we override the `__iter__` and raise an exception?

**Comment by pavoljuhas** [comment]
The `__iter__` seems to be defined at https://github.com/quantumlib/Cirq/blob/6e64449dccb8cb2613f5f2aa6df9e32955941414/cirq-core/cirq/ops/pauli_string.py#L440-L441

Perhaps `__getitem__` by itself does not make its class iterable.
