### ISSUE TITLE
incorrect type hints in `_BaseLineQid` and `_BaseGridQubit` addition/subtraction operator signatures

### ISSUE THREAD

**Issue by richrines1** [quantumlib/Cirq#5933]
**Description of the issue**

addition/subtraction operations between pairs of (equal-dimension) `LineQid`s or `GridQid`s are supported, but:

* annotations of `_BaseLineQid.__add__` and `_BaseLineQid.__sub__` only include addition/subtraction with integers

* annotations of `_BaseGridQid.__add__` and `_BaseGridQid.__sub__` only include addition/subtraction with two-tuples of integers

**How to reproduce the issue**

the following assertions pass, but get flagged by type checkers:
```
assert cirq.LineQubit(2) + cirq.LineQubit(1) == cirq.LineQubit(3)
assert cirq.LineQubit(2) - cirq.LineQubit(1) == cirq.LineQubit(1)
assert cirq.LineQid(2, 3) + cirq.LineQid(1, 3) == cirq.LineQid(3, 3)
assert cirq.LineQid(2, 3) - cirq.LineQid(1, 3) == cirq.LineQid(1, 3)
assert cirq.GridQubit(2, 2) + cirq.GridQubit(1, 1) == cirq.GridQubit(3, 3)
assert cirq.GridQubit(2, 2) - cirq.GridQubit(1, 1) == cirq.GridQubit(1, 1)
```

**Cirq version**

1.1.0.dev20221017221036

**Comment by sarahsor** [comment]
Hi, I can fix this if it's still needed.

**Comment by tanujkhattar** [comment]
@sarahsor Yes! Please send a PR and keep us updated if you are still working on it. I'll assign the issue to you for now.
