### ISSUE TITLE
inconsistent ordering of tags in `GateFamily._default_description`

### ISSUE THREAD

**Issue by richrines1** [quantumlib/Cirq#5949]
**Description of the issue**
 

the order of tags in `GateFamily._default_description()` is not guaranteed to be consistent, because both `_tags_to_accept` and `_tags_to_ignore` are frozensets which get passed to `list()` in the f-string. Because this description is included in `GateFamily._value_equality_values_()`, this can lead to (what should be) identical GateFamilies being evaluated as not equal.

**How to reproduce the issue**

might require some repetition/modification to reproduce on different platforms, but this usually works me:
```
gate_fam1 = cirq.GateFamily(cirq.X, tags_to_accept=frozenset("abcd"))
gate_fam2 = cirq.GateFamily(cirq.X, tags_to_accept=frozenset("dcba"))

print(gate_fam1.description)
print(gate_fam2.description)
print(gate_fam1 == gate_fam2)
```
which will print the something like
```
Accepts `cirq.Gate` instances `g` s.t. `g == X`
Accepted tags: ['c', 'a', 'd', 'b']
Accepts `cirq.Gate` instances `g` s.t. `g == X`
Accepted tags: ['b', 'a', 'd', 'c']
False
```
where the two descriptions show the accepted tags in different orders and so the gate families aren't equal

**Cirq version**

1.1.0.dev20221025155635

**Comment by chinmayee-vw** [comment]
Hi! Is this fix still needed? Could I please be assigned?
Thanks!

**Comment by vtomole** [comment]
@chinmayee-vw Yes, this is still outstanding.  I've assigned it to you.

**Comment by maffoo** [comment]
Yeah, we should only include the user-provided description in `_value_equality_values_`, which may be `None`, not the generated default description since that can be ordered differently.

**Comment by tanujkhattar** [comment]
@chinmayee-vw Do you still plan on working on this issue?

**Comment by chinmayee-vw** [comment]
@tanujkhattar yes! still working on it.

**Comment by skushnir123** [comment]
@tanujkhattar I can take this issue up.
