### ISSUE TITLE
LaTeX typo in cirq.asymmetric_depolarize

### ISSUE THREAD

**Issue by singular-value** [quantumlib/Cirq#5962]
**Description of the issue**
<img width="607" alt="image" src="https://user-images.githubusercontent.com/3976048/207660635-fc94a32b-c14e-4de9-a804-ff815dfd96f7.png">

**How to reproduce the issue**
In this line of code: https://github.com/quantumlib/Cirq/blob/db863600f9375a926299eee3c3e73acb3b2c76df/cirq-core/cirq/ops/common_channels.py#L40

Fix is `Pi` --> `P_i`

**Comment by viathor** [comment]
Thank you for reporting this!
