### ISSUE TITLE
I'm new to the community, but I had an idea of how to solve the noise problem in Quantum systems

### ISSUE THREAD

**Issue by Uleyra** [quantumlib/Cirq#5963]
I'll start with: I really don't know much about the systems and I apologize if I end up wasting some of your time.
That out of the way, would running redundant systems fight against the potential for noise?

**Comment by vtomole** [comment]
Hey @Uleyra 

This post is more appropriate for the [Quantum Computing StackExchange ](https://quantumcomputing.stackexchange.com) than here. This space is strictly for Cirq related issues.

Thanks.
