### ISSUE TITLE
cirq.measure modifies simulator's result state vector

### ISSUE THREAD

**Issue by rht** [quantumlib/Cirq#5973]
**Description of the issue**

Terminal measurements seem to affect the final state vector, which makes them different from the case when measurements don't exist.

**How to reproduce the issue**

```python
import cirq
qs = cirq.LineQubit.range(2)
c = cirq.Circuit([
    cirq.H(qs[0]),
    cirq.H(qs[1]),
    cirq.measure(qs, key="q"),
 ])

simulator = cirq.Simulator(seed=43)
result = simulator.simulate(c)
print(result.state_vector())
```
Outputs:
```
[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
```
The value depends on the seed I specify to the simulator.
I was expecting it to be
```
[0.49999997+0.j 0.49999997+0.j 0.49999997+0.j 0.49999997+0.j]
```

**Cirq version**
1.0.0

**Comment by rht** [comment]
I might have misremembered things. The `qsimcirq` [documentation](https://quantumai.google/qsim/tutorials/qsimcirq) says this:
> simulate only executes the circuit once.
> Sampling from the resulting state is fast, but if there are intermediate measurements the final state vector depends on the results of those measurements.

But this optimization seems to be specific to `qsimcirq` only. I tested the code above on `qsimcirq` and encountered the same behavior.
And so, the statement is inaccurate, based on my finding. "... if there are intermediate measurements  ..." -- it should be any measurements, not just intermediate measurements.

**Comment by daxfohl** [comment]
The behavior it appears you're looking for is in `simulator.run`, which simulates up to terminal measurements and then samples them the number of times you specify. If there are intermediate measurements it'll do this much more slowly by rerunning the circuit from the position of the first intermediate measurement each time. `simulate` is only for doing a single full simulation, including the terminal measurements and resulting state vector collapse.

**Comment by rht** [comment]
@tanujkhattar it would be great to know why the discussion outcome is wont-fix.
