### ISSUE TITLE
_repr_latex_ and _repr_mimebundle_ methods for Jupyter notebooks

### ISSUE THREAD

**Issue by westurner** [quantumlib/Cirq#5981]
**Is your feature request related to a use case or problem? Please describe.**

Use case: Teach QIS with a demo; Roll 2, 8, 6-sided coin/dice with a Hadamard gate in a Jupyter notebook and how many qubits, minimally.
- an example, many revisions past the original spec: https://colab.research.google.com/drive/1mLIltSEWyr8-L4SwMoOu-5-6PX7_4hu0#scrollTo=O4PPMNxHxqq2

**Describe the solution you'd like**

```python
display(circuit)  # -> circuit._repr_mimebundle_()
``` 

A `._repr_latex_()` method would be helpful, too:

```python
from IPython.display import display, Latex
display(Latex('\langle\text{0|0}\rangle'))

class Circuit:
    def _repr_latex_(self):
        # return latexstr
        return cirq.contrib.circuit_to_latex_using_qcircuit(self)

    def _repr_mimebundle_(self):
        return {'text/latex': self._repr_latex_()}
```

And also Dirac braket notation w/ MathJax and Jupyter would be real nice:

- https://docs.mathjax.org/en/latest/input/tex/extensions/braket.html
- - https://docs.mathjax.org/en/latest/input/tex/extensions/physics.html
- https://stackoverflow.com/questions/21122210/how-do-i-get-mathjax-to-enable-the-mhchem-extension-in-ipython-notebook
  - `$$\requre{braket}$$` in the first line of a markdown cell in colab doesn't seem to be working:
  -  `$\require{enclose} \enclose{circle}{x}$` works in colab
  - `$\require{braket} \braket{1|0}$` does not seem to work in colab
  - `$\require{physics} \braket{1|0}$` does not seem to work in colab
  - ```latex
    %%latex
    \braket{1|0}
    ```
    does work *in a code cell* in colab
  - ```python
    from IPython.display import Latex
    Latex(r"""\braket{1|0}""")
    ```
    does work *in a code cell* in colab
- https://github.com/jupyterlab/jupyter-renderers
- https://github.com/ipython/ipython/blob/main/IPython/core/display.py
- https://github.com/ipython/ipython/blob/main/IPython/core/display_functions.py#L207-L240
- https://gist.github.com/sametz/6db971a36d7bc3acdd169ade80c5a7ee

**[optional] Describe alternatives/workarounds you've considered**

**[optional] Additional context (e.g. screenshots)**

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle

**Comment by westurner** [comment]
- https://github.com/quantumlib/Cirq/issues/1492 would affect the `_repr_latex_` method.

**Comment by westurner** [comment]
People may or may not prefer the `__repr__()` `text/plain` representation in notebooks, tho?

**Comment by westurner** [comment]
Someday

**Comment by westurner** [comment]
> People may or may not prefer the `__repr__()` `text/plain` representation in notebooks, tho?

When you `IPython.display.display(cirq_expr)`, what should be displayed?

**Comment by westurner** [comment]
> When you `IPython.display.display(cirq_expr)`, what should be displayed?

**Comment by mhucka** [comment]
This issue was tagged as a duplicate back at https://github.com/quantumlib/Cirq/issues/5981#event-8258738408 but apparently never closed; consequently, this has gone through multiple rounds of being closed as stale by the stale issue bot only to be reopened for one reason or another. In fact, I reopened it just now because I missed that it had already been tagged duplicated.

My best guess about why is was considered to be a duplicate is that issue #5895 seems like it would subsume this one. Consequently, I'm closing this, and will reference this issue in #5895. Since 5895 is on the roadmap for 2025, we'll end up examining this issue as part of that work.

If this is wrong, we should reopen this issue.
