### ISSUE TITLE
cirq.M and cirq.R as aliases for measure and reset

### ISSUE THREAD

**Issue by zchen088** [quantumlib/Cirq#5992]
**Is your design idea/issue related to a use case or problem? Please describe.**
I was watching someone construct a cirq Circuit, and they tried to type `cirq.M` and `cirq.R` for measure and reset, which didn't work. However, this seems like it might be a reasonable thing to support, since M and R are often in used in Circuit diagrams in similar manner as H and X?

**Describe your design idea/issue**
Make cirq.M and cirq.R aliases for `cirq.measure` and `cirq.reset`.

**Comment by kjsatz** [comment]
I feel seen

**Comment by dabacon** [comment]
I see you @kjsatz
