### ISSUE TITLE
dimension ignored when comparing or serializing `XPowGate` and `ZPowGate`

### ISSUE THREAD

**Issue by richrines1** [quantumlib/Cirq#5995]
**Description of the issue**

the dimension of `XPowGate` and `ZPowGate` isn't included in `_value_equality_values_` or `_json_dict_` magic methods, leading to some unexpected behavior when the dimension is greater than 2 (see below)

**How to reproduce the issue**

```python
assert not cirq.approx_eq(cirq.X, cirq.XPowGate(dimension=3))  # ok
assert not cirq.equal_up_to_global_phase(cirq.X, cirq.XPowGate(dimension=3))  # ok
assert cirq.X != cirq.XPowGate(dimension=3)  # fails

print(cirq.XPowGate(dimension=3)._dimension)  # prints "3"
print(cirq.read_json(json_text=cirq.to_json(cirq.XPowGate(dimension=3)))._dimension)  # prints "2"

cirq.testing.assert_json_roundtrip_works(cirq.XPowGate(dimension=3))  # passes, but shouldn't
```

**Cirq version**

1.2.0.dev20230105212249

**Comment by tanujkhattar** [comment]
@joesho112358  Can you please leave a comment on this issue so I can assign it to you?

**Comment by joesho112358** [comment]
Hi! I'll give it a try

**Comment by mustapha-saad-codeStar** [comment]
Hi, would love to try

**Comment by tanujkhattar** [comment]
#6005 Should have fixed this.
