### ISSUE TITLE
Tests assume sysconfig scheme to invoke pip

### ISSUE THREAD

**Issue by markedmiston** [quantumlib/Cirq#6025]
**Description of the issue**
Test code which create new virtual environments assumes the location of pip is `/bin/pip` in relation to the base directory. This is an assumption by relying on one installation scheme. Python currently supports nine schemes, https://docs.python.org/3/library/sysconfig.html#installation-paths. For example, on a system with `posix_prefix` the scripts path would be `/usr/local/bin`.

**How to reproduce the issue**
Run the pytests on a system with a different sysconfig scheme than `posix_local`.  This may be easier to reproduce with Python 3.10.

Related:
https://github.com/pypa/virtualenv/pull/2415
https://lists.debian.org/debian-python/2022/03/msg00039.html

<details>

```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/cirq-pytest/test_isolated/bin/pip'

/usr/lib/python3.10/subprocess.py:1847: FileNotFoundError
------------------------------------------------------------------ Captured stdout call -------------------------------------------------------------------
Pytest worker [gw4] is creating /tmp/cirq-pytest/test_isolated for 'test_isolated'.
Removing /tmp/cirq-pytest/test_isolated, due to error: [Errno 2] No such file or directory: '/tmp/cirq-pytest/test_isolated/bin/pip'

```
```

================================================================= short test summary info =================================================================
FAILED dev_tools/cloned_env_test.py::test_isolated_env_cloning[b] - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/cirq-pytest/test_isolated/bin/pip'
FAILED dev_tools/cloned_env_test.py::test_isolated_env_cloning[a] - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/cirq-pytest/test_isolated/bin/pip'
FAILED dev_tools/cloned_env_test.py::test_isolated_env_cloning[c] - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/cirq-pytest/test_isolated/bin/pip'
=================================== 3 failed, 15989 passed, 106 skipped, 93 xfailed, 655 warnings in 119.59s (0:01:59) ====================================

```

</details>

**Cirq version**
1.1.0

**Comment by verult** [comment]
From Cirq sync:

- Context: This issue was found in the Cirq getting started guides.
- @markedmiston Could you add more steps for reproduction (for example, what was the operating system where you saw the error)?

**Comment by markedmiston** [comment]
I am using gLinux. I had a working Cirq using `pyenv local 3.11.2` and was able to reproduce by running the virtual environment steps from the development doc. It used Python `3.10.9`.

```
mkvirtualenv cirq-py3 --python=/usr/bin/python3
workon cirq-py3
python -m pip install --upgrade pip    
python -m pip install -r dev_tools/requirements/dev.env.txt

./check/pytest .
```

**Comment by dstrain115** [comment]
@pavoljuhas will investigate and report back.

**Comment by pavoljuhas** [comment]
@markedmiston - I have followed the steps in your [comment](https://github.com/quantumlib/Cirq/issues/6025#issuecomment-1523327047) and saw all the tests passing with the exception of
```
FAILED dev_tools/docker_test.py::test_docker_stable - AssertionError: assert 1 == 0
FAILED dev_tools/docker_test.py::test_docker_pre - AssertionError: assert 1 == 0
```
These failures were expected because I did not configure docker on my workstation.
After installing docker and fixing access permissions per https://stackoverflow.com/a/54504083 these tests passed as well.

Is there anything else that you saw going wrong?

**Comment by markedmiston** [comment]
I did not test with Docker and did not see any other errors. I presume if you drop into a Python shell on your container and checked the sysconfig scheme it would be the same as your host's Python. With a venv I believe the default is `posix_venv` which is the same as `posix_prefix`.
