### ISSUE TITLE
CI - run weekly isolated_notebook_test for all notebooks

### ISSUE THREAD

**Issue by pavoljuhas** [quantumlib/Cirq#6037]
[isolated_notebook_test.py](https://github.com/quantumlib/Cirq/blob/8b97aa5d8f90d48e41dabaddf3c2b56ec1d2bddd/dev_tools/notebooks/isolated_notebook_test.py#L156-L161) currently checks only the changed notebooks or all notebooks if the `isolated_notebook_test.py` itself changed.  This may leave the notebooks untested for a long time and miss failures when notebook dependencies or the cirq functions they use change.

I suggest to setup a weekly CI test that would execute isolated_notebook_test.py for all enabled notebooks.
These tests are very slow and should not run as within regular CI checks.

**Cirq version**

1.2.0.dev

**Comment by xXnathankerrXx** [comment]
I'm happy to take a crack at this, although I'm new(ish) to pytest and github actions. Let me know if my approach is off.

General Plan:

1.  Add a test similar to [test_notebooks_against_released_cirq](https://github.com/quantumlib/Cirq/blob/8b97aa5d8f90d48e41dabaddf3c2b56ec1d2bddd/dev_tools/notebooks/isolated_notebook_test.py#L161), parameterized with all notebooks and a custom "weekly" pytest mark. 
2. Update [conftest.py](https://github.com/quantumlib/Cirq/blob/8b97aa5d8f90d48e41dabaddf3c2b56ec1d2bddd/conftest.py) to skip tests marked with "weekly" unless explicitly called.
3. Add an Action to the [CI Config](https://github.com/quantumlib/Cirq/blob/8b97aa5d8f90d48e41dabaddf3c2b56ec1d2bddd/.github/workflows/ci.yml) to run all weekly tests at the start of each week.
