### ISSUE TITLE
Update requirements: support networkx 3.0

### ISSUE THREAD

**Issue by cqc-melf** [quantumlib/Cirq#6047]
**Description of the issue**
You are currently using the old `networkx~=2.4` version in the `cirq-core` python package. Would it be possible for you to upgrade to `networkx~=3.0`?

See [file `cirq-core/requirements.txt`](https://github.com/quantumlib/Cirq/blob/master/cirq-core/requirements.txt#L8) 

**Cirq version**
1.1.0

**Comment by mpharrigan** [comment]
Does anyone know why this restriction is in place? git blame is not helpful. @cqc-melf did you try manually installing networkx and seeing if any of the tests break?

**Comment by vtomole** [comment]
> Does anyone know why this restriction is in place? 

[Looks like we have a conflict with pyquil](https://github.com/quantumlib/Cirq/actions/runs/5051876074/jobs/9064165533?pr=6105)

```
  pyquil 3.5.1 depends on networkx<3.0 and >=2.5
```

**Comment by mpharrigan** [comment]
surely this shouldn't affect `cirq-core`

**Comment by vtomole** [comment]
It should not. I would guess we only pinned it to pass our CI/CDs. Will test locally.

**Comment by vtomole** [comment]
Just confirmed that `cirq-core` tests pass with `networkx==3.1`

**Comment by cqc-melf** [comment]
> > Does anyone know why this restriction is in place?
> 
> [Looks like we have a conflict with pyquil](https://github.com/quantumlib/Cirq/actions/runs/5051876074/jobs/9064165533?pr=6105)
> 
> ```
>   pyquil 3.5.1 depends on networkx<3.0 and >=2.5
> ```

Not sure if you have seen this, I have already reported a similar problem to pyquil

https://github.com/rigetti/pyquil/issues/1553

**Comment by mpharrigan** [comment]
What does "deploy" mean here?

I'd imagine we'd want to ship `networkx>=2.4` since I think you're saying our code base works with both networkx 2 and 3

**Comment by vtomole** [comment]
Our code base works with both networkx 2 and 3 but our checks don't work with `networkx==3`. This means that we won't be able to merge the update to the `master` branch.

**Comment by mpharrigan** [comment]
We don't have a CI check that tests `cirq-core` in isolation? In any event I think it's kindof pathological to kneecap our library because we don't have our testing infrastructure set up properly.

**Comment by vtomole** [comment]
Looks like loosening the requirements  to `>=2` instead of `>=3` fixes this issue: https://github.com/quantumlib/Cirq/pull/6105

**Comment by vtomole** [comment]
> We don't have a CI check that tests cirq-core in isolation? In any event I think it's kindof pathological to kneecap our library because we don't have our testing infrastructure set up properly.

The actual problem is that the pinned networkx version in  `cirq-core` is too strict. My bad.

**Comment by vtomole** [comment]
@cqc-melf Please let us know if [this version of cirq-core](https://pypi.org/project/cirq-core/1.2.0.dev20230524233104/) fixes your issue.
