### ISSUE TITLE
Generalize the result of Circuit.insert to allow ragged frontiers

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#605]
This is one of the reasons it's so hard to write good optimizers that have compact outputs.

**Comment by dabacon** [comment]
You're thinking about being able to insert across different moments?  Instead of insert at a particular index you could insert at different index for different qubits?

This feels like it might complicate the insert method by a lot, so if it is done it might be via a different method?

**Comment by dabacon** [comment]
Oh I think we have this.
```
def insert_at_frontier(self,
                           operations: 'cirq.OP_TREE',
                           start: int,
                           frontier: Dict['cirq.Qid', int] = None
                          ) -> Dict['cirq.Qid', int]:
```

**Comment by dabacon** [comment]
Oh I see this is to make insert return something that is useful for insert at frontier.

**Comment by dabacon** [comment]
OK but it looks like you can achieve this by using `insert_at_frontier` with no frontier specified.  So I think we just need to encourage that use for optimizers that run into this.  

Closing one more time as I don't think this is feasible with current insert's return type of `int`.  Overloading that feels like it would create a lot of overhead for callers.
