### ISSUE TITLE
Setup codecov coverage reports on GitHub

### ISSUE THREAD

**Issue by pavoljuhas** [quantumlib/Cirq#6063]
**Description of the issue**

Our GitHub project can benefit from integration with https://codecov.io to provide test coverage reports for the master branch and pull requests.  The CI already checks for [test coverage](https://github.com/quantumlib/Cirq/blob/1445f12e1efcc7afec99586e27945f4585135e38/.github/workflows/ci.yml#L239-L240) of the lines modified in the PR and blocks when changed lines are not tested.  codecov reports would in addition give us a color markup for covered/uncovered lines in PR diffs and also for all files on the master branch.

**Comment by jackreeceejini** [comment]
I would like to work on this

**Comment by pavoljuhas** [comment]
Thank you for taking this on!

**Comment by jackreeceejini** [comment]
The Codecov app might have to be installed and configured by an Admin in the Github organization https://codecov.freshdesk.com/support/solutions/articles/43000593941-set-up-github-app-integration to add a repository token as repository secret as per this: CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

**Comment by verult** [comment]
Is there a way to configure codecov to recognize `coverage: ignore`? Not a big issue though since we still have another coverage check today.
