### ISSUE TITLE
TODO tasks to follow the next release 1.1.1

### ISSUE THREAD

**Issue by pavoljuhas** [quantumlib/Cirq#6088]
The [notebooks-stable](https://github.com/quantumlib/Cirq/blob/37907b9f676dd95acaaf664148a400ff3f1d5219/.github/workflows/ci.yml#L290-L291) CI test checks notebooks against the last official release of Cirq.  If some notebooks require cirq update to pass their test, we need to skip them to unblock CI tests and then re-enable after the next Cirq release is out.

This issues is to track such notebooks and any other tasks that should be done after the next regular release.

## TODO list

- [ ] enable test of [Contract-a-Grid-Circuit.ipynb](https://github.com/quantumlib/Cirq/blob/master/cirq-core/cirq/contrib/quimb/Contract-a-Grid-Circuit.ipynb)
     The notebook requires cirq adjustment for quimb-1.5.0

**Comment by tanujkhattar** [comment]
Related: https://github.com/quantumlib/Cirq/pull/5972

**Comment by dstrain115** [comment]
@pavoljuhas This issue is several releases stale.  Is it still active?

**Comment by pavoljuhas** [comment]
Besides the fix in #6461 we should in general follow [Notebooks Lifecycle instructions](https://github.com/quantumlib/Cirq/blob/main/docs/dev/notebooks.md#lifecycle) before creating a stable release.

The [NOTEBOOKS_DEPENDING_ON_UNRELEASED_FEATURES](https://github.com/quantumlib/Cirq/blob/c3de7064224b8c2aec91646e83184b03b35b2010/dev_tools/notebooks/isolated_notebook_test.py#L44-L61) was not updated for a while so let us make sure we do so next time.
