### ISSUE TITLE
Support generators in Circuit.Zip

### ISSUE THREAD

**Issue by andbe91** [quantumlib/Cirq#6106]
**Is your feature request related to a use case or problem? Please describe.**
Currently you have to create an intermediate list just to pass it to `Circuit.zip`.
```python
cirq.Circuit.zip(*[make_circuit_for_single_qubit(q) for q in qubits])
```

**Describe the solution you'd like**
```python
cirq.Circuit.zip(make_circuit_for_single_qubit(q) for q in qubits)
```
This would make it analogous to how the built-in `zip` works

**[optional] Describe alternatives/workarounds you've considered**

**[optional] Additional context (e.g. screenshots)**

**What is the urgency from your perspective for this issue? Is it blocking important work?**
P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle

**Comment by andbe91** [comment]
Oh, that's interesting. I guess I got confused by the internal `sweeps.Zip` which does what I first described.

**Comment by tanujkhattar** [comment]
Closing the issue since this looks like a confusion.
