### ISSUE TITLE
Remove reference to deprecated `cirq_google.Foxtail` from docs

### ISSUE THREAD

**Issue by ryanhill1** [quantumlib/Cirq#6111]
**Description of the issue**

It seems as though `cirq_google.Foxtail` was deprecated with the `XmonDevices` https://github.com/quantumlib/Cirq/pull/5483

but is still referenced once or twice in docs, e.g. https://github.com/quantumlib/Cirq/blob/36d67c15141894ea1a062c5c0a9800f655821fbc/docs/dev/development.md?plain=1#L290

follow-up from QCSE: https://quantumcomputing.stackexchange.com/questions/32782/attributeerror-module-cirq-google-has-no-attribute-foxtail/32785#32785

**Comment by carthick** [comment]
Can this issue assigned to me?

**Comment by smruthijain** [comment]
@carthick Do you plan to work on this issue? If not can I pick this up please?

**Comment by smruthijain** [comment]
#6139

**Comment by smruthijain** [comment]
Thanks @carthick
