### ISSUE TITLE
Create a new sub-package for `cirq-ft`

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#6119]
We want to launch Cirq-FT soon. This task is to create a new empty sub-package for `cirq-ft` that depends on `cirq-core` and is compatible with all the Cirq packaging infrastructure. 

Once the package has been added, we can start moving files from internal private repository to Cirq open source.

**Comment by vtomole** [comment]
> cirq-ft

What is it?

`cirq-fault-tolerance`?
`cirq-fourier-transform`?
`cirq-full-time`?
`cirq-feet`?

**Comment by tanujkhattar** [comment]
Yeah, Cirq for Fault-Tolerant algorithms. We've been working on a prototype internally and we are targeting a launch by June 12th

**Comment by pavoljuhas** [comment]
Remaining TODO items:

- [ ] @tanujkhattar - please check the new [README](https://github.com/quantumlib/Cirq/blob/33934390b0035349724764ec286a541a636d80fb/cirq-ft/README.rst?plain=1#L6)
- [ ] remove temporary file [dropme_blank_test.py](https://github.com/quantumlib/Cirq/blob/33934390b0035349724764ec286a541a636d80fb/cirq-ft/cirq_ft/dropme_blank_test.py#L15) after adding some tests

**Comment by dstrain115** [comment]
Can this be closed now?

**Comment by tanujkhattar** [comment]
Yes, this can be closed
