### ISSUE TITLE
Add daily CI test for a fresh cirq --pre installation

### ISSUE THREAD

**Issue by pavoljuhas** [quantumlib/Cirq#6130]
**Description of the issue**

`pip install cirq --pre` may break with cirq installation if some of cirq dependencies release a dev package with API changes to PyPI.  The `--pre` option seems to affect cirq as well as any of its requirements.  See #6129 for an example breakage.

**Cirq version**

v0.15.0-298-g24abfa1d

**Proposed solution**

Add a daily CI test to perform a fresh `pip install --pre cirq` from PyPI and execute unit tests *on the installed code*.

This requires updates to our pytest configuration; as things are pytest requires the [./conftest.py](https://github.com/quantumlib/Cirq/blob/master/conftest.py) from the Cirq repository root, but this file is not distributed in cirq wheels.

**Comment by jackreeceejini** [comment]
I'm trying to work on this issue, any pointers on how to start?

**Comment by pavoljuhas** [comment]
I'd suggest to add a new CI workflow ci-daily.yml scheduled to run every day, see #6046 for an example.
Then you can use the `Pytest Ubuntu`, `Pytest Windows`, `Pytest MacOs` jobs as starting points,
but modify their [Install requirements](https://github.com/quantumlib/Cirq/blob/6c251a3dcf30cc89208939012fe6fed82d004d67/.github/workflows/ci.yml#L164-L167) parts to do
```
$ pip install --pre cirq
```
instead of installing from the dev.env.txt package list.

I think you will also need to do 
```
pip install \
    -r dev_tools/requirements/deps/format.txt \
    -r dev_tools/requirements/deps/pylint.txt \
    -r dev_tools/requirements/deps/pytest.txt
```
to be able to run check/pytest at line 171
https://github.com/quantumlib/Cirq/blob/6c251a3dcf30cc89208939012fe6fed82d004d67/.github/workflows/ci.yml#L170-L171

The idea is to install the pre-release cirq wheel and its dependencies from PyPI and verify things still work.

**Comment by jackreeceejini** [comment]
Okay. Thanks
