### ISSUE TITLE
Update Python version in Dockerfile-s

### ISSUE THREAD

**Issue by pavoljuhas** [quantumlib/Cirq#6175]
**Description of the issue**

#6167 raises the minimum Python version to 3.9,
but the following Dockerfile-s derive from images with Python 3.7 or 3.8:

- https://github.com/quantumlib/Cirq/blob/74cee7e8e8787ab56160124b3a13834550e31cc1/Dockerfile#L1
- https://github.com/quantumlib/Cirq/blob/74cee7e8e8787ab56160124b3a13834550e31cc1/dev_tools/docs/Dockerfile#L29
- https://github.com/quantumlib/Cirq/blob/74cee7e8e8787ab56160124b3a13834550e31cc1/dev_tools/pr_monitor/Dockerfile#L26

**TODO**

Check if all of these Dockerfile-s are in use then update their Python versions to 3.9.

**Comment by pavoljuhas** [comment]
cc: @tanujkhattar

**Comment by NoureldinYosri** [comment]
cirq-sync: accepted to updating the python version for the docker images in use ... we also need to findout which docker images are not being used to drop them

**Comment by pavoljuhas** [comment]
TODO @pavoljuhas - verify if anyone uses or wants to archive [Cirq/dev_tools/docs/Dockerfile](https://github.com/quantumlib/Cirq/blob/74cee7e8e8787ab56160124b3a13834550e31cc1/dev_tools/docs/Dockerfile#L29)

**Comment by jackreeceejini** [comment]
@NoureldinYosri Sorry did not see that you had accepted this because I had already updated the Python version to 3.9 but I don't know how to find out if they are in use or not though

**Comment by pavoljuhas** [comment]
> ...  I don't know how to find out if they are in use or not though

@jackreeceejini - thank you for taking this on.  I have asked on our internal cirq chat with no response so I submitted  #6184 to delete it.  Please hold on with changing Cirq/dev_tools/docs/Dockerfile until that PR is resolved.

**Comment by pavoljuhas** [comment]
The Cirq/dev_tools/docs/Dockerfile was deleted in #6184.
We need to update only the remaining two files.
