### ISSUE TITLE
Implement consistancy checks for unitary protocol in the presence of ancillas

### ISSUE THREAD

**Issue by NoureldinYosri** [quantumlib/Cirq#6182]
**Is your feature request related to a use case or problem? Please describe.**
#6101 was created to update `cirq.unitary` and `cirq.apply_unitaries` protocols to support the case when gates allocate their own ancillas. This was achieved in #6112, however the fix assumes the decomposition is correct. a consistency check is need to check that. This is the fourth task on https://github.com/quantumlib/Cirq/issues/6101#issuecomment-1568686661. 

The consistency check should check that the result is
      1. Indeed a unitary
      2. CleanQubits are restored to the $\ket{0}$ state.
      3. Borrowable Qubits are restored to their original state.

**Describe the solution you'd like**
for the correctness checks we need a `cirq.testing.assert_consistent_unitary` that does the checks listed above.

**What is the urgency from your perspective for this issue? Is it blocking important work?**
for the first task
P1 - I need this no later than the next release (end of quarter)

for the second and third tasks
P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle

**Comment by shef4** [comment]
@NoureldinYosri Thanks for breaking this down. I got my dev environment working and can start testing and adding code. 

I know you said you'd work on task 1 in #6112, but I'd be happy to work on it if you've got other task to get to. It's seems like a good first issue and time sensitive for unblocking?

**Comment by NoureldinYosri** [comment]
@shef4 the first task is the more tracktable of them. feel free tow work on it. the method should live in `cirq-core/cirq/testing` under `consistent_unitary.py`. you should create `consistent_unitary.py` since it doesn't  exists and `consistent_unitary_test.py` for its tests. 

the other tasks are not suitable as first issues. even the first is a bit too much so feel free to drop it if you feel that, but let me know if you do drop it.

**Comment by shef4** [comment]
Hey @NoureldinYosri  I was wondering if I could get some feedback on my `conssitent_unitary` function. 

`from cirq.linalg.predicates import is_unitary
from typing import Any

def assert_unitary_is_consistent(val: Any):
    """Asserts that a value is unitary, clean qubits are set to |0> state, and borrowable qubits are restored to their original state."""
    
    # assert that value is unitary 
    assert is_unitary(val)

    # assert clean qubits are set to |0> state
    clean_state = cirq.PauliString(qubit=cirq.LineQubit(0))
    #TODO: collect list of clean qubits
    clean_qubits = [None]
    for qubit in clean_qubits:
        assert qubit == clean_state

    # assert borrowable qubits are restored to original state
    #TODO: collect list of orignial state of borrowable qubits
    original_states = [None]
    #TODO: collect list of borrowable qubits
    borrowable_qubits = [None]
    for i, qubit in enumerate(borrowable_qubits):
        assert qubit == original_states[i]`
       
I placed TODOs at the parts I'm really not sure how to approach yet. if you have any suggestions I'd really appreciate it.

**Comment by NoureldinYosri** [comment]
@shef4 I started explaining how it should work but then found that it would be easier if I implement it. If you check #6196 you will find that the implementation mimics how #6112 updated `cirq.unitary`

**Comment by NoureldinYosri** [comment]
completed in #6196
