### ISSUE TITLE
Notebook tests failing on master 

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#6213]
**Description of the issue**
Notebook tests are failing on master with `ImportError: Numba needs NumPy 1.24 or less`.

This is probably caused by the recent Python 3.11 upgrade? 

**How to reproduce the issue**
See https://github.com/quantumlib/Cirq/actions/runs/5617237054/job/15221015891?pr=6095 for example

**Cirq version**
```
1.3.0.dev
```

**Comment by pavoljuhas** [comment]
I have tracked this down to interference between tested notebooks, they all shared a temporary directory for packages pip-installed from notebooks.  #6218 isolates tests by using a new pip-target directory for each test.
