### ISSUE TITLE
Cirq-FT: Isolated pytest fails at head for cirq-ft notebooks

### ISSUE THREAD

**Issue by NoureldinYosri** [quantumlib/Cirq#6227]
The notebook tests fail with `jupyter_client.kernelspec.NoSuchKernel: No such kernel named python3 `

Examples: 
- https://github.com/quantumlib/Cirq/actions/runs/5727847580/job/15523237094
- https://github.com/quantumlib/Cirq/actions/runs/5729717532/job/15527032587?pr=6224

**Comment by tanujkhattar** [comment]
Since the failure arises from the `execute_notebook` method, https://github.com/quantumlib/Cirq/pull/6158/files should help fix this issue. 

But I'm not sure why this is failing right now

**Comment by mpharrigan** [comment]
I ran into this bumping dependencies in qualtran

https://github.com/quantumlib/Qualtran/pull/340/commits/cee761edde78e018e6a6630c3ef14c1bc4152765

**Comment by verult** [comment]
From cirq cynque: need to add an explicit dependency to ipykernel
