### ISSUE TITLE
Replacing terminal measurements with identity gates causes the final state vector to have wrong normalization

### ISSUE THREAD

**Issue by rht** [quantumlib/Cirq#6228]
**Description of the issue**

While testing QED-C's [Shor benchmark code](https://github.com/SRI-International/QC-App-Oriented-Benchmarks/tree/master/shors/cirq), I happen to replace the measurements with identity gates. The circuit I use is attached in this issue: [shor_15_11.json.gz](https://github.com/quantumlib/Cirq/files/12240298/shor_15_11.json.gz).

**How to reproduce the issue**

```python
import cirq
import numpy as np
import qsimcirq

# Both has normalization problems
# simulator = qsimcirq.QSimSimulator()
simulator = cirq.Simulator()

# Factoring 15
# This is QED-C's ShorsAlgorithm(15, 11, 1, verbose=True)
circuit = cirq.read_json("./shor_15_11.json")

def replace_measurements_with_identities_inplace(circuit):
    # This is identical to how qsimcirq does it in
    # QSimSimulator._sample_measure_results.
    for i in range(len(circuit.moments)):
        circuit.moments[i] = cirq.Moment(
            (
                op
                if not isinstance(op.gate, cirq.MeasurementGate)
                else [cirq.IdentityGate(1).on(q) for q in op.qubits]
            )
            for op in circuit.moments[i]
        )

replace_measurements_with_identities_inplace(circuit)
result = simulator.simulate(circuit)
sv = result.final_state_vector
print("norm", np.sum(np.abs(sv) ** 2))
```

Would result in a norm of 0.99993384

**Cirq version**

```
1.2.0
```

**Comment by tanujkhattar** [comment]
Is this a precision issue? Did you try using `simulator = cirq.Simulator(dtype=np.complex128)` instead?

**Comment by rht** [comment]
Yeah, with `simulator = cirq.Simulator(dtype=np.complex128)`, I got `norm 0.9999999999998377` (though qsim, the one I mainly use, doesn't have a complex128 simulator). I was worried that since float32's precision is 6 digits, and according to https://stackoverflow.com/questions/39134956/accuracy-of-float32, for 1e-1 to 1e0, the max relative error should be 1e-8. But given that the circuit has sufficiently large number of gates, an error of 1e-5 is expected, I suppose.

I think for this issue, I can sleep well with just renormalizing the probabilities. Sorry for the false positive.

**Comment by rht** [comment]
> But given that the circuit has sufficiently large number of gates, an error of 1e-5 is expected, I suppose.

Though I can't explain why the bulk of the gates don't accumulate to an error of 1e-5 (with the norm of 0.9999989), yet the identities at the end cause it to go >1e-5.
