### ISSUE TITLE
Deprecate and remove `processor_ids` argument by v1.4

### ISSUE THREAD

**Issue by jurruti** [quantumlib/Cirq#6271]
The run methods in `Engine`, `EngineProgram` and `EngineClient` now include a parameter called `processor_id`. This parameter can be used to specify a specific processor for the run, and **will substitute the deprecated parameter `processor_ids`** , because allowing multiple candidate processors was not useful in practice.

**Comment by SudhanshuJoshi09** [comment]
Hey @jurruti , could I pick this up ?

**Comment by verult** [comment]
Hi @SudhanshuJoshi09 , are you still interested in taking this issue?

**Comment by JaShom** [comment]
Could I take on this issue please @verult ?

**Comment by pavoljuhas** [comment]
> Could I take on this issue please @verult ?

Sure @JaShom, thank you for looking into this.
