### ISSUE TITLE
Documentation of FSimGate has incorrect phase convention

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#6297]
**Description of the issue**
https://quantumai.google/reference/python/cirq/FSimGate

![image](https://github.com/quantumlib/Cirq/assets/4296166/07476b9f-cc8a-4796-84fc-436ac1674113)

The definition of c should have a negative sign in the exponent.

```python
import cirq
import numpy as np

np.round(cirq.unitary(cirq.FSimGate(theta=0, phi=np.pi / 2)))

```

```
array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.-0.j, 0.+0.j],
       [0.+0.j, 0.-0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.-1.j]])
```

**Comment by maffoo** [comment]
This was fixed recently but the doc site may not have been updated: https://github.com/quantumlib/Cirq/pull/6288

**Comment by pavoljuhas** [comment]
TODO - check if this is updated at the nightly build and then close if so.
