### ISSUE TITLE
Move from mypy to better type checker

### ISSUE THREAD

**Issue by daxfohl** [quantumlib/Cirq#6324]
**Description of the issue**
Newer type checkers, such as pyright, pytype, pyre are faster, able to infer types implicitly, and catch more errors. Pyright in particular is also incremental, so doesn't have to recheck the whole project on each change, and plugs in well to provide autocomplete in vscode and other.

**Comment by tanujkhattar** [comment]
@mpharrigan To investigate the different options in Qualtran and develop an opinion. We can then decide to migrate Cirq if we find an easy to migrate and obviously better option.

**Comment by mpharrigan** [comment]
Note that we do not follow pyright's convention for re-exporting public symbols https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface and indeed that is the source of many of the errors flagged from qualtran

**Comment by pavoljuhas** [comment]
* We use mypy for internal projects with no immediate plans to replace it.

* In my local development environment `check/mypy` takes 30 seconds to check everything,
  and mypy takes a few seconds if run on a specific file.  Other CI checks take significantly more time.

Closing for now, we can revisit should the above points change.
