### ISSUE TITLE
Remove build_doc CI job and dependencies

### ISSUE THREAD

**Issue by senecameeks** [quantumlib/Cirq#6416]
**Description of the issue**
Sphinx version update caused a [CI error](https://github.com/quantumlib/Cirq/actions/runs/7452039565/job/20274451752?pr=6399#step:5:15) with the `build_docs.sh` job. This job is no longer used since we instead use the quantumai website. Remove this job and it's dependencies (i.e Sphinx) 

**Cirq version**
1.4.0.dev20231221183905

**Comment by senecameeks** [comment]
https://cirq.readthedocs.io/ is no longer used and can be removed. It redirects to the quantumai website.

**Comment by pavoljuhas** [comment]
> https://cirq.readthedocs.io/ is no longer used and can be removed. It redirects to the quantumai website.

This should be presumably doable at https://readthedocs.org/dashboard/Cirq/edit.
@dstrain115 or someone else who has admin access to Cirq RTD - can you please take a look?
