### ISSUE TITLE
Cannot serialize cirq_google.experimental.ops.coupler_pulse.CouplerPulse()

### ISSUE THREAD

**Issue by aasfaw** [quantumlib/Cirq#6440]
**Description of the issue**

Serialization isn't supported for `cirq_google.experimental.CouplerPulse()`

**How to reproduce the issue**

Run the following circuit:
```
this_circuit = cirq.Circuit(
              cirq_google.experimental.CouplerPulse(hold_time=hold_time, coupling_mhz = 20)(*qubits),
              cirq.measure(*qubits, key = 'thequbits')
              )
```

<details>
Cannot serialize op cirq_google.experimental.ops.coupler_pulse.CouplerPulse(hold_time=5, coupling_mhz=20, rise_time=cirq.Duration(nanos=8), padding_time=cirq.Duration(picos=2500.0), q0_detune_mhz=0.0, q1_detune_mhz=0.0).on(cirq.GridQubit(4, 5), cirq.GridQubit(5, 5)) of type <class 'cirq_google.experimental.ops.coupler_pulse.CouplerPulse'>
</details>

**Cirq version**
1.3.0

**Comment by eliottrosenberg** [comment]
Hold time is supposed to be a `cirq.Duration`, but I get the same error when I do that.

**Comment by dstrain115** [comment]
Nour, can you take a look at this?
