### ISSUE TITLE
Can't print the `ResultDict` of an array with 2 values

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#6447]
**Description of the issue**
`cirq.ResultDict(records={'c': np.array([[[True], [True]]])})` can be created but it can't be printed .

**How to reproduce the issue**

```python
import cirq
import numpy as np
result = cirq.ResultDict(records={'c': np.array([[[True], [True]]])})
print(result)
```
Will throw
`ValueError: Cannot extract 2D measurements for repeated keys`

**Cirq version**
`1.4.0.dev20240126200039`

**Comment by NoureldinYosri** [comment]
cirq-cync: needs to invistigate whether the input is valid (and add input validation) and if it's find out the bug in printing.
