### ISSUE TITLE
OpenQASM 2.0 is removed in latest version of qiskit

### ISSUE THREAD

**Issue by purva-thakre** [quantumlib/Cirq#6480]
`qiskit 1.0` [has removed](https://docs.quantum.ibm.com/api/migration-guides/qiskit-1.0-features#qiskitconverters) `OpenQASM 2.0`.

As `cirq-core/cirq/contrib/qasm_import` still depends on `OpenQASM 2.0`, using any version of `cirq` with the latest version of `qiskit` leads to quite a few issues. 

https://github.com/quantumlib/Cirq/blob/02d29a975ebfcd8e3e2db5356c310c956ece03ac/cirq-core/cirq/testing/consistent_qasm.py#L65

It would help if the compatible `qiskit` version number is documented somewhere. 

The errors in `from cirq.contrib.qasm_import import circuit_from_qasm` when `qiskit` is bumped up to the latest version are due to `AttributeError: 'list' object has no attribute 'add_qubit'`

https://docs.quantum.ibm.com/api/qiskit/qasm2#alternatives

**Comment by dstrain115** [comment]
Cirq now supports import and export of OpenQasm 3.0 (at least to a limited extent) as of cirq 1.6.  Please file a new issue if you continue to find problems.
