### ISSUE TITLE
cirq homepage (?) returning 404s

### ISSUE THREAD

**Issue by natestemen** [quantumlib/Cirq#6486]
**Description of the issue**

https://quantumai.google/cirq is currently returning a 404.

**How to reproduce the issue**

1. Visit https://quantumai.google/cirq/start/start
2. Click "Cirq" in the top left portion of the screen (see below)
3. Get redirected for https://quantumai.google/cirq/ which returns a 404.

<img width="400" alt="screenshot of cirq docs with location to click circled" src="https://github.com/quantumlib/Cirq/assets/12703123/0c61069d-73ff-4560-8407-52c5deecb0f5">

The wayback machine has a copy of this page from ~1 month ago: https://web.archive.org/web/20240130102308/https://quantumai.google/cirq. If this is intended, and the page is being phased out, what is the new URL we should use to point to Cirq's homepage?

**Comment by smburdick** [comment]
It's working for me now.

**Comment by NoureldinYosri** [comment]
hi, thanks for reporting this. there were somechanges that brought the website down, but it should be backup now. if you still get 404 please checkagain after clearing your browser's cache or using a different browser.

**Comment by natestemen** [comment]
Looks good now. Thanks for the update!

FYI there is an extra indentation of the first line of the code on https://quantumai.google/cirq/.
<img width="500" alt="Screenshot 2024-03-07 at 1 17 28 PM" src="https://github.com/quantumlib/Cirq/assets/12703123/157b034a-2f68-4a2b-8412-f1cf9e2e4140">

Potentially coming from the extra newline here?
https://github.com/quantumlib/Cirq/blob/45138921be805a361ad604c728ba8584fa4113aa/README.rst?plain=1#L44-L46
