### ISSUE TITLE
GitHub roadmap project refers to 2023 in title

### ISSUE THREAD

**Issue by mhucka** [quantumlib/Cirq#6496]
This is a trivial issue, but since I happened upon it, may as well report it: the sole GitHub project in the Projects tab is titled ["Cirq 2023 roadmap"](https://github.com/quantumlib/Cirq/projects?query=is%3Aopen). If this is not deliberate, perhaps it would make sense to change the year to 2024?

<kbd>

![image](https://github.com/quantumlib/Cirq/assets/1450019/07f8418c-84cf-4365-a2c1-dd73e5169820)

</kbd>

**Comment by pavoljuhas** [comment]
TODO @pavoljuhas - close the 2023 roadmap, transfer open tasks to 2024.

**Comment by pavoljuhas** [comment]
> TODO @pavoljuhas - close the 2023 roadmap, transfer open tasks to 2024.

Done.  Cirq 2024 roadmap is thus far private, will be published soon.

**Comment by mhucka** [comment]
Closing as done.
