### ISSUE TITLE
Link for "Educational resources" on quantumai.google/cirq page leads to 404

### ISSUE THREAD

**Issue by mhucka** [quantumlib/Cirq#6497]
(Apologies if this is not the right place to report this; I didn't know where else to do it.)

On the [quantumai.google page for Cirq](https://quantumai.google/cirq), there is a block of Resources in the lower half of the page.

<kbd>

![image](https://github.com/quantumlib/Cirq/assets/1450019/494067eb-85ea-4c3c-b6a5-871924118cba)

</kbd>

The "learn more" link for Educational resources leads to a nonexistent page.

<kbd>

![image](https://github.com/quantumlib/Cirq/assets/1450019/ee4b495d-90bd-43a6-bdc3-d20089ddd42c)

</kbd>

**Comment by pavoljuhas** [comment]
Thanks for reporting this - TODO @pavoljuhas - convert to internal bug report.

**Comment by pavoljuhas** [comment]
This is fixed now.
