### ISSUE TITLE
Incorrect Numeric Expression Syntax in QASM Export

### ISSUE THREAD

**Issue by p51lee** [quantumlib/Cirq#6550]
**Description of the issue**

<img width="892" alt="image" src="https://github.com/quantumlib/Cirq/assets/68288688/049befc0-bf57-464f-b4a5-2e8d010c17c0">

The `to_qasm` method exports numeric expressions in a format not fully compliant with the [OpenQASM 2.0 specification](https://arxiv.org/abs/1707.03429). Expressions like `1e-10` are outputted without a leading digit or dot, which could lead to syntax errors in strict OpenQASM parsers.

**How to reproduce the issue**

```python
import math

cirq_circuit = cirq.Circuit()
a = cirq.NamedQubit("a")
cirq_circuit.append([cirq.Rz(rads=math.pi * 1e-10)(a)])
print(cirq_circuit.to_qasm())
```
**Result**
```qasm
// Generated from Cirq v1.3.0

OPENQASM 2.0;
include "qelib1.inc";


// Qubits: [a]
qreg q[1];


rz(pi*1e-10) q[0];  // invalid syntax (expected: 1.e-10 or 1.0e-10)
```

**Cirq version**
1.3.0

**Comment by verult** [comment]
From the Cirq Cync: we're planning to drop support for OpenQASM 2 and move to OpenQASM 3. Does the same issue apply in the new version?

**Comment by p51lee** [comment]
I'm working with the latest version and `to_qasm` method gives OpenQASM 2 code. Is there a parameter or a different method available that I should use to obtain OpenQASM 3 code instead?

**Comment by dstrain115** [comment]
It looks like this is not a problem with OpenQASM 3.0, since the specification and grammar changed:

```
FloatLiteral:
    // 1_123e-3, 123e+4 or 123E5 (needs the exponent or it's just an integer)
    DecimalIntegerLiteral FloatLiteralExponent
    // .1234_5678 or .1e3 (no digits before the dot)
    | DOT DecimalIntegerLiteral FloatLiteralExponent?
    // 123.456, 123. or 145.32e+1_00
    | DecimalIntegerLiteral DOT DecimalIntegerLiteral? FloatLiteralExponent?;
```

However, I will see if I can fix this anyway, since I am updating openQASM
