### ISSUE TITLE
`cirq` and `pyzx` have incompatible dependencies because of `cirq-rigetti`

### ISSUE THREAD

**Issue by dlyongemallo** [quantumlib/Cirq#6552]
**Description of the issue**

I am working on the [pyzx](https://github.com/Quantomatic/pyzx) library for ZX-calculus, and want to use Cirq with it. However, they cannot both be installed into the same environment due to incompatible dependencies, as `cirq-rigetti` dependson `pyquil`, which depends on an older version of `lark` than `pyzx` does.

I don't think I actually need `cirq-rigetti`. Is there a workaround that I can use to install `cirq` while ignoring the requirements for `pyquil`?

**How to reproduce the issue**

Create a new virtual environment for Python. Try to install the latest versions of `pyzx` and `cirq`.

```
pip install pyzx==0.8.0 cirq==1.3.0
```

`cirq` depends on `cirq-rigetti`, which depends on `pyquil`, and the above fails due to https://github.com/rigetti/pyquil/issues/1764.

<details>
INFO: pip is looking at multiple versions of cirq-rigetti to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install cirq-rigetti and pyzx==0.8.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    pyzx 0.8.0 depends on lark~=1.1.7
    pyquil 3.5.4 depends on lark<0.12.0 and >=0.11.1
    pyzx 0.8.0 depends on lark~=1.1.7
    pyquil 3.5.3 depends on lark<0.12.0 and >=0.11.1
    pyzx 0.8.0 depends on lark~=1.1.7
    pyquil 3.5.2 depends on lark<0.12.0 and >=0.11.1
    pyzx 0.8.0 depends on lark~=1.1.7
    pyquil 3.5.1 depends on lark<0.12.0 and >=0.11.1
    pyzx 0.8.0 depends on lark~=1.1.7
    pyquil 3.5.0 depends on lark<0.12.0 and >=0.11.1
    pyzx 0.8.0 depends on lark~=1.1.7
    pyquil 3.4.1 depends on lark<0.12.0 and >=0.11.1
    pyzx 0.8.0 depends on lark~=1.1.7
    pyquil 3.4.0 depends on lark<0.12.0 and >=0.11.1
    pyzx 0.8.0 depends on lark~=1.1.7
    pyquil 3.3.5 depends on lark<0.12.0 and >=0.11.1
    pyzx 0.8.0 depends on lark~=1.1.7
    pyquil 3.3.4 depends on lark<0.12.0 and >=0.11.1
    pyzx 0.8.0 depends on lark~=1.1.7
    pyquil 3.3.3 depends on lark<0.12.0 and >=0.11.1
    pyzx 0.8.0 depends on lark~=1.1.7
    pyquil 3.3.2 depends on lark<0.12.0 and >=0.11.1
    pyzx 0.8.0 depends on lark~=1.1.7
    pyquil 3.3.1 depends on lark<0.12.0 and >=0.11.1
    pyzx 0.8.0 depends on lark~=1.1.7
    pyquil 3.3.0 depends on lark<0.12.0 and >=0.11.1
    pyzx 0.8.0 depends on lark~=1.1.7
    pyquil 3.2.1 depends on lark<0.12.0 and >=0.11.1
    pyzx 0.8.0 depends on lark~=1.1.7
    pyquil 3.2.0 depends on lark<0.12.0 and >=0.11.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
</details>

**Cirq version**
1.3.0

**Comment by maffoo** [comment]
`cirq` is an umbrella package that installs a number of other packages. You can instead install `cirq-core` to avoid bringing in all the dependencies of `cirq-rigetti` and other associated packages (see the `cirq-*` directories in the repo, which correspond to individual packages). We may need to make some documentation updates to make it clear that installing the full `cirq` package is generally not necessary.

**Comment by dlyongemallo** [comment]
Okay, I'll use `cirq-core` and add other `cirq-*` packages as I need instead of depending on `cirq`. That got rid of the error. Thanks.

(I'll close the issue, but there's still a conflict between `cirq-rigetti` and `pyzx`, if anyone should ever want to use them together.)

**Comment by cosenal** [comment]
There is a [PR in progress](https://github.com/quantumlib/Cirq/pull/6281) to upgrade PyQuil to v4 in `cirq-rigetti`. That should resolve many dependency conflicts and hopefully will be shipped soon 🤞
