### ISSUE TITLE
Typo in docstring for GPI2 gate

### ISSUE THREAD

**Issue by oschwarze** [quantumlib/Cirq#6639]
There seems to be a typo in the docstring for the GPI2 gate:

https://github.com/quantumlib/Cirq/blob/ab967669caddc7da510dddc22c12e6c5747e9d85/cirq-ionq/cirq_ionq/ionq_native_gates.py#L101-L156

according to https://ionq.com/docs/getting-started-with-native-gates, the 10-component int the matrix should be $-i \exp{i \phi}$ and not $-i\exp(-i \phi)$

**Comment by dstrain115** [comment]
Cirq cycn:  Ionq folks, can you comment whether this should be positive or negative signed?

**Comment by pavoljuhas** [comment]
TODO(@pavoljuhas) - contact ionq folks about this

**Comment by pavoljuhas** [comment]
The suggestion looks good given the unitary matrix below - https://github.com/quantumlib/Cirq/blob/f5566b682ffe3fc2e865568e10238e7fb1630d47/cirq-ionq/cirq_ionq/ionq_native_gates.py#L120-L123

@Cynocracy or @splch - can you please confirm?

**Comment by Cynocracy** [comment]
@pavoljuhas can confirm, updating the comment to match the docstring sgtm.

The 2pi factor comes from, aiui, the phase argument being expressed in units of turns, and should be present in the doc string as well, if phi there is intended to be the phase argument

**Comment by pavoljuhas** [comment]
@Cynocracy - thanks for a quick response.  Can you PTAL at #6694?
