### ISSUE TITLE
External link returns 404

### ISSUE THREAD

**Issue by bongiojp** [quantumlib/Cirq#6646]
The "education page" link is broken on https://quantumai.google/cirq/start/start

**Comment by dstrain115** [comment]
@aasfaw Do you know what the proper link for the education page should be now?

**Comment by aasfaw** [comment]
educational resources page: https://quantumai.google/resources
all cirq pages start here: https://quantumai.google/cirq

**Comment by pavoljuhas** [comment]
- [ ] verify education page link works after nightly docs build at https://quantumai.google/cirq/start/start

**Comment by pavoljuhas** [comment]
Confirming working "education page" link after nightly docs build.  Closing as fixed.
