### ISSUE TITLE
update protobuf API calls so it does not have to be pinned to protobuf-4

### ISSUE THREAD

**Issue by pavoljuhas** [quantumlib/Cirq#6651]
**Description of the issue**

https://github.com/protocolbuffers/protobuf/commit/26995798757fbfef5cf6648610848e389db1fecf removed the `including_default_value_fields` argument which is used in cirq-google.
This is temporarily fixed by pinning protobuf-4.x in #6650

TODO: update API calls to use the new argument `always_print_fields_with_no_presence`.

**Cirq version**

1.5.0.dev at 0aae3c122ad457cec884e8bfbe001afde9d17f5b.

**Comment by dstrain115** [comment]
Let's update the relevant calls (or recompile the protos if necessary) to use the new call.  Investigate compatibility with internal systems.

Can either @verult @senecameeks take this?
