### ISSUE TITLE
cphase comparison with CZ failing after dependency update

### ISSUE THREAD

**Issue by NoureldinYosri** [quantumlib/Cirq#6663]
**Description of the issue**
test following test case started failing at HEAD when run with the latest dependency versions

https://github.com/quantumlib/Cirq/blob/32d48331fecd5f075c25e8f05c4551380bcd6c45/cirq-core/cirq/ops/common_gates_test.py#L902-L904

I temporarly added annotated it with xfail until we fix it.

**Comment by dstrain115** [comment]
cirq cync:  Comparison sympy.pi now no longer equals math.pi.
