### ISSUE TITLE
Quantum shannon decomposition fails for QFT with non-unitary matrix error

### ISSUE THREAD

**Issue by doublehoon** [quantumlib/Cirq#6666]
**Description of the issue**

I encountered an issue when attempting to decompose the unitary matrix of QFT(4) using the built-in `quantum_shannon_decomposition` function in Cirq.

According to the documentation, the `quantum_shannon_decomposition` function is supposed to decompose the unitary matrix into a sequence of CX, YPow, ZPow, and CNOT gates. However, it seems that the result of the decomposition contains a non-unitary matrix.

**How to reproduce the issue**

```python

import cirq

qft4_qubits = cirq.NamedQubit.range(4, prefix="q")
qft4_op = cirq.qft(*qft4_qubits)
qft4_qc = cirq.Circuit(qft4_op)

qft4_utry = cirq.unitary(qft4_qc)

print(cirq.is_unitary(qft4_utry))   # True

qsd_qft4_qubits = cirq.NamedQubit.range(4, prefix="q")
qsd_qft4_op = cirq.quantum_shannon_decomposition(qsd_qft4_qubits, qft4_utry)
qsd_qft4_qc = cirq.Circuit(qsd_qft4_op)

qsd_qft4_utry = cirq.unitary(qsd_qft4_qc)

print(cirq.allclose_up_to_global_phase(qft4_utry, qsd_qft4_utry))


```

<details>

```shell
True

Traceback (most recent call last):
  File "/tmp/qsd_bug_cirq.py", line 11, in <module>
    qsd_qft4_qc = cirq.Circuit(qsd_qft4_op)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/qcs/lib/python3.11/site-packages/cirq/circuits/circuit.py", line 1771, in __init__
    flattened_contents = tuple(ops.flatten_to_ops_or_moments(contents))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/qcs/lib/python3.11/site-packages/cirq/ops/op_tree.py", line 134, in flatten_to_ops_or_moments
    yield from flatten_to_ops_or_moments(subtree)
  File "/anaconda3/envs/qcs/lib/python3.11/site-packages/cirq/ops/op_tree.py", line 133, in flatten_to_ops_or_moments
    for subtree in root:
  File "/anaconda3/envs/qcs/lib/python3.11/site-packages/cirq/transformers/analytical_decompositions/quantum_shannon_decomposition.py", line 89, in quantum_shannon_decomposition
    yield from _msb_demuxer(qubits, v1, v2)
  File "/anaconda3/envs/qcs/lib/python3.11/site-packages/cirq/transformers/analytical_decompositions/quantum_shannon_decomposition.py", line 158, in _msb_demuxer
    yield from quantum_shannon_decomposition(demux_qubits[1:], W)
  File "/anaconda3/envs/qcs/lib/python3.11/site-packages/cirq/transformers/analytical_decompositions/quantum_shannon_decomposition.py", line 66, in quantum_shannon_decomposition
    raise ValueError(
ValueError: Expected input matrix u to be unitary,                 but it fails cirq.is_unitary check

```

</details>

**Cirq version**
1.4.1

**Comment by NoureldinYosri** [comment]
@uzzzzzzz can you take a look? since you implemented this https://github.com/quantumlib/Cirq/pull/6020

**Comment by pavoljuhas** [comment]
csynque meeting - we need to confirm this fails due to significant difference rather than round-off errors.

**Comment by NoureldinYosri** [comment]
related to https://github.com/quantumlib/Cirq/issues/6725

@pavoljuhas it seems that `quantum_shannon_decomposition` is indeed buggy

**Comment by ACE07-Sev** [comment]
@NoureldinYosri I would say this is a good opportunity to rewrite how cirq does QSD for two reasons:

1) It doesn't work as is.
2) Compared to Qiskit's QSD, it's 14 percent more expensive in terms of depth. This is an extremely important compilation which would directly dictate the size of problems you can meaningfully map to actual hardware.

It would be great if you can just replicate what Qiskit has for your QSD. I'd be more than happy to help where I can.

Here's a reference for QSD through qiskit vs through cirq (let's assume it's fixed):
![image](https://github.com/user-attachments/assets/8575fa49-4809-4b16-b239-bd73d7450c6a)

```
Cirq's depth: (7, 49, 235, 1027, 4291, 17539, 70915, 285185)
Qiskit's depth: (7, 41, 197, 869, 3653, 14981, 60677, 244229)
```

**Comment by ACE07-Sev** [comment]
I think it would be worthwhile to add two qubit decomposition function as I mentioned before. Looking at Qiskit's version VS Cirq's version:
![image](https://github.com/user-attachments/assets/206293dd-1444-4f4f-8e73-2bd9d8975c69)
![image](https://github.com/user-attachments/assets/93c26231-3716-4966-9701-74a8b2f70e9b)
There's a considerable difference. Besides that, the rest is the same from what I can infer.

**Comment by NoureldinYosri** [comment]
@ACE07-Sev QSD was a recent addition to Cirq and we welcome help with this and other issues. if you would like to help fix this, feel free to assign the issue to yourself and we would be very grateful. otherwise we will discuss this issue in the next cirq-sync.

**Comment by ACE07-Sev** [comment]
May I ask how I can get added to the meeting for this? I had a look at the cirq-dev google group, but I can't see any scheduled meetings there.

**Comment by NoureldinYosri** [comment]
@ACE07-Sev when you join https://groups.google.com/g/cirq-dev, you get automatic invitation to the meeting

**Comment by ACE07-Sev** [comment]
I didn't get any invites hehe, it's ok I'll try to follow from the issue discussion.

**Comment by NoureldinYosri** [comment]
@ACE07-Sev I can add you, what is your email?

**Comment by ACE07-Sev** [comment]
That would be wonderful. My email is amiralimlk07@gmail.com.

**Comment by NoureldinYosri** [comment]
looks like I can't, the event is for members of the group. make sure you followed the steps in https://github.com/quantumlib/Cirq/blob/ce1d9035e878f1f2f73e6ef9575f522bd180665f/docs/dev/rfc_process.md#how-to-submit-an-rfc

if this doesn't work you can join tomorrow at 10am pst through https://meet.google.com/www-wuvf-jjb

**Comment by NoureldinYosri** [comment]
cirq-sync: @ACE07-Sev do you want to take this task?

**Comment by ACE07-Sev** [comment]
Greetings there,

Hope you are well. Sorry for the delay, I am working on it but not sure when I'll reach the fix.

**Comment by NoureldinYosri** [comment]
@ACE07-Sev just checking if there are any updates?

**Comment by ACE07-Sev** [comment]
@NoureldinYosri Greetings,

Hope you are well. Not yet, I have been working on the QASM conversion issue. I saw your new commit, I'll have a look at that to catch up.
