### ISSUE TITLE
Support reset operation in QASM importer

### ISSUE THREAD

**Issue by natestemen** [quantumlib/Cirq#6704]
**Is your feature request related to a use case or problem? Please describe.**

We’ve encountered at least two cases where [Mitiq](https://github.com/unitaryfund/mitiq) users were unable to apply an error mitigation technique because their Qiskit circuits could not be converted to Cirq. Mitiq internally represents circuits as `cirq.Circuit` objects and relies on Cirq’s QASM importer for this conversion.

While I recognize that this might not be directly the responsibility of Cirq developers, I wanted to raise this issue for consideration. The QASM importer (https://github.com/quantumlib/Cirq/issues/1548) was developed before the reset operation was introduced (https://github.com/quantumlib/Cirq/issues/1774), so it’s possible that the reset operation was unintentionally omitted from the importer. It would be helpful to understand whether this is an area Cirq plans to address or if we should explore alternative workarounds.

**Describe the solution you’d like**

When converting a QASM circuit containing a reset operation, the resulting `cirq.Circuit` should include an instance of [`cirq.R`](https://quantumai.google/reference/python/cirq/R) to represent the reset operation.

**[Optional] Additional context**

Here’s a minimal reproducible example:
```python
from cirq.contrib.qasm_import import circuit_from_qasm

circuit_from_qasm("""OPENQASM 2.0;
include "qelib1.inc";

qreg q[1];

reset q[0];
""")
```

**Comment by NoureldinYosri** [comment]
@pavoljuhas please take a look

**Comment by rscircus** [comment]
@natestemen - having interest to support it. Am building the equivalent thing for us planning to cover QASMv3.

**Comment by rscircus** [comment]
what type of reset do you support? wait, preselection, some dissipative gate? any pointers for a starter?

**Comment by rscircus** [comment]
To me it looks like that reset is already somewhat prepared in the code. See:

`./cirq-core/cirq/ops/common_channels.py` -> `class ResetChannel` ln 704. At least it looks like they can export `ResetChannel`s to QASM.

**Comment by rscircus** [comment]
@natestemen - I think #6710 should solve your issue. It's been an interesting exercise to get into `PLY`. Further, so far it has been rather academic. It surely needs some more testing in the wild.
