### ISSUE TITLE
Replace type_workarounds.NotImplementedType

### ISSUE THREAD

**Issue by pavoljuhas** [quantumlib/Cirq#6775]
**Description of the issue**

Python 3.10 (our minimum requirement) provides [types.NotImplementedType](https://docs.python.org/3.10/library/types.html?highlight=notimplementedtype#types.NotImplementedType).  The following workaround is redundant and can be replaced with that type -
https://github.com/quantumlib/Cirq/blob/351a08e52b7090cfab3a1ad07859ebf09d54052a/cirq-core/cirq/type_workarounds.py#L15-L23

**TODO**

- switch to types.NotImplementedType in the code
- delete the type_workarounds module

**Cirq version**

1.5.0.dev at 351a08e52b7090cfab3a1ad07859ebf09d54052a.

**Comment by senecameeks** [comment]
Cirq Cynq: good first issue, no QC experience required.

**Comment by Ayobami-00** [comment]
Hi @senecameeks .

I'd like to work on this issue. Could you please assign it to me?

**Comment by Ayobami-00** [comment]
Hi @senecameeks , I made PR for this.

Kindly take a look.

https://github.com/quantumlib/Cirq/pull/6790
