### ISSUE TITLE
Consider re-organizing Circuit insertion methods

### ISSUE THREAD

**Issue by bryano** [quantumlib/Cirq#679]
There's been a proliferation of insertion methods for Circuit that do similar things but have slightly different signatures and behavior (because each new one serves a specific need as it arises as a subroutine of a larger procedure). This is far from urgent, but down the road we should return to these and consider integrating them in a coherent way.

**Comment by dabacon** [comment]
We currently have
```
append
batch_insert
batch_remove
batch_insert_into
clear_operations_touching
insert
insert_into_range
insert_at_frontier```
I think each of these has a reasonably easy to understand use case.  I'm going to close but if there is some that we think should be combined, we should re-open with that suggestion.
