### ISSUE TITLE
Add `_repr_pretty_` to all results and devices classes

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#682]
This method is used preferentially over `repr` in Jupyter notebooks and in ipython:

```
In [1]: class C:
   ...:     def __str__(self):
   ...:         return 'str'
   ...:     def __repr__(self):
   ...:         return 'repr'
   ...:     def _repr_pretty_(self, p, cycle):
   ...:         p.text('pretty')
   ...:     

In [2]: C()
Out[2]: pretty
```

`repr` is supposed to be unambiguous, so we often can't be too creative with it. In order to make the ipython experience smoother we should show coarser easier to read information.

`Circuit` works the way it should (pretty printing a circuit), but e.g. `TrialResult` does not. Support is generally very easy, because our `__str__` methods do the hard lifting:

```
    def _repr_pretty_(self, p: Any, cycle: bool) -> None:
        """Shown in ipython and Jupyter notebooks."""
        if cycle:
            p.text('TrialResult(...)')
        else:
            p.text(self.__str__())
```

**Comment by dabacon** [comment]
We don't have many implementations of this.  It is probably most urgent for "heavy" objects since otherwise it uses repr.

**Comment by dabacon** [comment]
Here is a pass on object we should consider making sure we have this for
```
cirq.Device
cirq.CliffordTrialResult
cirq.DensityMatrixStepResult
cirq.SimulationTrialResult
cirq.WaveFunctionStepResult
cirq.WaveFunctionTrialResult
cirq.IonDevice
cirq.google.Sycamore
cirq.google.Sycamore23
```
Some of these may already be done or covered by superclasses.

**Comment by dabacon** [comment]
I guess we also have guidance to use _repr_pretty_ for Gates.  So we should do a complete audit.

**Comment by dabacon** [comment]
There are now on results and on devices.
