### ISSUE TITLE
check.sh crashes if python2.7-output/ exists in the Cirq/ directory

### ISSUE THREAD

**Issue by cduck** [quantumlib/Cirq#698]
This happens while check.sh is copying the temporary repo.  It looks like shutil can't copy the broken symlink python2.7-output/docs/_templates/autosummary/module.rst.  (The symlink is broken because python2.7-generate.sh doesn't copy third_party/.)

**Comment by vtomole** [comment]
Closing due to removal of Python 2: https://github.com/quantumlib/Cirq/pull/1471
