### ISSUE TITLE
[DISCUSS] Get rid of xmon gates by merging them into the basic gate set

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#702]
It has become increasingly clear that having the xmon gate set is just duplicating work and creating incompatibility errors for no benefit. I suggest that we merge or move all xmon gates down to the base level.

Here's the proposed plan:

- The `to_proto` methods of the xmon gates are moved into a single utitlity method
- cirq.google.ExpZGate merges into cirq.RotZGate
- cirq.google.Exp11Gate merges into cirq.Rot11Gate
- cirq.google.XmonMeasurementGate merges into cirq.MeasurementGate
- cirq.google.ExpWGate becomes "cirq.PhasedRotXGate" or similar
- In the engine, we replace the W gate with "generic single qubit gate", because we can do any operation as W(a)^b Z^c and Z is free. We accept any and all operations with a single qubit as long as they have a matrix. The RotZGate will still be special, but only because it's free.

Benefits:

- Less duplication between gates.
- Several xmon-specific optimizers and decompositions can be applied more generally and move out of the google namespace.

Downsides:

- This will break pretty much everyone who has touched XmonGate.
- ExpZGate differs from RotZGate in terms of global phase. Opening that bike shed again.

What do people think?

**Comment by dabacon** [comment]
XmonGates no longer exist.
