### ISSUE TITLE
typing error when importing cirq python 3.5.1

### ISSUE THREAD

**Issue by ss2165** [quantumlib/Cirq#710]
Called from `value/timestamp.py", line 59, in Timestamp`
```
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/typing.py", line 1184, in overload
    raise RuntimeError("Overloading is only supported in library stubs")
RuntimeError: Overloading is only supported in library stubs
```

when `import cirq` was called

Am I correct in thinking this version of python is supported?

**Comment by Strilanc** [comment]
Yes, thanks for catching this. I'll release a package with the correct constraints. (And I guess delete the old one, since otherwise 3.5.1 will just grab the bad one.)

**Comment by Strilanc** [comment]
Fixed by https://github.com/quantumlib/Cirq/pull/715

**Comment by maffoo** [comment]
From the python 3.5.2 release notes it looks like the change to allow `@overload` outside stubs was already present in that version (https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-2-final). Was there another reason to skip 3.5.2 and require 3.5.3 instead?

**Comment by Strilanc** [comment]
Nope. Was just being safe and fast.
