### ISSUE TITLE
Reduce number of files at top level

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#748]
Super big nit: would be nice to have the Cirq logo show up without having to scroll down to see it :)

**Comment by Strilanc** [comment]
I suppose we could move the python2.7 stuff into a compat folder.

It looks like release.md can be moved into docs.

dev-requirements and apt-dev-requirements could go in dev_tools?

protobuf-generate might get squashed by removing the compiled protos.

It might be possible to configure travis to look for .travis.yaml inside continuous-integration. Similar for readthedocs.

MANIFEST.in might fit into dev_tools

**Comment by Strilanc** [comment]
I'll keep an eye out for changes to make this better during the next release.

**Comment by vtomole** [comment]
> Would be nice to have the Cirq logo show up without having to scroll down to see it

This is impossible as the screen is cutoff at the `docs` directory.  Let's just keep an eye out for anything that will go to top-level in the future. This issue is not specific so i will close it.
