### ISSUE TITLE
Update line placement to include calibration data

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#751]
- Define XmonCalibrationData class in google package with qubit-cost and edge-cost getter methods.
- Move placement code into google namespace (since it references xmon device) (leave LineQubit outside cirq.google).
- Add support for working with CZ-protection-adjacency (i.e. neighbor-of-neighbor of avoidance). 

@mrwojtek

**Comment by dabacon** [comment]
Point 2 is done.
Point 3 is no longer relevant.

It looks like the remaining work would be to take metrics from engine and support them as the costs.

**Comment by tanujkhattar** [comment]
While using calibration data to figure out optimal qubit placement is an important strategy, there have been no recent requests by experimentalists to add this feature to the line placement strategy. I will go ahead and close this issue for now and we can reopen if people think this should be prioritized.

cc @verult

**Comment by verult** [comment]
cc @wcourtney
