### ISSUE TITLE
Cirq tutorials contain explicit TODOs

### ISSUE THREAD

**Issue by mrwojtek** [quantumlib/Cirq#752]
Final section of those documents have this problems:
https://cirq.readthedocs.io/en/latest/gates.html
https://cirq.readthedocs.io/en/latest/simulation.html

**Comment by vtomole** [comment]
Those links are not TODO anymore, but we do need to add docs for optimization: https://github.com/quantumlib/Cirq/issues/1703.

**Comment by dstrain115** [comment]
It looks like those links still contain TODOs

**Comment by dstrain115** [comment]
REmoved all the TODOs, I believe.
