### ISSUE TITLE
optimized_for_xmon() should cancel more CZ gates 

### ISSUE THREAD

**Issue by cduck** [quantumlib/Cirq#756]
These should optimize to an empty circuit.

Input 1:
```
0: ───@───────────@───
      │           │
1: ───@───@───@───@───
          │   │
2: ───────@───@───────
```
Current output:
```
0: ───@───@───
      │   │
1: ───@───@───
```

Input 2:
```
0: ───@───────@───────
      │       │
1: ───@───@───@───@───
          │       │
2: ───────@───────@───
```
Current output:
```
0: ───@───────@───────
      │       │
1: ───@───@───@───@───
          │       │
2: ───────@───────@───
```

**Comment by Strilanc** [comment]
Hmmm. The first one would be fixed if you optimized again, but the second one is a fixed point.

Maybe we need a "commute forward looking for your anti-self" kind of check.

**Comment by Strilanc** [comment]
Although I think this would be great to do, it is quite difficult to pick a stopping point when it comes to optimizers. I think "all optimizations cancel locally" is as good a line as any. Also... this is now obsoleted by xmons being an older architecture.
