### ISSUE TITLE
[DISCUSS] Features for quantum teleportation

### ISSUE THREAD

**Issue by enakai00** [quantumlib/Cirq#762]
Hi, I'm wondering if executing quantum teloportation with Cirq is possible (or meaningful to implement necessary features for that).

I think one of the following features is required to implement [the Quantum teleportation circuit](https://upload.wikimedia.org/wikipedia/commons/d/dc/Quantum_teleportation_circuit.svg).

1. Using the measurement result as a control bit.

2. Hold the Bob's qubit status after running the first half of the circuit (until the Alice's measurement). And after building the last half of the circuit based on the measurement result, resume the circuit operation for Bob's qubit.

This may not be an intended use case of typical gate devices, but I want to know if it's worth implementing the above features.

**Comment by Strilanc** [comment]
Currently cirq doesn't have any specified way to perform feed forward. This is intended, because the same thing is true of hardware. We're waiting to see how hardware implements it before putting it into the library.

**Comment by enakai00** [comment]
I got it. I understand that hardware implementation is not trivial. Anyway, I will give it a try to implement 2. as a pure simulator feature in my private fork for my exercise. Thanks.
