### ISSUE TITLE
engine JobConfig needs good string representation 

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#776]
print(job_config) currently returns  just the object reference.  This should return a better representation of the job config.

**Comment by mizkulg** [comment]
I'd like to help. Which code file are you discussing here?

**Comment by dabacon** [comment]
https://github.com/quantumlib/Cirq/blob/master/cirq/google/engine/engine.py

JobConfig needs a good str/repr.  Example of a class with such a setup is TrailResult in https://github.com/quantumlib/Cirq/blob/cae6f8381245899f0d139d123fd4edce6da5008f/cirq/study/trial_result.py

**Comment by vtomole** [comment]
@cduck I implemented this. Can you close it? Thanks.

**Comment by Strilanc** [comment]
@vtomole If you include the magic words "Fixes #___" in the commit messages (and sometimes PR description), it should auto-close on merge.
