### ISSUE TITLE
JobConfig should be able to return resource name for program and job

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#777]
Natural to put the resource name on the JobConfig.  Also useful in using the JobConfig returned back in EngineJob to call the other resource name base commands.
/projects/<project id>/programs/<program id> etc.

**Comment by ptrc-n** [comment]
As all information needed to construct the resource name (currently in run_sweep()) is already present in JobConfig I would go with constructing the resource name directly when instantiating JobConfig.

Skimming thorugh the code I recognized that engines run() method takes keyword arguments that are not documented yet. A link to apiclient.discovery.build() documentation or a hint / check that kwargs have to be in ['model', 'requestBuilder'.....] might be helpful. 
Is this worth an additional issue or should I just work on that?

May I ask you to assign me this issue?

**Comment by dabacon** [comment]
`JobConfig` no longer exists.  We have moved away from using resource ids in the client code.  All that code should now refer to specific ids (project_id, program_id, job_id).  These are accessible attributes on relevant objects.
