### ISSUE TITLE
Add more links to other projects

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#788]
e.g. tket

**Comment by vtomole** [comment]
Context please?

**Comment by dabacon** [comment]
This is at the front documentation page.   Documentation revamp should consider this.  

@karlunho

**Comment by balopat** [comment]
I'll pick this up - @karlunho prepared a [doc](https://docs.google.com/document/d/1ME12KxdUHJGdcZqj7NkTxvdhYV_eNK8hHq9RsLsYRV8/edit#) for this

**Comment by balopat** [comment]
https://quantumai.google/cirq/ecosystem exists now, closing.
