### ISSUE TITLE
Update cirq.google.Bristlecone/Foxtail with accurate duration numbers

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#791]

**Comment by vtomole** [comment]
What are the correct duration numbers?

**Comment by Strilanc** [comment]
I'll add these once we have concrete numbers.

**Comment by dabacon** [comment]
@JulianSKelly for posterity what numbers would you recommend for xmon gate speeds (we currently have 50 ns CZ and 20 ns XY)?

**Comment by JulianSKelly** [comment]
I would use 45ns CZ and 15 ns XY
