### ISSUE TITLE
Minor incremental coverage bug

### ISSUE THREAD

**Issue by cduck** [quantumlib/Cirq#809]
Incremental coverage can say that a `continue` statement is uncovered when it actually is.

### Minimal case
cirq/t.py
```
def func(*args):
    for a in args:
        if a:
            return 2
        else:
            continue  # Incremental coverage thinks this is untouched
    return 1
```

cirq/t_test.py
```
from cirq import t

def test_func():
    assert t.func(False) == 1
    assert t.func(True) == 2
```

**Comment by vtomole** [comment]
This was not fixed because Python's optimizer replaces a jump to a continue with a jump to the top of the loop. See https://bugs.python.org/issue2506. There are two ways of fixing this: 

1.Tell Coverage.py to ignore `continue`

```
def func(*args):
    for a in args:
        if a:
            return 2
        else:
            continue  # pragma: no cover
    return 1
```
2. Add useless code to bypass CPython's peephole optimizer so that coverage records correctly

```
def func(*args):
    for a in args:
        if a:
            return 2
        else:
            1+1
            continue  
    return 1
```
@Strilanc Thoughts?

**Comment by Strilanc** [comment]
For now we'll stick with `# coverage: ignore` annotations. That's far better than a mystery expression to trick the optimizer.

**Comment by vtomole** [comment]
`continue` is used multiple times.  `cirq/circuits/qasm_output.py: line 168` for example. How was this coverage issue fixed?

**Comment by vtomole** [comment]
The mystery continues..

**Comment by Strilanc** [comment]
If it's not happening anymore, it may have been fixed upstream from us.

**Comment by Strilanc** [comment]
Victory reports not happening anymore.
