### ISSUE TITLE
Example function rot_11_layer in tutorial

### ISSUE THREAD

**Issue by XiaoMiQC** [quantumlib/Cirq#826]
It seems the rot_11_layer function in the tutorial is not doing what it is supposed to do.

**Comment by dabacon** [comment]
In particular the second loop over the column terms does not conjugate by X operators.

**Comment by dabacon** [comment]
Also the discussion of big endian needs to be better explained.

**Comment by dabacon** [comment]
Also the reshaping for the fold function is wrong.

**Comment by dabacon** [comment]
Fixed in #839
