### ISSUE TITLE
Bazel rules for protobufs so that we don't have to regenerate generated protobuf code

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#83]

**Comment by dabacon** [comment]
We no longer include the generated code because the engine code can use straight python dictionaries.  However we should probably include bazel rules here anyway.

**Comment by vtomole** [comment]
Would like to help with this if i knew what it meant. I'm willing to learn Bazel but there are no tutorials for Python: https://docs.bazel.build/versions/master/getting-started.html

**Comment by vtomole** [comment]
Looks like Bazel rules are language agnostic. This is what I have in a `BUILD` file in `cirq/api/google/v1`

```
proto_library(
    name = "operations_proto",
    srcs = ["operations.proto"],
)

proto_library(
    name = "params_proto",
    srcs = ["params.proto"],
)

proto_library(
    name = "program_proto",
    srcs = ["program.proto"],
    deps = [
    "operations_proto",
    "params_proto",
    ],
)
```

**Comment by dabacon** [comment]
@vtomole have you check to see if this compiles in Bazel?  If so I think we should add these (without making bazel a requirement of Cirq, but I think this will be useful...at least it will be inside of Google!)

**Comment by vtomole** [comment]
Bazel can compile it. Should I also send the `WORKSPACE` file? It's in `Cirq/` and it contains

```
# This statement defines the @com_google_protobuf repo.
http_archive(
    name = "com_google_protobuf",
    sha256 = "cef7f1b5a7c5fba672bec2a319246e8feba471f04dcebfe362d55930ee7c1c30",
    strip_prefix = "protobuf-3.5.0",
    urls = ["https://github.com/google/protobuf/archive/v3.5.0.zip"],
)

```
`
Cirq$ bazel build //cirq/api/google/v1:program_proto 
`
and friends can't succeed without it.

**Comment by Strilanc** [comment]
I had to kill the bazel step on travis because the jdk download started 404ing

**Comment by dabacon** [comment]
we have valid BUILD files, but aren't using or requiring bazel.  I think we should close.
