### ISSUE TITLE
Add cirq.testing.assert_same_diagram

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#830]
This method would do two things:

1. Strip the diagrams for you, so you didn't have to worry about trailing newlines in the code.
2. Give better error messages than python's default string error message.

For point 2, the main thing that is required is to append the actual diagram and reference diagram without abbreviation. Pytest is far too abbreviation heavy for the diagrams.

Secondarily for point 2, a better diff should be included. The information is 2d instead of line-based, and the diff should be similarly 2d. Show a copy of the actual diagram with any character positions that differ from the reference diagram replaced by ■ or some other obtrusive char.

**Comment by kevinsung** [comment]
For use cases I have encountered, I often want to ignore differences due to insertion strategies, i.e., I'd want to shove all gates to the left before comparing.

**Comment by Strilanc** [comment]
That would be better described as a circuit equivalence rather than a diagram equivalence.

**Comment by bryano** [comment]
`CircuitDag` would be good for that.

**Comment by cduck** [comment]
Probably, but it would have to support customizing node equality.  The matching in the two graphs wouldn't compare equal by default.

**Comment by cduck** [comment]
You can do it with is_isomorphic.
