### ISSUE TITLE
Replace XmonDevice from placement

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#849]
XmonDevice is currently used by the placement code, which is in core.  A suitable way to specify the geometry for devices outside of cirq.google should be made so that we don't have core cirq depending on cirq.google

**Comment by mrwojtek** [comment]
The number of issues on how the line place should really work grow, with more and more conflicting each other.

In #751 we agreed with @Strilanc to move line code inside the cirq.google, so it can freely depend on Xmon* classes. This move would make placement code work only within cirq.google and limit its behavior. After discussion with @dabacon we came to conclusion that we might want to rethink this decision.

In #95 I proposed a set of interface methods that grid or graph device would need to support in order for the placement code to be implementable. This would keep line placement generic. One current problem with that approach right now is that we have only `Device` and `XmonDevice` that implements it. We don't have any `GridDevice` or `GraphDevice`, where connectivity concepts that I'm about to introduce would have a meaning. To make placement generic we should probably have it.

**Comment by dabacon** [comment]
I'm going to close this. We now have two placement/routing codes in Cirq, one in Google and one in contrib.  I think we should think about whether a general location is suitable.  Of course there are also a lot of algorithms to explore in this space, so we would likely want to leverage previous algorithm work.
