### ISSUE TITLE
Create a Jupyter notebook with gates worked out explicitly

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#852]
This would help clarify some of the "half angle" confusions.

**Comment by vtomole** [comment]
What's the update on this?

**Comment by vtomole** [comment]
We couldn't find this because Jupyter is misspelled (`juptyer`).  @dabacon what's the context on this? Could be a two birds one stone with: https://github.com/quantumlib/Cirq/issues/1564

**Comment by dabacon** [comment]
A possible documentation page to think about @karlunho a notebook or page with all of the gates (gate zoo)

**Comment by MichaelBroughton** [comment]
Is this still in flight @dabacon ? Is this relevant : https://quantumai.google/cirq/gates ?

**Comment by dabacon** [comment]
Still in flight, doing two qubit gates next.

**Comment by dabacon** [comment]
Fixed in #5344
