### ISSUE TITLE
decompositions_test fails due to accuracy issues

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#858]
test_controlled_op_to_operations_concrete_case fails on my machine due to an accuracy issue:

E       assert [(cirq.Y**-0....dQubit(u't'))] == [(cirq.Y**-0.5...dQubit(u't'))]
E         At index 0 diff: (cirq.Y**-0.5000000000000001).on(cirq.NamedQubit(u't')) != (cirq.Y**-0.5).on(cirq.NamedQubit(u't'))

**Comment by dabacon** [comment]
@dstrain115 you were looking into this, correct?

**Comment by dstrain115** [comment]
Yeah, it should be fixed.  Do you still see it manifest at HEAD?  If not, we can close.

**Comment by dabacon** [comment]
Just wanted to close this issue.
