### ISSUE TITLE
name examples/supremacy.py is too general

### ISSUE THREAD

**Issue by sboixo** [quantumlib/Cirq#859]
There is a file in examples called 'supremacy.py' with a function 'generate_supremacy_circuit'

Details matter a lot for simulation and experiment, and this is a very generic name, without a version number. 
What about changing the name to something more specific for this particular ensemble or circuits?

**Comment by vtomole** [comment]
I'm not familiar with the circuit that is being generated here. What would you like us to rename `generate_supremacy_circuit'` to?

**Comment by vtomole** [comment]
Named to `google_v2_supremacy_circuit.py`: https://github.com/quantumlib/Cirq/blob/master/cirq/experiments/google_v2_supremacy_circuit.py
