### ISSUE TITLE
Allow Symbols to be specified in rads, e.g. in cirq.Rx

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#868]
Not sure yet what this would look like.

**Comment by babbush** [comment]
I agree this is absolutely necessary. I don't know what you think is so fundamental about half turns though. How would having "rads" as a symbol be any different? Do you mean that you don't know what you'd output in the ASCII diagrams?

**Comment by Strilanc** [comment]
This will be fixed by fixing https://github.com/quantumlib/Cirq/issues/393

**Comment by Strilanc** [comment]
Fixed by switch to sympy
