### ISSUE TITLE
Feature request: classical registers

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#887]
Intermediate representations like QASM have `creg c0[1];` to initialize classical registers and `measure q[0] -> c0[0];` for assigning measurement results to classical memory. Are there equivalent procedures in Cirq?

**Comment by bryano** [comment]
My understanding is that there was a conscious design decision to not support this because current hardware can't do intermediate measurements.

**Comment by Strilanc** [comment]
@bryano is correct. We don't know what the limitations of feedforward will actually be, so for now we've avoided codifying it. The closest thing we have to any kind of classical processing at the moment is the invert-result mask on measurement gates.

**Comment by vtomole** [comment]
Reopening based on comments by @balopat.

**Comment by balopat** [comment]
Related #3231.

**Comment by daxfohl** [comment]
@vtomole I think all the work in classical controls means this can be closed.
