### ISSUE TITLE
Optimize for use case: get wavefunction after each moment for small circuits

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#889]
@zchen088 uses this functionality quite heavily as part of randomized benchmarking, and cirq is the bottleneck. Switching off XmonSimulator made it better, but there's still quite a lot of overhead from computing gate matrices repeatedly.

**Comment by zchen088** [comment]
+1, though I should note that I tried implementing caching of the matrix computation and that only helped by around 20%. It looks like the remaining bottleneck is doing `isinstance` checks.

**Comment by Strilanc** [comment]
Yes, it's likely that the move away from extensions will help this use case.

**Comment by dabacon** [comment]
What functionality is missing from the moment iterator in the XmonSimulator?  That's the pattern we'll use with the numpy simulator too.

**Comment by Strilanc** [comment]
I suspect it's just that the functionality is not really exposed.

**Comment by maffoo** [comment]
I don't think there are any missing features for this use case. Just want things to run faster. @zchen088, do you have an numbers to compare the performance of cirq with what you'd want?

**Comment by dabacon** [comment]
Closing this as likely this is legacy from wonky xmon simulator.  If this is still to slow for some reason, please reopen, hopefully with some timings showing the issue.
