### ISSUE TITLE
Should xmon device's duration_of method validate the operation it acts on?

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#899]
You can pass in an operation that acts on a qubit that doesn't exist on the device.

```
cirq.google.Bristlecone.duration_of(cirq.google.Exp11Gate()(cirq.NamedQubit('a)))
```

**Comment by Strilanc** [comment]
Clearly we should return `float("inf")` in this case.

**Comment by c-poole** [comment]
@Strilanc This appears to have been resolved by throwing an error if an unrecognized operation gets passed in.

**Comment by dstrain115** [comment]
This has been fixed a while ago by raising a ValueError with ''Unsupported gate type'

https://github.com/quantumlib/Cirq/blob/master/cirq/google/devices/xmon_device.py#L75
