### ISSUE TITLE
Allow approximate circuit equality checks

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#900]
Blocking https://github.com/quantumlib/Cirq/pull/876

**Comment by vtomole** [comment]
Reminder: Convert ` PauliStringPhasor(pauli_string, half_turns=round(half_turns, 10)))` to `PauliStringPhasor(pauli_string, half_turns=half_turns)` in `cirq/contrib/paulistring/convert_to_pauli_string_phasors.py line 86-87` after this has been implemented.

**Comment by vtomole** [comment]
What's the best way to implement this? Here's a prototype: Looping though all the PauliStringPhasors and calling `isclose()`, which calls `round()` on them.
In `pauli_string_phasor.py`
```
def _isclose_tuple(self) -> Tuple[Hashable, ...]:
        return (PauliStringPhasor, self.pauli_string, round(self.half_turns))
```

In `circuit.py`
```
def isclose(self, other):
        phasor_str = 'cirq.contrib.paulistring.pauli_string_phasor.PauliStringPhasor'
        if not isinstance(other, type(self)):
            return NotImplemented

        for i, j in zip(self._moments, other._moments):
            if str(type(i.operations[0])) == phasor_str and str(type(j.operations[0])) == phasor_str:
                if i.operations[0].isclose(j.operations[0]) is False:
                    return False

        return True
```

**Comment by Strilanc** [comment]
I think we'd do this with a protocol such as `_isclose_` or `_is_approximately_equal_`, and a global utility `cirq.isclose` or `cirq.approx_eq`. The method would take `atol` and `rtol` as the numpy methods do, and then each gate would be responsible for knowing how it compares.

We might be able to make a variant of `cirq.value_equality` for this task, which would make it much easier.

**Comment by mrwojtek** [comment]
Approximate equality is now accessible through cirq.approx_eq() protocol. It is being introduced for EigenGate in #1275 and for matrix gates in #1276. It fall-backs to regular equality if neither SupportsApproximateEquality or _SupportsValueEquality protocols are implemented. As far as I remember from conversation with Craig Pauli strings are being refactored and code that is mentioned to be reverted is going to change.

**Comment by mrwojtek** [comment]
Can we close this issue, is there something still to be done inside of `PauliStringPhasor`?

**Comment by vtomole** [comment]
@Strilanc Ping.

**Comment by Strilanc** [comment]
Doesn't `Circuit` still need to implement `_approx_eq_` to finish this?

**Comment by mrwojtek** [comment]
Ack, I'll do this by Monday (perfect motivation to get back to Cirq).

I see that I also need to implement `_approx_eq_` on `Moment` which will just delegates to `_approx_eq_` on iterable of `Operation`.

For `Device` I'll just use type-equality?

If you think that some other parts of Cierq could also use support for `_approx_eq_` please let me know, I'm not following everything what is going on now...

**Comment by Strilanc** [comment]
circuit and moment supporting it is sufficient

**Comment by mrwojtek** [comment]
Created #1465.

I see there is also `CircuitDag`, shouldn't it have support for approximate equality?

**Comment by c-poole** [comment]
@Strilanc  This looks closable

**Comment by vtomole** [comment]
Pinging @Strilanc for @mrwojtek's question (`CircuitDag` needing support for approximate equality)

**Comment by vtomole** [comment]
@Strilanc Ping +2

**Comment by Strilanc** [comment]
We don't need CircuitDag to support this to close it. Thanks for the pings. :+1:
