### ISSUE TITLE
installation problem: No matching distribution found for cirq

### ISSUE THREAD

**Issue by dlyongemallo** [quantumlib/Cirq#906]
On some system configurations, when following the [installation instructions](https://cirq.readthedocs.io/en/latest/install.html), I am getting the following error upon executing `pip install cirq`:
```
Collecting cirq
  Could not find a version that satisfies the requirement cirq (from versions: )
No matching distribution found for cirq
```

A virtual environment was set up using:
`mkvirtualenv cirq-py3 --python=/usr/bin/python3`

System 1:
* python 3.5.2
* Ubuntu 16.04.5 LTS

System 2:
* python 3.5.2
* Ubuntu 14.04.05 LTS

**Comment by Strilanc** [comment]
This is because the package declares that it supports 2.7 and 3.5.3+.

In the next release, we are loosening the 3.5.3 to 3.5.2.

**Comment by dabacon** [comment]
Updated documentation and next release should be 3.5.2.  Closing for now

**Comment by bjwest** [comment]
Have you now dropped support for Python 3.6?  Because I'm getting this error with 3.6.7 installed.
