### ISSUE TITLE
Document easy way to displays circuits on grids

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#908]
That would automatically make Foxtail programs compatible with Bristlecone.

**Comment by maffoo** [comment]
Columns 5 and 6 of bristlecone are equivalent to foxtail, rotated on its side. We could add a function to map a foxtail circuit into those two columns.

**Comment by dabacon** [comment]
Ah I was thinking about moving the grid of Foxtail, but probably this is a bad idea because there is a nice convention for containing box containing 0,0 as grid point.

**Comment by dabacon** [comment]
I think what is missing here is just a simple method that creates the Callable between cirq.Qid's that is used in Circuit.with_device.  Actually I think can just pass lambda x: x+(1,2) to do the appropriate displacement.  

Keep this open as it might be nice to add this to doc string for with_device

**Comment by dabacon** [comment]
@karlunho

**Comment by tanujkhattar** [comment]
`Circuit.with_device` is now deprecated and replaced by `GridDevice` and `GridDeviceMetadata` which consume the device graph. This seems obsolete now so I'll go ahead and close it but please reopen if you think there's stuff that needs to be done. 

cc @verult for more context.
