### ISSUE TITLE
How does the Apache license work when it comes to attaching the boilerplate notice to a file?

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#912]
I've read the licence, but I've noticed some files in `Cirq/examples/` like `quantum_fourier_transform.py` have the licence at the top of the file while files like `grover.py` don't.

**Comment by Strilanc** [comment]
Not a lawyer, but I feel pretty strongly that the example code shouldn't be bogged down with license notifications. Why would we care if people copy-and-modify example code? That's what it's for.

**Comment by dabacon** [comment]
We should maybe add a README about this in examples?

**Comment by Strilanc** [comment]
That sounds reasonable. We could also mention things like "must run unconverted", "not included in the packaged library", etc.
