### ISSUE TITLE
Add ion trap devices

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#931]
Three different connectivities:
- All at once two qubit gates, single qubit gates
- All at once two qubit gates on region, single qubit gates
- Individual two qubit gates, single qubit gates
Configuration on parallelization of such gates.

**Comment by Strilanc** [comment]
This is waiting on a review from me.

**Comment by vtomole** [comment]
I don't know how "hard" the release deadline is; but all that's left from this is @mlihc15  changing `QubitId` to `Qid`.

**Comment by c-poole** [comment]
This was merged yesterday

**Comment by vtomole** [comment]
Yeah. Not related to https://github.com/quantumlib/Cirq/pull/1169.
