### ISSUE TITLE
Switch from _unitary_ to decomposition for large gates when simulating

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#940]
Basically, if someone provides a 20 qubit gate with a matrix and a circuit decomposition, cirq will make the very unfortunate decision to go with the matrix instead of the gates.

**Comment by dabacon** [comment]
This is another reason decompose should only be used for a composite gate and nothing else.

**Comment by dabacon** [comment]
Currently the simulators default to decompose first, so this shouldn't happen.  

Still think decompose is dangerous and should be handled with care :)
