### ISSUE TITLE
WaveFunction simulators should allow easy calculation of expectation values.  

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#941]
Need to be able to specify the operators to be measured over the wire, and then get back expectation values.

**Comment by Strilanc** [comment]
This should be merged with https://github.com/quantumlib/Cirq/issues/942

**Comment by babbush** [comment]
As I understood it (perhaps incorrectly), the issues are a little bit different. This issue sounds to me to be about changing the way the simulator works so that one can get expectation values directly instead of needing to average over many runs. Whereas issue #942 is about functionality for specifying the circuits needed to perform the measurements.

**Comment by kevinsung** [comment]
If I understand correctly, this issue is actually about potentially modifying the Quantum Engine interface to allow more than just taking a Circuit and returning bitstrings.

**Comment by babbush** [comment]
or even just the Cirq simulator.

**Comment by kevinsung** [comment]
True, currently the two interfaces are identical and I think the plan is for them to remain so.

**Comment by babbush** [comment]
Yes the interfaces are the same but the way you would get an expectation value from the simulator, versus from the device are very different. You need to sample the device whereas from the simulator you can exactly contract the expectation value from the wavefunction.

**Comment by dabacon** [comment]
WaveFunctionSimulatorState should have a way to pass in the PauliSumLike that you want to calculate the expectation of.

**Comment by mpharrigan** [comment]
@95-martin-orion can this be closed? or merged into some of the other open issues?

**Comment by 95-martin-orion** [comment]
Yeah, I'd say this was resolved as part of #3492.
