### ISSUE TITLE
Feature Request: Gate or method to measure qubits in Pauli eigenstate basis

### ISSUE THREAD

**Issue by babbush** [quantumlib/Cirq#942]
Often, people will want to run circuits repeatedly to measure the expectation value of a particular Pauli string. For instance, they might want to measure `<X2 Y3 Z4>`. Of course, one can use phase estimation to measure that operator directly and obtain 1 / eps scaling but that's not very NISQ. Typically, people will repeat the circuit 1 / eps^2 times and sample the expectation value. To do this, one needs a sequence of single qubit rotations. For instance, to measure X2 Y3 Z4, one must rotate qubit 2 around Y by pi / 2 and rotate qubit 3 around X by pi / 2, then measure qubits 1, 2 and 3.

I am tempted to make something like a "MeasurementRotationGate" which would take as input some specification of a Pauli string and then output the appropriate gates to perform rotations that allow one to sample in that basis. Thus, it would take X2 Y3 Z4 as input, and output a gate which performs the rotations and measurements mentioned above.

First, do people think this is a good idea? I think it would be very frequently used in the context of VQE. If so, how should the Pauli string input be specified? I would be partial to allowing either of the ways that we initialize QubitOperators in OpenFermion; i.e. we either allow them to provide an actual string like "X2 Y3 Z4" or they can give a tuple like ((2, "X"), (3, "Y"), (4, "Z")).

**Comment by dabacon** [comment]
Craig and I have talked about something like this in the past. #941 will need something like this.  There are two places we need to discuss how this would work
1) on the cirq side where I think we can use something like #932 or related to make this more transparent than a tuple or a string (what is the 1 in X1...people should have access to the GridQubits so we want them to be able to use that)
2) What sort of feature we add to the api to support this. 

Another thing to note is that one can already create such a gate in Cirq that does this, by creating the appropriate composite gate.  @Strilanc comments?

**Comment by Strilanc** [comment]
I think this falls under the purview of "displays", which would be special inspection gates that basically say "tell me an expectation value at this point in the circuit". Naively, every display requires its own set of runs of the circuit. But in a simulator you can fill them all in in one pass, assuming there are no measurements present.

**Comment by dabacon** [comment]
Since we've abandoned displays, we should revisit the main gist of this request, which is an easy way to measure in different Pauli eigenstate basis.  

This could be

1. A composite gate which takes in the PauliString and a key and is a gate and that decompose spits out the correct rotations followed by measurement.
2. A helper that returns an iterator of this gates, something like `Cirq.measure_pauli(paulistring, qubits, key)`.  You could then insert this into the your circuits just like you'd insert a measurement gate.  
3. Alternatively this could be added to PauliString itself.  `PauliString.measure(qubits, key)`.

The advantage of 2 is that it allows very compact code
```
cirq.measure_pauli('XXZ', qubits, key='a')
```
whereas for 3 there is another step of indirection
```
cirq.PauliString('XXZ').measure(qubits, key='a')
```

Of course these are not exclusive, the real question is whether we want to think of PauliString in a way that can be turned into a gate.  I think that is probably good, so would recommend 3 with the helper 2.

Other suggestions?

**Comment by maffoo** [comment]
It would be nice if this produced parameterized rotation gates for the basis change, so that one could potentially measure many different pauli strings as part of a sweep over parameters. There's also #2781 that tries to tackle this in a more general way.

**Comment by dabacon** [comment]
Yes would suggest something like `measure_paulis` which could take in multiple pauli string like and then produce the circuit along with the parameters.

**Comment by balopat** [comment]
Chatted on Cirq Cync. 
Requirements: 

* We can start with extending the cirq.measure. 
* The meat of this work will be `cirq.PauliMeasurementGate` analogous to the `cirq.MeasurementGate` (DensePauliString).
* In the hardware we have rotations and measurement. Maybe we should keep the representation closer to hardware: Parametrizability would be great (@maffo's comment) - this goes against using `DensePauliString`...  
* CompositeGate + decomposition (@Strilanc promised to add some comments/thoughts here)

**Comment by Strilanc** [comment]
So here's what I'm picturing as the general design:

```
class PauliMeasurementGate(cirq.Gate):
    def __init__(key: str, basis: Iterable[Union[cirq.Pauli, sympy.Basic]]):
        ...

    def _decompose_(self, qubits):
        yield single qubit rotations transforming into ZZZZ... observable
        yield CNOTs transforming into ZIIII... observable
        yield cirq.measure(qubits[0], key=self.key)
        yield reverse CNOTs transforming into ZIIII... observable
        yield reverse single qubit rotations transforming into ZZZZ... observable

    def observable() -> DensePauliString:
        if self._is_parameterized_():
            raise Error
        ...

    def _apply_to_(self, args):
        # don't recall the exact names of things here
        if isinstance(args, ~~~cirq.ApplyToStateVectorSimulatorState~~~):
            ... args.record_measurement ...
```

**Comment by mavzolej** [comment]
So has the functionality for measuring Pauli operators been added to Cirq?

**Comment by tanujkhattar** [comment]
Measuring a single observable using a `PauliMeasurementGate` has been done as part of #4444 
Measuring multiple observables using sweeps of parameters has been done as part of #4127

Closing this issue now.
