### ISSUE TITLE
Refactor PhaseableEffect class into a magic method protocol

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#947]
Part of https://github.com/quantumlib/Cirq/issues/672

This task includes:

1. Creating a magic method (akin to `def _unitary_`) that indicates phaseability.
2. Creating a utility method (akin to `cirq.unitary`) to invoke the phaseability magic methods.
3. Refactoring existing code that *uses* operation phasing to instead use the utility method defined in (2). Drop any directly related extensions functionality while doing so.
4. Refactoring existing classes that *provide* phasing functionality to instead use the magic method defined in (1). Drop any directly related extensions functionality while doing so.

**Comment by dstrain115** [comment]
I should be able to get BoundedEffect done this week (or at least our for review), so I think I can get this done in about 2 weeks.
