### ISSUE TITLE
Refactor BoundedEffect class into a magic method protocol

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#948]
Part of https://github.com/quantumlib/Cirq/issues/672

This task includes:

1. Creating a magic method (akin to `def _unitary_`) that indicates bounded trace distance.
2. Creating a utility method (akin to `cirq.unitary`) to determine a trace distance bound.
3. Refactoring existing code that *uses* bounds to instead use the utility method defined in (2). Drop any directly related extensions functionality while doing so.
4. Refactoring existing classes that *provide* bounds to instead use the magic method defined in (1). Drop any directly related extensions functionality while doing so.

**Comment by dstrain115** [comment]
Fixed by pull request 1005:

https://github.com/quantumlib/Cirq/pull/1005
