### ISSUE TITLE
Implement a `GraphQubit` type

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#95]
Right now QubitLoc is  just a 2d point.  This is very reasonable for our hardware, but there are other qubit types that are very natural and which we should support (lines, staggered grids, general graph connectivities).  

Proposal:
Abstract out the interface that describes adjacency, i.e. make an interface type HasAdjacency which requires the method is_adjacent.  (Right  constant two qubit gate assumes that the qubits implement this method).

New Qubit types
GridQubit
LineQubit

Also a way to go from an Adjacency graph to a set of GraphQubits which implement HasAdjacency and  which obey the adjacency relation of the graph.

This would mostly be relevant for defining a single / two qubit gates that respect adjacency, and also for device which use this adjacency in some of their constraints.

**Comment by bryano** [comment]
It seems more natural for adjacency and gate information to be part of the device rather than the qubit. Why not just give GraphDevice a graph attribute whose vertices can be generic `QubitId`s?

**Comment by vtomole** [comment]
@bryano Is this related to all of your not-yet-merged pull requests?

**Comment by bryano** [comment]
Yea, specifically #1181

**Comment by bryano** [comment]
Can this be closed?
