### ISSUE TITLE
Merge cirq.google xmon gates into the basic gate set

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#952]
Currently, the xmon gates are adding negative value. They do essentially the same thing as some of the basic gates, and people using basic gates get bit by the totally minor differences.

The merge must preserve the matrices of the gates. That is to say, it is necessary for the basic gates to support global phase shifting before this can happen.

Comes after https://github.com/quantumlib/Cirq/issues/950

**Comment by kevinsung** [comment]
Just curious, why is it essential for the Xmon gates to have a certain global phase?

**Comment by Strilanc** [comment]
People have preferences about whether a 180 degree rotation around the X axis should equal the Pauli X gate or exp(i pi X) = iX != X.
