### ISSUE TITLE
Add multiplication by scalar support to Symbol

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#961]
This is related to #393 but we could potentially implement this without doing #393. This would be super useful for creating parameterized circuits that approximate operators of the form exp(-i H t), where t is a variable parameter. For example, the `simulate_trotter` function in OpenFermion-Cirq would be able to take a Symbol for the `time` argument.

**Comment by vtomole** [comment]
Done by us moving to `sympy`. Please close.
