### ISSUE TITLE
Add __mul__ to cirq.PauliString and cirq.Pauli

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#962]
Note that the result has to be a `(complex, cirq.Pauli/cirq.PauliString])` tuple, because there may be an imaginary phase.

For example, `cirq.Pauli.X * cirq.Pauli.Y` should return `(1j, cirq.Pauli.Z)`.

**Comment by bradyb** [comment]
What should the `cirq.Pauli` result be when you're squaring?

**Comment by vtomole** [comment]
@bradyb The identity. It's not implemented in `cirq.Pauli` so i'm curious as to how we'll deal with that.

**Comment by Strilanc** [comment]
I would make the result type `Tuple[complex, Optional[Pauli]]` and use `(1, None)` to represent the identity.

**Comment by Strilanc** [comment]
The multiplication rules are quite simple; there's no need to go to the matrix arithmetic. Let r(I) be 00, r(X) be 01, r(Z) be 10 and r(Y) be 11. Then r(A*B) = r(A) xor R(b). Then you have to account for the sign of the product, which is based on the cycling direction: `s = 1j if A < B else -1j if A > B else 1`
