### ISSUE TITLE
Extend cirq.CliffordGate.__pow__ to do square roots with Clifford results

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#963]
Only need to support exponents that return Clifford results. For example, `cirq.CliffordGate.Z**0.5` should be `cirq.CliffordGate.Z_sqrt`.

**Comment by Strilanc** [comment]
Ah, good catch. Renamed issue to focus on the specific missing case.

**Comment by vtomole** [comment]
Forgot to add "closes" on https://github.com/quantumlib/Cirq/pull/1431. Please close.

**Comment by dstrain115** [comment]
Closed per vtomole.  Also added on assignee, since he did all the work!!!
