### ISSUE TITLE
Installation failed on linux - no module named cirq

### ISSUE THREAD

**Issue by marsscout22** [quantumlib/Cirq#974]
I did the exact installation steps and I got this error when I tried to verify that it is working:
python -c 'import cirq; print(cirq.google.Foxtail)'
output
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named cirq
 could you please help?

**Comment by Strilanc** [comment]
Do you have a log of the command line output during the installation?

My best guess is that you installed it in a different python environment than the one you are running (e.g. installing with pip3 then trying to run with python2).

**Comment by marsscout22** [comment]
I found out that I should activate "env" first in every time I use criq otherwise it won't work, 
Activation: by going to the working directory then type " source env/bin/activate"

Thank you @Strilanc

**Comment by vtomole** [comment]
@marsscout22 Glad you go it figured out. If you don't have anymore problems with this, may  you please close this issue?

**Comment by Strilanc** [comment]
I'll close it.

**Comment by marsscout22** [comment]
Thank you, I did not have an access to my email till now.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
