### ISSUE TITLE
Implement ThreeQubitDiagonalGate

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#980]
A three-qubit diagonal gate is a gate whose unitary matrix is of the form `np.diag([a, b, c, d, e, f, g, h])`. Such gates can be decomposed and simulated efficiently, and this decomposition/simulation code would be useful in several places (e.g. when defining the `CXXYY` gate in openfermion-cirq).

The `ThreeQubitDiagonalGate` class should have the following features:

- An `__init__` method taking the rotation angle for each element along diagonal. (The *angles*, not the complex values the angles produces. Also store the angles, not the complex values. This makes the behavior of `__pow__` better.)
- A `def _unitary_(self)` method that returns its matrix.
- A `def _circuit_diagram_info_(self, args)` method that uses symbols like `diag(a, b, ...)----#2----#3`.
- A `def default_decompose(self)` method that looks almost identical to the CCZ decomposition, except that the various T/phasing gates are replaced with gates that depend on the diagonal components of the matrix.
    - For reference, this is the CCZ code:

        ```python
        def default_decompose(self, qubits):
            """An adjacency-respecting decomposition.
    
            0: ───p───@──────────────@───────@──────────@──────────
                      │              │       │          │
            1: ───p───X───@───p^-1───X───@───X──────@───X──────@───
                          │              │          │          │
            2: ───p───────X───p──────────X───p^-1───X───p^-1───X───
    
            where p = T**self._exponent
            """
            a, b, c = qubits
    
            # Hacky magic: avoid the non-adjacent edge.
            if hasattr(b, 'is_adjacent'):
                if not b.is_adjacent(a):
                    b, c = c, b
                elif not b.is_adjacent(c):
                    a, b = b, a
    
            p = common_gates.T**self._exponent
            sweep_abc = [common_gates.CNOT(a, b),
                         common_gates.CNOT(b, c)]
    
            yield p(a), p(b), p(c)
            yield sweep_abc
            yield p(b)**-1, p(c)
            yield sweep_abc
            yield p(c)**-1
            yield sweep_abc
            yield p(c)**-1
            yield sweep_abc
            ```

    Each of the `p`s in the code controls the phasing of four of the eight diagonal entries in the matrix. By varying all 7 you can implement any diagonal matrix (up to global phase). You will have to write code to solve the actual_diagonal-to-phasing_angles problem.

- A `def _apply_unitary_to_tensor_` method that multiplies the appropriate entries by the appropriate phase values from the matrix.
     - For reference, here is how the CCZ would be implemented:
        ```python
        def _apply_unitary_to_tensor_(self,
                                      target_tensor: np.ndarray,
                                      available_buffer: np.ndarray,
                                      axes: Sequence[int],
                                      ) -> np.ndarray:
            ooo = linalg.slice_for_qubits_equal_to(axes, 0b111)
            target_tensor[ooo] *= np.exp(1j * self.exponent * np.pi)
            return target_tensor
        ```
    The code should avoid doing multiplications where the phase values equal 1.

- A `__pow__` method to extrapolate the phasing effect.
- `__eq__`/`__ne__`/`__hash__`

**Comment by bradyb** [comment]
@Strilanc what did you mean by the `#2---#3` in `def _circuit_diagram_info_(self, args)`?

**Comment by Strilanc** [comment]
It's a way of indicating the order of the other qubits in the operation. First qubit gets the name, others get numbers. This matters for operations that depend on the qubit order.

```
----op----
    |     
----#3----
    |     
----#2----
```
