### ISSUE TITLE
`Circuit.with_parameters_resolved_by` doesn't preserve layout of circuit

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#992]
Instead of appending the operations in, which can result in the operations moving around, the method needs to directly construct the moments of the new circuit.

**Comment by Strilanc** [comment]
Look into SupportsParameterization now that the magic method protocol is in place

**Comment by Ashalynd** [comment]
Is there a known example where it happened?

**Comment by Strilanc** [comment]
I think resolving `cirq.Circuit([cirq.Moment(), cirq.Moment([cirq.X(cirq.NamedQubit('q')])])` will return a circuit with one moment instead of two.

**Comment by Ashalynd** [comment]
Thanks, that was a good example!
