### ISSUE TITLE
Example algorithms from "Quantum Algorithm Implementation for Beginners" - Linear Systems

### ISSUE THREAD

**Issue by verult** [quantumlib/Cirq#996]
Problem V from https://arxiv.org/pdf/1804.03719.pdf

Implement the Harrow, Hassidim, Lloyd (HHL) algorithm as an example, first the simple instance of

<a href="https://www.codecogs.com/eqnedit.php?latex=A&space;=&space;\begin{bmatrix}&space;1.5&space;&&space;0.5&space;\\&space;0.5&space;&&space;1.5&space;\end{bmatrix}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?A&space;=&space;\begin{bmatrix}&space;1.5&space;&&space;0.5&space;\\&space;0.5&space;&&space;1.5&space;\end{bmatrix}" title="A = \begin{bmatrix} 1.5 & 0.5 \\ 0.5 & 1.5 \end{bmatrix}" /></a>

<a href="https://www.codecogs.com/eqnedit.php?latex=b&space;=&space;\begin{bmatrix}&space;1\\&space;0&space;\end{bmatrix}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?b&space;=&space;\begin{bmatrix}&space;1\\&space;0&space;\end{bmatrix}" title="b = \begin{bmatrix} 1\\ 0 \end{bmatrix}" /></a>

then a more generic version.

**Comment by verult** [comment]
I'd like to work on this

**Comment by vtomole** [comment]
Done. Please close.
