### ISSUE TITLE
Test cirq.testing.assert_equivalent_repr on every class with a __repr__ exposed by cirq

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#998]
Comes after https://github.com/quantumlib/Cirq/pull/997 (which defines the `cirq.testing.assert_equivalent_repr` method)

Basically the goal here is, for each place you can find `def __repr__(` in the project, there should be an associated test that calls `cirq.testing.assert_equivalent_repr(a, b, c) ` on a few test values.

**Comment by funston** [comment]
is this still a thing? i could give it a go if so.

**Comment by vtomole** [comment]
@funston It is. Go for it!

**Comment by Hancockan** [comment]
Assign this to me
